pcsx2-qt/Settings/DEV9SettingsWidget.cpp
pcsx2-qt/Settings/DEV9SettingsWidget.ui

The LBA48 checkbox is now disabled correctly when HDD is disabled
The DHCP Intercept label is now disabled correctly
Adjusted how the layout of the HDD section is created, ensuring the Browse and Create Image buttons are the same size
Consistency
Ensure that the LBA48 checkbox is disabled/enabled with the HDD enabled checkbox
Ensure that the DHCP Intercept label is disabled/enabled when the ethernet type is changed to/from Sockets

DEV9: Properly disable/enable labels/checkboxes in the settings UI

---

pcsx2-qt/Settings/DEV9SettingsWidget.cpp
pcsx2-qt/Settings/DEV9SettingsWidget.h

Delays the population of the ethernet devices until the network UI is visible.
No need to load this if the user might not even look at the relevant UI panel.
Maybe it speeds loading the settings widget.
Make sure the ethernet devices list is still populated in the UI

DEV9: Lazy load ethernet adapters in the settings UI

---

pcsx2-qt/AutoUpdaterDialog.cpp

Fixes a possible crash when initiating the update download before the changelog has finished fetching. Port of https://github.com/stenzek/duckstation/commit/52bdbf35dbc9a484bf2d4385a6665399a5de0a2c
Crash bad, parity with DuckStation good.
Verify that the updater works, fetches the changelog, downloads the update etc.

Qt: Fix rare crash during update download

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Try to prefer blend second pass for Ad cases on medium blend, higher levels will still prefer sw blend.
Also fix a VK compiler warning.
More brr on medium blend on dx.
Test games that got fixed with blend second pass and compare speed using medium blend master vs pr.

GS/HW: Optimize medium blend on dx.

---

bin/resources/GameIndex.yaml

Seems like the game is doing something silly with mipmapping causing it to sometimes display random garbage on the floor due to mipmapping. CSBW 1/0 seems to fix it fine so just yeet it at the CPU.
Before:
After:

GameDB: LOTR Twin Towers fixes

---

common/HeapArray.h

The non-MSVC implementation of `DynamicHeapArray<T>::internal_resize` contains a buffer overrun when the new size is smaller than the previous size, as it just performs a `memcpy(data, prev, prev_size)` without checking the size of `data`. This PR fixes the problem by using `min(size, prev_size)` instead of `prev_size`.
This issue caused a crash when changing from 128MB RAM back to the default 32MB RAM in https://github.com/PCSX2/pcsx2/pull/11111 on Linux.

HeapArray: Avoid writing out of bounds in internal_resize

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

True Crime: New York City strikes again...
A downsampling target prevents CSBW from kicking in, resulting in corruption to one of the dynamically drawn/decompressed mipmaps.
Fixes flickering/garbage texture in TC:NYC, sorry, I don't know the name of the level.
Also fixes a GPU crash I noticed when scrollwheeling resolutions.
Before:
After:
Smoke test TC:NYC.

GS/HW: Check for format combinations that make sense for CSBW

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml
.github/ISSUE_TEMPLATE/emu_bug_report.yaml

Make it clear that third-party packages are unsupported.
Packagers don't indicate that their builds are unofficial, and users get confused.
Check my wording isn't too harsh.

GH: Clarify lack of support for third-party Linux builds

---

common/Linux/LnxMisc.cpp

Apparently the Freedesktop/KDE runtime doesn't have aplay... but it does have `gst-play-1.0`, so we can use that instead.
Compatibility with Linux systems that do not have aplay.
Check achievements sound effects on Linux.

Misc: Add gstreamer fallback to aplay

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Pitfall: The Lost Expedition clears a Z24 depth buffer via a colour write, that was previously the target of a G->A channel shuffle, then uses it as a texture. We were clearing the target, despite it still having valid data in the alpha channel. So, don't do that.
Fixes #11150.
Check linked GS dump / game.

GS/HW: Ensure valid alpha doesn't get cleared on 24-bit targets

---

bin/resources/GameIndex.yaml

Fixes for Jak 1 with specific effects and reflections and for CMR 2005 with lines during intro and missing lighting.
Jak 1 Before:
Jak 1 After:
CMR 2005 Before:
After:
More fix more good.
Make sure CI Is happy boi.

GameDB: Jak 1 and CMR 2005 fixes

---

pcsx2/DEV9/AdapterUtils.cpp
pcsx2/DEV9/pcap_io.cpp

Improving logic for getting MacAddress, now it is working for Apple and FreeBSD
Previously on MacOS:
```
[   12.2374] DEV9: Opening adapter 'en0'...
[   12.2377] DEV9: Device uses DLT 1: EN10MB
[   12.2379] DEV9: Adapter Ok.
[   12.2418] DEV9: Unsupported OS, can't get MAC address
[   12.2420] DEV9: Failed to get MAC address for adapter
[   12.2422] DEV9: Failed to GetNetAdapter()
```
Now:
```
[  443.7172] DEV9: Opening adapter 'en0'...
[  443.7173] DEV9: Device uses DLT 1: EN10MB
[  443.7175] DEV9: Adapter Ok.
```

DEV9: Improve logic for getting MacAddress

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Detect triangle quads used for shuffles.
We only checked for sprites before, so this fixes that.  We do still treat it like sprites when processing further on, but it doesn't seem to matter, so YOLO.
Test Toyko Xtreme Racer Drift 2, nothing else showed in dump run.
Fixes #8203
Hard to see as it's a fade, but this is Toyko Xtreme Racer Drift 2
Master:
PR:

GS/HW: Detect shuffles using quads

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

- Round coordinates in PrimitiveCoversWithoutGaps() - fixes detection in games like God of War 2.
- Allows scaled RTA transitions on non-blended draws that fully cover the target.
- Fixes reading of P8H textures with scaled alpha by rounding.
- Renames the confusing function names.
More RTA, fewer barriers, which AMD enjoys very much.
Smoke test.
Check some sensitive games like Band Hero (menu), Ace Combat, etc.

GS/HW: Allow transition to scaled RTA on full cover draw

---

pcsx2/DEV9/Sessions/TCP_Session/TCP_Session.cpp
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session.h
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_In.cpp
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_Out.cpp

Replace C-Style casts with C++ equivalents.
Make capitalisation of text in log messages consistent.
Format comments to (hopefully) be more inline with PCSX2's comment style
Fix incorrect error check on TCP send
Add a few missing const
It may be easier to review each commit one by one rather than the whole pr at once
Improve code quality
Fix a broken error check
Test networked games using the sockets backend.

DEV9: TCP Cleanup

---

pcsx2/Counters.cpp
pcsx2/Counters.h
pcsx2/IopCounters.cpp
pcsx2/IopCounters.h
pcsx2/R5900.cpp
pcsx2/SaveState.h

Rewrites Gating functionality following hardware tests.
Gate behaviour was completely wrong in PCSX2. Did some extensive testing and modified the behaviour in PCSX2 to match the PS2.
Test CMR 2005, and any other games which ran too fast and needed EE cycle rate changes to slow it down, or things didn't happen when they should do.
Savestate version bump, sorry

EE/IOP Timers: Rewrite gate functionality

---

bin/resources/GameIndex.yaml

Adds VU1 Extra+Sign clamp to fix missing vertices on ramps.
Fixes #11160 
Before:
After:
Less broken game more good.

GameDB: Crash Nitro Kart fixes

---

bin/resources/GameIndex.yaml

Fixes missing godrays and likely other effects throughout the game.
Before:
After:
Godrays look nice.

GameDB: God of War 2 mipmapping fixes

---

pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.cpp

Apple (old BSD)'s raw IP sockets implementation converts the `ip_len` field to host byte order, but also subtracts the IP header length as well. This caused us to effectively subtract the header length twice and allocate the return ping in `ICMP_Session::Recv()` with a negative size, crashing PCSX2.
[crash log of reproduction on a Mac M-series](https://github.com/PCSX2/pcsx2/files/15158240/message.txt)
Fixes a crash which occurs in Twisted Metal Black: Online if there are any P2P game rooms whose hosts are accessible via ICMP.
This was encountered after an update to the community-run <<removed>>, which now correctly emulates and broadcasts the "game stats" field in SCERT `MediusWorldReport` packets. In TMBO specifically, this allows users in the lobby to get the IP of any room host and …

DEV9: Fix MacOS crash upon receiving an ICMP reply

---

cmake/CopyBaseTranslations.cmake
pcsx2/CMakeLists.txt

Avoids using moc's path to find *deployqt and lconvert
Qt supplies targets for all of its executables, not just moc, so use those
CMake seems to support using targets as executables in custom commands, though I wasn't so sure about what variables are available to things run from an `install(CODE` so I pulled it out for that.
Fixes building without dependencies (or some other qt installation) on your path (e.g. if using `-DCMAKE_PREFIX_PATH=DEPS_INSTALL_DIR`)
(moc installs to libexec on unix platforms, while lconvert and macdeployqt go in bin)
Try to build on various systems and make sure it still works

CMake: Don't assume all qt utils are in the same place

---

pcsx2/x86/iFPUd.cpp

Increase size of a jump in a long JIT block when using Full EE Clamping + FPU Mul hack
The code path was exceeding 0x7f (127) byes in length, causing an error.
Test SSX with full EE Clamping and the FPU Mul hack from the Game Fixes (doesn't normally need it, just a test case that hits it), make sure it doesn't crash ingame.

EE/JIT: Increase size of jump for FPU MUL with Full EE clamping

---

bin/resources/GameIndex.yaml

Adds missing GSC to GT Concept 2001 and also removes patches that are no longer needed due to being fixed by #11163 
Missing fix bad.

GameDB: Add missing GT Concept 2001 fixes

---

pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Ger rid of clr_blend1_2 condition.
Prefer sw blend instead when Alpha > 1 on Cd*(Alpha + 1) contitions when there's no overlap
on basic blend.
Make sure when a draw is rta scaled for blend second pass.
Implement dithering on blend second pass on some formulas.
Alpha = As or Af Cs + Cd*Alpha, Cs - Cd*Alpha.
Other formulas will do dither on first pass only, it's probably wrong, maybe less, but was also wrong doing both passes, something to think about in the future and if it can be improved, just don't wanna bother with it now.
Accuracy.
Test Battlefield 2, Midnight club

GS/HW: More blend improvements.

---

pcsx2/Counters.cpp
pcsx2/IopCounters.cpp

Fix up some timer behaviour on EE and IOP
Introduced a bug in the previous PR by accident, realised that if the game didn't update gated counters before hsync/vsync and the counter got reset, it would retain the old value.
Also tested HSync timing on the PS2, and corrected it in PCSX2.
test hsync timing sensitive games, i guess.  No known fixes.

Timers: Fix up some timer behaviour

---

.github/workflows/scripts/linux/build-dependencies-qt.sh

Apparently I forgot these when cleaning up..
Not hitting server with invalid links.
CI passes.

CI/Linux: Remove invalid download links

---

pcsx2/SPU2/Reverb.cpp

Fixes spurious SPU IRQ's that trip up Colin McRae 2005
Hardware tested.
Check if Nicky still has a stutter.

SPU: Only fire IRQ for Reverb reads when FxEnable

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Accidentally purged the second half of the `blend_mix1` condition, which leads to broken overbright blending in a handful of games.
Regression from #10991.
Briefly check affected games, like Driver 3.

GS/HW: Fix blend_mix regression

---

pcsx2/DEV9/sockets.cpp
pcsx2/DEV9/sockets.h

Defer deleting the closed session until the end of the send/recv call
Turns out, this did cause issues (certain UDP sessions was crashing debug builds when closing)
Maybe there is a better way to do this
Test networking games

DEV9: Defer deletion of socket sessions

---

3rdparty/simpleini/include/SimpleIni.h
common/FileSystem.cpp
common/FileSystem.h
common/HeapArray.h
common/MemorySettingsInterface.cpp
common/MemorySettingsInterface.h
common/SettingsInterface.h
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2-qt/SettingWidgetBinder.h
pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/ControllerBindingWidgets.cpp
pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp
pcsx2-qt/Settings/ControllerSettingWidgetBinder.h
pcsx2-qt/Settings/ControllerSettingsWindow.cpp
pcsx2-qt/Settings/ControllerSettingsWindow.h
pcsx2-qt/Settings/SettingsWindow.cpp
pcsx2-qt/Settings/SettingsWindow.h
pcsx2/Config.h
pcsx2/INISettingsInterface.cpp
pcsx2/INISettingsInterface.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/LayeredSettingsInterface.cpp
pcsx2/LayeredSettingsInterface.h
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

When modifying game settings, it's pretty easy to end up with a file full of empty sections. That's a bit messy.
This PR makes the interface clean out empty sections, as well as removing empty gamesettings files completely if no settings are changed.
And a couple of other random tidy-ups.
Less mess in `gamesettings` directory.
Test game settings. Make sure files are created, and get removed when the last changed setting is reset.
Make sure input profiles are still creatable and editable.
Make sure speed limiter and fast forward boot still works as expected.

Qt: Clean and remove empty game settings

---

3rdparty/simpleini/LICENCE.txt
3rdparty/simpleini/include/ConvertUTF.h
3rdparty/simpleini/include/SimpleIni.h
3rdparty/simpleini/src/ConvertUTF.c

Updates simpleini to the latest release v4.22.
The last release we used was from 2013 that's old.
Make sure settings load correctly.

3rdparty: Update simpleini to v4.22

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/AudioSettingsWidget.ui

This PR fixes the wrongly labeled Reset Volume button.
Before:
After:
Correctness 100
See if the button is correctly labeled.

Qt: Fix incorrectly labeled Reset Volume button

---

pcsx2-qt/Settings/DEV9UiCommon.cpp
pcsx2-qt/Settings/DEV9UiCommon.h

Make `IPItemDelegate` Inherit from `QStyledItemDelegate` instead `QItemDelegate`
`QStyledItemDelegate` better respects the selected theme
This corrects the selection highlight for the `Address` field in the `Internal DNS` host list on the Windows 11 Native theme.
Other themes may also have be affected.
Old
New
Make sure the style of the `Address` field in the Internal DNS host panel matches the style of the other fields (and then rest of the window)

DEV9: Inherit from QStyledItemDelegate for Address fields in DNS hosts table

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/AudioSettingsWidget.ui

Adds an ms label next to the buffer slider backported from Duckstation.
Labels are helpful.

Qt: Add label next to audio buffer size

---

.github/workflows/scripts/linux/flatpak/modules/20-sdl2.json
cmake/SearchForStuff.cmake
common/CrashHandler.cpp
common/CrashHandler.h
common/DynamicLibrary.cpp
common/DynamicLibrary.h
common/Error.cpp
common/HostSys.h
common/Linux/LnxHostSys.cpp
common/Windows/WinHostSys.cpp
pcsx2-qt/Settings/GameListSettingsWidget.cpp
pcsx2-qt/Settings/GameListSettingsWidget.h
pcsx2-qt/SetupWizardDialog.cpp
pcsx2-qt/SetupWizardDialog.h
pcsx2/vtlb.cpp

- Bumps SDL version for Flatpak, since both Jordan and I forgot about it.
- Simplifies the page fault handler logic, also provides the host with whether it was a write or read.
- Stops the crash handler from leaking zombie PCSX2 processes when it crashes. Hopefully this'll fix the random "permission denied" error some users get when updating.
- Fix remove game directory/excluded path tool button being enabled without a selection.
See above.
Make sure games still boot.
Make sure when adding/removing a game/exclusion directory, the remove button behaves as expected.

Misc: More DuckStation backports

---

.gitignore

Adds `/deps-build` to gitignore
vscode complains about the number of changes if you have open while building dependencies
`git status` while building dependencies

gitignore: Add deps-build path

---

pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.h
pcsx2/DEV9/Sessions/UDP_Session/UDP_Session.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_Session.h
pcsx2/DEV9/sockets.cpp

Replace C-Style casts with C++ equivalents.
Make capitalisation of text in log messages consistent.
Format comments to (hopefully) be more inline with PCSX2's comment style
Simplify closing of UDP sockets slightly,
Improve handling of sent multicast packets
Improve error handling when creating certain UDP connections
It may be easier to review each commit one by one rather than the whole pr at once
Improve code quality
Better error handling
This ended up picking up more changes then I had intended, I can split this into separate PRs if that makes this easier
Test networked games using the sockets backend.

DEV9: UDP Cleanup + Various fixes

---

pcsx2/CDVD/CDVD.cpp
pcsx2/IopBios.cpp
pcsx2/IopBios.h

This PR adds handling for `host%d:` device paths and the host root in `cdvdLoadElf`. A new `Path::IsDevicePath` API is provided to simplify checking for these paths (it is essentially a generalized version of `is_host` from IopBios.cpp). I have not changed other code that manually checks for things like `"cdrom:"` and `"cdrom0:"` because I felt it was out of scope for this PR and I'd rather explore that after getting some feedback.
The current implementation of `cdvdLoadElf` only checks for `host:`, so it does not handle `host0:` requests. Additionally, it does not take the host root path into account, meaning `LoadExecPS2("host0:file.elf", 0, NULL)` can fail due to the ELF not being found.
1. Download [cdvd-host-elf.zip](https://github.com/PCSX2/pcsx2/files/15212368/cdvd-host-elf.zip)
2. …

CDVD: Improve handling of host: paths in cdvdLoadElf

---

pcsx2/CMakeLists.txt
pcsx2/Config.h
pcsx2/DEV9/InternalServers/DHCP_Logger.cpp
pcsx2/DEV9/InternalServers/DHCP_Logger.h
pcsx2/DEV9/net.cpp
pcsx2/DEV9/net.h
pcsx2/Pcsx2Config.cpp
pcsx2/pcsx2.vcxproj
pcsx2/pcsx2.vcxproj.filters

Adds an option to enable logging of DHCP traffic
Games and homebrew can sometimes fail to get a correct IP via DHCP when TAP or pcap is used
Open`PCSX2.ini` 
Replace `EthLogDHCP = false` with `EthLogDHCP = true`
If the entry is missing, insert it under `EthDevice`
Run an online game and inspect the log

DEV9: Add a DHCP Logger

---

pcsx2/x86/iCOP0.cpp
pcsx2/x86/ix86-32/iR5900.cpp

Corrects cycle masking when a block has a low cycle count while overclocking.
The mask to retain fractional values was different to what was actually being used when the cycle count was low, causing the cycle count to be wrong. This regressed Panzer Elite Action - Fields of Glory
I also removed the hack from MFC0 where it was fudging adding a cycle to the COP0 counter, this was wrong.
Try Panzer Elite Action - Fields of Glory, and any other games which use overclocking in the gamedb, don't care too much about others.
Fixes #4793

EE: Correct update of EE cycles on low cycle counts when overclocking

---

pcsx2/VMManager.cpp
pcsx2/x86/ix86-32/iR5900.cpp

This PR makes two changes:
* `mmap_ResetBlockTracking` now uses `TotalRam` instead of `ExposedRam`
* `VMManager::Reset` now calls `mmap_ResetBlockTracking` before `SysMemory::Reset` is called
`mmap_ResetBlockTracking` is supposed to clear _everything_, so it probably makes more sense for it to use `TotalRam` rather than `ExposedRam`. It is now called from `VMManager::Reset` to fix a crash that occurs when the VM is reset after disabling expanded memory if the program has executed code in high RAM. PCSX2 will AV [here](https://github.com/PCSX2/pcsx2/blob/5f7e97c27c966059ba80e93ba800ae5fc0398de3/pcsx2/Memory.cpp#L1160) when trying to clear `eeMem`, because it has leftover read-only page protection flags from the previous session.
1. Download …

VMManager: Clear protected pages when resetting VM

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Optimize sw/hdr colclip on some blend formulas.
Alpha is either As or Af.
`Cd*Alpha, Cd*(1 - Alpha).`
When Alpha <= 128 we can let hw blend do it's thing as it won't be able to wrap.
Brrr, less draw calls, copies, barriers.
Helps Sly 2, Big Mutha Truckers, Lord of the rings Third age, so test these games.
```
Big Mutha Truckers_SLUS-20291_20230214212340 ['Barriers: -2 [39=>37]']
Big.Mutha.Truckers ['Barriers: -2 [134=>132]']
Lord of the Rings, The - The Third Age_SLES-52801_20230919222807 ['Draw Calls: -2 [44=>42]', 'Render Passes: -1 [16=>15]', 'Copies: -1 [8=>7]']
Lord_of_the_Rings_The_-_The_Third_Age_SLES-52801_20230707223226 ['Draw Calls: -2 [189=>187]', 'Copies: -2 [8=>6]']
Lord_of_the_Rings_The_-_The_Third_Age_SLUS-21027_20230404183506 ['Draw Calls: -2 [150=>148]', 'Render …
```

GS/HW: Optimize sw/hdr colclip on some blend formulas.

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Apparently Bee Movie hits this.
No diffs changed, though.
Spec violationssss
Smoke test

GS/HW: Fix incorrect StretchRect() in double buffer copy

---

pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSRenderer.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

**GS: Fix use-after-free on lost device**
- Stops PCSX2 accessing freed memory on device loss. I mean, we're probably going to flop anyway since it's just going to crash the GPU again, but use-after-frees are bad.
**GS/HW: Fix invalid self copy from move in DX renderers**
- Spec violation in DirectX.
**GS/HW: Fix possible texture leak on skipped draw**
- Temp targets don't get cleaned up. Also very unlikely, but avoids a `goto` here.
Correctness
Smoke test because who cares about directx anyway

GS: Misc fixes

---

pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

So I bought a 7900GRE to debug this issue and...
It turns out *not* doing this causes GPU resets on RDNA3, specifically Windows drivers. Despite the layout changing enforcing the execution dependency between previous draws and the first input attachment read, it still wants the region/fragment-local barrier...
(Hopefully) Fixes the RDNA3 crashes.
Fixes #10720.
Smoke test Vulkan renderer.
See if RDNA3 no longer crashes.

GS/Vulkan: Always issue first barrier on RDNA3

---

pcsx2/USB/usb-pad/usb-pad.cpp

This change adds four d-pad directions to the `RBDrumKitDevice` USB pad, which bind to the `CID_DPAD` directions. This automatically is exposed in the Qt UI, and input can then be provided to games that support this controller.
The Rock Band drum kit currently has bindings only for the four pads, the kick pedal (which is named Orange), and the Start and Select buttons. The kit however contains additional buttons, and of note for this PR, the d-pad.
Rock Band supports menu navigation with the d-pad as well as also using the yellow and blue pads. Guitar Hero, however, does not support menu navigation any other way, which means games such as Guitar Hero World Tour cannot be played fully.
Adding these d-pad controls allows players to operate the menus using the required inputs.
With this …

USB: Add d-pad controls to RBDrumKitDevice

---

pcsx2/ImGui/FullscreenUI.cpp

Automatically hide advanced graphics settings on BPM depending on global advanced settings visibility.
Forgot about it when i added the functionality on Qt
Closes #11239 
Consistency 100
Test the functionality, toggle the global advanced settings option and see if the advanced graphics settings section gets hidden.

FSUI: Automatically hide advanced graphics settings

---

pcsx2/SaveState.cpp

This PR attempts to simplify the incompatible savestate warning message to be more easily understandable and digestible.
Preview:
Hoping that people would actually read the message.
Check if the message shows up properly.

Qt: Simplify incompatible savestate message

---

pcsx2/CDVD/CDVD.cpp
pcsx2/CDVD/CDVD.h
pcsx2/Counters.cpp
pcsx2/Counters.h
pcsx2/GS.cpp
pcsx2/GS.h
pcsx2/IopCounters.cpp
pcsx2/IopCounters.h
pcsx2/IopDma.cpp
pcsx2/R3000A.cpp
pcsx2/R3000A.h
pcsx2/R5900.cpp
pcsx2/SPU2/Dma.cpp
pcsx2/SPU2/spu2sys.cpp
pcsx2/SaveState.cpp
pcsx2/SaveState.h
pcsx2/ps2/Iop/IopHwRead.cpp

Refactor timers a bit to be a little less gross and more readable, also fix a couple of bugs.
There was a bunch of repeated code and legacy naming which wasn't obvious to what it was, which I wanted to sort out.
Also fixed the slight inaccuracy of counting time for framerates which weren't whole numbers.
Correct start cycles so they are on clock tick boundaries.
Disable sending V/H sync interrupts etc when SINT (this is the PCRTC initialization mode)  is enabled, nothing happens during this sequence on a PS2.
Test a whole bunch of things, make sure everything is fine.
Unfortunately I don't think anything is fixed :(
Double unfortunate this required a savestate bump.

Core: Refactor a lot of timer work and fix a couple of bugs

---

pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
pcsx2/GS/Renderers/SW/GSNewCodeGenerator.h

Replaces reciprocal Q with normal ST/Q division.
the original method is quite inaccurate, especially when you're dealing with interpolation and is just not adequate.  Sten mentioned that it's likely that there would be a stall with the original multiplication anyway, so the performance difference is negligible. But this fixes a bunch of problems. Faster isn't better if it breaks things.
Test games listed below in SW or any you know that have SW only issues. I've checked Armored Core's radar and GOW's controller screen, plus the lines problem in Mercenaries and Klonoa 2, Crash Twinsanity's weird pixels on curves.
Fixes #3295 Metal Gear Solid 2 Locker
Fixes #4825 Spider-Man 3 texture issues
Fixes #6156 Corrects Castlevania map in software mode (Hardware was already fixed)
Corrects #9151 …

GS/SW: Don't use fast reciprocal stq calculation, it's too inaccurate

---

pcsx2/R3000A.cpp
pcsx2/R3000AInterpreter.cpp
pcsx2/R5900.cpp
pcsx2/x86/iR3000A.cpp

Adjusts the IOP cycle count slightly more accurately with the EE.
It was very wrong in PS1 mode, this is still wrong, just by a fraction of a cycle per block instead of 1 cycle per 3 instructions.
Make sure nothing explodes.

IOP: Adjust cycle counts slightly more accurately in some situations

---

pcsx2/R3000A.cpp
pcsx2/R3000A.h
pcsx2/R3000AInterpreter.cpp
pcsx2/SaveState.h
pcsx2/x86/iR3000A.cpp

Gotta be deterministic.
I didn't add it in for the patch #11253 because it was 2am.
Check (grumbles) PSX mode.

R3000: Serialize IOP->EE ticks carry

---

.github/workflows/scripts/linux/appimage-qt.sh
pcsx2/CDVD/CsoFileReader.cpp
pcsx2/CDVD/GzippedFileReader.cpp

Fixes an inverted assertion in the CSO reader, and the gzip reader crapping out at the end of some files.
Re-bundles libssl since it didn't help #11230.
Regressions from #11258.
Already tested, CI passes.

CDVD: Fix my regressions

---

.github/workflows/linux_build_flatpak.yml

pcsx2.net (cloudflare?) appears to be blocking the GitHub runner. Until this is resolved, disable runner-side validation.
Builds failing.
See what CI says.

CI/Flatpak: Temporarily disable repo/appstream validation

---

bin/resources/GameIndex.yaml

Switches KH2 roundSprite mode to half to fix a graphical upscaling artifact.
https://github.com/PCSX2/pcsx2/issues/11265 reported tearing-like issues that didn't seem to happen in previous revisions when upscaling KH2. Bisecting led me to https://github.com/PCSX2/pcsx2/pull/7545 , which fixes other upscaling issues with KH2, but also introduces this graphical bug.
Switching roundSprite to half seems to fix the bug while not introducing other obvious ones (eg, Mulan's cutscene as shown in @JordanTheToaster 's PR works fine under half mode.
See if anything in KH2 breaks pretty much, as I didn't see any discussion as to why we used full rounding in the past, this might break something I'm unaware of. Nevertheless opening this PR to at least talk about it.

GameDB: fix tearing like issues on KH2 when upscaled

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/ImGui/FullscreenUI.cpp

This PR cleans up the texture replacement settings section by re-arranging the checkbox to be more fitting, and disabling related option depending on the main toggle.
Preview:
https://github.com/PCSX2/pcsx2/assets/14798312/3a0b6d83-10b3-42c3-b956-0d2820f888b5
Eyecandy and usability 100
Check the functionality, see if the options are properly disabled.

Qt: Tidy up texture replacement settings

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Adjusts the conditions for CPU sprite renderer triggering.
Some games like Spider-Man 3 and Driv3r require a high level of software drawing to fix some issues, but break other things as a result as they need the information in the render target, however these draws don't really the software renderer to be successful.
Test Driv3r and Spider-Man 3, Wall-E, Jak 3, Jak-X Combat Racing and some random stuff.
Jak and Daxter - The Lost Frontier's upscaled shadow that was fudged with the software sprite renderer is no longer fixed by it, it's a casualty, but what can you do.
Driv3r:
Master:
PR:
Spider-Man 3 (with the higher sprite level required for some upcoming changes in #11241 ):
Master:
PR:
Jak-X Combat Racing:
Master:
PR:
Wall-E:
Master:
PR:

GS/HW: Adjust conditions for CPU sprite renderer

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/SIO/Pad/Pad.cpp
pcsx2/VMManager.cpp

Always enable full mipmap with ps2 trilinear by default.
Change mipmap option from a drop down to a bool with on off option only, remove automatic and basic options.
TODO for the future: remove support of trilinear and mipmap from db.
Accuracy, less hassle to keep adding gamefixes, instead we will add gamefixes to force disable mipmap on some games that break.
Test variety of games that use mipmap + triliear, make sure to disable gamefixes .
DB list needs to be updated.

Misc: Always enable full mipmap with ps2 trilinear by default

---

pcsx2/GS/GSState.cpp

Increases sensitivity of tex_flush when autoflushing.
There is some very slightly discrepancies which don't get picked up, causing Jak to have puppet lines in software.  This will cause autoflush to happen more often in some situation but not much can be done about it right now without breaking stuff.
Test Jak II in software mode, make sure the shadows are okay.

GS: Increase sensitivity of texflush but avoid some situations

---

common/Linux/LnxHostSys.cpp

MAP_FIXED will clobber any existing memory mapping, and is not safe to use in a multi-threaded environment. Whether we like it or not, we are a multi-threaded environment, because Qt initializes before we get to main(), so it's already too late to safely use MAP_FIXED by the time we get there.
Use MAP_FIXED_NOREPLACE instead. This is how MAP_FIXED should have behaved from the beginning.
Obviously this means you'll need Linux 4.17+ and a semi-recent libc to use PCSX2 now. But if you're running a 6 year old unsupported kernel, you have bigger problems.
Fixes "random" startup crashes on Meme Linux.
Try to crash PCSX2 by repeatedly shutting down+restarting the application.

Common: Don't use MAP_FIXED on Linux

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Don't care about alpha on double half clear if the game isn't using it, or it's all black (as the clear is writing on the Z)
Tony Hawk Pro Skater 4 does this clear with the alpha masked, but Z32 for the bottom half (so writes to alpha area). Normally we avoid this because it's not really acceptable for a double half clear, but in this case, the game isn't actually using the alpha, and so it's black, so writing to it doesn't really matter.
Test Tony Hawk Pro Skater 4 and look for some water, put it in the lower half of the screen.
Master (this did just multiply before until it was as bright as the sun:
PR:

GS/HW: Ignore alpha on double half clear if not used

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes Jak
I broke Jak
Test Jak

GS/HW: Restrict CPU Sprite abort to non-opaque draws

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Null pointer dereferences, constants, redefinitions.
Cleaner code.
Dump run shows no diffs, smoke test.

GS/HW: Cleanup RendererHW.

---

common/Linux/LnxHostSys.cpp
pcsx2-qt/AutoUpdaterDialog.cpp

Corrects type for stub implementation of `AutoUpdaterDialog::processUpdate()`
Define `MAP_FIXED_NOREPLACE` as `MAP_FIXED | MAP_EXCL`, which should serve the same purpose
Some socket code is common between Mac and FreeBSD, but not Linux.
Setting up a FreeBSD VM for testing is cheaper then getting a Mac (I mean, it's in the name)
It's still a bit of effort compile for FreeBSD, In addition to this PR you would need to deal with the following issues;
Qt with Multitouch fails to compile, due to code intended to support FreeBSD you can do one of the following;
Disable Multitouch with `-no-mtdev` or apply the same Qt [patches](https://cgit.freebsd.org/ports/tree/devel/qt6-base/files) FreeBSD's port does.
cpuinfo doesn't support FreeBSD
Locally apply either …

Some small fixes for FreeBSD

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ShaderCacheVersion.h

Adds a new option to override dithering and force 32bit pixel depth
Disabling dithering stuff truncates colours to 16bit which causes some gross banding.  Disabling dithering *can* force 32bit, but if there's any software blending (which we do a lot), it will bypass it.
Try the new option, most obvious with high blending settings.
Off:
Force 32bit:

GS/HW: Allow forcing Dither to 32bit for 16bit draws

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/SettingsWindow.ui

Fixes description content for dithering, and resizes the box so 4 lines actually fits without a scroll bar.
Wrong descriptions are gross, scroll bars are gross. Gross.
Quickly check the dithering description in the settings make sure all is fine and dandy

UI: Fix dithering description + make it so 4 lines of description fits

---

pcsx2/Input/InputManager.cpp

Backport of https://github.com/stenzek/duckstation/commit/a7f2ad37de936d68e8881aa6878e91ed213d228a
Fixes the activate menu button from being forwarded to the game after the menu is closed.
Test pressing the menu activate button (e.g. enter or X/A on controller) with it also bound to a PS2 controller button. Input shouldn't be forwarded to game anymore.

InputManager: Fix exit menu button forwarding to game

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/GS/Renderers/Vulkan/VKSwapChain.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

Apparently some users like additional input lag, and more inconsistent frame timings (the "old" behaviour for vsync). So give them the option for the worse experience. While we're at it, purge threaded presentation, since it provides no benefit now.
For those who want to argue:
Mailbox enabled:
Mailbox disabled:
See how QF = 1, this means that there's an additional buffered frame by the EE (=> 1 more frame of input lag). It does periodically drop back to 0, then back to 1 again, because like I keep saying, refresh rates are mismatched.
Purgey purge.
Make sure Vulkan frame timing is fine on NVIDIA.
Test VK+DX with mailbox disabled.

GS: Add option to disable mailbox presentation / purge threaded presentation

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fixes fade transitions when upscaling in GT3.
I wrote terribly incorrect code last year.
Check GT3/GT4 with upscaling.
~~Still need to dump run.~~

GS/HW: Fix unscaled rect in CopyRGBFromDepthToColor()

---

pcsx2/CMakeLists.txt

Fixes errors about MoltenVK not getting signed 
Things building successfully is generally preferred
Attempt to build an Xcode project generated with `cmake -G Xcode` (tested)

CMake:macOS: Tell Xcode to sign with `--deep`

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

Inverts a check to match the Vulkan renderer, which I apparently broke when I originally copied it back in #8859
(Also adds to the debug name)
Less broken
Test [ApeEscape2-LOD.zip](https://github.com/PCSX2/pcsx2/files/15478940/ApeEscape2-LOD.zip)

GS:MTL: Fix inverted UseMipmapFiltering check

---

common/Darwin/DarwinMisc.cpp
common/Linux/LnxHostSys.cpp

MacOS does not support an equivalent of MAP_FIXED_NOREPLACE via mmap(), which means that our usage for allocating PCSX2's memory map is not thread-safe.
#11282 fixed this for Linux, this PR implements it for MacOS.
I'll follow up later with a signal handler tidy-up, that way we can skip compiling everything in the Linux/ directory on MacOS.
Preventing a race condition that can cause memory corruption in PCSX2 on startup, while it allocates its memory map.
Make sure Mac builds still boot.
@TellowKrinkle I've tagged you for review in case you know anything about these system calls. Apple's documentation is all blank pages, I ended up using the published XNU source as a reference...

Common: Use Mach VM routines for memory mapping

---

3rdparty/include/vk_mem_alloc.h

Updates VMA to the latest release 3.1.
We already used 3.1 dev so might as well just bump to the latest numbered version.
Make sure Vulkan doesn't crash horribly because that would be bad.

3rdparty: Update to VK memory allocator 3.1

---

pcsx2/DEV9/AdapterUtils.cpp
pcsx2/DEV9/AdapterUtils.h
pcsx2/DEV9/Win32/tap-win32.cpp
pcsx2/DEV9/pcap_io.cpp
pcsx2/DEV9/sockets.cpp

Merge code related to getting a network adapter.
Corrected the buffer type used for `GetAdaptersAddresses()`, as other structures where also placed in there.
Replace C-Style casts with C++ equivalents.
It may be easier to review each commit one by one rather than the whole pr at once
This effort was mostly born this https://github.com/PCSX2/pcsx2/pull/10937#discussion_r1560557998, regarding type punning
The socket api does not make it easy to avoid UB type punning, due to strict aliasing rules, The general consensus appears to be that these types are passed in an aliased form and we just cast back to get the true type.
Test connection with pcap. sockets and tap
Test the above (where supported) on Windows, Linux and FreeBSD/Mac

DEV9: Adapter Utils Cleanup

---

cmake/BuildParameters.cmake
common/vsprops/common.props
pcsx2/GS/Renderers/SW/GSNewCodeGenerator.h

Instruct MSVC to use its newer preprocessor, which has better standards conformance
Remove the preprocessor hack present in `GSNewCodeGenerator.h`
I had switched to the new preprocessor as I had wanted to use `__VA_OPT__` on the macros in pcap
That ended up being not really worthwhile, however, I had noticed that GS  `GSNewCodeGenerator.h` had a hack for the old preprocessor.
May as well have each compiler's preprocessor behave the same, and remove this hack.
Test MSVC Builds

GS: Remove MSVC macro hack and use MSVC's new preprocessor

---

.github/workflows/scripts/linux/appimage-qt.sh

Hasn't been needed for some time, apparently I forgot to remove it here.
Ever so slightly smaller downloads.
Make sure crapimage still runs.

CI/AppImage: QtNetwork is no longer needed

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Improve target selection on tex in rt and improve detection of targets to be deleted.
Just the way some games do things confuses the TC, this improves it
Test games below, make sure everything is okay. Any Tex in RT games are probably a good shout too (including Valkyrie Profile 2)
Master:
PR:
Master:
PR:
Master:
PR:
Master:
PR:
Master:
PR:
Master:
PR:
Master:
PR:

GS/HW: Favour newer draw on source overlap + improve target overwrite

---

pcsx2/GS/Renderers/Metal/GSMTLDeviceInfo.mm

Sets slow_color_compression for Intel HD 4000s, which makes us add `MTLTextureUsagePixelFormatView` to them.  Apparently they're really slow without it, at least in our sample size of one OCLP Big Sur Mac mini.
Not sure why this does anything at all, as [texture compression is only supported on Skylake+](https://gitlab.freedesktop.org/mesa/mesa/-/blame/c572adceaa493ab2f7b6cad6d6bd100c6d93ff4d/src/intel/isl/isl_format.c#L88) (and only on Icelake+ in a way Metal can use due to its allowance of reinterpreting between sRGB and non-sRGB textures even on non-PFV textures), but apparently it does something and that something makes things faster
Makes Metal renderer not slower than MoltenVK on Intel HD 4000
@MajmunX can you verify that this makes Metal fast without having to run with …

GS:MTL: Add Intel HD 4000 to the list of GPUs to use PixelFormatView on

---

bin/resources/GameIndex.yaml

Fixes ghosting in all Tokyo Xtreme Racer Drift/Kaido Racer/Kaido Battle games during Rainy/Stormy weather where applicable.
**Tokyo Xtreme Racer: Drift/Kaido Battle**
Before
After
**Kaido Racer/Kaido Battle 2**
Before
After
**Tokyo Xtreme Racer: Drift 2/Kaido Battle 2**
Before
After
Clearer picture!
Test the games if something isn't broken. I have already 100%'d both TXRD1/2 with those fixes and all seemed fine to me.

GameDB: Tokyo Xtreme Racer Drift/Kaido Racer - Upscaling fixes

---

pcsx2-qt/MainWindow.cpp

Use `QDir::toNativeSeparators()` to convert directory separators from `/` to `\` on Windows when opening a file for input playback
`QFileDialog` returns paths with unix slashes.
Windows would normally be able to handle paths with unix slashes, except when paths that are prefixed by `\\?\`, (which we do for longer than MAX_PATH support).
Convert the path to use native separators (so `\` on windows) to allow the to be prefixed path to work.
Fixes https://github.com/PCSX2/pcsx2/issues/11060
Open an input recorded file and see if it plays.

input-rec: Use `toNativeSeparators()` when opening recording

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSState.cpp

Checks gradient of draw to if it should use inclusive edges of textures
Before it was always on causing silly expansion of textures and missing lookups because they went outside of the texture.  The rects are technically already inclusive, but depending on the gradient it may need a bit more, so this checks the gradient before calculating the boundaries. Mobile Suit Gundam was copying the screen in strips and the last strip was trying to grab 65x225 instead of 64x224, so the tex in rt check was saying it was out of bounds.
As a result a bunch of copies no longer happen, or uploads, or resizes, which is always good. Raw Danger seems to run better than master, I actually get a playable speed.
Test random stuff make sure everything is peachy, and Mobile Suit Gundam - One Year War listed …

GS: Don't be inclusive of textures edges in all cases

---

.github/workflows/windows_build_qt.yml

temp fix the clang cmake builds until the action runner gets fixed. See [#10001](https://github.com/actions/runner-images/issues/10001)
Runner broked.
Watch runner

CI: Tempfix windows clang builds

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Takes the render target end block if bigger than calculated end on channel shuffle
Source isn't a perfect source of truth, if it's not drawn the entire size of it the end block may be incorrect.  We kinda cheat with channel shuffles anyways, so if the render target end is larger, assume that ending.
Test Mercenaries (already done)
Master:
PR:

GS/HW: Take render target end block for channel shuffles if bigger

---

.github/workflows/scripts/windows/build-dependencies.bat
.github/workflows/scripts/windows/qtbase-disable-pcre2-jit.patch

Backport of https://github.com/stenzek/duckstation/commit/daed75de20e8d533bf0ef3a53b314780ba1d136e
For some reason that I can't be bothered to debug, the AVX2 detection in PCRE2 doesn't behave correctly in a VM that has `xsave` disabled via `bcdedit`, which is the only way I have of testing SSE4 builds.
So just disable the JIT instead, it's not like we're heavily using regexp.
Make sure it still runs.

CI/Windows: Disable Qt's PCRE2 JIT

---

3rdparty/xbyak/xbyak/xbyak.h
3rdparty/xbyak/xbyak/xbyak_mnemonic.h
3rdparty/xbyak/xbyak/xbyak_util.h

Updates to latest xbyak release.
Might fix https://github.com/PCSX2/pcsx2/issues/11345 a crash on older AMD CPUs apparently.
Make sure nothing explodes.

3rdparty: Update xbyak to 7.06

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Corrects TEXA usages on shuffles
Order of operations was a little backward here, it was being added *after* blends and modulation when it was a shuffle, which makes no sense, but also AEM was non-functional, snoopy relied on this behaviour for converting the depth to a fog effect.
Normal testing, plus the two dumps in the archive below, especially Metal.
[testdumps.zip](https://github.com/user-attachments/files/15569901/testdumps.zip)
Fixes #5240 Snoopy last outstanding issue.
Master:
PR:

GS: Correct TEXA behaviour on shuffles

---

pcsx2/GS/Renderers/Metal/tfx.metal

Fixes tex is fb + depth texture on the Metal renderer
Less broken
Test [OutRun_2006.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/12908672/OutRun_2006.gs.xz.zip)

GS:MTL: Fix handling of tex is depth fb

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Tools/InputRecording/InputRecordingViewer.cpp

Use `QDir::toNativeSeparators()` to convert directory separators from / to \ on Windows when opening a file for input playback
Also adds a message box when we are unable to open the file
I saw it mentioned in the discord that this was also broken
See #11332 for the need to use `QDir::toNativeSeparators()`
Provide a message box to make the failure clear (also this was mentioned as a TODO in the recording viewer)
Open a recording in the input recording viewer and see if it loads.

input-rec: Use toNativeSeparators() when using the recording viewing

---

pcsx2/GS/MultiISA.cpp
pcsx2/GS/MultiISA.h

Consistency with checking CPU features. We use cpuinfo in VMManager.
Make sure builds run on AVX2 and SSE4.

GS: Swap to cpuinfo for checking CPU features

---

pcsx2-qt/VCRuntimeChecker.cpp
updater/CMakeLists.txt
updater/updater.vcxproj
updater/updater.vcxproj.filters

Add VC runtime checker to the updater
So it warns user that try to run the new version.
Run the updater with an old VC Runtime installed.

Updater: Add VC Runtime check

---

pcsx2/ImGui/ImGuiFullscreen.cpp

Backport from https://github.com/stenzek/duckstation/commit/bac2ac01513ee8082768f999df1a9b54389a75bf
Scrollbars are evil.

FullscreenUI: Fix incorrect padding calculation in pause menu

---

pcsx2-qt/Debugger/Models/BreakpointModel.cpp
pcsx2/DebugTools/DisassemblyManager.cpp

Disassembly is a pain point. There are multiple disassembler interfaces, and the "good" one we don't even use properly.
I've disabled another heuristic to prevent pseudo ops like `li`,
Fixes: #10702 
See if pseudo instructions such as `li` shows up in the disassembly widget, or in the breakpoint listing.

Debugger: Disable pseudo ops

---

pcsx2-gsrunner/Main.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSVector4i.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
pcsx2/GS/Renderers/SW/GSTextureCacheSW.cpp

Replaces a few non-immediate constant shifts with the templated version.
Adds `rcontains()` and `rintersects()` helpers.
Removes `runion_ordered()`, and replaces `runion()` with the previous "ordered' version. All our rects are, well, rects, and thus ordered.
Adds `geNN()` and `leNN()` methods.
Needed for Apple Silicon.
Smoke test hardware and software renderers.
HW dump runs fine, SW is acting.... strange. Need to look into it further.

GS: GSVector maintenance/tidyup

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Cd*(1 + Alpha).
Alpha = As, Ad or Af.
For As or Af case when alpha > 128.
For Ad case when there is no RTA correction.
Accuracy.
Test the listed dumps:
There shouldn't be any diffs or minimal since the alpha isn't higher than 128 in these games.
Found a few where it is higher than 128 but with overlap so won't help in those cases.

GS/HW: Extend blend second pass to more blend formulas v2.

---

pcsx2/DEV9/PacketReader/ARP/ARP_PacketEditor.cpp
pcsx2/DEV9/PacketReader/ARP/ARP_PacketEditor.h
pcsx2/DEV9/pcap_io.cpp
pcsx2/DEV9/pcap_io.h

More strictly enforce MTU of packets received using pcap
The previous limit was not strict enough, allowing 'small' jumbo frames to be received.
This was causing TLB misses and other issues in some homebrew software, due to what appeared to be a buffer overrun.
Test pcap backend on network games and homebrew (that receive large packets).
Testing should be performed in a network that supports an MTU > 1500
Testing in networks that have an MTU == 1500 would be useful to ensure we aren't too strict.
~~I currently assume that libpcap dosn't capture the etherframe FCS
This might not be the case on FreeBSD or MacOSX, as libpcap, so specific testing there would needed.~~

DEV9: More strictly enforce MTU in pcap

---

pcsx2-qt/Settings/DebugSettingsWidget.ui
pcsx2/GS/Renderers/Common/GSVertexTrace.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Corrects depth trace correction for sprites and tries to optimise out making new depth targets when they aren't required.
The correct depth trace was checking every vertex for Z values, where only every second one is valid on sprites, meaning the "equal" test was failing. This is now fixed.
Also added some code to later optimise the "all tests pass" when it's selecting the depth targets.
Nothing really fixed.
Smoke test I guess

GS: Correct depth trace for sprites + optimize HW depth selection

---

pcsx2/CDVD/CDVD.cpp

a0d32d493c0781dc283106d418542f995a493a8c is incorrect, it always truncates the file, which makes the check-for-modification redundant.

CDVD: Actually fix NVRAM open mode

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Stops killing targets that are just a little bit dirty.
No real need to destroy the whole target because it's slightly dirty, doesn't make a lot of sense if there isn't another target over it.
Try Shadow hearts pause menu (already checked with GS Dump)
Fixes Shadow Hearts pause screens.
Before:
PR:
(the bit at the bottom is a TODO, pretend that's not there)
Edit: Decided to fix this other bug, so now it looks fine.

GS/HW: Don't kill old targets unless completely dirty or targets overlap

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Fix up Tekken 5 CRC hack for upscaling.
I got tired of hearing about the boxes all over the screen.
Test Tekken 5, notice it no longer has boxes.
Master:
PR:

GS/HW: Fix up Tekken 5 CRC to get rid of boxes when upscaling

---

pcsx2-qt/Settings/AdvancedSettingsWidget.cpp
pcsx2-qt/Settings/AdvancedSettingsWidget.ui
pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2-qt/Settings/EmulationSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/Renderers/SW/GSRasterizer.cpp
pcsx2/GS/Renderers/SW/GSRasterizer.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp
pcsx2/VMManager.h

Instead of having control over specific threads, thread pinning puts the EE/VU/GS threads on the most performant cores, then the software threads on the remaining cores, but only if they're in the same cluster.
This way we don't end up pinning across clusters with different performance characteristics, which would harm instead of help software renderer performance.
Also unpins on shutdown, that way we don't keep CPU cores awake.
And ignores SMT cores, because you don't want to be pinning two heavy threads on the same hyperthread...
The option in its current form is potentially detrimental to performance on heterogeneous CPUs.
Check option behaves as expected. You can see what threads are pinned in the log.

VMManager: Refactor Affinity Control to Thread Pinning

---

.github/workflows/scripts/linux/appimage-qt.sh

Wayland still being a pain in the arse, **despite us using xcb**, and appimages being the rubbish, hacked dependency hell that they are...
Ironically, if we didn't ship the QPA so fools can override the environment variable and get a broken experience, this wouldn't have been a problem to begin with.
Closes #11407.
Try PCSX2 on Meme Linux.

CI/AppImage: Explicitly remove libwayland-*

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

adds a check to see if a shuffle is doubling in a direction before aborting for the superman style shuffle.
TOCA 3 does a partial offset shuffle, which was confusing our code. But this won't be properly fixed until RT in RT is a thing
Smoke test mostly, not much fixed by it right now.

GS/HW: Additional texture shuffle dimension check

---

pcsx2/GameDatabase.cpp
pcsx2/VMManager.cpp

Misc: Make sure hw renderer is selected for hw renderer osd messages.
We don't want them displaying on sw renderer.
Make sure hw renderer osd messages don't display on sw renderer.

Misc: Make sure hw renderer is selected for hw renderer osd messages.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Allows offsetting in to render targets on offset channel shuffles.
A bunch of games do channel shuffles in such a way we can't override it and HLE it, so this allows that to work, but also accounts for both the draw and the read being offset by a number of blocks (block layout matches, so this is allowed).  This means as a result a lot of uploads etc are reduced.
As a result, we can now upscaled Monster Lab, just be careful as it gets heavy, plus this gets rid of a readback, so it should increase performance on some machines.
Check the following games.
Hitman - Blood Money (just make sure it's no worse, it should be fine, but won't be fixed)
Draw Calls: -4 [492=>488]
Render Passes: -5 [396=>391]
Copies: -1 [31=>30]
Uploads: -1 [47=>46]
Monster_Lab
Draw Calls: +1 [548=>549]
Render Passes: …

GS/HW: Allow offset channel shuffles on sources.

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/GameIndex.md
pcsx2/Docs/gamedb-schema.json
pcsx2/GS/GSRegs.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSRenderer.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Pcsx2Config.cpp

Downscales targets when being shrunk for post processing/bloom reaosns
A lot of games do bloom effects which rely on bilinear filtering, when you upscale this filtering gets completely broken or becomes exponentially more intensive to compute (if we did so). This PR will downscale the target to native resolution before bilinearly shrinking it.
This won't fix everything magically, but it will improve some games.
Test games which have horrible looking post processing at high resolution.
Keep in mind, this option is forced on in this PR but will become an upscaling fix later.
Screenshots from x8 or x3
Tomb Raider Legend:
Master:
PR:
Project Snowblind:
Master:
PR (SW looks like this too):
Valkyrie Profile 2:
Master:
PR:
Devil May Cry 3:
Master:
PR:
Tony Hawk Project 8:
Master:
PR:
Dragonball …

GS/HW: Natively downscale targets - General post processing

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Keeps the correct draw rect for the final clean up of draws.
the draw rect was getting changed to 1024x1024 when a channel shuffle happened, causing the validrect update check to mistakingly pass, this meant we had targets saying they were huge, taking up most of the memory and misfiring, most notably in Valkyrie Profile 2.
Test Valkyrie Profile 2 (already done), dump run also good, probably just gonna merge when it builds.

GS/HW: Keep real rect before draw to avoid bad valid rect update

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Correct the scale factor for lines when texturing.
When I modified this, I didn't quite understand what was going on with the Z vector, presumed it was all the same thing, but it turns out that is target scale not source, so upscaling in Vulkan really showed this up when lines were being drawn. Regression from #11337
Test 007 - Everything or Nothing
Master:
PR:

GS/HW: Fix line width factor when upscaling.

---

bin/resources/GameIndex.yaml

Changed Half Pixel Offset "Special (Texture)" with Round Sprite "Half"
It achieves the same effect as Half Pixel Offset on "Special (Texture)" while also aligning shadows more like on software renderer/real HW.
Check if it makes anything look weird (At least I couldn't find anything).
GS Dump (For reference):
[Crash Twinsanity_SLES-52568_20240621132529.zip](https://github.com/user-attachments/files/15926912/Crash.Twinsanity_SLES-52568_20240621132529.zip)
Before:
After:

GameDB: Fix shadows alignment on Crash Twinsanity

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

Restrict how large a target can be before it downscales to do a copy.
This was misfiring when copying a large "downscaled" target on to the framebuffer, which as a result downscaled the framebuffer, since there's no easy way to detect if this can be downscaled or not, so better to restrict the size.
Try Valkyrie Profile 2 and Dragons Quest VIII where it was forcing downscaling.
Keep in mind I'm probably still not going to put anything past "normal" native scaling on Dragons Quest as it causes some bad pixelation still

GS/HW: Fix up some down/upscaling behaviour

---

pcsx2/GS/GSState.cpp

Enforces a minimum rect size should there be a zero height or width
Because of some recent changes that stopped a rect *always* being too big, it meant any zero sized rects became zero, so now we need to check these at the end, since rects are exclusive end.
Smoke test mainly, dump run (and splashdown in software) says it's good

GS: Make sure min/max for texture is at least 1 pixel

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
.github/workflows/scripts/macos/build-dependencies.sh
.github/workflows/scripts/windows/build-dependencies.bat

Hello it is me Stenzek and today we once again drop the freshest versions of Qt.
Note for future people looking back at this I had to remove "-DFEATURE_printsupport=OFF" from the build dependencies script on Linux and Mac to get this to build properly which appears to be a Qt bug fixed in 6.7.3.
https://bugreports.qt.io/browse/QTBUG-125066
Might end up fixing some bugs we have which would be handy.
Make sure everything still works.

Deps: Update to Qt 6.7.2

---

bin/resources/GameIndex.yaml

When upscaled, the post processing is misaligned (noticeable with higher resolution 6x or 8x) and there's a weird ghosting effect. The new "Natively downscale targets" hack solves it.
Before : 
After :

GameDB: Street Fighter EX3 - Fix the post processing at high resolution

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Improves detection of when scale needs to be preserved
This was errantly leaving targets downscaled when they don't need to be in Prince of Persia, so I've improved the detection to only preserve the target size when it should be.
As a result the misdetection on Shadow of the Colossus no longer happens meaning Native Scaling is useless here, but the problem is the half pixel offset, not a scaling issue.
Smoke test, already been through the Native Scaling dumps

GS/HW: Improve scale preservation check

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Metal/GSMTLSharedHeader.h
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Apparently this was completely missing, whoops.
Also enables clamp elimination in mipmapped situations, which is important due to us having mipmapping on by default now. TW/TH won't match when mipmap minimization eliminates the base level, so use the TEX0 register from the context instead.
Fixes #11441.
Couple of other noteworthy mentions:
Check linked dump on all renderers.
Smoke test, runner says we good.

GS/HW: Allow use of trilinear with shader sampling

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/GS/Renderers/Vulkan/VKEntryPoints.inl
pcsx2/GS/Renderers/Vulkan/VKSwapChain.cpp
pcsx2/GS/Renderers/Vulkan/VKSwapChain.h

When image acquire returns suboptimal, apparently we should release the swap chain image we just acquired, because apparently that doesn't happen implicitly on creation of a new swap chain? (if you're transferring, not destroying/creating).
Related to #11280.
See if the leak/driver crash occurs.

GS/Vulkan: Release swap chain images on acquire fail

---

pcsx2-qt/LogWindow.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h

Works around the menu-backgrounds-being-transparent bug when switching between classic windows and any other style by recreating the window. Terrible, but I don't feel like debugging Qt today.
Bug workarounds.
Test changing theme.

Qt: Work around theme swap bug with Classic Windows

---

pcsx2/GS/GSLocalMemory.cpp
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Optimises blends to use constants in some situations to avoid software blending.
Fixed a bug with GPU CLUT not setting the right alphas (Setting it to "don't know" currently, as it's better than blatantly wrong)
Fixed up GS memory page mapping to only map up to the maximum size of the GS memory, not much point in doing more.
Optimisation are always nice, in some cases (listed below) it saves hundreds to thousands of barriers, making some games run faster on AMD and low powered GPU systems.
Test below listed games when GPU limited (you will need either a potato or hope 8x native resolution is enough), using default blending for said games.
Improves the GPU limited performance of the following games:
Ace Combat 5/Zero/Squadron Leader
Driver - Parallel Lines
Need for Speed Most …

GS/HW: Optimize blends in some zero color scenarios

---

bin/resources/GameIndex.yaml

Disables FBMask reducing the silly barrier count from 12,000 odd to 0.
Capcom are dumb and are ruining our performance.
Make sure the patches work correctly as described on the tin.

GameDB: RE Outbreak disable FBMask patch

---

pcsx2/DEV9/Sessions/BaseSession.h
pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.cpp
pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.h
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session.cpp
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session.h
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_In.cpp
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_Out.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.h
pcsx2/DEV9/Sessions/UDP_Session/UDP_Session.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_Session.h
pcsx2/DEV9/SimpleQueue.h
pcsx2/DEV9/sockets.cpp

Return the server IP that sent the packet alongside the payload
Use unique_ptr instead of raw pointers for managing the return packet within sessions
The existing method of passing the server IP by adjusting the destIP field is not obvious.
ICMP was reusing the destIP field, and would end up targeting the incorrect address during traceroute.
Less managing raw pointers
Test networking games using sockets.

DEV9: Sockets: return server IP alongside payload

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/Pcsx2Config.cpp

Currently, when we do a draw that covers the whole target, we invalidate the target as a performance optimization. This is great, but when you're upscaling, draws tend to be offset due to HPO native shenanigans, and not cover the target.
So, clear the targets instead. This'll require a little more VRAM bandwidth, but it's better than sampling random garbage because HPO pushes the coordinates down.
Hopefully fixes "random" garbage on the edges of the screen with HPO native, replacing it with "black" garbage, but at least that's consistent.
Check HPO native games.

GS/HW: Clear instead of invalidating upscaled targets

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes bug
Bug bad
Check native scaling games still act as expected, not expecting any change, but you never know.

GS/HW: Fix upscale draw detection check

---

bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/vulkan/convert.glsl
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSMTLSharedHeader.h
pcsx2/GS/Renderers/Metal/convert.metal
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

Fixes some of the aliasing you get in downsampled postfx (e.g. katamari, ratchet) by smoothing out the source texture with a box filter, instead of nearest-neighbour.
Check for affected games. ~~I still need to implement it in DX/GL/Metal.~~

GS/HW: Use box filtering for source downsampling

---

bin/resources/GameIndex.yaml

Reverted an accidentally changed game title by #10928 
wrong names bad
See game list

GameDB: Revert wrongly changed game title

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Avoids preloading data outside of the valid area
Valkyrie profile 2 makes a new target with a width of 4 (this is 256 pixels), then only draws to 129x96, but the preload tries to put something next to it, which later causes a shuffle to fail because it thinks the target is dirty (even though it's not going to read it that area) and ends up drawing garbage.  Ideally we'd have perfect rect checking in our Lookup Source code, but they didn't use complete pages, so that kinda ruined my day.
Test valkyrie profile 2
Master:
PR:

GS/HW: Fix preloading targets dirty update

---

bin/resources/GameIndex.yaml
bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/vulkan/convert.glsl
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Metal/convert.metal

Truncates depth buffers from 32bit to 24bit values when a game requests to read depth as 24bit.
We store depth as a normalized 0-1 value, so when a game swaps to 24bit it still retains what would normally be the upper 8 bits of the depth buffer.  In the case of Harry Potter it expects this top 8 bits to be gone, and it messes up handling of the post processing.
Also added upscaling fixes to said game so it doesn't look sucky when upscaled.
Dump run said it was fine, test Harry Potter - Quidditch World Cup. Also try Superman Returns and X-Men - Wolverine's Revenge as they showed up in the dump run as probably hitting this code (have tried them, no noticable difference).
~~TODO: Need to do DX, OGL, Metal~~
You can test this dump:
[Harry Potter - Quidditch World …

GS/HW: Allow conversion from 32bit to 24bit depth

---

bin/resources/GameIndex.yaml

Revert Half Pixel Offset to Special (Texture).
Avoid shadow glitches introduced by Align To Native. 
Image clarity is not quite as good, unfortunately.
4x Native, otherwise default:
HPO Align To Native / Master:
HPO Special (Texture) / PR:
Check CI.
Test [this dump](https://github.com/user-attachments/files/16033791/Shadow.of.Rome_SLES-52950_Shadows-HPO.gs.zip) and the game in general.

GameDB: Shadow of Rome revert to HPO Special

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Why were we doing this to begin with?? It's two copies versus one.
As much as I dislike doing things that benefit DX, this is a no-brainer.
Fixes #11480.
Honourable mentions:
```
Big.Mutha.Truckers ['Draw Calls: -405 [1308=>903]', 'Render Passes: -535 [1152=>617]', 'Copies: -202 [764=>562]']
Detective Conan MENU Graphics Bug Multi Frame ['Draw Calls: -335 [1934=>1599]', 'Render Passes: -418 [1073=>655]', 'Copies: -167 [714=>547]']
sakura taisen shadows 1 (hw) ['Draw Calls: -46 [396=>350]', 'Render Passes: -53 [240=>187]', 'Copies: -23 [162=>139]']
Shadow_of_Rome_SLES-52950 ['Draw Calls: -88 [819=>731]', 'Render Passes: -61 [168=>107]', 'Copies: -44 [109=>65]']
Sly_2_-_Band_of_Thieves_SCUS-97316_20221019165824 ['Draw Calls: -1013 [3868=>2855]', 'Render Passes: -761 [2842=>2081]', 'Copies: …
```

GS/HW: Prefer SW blend over HDR for colclip without overlap

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

reduces area the downscale filter copies.
With the addition of box filtering, this gets exponentially slower the higher the resolution, so if we can shave off some pixels, all the better.
Try games which slowed down a bunch with higher resolutions that used native scaling.
Still not great but it's better than it was.  shadow of the colossus (which doesn't currently have NS but needs it), went from about 56-58 up to about 95fps, so that's the difference of playable full speed on my machine.

GS/HW: Optimize area of downscale algorithm to reduce processing

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHWMultiISA.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Cleans up function PrimitiveCoversWithoutGaps (now CalculatePrimitiveCoversWithoutGaps) to reduce some branches.
There was no point in it being optional because we were always calculating it (unless it was a SW call, but that should have had it too, really), tidies up the code.
Test some games in HW and SW, make sure they still work ok.

GS: Clean up usage of PrimitiveCoversWithoutGaps

---

pcsx2-qt/Settings/SettingsWindow.cpp
pcsx2-qt/Settings/SettingsWindow.h
pcsx2/Config.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp

derp derp
Fixes #11489.
Check steps listed in #11489.

Qt: Fix crash in copy game settings

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/D3D.cpp
pcsx2/GS/Renderers/DX11/D3D.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSMetalCPPAccessible.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp

Removes the arbitrary 8x limit from the UI, allowing a maximum of 12x if show advanced options is not enabled, otherwise whatever your GPU's texture size limit is.
@JordanTheToaster's idea, send all anger to him, I'm innocent.
Test upscaling.
Make sure DX11 doesn't crap itself in Baldur's Gate anymore if you set upscale too high.

GS: Uncap upscale multiplier subject to GPU limits

---

pcsx2/Cache.cpp
pcsx2/Cache.h
pcsx2/vtlb.cpp

You are able to make TLB entries that point to invalid physical addresses. Because the cache is accessed before the physical write , the cache will still store data for these physical addresses. Once the cache data is evicted, curiously there is no bus error for addresses such as 0x70004000, so the data is silently discarded.
Find my Own Way uses this method to create a "virtual scratchpad" of higher speed, temporary memory.
Previously our cache line locking wasn't fully implemented. This PR addresses that as well.
With the combined invalid physical address mapping and cache line locking support, **I believe I have fixed the find my own way demo!.**
This is proper cache behaviour.
Test games that require EE Cache (I'm sorry, I know it's slow :( ), make sure they still work.
Also, **if any …

EE Cache: Fix cache masking, support caching invalid phadr, and cache line locking

---

pcsx2-qt/Translations/pcsx2-qt_en.ts
pcsx2/CDVD/ThreadedFileReader.cpp

This PR makes some more strings related to CDVD Precaching be translatable:
More translation the gooder
See and make sure i didn't break anything else

Qt: Make more precache strings translatable

---

bin/resources/GameIndex.yaml

Title includes exclamation mark.
"Make War, Not Love!" is a tagline, not part of the title. Removed.
Correct title.
Make the game appear in the Game List after _Destroy All Humans!_ when sorting by title.
Check CI.

GameDB: Destroy All Humans! 2 PAL Title

---

pcsx2-qt/Settings/AdvancedSettingsWidget.cpp
pcsx2-qt/Settings/GameFixSettingsWidget.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp

* Add text for up to 25x resolution in the Qt UI.
* Remove 2.25x and 2.75x upscaling multipliers.
Stenzek recently changed upscaling options to up to 12x by default; this adds text for those new options like we do for the old ones. Furthermore, in Advanced Settings, you can now go up to a resolution limited by your hardware specifications; this goes up to 25x for seemingly most people.
Regarding the removal of 2.25x and 2.75x, whereas 2.5x or 900p seems very reasonable, the 2.25x and 2.75x multipliers seem to just take up space, and I have never heard of anybody using them.
Enable Advanced Settings and look up to 25x. Also try without Advanced Settings enabled to make sure I didn't break anything for the default user experience.
Also fixed the 5x option reading `~1620p`, despite the fact …

GraphicsSettingsWidget.cpp: Add text to upscaling multipliers and remove two fractional multipliers

---

bin/resources/GameIndex.yaml

Previously under #11502, resubmitted with cleaner commit (and Unix EOL)
Previously contributed under @CelestialRyuneko and @JamesKnight313 (both accounts lost to 2FA failure)
Add eeClampMode fix to SLPM-66644 (J-League Pro Soccer Club o Tsukurou 5)
Makes the game correctly register left and right Dpad button input in certain screens.
Go to the roster screen, and without patch you can't go further right than the leftmost players. You can do that with the patch. Patch adapted from SLES-54151 (same engine).

GameDB: Add eeClampMode fix to SLPM-66644

---

pcsx2/USB/usb-hid/usb-hid.cpp

Map `Q_KEY_CODE_DOT` to "Period" instead of "Dot"
Fix the regression noted in https://github.com/PCSX2/pcsx2/issues/7605#issuecomment-2209905668
As far as I can tell, current code builds mappings between the Q_KEY_CODE (which is the scan code) to QT::Keys based on the name.
The equivalent QT key `Qt::Key_Period` has the name of "Period" and wouldn't match before.
Test keyboard input, in particular the "." button.

USB: Fix period key not working

---

pcsx2/GS/Renderers/Null/GSRendererNull.cpp
pcsx2/GS/Renderers/Null/GSRendererNull.h

The null renderer was ignoring draws a little _too_ well. The draw queue was filling endlessly, causing a memory leak.
Memory leaks are bad
Run a heavy game (GT4 night course worked well) with the null renderer with the framerate unlocked and see if memory usage increases a lot. GS dumps were affected too.

GS: Clear draw queue when using the null renderer

---

pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/ExpressionParser.cpp

Add f[0->31] register support in the expression parser.
Breaking only when an FPU register is a certain value is a possible need for some.
See if breakpoints properly evaluate FPU registers.
Note: Using `==` with floating point constants casts the value into a **host (NOT PS2)** float and compares it that way. Not using any float constants causes the expression parser to use bit comparisons. Think `f0==f2` for example. Using float constants has more error tolerance than a bit compare, but do know that like any other programming, using == with floating point is a sin and can cause a bad day. I was thinking of adding a lenient floating compare such as `~=` (identical to the memory search system) but defining behaviour rules for it was difficult, so I scrapped the idea.

Debugger Expressions: Add FPU registers to breakpoint conditionals.

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp

GS: Fix half pixel offset normal upscaling above 8x.
Fixes half pixel offset normal upscaling above 8x, and simplifies the code to work on any upscale res.
Test HPO normal on various upscale res.

GS: Fix half pixel offset normal upscaling above 8x.

---

pcsx2/GS/GSLocalMemory.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

GS: Fix Wsign-compare warning.
GS/Metal: Add FLOAT32_TO_FLOAT24 case to DepthStencil texture format for shader convert.
Correction, cleanup.
Test 32 to 24 depth conversion still works on metal from https://github.com/PCSX2/pcsx2/pull/11476.

GS: Miscellaneous changes.

---

bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/vulkan/convert.glsl
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/ShaderCacheVersion.h

GS/HW: Check for full cover in more situations when we disable blending.
More hits on RTA Scaling/Descaling.
Improves RTA Scale/Descale.
Some games gain/lose copies/passes/barriers.
dump run is clear on dx and vk, nothing broken.
Improves Star Wars Battlefront on DX with basic blending:
Before vs after:

GS/HW: Check for full cover in more situations when we disable blending.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Allow detection of non-bilinear downscales
Scaler downscales non-bilinearly.
Test Scaler and some random games with native scaling.
Scaler:
Master:
PR:
Drakengard 2 slightly improves:
Master:
PR:

GS/HW: Improve scale detection and allow non-bilinear downscales

---

bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSMTLSharedHeader.h
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/ShaderCacheVersion.h

GS/HW: Adjust point sampler behavior.
VK/GL/Metal: Get rid of it completely as it doesn't seem needed anymore.
DX: Only enable it with combination with GPU Palette Conversion enabled as that's when the issue occurs.
Fixes https://github.com/PCSX2/pcsx2/issues/11521
Test the linked dump with GPU Palette Conversion enabled on AMD.
[Dragon Ball Z - Budokai Tenkaichi 3_SLUS-21678_20240708211609.gs.zst.zip](https://github.com/user-attachments/files/16133760/Dragon.Ball.Z.-.Budokai.Tenkaichi.3_SLUS-21678_20240708211609.gs.zst.zip)

GS/HW: Adjust point sampler behavior.

---

pcsx2-qt/Translations/pcsx2-qt_en-US.ts
pcsx2-qt/Translations/pcsx2-qt_en.ts
pcsx2/SIO/Pad/PadDualshock2.cpp

This PR clarify the confusing pressure modifier string `Modifier Pressure` -> `Pressure Modifier Amount`
Translation 100

Qt: Clarify Pressure Modifier String

---

pcsx2-qt/MainWindow.cpp

Previously, selecting 'Open Debugger' while the debugger window was open would close the debugger as though it were toggling it.
If a user accidentally reclicks 'Open Debugger', they probably don't want the window closed.
Select Open Debugger both while the window is opened and closed.

Debugger: Fix Open Debugger option to not toggle

---

pcsx2/Input/InputManager.cpp

Fixes a crash when disabling the input source while emulation was running. 
Crash bad.
1. Run any game.
2. Enable any input source (SDL, DInput, XInput).
3. Disable that input source.
4. PCSX2 should not crash.
Fixes #11377

InputManager: Release settings lock before shutting down the input source

---

README.md

Replaced the broken link to BIOS dumping instructions to the one currently used in Setup Wizard.
The link was broken, verly likely outdated.
Follow the link? Hope it works now!

Fix BIOS dump link in README

---

bin/resources/GameIndex.yaml

Disabling MTVU is no longer needed and all it does is slow down the game on weaker hardware.
Disabling MTVU for no reason is silly.

GameDB: Fix up ATV ORF 3 fixes

---

pcsx2-qt/MainWindow.cpp

Previously, right-clicking games on the list and choosing a game cover individually created an image in pcsx2 > covers whose filename was that of the name we use in the DB. It now uses the game's serial instead.
Resolves #10126. Game names are often highly volatile, as Jordan and I change them in the DB all the time. Using the game serial makes it so that it is near impossible for a GameDB update to break a user's config in this manner. Moreover, if two games had different covers but the same names (e.g. from different regions), you would simply have to select one and share them or change the name of one manually.
Try right-clicking a game in the game list, then selecting a cover image. Check pcsx2 > covers and see if the game has a serial instead of its full name.

Covers: Use serial for cover image names when selected individually

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/GameDatabase.cpp

Made it so that the native scaling ImGui nag for manual HW fixes does not nag users at native or lower resolution.
Currently no matter what if you are at native or lower resolution and have manual HW fixes enabled, native scaling will nag you in the ImGui messages (even if you have the corresponding native scaling enabled). Much like HPO and RS, it should not nag you whatsoever until you upscale.
Try messing around with a game that has native scaling recommended in the DB.
Additionally corrects unambiguous typo in a graphics settings description.

GameDB: Ensure NativeScaling doesn't nag users at native res

---

pcsx2-qt/Debugger/MemoryViewWidget.cpp
pcsx2-qt/Debugger/MemoryViewWidget.h

Support little and big endian view modes within the debuggers memory view via context menu action.
Big endian values, although easier to work with in this context, don't make sense for the PS2.
Please test all byte grouping modes. Copying memory, pasting memory, using keyboard arrows to move around with both big and little endian modes.
fixes #7998

Debugger: Implement little endian memory view support

---

pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Themes.cpp

Adds new Emerald theme. Corrects palette variable names in themes to reflect actual theme names.
Rounds out Ruby and Sapphire with a green theme. Variable names corrected for more readable code (previously appeared copy-pasted). These are huge walls of palettes, so being able to easily orient yourself is important.
Try the new theme out and see if you like it! This isn't an omnibus PR; Emerald theme can be removed if not desired but changed variable names are.

Qt: Add Emerald theme and fix palette var names

---

common/CMakeLists.txt
common/Linux/LnxHostSys.cpp

Use cpuinfo to detect cache line size on FreeBSD
I elected to keep the existing logic for other platforms as if, as I can't test Mac or Arm.
If desired, I could swap all platforms to use cpuinfo for this
Fix FreeBSD builds (With the workarounds mentioned here https://github.com/PCSX2/pcsx2/pull/11287)
This is only a build fix, the code doesn't actually get used on x86, and I don't think cpuinfo supports FreeBSD on Arm (but neither do we)
Test CI works,

[RFC] Common: Use cpuinfo to detect cache line size on FreeBSD

---

pcsx2/IopMem.cpp
pcsx2/MemoryTypes.h
pcsx2/x86/ix86-32/iR5900.cpp

The SCPH-50009 model features a 64-Mbit DVD-ROM chip, with the first 4MB allocated to Rom1 and the last 4MB to Rom2. This entire chip is mapped to the EE/IOP memory at address 0x1E000000. This PR addresses the issue of hardcoded size limits for Rom2, previously set to 512KB.
This PR resolves the improper loading of `rom2:GB18030` into memory, which was previously being loaded in a cropped state.
Please refer to the game list provided in [this comment](https://github.com/PCSX2/pcsx2/pull/3439#issuecomment-2231805578). Potentially affected games include:
- Ape Escape 2 - 捉猴啦 2 (SCCS 40001
- Viorate no Atelier: Gramnad no Renkinjutsushi 2 - 薇欧蕾特的工房 ～古拉姆那特的炼金术士2～ (SCCS 40015)
- EyeToy: Play - 爱淘儿 (SCCS 40017)
- EyeToy: Saru EyeToy: Oosawagi! Ukkiuki Game Tenkomori!! - 比波猴@爱淘儿 (SCCS 40018)

Bios: Fix Rom2 size limit

---

pcsx2/DEV9/PacketReader/IP/IP_Payload.h
pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.cpp
pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.h

Replace C-Style casts with C++ equivalents.
Make capitalisation of text in log messages consistent.
Format comments to (hopefully) be more inline with PCSX2's comment style
Use non-blocking sockets, unifying code between Linux and Mac/FreeBSD
Various bug fixes and cleanup
Add consts
It may be easier to review each commit one by one rather than the whole pr at once
Improve code quality
Fix bugs
Test networked games/apps that performs pings using the sockets backend.

DEV9: ICMP Cleanup

---

cmake/BuildParameters.cmake
cmake/SearchForStuff.cmake
common/CMakeLists.txt
common/CrashHandler.cpp

RFC? Should this be implemented?
Adds the USE_BACKTRACE CMake build option to optionally disable libbacktrace
fixes #11566 
Try to build with -DUSE_BACKTRACE=1 (default) and -DUSE_BACKTRACE=0
Please know that support will not be given for builds with libbacktrace disabled.
I'd also like to remind Linux users: **First class Linux support is provided for the AppImage and Flatpack only. If it is not reproducible on either builds, we will consider the issue invalid.**

linux/cmake: Allow libbacktrace to be disabled

---

pcsx2-qt/MainWindow.cpp

This fixes a crash on wayland (and possibly others)
On Wayland, check hide main window, make sure render to main is set, boot a game then try to boot another.
@kamfretoz to test

qt/MainWindow: for disable hide window if render to main is enabled

---

pcsx2-qt/MainWindow.cpp

Disables Tools > Save Single Frame GS Dump when not running. Additionally creates a small microoptimization within MainWindow::updateEmulationActions.
Tool has no functionality if not running. Moreover, we only ever use starting_or_running || stopping in the body of this function, so starting_or_running_or_stopping seems like the logical next choice. I asked ref if we re-poll 'stopping' as some sort of timing issue, but that does not appear to be the case; just a few wasted clock cycles maybe.
Make sure 'Save Single Frame GS Dump' is available when needed and not available when not needed.

Qt: Disable Single Frame GS Dump tool when not running

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/GS.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Pcsx2Config.cpp

This PR adds a toggle to show the PCSX2 version to the OSD (Disabled by default).
Preview (Top Right):
Can help with identifying PCSX2 version during support.
Test if the toggle works and the version shows up correctly on the OSD.

OSD: Add PCSX2 Version toggle

---

pcsx2/GS/GSCapture.cpp

VAAPI seems to report as supporting `AV_PIX_FMT_VAAPI` but trying to create with a `sw_format` of `AV_PIX_FMT_VAAPI` doesn't work.  I'm assuming we're supposed to use `NV12` based on [ffmpeg documentation telling people to use nv12 on the CLI](https://trac.ffmpeg.org/wiki/Hardware/VAAPI) but tbh I don't know if this is the right solution.  It does work on my computer though.
Linux hardware encoding
Try all the vaapi encoders your gpu supports
Note: You may need to adjust some packages to enable VAAPI, e.g. [Fedora directions](https://rpmfusion.org/Howto/Multimedia)

GS:Capture: VAAPI support

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/GSCapture.cpp
pcsx2/GS/GSCapture.h
pcsx2/Pcsx2Config.cpp

On newer avutil versions we must set the channel layout. This wasn't an issue on the flatpack because the ffmpeg version is fixed. On appimages this was an issue because we depend on the system library, which can be a higher version.
I implemented the ability to select the pixel format based on the current codec selected. This fixes hw encoding with AMD GPUs on Windows as it did not like the YUV420P format. As for Linux, I'm not entirely sure. It appears that hw encoding support is quite a mess. AMF is only supported on nonfree AMDGPU-PRO drivers, and I don't really know the capabilities of mesa.
Fixes captures on newer ffmpeg/libavutil versions.
More capture options for the videophiles. 
Obviously if you select weird options like `cuda` or `d3d11` things are going to not work. Don't …

GS Capture: Set Avutil Channel Layout and Implement Pixel Format Selection

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/Settings/GameSummaryWidget.cpp
pcsx2-qt/Settings/GameSummaryWidget.h
pcsx2-qt/Settings/GameSummaryWidget.ui

Gives the user an option in the game list's right-click menu to be taken to the relevant PCSX2 wiki page.
It accomplishes this because I recently ran a script on the wiki to create redirects to the relevant pages for every single serial in the GameDB. Most games should currently work, but the serials that redirect to a red link (a non-existent article) or which attempt to double-redirect (not possible on MediaWiki) will need to be corrected over time.
Gives the user a quick and easy way to access the relevant PCSX2 wiki page for their game. Much better and more consistent than using the entry's name, as that frequently changes both in the DB and on the wiki. This gives us a permanent bridge between those two platforms.
Right-click on your games in the game list/grid and select 'Check Wiki …

Qt: Add per-game link to PCSX2 Wiki pages on right-click

---

pcsx2-qt/Settings/GameSummaryWidget.cpp
pcsx2-qt/Settings/GameSummaryWidget.ui

Get rid of extraneous icon for the compat line in GameSummaryWidget and turn the line into a read-only text field.
The icon was so tiny as to be unreadable and therefore useless. The line was previously a dropdown menu that could not be changed, creating an extraneous arrow symbol on the right side of the line and reducing the contrast of the text against the background.
Before:
After:
Check the game properties widget for your games.
Also adds a star rating system that was poorly implemented previously as icons. Credit to @F0bes for amending my star rating lambda to be more compact.

Qt: Simplify compat line in GameSummaryWidget

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/MainWindow.ui
pcsx2-qt/resources/icons/black/svg/camera-video.svg
pcsx2-qt/resources/icons/white/svg/camera-video.svg
pcsx2-qt/resources/resources.qrc
pcsx2/GS/GSCapture.cpp

This PR adds the Video Capture button into the toolbar for quicker access.
Easier to access the video capture rather than going through Tools -> Video Capture
QoL 100

Qt: Add Video Capture button to toolbar

---

pcsx2/Recording/PadData.cpp
pcsx2/SIO/Pad/PadBase.h
pcsx2/SIO/Pad/PadDualshock2.cpp
pcsx2/SIO/Pad/PadDualshock2.h
pcsx2/SIO/Pad/PadGuitar.cpp
pcsx2/SIO/Pad/PadGuitar.h
pcsx2/SIO/Pad/PadNotConnected.cpp
pcsx2/SIO/Pad/PadNotConnected.h
pcsx2/SIO/Pad/PadPopn.cpp
pcsx2/SIO/Pad/PadPopn.h

Directly set the controller state to the values recorded, bypassing the extra processing in `Set()`
Existing code did not correctly pass the pressure value, treating any pressure value above 0 as 255.
This was due to the input recorder passing a value of range 0-255, rather than a 0-1 float range that `Set()` expected.
Existing code recalculated the pressed state, which could differ from the recorded value
I managed to create a recording with a pressed state of true, but zero pressure
I suspect this happened because my triggers had higher resolution than the PS2 controllers, and a _very_ light touch got rounded down.
Record your input and then play it back, comparing the results
I had used padtest for comparing.
I would like if someone could test with pressure sensitive face buttons. the …

input-rec: Directly use recorded values for pressure sensitive buttons

---

pcsx2-qt/Settings/GameSummaryWidget.cpp
pcsx2/GameList.cpp

Makes the GameList::EntryCompatibilityRatingToString return strings translatable.
Unbreaks what I broke in my previous PR and makes this function more versatile.
Make sure the compat string still displays correctly in the summary widget and the fullscreen UI.

GameList: Make compat strings translatable

---

.github/workflows/linux_build_flatpak.yml
.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json

Currently building the flatpak fails as the metainfo file is missing.  This change moves generation of the metainfo file from the github gi workflow into the flatpak manifest.
The MR also updates the ffmpeg extension to match the freedesktop platform the package uses `23.08`. You can check this with:
```bash
flatpak run --command=grep org.kde.Platform//6.7 runtime-version /usr/manifest.json
```
It makes it easier to compile the flatpak locally.
```bash
flatpak run org.flatpak.Builder --user --jobs=20 --force-clean --install ./_build ./.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json
```
Out of interest is there a list of wayland related issues? Now that this project no longer uses wxWidgets I'm interested in tackling the ones that aren't just NVIDIA driver bugs.

CI: Move appdata generation into flatpak manifest

---

pcsx2-qt/CoverDownloadDialog.cpp
pcsx2-qt/CoverDownloadDialog.ui

Uses serials by default when using the cover downloader instead of titles of games. It has now flipped so that there is a 'Use Title File Names' option.
Using the titles of games is an inherently unstable, messy way to name these files by default. When a user creates and downloads their covers, in all likelihood they do not want to ever have to re-configure the covers. However, using the title by default creates exactly that problem, and it has cropped up several times in the Discord: Jordan or I change the name in the GameDB, and now suddenly the cover images are broken for the end user who needs to go and replace them again.
Additionally, it means that titles with the same name but different covers for multiple regions will have a collision. It is clear that using the serial is the …

Qt: Use serials by default for cover filenames with downloader

---

pcsx2/USB/usb-pad/usb-buzz.cpp
pcsx2/USB/usb-pad/usb-buzz.h
pcsx2/USB/usb-pad/usb-trance-vibrator.cpp
pcsx2/USB/usb-pad/usb-trance-vibrator.h

Oversight when merging some USB prs, oops.
When these devices were created / moved, their freeze function wasn't implemented.
It made it so you could not save state when these devices are selected
Try to save and load a savestate.

USB: Implement trance vibrator and buzz savestate freezing

---

.github/workflows/cron_publish_flatpak.yml

flatpack cron job thought that our current release version was less than what is on flatpack. 
I don't really trust comparing to semver strings and I don't know why else the second job would've been skipped...
Flatpack is not updating
I'll have to merge to master and then test.

ci: Possibly fix flatpack release vs pcsx2 release version compare

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/GS.cpp
pcsx2/ImGui/ImGuiManager.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Pcsx2Config.cpp

* Allow performance OSD to be toggled off altogether
* Allow right-alignment of OSD messages
* Allow left-alignment of OSD performance statistics
* Create QComboBox for OSD messages (obsoletes `Show OSD Messages` checkbox)
* Create QComboBox for OSD performance statistics
* Make the way we do OSD more extensible.
Note that the performance statistics `None` setting does not disable controller input OSD or settings OSD, and furthermore note that the positions of the inputs and settings cannot be swapped.
Allow the user to switch between alignment of the OSD messages and OSD performance. Allows the user to easily disable all OSD performance without using a hotkey.
Partially addresses #6642.
Change OSD position around.

OSD: Allow independent left- and right-align for OSD

---

bin/resources/GameIndex.yaml

Fixes game names that are incorrect which I come upon doing the serial redirects on the wiki. Also adds English names to non-English titles where missing.
This list will continue to be updated.
Pedantry I guess (and threw in a fix for good measure).
Make sure the changed names are accurate.
* Fixes #11496 for Kumauta (fix by @Buzzardsoul and @Mrlinkwii)
* Fixes #11618 for the Karaoke Revolution games

GameDB: Fix game names

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

Shows the current system CPU in the OSD when ticking the new show hardware info OSD option. Also reenables Fobes previously disabled GPU info and driver logging.
Example:
This will be helpful for support queries as well as people who stream or make videos and want to display hardware information easily.
Make sure the CPU info works on Windows Linux and Mac and doesn't end up making anything else go boom.

OSD: Add hardware info statistics

---

pcsx2/USB/usb-msd/usb-msd.cpp
pcsx2/USB/usb-msd/usb-msd.h

- Convert the generic Mass Storage emulated device to Zip100 and add new SCSI commands needed by Zip100.
- The apps that don't expect a specific storage device (GT4, TT, wlaunchElf, anything else?) will continue to work but will also support Zip-100 specific apps.
- https://www.ign.com/articles/2001/03/24/gdc-2001-iomega-zip-drive
- ![Untitled](https://github.com/user-attachments/assets/49322cbc-2b56-4367-ae64-a2caf05eef75)
- PictureParadise emulation (Sony MSAC-US1).
- https://www.ign.com/articles/2000/09/26/tgs-2000-put-yourself-in-the-game
- ![picpara_logo](https://github.com/user-attachments/assets/d262643b-afaa-494b-b0cf-5d2bf6c13173)
- PictureParadise is very picky about the disk format, doesn't support disks larger than 128MB and needs strict DCF photos.  A supported disk can be …

USB: Zip100 and PictureParadise emulation

---

CMakeLists.txt
cmake/BuildParameters.cmake
pcsx2-gsrunner/CMakeLists.txt

Adds `ENABLE_GSRUNNER` option to build GSRunner using CMake
Remove the extra `n` in pcsx2-gsrunner CMakeList
Parity with MSBuild
Make sure GSRunner is not built when CMake is configured without `-DENABLE_GSRUNNER=ON`
Build pcsx2 using CMake with an additional configure argument `-DENABLE_GSRUNNER=ON` on windows

GSrunner: Add CMake Build Option

---

bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp
pcsx2/ShaderCacheVersion.h

Test restoring feedback loop layout.
Fixes #11238 
Fixes rendering problems on RDNA 2 and 3 GPUs on Windows.
Test to see if rainbows or other strange phenomena appear on RDNA 2 or 3 GPUs on Windows.

GS/Vulkan: Restore VK_EXT_attachment_feedback_loop_layout

---

bin/resources/GameIndex.yaml

Enables use of the Football Fusion cross-play feature in FIFA 2004 and Total Club Manager 2004 with FolderMCs.
Allows FolderMC users to use this (admittedly niche) feature.
1. Start a new career of TCM 2004.
2. Get to the first friendly match.
3. Export to Football Fusion.
4. Switch game to FIFA 2004.
5. Use Football Fusion to play the match.
6. Export back to TCM 2004.
7. Load the Fusion back in.
8. Progress should have been saved.

Add memcardFilter for SLES-51953 and SLES-52022

---

bin/resources/GameIndex.yaml

Fixes broken bilinear on lighting effects by applying ATN.
Before:
After:
Broken bilinear bad.

GameDB: SMT Nocturne Fixes

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

If the two targets are misaligned, it's likely a relocation, so we can just kill the old target.
Kill targets that are overlapping new targets, but ignore the copy if the old target is dirty  because we favour GS memory.
Also check for width offset and adjust width accordingly using the offset.
Fixes https://github.com/PCSX2/pcsx2/issues/11559
Test DQ8, Ace Combat 5, B-Boy, as well as other games.

GS/TC: Adjust how we handle merging targets in PreloadTarget. 

---

pcsx2/DebugTools/DisassemblyManager.cpp

We do a bunch of ugly pointer arithmetic to build opcode strings. When we incremented our pointer and passed that to snprintf, we still told snprintf the total size of the buffer despite us starting x amount of chars after the beginning.
I tracked how far we are inside of the buffer and subtracted that from its total size and gave that to snprintf.
This in practice this would likely not be an issue, unless maybe if you had incredibly long symbol names. However, [source fortify](https://www.gnu.org/software/libc/manual/html_node/Source-Fortification.html) caught the issue and would SIGABORT. 
Put `0x1000FFF9` at some address in the memory view, and go to that address in the disassembly view and see if it dies.
(We do not build with fortify enabled on AppImage or Flatpak builds, you can not …

Debugger: Track remaining buffer size for snprintf 

---

.github/workflows/linux_build_qt.yml
.github/workflows/scripts/linux/appimage-qt.sh
.github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in

Backported from: https://github.com/stenzek/duckstation/pull/3251
This solves the common problem of the appimage needing libfuse2 to function.  
Better compatibility with newer distros.
Test if the build succeeded and the appimage works.

CI/Appimage: Use fuse3 compatible appimagetool

---

pcsx2/x86/ix86-32/iR5900.cpp

Fixed a heap-buffer-overflow in `recompileNextInstruction`.
Fixes a heap-buffer-overflow found by ASAN.
```
00000001	23:44:41	[7340] =================================================================	
00000002	23:44:41	[7340] ==7340==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x119da91652c7 at pc 0x7ff6cd94ce59 bp 0x0023e8bfe870 sp 0x0023e8bfe8b8	
00000003	23:44:41	[7340] READ of size 1 at 0x119da91652c7 thread T1	
00000004	23:44:41	[7340]     #0 0x7ff6cd94ce58 in _recIsRegReadOrWritten(EEINST*, int, unsigned char, unsigned char) C:/src/pcsx2/pcsx2/x86/iCore.cpp:911:9	
00000005	23:44:41	[7340]     #1 0x7ff6cd1a951f in recompileNextInstruction(bool, bool) C:/src/pcsx2/pcsx2/x86/ix86-32/iR5900.cpp:1717:13	
00000006	23:44:41	[7340]     #2 0x7ff6cdc9ab9c in …
```

fix heap-buffer-overflow in `recompileNextInstruction`

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/ShaderCacheVersion.h

GS: Match data types to be the same in shaders.
Fixes shader warnings on gl on linux, mesa, or windows using mesa gl drivers.
Also changed dx and vk for consistency.
Test GOW on OpenGL, see if the warnings are fixed using mesa drivers on linux/windows.

GS: Match data types in shaders to be the same when doing bitwise operations.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Extends the bilinear upscale fix to cover dirty depth this fixes the broken textures in ATV Offroad Fury 2 when upscaling.
Fixes #7611 
Before:
After:
Broken textures bad.
Make sure games that already use Bilinear Upscale Nearest in the db still work correctly.

GS/HW: Extend Bilinear Upscale Hack to dirty depth

---

pcsx2/Pcsx2Config.cpp

Updates the macOS version to use the directory containing the bundle as the AppRoot, instead of the directory of the executable file.
Currently portable mode does not work properly on macOS; you must put the `portable.ini`/`portable.txt` and all of the user data inside of the app bundle instead of next to it. This is a problem as it breaks app bundle integrity, and if the user replaces the app bundle, e.g. for an update, all of their data could be lost.
I've tested the emulator both without portable mode and with a `portable.txt` next to the app bundle, in both cases the user data is placed in the expected location.

Config: Use directory containing bundle as AppRoot on macOS.

---

pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS/HW: Rename blend second pass to blend multi pass.
Easier if I want to add more passes.
Smoke test some dx titles that got fixed with multipass.
Edit: ran dump run.

GS/HW: Rename blend second pass to blend multi pass.

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp

GS/DX11: Fix feedback write 1 null pointer crash.
We were using the wrong texture as the source, should be dTex when copying.
Fixes crash on dx11 on DoMerge when merging 2 source textures.
DX11, OpenGL and possibly Metal differ than DX12 and Vulkan, something to look in to in the future.
Fixes Dynasty Warriors 2 crashing on dx11.
Check if the dump doesn't crash anymore on dx11.
Rename .zip to .xz [Dynasty Warriors 2  Shin Sangoku Musou - Garbage on post character selection screen with software rendering_2.gs.zip](https://github.com/user-attachments/files/16617551/Dynasty.Warriors.2.Shin.Sangoku.Musou.-.Garbage.on.post.character.selection.screen.with.software.rendering_2.gs.zip)

GS/DX11: Fix feedback write 1 null pointer crash.

---

3rdparty/imgui/include/imconfig.h
3rdparty/imgui/include/imgui_internal.h
3rdparty/imgui/src/imgui.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiManager.cpp

Fixes the nav menu appearing when holding square and also removes some obsolete functions.
Fixes #11699 
Tidy code is good code also the nav menu is annoying.
Make extra sure this time that everything works and no strange boxes take over your screens.

3rdparty/imgui: General fixes

---

pcsx2/Achievements.cpp
pcsx2/Achievements.h
pcsx2/VMManager.cpp

This PR adds RetroAchievement icon support to our Discord's Rich Presence implementation.
**NOTE: This require said game to have Rich Presence and achievement support available for that game on RCheevos, otherwise the icon will not show up!**
Preview:
Coolness Factor 2x
See if the icon shows up properly and nothing else breaks.

DiscordRPC: Add RCheevos game icon support.

---

pcsx2/Pcsx2Config.cpp

Adds the ability to put a relative path in the `portable.txt` file to place portable data in a specific relative location.
Note that this only applies to `portable.txt` and not `portable.ini` as adding an INI format definition for this would be a more complex. If it doesn't matter whether it's an actual INI formatted file, I could just add it in as an alternate path and read in the same way, but in the interest of respecting the file type I've just added it for the TXT file currently.
This allows users to have a portable setup without all of the various data files and directories in the same directory as the executable. For example, the data could be put in a sub-folder, or in a different directory on the same drive used for various emulator data.
Put a `portable.txt` next to the emulator …

Config: Allow specifying portable directory relative path in portable.txt

---

bin/resources/GameIndex.yaml

Removes "Disney's" from two Phoenix Games titles which are not at all associated with Disney.
These two titles were mistakenly prefixed with "Disney's". While their box art and naming is somewhat convincing, these are not in fact real Disney titles.

GameDB: Correct two Phoenix Games title names

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

GS/HW: Implement PABE(Per pixel alpha blending) on accumulation and add optimizations.
PABE accumulation blend:
Idea is to achieve final output Cs when As < 1, we do this with manipulating Cd using the src1 output.
This can't be done with reverse subtraction as we want Cd to be 0 when As < 1.
Blend mix is excluded as no games were found, otherwise it can be added.
PABE Disable blending:
We can disable blending here as an optimization since alpha max is 128
which if alpha is 1 in the formula Cs*Alpha + Cd*(1 - Alpha) will give us a result of Cs.
Better accuracy using hw or hw/sw blend mixed mode, less barriers/draw calls, more speed.
Dumps to benchmark/test:
[PABE.zip](https://github.com/user-attachments/files/16695561/PABE.zip)
Smoke test metal if it still works.
The following games will …

GS/HW: Implement PABE(Per pixel alpha blending) on accumulation and add optimizations.

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Fixes #11716
(Attempting to transition textures in the middle of the present render pass)
Less crashy
Test things from #11716

Vk: Don't try to transition present source during present

---

pcsx2/USB/usb-eyetoy/cam-windows.cpp

Fix CaptureEye corruption on dark images.
CaptureEye uses 16 consecutive zeros as padding to fill the iso packets when no data is available.
For 2000's cameras it wasn't a problem because they were unable to capture pure black images without noise, but now we have better cameras.
Theoretically it's enough to have a single non-zero pixel every 16 bytes, but it's easier to limit the grayscale range between 1 and 255.
Fix CaptureEye corruption on dark images.
none

USB: Fix CaptureEye corruption on dark images

---

pcsx2-qt/GameList/GameListWidget.cpp

Application focus set to Game Library on start-up, after switching between list/grid view, and after closing a game.
Improved keyboard navigation. Users can navigate the Library and play/exit games with just the arrow keys and Enter/Esc.
Boot. Press arrow keys to select a game. 
Press Enter to play game. Press Esc to exit game. Press arrow keys to select another game.
Change view. Press arrow keys to select a game.
Remove games from directory. Rescan. Restore games to directory. Rescan. Press arrow keys to select a game.

Qt: Set focus to Game Library for improved keyboard navigation

---

pcsx2/ImGui/FullscreenUI.cpp
pcsx2/VMManager.cpp

Removes the option to make literal per-game mappings, and PCSX2's ability to read them. Instead introduces the same input profile selector found in the normal UI to Big Picture. 
This allows the same functionality of having controls customizable on a per-game basis, but in the same clean sandbox of profiles as in the desktop UI. This in turn fixes the issues we've been having with controls being seemingly "stuck", because they are crammed into game properties files when the user never really wanted them to be.
Create a new profile, set mappings which purposely don't make sense or are partially incomplete so that it is extra obvious when you have one profile vs another enabled, then test swapping profiles via each UI mode and using said controls. Swap profiles in and out both in desktop …

Big Picture: Remove ability to make per-game controls

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/ShaderCacheVersion.h

GS/HW: Further expand blend multipass.
For formulas:
```
Cs*Alpha + Cd*(1 - Alpha).
Cd*Alpha + Cs*(1 - Alpha).
```
Where Alpha is higher than 1 and is either As or Af.
Improves accuracy on basic blend on dx11/12.
Dump run is fine, smoke test all renderers (vk and gl with and without barriers disabled.
Some comparisons/fixes:

GS/HW: Further expand blend multipass.

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/VMManager.cpp

Changes to CPU detection and feature detection text as well as moving texture preloading into advanced settings.
More text more gooder.
Make sure the things work and that texture preloading setting still works already checked this one but will be good to double check.

Misc: Minor text and settings changes

---

pcsx2-qt/Debugger/Models/BreakpointModel.cpp
pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/SymbolGuardian.cpp
pcsx2/DebugTools/SymbolGuardian.h

Some very minor changes have been made to fix some compiler warnings on Windows. All except for the breakpoint one were introduced by [my symbol table PR](https://github.com/PCSX2/pcsx2/pull/10224).
Warnings are undesirable (except for Without Warning).
Build on Windows.

DebugTools: Fix some compiler warnings

---

pcsx2-qt/MainWindow.cpp

Properly toggled the toolbar and system menu savestate options. Before it was checking if there was a proper CRC and serial, but that isn't relevant anymore.
Saving state in BIOS was supported and worked fine with hotkeys, the UI just didn't reflect that.
Try to use savestates in games and the BIOS. Ensure that when the VM is shutdown the toolbar and system menu properly disable savestate buttons and such.

UI: Enable "System" menu and toolbar savestate options while running the BIOS

---

common/FileSystem.cpp
common/FileSystem.h

Revert of [`c8a3e5a` (#11739)](https://github.com/PCSX2/pcsx2/pull/11739/commits/c8a3e5a9ec4b41ae8c268de78414942b726c9e1f)
My previous PR broke the handling of symlinks on Linux, so let's revert that.
No more broke
See if i didn't broke anything else for real this time

 FileSystem: Fix handling of symlinks

---

pcsx2/ImGui/FullscreenUI.cpp

This PR adds fixes that i missed from the previous PR.
See commit list for changes.
Fix 100
See if i broke anything

FSUI: Misc Fixes

---

pcsx2/Hotkeys.cpp

Flipped the order of Hotkey action "SaveStateAndSelectNextSlot" to "SelectNextSlotAndSaveState"
Flipped the order of hotkey actions from
Creating a Save State -> Selecting Next Save Slot
to
Selecting Next Save Slot -> Creating a Save State
The intention behind this is to streamline the quicksave/quickload process, as with this change the LoadStateFromSlot action will load the most recent Save State instead of the oldest one.

Hotkeys: Implement "SelectNextSlotAndSaveState"

---

pcsx2/VMManager.cpp

Removes a leftover check against the old "use per-game controls" setting which can be lingering in game properties files, allowing profiles to actually load without interference.
Partially fixes #11764. Will allow profiles to load properly for anyone who hasn't cleared lingering pad settings out of their game properties.
Create a profile with bindings very different from shared, switch profiles and verify controls still switch as intended.

Config: Prevent pad settings lingering in game properties blocking profiles

---

pcsx2-qt/Settings/AdvancedSettingsWidget.ui

Allows the `NTSC Frame Rate` and `PAL Frame Rate` options in the Advanced settings to go up to 1000.0, instead of 99.99.
This option is useful for either:
- Playing a game at higher speeds without speeding up the audio.
- If the game physics use delta time, then you get higher framerates at the same speed. Playing above 60 FPS is cool (and for PS2 games, there's no other way to do it while keeping a normal audio).
- Some games don't use delta time, but have a static internal "Game speed": for instance, you can set it to half speed with a cheat code, set the framerate to 120 FPS, and get a 120 FPS experience at normal speed.
Regardless of how it might break things, this option was already there, in the Advanced settings, I'm just raising the limit.
(Also, the setting was not in the …

Config: Set `{ntsc,pal}FrameRate` bounds to 10-300 Hz

---

pcsx2/VMManager.cpp

When resetting the VM we didn't notify the rc client
Game achievement state wouldn't be reset when you reset the VM
See if https://github.com/PCSX2/pcsx2/issues/11795 is fixed

Achievements: Reset client state on system reset

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Added mipmapping description similar to the help/hover text of other items. Wording is my own phrasing.

UI: Update mipmapping help description

---

3rdparty/rcheevos/src/rc_client.c
pcsx2-qt/Settings/SettingsWindow.ui
pcsx2/Achievements.cpp
pcsx2/VMManager.cpp

This PR further improve the icon url mainly to not call the API twice to retrieve the URL, also checks whether the URL exist or not.
Also make the Settings list word wrapped to account for longer text length due to localization.
Betterer Code
Already tested, shouldn't affect anything for the most part/

DiscordRPC: Further improve icon url call

---

bin/resources/GameIndex.yaml

The videos in #4886 would freeze after playing for 2-6 seconds, rendering the game unplayable without skipping the videos in a timely manner. In simple words, players need to skip the videos quickly or risk losing all of their progress.
I've already tested that the gamefix works.

GameDB: Add Skip MPEG Hack to Never7

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Reduce sw/hdr colclip in more cases.
When doing `Cs*Alpha + Cd*(1 - Alpha)` or `Cd*Alpha + Cs*(1 - Alpha)` with an alpha of 128 or lower we don't really need to hdr or sw colclip blend it because colour range of the result will be between 0-1 (0-255) without it overflowing.
Also update previous optimizations to include Ad cases when RTA is already scaled.
More speed, less barriers/draw calls/copies.
Notable dump mentions:
```
dbz_bt2_oi_imine_depth Draw Calls: -26 [991=>965] Render Passes: -25 [69=>44] Barriers: -1 [12=>11] Copies: -25 [27=>2]
Power_Rangers_-_Super_Legends_SLUS-21679_20221215160520 Draw Calls: -20 [109=>89] Render Passes: -26 [56=>30] Barriers: -7 [9=>2] Copies: -20 [21=>1]
Tales_of_Destiny_Directors_Cut_SLPS-25842_20221015223409 Render Passes: -1 [7=>6] Barriers: …
```

GS/HW: Reduce sw/hdr colclip in more cases.

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/ImGui/ImGuiOverlays.cpp

This PR adds the currently used GPU string name to the OSD as part of the HW Info settings.
Preview:
Ease the user support process.
Check every renderer, ~~DX11 is currently crashing which im still working on right now~~ Fixed.

OSD: Add GPU Info

---

pcsx2-qt/QtHost.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Pcsx2Config.cpp

Renames and splits the G and V values on the OSD into FPS and VPS and adds Speed with a target percentage eg Max for uncapped. A big thanks to Kam for helping me get into a 3 day long fist fight with the OSD to get the layout correct.
Current display;
PR display:
It will more accurately represent what they do and to make it easier for users to understand what a game is running at and what the emulator is running at as these names are inline with other emulators who use the same terminology for statistics.
Test different combinations of OSD settings between FPS VPS and Speed and make sure these all display and function correctly under different internal FPS type detections eg Privileged Register Blit ect.

OSD: Rename and split G and V values

---

pcsx2-qt/Debugger/SymbolTree/SymbolTreeDelegates.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeDelegates.h
pcsx2-qt/Debugger/SymbolTree/SymbolTreeModel.cpp

This fixes two minor issues with the symbol trees:
- When you click a checkbox in the symbol tree (displayed for bools) it will now write the new value back to memory immediately instead of waiting for you to deselect the checkbox.
- When you reset the children of a symbol tree node it will now populate their values from memory immediately instead of waiting for them to update. This prevents flicker.
It makes the check box widgets delightful to use.
- Create a global variable of type bool for some variable where the result is immediately apparent on screen, and check and uncheck the box repeatedly until you're satisfied that the new behaviour is better.
- Now make an array and click the "Reset Children" context menu option on it, and observe that the children don't flicker.

Debugger: Improve the responsiveness of some symbol tree widgets

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Fix/cleanup pabe optimization condition.
We should check only if As max is 128, also make sure we are checking the original Alpha C value as it could have been modified for an optimization.
Bugfix.
Follow up from https://github.com/PCSX2/pcsx2/pull/11737 test the same games mentioned in that pr.

GS/HW: Fix/cleanup pabe optimization condition.

---

.github/ISSUE_TEMPLATE/feature_request.yaml

We will be trying out a new feature request labelling system.
Feature requests (abbreviated as FR) are going to have a `FR: Awaiting Consideration` label once created.
Once a team member looks over it they will remove the  `FR: Awaiting Consideration` label and categorize the feature request based on their complexity and priority.
There are a new bunch of labels for this system:
Priority
Complexity
I hope that this helps new and current contributors find tasks that need to be worked on. I also hope that this helps with this years Hacktoberfest which we plan on participating in.

gh: update the feature request template labels

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp

Follow up from #11812 this improves the spacing a smidge on the main window OSD stats to make them look less jank.
Current:
PR:
The previous spacing looked pretty bad.
Test if the stats still function correctly.

OSD: Improve main window stat spacing

---

bin/resources/GameIndex.yaml

Align sprite no longer works, requires Half Pixel Offset (Normal Vertex).
Changed all instances of Align Sprite to Half Pixel Offset in all versions of Pro/TOCA/V8SC/DTM Race Driver.
Vertical lines persist with default Align Sprite in recent nightlies, hence the change to normal vertex, as the comments helpfully point out.

Fix Pro/TOCA/V8SC/DTM Race Driver Vertical Lines

---

pcsx2/x86/microVU_Compile.inl

Fix ASAN container-overflow in mVUsetupRange.
When the iterator is erased in `pcsx2\x86\microVU_Compile.inl:94`
```
it = ranges->erase(it);
```
These references get invalidated.
```
s32& rStart = mVUrange.start;
s32& rEnd = mVUrange.end;
```
These variables should not be references.
Build with `-fsanize=address` and run pcsx2.
```
=================================================================
==23240==ERROR: AddressSanitizer: container-overflow on address 0x12211936e0d0 at pc 0x7ff67f43d287 bp 0x007a23bf3c60 sp 0x007a23bf3ca8
READ of size 4 at 0x12211936e0d0 thread T3
#0 0x7ff67f43d286 in mVUsetupRange(microVU&, int, bool) C:/src/pcsx2/pcsx2/x86/microVU_Compile.inl:90:23
#1 0x7ff67f42f246 in mVUcompile(microVU&, unsigned int, unsigned long long) …
```

microvu: fix ASAN container-overflow in mVUsetupRange

---

pcsx2/x86/microVU_Compile.inl

Fixes a regression introduced from #11818 
Games were broken (specifically P4 and GTA: LCS)
Ensure that there is are no broken or flickering textures / primitives.

microVU: fix block clearing regression

---

pcsx2/DebugTools/DebugInterface.cpp

Try to allow debugger kernel memory access.
I changed it long ago to allow 0xBFCxxxx access but this caused crashes when accessing invalid 0x8xxxxxxx mappings.
I then partially reverted this change, and now I need kernel access again so this is my attempt at having both mappings work and not crash.
Access kernel memory and beyond and hope it doesn't crash.

DebugInterface: Try to show the kernel memory mappings, again

---

pcsx2-qt/QtKeyCodes.cpp

This addresses an issue present in EQOA where SHIFT only worked on alpha characters. SHIFT now is detected and works to produce symbols as well. It also should address most issues reported in https://github.com/PCSX2/pcsx2/issues/7605.
This pull request introduces functionality that allows the SHIFT key to be properly detected for non-alpha characters. The change fixes an issue present in EQOA where symbols (e.g., "!" or "@") were not being produced when SHIFT was pressed in conjunction with number keys and other symbol-producing keys.
The previous behavior only detected SHIFT for alphabetic characters, limiting the usability of symbol entry. This change ensures that symbols can be correctly produced when the SHIFT key is pressed alongside other keys, addressing a specific issue in EQOA …

Qt: Fix for keyboard SHIFT with non-alpha characters

---

pcsx2/CDVD/CDVDcommon.cpp
pcsx2/CDVD/CDVDcommon.h
pcsx2/CDVD/CDVDdiscReader.cpp
pcsx2/CDVD/CDVDdiscReader.h
pcsx2/CDVD/CDVDisoReader.cpp
pcsx2/CDVD/Darwin/IOCtlSrc.cpp
pcsx2/CDVD/Linux/IOCtlSrc.cpp
pcsx2/CDVD/Windows/IOCtlSrc.cpp

Added cdvdTrack, cdvdTrackIndex, changed sub Q mode field to ADR
- Prep work for track-based formats like CHD, BIN / CUE. Using cdvdTrack as a common type for all track reading formats including CDVD Disc reader. 
- [Other than that, moar accuracy](https://psx-spx.consoledev.net/cdromdrive/#subchannel-q) 
Already tested, PR makes no significant changes to CD-based games outside of more correct SubQ reads and fixes Track layout in array. This fixes Dance Factory by pushing tracks into, 0 indexed array instead of 1 indexed

CDVD: Added cdvdTrack, cdvdTrackIndex, assigned subQ from hardware reads

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
pcsx2-qt/Settings/MemoryCardConvertDialog.cpp
pcsx2-qt/Settings/MemoryCardConvertDialog.h

Added a permissions check during the conversion of a memory card. It occurred to me that if somehow the permissions change during the setup of the conversion, then it will finish successfully, but wont be copied over to the new directory.
Furthermore, I also made a slight modification to the `build-dependencies.sh`, as I had an error when using curl.
More specifically: `curl: (33) HTTP server does not seem to support byte ranges. Cannot resume.`
Its just a bug fix. Helps user understand what went wrong.
- Have permissions to the memcard directory
- Select a memcard for conversion
- When the popup is displayed, change permissions of the directory to nobody (`sudo chmod 000 ./memory_save`)
- Start conversion
This time you should get an error popup.

BugFix: Error popup on insufficient permissions during memcard conversion

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Make sure it's not a channel shuffle when the alpha of a target is used as source.
The alpha of a target used a source is meaningless to us, since it's not really an indexed texture.
Fixes https://github.com/PCSX2/pcsx2/issues/2279
Dump run looks good, check variety of games, also mentioned in: https://github.com/PCSX2/pcsx2/pull/11010

GS/HW: Make sure it's not a channel shuffle when the alpha of a target is used as source.

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Counters.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

Add native pixel ratio 640:448 (10:7) for some games.
Most games have an internal native pixel ratio of 640:448 (10:7), which is then stretched to 4:3, and the developers at the time were also well aware of this. So 4:3 usually gets the correct ratio. However, there are always exceptions, and some game developers seem to insist on using the original pixel ratio instead of 4:3 to express the true effect of the game. If still stretch it to 4:3 in pcsx2, causing the y-axis to be stretched by 7.14% and the character to look a bit thin and long visually.
For example:
Tekken Tag Tournament
4:3 ratio
native ratio
Sengoku Basara X
4:3 ratio
native ratio
Tenchu: Fatal Shadows
Although its internal resolution is 512:448, it seems to follow the 10:7 ratio.
4:3 ratio
10:7 ratio
test these games …

Add native pixel ratio 640:448 (10:7)

---

pcsx2/Patch.cpp

Implement a new `dpatch` command 
The length of the dpatch line is dynamic and user controlled
`dpatch=<version/type>,<# of patterns>,<# of replacements>,...`
**As of this PR the only valid version/type is 0. This is to prevent the need to break backwards compatibility in the future**
After these first three sections you put the patterns and replacements. The format of those are identical:
`<offset>,<value>`
An example is as follows:
`dpatch=0,3,1,0,8FA20000,4,02002025,8,24420010,8,00000000`
This line has 3 patterns and 1 replacement
It looks for the following set of instructions
```
0 | 8FA20000
4 | 02002025
8 | 24420010
```
and will replace offset #8 with 00000000
The values are a fixed 32 bits because **this only works on code memory**. Dynamic patches only work on the EE recompiler …

Implement dynamic patching support in pnaches

---

pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DebugInterface.h
pcsx2/DebugTools/MIPSAnalyst.cpp
pcsx2/DebugTools/MIPSAnalyst.h
pcsx2/DebugTools/SymbolGuardian.cpp

I've been planning to change the behaviour of the `MIPSAnalyst` so that it at first only reads from the ELF file on the disc, and then later the user can re-run it on demand if the code in memory was overwritten.
This PR implements the first half of that plan. I've added a `MemoryReader` interface for the `MIPSAnalyst` to use which is implemented by the debug interfaces and a new `ElfMemoryReader` class.  The `SymbolGuardian::ImportElf` function has been updated accordingly.
While I was at it, I also fixed some error handling logic in `MIPSAnalyst::ScanForFunctions`. In practice I believe this was harmless since `SymbolDatabase::get_symbol_source` should really never fail, however it's still nice to get this fixed.
The previous behaviour resulted in a race condition where …

DebugTools: Scan for functions from the ELF instead of from memory

---

pcsx2/IopBios.cpp

Disables the 'clean_path' function on Windows that replaces back slashes with forward slashes.
It's currently breaking WSL paths because you can't use all forward slashes when accessing the WSL filesystem.
Use ulaunchelf on Windows and try to load an elf from a WSL path.
fixes #11843

iop/hostfs: don't replace back slashes with forward slashes on Windows

---

pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DisassemblyManager.cpp

Instead of using the unsafe vtlb access functions that can cause tlb misses and trigger MMIO handlers I've migrated the debugger to use the safer ones.
This seems to have fixed the recursion issue when pause-on-tlb-miss is enabled.
It also wasn't great that the debugger can read guest FIFOs and such.
Enable pause-on-tlb-miss, open the debugger, and reset a bunch of times and see if PCSX2 crashes.
Test and see if the debugger still works fine.
Fixes #11594

Debugger: Use safe vtlb read/write methods

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Clamp TW/TH to 11, as GS memory loops around 2048, anything higher than 12 causes a crash when texture mapping isn't supported like in Direct3D11.
Fixes https://github.com/PCSX2/pcsx2/issues/11749
Test https://github.com/PCSX2/pcsx2/issues/11749, test other games.
No dump diffs on dx11 or vulkan.

GS/TC: Clamp TW/TH to 11 in source flush.

---

pcsx2-qt/Settings/AdvancedSettingsWidget.cpp
pcsx2-qt/Settings/AdvancedSettingsWidget.ui
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.ui
pcsx2/ImGui/ImGuiOverlays.cpp

> Don't you hate it when you come up with more ideas just minutes AFTER the PR has been merged?
This PR further improves upon #11848 by:
- Adding the "Close Menu" legends to the Save State Selector, letting the user know that they can do so.
- Moving all the savestate related options from interface settings to the advanced settings.
Preview:
QoL Improvements.
Test the new settings and see if i broke anything.

Savestate: Misc Improvements

---

pcsx2/IopBios.cpp
pcsx2/SaveState.cpp
pcsx2/SaveState.h

[SAVEVERSION+]
Save host file handle and position information in save states, and reopen handles at the correct position when states are loaded.
Note: This is my first contribution, and I am still learning PCSX2's codebase, as well as best C++ practices. Criticism is appreciated!
Currently, if a homebrew/game uses Host Filesystem to stream files, using save states can cause issues. For example if the streamed file is audio, it can cause audio to be desynced, stop entirely or even play the incorrect song. This is caused by open file handles no longer existing or the file offset pointer being different when loading a savestate.
@penguino118 has graciously created a homebrew elf that demonstrates this issue. The program streams audio from `GTA.wav`and `HMU.wav`. (Assets are copyright …

HostFS: Retain File Handles in Save States

---

pcsx2-qt/MainWindow.cpp

Clears the text of `m_status_verbose_widget`
When starting emulation, either onVMResumed or onVMPaused is called depending on if Pause on start is set.
The emulator stop prompt will pause the emulator, if you accept, this will backup the previous value of `m_status_verbose_widget` to `m_last_fps_status` and set the text of `m_status_verbose_widget` to "Paused"
When you that start the emulator again, with Pause on start enabled, onVMPaused is called again, which will overwrite the backup text in `m_last_fps_status` with the value of `m_status_verbose_widget`, which was left as "Paused" from the previous run.
When you unpause, the text of m_status_verbose_widget is set to the value of m_last_fps_status, which contains "Paused" leading to no visual change.
This PR resets the value of …

QT: Clear m_status_verbose_widget text on VM stop

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
.github/workflows/scripts/macos/build-dependencies-universal.sh
.github/workflows/scripts/windows/build-dependencies-arm64.bat
.github/workflows/scripts/windows/build-dependencies.bat
cmake/SearchForStuff.cmake

Qt 6.8 is now actually out so lets just roll with that. Mac is doing something weird that I am not qualified to figure out so I will leave that to someone else.
Fixes #11097 
Fixes and security fixes are good.
Make sure PCSX2 functions correctly and nothing got broken by the update such as menus themes checkboxes ect.

Deps: Update to Qt 6.8.0 on Windows and Linux

---

pcsx2/IopBios.cpp

We were tracking file descriptors of files that were never properly opened.
Also included a check when saving states to ensure that the hostfs file actually existed on the host device. If not we fix `pos` to zero but don't try and exclude it from the state.
Crashing when trying to save a state is bad.
Save and Load states with homebrew that use hostfs.
See if the reproduction steps on https://github.com/PCSX2/pcsx2/pull/11875 still work.

IOP HLE: Only track handles to valid files.

---

pcsx2/GS/GS.cpp

OSD Performance Text in SW mode has overlapped keywords which confuses if D means Drawcall or Download.
This commit fixes it by renaming few stuff and naming it correctly.
D vs D is off
Make sure OSD is OK in SW.

OSD: Update OSD Text on SW mode so no overlap keyword appears

---

pcsx2-qt/QtKeyCodes.cpp

Call  `map_text_to_keycode()` only if we're using Shift modifier and also if we're not using Keypad modifier (or else "NumpadAsterisk" would return "8" keycode and "NumpadPlus" would return "Equal" keycode.).
See #11838, currently Keypad "*" and "+" return incorrect keycodes due to the function not checking for Shift modifier.
It's also a big issue as an AZERTY FR keyboard user because without a Shift modifier check it messes up heavily with default bindings, especially R2 and R3, both keys being mapped to the same "Apostrophe" keycode. See my 2nd reply in #11838 for more details.
Although this is much better with these modifiers checks, this is still not a perfect solution, for example on AZERTY FR "5" and "%" are on 2 different keys and `map_text_to_keycode()` will map "%" to "5" …

Qt: Call 'map_text_to_keycode()' only when Shift modifier is being used

---

pcsx2/DEV9/DEV9.cpp

Correct behaviour of `SPD_R_20`/`SPD_R_INTR_CAUSE`
Unify Speed 16bit and 8bit reads/writes
PSBBN writes 1 to this reg, but does not expect it to change the value of `SPD_R_INTR_STAT`
While I'm unsure as to what this reg is for, however, it appears to always return a value of 1.
The homebrew PS2SDK might use this reg to detect if the DEV9 unit is official or not via a 16bit read.
Previously we would return 0.
PSBBN performs 8bit IO to the Speed regs (such as to the REV regs), which we didn't fully implement.
Such software should be able to access these regs correctly with this PR.
Fixes https://github.com/PCSX2/pcsx2/issues/11893 and partially https://github.com/PCSX2/pcsx2/issues/11894
Test network games
Test network homebrew

DEV9: Correct bad Speed reg implementation and unify 8bit & 16bit regs.

---

pcsx2/GS/Renderers/DX11/D3D.cpp

GS: Default to OpenGL on intel GPUs that support it.
Feature level 12 requirement.
Intel crashes have been fixed since https://github.com/PCSX2/pcsx2/pull/10992
Arc still defaults to Vulkan btw.
Better defaults.
For intel crash, test Persona 3 FES intro video. Also test performance, test if Auto picks up GL on Broadwell and up chips and works fine (technically we could support Haswell too).

GS: Default to OpenGL on intel IGPUs that support it instead of DX11

---

pcsx2/USB/usb-pad/usb-pad-sdl-ff.cpp

When updating a constant force FFB effect, unconditionally start the effect regardless of whether it is currently running.
Certain modern direct-drive wheels such as the Moza R5, R9, etc. implement timeouts for FFB constant forces, and only restart their 'timeout clock' when the force is started, regardless of whether the effect is regularly being updated. I've read similar-sounding complaints from users of the Logitech G29, but I don't have that wheel on hand to test with.
In Gran Turismo 4 (and likely other titles with wheel support unless their implementation differs significantly), Moza wheels will experience sudden, sporadic dropouts of FFB during racing. The FFB won't return until the wheel returns to neutral and the car is settled, as this is when the game (conditionally) issues a …

USB: Work around FFB dropouts with certain modern wheels

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/ImGui/ImGuiOverlays.cpp

This PR adds further label to the OSD's frametime counter.
Preview:
And also small tweak it so that we don't query the adapter name twice on DX11.
Making it easier to distinguish between entries on the OSD a little bit more.
See if the formatting is correct and nothing else broke.

OSD: Clarify Min/Avg/Max label to Frametime counter

---

pcsx2/HwWrite.cpp
pcsx2/ps2/Iop/IopHwWrite.cpp

Each CPU can trigger an SBUS interrupt on the other, this implements that.
Only confirmed use case is Linux IRQ relay.
Just test some stuff, this should not impact anything normal.

IOP/EE: Add SBUS interrupts

---

pcsx2/DEV9/ATA/ATA.h
pcsx2/DEV9/ATA/ATA_State.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdExecuteDeviceDiag.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdPIOData.cpp
pcsx2/DEV9/ATA/Commands/ATA_Command.cpp
pcsx2/DEV9/DEV9.cpp

Support 8bit IO.
Implement pending interrupts, per ATA spec.
Disable interrupts in the initial/reset state.
Don't drop writes to `ATA_R_CONTROL` while mid command.
- PSBBN and PS2 Linux use 8bit IO to talk to most ATA regs
- PSBBN and PS2 Linux rely on pending interrupts during read DMA
- They will issue a ReadDMA command with IRQs disabled, enable IRQ interrupts and wait for the command completion interrupt
- We currently complete the command before IRQs are enabled, so pending interrupts are required here.
- PS2 Linux seems to not expect interrupts to be enabled on bootup.
- It issues a HDD identify command and then gets confused if it receives a PIO data ready interrupt, after a multi second delay it will continue.
- PSBBN's boot enables interrupts before handing over to linux so runs …

DEV9: Various improvements to ATA interrupts & Support 8bit IO to ATA regs

---

pcsx2/DEV9/smap.cpp

Relocate the Adapter Detection Hack
Relocate call to resetting the network backend (tap/pcap/sockets)
The Adapter Detection Hack sets `TXEND`/`RXEND`/`TXDNV` bits in the `SPD_R_INTR_STAT` in order to pass a check during initialisation.
PSBBN (see https://github.com/PCSX2/pcsx2/issues/11746), however, clears `TXEND`/`RXEND` after we set them, causing it to fail to init.
HW tests indicate that both `TXEND`(expected) & `RXEND`(??) get set when processing `SMAP_E3_TX_GNP_0`.
`TXDNV` also exists, but isn't set during `SMAP_E3_TX_GNP_0` (at least in the init phase), so I'm yet unsure where it comes from.
Additionally, none of the values written to `SMAP_R_EMAC3_TxMODE1` are related to resetting, so move resetting the network backend.
The `EMAC` and `PHY` are reset during SMAP initialisation, so …

DEV9: Move Adapter Detection Hack

---

pcsx2/DEV9/ATA/ATA.h
pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp
pcsx2/DEV9/DEV9.cpp
pcsx2/DEV9/DEV9.h
pcsx2/IopDma.cpp
pcsx2/IopDma.h

Implement the SPEED <-> FIFO (instead of pretending it exists)
Handle deferring completing DMAs, based on `XFR_CTRL`'s `DMAEN` bit (and also fix our define).
Alter our implementation of resetting the fifo counters via DBUF_STAT writes, based on info I've been provided.
I previously thought the emulating the FIFO buffer (instead of just its counters) was required for PS2 Linux.
Later testing reviled this wasn't needed, but I'd already added this buffer, so here it is.
PS2Linux and PSBBN start a DMA before sending a Read command, but leave the SPEED's DMA disabled until after sending said command. Existing code would complete the DMA without transferring data.
Fixes https://github.com/PCSX2/pcsx2/issues/11918
Test HDD games and homebrew

DEV9: Handle deferring DMAs & don't fake the SPEED-HDD FIFO

---

pcsx2/DEV9/ATA/ATA.h
pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdSMART.cpp
pcsx2/DEV9/ATA/Commands/ATA_Command.cpp

Stubs SMART Save Attributes sub-command.
Implements Recalibrate command.
Exposes Set Multiple Mode.
These commands are used by PS2 Linux
SMART `SaveAttributes` is stubbed as we don't actually record any SMART data.
`Recalibrate` seeks to the 1st sector. Will always succeed as if we can't access the start of a file then we probably have bigger problems.
`SetMultipleMode` affects the `ReadMultiple` command. I had previously implemented these commands, but didn't expose them as nothing before had used these over `ReadSector` or `ReadDMA`.
Fixes https://github.com/PCSX2/pcsx2/issues/11892
This is hopefully the second to last DEV9 pr that PS2 Linux needs (at least until it hits TLB-miss town).
Test HDD software

DEV9: Add ATA commands used by PS2 Linux

---

pcsx2/Memory.cpp

Puts EE writes to IOP mem through a handler that calls the write function for IOP mem. This ensures we clear IOP code blocks when EE writes to it.
The b000p demo (see #3983) has a LoadModuleBuffer patch that is applied with memcpy from the EE. Previously we didn't properly invalidate the cache when this was applied.
Check that b000p works and nothing broke 🤷

EE: vtlb handler for writes to IOP mem

---

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp
pcsx2-qt/Settings/GameCheatSettingsWidget.h
pcsx2-qt/Settings/GameCheatSettingsWidget.ui

resolves #11193
I felt like `QSortFilterProxyModel` would be the simplest method to add filtering/search to the cheats list. For this, I had to replace the use of `QTreeWidget`  with a combination of `QTreeView` and `QStandardItemModel` in `Settings/GameCheatSettingsWidget`.
I saw the feature request and I thought this would be a great thing to have, especially for games with a large cheat list. 
I aimed to keep everything functioning as it currently is:
- Double clicking any of the columns of a child row toggles the check state
- Double clicking any of the columns of a parent row toggles expand/collapse
- Reloading the list expands all parents
- Filtering is disabled if cheats are disabled
- Checked state is preserved through filtering
More about filtering:
- Filtering is case …

Qt: Add search bar to cheats list

---

pcsx2/DEV9/ATA/ATA.h
pcsx2/DEV9/ATA/ATA_State.cpp
pcsx2/DEV9/ATA/ATA_Transfer.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdPIOData.cpp
pcsx2/DEV9/ATA/Commands/ATA_Command.cpp

Set/Clear the seek bit any any command could need to seek to complete
Implement holding the value of the SEEK bit when en error occurs
PS2Linux actually checks for the SEEK bit to determine if a DMA command completed.
The SEEK bit will be set/cleared based on what happens with the command
With the exception of the Flush command, I've opted not to factor in the actions of the write cache.
The holding/locking of the reported value of the SEEK bit as added here is specified in older version of the ATA spec.
The last of my PSBBN prs, Fixes https://github.com/PCSX2/pcsx2/issues/11924
Test HDD software/games

DEV9: Set/Clear SEEK bit in all relevent commands

---

pcsx2/USB/usb-pad/usb-pad-sdl-ff.cpp
pcsx2/USB/usb-pad/usb-pad.cpp
pcsx2/USB/usb-pad/usb-pad.h

This PR changed a lot over the course of its development as a lot of research was done to ensure this was the correct approach; I ultimately pivoted back to this after digging through everything I could find. As a result, the comment history may be confusing/misleading if read out of context.
- By default, remove the workaround that bypassed the "effect already running" check for constant forces
- Change the length of all FFB effects to SDL_HAPTIC_INFINITY.
- Add a config option to restore the old workaround for wheels that still need it
Getting here has been a bit of a journey, and I'm not sure whether this counts as a victory or a surrender. Some wheels are just... outright bugged. Issues we've been seeing with the Simagic wheel appear to be encountered by some other games such as …

USB: Use infinite duration for FFB forces, make the recently added FFB workaround optional

---

pcsx2/VMManager.cpp

Adds a once per launch warning if a user does not have the renderer set to Automatic or Software.
Some users may change the renderer to a sub optimal option and experience problems with graphical issues performance and driver crashes on certain brands of GPUs. This warning will help point them in the right direction as to why this is happening.
Make sure the warning works correctly.

VMManager: Add renderer selection warning

---

pcsx2-qt/Debugger/CpuWidget.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeWidgets.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeWidgets.h

The local and parameter symbol trees will now check if the program counter is inside or outside the function they're displaying the variables for when deciding whether to reset. The `CpuWidget::reloadCPUWidgets` function now calls `SymbolTreeWidget::updateModel` instead of `SymbolTreeWidget::reset` directly.
Previously the local and parameter symbol trees would reset when single stepping, which would collapse any nodes the user had expanded. This was annoying.
Find a function, create a local/parameter variable with an array type e.g. "int[10]" so you can expand it, then single step inside the function.

Debugger: Avoid resetting symbol trees while single stepping

---

pcsx2-qt/Settings/DebugAnalysisSettingsWidget.cpp

This fixes the symbol sources list in the "Clear Existing Symbols" section of the analysis tab in the per-game settings dialog. Due to a rather silly mistake in [this PR](https://github.com/PCSX2/pcsx2/pull/11901), `DebugAnalysisSettingsWidget::saveSymbolSources` was previously never actually run.
To be fair check boxes and combo boxes are quite similar.
- Launch a game.
- Launch the debugger.
- Open the per-game settings dialog.
- Try checking/unchecking the symbol sources.
- Restart PCSX2.
- Make sure the changes stay.

Qt: Fix symbol sources list in per-game settings dialog

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/DX11/D3D.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS: Check feature level 12 as a requirement when selecting auto renderer on intel.
Just to be on the safe side when selecting OpenGL.
GS/D3D12: Disable DX12 if feature level is not detected.
Intel Haswell doesn't actually support DX12 even tho the device is created which results in a crash,
to get around this check if device can be created using feature level 12 (skylake+).
GS/Qt: Adjust how we handle Default adapter.
Try to resolve it again since it annoys me.
Treat is as empty.
Bugfix, better defaults.
Make sure DX12 still works on amd/nvidia, and Intel Skylake and above.
Make sure OpenGL is auto selected on Skylake and above on intel.
Check log for Vulkan when using Default adapter what GPU is selected.

GS: Misc adapter and vendor detection changes

---

.github/workflows/scripts/windows/build-dependencies.bat
.github/workflows/scripts/windows/qtbase-fix-icon-stretch.patch

Qt alters the size of rectangles used for SE_ItemViewItemDecoration (Icons in Item Views), widening it by 4 pixels
This altered rectangle causes our settings icons to be stretched by 4 pixels when using the native or classic theme on Windows
I don't know _why_ Qt does this.
Look at the icons in the settings window
Go though any other list views to see if something is missing 2 pixels each side (or otherwise squashed).

Qt: Hackfix settings icon stretching on Windows themes

---

.github/workflows/scripts/common/update_base_translation.sh

With how the previous scripts are executed out of order, any strings changes that happens inside BPM will not be picked up by the Qt translation script update on the first run. This PR changes the order of operations for the workflow scripts so that the other scripts for BPM and Glyph ranges are executed first ensuring that the string changes are properly getting picked up by the Qt script as it will be the very last one to be executed.
Fixing the workflow so that all the translations changes are correctly picked up
Nothing for now.

CI: Fix Translation Workflow Scripts Order of Operation

---

pcsx2/ImGui/FullscreenUI.cpp

Should fix #11960
I quickly tested it, seems to work fine. Would like more testing though, I'm not entirely sure why those empty bindings were there in the first place.
Crashing is bad.
Test negcon and jogcon emulation. Test configuring them in the fullscreen UI as well.

PAD: Fix negcon and jogcon BPM crash

---

pcsx2/Patch.cpp

When I implemented dynamic patches in pnaches I accidentally broke the dpatch system in the gamedb.
dpatches in the gamedb were not working.
Test dpatches. Test the ratchet and clank turret dpatch provided in the gamedb.

Patches: Fix a regression that broke gamedb dynpatches

---

.github/workflows/cron_publish_flatpak.yml
.github/workflows/linux_build_flatpak.yml
.github/workflows/release_cut_new.yml

Changes the daily flatpak branch to beta. When a stable release is cut it will push to the stable branch.
Caveat: The stable branch is going to be stuck on a dev build until the next stable release. I don't if it's ideal to merge this at this time??
We have a stable version but you can't use it properly with flathub / flatpak because our dev builds are on the same branch.
I don't know, I'm scared to commit this :laughing: 
resolves #11688

CI: Default to flatpak beta branch

---

bin/resources/GameIndex.yaml

Changed EE rounding mode from negative to positive for Final Fantasy X and the International version, as well as removing obsolete VU0 clamping lines and adding missing HW hacks for the international version of the game.
Fixes the vast majority of FFX's FPU glitches as well as fixing a major cutscene bug without breaking anything more than what the current config already breaks.
EE clamping fixes reverse controls and characters and enemies facing the wrong way during battles, everything else is affected by EE rounding and EE division rounding.
VU0 clamping affects nothing.

GameDB: Final Fantasy X Optimal FPU config

---

pcsx2/ImGui/FullscreenUI.cpp

Move setting the cursor to the beginning of the Game Grid drawing loop.
Previously we would also set the cursor for the next item, even when we where the last item.
If the GameGrid was drawing an empty list, or a list where the number of grids was a multiple of the grid width, we would set the cursor onto a "grid line" with no entries.
In older versions of IMGUI, setting the cursor implicitly extended the parent's boundaries, this change was deprecated and only adding items would set the size. https://github.com/ocornut/imgui/issues/5548
During this, an assert was added to detect the programs relying on this deprecated behaviour.
We trigger this assert when we move the cursor onto a new line, but leave it empty.
As the problem this PR addresses is minor, it should not block v2.2's …

FSUI: Don't move IMGUI cursor unnecessarily in DrawGameGrid()

---

pcsx2/ImGui/ImGuiOverlays.cpp

Fixes #11981 
Actually shows shows when we are paused.
Make sure i didn't break anything else (for real this time).

OSD: Fix Pause indicator not showing up

---

pcsx2/DebugTools/SymbolImporter.cpp
pcsx2/DebugTools/SymbolImporter.h

- Improve error handling.
- Create type name AST nodes instead of built-in nodes. This means different types will be shown in the global variables tab for these symbols e.g.  `u8`  instead of `8-bit unsigned integer`.
- Use `FileSystem::OpenManagedCFile` instead of `FileSystem::OpenCFile`.
- Silence a spammy error message.
- The previous behaviour with the built-in AST node made the type more annoying the edit in the debugger.
- Make sure any .sym files you have are still being imported correctly.

Debugger: Refactor nocash symbol importer

---

pcsx2/DebugTools/SymbolImporter.cpp

This fixes an unfortunate typo in SymbolImporter.cpp. Previously, instead of loading symbol from the file specified it would just try to load symbols from the boot ELF again.
- This fixes loading extra ELF files.
Test that loading extra ELF files in the debug analysis settings dialog works.

Debugger: Fix loading symbols from ELF files other than the boot ELF 

---

bin/resources/GameIndex.yaml

The game uses a different CRC depending on the language and a different address for the patch.

GameDB: NBA 2K6 fix hangs on PAL version

---

.github/workflows/scripts/linux/flatpak/modules/10-libpcap.json
.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json

Update Flatpak dependencies: Qt to 6.8, FFMPEG extension and libpcap.
Up-to-date dependencies.
Successful build, install the PCSX2 flatpak and run it; I suppose.

Deps: Update Flatpak dependencies

---

pcsx2-qt/AutoUpdaterDialog.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtHost.cpp
pcsx2/Achievements.cpp
pcsx2/BuildVersion.cpp
pcsx2/BuildVersion.h
pcsx2/CMakeLists.txt
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/Host.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/PINE.cpp
pcsx2/Recording/InputRecordingFile.cpp
pcsx2/SIO/Memcard/MemoryCardFile.cpp
pcsx2/SIO/Memcard/MemoryCardFolder.cpp
pcsx2/SaveState.cpp
pcsx2/VMManager.cpp
pcsx2/pcsx2.vcxproj
pcsx2/pcsx2.vcxproj.filters

I have created a new pair of files for retrieving version information: `BuildVersion.h` and `BuildVersion.cpp`. They provide exactly the same information as `svnrev.h` but they don't force a recompile for all translation units using them every time cmake configure is run.
Most systems that used `svnrev.h` directly have been ported to use this new wrapper instead. The most notable changes are in the auto updater since it previously relied on a lot of preprocessor logic.
The only place `svnrev.h` is used directly is now the Windows resource files.
- Don't recompile a bunch of files unnecessarily whenever cmake configure is run.
- No more `// Remember to manually update this every release.` shenanigans (see GSDeviceVK.cpp).
- Minimal changes made to the existing build systems.
- Get our …

Misc: Minimise the amount of work done when svnrev.h is updated

---

bin/resources/GameIndex.yaml

- Reversed instructions that reads each enemies' stature and found a constant that is used for switching stuck and unstuck.
- This patch just makes the constant little bigger. (`3E4CCCCD` -> `3E4CCCE0`)
```
[Fix Enemy Stuck (dynamic)]
author=Berylskid
description=Fix Enemies' stuck. Region free.
dpatch=0,4,1,0,3C023E4C,4,3442CCCD,8,E7A300D0,C,E7A200D4,4,3442CCE0
```
Related to #8587 
- Test all kind of MT enemies (except AC enemies like Arena, I mean).
- Test various region versions.
- [Resolved] Enemies ignore walls

GameDB: Fix Enemies Stuck in Armored Core Nine Breaker

---

3rdparty/ccc/src/ccc/elf.cpp
3rdparty/ccc/src/ccc/elf.h
3rdparty/ccc/src/ccc/symbol_database.h
3rdparty/ccc/src/ccc/symbol_table.cpp
3rdparty/ccc/src/ccc/symbol_table.h
pcsx2-qt/Debugger/BreakpointDialog.cpp
pcsx2-qt/Debugger/DisassemblyWidget.cpp
pcsx2-qt/Debugger/MemoryViewWidget.cpp
pcsx2-qt/Debugger/Models/BreakpointModel.cpp
pcsx2-qt/Settings/DebugAnalysisSettingsWidget.cpp
pcsx2-qt/Settings/DebugAnalysisSettingsWidget.h
pcsx2-qt/Settings/DebugAnalysisSettingsWidget.ui
pcsx2/Config.h
pcsx2/DebugTools/Breakpoints.h
pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DebugInterface.h
pcsx2/DebugTools/ExpressionParser.cpp
pcsx2/DebugTools/ExpressionParser.h
pcsx2/DebugTools/MipsAssembler.cpp
pcsx2/DebugTools/SymbolImporter.cpp
pcsx2/DebugTools/SymbolImporter.h
pcsx2/Pcsx2Config.cpp

- The analysis settings dialog (and the tab in the per-game settings dialog) now lets you specify a base address expression and a load condition expression for each extra symbol file loaded.
- The start and end addresses for function scanning can now also be expressions.
- While working on the above item, I moved the function scanner back to running on the main database rather than the temporary database for the importer. I made the reverse change a while back, but this introduced an issue where user-defined functions would be ignored by the function scanner on repeated analysis runs, so I've reverted it back.
- This exposed a performance issue with running the function scanner on a large invalid address range, hence I've also updated some error handling code in CCC to be more performant. …

Debugger: Add options to load extra symbol files conditionally and/or with a base address and more

---

cmake/Pcsx2Utils.cmake
pcsx2/CMakeLists.txt

Not a huge fan of this solution, but it was the best I could think of.  If anyone has a better solution please say so.
Fixes the issue mentioned in #11287, as well as building on macOS with homebrew ffmpeg (that you want) and a homebrew-installed shaderc that you don't want.
There's actually two parts to the problem:
1. The `deps` directory gets marked as a system include by one of the packages in it
2. `/usr/local/include` does not (at least if the only thing in it is ffmpeg)
3. ffmpeg is ordered before everything else when we set up PCSX2_FLAGS, so even if both are marked system, `/usr/local/include` ends up coming first.
So this patch adds a function that both marks matching include directories as system, and puts the dependencies that contain them at the end of the list.  ~~It can …

CMake: Force /usr/local/include to come last

---

pcsx2-qt/QtHost.cpp
pcsx2/ImGui/ImGuiOverlays.cpp

This PR moves the VU stats above the SW threads when using SW renderer
Making the OSD stats looks more organized
Make sure i didnt break other things

Qt/OSD: Misc Improvements

---

pcsx2/PINE.cpp

A `strcpy` call has been swapped out with a ~~`strncpy`~~ `StringUtil::Strlcpy` call in `PINEServer::Initialize`.
For example, on Linux you could previously make it crash with the following command if PINE was enabled:
```
XDG_RUNTIME_DIR=/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/really/long/path ./build/bin/pcsx2-qt 
```
Try the command above, make sure it doesn't crash.

PINE: Fix stack buffer overflow for long XDG_RUNTIME_DIR paths

---

pcsx2/GameList.cpp

This caused crashes when file names had percent signs in them because we passed the file name as the format to SetFormattedStatusText. I opted to continue to use fmt for consistency.
Use SetStatusText instead of SetFormattedStatusText because we already format the string.
This issue caused the crash in #12011. This PR fixes #12011.
Rename a file in your game directory `Ichigo 100% Strawberry Diary (Japan).chd`. Reload the game list and see if it crashes.

QT: Use SetStatusText instead of passing a formatted string as a fmt

---

pcsx2/CDVD/CDVD.cpp
pcsx2/CDVD/CDVDcommon.cpp
pcsx2/CDVD/CDVDcommon.h
pcsx2/CDVD/CDVDdiscReader.cpp
pcsx2/CDVD/Linux/IOCtlSrc.cpp
pcsx2/CDVD/Windows/IOCtlSrc.cpp
pcsx2/SPU2/spu2sys.cpp

Fixes a regression introduced back in 2022, preventing OSDSYS from playing CD audio longer than one second.
Fixes another regression regarding SUBQ and an off-by-one in the getTOC implementation
Accuracy is good. Fixes the OSDSYS CD player for those who like watching that little cube spin around.
Fixes #4178
Use an audio CD in OSDSYS and see if it plays music or stops after 1 second.
See if dance factory still works. EDIT: It does.

CDVD: Fix OSDSYS Audio CD regressions.

---

pcsx2/DebugTools/Debug.h

The buffer size for lines written to the EE/IOP consoles has been limited to 4096 characters. In addition, consecutive newline characters are no longer eaten.
Previously it was very easy to accidentally exhaust the host's memory. For example, if you made an infinite loop and forgot the newline character. Since there would be no output it wouldn't be immediately obvious what was wrong either.
Here's a small program that triggers this behaviour:
```
.set noat
.set noreorder
.set nomacro
.global _start
_start:
print_loop:
lui $a0, %hi(format_string)
addiu $a0, $a0, %lo(format_string)
addiu $v1, $zero, 117
syscall
b print_loop
nop
.section .rodata
format_string:
.string "hello world"
```
Here's the above program in its compiled form: …

Console: Limit buffer size in ConsoleLogFromVM::Write

---

3rdparty/ccc/src/ccc/elf.cpp
3rdparty/ccc/src/ccc/elf_symtab.cpp
3rdparty/ccc/src/ccc/mdebug_section.cpp
3rdparty/ccc/src/ccc/sndll.cpp
3rdparty/ccc/src/ccc/symbol_file.cpp
3rdparty/ccc/src/ccc/util.cpp
3rdparty/ccc/src/ccc/util.h

DWARF support is in the works but will still likely take a few months to be ready for prime time. In the meantime, I thought I would backport some crash fixes just for PCSX2.
The bounds checking bugs were found via fuzzing, so I think are unlikely to affect any games, but I still think it's nice to get them fixed. The assertion fix makes CCC crash more cleanly if an assertion were to fail, since previously it called exit which PCSX2 doesn't like very much.
Fix some bugs.
You could test some of the games listed in my original symbol table PR #10224 and open the debugger.

3rdparty/ccc: Backport some fixes

---

bin/resources/GameIndex.yaml

Add Half Pixel Offset Special (Texture) and Round Sprite Half to _Champions of Norrath_.
Add Show Overscan to _Champions of Norrath_ and _Champions: Return to Arms_.
Fix edge garbage (visible on the left half of the bottom of the screen, most noticeable when braziers, torches, etc. are at the top of the screen) and UI seams (most visible around button prompts and skill tree) in _Champions of Norrath_. Same fixes are already applied to _Champions: Return to Arms_.
Fix offscreen image in _Champions of Norrath_ and _Champions: Return to Arms_. Reveals ~6 lines (at native resolution) that were pushed off the top of the screen, removing a black bar at the bottom. These games lack a screen position setting.
_Champions of Norrath_ Gameplay - Master
_Champions of Norrath_ Gameplay - PR
_Champions …

GameDB: Champions of Norrath & Champions: Return to Arms (PAL)

---

pcsx2/DebugTools/Debug.h

This fixes a silly regression introduced by [this PR](https://github.com/PCSX2/pcsx2/pull/12034) where, contrary to its marketing claims, it would eat all newlines.
Tried to do some last minute refactoring, ended up breaking console logging. Turns out newlines are control characters, doh.
Observe that newlines are not eaten now.

Console: Fix newline logging regression

---

pcsx2-qt/Debugger/DisassemblyWidget.cpp

The colour of each function is now determined by its address rather than its symbol handle, making it more stable across runs.
This addresses one of the problems brought up by #12014.
Remember the colour of a function, re-run analysis, make sure it remains the same colour.

Debugger: Make sure the colours of functions are consistent across runs

---

pcsx2/IopBios.cpp
pcsx2/SaveState.cpp
pcsx2/SaveState.h

Add bounds checking for `FreezeMem` loads
Always save HostFS data
When a savestate is saved without Host File System enabled, this tag is omitted.
If that savestate is then loaded after enabling Host File System, then FreezeTag will fail to find HostFS tag and reject the savestate
Additionally, `FreezeTag` will end up reading beyond the end of the savestate in such a situation.
Test savestates with and without Host filesystem enabled.

Savestate: Always write HostFS savestate tag (Savestate bump)

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/TC: Remove no longer needed asserts in PreloadTarget.
Asserts are no longer needed as we check for width offset and adjust width accordingly using the offset.
No longer needed.
Fixes https://github.com/PCSX2/pcsx2/issues/12040
Dev Debug build test https://github.com/PCSX2/pcsx2/issues/12040
Edit: tested gs dump locally and works as expected

GS/TC: Remove no longer needed asserts in PreloadTarget.

---

pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.cpp
pcsx2/DEV9/sockets.cpp

Always bind the UDP source port when using sockets
Reworded some logs
Duplicate FixedPort's connections vector for resetting child connections
Previously, we would only bind the UDP source port in specific situations (Broadcast, multicast and when src and dst port similar).
This proved inadequate for some games, which would either fail to connect of behave strangely if the source port wasn't maintained.
Expanding the heuristics used to catch every game seemed non-trivial, so I've opted to forgo this previously used heuristic and always bind the port.
This does mean we now sometimes bind the port unnecessarily (namely DNS requests), however, different games use ranges for dynamic ports, so avoiding this seemed not worth the effort.
Additionally, FixedPort's `Reset()` method could …

DEV9: Always bind UDP ports in sockets

---

pcsx2/DEV9/AdapterUtils.cpp
pcsx2/DEV9/PacketReader/IP/IP_Packet.cpp
pcsx2/DEV9/PacketReader/IP/IP_Packet.h
pcsx2/DEV9/PacketReader/IP/TCP/TCP_Packet.cpp
pcsx2/DEV9/PacketReader/IP/UDP/DNS/DNS_Classes.h
pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.cpp
pcsx2/DEV9/ThreadSafeMap.h
pcsx2/DEV9/sockets.cpp

Skip over invalid gateways for DHCP Auto Gateways on Windows
Correct `SetDscpValue()` function definition and remove unused duplicate definitions for `Read/WriteDNSString()`
Guard against out of bound reads when handling ICMP port rejected packets
Use Common functions for aligning header length
Fix possible race-condition when removing closed connections
A gateway of 0.0.0.0 is not usable, code to exclude this existed for other platforms.
Function definitions should not be incorrect.
When handling malformed ICMP packets, the offset to the contained IP packet was not accounted for when reading said IP packet.
Additionally, make sure we don't loop (potentially) infinitely if we get a _really_ malformed packet.
Existing alignment for IP and TCP options was correct enough to work, but not …

DEV9: Various Socket Fixes

---

common/FileSystem.cpp
common/FileSystem.h
tests/ctest/common/CMakeLists.txt
tests/ctest/common/filesystem_tests.cpp

- The `FileSystem::RecursiveDeleteDirectory` function will no longer recurse through symbolic links.
- To support this change, the `FileSystem::IsSymbolicLink` and `FileSystem::DeleteSymbolicLink` functions have been added. The `FileSystem::IsRealDirectory` function has been removed since it was unused.
Prevent accidental data loss e.g. when deleting folder memory cards.
This needs testing on macOS and especially Windows, since it touches Windows API code and I've only tested it on Linux. Since this is modifying some fairly important code I want multiple core contributors to review it before it's merged.
Here's an example of how you could reproduce the issue on Linux/macOS:
```
cd path/to/memcards/directory/
pcsx2-qt # create a folder card called "testcard" from the gui
mkdir …
```

FileSystem: Don't follow symbolic links when recursively deleting directories

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
.github/workflows/scripts/windows/build-dependencies-arm64.bat
.github/workflows/scripts/windows/build-dependencies.bat
pcsx2-qt/QtHost.cpp

Qt 6.8.1 is now out so let's do that for Windows and Linux.
Fixes and security fixes are good.
Make sure it builds correctly and everything works as expected.

Deps: Update to Qt 6.8.1 on Windows and Linux

---

bin/resources/GameIndex.yaml

Fixes incorrect field order in FMVs by using Adaptive BFF.
Automatic:
Adaptive BFF:
Incorrect field order looks gross as heck.
Make sure CI is happy boyo.

GameDB: Fix incorrect field order in Silent Hill 3 FMVs

---

pcsx2/Cache.cpp
pcsx2/Cache.h
pcsx2/Interpreter.cpp

Introducing another fix that affects 0.01% of users. 🥳 
When the interpreter shuts down and control goes to the recompiler I've made it so all EE cache entries are written back to memory.
This fixes #6637
Run a game, enable the EE cache, disable the recompiler, and then enable the recompiler. It some instances it would cause PCSX2 to crash or the game to TLB miss and freeze. This should have been addressed in this PR.

EE Cache: Writeback dirty cache entries when exiting the interpreter.

---

bin/resources/GameIndex.yaml

Changes the fixes from HPO Align to Native Native Scaling Normal to HPO Normal Native Scaling Aggressive to fix edge bleed that seems to have cropped up.
Current:
PR Fixes:

GameDB: Change LSW 2 fixes

---

pcsx2/SaveState.cpp

Add a cast to the bounds check I added in https://github.com/PCSX2/pcsx2/pull/12041
Fixes warning
Check log for warning
Make sure nothing explodes

SaveState: Fix comparison warning

---

pcsx2/CDVD/ChdFileReader.cpp

This check would fail if the returned extension was `.chd`
Additionally, `GetExtension` would return the extension without `.`, so no file would fail
This issue only impacts chd files with parent chd files
When searching for the parent chd, we would trying to examine every file as a chd, instead of only examining chd files
Test CHD files with parent CHD files and see if they still open
Such files can be created with `chdman createdvd -i "disc.iso" -op "parent.chd" -o "disc.chd"`
I'll note that chdman 0.271 and 0.272 currently has [issues](https://github.com/mamedev/mame/issues/13029) creating such files for PS2 sized games, so use an older version.

ChdFileReader: Correct extension check

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/TC: Use proper alpha min max for palettes when looking up a source.
If it's an old source made from target make sure it isn't a palette, alphas need to be used from the palette then.
GS/HW: Adjust how we handle dithering on blend mix.
Allow dither adjust regardless of alpha. usually it is clamed to 1 anyway so we can expand it if alpha max is higher than 128. 
Expand dither adjust to work in rev subtract conditions.
Accuracy.
Test variety of games, dumb runner didn't show anything broken, some comparisons are below.

GS/HW: Use proper alpha min max for palettes when looking up a source, adjust dither on blend mix.

---

common/FileSystem.cpp
common/FileSystem.h
tests/ctest/common/filesystem_tests.cpp
tests/ctest/common/path_tests.cpp

When resolving relative symlinks that contain `.` and `..` components on Linux, `Path::RealPath` will now return canonical paths instead of paths that contain said `.` an `..` components.
The `FileSystem::CreateSymLink` function has been added so I no longer have to call a POSIX-specific function in the test code (although the tests are still only run on Linux since on Windows they would require elevated privileges or developer mode to create the symbolic links).
While I was at it, I neatened up the recursive directory deletion test a little bit.
One symptom of this was that if you created a circular symbolic link in a recursively scanned game directory on Linux or macOS, PCSX2 would go crazy scanning the same games again and again. This happened because the `RecursiveFindFiles` function …

FileSystem: Prevent Path::RealPath from returning paths containing '.' and '..' components

---

3rdparty/d3d12memalloc/LICENSE.txt
3rdparty/d3d12memalloc/README.md
3rdparty/d3d12memalloc/include/D3D12MemAlloc.h
3rdparty/d3d12memalloc/src/D3D12MemAlloc.cpp
3rdparty/vulkan/include/vk_mem_alloc.h
3rdparty/vulkan/include/vulkan/vk_mem_alloc.h

Syncs both vkmemallocator and d3d12memallocator to the respective latest commits for each.
Fixes a use after free in vkmemallocator and likely other small bug fixes and new features.
Make sure DX12 and Vulkan still work as expected.

3rdparty: Sync memory allocators to latest master commits

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Get the proper context for the next draw if it's a split texture shuffle.
Draw might switch the context so make sure we get the correct one.
Fixes Genji: Dawn of the samurai crashing on Mt. Kurama during the night on hardware renderers.
Fixes https://forums.pcsx2.net/Thread-Bug-Report-Genji-Dawn-of-the-Samurai-NTSC-U
Test the dump, see if it crashes still https://dumps.pcsx2.net/index.php/s/RLfAYxYc5rkR83Y
Test variety of games, dump runner is clear.

GS/HW: Get the proper context for the next draw if it's a split texture shuffle.

---

3rdparty/libchdr/include/libchdr/chd.h
3rdparty/libchdr/src/libchdr_chd.c
pcsx2/CDVD/ChdFileReader.cpp

Removes the patches applied to chd_open_file, and instead uses libchdr's virtual IO API to achieve the same behaviour
Such patches can be missed when updating dependencies, potentially leading to difficulty updating or introduction of bugs
Additionally, this patch did not check for `CHD_OPEN_TRANSFER_FILE` before taking ownership, this issue, however, didn't actually impact us as we always wanted that anyway.
This could in future allow use to implement precaching ourselves, rather then relying on the (patched) implementation provided by libchdr.
Test using CHD files

ChdFileReader: Use core_file instead of modifing chd_open_file

---

3rdparty/libchdr/include/libchdr/chd.h
3rdparty/libchdr/src/libchdr_chd.c
pcsx2/CDVD/ChdFileReader.cpp

Migrate added `chd_is_matching_parent` function into PCSX2 code
Such patches can be missed when updating dependencies, potentially leading to difficulty updating.
Added function works just as well when within PCSX2 code.
Test CHD files with parent CHD files and see if they still open. (see https://github.com/PCSX2/pcsx2/pull/12076 for how to create them)

ChdFileReader: Migrate libchdr patch into PCSX2

---

pcsx2/IopBios.cpp

Instead of moving data in 8-bit loops, use safeiopmem(read/write) functions which use an underlying memcpy.
Minor performance increase in medium to large ioman I/O
When reading hostfs on master, our hottest point (besides the EE JIT) was the recClearIOP function called by each iopMemWrite8.
With this PR we now see faster execution times (~8.5%) with my hostfs bench-marking tool, and more CPU time on read().
See if games and homebrew that uses HostFS still work.

IOPBios: use memcpy read/write functions instead of 8 bit loops

---

3rdparty/libchdr/include/libchdr/chd.h
3rdparty/libchdr/src/libchdr_chd.c
common/FileSystem.cpp
common/FileSystem.h
pcsx2/CDVD/ChdFileReader.cpp

Removes the patches applied to libchdr, and instead uses libchdr's virtual IO API to achieve the same behaviour.
Such patches can be missed when updating dependencies, potentially leading to difficulty updating.
We now also precache parent CHD files, which the patched libchdr did not.
Includes on https://github.com/PCSX2/pcsx2/pull/12075
Test precaching using CHD files

ChdFileReader: implement precaching of CHD files within PCSX2 instead of modifying libchdr

---

3rdparty/libchdr/include/libchdr/cdrom.h
3rdparty/libchdr/include/libchdr/chd.h
3rdparty/libchdr/include/libchdr/coretypes.h
3rdparty/libchdr/include/libchdr/huffman.h
3rdparty/libchdr/src/libchdr_cdrom.c
3rdparty/libchdr/src/libchdr_chd.c
3rdparty/libchdr/src/libchdr_huffman.c

Hi, I'm ~~JordanTheToaster~~ TheLastRar and I'm here to update a 3rdParty library.
Purge remaining local patches
Syncs libchdr to latest master commit
Upstream has various improvements that we currently lack, such as fixes related to handling malformed CHD files.
Allows us to replace our patched version of `chd_read_header_*` with the upstream version.
No more local patches means future updates should be much simpler.
Test CHD files

3rdparty: Sync libchdr to latest master commit

---

.github/workflows/scripts/linux/appimage-qt.sh

Suppress the error return code for `git describe --tags`
This command will return error if the repo has zero tags
We already handle the failure by checking the stdout of the command (which is empty as the error message goes to stderr)
Test this change on a fork that lacks tags
I've tested locally, but I've not tested on the CI

CI/Appimage: Suppress error when no tags are present

---

common/vsprops/common.props

Replaces the march arguments for clang-cl with the msbuild EnhancedInstructionSet setting
Intellisense appears unable to infer AVX2 support from the additional march argument, instead relying on the value of `EnableEnhancedInstructionSet`
Test performance in master and PR clang AVX2 builds
~~Test that non-AVX2 clang still supports none AVX2 systems (presumably it will)~~

Build: Always set EnhancedInstructionSet for AVX2

---

pcsx2/COP0.cpp
pcsx2/R5900.cpp
pcsx2/R5900.h
pcsx2/SaveState.cpp
pcsx2/SaveState.h
pcsx2/vtlb.cpp

I had a list of optimizations here beforehand (you can view the edit history), but I've replaced it all with SIMD.
When we check to see if an address is part of a cached TLB entry we can do 4 at a time instead of one.
I want to get more familiar with VTune profiling. The EE cache is also very slow.
Test games that require EE cache with this PR (ensure any patches we have for the game are disabled)
Run the EE cache and compare the speed to master.

R5900: Improve the EE cache performance

---

bin/resources/GameIndex.yaml

Fix Trial & Demo titles.
Fix 2games speed hack.
I used the difference tool to edit it to make sure there was no waste.
I'm sorry to bother you all, but please check.
*I'm not touch name-en: about Zero (Fatal Fram series) & options code.
*I got base .yaml latest file  today morinig.
I couldn't fix it and thought of giving up. 
However, if this is not a problem, the modification of the Japanese title is almost finished, so I tried again.
I look forward to your support.
*I don't have any Linux-machine. So, I worked only Win-PC.

Fix Japanese Title Fix (Not -en) & Speed Hacks

---

pcsx2-qt/Settings/DebugSettingsWidget.cpp
pcsx2-qt/Settings/DebugSettingsWidget.ui

Qt: Properly disable all dumping options if draw dumping is disabled.
Also move around sone options.
UI improvements.
Make sure all draw dump options are disabled if draw dumping is disabled.

Qt: Properly disable all dumping options if draw dumping is disabled.

---

pcsx2/Achievements.cpp
pcsx2/Counters.cpp
pcsx2/GameDatabase.cpp
pcsx2/Input/SDLInputSource.cpp
pcsx2/R3000AInterpreter.cpp
pcsx2/SIO/Memcard/MemoryCardFolder.cpp
pcsx2/SIO/Pad/PadDualshock2.cpp
pcsx2/SIO/Pad/PadGuitar.cpp
pcsx2/SIO/Pad/PadJogcon.cpp
pcsx2/SIO/Pad/PadNegcon.cpp
pcsx2/SIO/Pad/PadPopn.cpp
pcsx2/VMManager.cpp
pcsx2/x86/iR3000A.cpp

This PR adds a log entry that warns the user through the log if they have advanced options enabled.
Preview:
Helps with user support in the event a user has messed around with the advanced settings.
See if the warning shows up correctly if the advanced settings are enabled. Also checks when its off too, or when the value is absent from the ini file.

Settings/Log: Print advanced settings warning on the log

---

bin/utils/bulk_compression.py

Converts refraction's bulk compression script which was presented as a Windows-only batch file into a cross-platform Python script.
Makes the tool cross-platform, putting Windows, Linux, and macOS users (freeBSD?) on a more equal footing and allowing us to ship the tool with PCSX2 instead of tucked away in Red's PCloud.
Try all 9 options and try them with and without deleting source items as well as different block sizes if compressing. Presently needs tested on all three major OSes, and it may work in freeBSD, but there's no guarantee at all for that. Until it has been properly tested by multiple people, USE THIS IN A CONTROLLED TESTING ENVIRONMENT WITH JUST A FEW FILES WHICH YOU HAVE BACKED UP ELSEWHERE.

Tools: Port refraction's bulk compression script to Python

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS: Properly name logs with prefixes.
Easier readability to know from which renderer are the logs from.
Smoke test.

GS: Properly name logs with prefixes.

---

3rdparty/include/xxhash.h
pcsx2/GS/GSXXH.cpp

Updates our xxHash to the latest release v0.8.3.
Ours was massively out of date and really needed to be updated at this point.
Make sure everything builds correctly and PCSX2 functions as normal in hardware mode as well as with texture packs.

3rdparty: Update xxHash to v0.8.3

---

pcsx2/vtlb.cpp

When introducing x86 intrinsics into the cache lookup, I completely forgot that we technically support ARM interpreters.
This would have broke any ARM building.
I tested locally by checking for a non-existing define (to not compile the SIMD code) and it worked fine. I guess try and build ARM?

EE Cache: Make the SIMD path x86 only to support ARM interpreters

---

bin/utils/bulk_compression.py

Changes ".cso" to ".iso" on line 172 and tells the user why ".iso" is even being brought up.
Obvious typo I made.
Make sure lines 172 and 173 don't introduce any typos.

Tools: Fix typo in compression tool

---

pcsx2-qt/Debugger/SymbolTree/SymbolTreeModel.cpp

Fixes a bug where the symbol tree model would think fields owned by a base class were instead owned by a subclass.
In theory this could cause a crash if the base class was deleted. In practice the debugger provides no way to delete individual data types currently so it would never actually happen, but it may be helpful in the future.
Check a .mdebug game.

Debugger: Fix AST node ownership confusion bug

---

3rdparty/vulkan/include/CHANGELOG.md
3rdparty/vulkan/include/README.md
3rdparty/vulkan/include/vk_mem_alloc.h
3rdparty/vulkan/include/vulkan/vk_mem_alloc.h

Updates VMA to release v3.2.0.
Teach me to update just before they added VK 1.4 support.
Same as last time make sure nothing go boom.

3rdparty: Update vkmemoryallocator to v3.2.0

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Adjust need_aem_color and req_color conditions.
Improves LookupSource to not use dirty data when it shouldn't.
Fixes https://github.com/PCSX2/pcsx2/issues/12122
Dump run is ok, test some games, test https://github.com/PCSX2/pcsx2/issues/12122

GS/HW: Adjust need_aem_color and req_color conditions.

---

pcsx2/Patch.cpp
pcsx2/Patch.h
pcsx2/VMManager.cpp

This PR introduces two changes:
1. Patches of type `PPT_COMBINED_0_1` were erroneously working identical to the Type 1 patches, as they were not applying in the entrypoint, contrary to what the docs claimed.
2. Patches of type `PPT_ONCE_ON_LOAD` that are enabled while the game is running are now being applied immediately, without requiring a restart. Without this change, one-time patches were effectively at a disadvantage compared to the every-frame patches, as the user could not enable them on runtime, even if they were safe to do so.
Stop punishing one-time patches for trying to be nice and not overwriting the code over and over every frame.
1. Run any game that has one-time patches, for example the 16:9 Widescreen fix for Tokyo Xtreme Racer Zero. Ensure the patch is disabled.
2. Enable …

Patch: Re-run PPT_ONCE_ON_LOAD patches when enabling them as the game is running

---

pcsx2/Cache.cpp

Instead of storing valid PFN in a boolean in the tag struct, use one of the unused bits in the tag directly. The PS2 documentation states that these bits are unspecified.
There was an observable performance increase while doing this.

EE Cache: Shrink tag size by 4 bytes

---

common/Linux/LnxMisc.cpp

This PR extends the screensaver inhibition function to MATE Desktop, which fixes #12169

Add support for MATE Desktop (fixes #12169)

---

.github/workflows/windows_build_matrix.yml
.github/workflows/windows_build_qt.yml

Takes https://github.com/PCSX2/pcsx2/pull/12129 and forces LLVM 19 to be used for both MSBuild (unlike the last PR) and CMake
Removes the `Tempfix Clang` step
Hopefully resolves the issue with the Windows Clang runner dieing.
Span the CI for clang builds

CI/Windows: Use Windows Server 2025 and LLVM 19

---

pcsx2/SIO/Memcard/MemoryCardFile.cpp

Old memcard code was doing FSeek64 calls extremely often which was thrashing performance. One culprit was support for legacy PSX memcards with special headers, which I would argue are no longer used (or should no longer be used). The other was being used when fetching the card's size info, which is done on every sector change. FSeek64 is now called once upon card opening.
Card size is static through PCSX2's lifecycle and only needs retrieved once. Doing so provides significant performance improvements as the IOP is no longer constantly performing unnecessary IO on the host file essentially every RPC call.
As always with memcard tests, make copies and use those for testing.
Boot all variety of games and test for data to load and save normally. Compare EE thread performance on master branch …

Memcard: Remove unnecessary FSeek64 for speed improvements

---

pcsx2/SIO/Sio.cpp

Adds a line break in the recently added OSD message that warns you about the use of save states after an hour of not saving. Additionally changes "for quite some time" to "in a long time".
The line break was used because this message is already so long that it wraps to a second one. The message makes extremely inefficient use of its space, having around 3/5 of an entire row blank. The deliberate line break also makes the second sentence (which would otherwise get cut in half) less awkard to read. Finally, the line break substantially cuts down on the overall horizontal length of the message with no effect on the vertical.
"for quite some time" to "in a long time" because it 1) more heavily emphasizes the length ("quite some time" is very gentle wording; "a long time" is very direct and …

SIO: Fix save state OSD warning formatting

---

pcsx2-qt/Debugger/CpuWidget.cpp
pcsx2-qt/Debugger/DisassemblyWidget.cpp
pcsx2-qt/Debugger/DisassemblyWidget.h

Adds a context menu option to disable the behaviour of making the disassembler jump to the address stored in the program counter when the VM is paused.
Implements/closes #12170. Seems like a reasonable suggestion.
Try the new context menu option and see if it still jumps.

Debugger: Add disassembler toggle to go to the PC address on pause

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/GameCheatSettingsWidget.cpp
pcsx2-qt/Settings/GamePatchSettingsWidget.cpp
pcsx2-qt/Settings/GameSummaryWidget.cpp
pcsx2-qt/Settings/SettingsWindow.cpp
pcsx2-qt/Settings/SettingsWindow.h
pcsx2/Patch.cpp

This PR improves the behaviour of the game list for ELFs loaded with the "backing" ISO set by the Disc Path. The following changes were made:
1. If the serial is not known, patches/cheats no longer try to use the empty serial. This previously resulted in PCSX2 attempting to load files with the filename format `_crc.pnach`, which, coincidentally, resulted in my "disabled" pnachs loading as I disabled some by prefixing them with an underscore.
2. If the serial is not known, `All CRCs` in Patches and Cheats is greyed out as it's meaningless.
3. If Disc Path is set, use the serial from that disc when populating the cheat and patch lists. This makes the UI behaviour match what PCSX2 was doing when loading the game - previously, these patches were loaded, but it was not possible to enable them …

Patches: Load and list patches for ELFs with a Disc Path set

---

pcsx2-gsrunner/test_check_dumps.py
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

This is some fixes I made in the RT in RT PR #11461 which I'm backporting to master as they should really be separate and they help outside of that, especially with a bug with a WWE game which was being investigated.
Fix misdetection of draw as clear, when it was a fog effect.
Fix preload target overlap behaviour and allow smaller widths which overlap.
Reduce target expansion when it doesn't need to due to subtractive blend on black (clamped).
Create a new target if a move is done with the same target, but the new position is outside of the target.
Fix AEM color requirement check for sources.
Debugging stuff changes:
Fix some of the HTML generation for the GS dump runner when frames are missing, this stopped the image comparer working.
Added the real BP for targets on to the name of …

GS/HW: Backport some fixes from RT in RT PR

---

pcsx2/x86/iR3000A.cpp
pcsx2/x86/ix86-32/iR5900.cpp

Removes JIT mid block jumping.
Vroom.
Test any games you'd like and see if it breaks anything.

iR5900: Remove mid block jumping

---

common/emitter/x86emitter.cpp

XMM6-XMM15 are non-volatile on Windows
On windows, backup and restore XMM5-XMM15 when using `xScopedStackFrame`
These registers can be clobbered by recompiled code, while the calling code will expect these registers preserved.
This _appears_ to be the cause behind https://github.com/PCSX2/pcsx2/issues/11549, at least with Jak X when testing with MTVU disabled.
Test to make sure I didn't blow up the core

x86emitter: Backup and restore non-volatile SSE registers

---

pcsx2/Input/SDLInputSource.cpp

Adjusts the default DS4 and DS5 LED intensity to a more sane 50% as to not cause blindness in users. You can further adjust this down in the controller settings if you do not wish to experience a breach and clear at 3am courtesy of your DS4 or DS5.
Closes #12186 
Getting flashbanged by a controller is unpleasant. 
Make sure the default colors are correct.

SDLInputSource: Halve default LED brightness

---

bin/resources/GameIndex.yaml

I would chekced & fixed some Japanese titles.
Good Game List.

GameDB: Fix Japanese Game Titles

---

pcsx2/x86/iR3000A.cpp
pcsx2/x86/ix86-32/iR5900.cpp

Partially reverts #12056 since it causes the Jak games to trip the impossible block clear assert.
I don't fully understand how our block caching works but it seems pretty clear that something broke. This probably does negate the perf changes seen by that PR, but someone needs to fully understand the cache and the block to figure out what the interactions are here if we want to make changes.
Probably stuff that dynamically load code was affected. (Jak games, probably SOTC, idk about others)

iR3000A/iR5900: Partial revert of 8c98f5d928 ("Remove mid block jumping")

---

pcsx2/USB/usb-pad/usb-turntable.cpp

This change fixes 2 bugs with DJ Hero turntable binding.
* Fixed automatic mapping of the Right Turntable's axis binds, which were originally backwards for Xbox 360 turntables.
* Fixed the Turntable Multiplier setting's functionality and increased the maximum multiplier to 512x, enabling the use of Xbox 360 turntables that output a tiny axis range (1/256 of full range). Also update the setting's description.
* This setting still doesn't work for the SDL handler for some reason, but I didn't want to touch SDL. The multiplier works with the XInput handler, which is enough to get Xbox 360 turntables working.
In order to play DJ Hero, a turntable controller needs to be bound. Due to the bugs described above, the process of binding Xbox 360 turntables was [way more complicated than it ought to …

USB: Fix DJ Hero Turntable automatic mapping & turntable multiplier

---

pcsx2/VMManager.cpp
pcsx2/arm64/RecStubs.cpp

We still need to fire up the VU1 thread despite having no recompilers.
Adjusted the VU recompiler stub so save-states will save / reload, with 0 recompiler support.
Trying to use ARM64 and I was sick of the VM deadlocking.
Test save-states, shutting down, resetting, etc on ARM64.

VMManager / vuJIT: Fix save state loading and saving on ARM64

---

3rdparty/imgui/include/imconfig.h
3rdparty/imgui/include/imgui.h
3rdparty/imgui/include/imgui_freetype.h
3rdparty/imgui/include/imgui_internal.h
3rdparty/imgui/include/imgui_stdlib.h
3rdparty/imgui/include/imstb_textedit.h
3rdparty/imgui/src/imgui.cpp
3rdparty/imgui/src/imgui_demo.cpp
3rdparty/imgui/src/imgui_draw.cpp
3rdparty/imgui/src/imgui_freetype.cpp
3rdparty/imgui/src/imgui_stdlib.cpp
3rdparty/imgui/src/imgui_tables.cpp
3rdparty/imgui/src/imgui_widgets.cpp
pcsx2/Achievements.cpp
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiManager.cpp
pcsx2/ImGui/ImGuiOverlays.cpp

Updates ImGui to v1.91.7
I got asked to update this.
ImGui now uses `ImU64` for `ImTextureID`, the casting approach is similar to the method recommended by ImGui.
Alternatively we can [provide our own define](https://github.com/ocornut/imgui/blob/d7454de80a2d51cee6601d275c441987e7aebb5e/imgui.h#L253-L260), which if preferred I can look into.
The patch we have for disabling the nav menu is kept (and is slightly larger)
I note that the nav menu gets disabled if a window/popup exists with the `ImGuiWindowFlags_Modal`.
This might be work investigating if we want to remove our patch, but I don't know my way around our ImGui code, so for now the patch remains).
Test OSD and Big Picture Mode

3rdparty: Update ImGui to v1.91.7

---

.github/workflows/scripts/windows/build-dependencies-arm64.bat
3rdparty/vixl/CMakeLists.txt

Adds missing define in vixl cmake file
Corrects confused hashes in windows arm64 deps script
While mmap is present on Mac, the mmap code path used a define not found on MAC(?)
We don't use the code buffer, so define the malloc one instead for all platforms
Test building arm64 with CMake
Test building arm64 deps on Windows

Arm64 build fixes

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Limit GetValidSize height and width.
Max texture size limit is 2048.
This should never happen but if it does clamp it
Prevent any crashes when target texture sizes are out of bounds.
Smoke test, I didn't find any dump that triggered it.

GS/HW: Limit GetValidSize max height and width.

---

bin/resources/GameIndex.yaml

SLPS-20307/20404/20419/20460/25770/25921 Rakusho ! Pachi-Slot Sengen Series has some graphic glitch.
Some of these glitch can be alleviated by  "Change CPU frame buffer" option .
Although it cannot fix some distortions in the drawing, it does improve critical problems such as objects that are not displayed at all being displayed, so I made a Pull Request for this.
This allows you to play at least as much as possible.
Please, See issue #12022

A Little fix Raksuho Pachi-slot Sengen series glitch (issue #12022)

---

pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/ImGui/ImGuiOverlays.h
pcsx2/Recording/InputRecording.cpp
pcsx2/Recording/InputRecording.h
pcsx2/Recording/InputRecordingFile.cpp

Make the communication between the EE (input recording) and the GS (displaying the frame count via ImGui) thread-safe. Additionally fixes a bug where the frame count was +1 what it should actually be. See #10793, which this is a follow-up to. (This fixes a small bug from that as well.)
Good to have the correct value displayed (previously we would run into an issue where we would say that we're on a frame that doesn't exist yet; for example, if we'd written 580 frames to an input recording and were actively recording, we'd be on frame 581). And make the code operate in a way that's not subject to a potential race condition.
Test input recording to make sure 1) the correct value is displayed and 2) nothing is broken.
* Definitely fixes #8128 
* Potentially interacts with #11454

ImGui: Make input recording frame count thread-safe

---

pcsx2/DebugTools/SymbolImporter.cpp
pcsx2/DebugTools/SymbolImporter.h
pcsx2/SaveState.cpp
pcsx2/VMManager.cpp

The symbol importer thread will now wait for the entry point to run before scanning for functions from memory.
I've used `std::condition_variable` to implement it so hopefully there won't be any deadlock issues this time.
When I modified the function scanner to scan the ELF file, I removed the code to sync the symbol importer thread with the CPU thread because it was broken, but when I reintroduced support for scanning from memory I forgot to reintroduce it.
Previously this meant that if the `Scan From Memory` option was selected from the global or per-game settings dialogs (not from the analysis options dialog in the debugger as that won't affect boot) the function scanner could run before the game's code was actually loaded in memory. This could be fixed by doing another analysis run, …

Debugger: Wait for the entry point to run before scanning from memory

---

bin/resources/GameIndex.yaml

Add cross-save support for a set of Nicktoons games.
The following games have features exclusively though the cross-save program:
- Nicktoons Unite!
- Tak - The Great Juju Challenge
- Nickelodeon SpongeBob SquarePants - Lights, Camera, Pants!
- Nickelodeon Barnyard
Have multiple saves of the above games and test out the cross-save feature in each game, preferably them with them all.

GameDB: Add Nicktoons Cross-Save Feature

---

pcsx2-qt/SettingWidgetBinder.h
pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2-qt/Settings/EmulationSettingsWidget.h
pcsx2-qt/Settings/EmulationSettingsWidget.ui
pcsx2/CDVD/CDVD.cpp
pcsx2/Config.h
pcsx2/Pcsx2Config.cpp

Allows the user the option to manually input a date and time for the PlayStation 2's real-time clock rather than 2020-04-03 00:00:00 for input recording and the OS' system clock otherwise. Only works if the BIOS is set to a region which is GMT+0 and DST is Summer Time (which is the default PCSX2 uses).
Multiple games have mechanics that play with the real-time clock.
* Tool-assisted speedrunners may want the ability to designate an arbitrary start date and time for RNG purposes.
* Some games make use of the date for an in-game event, such as Scooby-Doo! Night of 100 Frights' multiple holidays.
* Some games make use of the advancement of real time for an in-game event, such as The End's boss fight in Metal Gear Solid 3.
* Some games make use of the time for an in-game event, for example …

Settings: Allow user to manually set RTC per-game

---

pcsx2/DebugTools/DebugInterface.cpp

Mask off the segment bits so we don't show invalid address errors when in exception handling code.

DebugInterface: isValidAddres on physical

---

pcsx2/x86/Vif_Dynarec.cpp
pcsx2/x86/Vif_UnpackSSE.cpp
pcsx2/x86/Vif_UnpackSSE.h
pcsx2/x86/newVif.h

Backup and restore the non-volatile registers used by compiled Vif code.
XMM6-XMM15 are non-volatile on Windows, of which the Vif uses 3 of those.
These registers can be clobbered by JIT unpack code, while the calling code will expect these registers preserved.
This _appears_ to also cause https://github.com/PCSX2/pcsx2/issues/11549, at least with Jak X when testing with MTVU disabled.
Windows On Arm64 also has non-volatile fp registers, but the Arm vif code appears to not use these, so no changes for Arm.
Test to make sure I didn't blow up the core.

Vif: Backup and restore used non-volatile SSE registers

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Tries to reduce the number of copies for HDR draws.
Master would copy the render target to a new texture, draw, then copy back, every single time, but a lot of games do a lot of separate draws in a row to the same target, so it's better to keep it in one place until the end of the chain. This PR will keep it HDR as long as possible before converting back, hugely reducing copies and render passes in some cases.
TL;DR: Makes some games go brr more
Test the games listed below (sorry for the names)
Slightly Cherry Picked Reduction Results from Vulkan:
```
Ace Combat - Squadron Leader_SCES-52424 ['Draw Calls: -1 [620=>619]', 'Render Passes: -1 [44=>43]', 'Copies: -1 [8=>7]']
Big.Mutha.Truckers ['Draw Calls: -352 [903=>551]', 'Render Passes: -423 [440=>17]', 'Barriers: -127 [132=>5]', 'Copies: …
```

GS/HW: Reduce number of copies for HDR

---

pcsx2/Input/SDLInputSource.cpp
pcsx2/Input/SDLInputSource.h
pcsx2/SIO/Pad/Pad.cpp

Makes it so that the `Restore Defaults` button in the `PCSX2 Controller Settings` restores the default LED colors for the four players. This takes effect immediately.
`Restore Defaults` previously did not reset the controller LED colors set by the user, when it should reset all controller settings.
Go to `Settings` > `Controllers` and click the little lightbulb next to `DualShock 4 / DualSense Enhanced Mode`. Set all the ports to something obviously non-default. Then `Restore Defaults` either before you've exited out of PCSX2 or after reopening the application. If you have a DS4 or DS5 controller, check to ensure that this immediately changes the physical LED color on your controller.

Controllers: Make restore defaults restore controller LED

---

pcsx2-qt/QtHost.cpp
pcsx2/Config.h
pcsx2/Pcsx2Config.cpp

This PR adds in `-portable` launch arguments that forces PCSX2 to run in portable mode regardless of the presence of the `portable.ini/txt` file.
Feature parity with wxWidgets.
Test windows and linux (appimage)

Qt: Add Portable Mode launch argument

---

3rdparty/imgui/include/imgui.h
3rdparty/imgui/include/imgui_internal.h
3rdparty/imgui/src/imgui.cpp
3rdparty/imgui/src/imgui_demo.cpp
3rdparty/imgui/src/imgui_draw.cpp
3rdparty/imgui/src/imgui_freetype.cpp
3rdparty/imgui/src/imgui_tables.cpp
3rdparty/imgui/src/imgui_widgets.cpp

Updates imgui to v1.91.8 against my will.
Keeping this up to date will reduce future suffering I or anyone else may endure during the process of keeping this thing up to date.
Make sure all the usual things work.

3rdparty: Update ImGui to v1.91.8

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
.github/workflows/scripts/windows/build-dependencies-arm64.bat
.github/workflows/scripts/windows/build-dependencies.bat

Updates our Qt version to 6.8.2.
Bug fixes are always good.
Make sure themes work text checkboxes ect all function correctly and nothing go boom.

Deps: Update to Qt 6.8.2 on Windows and Linux

---

pcsx2/VMManager.cpp

Removes two possible move-after-frees in the vmmanager
Using an object (like an std::string) after it has been moved I believe is undefined behaviour, or implementation defined behaviour. Not good nonetheless.
Change discs and savestate when you can't rename to backup.

VMManager: Avoid use-after-move conditions

---

pcsx2-qt/Debugger/MemorySearchWidget.cpp
pcsx2-qt/Debugger/MemorySearchWidget.h
pcsx2-qt/Debugger/MemorySearchWidget.ui

Adds an 'unknown initial value' comparison to the memory searcher (fixes #12276)
Made it so we only validate the search value input when the comparison uses the value.
Better ergonomics and improves the utility of the debugger. 
Try doing a filter search with 'decreased by', 'unchanged', etc with the search value text-box being empty
Try filtering down a value using the 'unknown initial value' comparison.

Debugger: Memory search changes

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Adds a CRC and necessary fix to make Axel Impact/DT Racer/DT Carnage look mostly right and play at a decent speed.
It's not perfect with this PR, but with RT in RT #11461 it will be accurate. This still makes a huge improvement to playability.
It was annoying me how broken they were and the game does an insane shuffle PCSX2 cannot handle, so this was the only real option.
Test said Games.
Axel Impact:
Master:
PR:
DT Carnage:
Master:
PR:
DT Racer: (You can see noticeable glitches here, they are gone on RT in RT)
Master:
PR:

GS/HW: Add CRC fixes for DT Carnage/Racer/Axel Impact

---

pcsx2/x86/ix86-32/iR5900.cpp

Resets the manual protection counters on emulator reset
This counters are used to avoid excessive recompilation of blocks that share a page with data see; https://github.com/PCSX2/pcsx2/blob/bf8693a7e8546f1ec3bcb8a71603d9e460430b5e/pcsx2/x86/ix86-32/iR5900.cpp#L2041-L2049
For some currently unknown reason, the initial value of these counters has an observable impact on TAS playback (at least with Jak X)
As these arrays weren't previously cleared, the sequential playback of the same TAS file will playback differently.
Ideally, we would investigate _why_ this has an effect on TAS playback (especially given that these values are not stored in savestates), but I believe these arrays should be reset regardless.
This might impact the performance on the second game launched in a PCSX2 session …

iR5900: Reset manual protection counters on emulation reset

---

pcsx2-qt/Settings/MemoryCardConvertWorker.cpp

Makes the progress bar for File -> Folder conversion go from 0% to 100% instead of 0% to 99% (Folder -> File already worked as intended). This was purely an aesthetic issue.
Resolves #12271.
Convert your file memcard to a folder memcard and look at the progress bar. Test on master to ensure this really was a problem.

Qt: End memcard conversion progress at 100% instead of 99%

---

pcsx2-gsrunner/Main.cpp
pcsx2/Config.h
pcsx2/GS/GSDrawingContext.cpp
pcsx2/GS/GSDrawingEnvironment.h
pcsx2/GS/GSLocalMemory.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSTexture.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSTextureCacheSW.cpp
pcsx2/Pcsx2Config.cpp

Add additional options to GS dump runner to allow: dumping render target, textures, depth, alphas per draw; range of frames or draws to dump. Some miscellanous fixes to formatting of file names and dumping of GS context.
To make it easier to debug large numbers of GS dumps. Example workflow: run a large number of GS dumps just outputting the frames, check which dumps/frames are different, rerun the dump runner on the differing dumps/frames while dumping all draws RTs to see which draw the change ocurred.
Run the GS dump runner with new options -dump [rt|tex|z|f|a|i], -dumprange, -dumprangef. Example:
`pcsx2-gsdumprunner-x64-dbg.exe <dump file> -renderer sw -dumpdir <output dir> -dump rttexfzai -dumprange 100,100,3`
to dump RTs, textures, frames, alphas,and info (context, vertex, vsync …

Tools: Add additional options for dumping in GS runner.

---

pcsx2/SIO/Memcard/MemoryCardFolder.cpp

Fixes building in the latest Visual Studio 2022 update.
For more information see: https://learn.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=msvc-170#:~:text=Moved%20system_clock%2C%20high_resolution_clock%2C%20and%20chrono_literals%20from%20a%20commonly%20included%20internal%20header%20to%20%3Cchrono%3E.%20If%20you%20see%20compiler%20errors%20that%20types%20like%20system_clock%20or%20user%2Ddefined%20literals%20like%201729ms%20aren%27t%20recognized%2C%20include%20%3Cchrono%3E.

Build/VS: Fix change in latest VS 2022 update with std::chrono

---

pcsx2/Host/SDLAudioStream.cpp

Tells SDL to name our audio output stream "PCSX2".
SDL and cubeb backends previously resulted in different names for the output which caused them be identified as different applications by the OS.
Check that the application name in the system volume mixer is as expected.

SDL Audio: Set app name hint

---

bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/ShaderCacheVersion.h

GS/HW: Cleanup gl and vk shaders.
gl: Rename fetch_rt to sample_from_rt to match vk shaders, remove old atst call.
vk: Make sure shuffle values have correct unsigned type.
Cleanup.
Smoke test gl/vk hw.

GS/HW: Cleanup gl and vk shaders.

---

.github/workflows/scripts/linux/appimage-qt.sh
.github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in

I actually went and read through the entire documentation of the metainfo format available here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
I found a few nitpicks:
* `developer_name` is deprecated in favour of `developer`
* Set categories to the same one we have set in our .desktop file for consistency
* Add github and contributing link
* Add support/recommends entries so flathub & co knows we are a desktop app and would recommend a gamepad/at least 8GB of ram
* Require a display that's at least a tablet/laptop and an input device: our UI is not made for phones

flatpak: misc additions to the metainfo

---

pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Themes.cpp

This PR adds a new pitch black theme.
Aiming for less eye-straining and flash-banging also helps with OLED screens.
Preview:
For those who wants darker than dark mode theme.
Check if it looks good and if usability isn't affected in a negative way.

Qt: Add AMOLED Theme

---

common/CMakeLists.txt
common/Darwin/DarwinMisc.cpp
common/HostSys.h
common/Linux/LnxMisc.cpp
common/Windows/WinMisc.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.ui

Continuation of #12239 but instead if polling, use event based systems.
See the original PR
Fixes: #11902
See the original PR
Note that this does not work on Wayland. Possibly myself or someone else can implement something regarding zwp_pointer_constraints_v1.

Qt: Add mouse grab/lock feature when PCSX2 is in focus

---

pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp
pcsx2-qt/Settings/MemoryCardSettingsWidget.h
pcsx2/SIO/Memcard/MemoryCardFile.cpp
pcsx2/SIO/Memcard/MemoryCardFolder.h

Folder memcards always returned that they were formatted, whether or not that was the case. Additionally, we allowed to convert  unformatted memory cards which, in the case of folder memcards, lead to a crash because of the superblock being uninitialized.
This PR fixes that.
This fixes https://github.com/PCSX2/pcsx2/issues/12270
Check whether you can still convert memcards and particularly folder memcards.

SIO: correctly report & check formatted status for conversion

---

.github/workflows/scripts/linux/appimage-qt.sh
.github/workflows/scripts/linux/apprun-hooks/default-to-x11.sh
.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json
pcsx2-qt/MainWindow.cpp

Following the original discovery that Qt's wl_surface lifetime were broken around 8 months ago, here's another upstream Qt bug!
Qt has two types of rendering for its widgets, alien and native. While alien is usually more efficient and allows Qt to handle its own refresh primitives, native window rendering is necessary if we want to paint to a widget ourselves (see [Qt::WA_PaintOnScreen](https://doc.qt.io/qt-6/qt.html#WidgetAttribute-enum) ).
Unfortunately, this comes with the side effect of letting the compositor decide how to deal with those surfaces.
Compositors that do not implement SSD, like GNOME (mutter) or weston do not by design, thus leading to pretty borked results on those OSes for some widgets, for example:
As such, let's disable native window rendering for everything but the …

wayland: fix and enable by default

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

maintains already downscaled targets on more downscaling.
it was doing partial draws downscaled then upscaling it immediately in Onimusha 3 when using Normal NS, which is wrong.
test games which use native scaling, make sure they don't look more gross.
Changes which are technically better or different:
BBoy:
Master:
PR:
Spyro:
Master:
PR:
Ratchet & Clank Up Your Arsenal:
Master:
PR:
Tomb Raider Legends:
Master:
PR:

GS/HW: Maintain scale on subsequent downscale draws

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Increases sensitivity of paving check to avoid turning on merge sprite for incorrect draws.
It was making a meal of things which looked like they were paving, but weren't, like Ace Combat series.
Test games which use merge sprite to make sure they're okay.
Ace Combat 04:
Master:
PR:

GS/HW: Increase Merge Sprite paving sensitivity to avoid mismerges

---

pcsx2/SIO/Memcard/MemoryCardFile.cpp

This function is only called when the UI needs to know how many memcards you have for display purposes, but to do so needs to at least open them to see what they are. Switched enableFiltering from forced false to use whatever the automatically manage checkbox is set to.
Prevents log being flooded with warnings when large folder memcards exceed 8 MB size and trying to open settings or run GS dumps.
Have a folder memcard containing more than 8 MB of data. Enable the log window. Open your settings menu. Verify that, if in your memory card settings the checkbox for automatically managing is ticked, you are no longer getting warnings for the folder memcard being full. Close PCSX2 and repeat for loading a GS dump.

Memcard: Apply filtering when checking all possible memcard options

---

pcsx2/DebugTools/ExpressionParser.cpp
pcsx2/DebugTools/MipsAssembler.cpp
pcsx2/DebugTools/MipsAssemblerTables.cpp

Fixes an invalid opcode form in the assembler table.
Also added an error message to an expression parser failure condition.
This made assembling bc1f/bc1t bc1fl/bc1tl not possible as the immediate was clobbering the bits outside of the offset field.
The error message fixes a case where entering multiple constants failed, but didn't say why.
Try assembling the previously mentioned opcodes. The assembler uses absolute addressing (and internally converts it to be relative). Try assembling the maximum offset possible and beyond, make sure that there is no off-by-one errors.

Debugger Assembler: BC1(t|f) 24 bit immediates to 16 bit immediates

---

bin/resources/GameIndex.yaml

**Please merge together with https://github.com/PCSX2/pcsx2_patches/pull/499.**
Multiple NFS games and TOCA Race Driver 3 grant bonuses if they detect saves from the previous game in the series. This was previously set only for NFS Most Wanted (looking for saves from Underground 2), but even that was not exhaustive.
In this PR:
* Filters for Most Wanted have been improved.
* Filters for Carbon have been added. One of the checks in Carbon has a bug and checks for a wrong serial of MW Black Edition. **Both** wrong and correct serials have been added to the database, and a patch to correct the serial has been submitted to the patch repo. Filters for Underground 2 were also added, as the game has unused code referencing those.
* Filters for ProStreet have been added. Filters for Underground 2 …

GameDB: Memory card filters for TOCA Race Driver 3 and NFS games

---

pcsx2/Achievements.cpp

Remove setting indicator active state in `HandleLeaderboardTrackerUpdateEvent` per https://github.com/PCSX2/pcsx2/pull/12352#issuecomment-2679263223
Image showing the issue:
Demo video showing the issue and before/after:
https://github.com/user-attachments/assets/f04ed5ce-5137-42e8-96be-f284766cdc0a
Fix the timer being set if events come in out of order.
<details><summary>OLD PROPOSAL (outdated) </summary>
Drop `INDICATOR_FADE_IN_TIME` (0.1) / `INDICATOR_FADE_OUT_TIME` (0.5)
Replace with `INDICATOR_FADE_TIME` with value 0.1.
This makes it highly unlikely to experience a persistent timer.
Depending on the rate that new timer/achievement (bottom right) indicators are added, it is possible to have indicators that never disappear until you end the emulation.
The new default of 0.1 does not …

Achievements: Fix leaderboard timers persisting

---

pcsx2/ImGui/FullscreenUI.cpp

Adds a config option to swap OK/Cancel within BPM
Like the light theme toggle, this option only exists in BPM's settings panel.
Japanese PS2 titles often used circle as OK
With the upcoming update to SDL3, The button used for OK and cancel on Nintendo controllers will be swapped, this allows those users to swap that back.
Test if the config option works
Test that the button prompts/tips are correct when swapped

FSUI: Add a config option to swap OK/Cancel within BPM

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/Settings/DebugSettingsWidget.cpp
pcsx2-qt/Settings/DebugSettingsWidget.ui
pcsx2/Config.h
pcsx2/Pcsx2Config.cpp

Add UI elements for options to control dumping of GS data in the System/Settings/Debug/GS menu. Specifically: SaveInfo, SaveAlpha, Start Frame Number, Frame Dump Count. Note: This is a quick (but hopefully not dirty) PR to add the missing functionality that I intend to improve in a followup PR.
I forgot to add these in a previous PR that added the said options.
Run any game and use the options mentioned above in the menubar System/Settings/Debug/GS (after enabling advanced settings in the menubar Tools/Show Advanced Settings).

UI: Add debug UI options for new GS dumping options.

---

pcsx2/ImGui/FullscreenUI.cpp

Removes the second confirm
Buttons only confirm once
Go to the Swap OK/Cancel setting and read the description

FSUI: Correct description of the "Swap OK/Cancel" option

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp

What happens when two idiots look at Tales of the Abyss and see the grid pattern that can't be fixed and go "hey, that looks like Tekken does without the CRC hack", that's right, the idiots slap the Tekken CRC on it, and it only goes and bloody works.
Same engine as Tekken 5, same problems, same developer, different day.
Test Tales of the Abyss and Taiko no Tatsujin - Doka! to Oomori Nanadaime upscaled.
Fixes #6497
Tales of the Abyss:
Master:
PR:
Taiko no Tatsujin - Doka! to Oomori Nanadaime:
Master (actually RT in RT to get effects right):
PR:

GameDB: Add Namco CRC to Tales o.t. Abyss + Taiko no Tatsujin 9

---

pcsx2-qt/Debugger/BreakpointDialog.ui

Title.
Size 4 is more inclusive than size 1. I was left scratching my head around the reason why I was unable to find the instructions manipulating a specific data in Yu-Gi-Oh! Duelists of the Roses, up until I changed the size to 4. 
This will help those using the debugger in finding the instructions they're looking for. If a person desires exclusionary sizes such as 1 or 2, which is unlikely, they can change it so. And considering size 8 is unlikely to be searched for, then no need to expand the number to that. However, given that size 4 is able to find most instructions, then size 4 it is. This lessens the burden of having to enter 4 every time I'm setting a breakpoint, and helps the inexperienced, unwary users out. Now every LB, LH, SB, OR SH instruction can be found when setting a …

Debugger: Set default breakpoint size to 4

---

pcsx2-qt/Debugger/MemorySearchWidget.cpp

This changes s64 to u64
8 byte searches were broken. 
Not needed.

Debugger: Fix 8 byte searches

---

pcsx2-qt/MainWindow.cpp

Updated version of #12321
Due to their PR being on their `master` branch I don't have access to implement changes, and I don't want the PR to go stale.

Qt: Allow recording on game boot

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/ImGui/FullscreenUI.cpp

New Half Pixel Offset option, based on Align Native but with texture adjustment and removes a very annoying vertex offset.
The vertex offset was causing problems in the RT in RT branch due to things being drawn offset in to a target, but by default the option leaves the first pixel blank due to a forced offset, this gets around that but needs to adjust texture coordinates also.
Test games with the new option under the HPO upscaling fixes.
Known to be better for Ace Combat games, Catwoman, Madagascar and potentially others with borders.  GOW also looks better on the RT in RT branch, as well as being required for FF7 DoC and Project Snowblind to avoid bad textures.
Catwoman:
Master:
PR with new option:
Madagascar:
Master:
Master with Align to Native:
PR With new options:

GS/HW: Add new HPO - Align to Native With Texture Offset

---

pcsx2/Docs/GameIndex.md
pcsx2/Docs/gamedb-schema.json

Forgot to allow limit for Align to Native with Texture Offsets
Github getting angry
Make sure it builds

GameDB/Link: Fix validation limit for Half Pixel Offset

---

pcsx2/Input/InputManager.cpp
pcsx2/Input/InputManager.h
pcsx2/SIO/Pad/Pad.cpp
pcsx2/SIO/Pad/Pad.h

Macros don't trigger if you only press one key of a chord anymore, fixes #8192
`InputAxisEventHandler` has `InputBindingKey` as an argument now
`InputManager::SplitChord` was made public
`SetMacroButtonState` was changed to check if all triggers of a macro were pressed before proceeding with the input
To make games that utilize pressure sensitive controls, like MGS3, playable on controllers that don't have it
Test this on a windows system, because I don't have one

Input: Make macro chords work properly

---

pcsx2/VMManager.cpp

Sten broke it during the port to Qt...
This fixes #12375 .
Tested locally, seems to work

VMManager: initialize PINE with config-provided slot

---

common/FileSystem.cpp
common/FileSystem.h
pcsx2/GameList.cpp

We get a lot of users that accidentally tell PCSX2 to recursively scan massive directories (e.g. home directory) and then complain about it freezing.  Looks like this is caused by gamelist scanning not being cancellable while it scans directories (only when scanning the files in those directories), so if anything asks the gamelist scan to cancel and then waits for it to finish, it ends up waiting for a long time.
Less freezing, though it means people who do this won't come to us for help and will therefore never find out why PCSX2 spends tons of CPU scanning directories in the background whenever they open it.  Maybe we should add a warning if we notice a scan has been going on for some large amount of time asking the user if they want to set the directory to non-recursive...
- Set a …

GameList: Allow recursive scans to be cancelled

---

pcsx2-qt/Translations.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/FullscreenUI.h
tests/ctest/core/StubHost.cpp

Add an auto mode to swapping X and O in BPM
This is based on either the user language, or the selected BIOS region
Also format the FSUI file
We can infer the users preference for the confirm button based on these settings
In future we can also set O as confirm when a switch controller is used, this will be after (or part of) the SDL3 pr
Set "Swap OK/Cancel in Big Picture Mode" to Automatic
Change your language to Japanese/Chinese/Korean and check if X and O swap
Change your BIOS between an Asian and non-Asian region one (if you have multiple) and check if X and O swap.

FSUI: Add automatic mode to "Swap OK/Cancel" option

---

common/FileSystem.cpp

Fixes me being dumb in #12359
Less leaky
Make sure scan cancelling still works

FileSystem: Don't leak on directory scan cancel

---

pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiFullscreen.h

This PR adds themes to Big Picture Mode (ported from the Qt ones), I'm aiming for parity with the Qt themes, ~~hence the draft status.~~
And possibly makes the entire theme system unified (Changing it on one side also affects the other) but thats for another day.
Some preview:
Feature parity with Qt, and just more eye-candy in general.
Test for usability and readability issues, I've tested it before but there's a chance that i might miss something.

FSUI: Add Themes

---

pcsx2/VU0.cpp
pcsx2/x86/iCore.h
pcsx2/x86/ix86-32/iCore.cpp
pcsx2/x86/ix86-32/iR5900.cpp

Delete Const registers when flushing them completely for drop to interpreter
Propagate the CLIP_FLAG value if it gets written via CTC2 on the EE interpreters, as if the CLIP instruction is run directly after, it will have the wrong clip value. VU JIT doesn't suffer from this as COP2 is direct for both.
With constants, if you dropped to interpreter and the reg that was constant got written it didn't clear the constant status, causing everything to explode. No idea if this affects anything outside of development where we may force dropping to interpreter, I noticed it when forcing FPU RECOMPILE down to interpreter while trying Soft Float on Twin Caliber. I don't expect any real performance impact as we don't drop out of the EE JIT very often at all.
the CLIP_FLAG issue is because the VU Int …

Core: Const Reg flushing fix + COP2/Int CLIP fix

---

common/emitter/implement/simd_moremovs.h
common/emitter/instructions.h
common/emitter/simd.cpp
pcsx2/VUops.cpp
pcsx2/x86/microVU_Misc.h
pcsx2/x86/microVU_Upper.inl
tests/ctest/common/x86emitter/codegen_tests_main.cpp

Implements a version of CLIP that properly compares floats with max exponent
Also optimizes the flag extraction through the magic of SSE4.1
In preparation for #12001, I'd like to maintain two code paths for as few instructions as possible.  So I'd like to see if any games break when just using an accurate version of CLIP at all times, even when all other ops are getting clamped.
See if any games break
See if I made anything slower

Core: Accurate clip instruction

---

pcsx2/ImGui/FullscreenUI.cpp

Format FullscreenUI, again
In https://github.com/PCSX2/pcsx2/pull/12366, I had formatted this file after getting frustrated with how similar lines where formatted in 3 different ways.
With the exception of 3 string arrays got as collateral, clangformat matched the existing code
It was, however, determined that the existing code was not formatted as nice as we would like.
While we can't precisely configure clangformat's behaviour here, it was found that adding a trailing `,` mostly gets the desired behaviour.
Also, re-adds a space that was removed in https://github.com/PCSX2/pcsx2/pull/12369, I'm unsure why it was removed so RFC here.
Is the code visually better looking

FSUI: Formatting

---

pcsx2/Input/InputManager.cpp
pcsx2/Input/SDLInputSource.cpp
pcsx2/Input/SDLInputSource.h

Fix warnings emitted at build time
Also correct issues made apparent by said warnings
Fixing warnings is good
Wrong array was used for mouse axis UI strings
Correct using the wrong event type for device (dis)connect, That issue had been around in SDL2 as well
Test to make input still works

Misc: Fix warnings relating to SDL3 update

---

pcsx2/windows/PCSX2.manifest

Modify our manifest to allow long paths within PCSX2 
[According to the docs](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#application-manifest-updates-to-declare-long-path-capability) a registry key needs to be set, and applications need to add this key to their manifest.
See if long paths are fixed
Hopefully fixes #12368

Windows: Make PCSX2 long path aware

---

common/FileSystem.cpp

Don't pass file access mode strings into GetWin32Path()
Fix use after free when handling relative paths
File access modes strings are not paths, and should just directly be converted to wide strings on Windows
`SplitNativePath()` returns a `std::string_view` so the passed `std::string` needs to be kept in scope
Test gamelist recursive scanning of relative paths that cross (cyclic?) symlinks (on any OS)
Test files open correctly (Windows)

FileSystem: Couple fixes

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Check if pabe sw is actually enabled.
No need to check for PABE if it's not enabled on sw blend. In fact on ICO flag is enabled even if ABE is disabled which is pointless.
Bugfixes.
Not needed, dump run clear.

GS/HW: Check if pabe sw is actually enabled for ate second pass.

---

.github/workflows/windows_build_qt.yml

I wrote up a method for minidump viewing on Linux and OSX.
https://github.com/PCSX2/pcsx2/wiki/17-Viewing-Windows-Minidumps-on-Other-Platforms
We can skip a step by converting the symbols into the format minidump-stackwalk expects and shipping that with our symbol package.
We don't have as many active Windows testers as we've once had, and spinning up a VM just to view a users minidump is ridiculous. This PR streamlines one of the steps required to view the minidumps on Linux / OSX.
See if the CI fails (it probably will), and see if the generated symbol file is valid.

CI: Generate Breakpad symbols for Linux / OSX Windows debugging ease

---

.github/workflows/windows_build_qt.yml

Because of my changes in #12397, the windows PDBs were put into a subdirectory instead of the root of the artifact. This fixes that.

CI: Flatten symbols for upload-artifact

---

pcsx2-qt/Settings/InputBindingWidget.cpp
pcsx2/Input/SDLInputSource.cpp
pcsx2/Input/XInputSource.cpp

Fixes the vibration input binding window
I did a poor job of updating this for UI strings during the SDL3 pr
Test manually selecting a vibration motor in the controller settings window

Qt: Fix pad vibration binding window

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/Config.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/ImGui/FullscreenUI.cpp

Defaults the screenshot quality to 90%.
Saves some space when using our default of PNG which is nice.
Make sure the default value is loaded correctly.

Config: Default to higher screenshot quality

---

pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/FullscreenUI.h
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiFullscreen.h
pcsx2/ImGui/ImGuiManager.cpp
pcsx2/ImGui/ImGuiManager.h
pcsx2/Input/DInputSource.cpp
pcsx2/Input/DInputSource.h
pcsx2/Input/InputManager.cpp
pcsx2/Input/InputManager.h
pcsx2/Input/InputSource.h
pcsx2/Input/SDLInputSource.cpp
pcsx2/Input/SDLInputSource.h
pcsx2/Input/XInputSource.cpp
pcsx2/Input/XInputSource.h

When a switch controller is used in BPM and "Swap OK/Cancel" is set to auto, set Circle as OK
Users with switch controllers are presumably used to A as accept, which is in the same position as circle on the switch
Enter BPM with a switch controller and press A/Circle to see if it works as accept when "Swap OK/Cancel" is set to auto

FSUI: Swap OK/Cancel on switch controllers with automatic "Swap OK/Cancel"

---

bin/resources/GameIndex.yaml

Save data from Midnight Club 3 - DUB Edition (non-Remix) can be imported into Remix.
Feature parity between folder memcards and normal memcards.
1. Have a save from MC3 DUB Edition.
2. Launch MC3 DUB Edition Remix.
3. Attempt to import the save data.

GameDB: Add memcard filters for Midnight Club 3 - DUB Edition Remix

---

.github/workflows/scripts/macos/build-dependencies.sh

macOS dependency build was taking an hour because the kddockwidgets would attempt to build every file at once and swap like mad
Faster builds
Verify that dependency build takes 40m instead of an hour

GHActions:MacOS: Don't use cmake --parallel without specifying job count

---

pcsx2-qt/Debugger/Breakpoints/BreakpointDialog.ui

This reverts commit 92b9390c51ea4e0caaf9f7d3de5e9d4ed2624073.
Reverts changes in https://github.com/PCSX2/pcsx2/pull/12356.
A size of 1 captures all read/write operations which affect the byte at the given address, while a size of 4 is too inclusive and will capture additional variables if the variable at the address broken at is shorter than 32-bits.

Revert "Debugger: Set default breakpoint size to 4"

---

bin/resources/GameIndex.yaml
pcsx2/x86/microVU_Analyze.inl
pcsx2/x86/microVU_Compile.inl
pcsx2/x86/microVU_Lower.inl

Expand the IBit hack to several commands using immediates, to help reduce recompilation on games which modify these values a lot.
Games like Shellshock - Nam '67 and Killzone modify their VU programs a lot, changing immediate values and nothing else in several cases, This expands the IBit hack to try and ignore these differences and load the values from RAM instead of compiling  new program.
Test Shellshock - Nam '67, Killzone, Scarface and Crash Tag Team racing.  If you know any other games that recompile constantly, try enabling the IBit gamefix and see if that helps.
Reduces VU compilation in Killzone by about half
Reduces VU compilation in Shellshock - Nam '67 by roughly 10% (reduces hitching by a bit)

VU: Expand IBit hack to work for immediates on several instructions

---

pcsx2/VMManager.cpp

Enables file logging by default.
Make support easier when asking for an emulog.
Make sure on a clean build file logging is enabled.

VMManager: Enable file logging by default

---

pcsx2-qt/ColorPickerButton.cpp

Fix the display of the LED colours on Windows with the native theme
The native themes would treat the colour set in the stylesheet as ARGB as its 8 hexadecimal digits long
As we never set the alpha, the colour would be fully transparent with these themes
Instead, only use 6 hexadecimal digits for an RGB format
In Controller->Global->Light bulb Icon
Check the Windows native themes to see LED colours are visible
Check other themes to make sure nothing broke there

Qt: Fix display of LED colours on Windows native themes

---

.github/workflows/cron_update_base_translation.yml
.github/workflows/cron_update_controller_db.yml
.github/workflows/macos_build.yml
.github/workflows/release_cut_new.yml
.github/workflows/triage_pr.yml
.github/workflows/windows_build_qt.yml

In wake of a massive supply chain attack in a thirdparty action with [over 23000 repositories having their secrets leaked](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised). I think it's in our best interest to pin actions to the full length commit sha. This is recommended by GitHub on their [Security Hardening Documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
I've left out actions coming from trusted sources such as GitHub or Microsoft.
Using tags is convenient, but a bad actor is able to change what commit a tag points to. In the case of the above incident, all of the tags were silently changed and pointed to the malicious …

CI: Harden security by pinning third-party actions to a SHA

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Makes sure the next draw is using texture mapping before relying on the information in the texture registers.
Regression from #11267
Test Spiderwick Chronicles and Rainbow Six 3 (Already done)
Fixes #12425
Master:
PR:

GS/HW: Fix width prediction on texture shuffles

---

cmake/SearchForStuff.cmake

Add an extra include path to work around [an include bug](https://github.com/KDAB/KDDockWidgets/commit/3d6954f07dbe647295f7d295aa372b9b2daa27b3).
The `INTERFACE_INCLUDE_DIRECTORIES` property I'm using is set in `lib/cmake/KDDockWidgets-qt6/KDDockWidgets-qt6Targets.cmake`:
```
set_target_properties(KDAB::kddockwidgets PROPERTIES
INTERFACE_COMPILE_DEFINITIONS "KDDW_FRONTEND_QTWIDGETS;KDDW_FRONTEND_QT"
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/kddockwidgets-qt6"
INTERFACE_LINK_LIBRARIES "Qt6::Widgets"
)
```
Keep Linux package maintainers happy until a new KDDockWidgets release is published.
I've not done much testing on this. I'm sorry about that but I'm a bit busy at the moment.

Deps: Add an extra include path for KDDockWidgets

---

.github/workflows/scripts/macos/build-dependencies-universal.sh
.github/workflows/scripts/macos/build-dependencies.sh
cmake/SearchForStuff.cmake

Updates Mac Qt to 6.7.3.
We aren't updating past this any time soon to keep compat with 10.15 so let's update to the latest 6.7 version.
Make sure nothing on Mac goes kaboom.

Deps: Update Mac to Qt 6.7.3

---

pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2-qt/Debugger/DebuggerWindow.h
pcsx2-qt/Debugger/DisassemblyWidget.cpp

Prevent the disassembler from jumping to the program counter if the breakpoint code paused the core.
Fix a regression from my docking PR.
Make sure adding a breakpoint when the core is running doesn't make the disassembler jump to the program counter.

Debugger: Don't jump to PC if the breakpoint code paused the core

---

pcsx2-gsrunner/Main.cpp

Lowers the PNG compression on the dump runner
the new default quality/compression of 90% for screenshots was making each frame take 1.56 seconds to dump, which adds up when you're doing thousands of them.  This lowers the compression to 10% which takes 0.0356 seconds to dump, at the cost of being 25% bigger files.
Do note that this is using PNG so the compression is lossless, so the only thing being lost here is a tiny bit of hdd space, and it's not much different from what it was pre the default change.
No need, immediately going to merge.

GS/Runner: Set the screenshot compression low to stop slow dump times

---

pcsx2/GS/Renderers/Common/GSVertexTrace.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Adjust AA1 draw behavior.
Make sure we use coverage alpha on aa1 draw when there's no blending.
Make sure we set coverage alpha to 128 in vertex trace alpha min max.
Some const and cast cleanup.
Bugfix, accuracy, fixes https://github.com/PCSX2/pcsx2/issues/12442
Dump run no changes except the fixed issue.

GS/HW: Adjust AA1 draw behavior.

---

pcsx2/DebugTools/DebugInterface.cpp

BIOS ROM is now valid for reading in the IOP debugger.
Users might want to inspect it.
0xBFC00000 onwards should now be readable in the debugger.
There appear to be strange issues with breakpoints on/around the initial IOP reset vector, I didn't really investigate though.

IOP Debug: allow reading ROM

---

pcsx2-qt/Debugger/Breakpoints/BreakpointModel.cpp
pcsx2-qt/Debugger/Breakpoints/BreakpointWidget.cpp

If you select multiple columns of the same breakpoint, and then try to delete it, PCSX2 will no longer crash. I've also added some error handling logic to BreakpointModel::removeRows while I was at it.
Prevent crashes. At first I was worried this was a regression from my docking PR, but it seems like it isn't.
- Make some breakpoints.
- Select multiple columns from the same breakpoint e.g. with Ctrl+A.
- Hopefully no crash.

Debugger: Fix crash during breakpoint deletion

---

pcsx2/x86/iR3000A.cpp
pcsx2/x86/ix86-32/iR5900.cpp

Adjusts some asserts to not trip every time we run out of rec code space
(They should now only trip if we actually start writing out of bounds)
We shouldn't be tripping asserts during normal operation
Play R&C 2 or 3 for a few hours in a Devel build
(Or just pretend you did and say it's fine)

Core:Rec: Adjust bounds check asserts to not erroneously trip

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Fix typo on Tekken 5 CRC
Condition was backward
Don't :)

GS/HW: Fix typo on Tekken 5 CRC

---

.github/workflows/scripts/linux/build-gammaray.sh
.github/workflows/scripts/windows/build-gammaray.bat
.gitignore

Adds build scripts for [GammaRay](https://github.com/KDAB/GammaRay), a debugging tool for Qt applications.
Screenshots:
After my positive experience with KDDockWidgets, I found KDAB also make this. Should make it easier to debug issues with the Qt frontend.
I didn't have much luck with the latest release (3.1.0 at time of writing), so currently it just downloads the version from the master branch.
Try building it and using it to debug PCSX2.
On Linux:
```
.github/workflows/scripts/linux/build-gammaray.sh deps gammaray
./gammaray/bin/gammaray build/bin/pcsx2-qt
```
On Windows (for example):
```
.github\workflows\scripts\windows\build-gammaray.bat
gammaray\bin\gammaray.exe bin\pcsx2-qtx64-avx2.exe
```
Note: You must run the script to build PCSX2's dependencies first (or in the case of …

Qt: Add GammaRay build scripts

---

pcsx2-qt/Settings/DebugAnalysisSettingsWidget.cpp
pcsx2-qt/Settings/DebugAnalysisSettingsWidget.h

Makes it so the per-game settings dialog no longer forgets previous values for the custom function scan range settings, and removes broken validation checks that should have been removed when the ranges became expressions. Also, make sure symbol sources get saved properly and improve formatting.
Fix some bugs.
Make sure that the function scan range settings all work properly.

Qt: Fix custom scan range settings and make sure to save symbol sources

---

.github/workflows/scripts/macos/build-dependencies.sh

Moves over the URL for Mac Qt deps to archive from official release.
Qt moved 6.7 to the archive which broke our Mac scripts which is bad.
See if the CI explody.

Deps: Move Mac Qt download link to archive

---

common/CocoaTools.h
common/CocoaTools.mm
pcsx2-qt/MainWindow.cpp

This gives it a nice search box for searching other menus.
This would happen automatically to menus named help, but only if the name matched the macOS name for the help menu in the system language.  By explicitly telling macOS which menu is the help menu, this will work regardless of what language is set in PCSX2 vs macOS.
Searchable menus are nice
Check the help menu and see if it has a search box

MacOS: Mark our help menu as the macOS help menu

---

pcsx2-qt/CMakeLists.txt
pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2-qt/Debugger/DebuggerWindow.h
pcsx2-qt/Debugger/Docking/DockManager.cpp
pcsx2-qt/Debugger/Docking/DockManager.h
pcsx2-qt/Debugger/Docking/DockMenuBar.cpp
pcsx2-qt/Debugger/Docking/DockMenuBar.h
pcsx2-qt/Debugger/Docking/DockViews.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/pcsx2-qt.vcxproj
pcsx2-qt/pcsx2-qt.vcxproj.filters

The PR addresses the following theming issues:
- The layout switcher tabs appearing in the wrong place for the [Windows Vista](https://github.com/qt/qtbase/blob/dev/src/plugins/styles/modernwindows/qwindowsvistastyle.cpp) and [Windows 11](https://github.com/qt/qtbase/blob/dev/src/plugins/styles/modernwindows/qwindows11style.cpp) styles.
- A weird underline appearing under the non-selected tabs when using the [Fusion](https://github.com/qt/qtbase/blob/dev/src/widgets/styles/qfusionstyle.cpp) style on Windows.
- The background colour of the menu bar being wrong when using the Windows Vista style.
- The bottom border of menu bar items being drawn too high.
- The lock/unlock toggle having white on white text when the Windows 11 style is used.
- The KDDockWidgets tab bars not updating when the …

Debugger: Fix some theming issues

---

bin/resources/GameIndex.yaml

Changed from 'Special (Texture)' to 'Align to Native'.
Blur offset when upscaling bad.
**Master:**
**PR:**

GameDB: Add HPO Native for resident evil 4

---

bin/resources/GameIndex.yaml

Applied the AtNwTO (Align to Native with Texture Offset) to three Armored Core games:
- Armored Core - Nexus
- Armored Core - Nine Breaker
- Armored Core - Formula Front
And, only for Formula Front, I removed CPU Sprite Render Size hack because AtNwTO does not glitch shadows.
Looks better than Normal (Vertex) at dealing with misaligned post-processing blur.
Pros of AtNwTO:
- Normal causes some UI artifacts and annoying borders, but AtNwTO doesn't.
- Does not glitch shadows as written above.
Cons of AtNwTO:
- Makes Radar HUD gliched in split screen mode.
- Lock-on reticles look horrible unless [No-Interlacing] patch is applied.
- Sometimes produces gliched artifacts on top of screen, but this can be vanished by toggling renderer.
- Same as Normal, it produces blur at top and bottom side of …

GameDB: HPO update for Armored Core games

---

bin/resources/GameIndex.yaml

Adds "Native with Texture Offset" Half Pixel Offset to Ratchet & Clank: Size Matters to fix misaligned bloom.
Game without Half Pixel Offset:
Game with Native with Texture Offset:
Test with other regions besides NTSC.

GameDB: R&C Size Matters HPO Native with Texture Offset

---

pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2/DebugTools/Breakpoints.cpp
pcsx2/DebugTools/Breakpoints.h

Keep a track of which breakpoints were created by the stepping code, and prevent the layout tab corresponding to the CPU the stepping breakpoint was triggered for from blinking.
Fewer distractions while single stepping. I needed to make it its own flag since otherwise it would disable the animation when clicking "Run To Cursor" too, which I think should still make the tab blink.
Test breakpoints and stepping.

Debugger: Prevent blinking animation when stepping

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
.github/workflows/scripts/windows/build-dependencies-arm64.bat
.github/workflows/scripts/windows/build-dependencies.bat
pcsx2-qt/GameList/GameListWidget.cpp

After 17 ice ages 3 global pandemics at least 2 near earth asteroids and the magnetic fields flipping Qt 6.9.0 is finally out and we can finally update to it.
Hopefully this makes Wayland a bit better with some shiny new features.
Test Wayland heavily as well as everything else as usual.

Deps: Update Windows and Linux to Qt 6.9.0

---

pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2-qt/Settings/EmulationSettingsWidget.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/PerformanceMetrics.cpp
pcsx2/VMManager.cpp

Moves Skip Presenting Duplicate Frames from Graphics Settings Advanced to Emulation Settings Frame Pacing/Latency Control,
Move skip dupe frames.
Make sure skip duplicate frames still functions.

UI: Move Skip Presenting Duplicate Frames

---

pcsx2-qt/GameList/GameListWidget.cpp

Enables mouse tracking on the Windows 11 native theme.
Fixes the highlight selection getting stuck after our update to Qt 6.9.0.
Make sure the highlight box does not get stuck when using the Windows 11 native theme.

Qt: Enable mouse tracking on Windows 11 native theme

---

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp

This PR adds a tooltip to the cheat description. unfortunately adding a word wrap to the description requires a significant rework to the code so this will do for now.
Partially fixes #12492 
Better usability and UX.
Test if the cheat descriptions tooltip shows up properly

Qt/Cheats: Add tooltip to cheat descriptions

---

bin/resources/GameIndex.yaml

Fixes FMVs getting absolutely clobbered in hardware mode.
Before:
After:
Broken FMV bad.
Make sure the CI Is happy boy.

GameDB: Fix broken FMVs in Clock Tower 3

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Masks 16 bit colours when blending is disabled. Currently known to fix Need for Speed Carbon car colour compared to software.
Master Hardware:
Master Software:
PR Hardware:
The colours are incorrect and this is bad.
Check any games you have and see if you spot an visual differences and also make sure nothing go boom.

GS/HW: Mask 16bit colours when blending is disabled

---

common/vsprops/QtCompile.props
common/vsprops/QtCompile.targets
common/vsprops/QtCompile.xml
pcsx2-qt/pcsx2-qt.vcxproj
pcsx2-qt/pcsx2-qt.vcxproj.filters

Switches the `QtUi` task to use [tlog files](https://learn.microsoft.com/en-us/visualstudio/extensibility/visual-cpp-project-extensibility?view=vs-2022#tlog-files)
Link the Qt ItemTypes to the relevant ContentTypes
Set the `moc` tool as an input for the QtMoc task
Fix the QtMocClean task
`tlog` files list what files are used or created during the build process.
Visual Studio uses these logs to figure out what files need to be checked for up-to-date checks.
Creating these files will allow Visual Studio to know that a build is needed when the `.ui` files have been edited.
They also get used during clean, making the QtUiClean redundant.
Documentation was pretty thin, only really figured it out thanks to a [blog post](https://www.reedbeta.com/blog/custom-toolchain-with-msbuild/#adding-a-custom …

MSBuild: Improve handling of Qt files

---

pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2-qt/Debugger/DebuggerWindow.h
pcsx2-qt/Settings/DebugUserInterfaceSettingsWidget.cpp
pcsx2-qt/Settings/DebugUserInterfaceSettingsWidget.ui

Adds an option to change the UI refresh interval for the debugger. The default refresh interval remains 1000ms.
Fixes #12489. It's a good suggestion.
Change the setting, see the register and memory views update accordingly.

Debugger: Add setting to change UI refresh interval

---

pcsx2/Achievements.cpp

Push g_medium_font before CalcTextSize is called for the achievement progress text.
This fixes the issue where, depending on the window size/aspect ratio, the vertical alignment of the progress text would be off.
Noticed this on a 1440p monitor with a maximized window.
I've tested by manually resizing the window.

UI: Fix vertical alignment of achievement progress text

---

pcsx2/GS/GSState.cpp

GS: Use inclusive req factor of 1 for sw renderer.
Workaround until the issue can be properly fixed.
Workaround bugfix.
Fixes https://github.com/PCSX2/pcsx2/issues/12100
Fixes https://github.com/PCSX2/pcsx2/issues/12478
Related PR  for reference: https://github.com/PCSX2/pcsx2/pull/12192
Dump run seems okay at first glance?
Test the issues, test games on sw renderer.

GS: Use inclusive req factor of 1 for sw renderer.

---

bin/resources/GameIndex.yaml

Changes preload frame data to software FMV to fix both the black FMVs issue and hash cache disabling itself.
Hash cache disabling itself is not good very bad.

GameDB: Switch Rule of Rose to SoftwareFMV

---

common/Console.cpp

Use the shared file function, allowing shared read
Noticed by https://github.com/PCSX2/pcsx2/issues/12503
Not really any reason to prevent the file from being read while the emulator is open, and it seems like a simple enough change
Run the emulator and try to open the log file

Common: Allow shared reading of log files

---

common/HostSys.h
common/Windows/WinMisc.cpp
pcsx2/CDVD/ThreadedFileReader.cpp

CDVD: Adjust ram requirements when precaching.
When precaching check for available ram instead of total physical ram.
Reserve 2GB headroom for the system.
Better precaching, previously we checked total ram in the system which would result in issues/crashes if the ram was already full.
This aims to address that since we are now checking available/not in use ram instead.
Windows only, test precaching with either plenty of available ram or mostly full.
Todo: linux/mac someone else.

CDVD: Adjust ram requirements when precaching.

---

bin/resources/GameIndex.yaml

Fixes https://github.com/PCSX2/pcsx2/issues/2852
An horizontal & a vertical colored line are present when upscaled in the intro FMV of Soulcalibur II/III, this adds the Software FMV hack to solve it.

GameDB: Adds Software FMV hack to Soulcalibur 2/3 Games

---

bin/resources/GameIndex.yaml

Adds both normal US version of MKA and MKA Premium edition to the memcard filters, as MKA Premium edition saves and loads its saves as if it was the normal MKA version
Mortal Kombat has 2 editions, the normal one, and the premium one, the premium edition saves and loads its game data as if it was the normal edition (SLUS-21410 and NOT SLUS-21543).
Without these filters, the premium edition is unable to properly save and load its data
Also, without these changes, assuming you have data in the normal edition and use a folder type memory card with managed saves, when opening the premium edition it will say the memcard has no MK data and when pressing square to format it, it would wipe all your MK game data (RIP my MKA save)
NOTE: I didnt do the same for the PAL-M5 (SLES-54156) version of the …

GameDB: Add memcard filters for Mortal Kombat Armageddon Premium

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp

GS/DX12: Copy/bind rt when tex is fb on slot 0.
Copy the rt when draw is is tex in fb, we already do this for dx11 since it doesn't support texture barriers.
Accuracy, better parity with dx11.
Fixes Death By Degrees top left issue.
Fixes Time Crisis 3 top left issue.
Fixes Thrillville - Off the Rails.
Test the mentioned games.
Thrillville - Off the Rails
master dx12:
pr dx12:
Note: Death By Degrees and Time Crisis 3 need medium blending.
master dx12:
pr dx12:

GS/DX12: Copy/bind rt when tex is fb on slot 0.

---

common/Darwin/DarwinMisc.cpp
common/Linux/LnxMisc.cpp
pcsx2/CDVD/ThreadedFileReader.cpp
pcsx2/VMManager.cpp

CDVD: Adjust precache osd to display decimal value for required ram.
Qol.
Test precache when there's not enough available ram.

CDVD: Adjust precache osd to display decimal value for required ram, adjust linux get available memory logic.

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/Patch.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

This allows users with monitors of any aspect ratios to use patches made for any other aspect ratio. For example, if on 32:9 one uses a 21:9 patch, pcsx2 will automatically size the presentation to 21:9 within 32:9. This also removes some ugly or hardcoded stuff from the code :). It also opens the door to add a "Custom" user aspect ratio, without the patch needing to specify the aspect ratio, so users could stretch the image to any AR they'd like, but for now there's no need to add that.
Automatic 21:9 within 32:9 (stretched because the cheat wasn't for the right version of the game):
one of the most important things is that 21:9 isn't an actual real aspect ratio, every "21:9" monitor has a slightly different aspect ratio, so patches should specify the exact aspect ratio (3440x1440 being …

GS: Allow for widescreen and ultrawide patches to specify their target aspect ratio

---

pcsx2-qt/Debugger/DebuggerWindow.ui

Add dummy items to the Tools and Windows menus. These menus are regenerated every time they're opened, so the dummy items should never actually be visible.
Fixes #12541 apparently.
Test on macOS.

Debugger: Add dummy actions to the Tools and Windows menus

---

pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fixes regressions with the BIOS, BloodRayne (when upscaling), Prince of Persia Warrior Within (was showing when upscaling but was a caused by an error/waste of time even in native) and Rumble Racing.
BIOS: When we calculate the draw area, it was one pixel short due to a small fraction, which should draw more, so we were loading garbage from VRAM after my changes in RT in RT, so now it accounts more for any fraction.
Fixes https://github.com/PCSX2/pcsx2/issues/12547
BloodRayne: This was disappearing when HPO was set to anything below Align to Native due to some invalidation code which relied on that, but the problem was really misdetection of Triangles being Quads, the game was drawing a border around the screen and we took that as covering the entire thing, so it was getting nuked.
Prince …

GS/HW: Fix up some regressions from RT in RT

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Checks that a dirty target has been accessed recently when accessing inside of it. only affects games using Tex in RT/RT in RT
This is just a paranoia thing to try and make Valkyrie Profile 2 suck less as it creates lots of targets slightly offset from each other and it gets in a mess. I'm full expecting it to break in a new exciting way. There's no real logic behind this except maybe it could be an old target we don't want to use.
Test Valkyrie Profile 2 and Project Snowblind (if possible, just to confirm it's ok) 
Fixes Valkyrie Profile 2 bug:
Master:
PR:

GS/HW: Only reuse dirty targets that were recently accessed

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/HW: Unlink source texture from old target before deletion.
DT Racer hits this path and causes a crash when RT in RT is disabled, so let's make sure source and target texture isn't linked/shared before deleting the target.
Fixes DT Racer crashing when RT in RT is disabled (old issue and was present before RT in RT was introduced).
Test DT Racer and variety of games, no difference on dump runner.
Most easy to test the crash is with debug build or when switching between renderers, mostly OpenGL.

GS/HW: Unlink source texture from old target before deletion.

---

bin/resources/shaders/common/fxaa.fx
pcsx2/ShaderCacheVersion.h

GS/Shaders: Try to fix Warning X4000: FxaaPixelShader potentially unitialized variable.
Clean up shader warnings on DX12.
I wasn't able to reproduce it after a system restart so I dunno, just in case let's clean it up, remove extra conditions, make sure everything is initialized for returning values.
Test Fxaa on all renderers if it still works, see if any warnings are present on dx12, make sure to clean shader cache.

GS/Shaders: Try to fix Warning X4000: FxaaPixelShader potentially unitialized variable.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Uses the correct vertex colour on target clears. Fixes screen transitions in Sega Ages 2005 Vol 1 Phantasy Star: Generation and Dodgeball.
Before:
After:
Transitions should fade to black not a deep purple.
Test aforementioned games and any other random assortment of games.

GS/HW: Use correct vertex colour on target clear

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/HW: Also unlink source texture from target before deletion on z draws.
Futureproof bugfix.
There's got to be that one game that does this, so far we don't have any hits but better play it safe than sorry.
Hard to test, the only way to get it to crash is random or debug build consistently.

GS/HW: Also unlink source texture from target before deletion on z draws.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Fix ResizeTexture not getting the proper new_drect values.
Bugfix, accuracy, fixes vkCmdSetScissor validation layer errors.
Improves VP2 a bit.

GS/HW: Fix ResizeTexture not getting the proper new_drect values.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Merges any targets which fall within a target after expanding the target backwards.
Also don't invalidate RGB on different target types, this conflicts with Gran Turismo 3's transition effects, possibly due to the CRC hack.
Bug was exposed with #12581 where a target ended up inside where another target expanded to, causing source lookups to pick the wrong target, this merges the two together so the right data exists inside the expanded target.
Test Valkyrie Profile 2 and Tomb Raider Legend, not sure it affects much else.

GS/HW: Merge contained targets when expanding target backward.

---

common/Linux/LnxMisc.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/Input/SDLInputSource.cpp

Misc: Fix compiler warnings.
Mostly -Wsign-compare.
GS/GL: Guard/track PopDebugGroup calls.
Fixes GL_STACK_UNDERFLOW and GL_INVALID_VALUE issues which spammed the log.
common-linux: Fix -Wformat warnings.
Fixing compiler warnings.
CI passes without the warnings.
For OpenGL you need to build debug build and check the console compared to master, compare the both.

Misc: Fix compiler warnings and debug fixes.

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2/Hotkeys.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/ImGui/ImGuiOverlays.h
pcsx2/VMManager.cpp
pcsx2/VMManager.h

This PR adds the option for you to load backup savestates using either hotkey or the Load State menu.
NOTE: The hotkey are not bound by default and has to be bound manually.
QoL Improvements.
Test loading backup savestates, either do it through the context menu or by using hotkey (you need to bind it first)

Savestate: Add backup slot loading ability

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/ImGui/FullscreenUI.cpp

Removes the fractional values from the internal resolution selector. They can still be used if set via the ini as you could previously.
They are very jank and cause a variety of graphical issues in certain games.
Make sure they are gone from the internal resolution selector in the main UI and FSUI.

UI: Remove fractional upscales

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Detect if RT in RT is finding a double buffer when Z isn't offset and split them.
It is impossible for us to write to the Z buffer in a different location to the colour pixels, which caused a copy to happen every draw this happened, which in some situations, like Stolen, caused 1200+ copies per frame, and as you can imagine, this was very slow.
Test Stolen, maybe a smattering of other games fixed by RT in RT #11461
Stat changes for Stolen:
Draw Calls: -837 [3488=>2651]
Render Passes: -772 [3227=>2455]
Copies: -964 [1242=>278]
Uploads: -4 [54=>50]
Framerate roughly doubles and a bit.

GS/HW: Detect double buffers when Z not offset during RT in RT

---

pcsx2-qt/Settings/AchievementSettingsWidget.cpp

Fixes #12595
No more crashy
Check all per-game achievement settings, tick/untick the checkboxes.

Qt: Fix crashing per-game achievement sound effect settings

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
cmake/SearchForStuff.cmake
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp

Build PlutoVG as a shared lib
Remove the version check for PlutoVG in our CMake file
Fix Fill mode for `CenterImage()` when using an `ImRect` region
All other dependencies built with the dependency script are build shared.
The changes between PlutoVG 0.0.13 and 1.0.0 don't impact our code, Arch seems to patch their build of PlutoSVG to accept the newer version of PlutoVG, so we should accept the same version it if building with system packages.
Bug fixes
Make sure CI doesn’t explode
Test AppImage can still render the region and star SVG files

ImGui SVG Fixes

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

Removes the Haunting Ground CRC and round sprite half replacing it with Tex in RT and ATNWTO.
Fixes #12594 
The CRC breaks the game now and Tex in RT can fix the issue without it.
Make sure the game is not broken in any new fun ways.

GS/HW: Remove Haunting Ground CRC

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Fix copy range for shuffles.
We should be using the sizes based on source instead of target when clamping depth range.
Fixes Hitman Blood Money validation errors/crashes/broken graphics varying on renderer.
Dump run all good, test Hitman Blood Money on different renderers.

GS/HW: Fix copy range for shuffles.

---

bin/docs/GPL.html
bin/docs/ThirdPartyLicenses.html
pcsx2/Docs/License.txt

- Updates an old file that was falsely implying PCSX2 was still licensed under the LGPL.
- Adds missing third party licenses for the nlohmann JSON library (used by KDDockWidgets), libiberty (the symbol demangler), and Pluto(S)VG.
- The formatting of the third party licenses file has been improved.
- The GPL license file has been replaced with a fresh copy, removing some bizarre advertising/tracking gunk that was previously present (GovanifY figured out it was probably injected by an ad blocker).
- Comply with the licenses of our dependencies.
- Fix some issues with the existing license documents.
Open the about dialog, make sure Qt is rendering the license and third party licenses documents correctly.

Docs: Update licensing documentation

---

bin/resources/GameIndex.yaml

Fixes water lines on sewer levels by preferring HPO Native with Texture Offset.
**Master:**
**PR:**
[GS Dump](https://drive.google.com/file/d/1XhrOsTXsLcRtWfXusWIeNnkVCeH5avbz/view?usp=sharing)
Upscaling issues bad.
Check if I didn't screw up anything else.

GameDB: HPO Native w/TO for Resident Evil Dead Aim

---

bin/resources/GameIndex.yaml

Changes Half Pixel Offset from Normal (Vertex) to Align to Native
The game looks better and sharper upscaled.
Software
Normal (Vertex)
Align to Native

GameDB: Add ATN to Fatal Frame III

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp

Fixes an issue where the global volume, fast-forward volume, and mute settings would override what was in the per-game settings if the global settings were changed while the VM was running. This was because we unconditionally changed what the emu thread was doing with those specific settings if the global ones changed – rather than using `applySettings()` after committing the changes which would give per-game settings precedence over global ones.
Fixes #12408 as well as two related bugs.
* Set the volume, fast-forward volume, and mute settings to something in the per-game settings.
* Go into a game.
* Try to mess with these settings globally and see if those global settings interfere with the per-game settings (the per-game settings should take priority).

Audio: Fix global settings overriding per-game ones

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Adjust Qt logic to handle "(Default)" as an empty string
Adjust previously unused logic to save the default adapter as "(Default)" (untranslated) instead of an empty string
Use said previously unused logic to handle saving the adapter setting
Enable translating the default adapter string
Strangely, the needed logic was already present (but partly unused), it just needed adjustment to match https://github.com/PCSX2/pcsx2/commit/1b50057764a351e942c8087dc46cc81e73907889
Prior to https://github.com/PCSX2/pcsx2/commit/1b50057764a351e942c8087dc46cc81e73907889, we where accidentality saving "(Default)" in the users language (instead of an empty string as intended).
https://github.com/PCSX2/pcsx2/commit/1b50057764a351e942c8087dc46cc81e73907889 switched to intentionally saving "(Default)" in the …

Qt: Allow translating the default adapter text

---

pcsx2/x86/ix86-32/recVTLB.cpp

Since this works well right now I don't think we need this.

vtlb: silence backpatch log spam

---

bin/docs/ThirdPartyLicenses.html

- Added licenses for Roboto (big picture) and Noto Sans (non-Latin scripts).
- Changed "Index" to "Table of Contents".
- Comply with the licenses of our dependencies.
Open the about dialog, make sure Qt is rendering the license and third party licenses documents correctly.

Docs: Add even more missing third party licenses

---

pcsx2-qt/Debugger/Memory/MemorySearchView.ui

- The drop down option "Array of byte" has been changed to "Byte Array".
Better grammar.
N/A

Debugger: Fix a typo in the memory search view

---

.github/workflows/linux_build_qt.yml
pcsx2/CDVD/CDVDcommon.h

Disable PCH on Linux AppImage builds.
This allows us to better utilize ccache. The appimage builds are roughly 5 minutes faster (~7.30 to ~2.30 minutes)
Unfortunately I question if ccache is actually working properly with flatpak-builder. Disabling the PCH there did not exhibit any build time increase, so flatpak builds are going to be left as-is.

CI: Disable PCH for Linux AppImage builds

---

pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS: Retry texture creation after initial retry fails.
This should've been done.
GS/HW: Add hazard check for temporary depth buffer creation.
GS/HW: Add hazard check for date depth buffer creation.
Texture creation hazard checks, less prone to crash, also retry creation texture in CreateSurface after the memory pool has been cleared should've been done, this will be rarely hit unless out of memory, either to tc bug or high upscaling?
Make sure nothing broke, see if you can trigger any OOM issues with high upscaling, see if it's better? The Hazard checks might trigger in the same conditions too.

GS: Improve texture creation hazards.

---

.github/workflows/scripts/windows/build-dependencies-arm64.bat
.github/workflows/scripts/windows/build-dependencies.bat
cmake/BuildParameters.cmake
common/vsprops/LinkPCSX2Deps.props
pcsx2/CMakeLists.txt

Also build KDDockWidgets in debug when Qt is built for debug (Windows)
This is a Windows only issue, on other platforms we always build and link to release builds of Qt.
A clean debug build would only copy the debug Qt binaries, but the release build of KDDockWidgets 
KDDockWidgets would then complain about not being able to find the release Qt binaries
Building and linking against a debug build of KDDockWidgets would resolve this.
For some reason, KDDockWidgets decided to name the Windows binaries differently if `CMAKE_CONFIGURATION_TYPES` is used, so always use that even when only building release, and change out build scripts to suit the other name.
The CMake was updated to suit, I noticed that, with the exception of Qt, Devel would import debug packages if given the choice, I've …

Fix KDDockWidgets needing release Qt on Windows Debug builds

---

.github/PULL_REQUEST_TEMPLATE.md

Add a "Did you use AI blah blah blah" disclosure question for PR authors to answer.
I want this to be a little bit of an RFC. Does anyone else agree / disagree?
Unfortunately open source seems to be experiencing a increasingly common pattern of AI slop in many forms. Such as [bogus CVE reports](https://daniel.haxx.se/blog/2023/09/05/bogus-cve-follow-ups/) and [pull requests](https://github.com/PCSX2/pcsx2/pull/11825#issuecomment-2366845879). Avoiding the politics involved with its usage, it's just incredibly time consuming for us when it's used improperly. It would be nice to know when to put on my BS glasses.

GitHub: Require PR authors to disclose AI usage

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

When combining targets used the drawn area not the valid area.
Valid area can be garbage if the target is preloaded from GS memory but only draws a tiny bit, then if it's combined in to another target, it could destroy perfectly valid data.
Test Valkyrie Profile 2
Fixes some glitching with Valkyrie Profile 2 (mostly single frames)
Master:
PR:
Master:
PR:

GS/HW: Combine target using the drawn area, not valid area

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fix the combine targets function when the end block wraps around the end of GS memory causing misdetections.
On Tex in RT source lookups, if the width doesn't match the source and is just a PSMT8H lookup, take the frame width as the source target width.
The combine targets function was just wrong, misdetection due to targets wrapping around the end of memory, this should be fine now and stop mistaken combining/deleting.
The PSMT8H lookup was a pain one with Hitman Blood Money where it was storing information in the alpha at a buffer width of 4, then the RGB was buffer width of 8, causing the source lookups to think it was 8 wide and picked the wrong location inside the target.  In these cases we will use the FRAME width as a source of truth to how big it should be, as it's likely a kind …

GS/TC: Fix combine targets wrapped end block + PSMT8H lookup

---

pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Enable feedback loop if channel shuffle enabled barriers.
Need to make sure to enable feedback loop if barriers got enabled on a channel shuffle draw, was mostly an issue on minimum blending on Hitman Blood Money.
Bugfix, yes another Hitman fix.
Test Hitman Blood Money on Minimum blend, smoke test some other games maybe?

GS/HW: Enable feedback loop if channel shuffle enabled barriers.

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ShaderCacheVersion.h

GS/HW: Fix texture copies when tex is fb draw. 
Fixes an issue with texture copies didn't work properly on tex is fb draw: Fixes Hitman Blood Money on minimum blend. DX can't do partial depth copy so do a shader based copy which works.
Fixes a bunch of games that couldn't do partial depth copy on dx.
GS/HW: Backport some tex is fb shaders to dx and opengl.
Bonus unrelated: FullscreenUI: Fix -Wlogical-op-parentheses warning. 
Accuracy, bugfixes.
Fixes https://github.com/PCSX2/pcsx2/issues/12309
Dump run is ok for both dx11, vk and gl.
Test mentioned games on mentioned renderers, test other stuff on all hw renderers too.
Test Hitman on minimum and basic blend, test the other games on basic blend or whatever they use, make sure nothing broke on all hw renderers.
VK fixes:
Hitman Blood Money …

GS/HW: Fix texture copies when tex is fb draw, backport missing tex is fb shaders to gl/dx.

---

.github/PULL_REQUEST_TEMPLATE.md

Made it so the "Did you use AI..." disclosure doesn't use checkboxes anymore.
Using checkboxes implicitly made it a task list that cluttered up the PR list.
This "anti-feature" request was proposed 4 years ago, it was never implemented.
https://github.com/orgs/community/discussions/5197
None

Make authors disclose whether they used AI or not.

---

common/Darwin/DarwinMisc.cpp

vm_map reads the address you pass it, so we need to initialize it.
Dolphin had a similar issue that they just fixed: https://github.com/dolphin-emu/dolphin/pull/13521
IDK if this affected anyone in release builds, but it definitely affected my debug builds
Less broken
Open PCSX2 and check if it complains about failing to allocate memory
Might help with #11728

Core:macOS: Initialize all address variables passed to vm_map

---

cmake/BuildParameters.cmake

Widen the range of configurations that can be imported with a Devel build
Arch likes to build packages with `CMAKE_BUILD_TYPE=None` because they don't want to build with `-O3` (which apparently is the default for CMake release builds).
The `CMAKE_MAP_IMPORTED_CONFIG_DEVEL` I added to avoid linking to debug libraries didn't factor this in.
While I'm at it, also add in `MinSizeRel` (which I missed) and `NoConfig` (`CMAKE_BUILD_TYPE=""`), since they link against the release runtime.
Build a dependency using a `CMAKE_BUILD_TYPE` such as `RelWithDebInfo/Release/None/""`
See if the project configures

CMake: Widen the range of configurations that can be imported with a Devel build

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

GS/GL: Check for texture creation hazard for fb copy.
GS/DX11: Merge CloneTexture with CopyRect.
Unified between renderers, easier to make shared changes.
GS/DX: DX requires a copy to sample the depth buffer.
Accuracy, bugfixes, robustness.
Test time crisis 3, test games that use shuffles, make sure dx11/12, gl didn't break.
Fixes Time Crisis on DX11/12 which costs +79 copies
Master:
PR:

GS/HW: Improve tex is ds handle on DX, clean up some stuff.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Deletes fully dirtied targets on source lookup
Allows RT in RT to use targets last used up to 3 draws ago instead of 1
Updates a source is it's pulling from GS memory but should be using the newly created target
Detects shuffles to avoid the target height cache being poisoned with double heights
More stuff in Valkyrie Profile 2 not working correctly, then came across the height cache issue with The Getaway whilst attempting to fix this.
Test Valkyrie Profile 2 and some random games with Tex in RT enabled.
No

GS/HW: Improve rt in rt lenience and dirty/new rt handling

---

.github/workflows/scripts/macos/build-dependencies-universal.sh

This PR makes three changes to the macOS universal dependency build script.
1. When looking for x86_64 binaries to merge and create fat binaries, it now skips any arm64 binaries that may appear in the x86_64 build directory, e.g. ``lz4-1.10.0/build-dir/CMakeFiles/4.0.2/CompilerIdC/a.out``
2. Qt downloads moved to the archive, where Qt 6.7 is hosted.
3. libjpegturbo, PlutoVG and PlutoSVG are now built as fat binaries.
Although this script is not currently used in any CI steps, it should still work. It may come in handy for any developers wanting to work on the arm64 build of the emulator.
1. Run this script
2. Build the x86_64 version of the emulator
3. Make sure the emulator still works and all libraries in ``PCSX2.app/Contents/Frameworks`` are universal binaries

CI: Fix script building universal dependencies on macOS

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Allow partial depth copy on dx12.
Optimization, unlike dx11 dx12 supports partial depth copy which is faster so we don't need the sample depth check, the check is no longer needed for dx11 as it's already handled in device11.
Didn't find any games that hit this code path, smoke test.

GS/HW: Allow partial depth copy on dx12.

---

pcsx2/DebugTools/Breakpoints.h

Makes sure the `hasCond` member variable in breakpoints is initialized.
I think this is why breakpoints stopped working for the AppImage builds. Looks like it was my fault.
Make sure that breakpoints work with the AppImage.
No.

DebugTools: Fix uninitialized variable in breakpoint code

---

pcsx2-qt/Debugger/ThreadView.cpp

Fixes indexing issues with the thread list when sorted in an order that doesn't match the underlying thread array.
Also makes clicking the entry point move the disassembler instead of the memory view.
Since the list is sortable we need to look up the real source index through the proxy model to get a correct index.
Make sure the thread list behaves correctly.
No

debugger: fix thread view row lookup

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Improves target selection and shuffle detection
as a bonus it gets rid of a couple of copies here and there, but nothing major.
It was possible for a texture inside RT picking a 32bit target for a 16bit draw which as been overwritten and no longer 32bit, and is not a shuffle.  This improves the shuffle detection for some edge cases and disallows reading 32bit as 16bit unless it's a shuffle.
Test random games with Tex in RT/RT in RT, but mainly Star Ocean 3
no
Master:
PR:

GS/TC: Don't allow Tex in RT 32bit target use as 16bit if not a shuffle

---

bin/resources/GameIndex.yaml

Some games are missing some gamefixes or other type of fixes. Also added comment for like Energy Airforce where a legacy code never had a comment and need to check in future to amend properly. Also missing entry SLPS-25875:
name: "xxxHolic - Shigatsu Tsuitachi no Izayoi Sowa [Best Collection]"
Better GameDB
Check the applicable games
No, I am crazy enough.

GameDB: Add missing variants + fixes

---

pcsx2/GS/GSClut.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Add sanity/hazard checks for DATE and Texture barriers.
When checking for full barrier, also check if texture barriers are supported.
Get rid of preprocessSel in DX11, turn off full barrier and related stuff when not supported in rendererhw instead.
Check if StencilDate types are actually enabled, don't want to turn it on for any others.
Bonus:
GSClut: Get rid of m_read.dirty assert in GetAlphaMinMax32.
Replace it with a log.
Hazard checks, these shouldn't be hit but just in case, and makes testing/changing stuff easier.
Quick test on Persona 3/4 shadows, GT4 car reflections with max blending, and some other games.

GS/HW: Add sanity/hazard checks for DATE and Texture barriers.

---

bin/resources/GameIndex.yaml

Adds the 4 versions of [PSX Update Disc](https://wiki.pcsx2.net/PSX_Update_Disc) to the index.
I had pondered for a couple months now how to make the PCSX2 menu show the PSX Update Discs with a Japanese flag by default (as opposed to having to change the flag manually in PCSX2's game settings), and gradually found the Game Index system, which I'm now hoping to add the disc infos to.
1. Have any of the PSX Update Disc versions show up in the game list of a PCSX2 instance.
2. See that their flags by default show a grey box with a question mark, or no box/flag at all.
No.

Add listings for PSX Update Disc to the GameDB.

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Always deletes depth targets on clear overlap
This was the behaviour from before RT in RT, however when I allowed partial invalidations I didn't limit it to render targets, this changes that.
Test Ace Coimbat Squadron Leader/The Belkin War (just in case) and WWE Smackdown Vs RAW 2006 
If you mean Actual Insanity, yes, if you mean Artificial Intelligence, no.
WWE SvR 2006:
Master:
PR:

GS/TC: On clear delete overlapping depth targets

---

bin/resources/GameIndex.yaml
pcsx2/ImGui/ImGuiOverlays.cpp

Adds various fixes and some reverts that broke games like Dragon Quest 8. Also adds vsync to the OSD to make it easier to tell when a user has it on.
Fixes good more fixes better.
Make sure the CI passes.
Nein.

GameDB: Various Fixes Part 4 (one with cheese)

---

bin/resources/GameIndex.yaml

Add memcard filters for some NTSC-J titles.
Couldn't load savedata due to a different game ID.
Try save and load in the applicable games.
No.

GameDB: Add memcard filters for some NTSC-J titles.

---

pcsx2/GSDumpReplayer.cpp

Makes it so that the GS run stats flip to the right side if the performance stats are on the left side.
Fixes #12706.
Try to repro 12706 (steps there).
Negative. I am a flesh-based organic humanoid much like yourself. beep boop

OSD: Fix performance overlay overwriting dump stats when shifted left

---

pcsx2/ImGui/FullscreenUI.cpp

This PR fixes savestates entry duplicating due to backup states.
Before:
After:
Less brokee, more goodee.
When running a game, go to the Save state menu on BPM and see if the entry are duplicated.
Nggak

FSUI: Fix save state duplicate entry

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Fixes the scissor size for copying the HDR texture to/from the RT
Was overlooked/broken in #12254
Test HDR games mentioned in the above PR with DX12 make sure they look okay.
No
Master:
PR:

GS/DX12: Fix HDR copy scissor area

---

pcsx2/SIO/Memcard/MemoryCardFile.cpp

Fixes memory card alphabetical ordering on Linux when using btrfs.
On Linux in some situations memory cards did not return alphabetically this should fix it.
Make sure in those same situations memory cards return alphabetically.
No.

MemoryCardFile: Fix memory card sorting on Linux

---

pcsx2/FPU.cpp
pcsx2/VUops.cpp
pcsx2/x86/iFPU.cpp
pcsx2/x86/iFPUd.cpp
pcsx2/x86/microVU_Misc.h
pcsx2/x86/microVU_Upper.inl

Slightly faster FTOI implementation
I also removed the FPUd implementation, since it was identical to the normal one
Also I totally broke FTOI on negative numbers in the interpreter in #12324, this fixes that
Faster yay
Test games
<details>
<summary>Run this program</summary>
```cpp
int main(int argc, const char* argv[]) {
u32 i = 0;
do {
if ((i & 0xfffffff) == 0)
printf("%08x\n", i);
u32 cop1, cop2;
asm(
"qmtc2 %[reg], $vf1\n\t"
"mtc1  %[reg], $f1 \n\t"
"vftoi0  $vf2, $vf1\n\t"
"cvt.w.s $f2,  $f1 \n\t"
"qmfc2 %[c2],  $vf2\n\t"
"mfc1  %[c1],  $f2 \n\t"
"addiu %[c2],  0   \n\t"
: [c1]"=r"(cop1), [c2]"=r"(cop2)
: [reg]"r"(i)
: "f1", "f2"
);
u32 exponent = (i >> 23) & 0xff;
u32 expected;
if (exponent >= 158) {
expected = (i & 0x80000000) ? 0x80000000 : 0x7fffffff;
} else if (exponent < 127) …
```

Core: FTOI optimizations

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/TC: Fine tune Frame buffer conversion.
Make it so Frame buffer conversion isn't enabled when not needed and break things, exclude shuffles or 32bit format.
Test games that use frame buffer conversion, see db.
No.

GS/TC: Fine tune Frame buffer conversion.

---

pcsx2-qt/GameList/GameListModel.cpp
pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/Settings/GameSummaryWidget.cpp
pcsx2/GameList.cpp
pcsx2/GameList.h
pcsx2/ImGui/FullscreenUI.cpp

- The file paths for the region flag icons are no longer translated incorrectly.
- Various strings are no longer translated twice.
- The `GameList::EntryTypeToString`, `GameList::RegionToString` and `GameList::EntryCompatibilityRatingToString` functions have been refactored so that they can return a translated or non-translated string depending on the value of the new `translate` parameter.
- The `GameList::ScanDirectory` function has been very slightly modified to make clang-format happy.
- Prevent the `GameList::EntryType::Invalid` option from appearing in the filter box in the GUI.
- Clip the flag and compatibility rating pixmaps to the available space.
- The region flag icons were broken for non-English languages.
- Strings shouldn't be translated twice.
- The `EntryTypeToString` …

GameList: Fix region flag icons for non-English languages and more

---

pcsx2/GS/GSLocalMemory.cpp
pcsx2/GS/GSLocalMemory.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Invalidate by column if in the first block when formats do not match but the size of the invalidation is less than/equal to the size of a column
This should be safe to do as the storage size of a column is the same on every format, and the first column of the first block in a page is always in the same place.  Katamari Damacy overwrites this with a palette, for some reason, I guess they thought it'd be hidden by overscan, but we were nuking the entire first page before to be safe, leaving a very obvious black square in the corner.
Check Katamari Damacy 2 player mode, not much else affected.
No
Fixes #8353
Katamari Damacy:
Master:
PR (Software looks identical):

GS/HW: Invalidate single columns on format mismatch

---

pcsx2-qt/MainWindow.ui
pcsx2/ImGui/FullscreenUI.cpp

Standardizes the ordering of the options in 1) the Qt UI widget, 2) the 'Settings' dropdown menu, and 3) the FSUI navbar. This PR doesn't add any options where they already aren't to avoid an omnibus; it simply reorders them where they already exist to conform to a standard order:
1) Interface
2) Game List (not yet implemented in FSUI)
3) BIOS
4) Emulation
5) Graphics
6) Audio
7) Memory Cards
8) Folders
9) Achievements
10) Controllers (part of controllers rather than the Qt settings widget)
11) Hotkeys (part of controllers rather than the Qt settings widget)
12) Advanced (not in the toolbar; very arguably should be)
13) Debug (not yet in toolbar or FSUI; very arguably should be in the former, and I'm planning work toward the latter)
The ordering of options is inconsistent between the Qt …

UI: Standardize order of option groups

---

pcsx2/GS/GSState.cpp

Allows the strips to be of any size, as long as the last one is butted up against the current one and the height matches.
Some games like Prince of Persia do a tiny strip, followed by a bunch of normal ones, but this was enough to throw off the "no gaps" check, making native scaling fail to happen on some draws. That said I didn't really notice any changes outside that series
Test the lighting with high upscales in the prince of persia games vs master.
Nope.
Sands of Time:
Master:
PR:

GS/HW: Adjust SpriteNoGaps check for vertical strips

---

pcsx2-qt/Debugger/Docking/DockViews.cpp

Check if the version of KDDockWidgets in use has a certain hack in place before trying to work around it.
I'd like to get this in before 2.4.
This may prevent a memory leak in the case that someone wants to build an older version of PCSX2 against a newer version of KDDockWidgets where [this hack might work differently](https://github.com/KDAB/KDDockWidgets/pull/636).
Try changing between different themes on Windows.
No.

Debugger: Improve DockTabBar ownership workaround

---

pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp

FSUI was sending this option to the shadow realm by sending it to the [UI] section (whereas it's under [EmuCore] in the Qt settings) and calling it "DiscordPresence" instead of "EnableDiscordPresence".
This should hopefully fix Discord Rich Presence in the FSUI. I can't test because Discord Rich Presence has been broken for me on PCSX2 for a long time.
1) Open FSUI
2) Simultaneously open `Settings` > `Interface`.
3) Make sure that when you check and uncheck `Enable Discord Presence` in the Qt UI that the corresponding slider in the FSUI moves along with it.
I have no mouth and I must eat spaghetti

UI: Fix Discord Rich Presence not activating in FSUI

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h

Stores the GS Transfer registers in our internal state on TRXDIR write (transfer start), as the registers can be updated after this and have no effect on the current transfer.
Saishuu Densha was doing this causing it to not only corrupt the picture and offset it by 16x16 pixels, but also crash the emulator due to bad memory access.
Test Saishuu Densha, not sure what else does this cursed nonsense.
No.
Saishuu Densha:
Master (with crash not pictured here):
PR:

GS: Store entire GS transfer state at TRXDIR write

---

pcsx2-qt/CoverDownloadDialog.cpp
pcsx2-qt/DisplayWidget.cpp
pcsx2-qt/GameList/GameListModel.cpp
pcsx2-qt/GameList/GameListModel.h
pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/GameList/GameListWidget.h
pcsx2-qt/QtUtils.cpp
pcsx2-qt/QtUtils.h
pcsx2-qt/Settings/AchievementLoginDialog.cpp
pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp
pcsx2-qt/Settings/MemoryCardCreateDialog.cpp

Fix DPR handling in Game-list flags/icons.
Fix icons in setting dialogs  being drawn at a higher DPR then needed for the current screen.
Remove seemingly redundant method
Use DPR changed event instead of paint event to detect DPR changes in display widget
Most of the icons corrected here where drawn at highest DPR of all connected monitors, rather then the monitor the window was visible on, while the stars are drawn at a DPR of 1.
For icons being rendered from SVGs, upscaling/downscaling artefacts can be noticeable
This was moreso for stars as they where upscaled, flags and various setting dialog icons where less noticible as these got downscaled.
The existing `GetDevicePixelRatioForWidget()` appears redundant and I couldn't see a reason for not just using `QWidget.devicePixelRatioF()`. …

Qt: Better handle multi monitor setups with different DPIs

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS: Better handle hazards when dx12/vk device creation fails.
VK/DX12: Move CreateNullTexture before reading shader resource.
Fixes null pointer dereference.
VK: Check if vertex buffer is valid before binding.
Fixes vertex buffer validation error null handle.
Fixes a crash on dx12 when tfx shader is not found, issue was we were trying to unbind null textures when destroying device but since the shader was not found null textures weren't created in the first place leading to dereferencing a null pointer.
Fixes validation error on vk when device creation fails (missing shaders for example) which binded invalid vertex buffer.
Delete the vk and dx12 shaders folders/files, try to boot anything, see if dx12 crashes, see if vk validation error is resolved.
Also smoke test dx12/vk normally.
Is …

GS: Better handle hazards when dx12/vk device creation fails.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Clear any matched targets which exist on a hardware move to avoid it taking precedence.
Removes the CRC hack for Simple 2000 Series Vol. 114 - The Onna Okappichi Torimonochou - Oharu-chan GoGoGo! and fixes the shadows
The move was being ignored as this was considered the copy.
Test Simple 2000 Series Vol. 114 - The Onna Okappichi Torimonochou - Oharu-chan GoGoGo!
No
Simple 2000 Series Vol. 114 - The Onna Okappichi Torimonochou - Oharu-chan GoGoGo!:
Master:
PR:

GS/HW: Clear matched target on HW Move

---

pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/Themes.cpp

Include tint colour in cache key for selected icons generated for stars/flags.
When switching themes, the tinted star for the wrong theme could be used for selected items.
Select a game on the gamelist
Change to a different theme
Select a game on the gamelist and check that the colour the stars are tinted to
Restart PCSX2
Select a game on the gamelist and check that the colour the stars are tinted to, the before restart tint should match this
Negative

Qt: Fix selected gamelist icons being wrong colour after theme switch

---

pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp

Previously, the emulator would only create the texture dump directory if the *game dir* didn't exist.  If someone grabbed a texture pack online and installed it, dumping would not work because there was a game dir but no dump dir.
In addition, some texture pack creators seem to be renaming their texture packs' replacement directories with capital letters.  This adds a warning if any case mismatches are found.  Hopefully this will both (A) deter renaming of texture replacements and (B) notify users on case sensitive filesystems that they need to rename the folder to use the texture pack.
So users don't spend like a week and a half of getting frustrated trying to figure out why their texture packs are broken.
- Try to dump textures with a game folder but no dump folder
- This should work
- …

GS: Better texture dump directory handling

---

cmake/SearchForStuff.cmake
pcsx2-qt/Debugger/Docking/DropIndicators.cpp

- Specify the minimum version of KDDockWidgets supported (2.0.0) in the cmake file.
- Add a missing include that's required to actually get it building with 2.0.0.
Friendlier build error for users trying to build against KDDockWidgets 1.x (e.g. #12778). 2.x is majorly different so this won't work.
Make sure it builds against different supported versions of KDDockWidgets.
No.

Deps: Specify minimum version of KDDockWidgets in cmake file

---

CMakeLists.txt
cmake/BuildParameters.cmake
common/CocoaTools.h
common/CocoaTools.mm
pcsx2-gsrunner/Main.cpp
pcsx2/CMakeLists.txt
pcsx2/GS/Renderers/Metal/GSMTLDeviceInfo.mm
pcsx2/Input/InputManager.cpp
pcsx2/Pcsx2Config.cpp

Supports running the gsdump runner on macOS
Note: Since the gsdump runner is not in an application bundle, it will search for a `resources` directory in the same directory as it, similar to how the main PCSX2 exe works on Windows.
It's nice to have a working GSdump runner
Test the GSdump runner on macOS
~~(Note: I tested a while back and it worked then, but then I rebased it without testing so please test)~~
Edit: I tested it, it now works without crashing on shutdown.
No

GSRunner: Mac support

---

bin/resources/GameIndex.yaml

Fixes broken and missing graphics in simple series 2000 vol 92.
Fixes #12806
Game broken bad.
No.

GameDB: Simple 2000 Vol 92 Fixes

---

bin/resources/GameIndex.yaml

Adds native scaling to Scooby-Doo! Unmasked to fix misaligned post-processing effects.
This game downscales non-bilinearly, like [Scaler](https://github.com/PCSX2/pcsx2/pull/11514).
Test Scooby-Doo with and without native scaling.
Before:
After:
No.

GameDB: Add native scaling to Scooby-Doo! Unmasked

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Removes the Channel Shuffle portion of the CRC hack override from the Namco CRC hack, which is currently used for Tekken 5, Death by Degrees, Tales of the Abyss and some (if not all) Taiko no Tatsujin games.
This was implemented before RT in RT was a thing mainly for Tekken 5, so it couldn't be done by conventional methods, but now it can, and this override was causing problems with Death by Degrees, which just got moved over to the namco CRC, but has a more complex channel shuffle than was present.
Test the above mentioned games to make sure they're okay. GS Dumps turned out fine.
No,
Death By Degrees:
Master:
PR:

GS/HW: Remove channel shuffle override from Namco CRC hack

---

pcsx2-qt/LogWindow.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2/Host.h
pcsx2/ImGui/FullscreenUI.cpp
tests/ctest/core/StubHost.cpp

This PR fixes a crash to desktop when you are trying to Exit to Desktop while running in No GUI mode.
Less crashing more goodie
Launch PCSX2 with `-fullscreen -bigpicture -nogui`
PCSX2 should no longer shows the exit to desktop button.
Test both normal and no GUI mode.
gak

BPM: Fix CTD when exiting BPM in No GUI mode

---

pcsx2-qt/Debugger/Docking/DockManager.cpp

Previously the debugger would crash when receiving a breakpoint in its constructor immediately while it was being created since it would try to start the blinking animation even though the menu bar hadn't been created yet.
Fixes #12847.
Try to reproduce the steps in #12847.
No.

Debugger: Fix crash when breakpoint is hit before createMenuBar call

---

.github/workflows/cron_publish_flatpak.yml

Restores the check for the repository in the Flathub publish action
This check got removed when disabling a different non-functional version check
Without forks configuring their own flathub secrets, this action will fail anytime its run.
Cherry pick the commit onto a fork, and run the flatpak publish action on the related branch to see if the build/publish gets skipped.
Make sure it doesn’t break the action when its supposed to run.
No

CI: Restore repository check in Flathub publish action

---

bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/vulkan/convert.glsl
pcsx2/ShaderCacheVersion.h

GS/DX: Don't output color for datm/stencil date shaders.
RTV(Render target view) is not bound so no need to output anything, just clip/discard if needed.
Fixes dx11 api warning that pixel shader writes color output but no rtv is bound.
Note: We already do this for gl/vk/metal.
Fixes dx11 api warning:
`D3D11 WARNING: ID3D11DeviceContext::Draw: The Pixel Shader expects a Render Target View bound to slot 0, but none is bound. This is OK, as writes of an unbound Render Target View are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Render Target View here. [ EXECUTION WARNING #3146081: DEVICE_DRAW_RENDERTARGETVIEW_NOT_SET]`
Didn't see any differences on dx11 dump run, smoke tested dx11 and …

GS/DX: Don't output color for datm/stencil date shaders.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Attempt to improve native scaling detection and include direct from GS memory draws. Plus detect recursive upscales (Xenosaga lights, unfortunately also Naruto Ultimate Ninja 3 shadows, so they look lower resolution now, not too distracting, though).
This may or may not go in as it currently is, we might need to add an additional option (Very aggressive?) as to not hurt the few games that are affected by it.
Also note some games will now have lines left and top where Align to Native is enabled and will need moving to ATNwTO.
Some games will generate texture atlases or upload FMV frames direct and if it's scaled up it can make a mess of it, so this attempts to keep it in native resolution for these draws.
Test games with Native Scaling enabled, maybe try ones without by enabling native …

GS/HW: Improve Native Scaling detection + Include direct mem reads

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fixes the region area of a new source on a shuffle, if there is one.
Resize the valid area to the size of the draw if it is a clear which covers most of the valid area (within 1 page of height)
Okami (source fix) regressed from my new source on shuffle checks due to missing the extra information.
Prince of Persia depth (valid size change) was still making its target too big by just a few pixels and ruining the clear check, something I previously tried to fix and evidently missed some scenarios.
Test Prince of Persia Warrior Within and Okami (loading screens and maybe smoke test the game).
Smoke test random stuff, maybe 007 - From Russia with Love, Ace Combat 04 - Shattered Skies, Crash Bandicoot - The Wrath of Cortex (Underwater stages), as these come up in the GS dump run but nothing …

GS/HW: Fix region area on new source + valid on clear

---

pcsx2/DebugTools/DebugInterface.cpp

Remove the frame count check in DebugInterface::isAlive()
This prevented you from debugging the early bios boot code.
Idk, just make sure normal debugger work doesn't break.
no

Debugger: Allow debugging before first frame

---

bin/resources/GameIndex.yaml

Added memcardFilter entries to allow importing Nine Breaker and Nexus (NTSC-U) saves into Last Raven (NTSC-U).
The NTSC-J version of Last Raven has memcardFilter entries set, but not NTSC-U, and otherwise couldn't import saves from my Folder memory card.
Works with no obvious issues on Linux Flatpak PCSX2 v2.3.436. Last Raven detects and imports saves from Nine Breaker and Nexus successfully using a Folder memory card, and did not before.
No.

GameDB/Misc: Add memcardFilters to Armored Core: Last Raven NTSC-U SLUS-21338

---

bin/resources/GameIndex.yaml

Re adds tex in rt to fix broken textures on crystal surfaces. This previously made people bald which was bad.
Without:
With:
Broken games that can be fixed should be fixed.
Nop

GameDB: Xenosaga Episode III fixes

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS/DX11: Make sure no SRVs are bound using the same texture before binding it to a RTV.
Fixes api hazard warnings.
GS/DX11/GL: Check if primid texture exists instead if it's a primid draw.
Makes local testing easier to null out primid tex.
Also match naming between gl and dx11.
Follow up from https://github.com/PCSX2/pcsx2/pull/12600
Fixes hazard warnings on dx11.
Example:
```
[28236] D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets: Resource being set to OM RenderTarget slot 0 is still bound on input! [ STATE_SETTING WARNING #9: DEVICE_OMSETRENDERTARGETS_HAZARD]
[28236] D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets[AndUnorderedAccessViews]: Forcing PS shader resource slot 0 to NULL. [ STATE_SETTING WARNING #7: DEVICE_PSSETSHADERRESOURCES_HAZARD]
[28236] D3D11 WARNING: …
```

GS/DX11/GL: Fix more hazard warnings on dx11, tweak primid checks on dx11/gl.

---

pcsx2/ImGui/FullscreenUI.cpp

Adds missing logic to centre the disc/gear icon in the preview panel in the BPM games list.
Regression from #12875
Master on left, PR on right
Look at the preview panel in the BPM games list.
No

FSUI: Centre disc/exe icon in game list selected preview

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h

GS/DX11: Also check DrawMultiStretchRects copy for srv conflicts with rtv.
Also adjust the naming.
Follow up from https://github.com/PCSX2/pcsx2/pull/12884
Even less api warnings.
Test Hitman Blood Money.
No.

GS/DX11: Also check DrawMultiStretchRects copy for srv conflicts with rtv.

---

.github/workflows/linux_build_qt.yml

Links ffmpeg for the appimage to allow video recording by default.
Having this feature be broken for a lot of users to save 40MB of space doesn't really make sense so let's fix that.
Make sure the CI still passes and video recording works with the appimage.
No

CI/Linux: Link ffmpeg for the appimage

---

bin/resources/GameIndex.yaml

Fixes light going through buildings intensity and alignment of said light.
Fixes #12917 
Before:
After:
Make sure CI pass.

GameDB: The Golden Compass fixes

---

pcsx2/GS/GSClut.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSUtil.cpp
pcsx2/GS/GSUtil.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Put the psm_str function (which converts a psm code into a string representation) into the GSUtil struct.
This is for consistency since other similar functions are in the GSUtil namespacce.
Nothing to test. It builds and runs correctly.
No.

GS: Put psm_str in the GSUtil struct.

---

pcsx2/USB/usb-pad/usb-buzz.cpp
pcsx2/USB/usb-pad/usb-buzz.h

Throttle the Buzz data packets, which should should resolve the problem with ghost inputs
Closes #4990, closes #8393, closes #9898
Buzz

USB: Throttle the Buzz data packets

---

.github/workflows/scripts/windows/build-dependencies.bat
common/vsprops/LinkPCSX2Deps.props
common/vsprops/QtCompile.props
pcsx2/CMakeLists.txt

Bundle Qt & SDL symbols
Force Qt plugin symbols
The Windows deps script force enables Qt and SDL symbols, it seems reasonable to also bundle them in our symbols archive.
Qt plugins are now force enabled to align with the rest of Qt.
Download symbols and see if they get loaded when debugging the build.
Negative

Bundle Qt and SDL Windows Symbols

---

pcsx2/Resources/Info.plist.in

Ensures macOS treats it as a known file type, so it doesn't try to prevent users from adding it as a file extension
Side note, we could also add a custom icon for pnach files this way, but I don't feel like making icon artwork so I'm leaving it default.
Currently, when users try to rename text files to pnach files, macOS leaves the .txt extension and hides it instead of adding the new extension.
- Try to rename a .txt file to .pnach in Finder with after unzipping PR's PCSX2.  It should rename it without sneakily adding a hidden .txt
- Look at a .pnach file.  It should have a text-document-looking icon with PNACH over it, instead of a blank generic unknown file icon.
No

MacOS: Add pnach definition to Info.plist

---

bin/resources/icons/ra-icon.svg
pcsx2/ImGui/FullscreenUI.cpp

Before:
After:
- Added `DrawAchievementsLoginWindow()` function with custom styling matching the Fullscreen UI theme
- Implemented proper internationalization using FSUI translation macros
- Added state management for the login dialog (username, password, logging status)
- Styled the dialog with consistent spacing, colors, and visual elements
- Visual Consistency: Dialog now matches the Fullscreen styling and color scheme
- Better UX: Integrated seamlessly without breaking the Fullscreen experience
- Maintainability: Reduces dependency on Qt dialogs in Fullscreen mode
I did not use it for my code but it did help me with grammar and better helping understand why this should be added

FSUI: Add RetroAchievements login dialog

---

pcsx2-qt/CMakeLists.txt
pcsx2-qt/Debugger/Docking/DockTables.cpp
pcsx2-qt/Debugger/ModuleModel.cpp
pcsx2-qt/Debugger/ModuleModel.h
pcsx2-qt/Debugger/ModuleView.cpp
pcsx2-qt/Debugger/ModuleView.h
pcsx2-qt/Debugger/ModuleView.ui
pcsx2-qt/Debugger/ThreadModel.cpp
pcsx2-qt/Debugger/ThreadModel.h
pcsx2-qt/Debugger/ThreadView.cpp
pcsx2-qt/pcsx2-qt.vcxproj
pcsx2/DebugTools/BiosDebugData.cpp
pcsx2/DebugTools/BiosDebugData.h
pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DebugInterface.h
pcsx2/IopBios.cpp

(oops, text section end is broken in screenshot but fixed in pr)
Find and display the list of loaded modules by inspecting `loadcore`.
It's nice for debugging to be able to quickly figure out what code is running.
Just open the list on whatever game/thing you can think of.
I'm quite worried about the loadcore detection and list traversal breaking if there is some possible struct layout that I didn't account for, or on something weird that doesn't have loadcore at all.
No

Debugger: List loaded IOP modules.

---

3rdparty/soundtouch/README.html
3rdparty/soundtouch/soundtouch/STTypes.h
3rdparty/soundtouch/soundtouch/SoundTouch.h
3rdparty/soundtouch/source/SoundTouch/BPMDetect.cpp
3rdparty/soundtouch/source/SoundTouch/FIRFilter.cpp
3rdparty/soundtouch/source/SoundTouch/FIRFilter.h
3rdparty/soundtouch/source/SoundTouch/sse_optimized.cpp

Author also moved to https://codeberg.org/soundtouch/soundtouch
Minor update, also increases audio channels from 16 to 32.
Test soundtouch (specifically, SoundTouch is used in the AudioStretch or AudioResampler components, which are responsible for time-stretching audio frames to maintain sync with the emulated CPU and video section or also known as the SPU2).
No.

3rdparty: Soundtouch bump to v2.4.0

---

pcsx2-qt/Debugger/Docking/DockManager.cpp
pcsx2-qt/Debugger/Docking/DockMenuBar.cpp
pcsx2-qt/Debugger/Docking/DockViews.cpp
pcsx2-qt/Debugger/Docking/LayoutEditorDialog.cpp
pcsx2-qt/Debugger/SymbolTree/NewSymbolDialogs.cpp
pcsx2-qt/Debugger/SymbolTree/TypeString.cpp

Make some more strings translatable, and add a type name to the type string error messages.
Some of these cases are obvious, for some of them I thought it wouldn't be required when originally writing the code, but I didn't consider some cases e.g. right to left languages, in which case I think translating these could still be useful.
N/A
No.

Debugger: Make some more strings translatable

---

pcsx2-qt/Debugger/Memory/MemoryView.cpp
pcsx2-qt/Debugger/Memory/MemoryView.h

Adds a Follow Address menu option to the memory view.
Parity with the wxWidgets debugger, fixes one of the issues mentioned in #12691.
Make sure the new menu option works.
No.

Debugger: Add Follow Address option in memory view

---

pcsx2/SIO/Memcard/MemoryCardFile.cpp

- Renamed 'IsMemoryCardFolder' to 'FileMcd_IsFolder' for better consistency and clarity on MemoryCardFile.cpp.
- Consistency and clarity
- Not needed

Refactor: Rename helper function for consistency

---

pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp

Corrected two defaults that did not match the actual default values in the code. A few other typos and minor wording improvements in the settings help text.
Help text is more correct.
N/A (purely cosmetic change).
No.

Qt: Fix minor typos in settings help text

---

pcsx2-qt/Debugger/Breakpoints/BreakpointView.cpp
pcsx2-qt/Debugger/Memory/SavedAddressesView.cpp
pcsx2-qt/Debugger/ModuleView.cpp
pcsx2-qt/Debugger/StackView.cpp
pcsx2-qt/Debugger/ThreadView.cpp

Unlocks the layout of the tables in the debugger.
to make the debugger view even more comfortable by adjusting the rows
open the debugger, go to e.g. stack view and try to move the columns
no

Debugger/Qt: Unlock debugger table view layout

---

pcsx2/GS/GS.cpp
pcsx2/SIO/Pad/Pad.cpp

(for you @Mrlinkwii) 
Adds a new hotkey `CycleTVShader` that allows users to cycle through all 8 TV shader options during gameplay.
This was a user requested feature to have quick access to TV shader settings without needing to navigate through menus during gameplay
- Make custom keybind
- Verify shader cycles through all 8 options
- Check that OSD message appears showing current shader name
- Verify hotkey setting appears in Settings -> Controllers -> Hotkeys -> Graphics section
- Confirm custom key bindings can be set and work correctly
- Test in both Qt interface and FullscreenUI
nuh uh

GS: Add hotkey for cycling TV shaders

---

pcsx2-qt/Debugger/Docking/DockLayout.cpp
pcsx2-qt/Debugger/Docking/DockTables.cpp
pcsx2-qt/Debugger/Docking/DockTables.h

Use an integer index to refer to dock groups instead of an enum.
This was a small oversight when designing the docking system, each default dock layout previously had to have the same dock groups.
Make sure the debugger dock layouts still work as expected.
No.

Debugger: Allow default layouts to be defined with different groups

---

pcsx2/Hotkeys.cpp
pcsx2/SIO/Memcard/MemoryCardFile.cpp
pcsx2/SIO/Memcard/MemoryCardFile.h

- Creates a core Swap Memory Card function.
- Add field to set a custom hotkey under Controllers>Hotkeys>to quickly swap memory cards.
- Allow users to change memory cards on demand. This is really useful on shared machines, specially with kids around (Forget kids accidentally overwriting your save games with over 100 hours of gameplay!).
- By creating a memory card swap function in the core, we can now use it anywhere
- Make sure to create a backup of your memory card file/folder before testing, although there shouldn't be any issues what so ever.
- Having save files on the memory card will help testing as swaps will be more evident.
- Assign hotkey under Controllers>Hotkeys>Swap Memory Cards and test while on BIOS Browser or in game.
- Try pressing the hotkey while on different stages …

Core/Qt: Add hotkey support for swapping memory card

---

pcsx2-qt/Settings/AchievementSettingsWidget.cpp
pcsx2-qt/Settings/AchievementSettingsWidget.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Achievements.cpp
pcsx2/Config.h
pcsx2/GSDumpReplayer.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiFullscreen.h
pcsx2/ImGui/ImGuiManager.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/ImGui/ImGuiOverlays.h
pcsx2/Pcsx2Config.cpp

Add 9 positioning controls for all overlay elements:
- Achievement overlays: Challenge indicators, progress bars, and leaderboard trackers now support 9-position alignment grid (TopLeft through BottomRight)
- Achievement notifications: Unlock popup messages can be positioned anywhere on screen
- OSD elements: Messages and performance statistics support full positioning options
- UI integration: Added controls to both Qt settings and FullscreenUI
Fixes #12361 where a user asked better control over achievement overlay positioning. Previously, overlays were fixed in the left or right side of the screen at the top, which would possibly go over some UI elements in game
This change allows users to:
- Position achievement overlays away from in-game UI elements
- Customize notification …

OSD/Achievements: Add 9-position alignment options for Achievement notifications/popups, and OSD

---

pcsx2/SIO/Memcard/MemoryCardFile.cpp

Remove a broken assertion statement in FileMcd_Swap.
It broke the build.
This new hotkey seems to crash PCSX2 when I press it, someone more experienced with the memory card stuff should probably look into that (update: actually it looks like it might be to do with STL iterators in the InputManager, so maybe it only happens on Linux). This is just a quick fix for now.
Try compiling a debug build.
No.

Memcard: Remove a buggy assertion

---

pcsx2/PINE.cpp

Give the PINE server thread a name.
Previously it showed up as "CPU Thread" in gdb, was kinda confusing.
- Open PCSX2 under gdb.
- Make sure PINE is enabled.
- Use the command: `info threads`
ⓃⓄ

PINE: Give the server thread a name

---

pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes an issue with temporarily offset Z and a clear misdetection.
Offset Z in Time Crisis 3 was detecting a channel shuffle (which was technically correct) and not copying the Z correctly to the new position, it now properly detects this situation.
Tales of Destiny does 2 triangles across the screen to do a cool effect at the end of of a battle, but this was being detected as a clear with quad. The code now checks for at least one shared vertex in this case.
From here on the GT3 demo (possibly the full game) may require high blending if it doesn't already to stop the left/right buttons in the car select from flickering. This was an issue before RT in RT but due to the false clear, it kind of "fixed" it.
Test Tales of Destiny and Time Crisis 3 (visible in menu demos).  Can also check …

GS/HW: Fix temp z and clear detection regression

---

bin/resources/shaders/opengl/tfx_vgs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/ShaderCacheVersion.h

Scales vertex base to avoid the need for GL_ARB_shader_draw_parameters on OGL and VK_KHR_shader_draw_parameters on Vulkan
Some older Nvidia GPUs break when you use it
Test OGL and Vk
Test OGL and Vk on Kepler and Maxwell GPUs (I've tested on a 750M and it works now, someone should test Maxwell)
No

GS: Avoid shader_draw_parameters

---

pcsx2-qt/Debugger/Breakpoints/BreakpointModel.cpp

Removed the Breakpoint Enabled/Disabled Text
Fixes #12049 , also not needed as the [X] is sufficient
Load up a game, and set a breakpoint in the debugger
No

Qt/Debugger: Remove text display for breakpoint enabled state

---

pcsx2-qt/Settings/AchievementSettingsWidget.ui
pcsx2-qt/Settings/FolderSettingsWidget.cpp
pcsx2-qt/Settings/FolderSettingsWidget.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2-qt/Settings/SettingsWindow.ui

This PR moves the screenshot section from the Display tab over to the Recording tab, then subsequently rename that tab to Capture.
A small followup to #12979
Better organizations.
See if the screenshot sections shows up correctly and make sure the option still works.
Nada

Qt: Move screenshot section to Recording tab

---

pcsx2-qt/QtHost.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.ui

Fixes #12857
Adds a new setting in Qt Interface Settings to automatically start PCSX2 in Big Picture Mode (FullscreenUI) instead of the Qt UI.
- New "Start Big Picture" checkbox in Interface Settings -> Game Display section
- Setting is stored as "StartBigPictureMode" in the "UI" configuration section
- Changed QtHost.cpp to check both command line (-bigpicture) and the new setting
Users who primarily use PCSX2 in BPM had to manually switch to it every time they launched the application, or remember to use the `-bigpicture` cli option . This was inconvenient for users who prefer the BPM interface as their default experience.
nuh uh

Qt: Add option to start in Big Picture Mode from settings.

---

bin/resources/GameIndex.yaml

Adds Blue Tongue CRC to El Tigre to fix broken graphics.
Fixes #13003 
No.

GameDB: El Tigre fixes

---

.github/workflows/macos_build.yml

Updates the macOS runners to use macOS 15 and Xcode 16.4. 
Fixes warnings and probably something else I've forgotten at this point.
Make sure nothing breaks on the Mac builds.
No

CI: Update macOS runners to 15

---

pcsx2-qt/Debugger/ThreadView.cpp

Fix copying out of the thread view by looking up the real index of the selected line through the sorted proxy model.
Fixes #13029 
Copy items out of the thread view and make sure they match the selection.
No

Debugger: Fix copying out of sorted thread view

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

Adds CRC for Sand Grain Games games.
We have no way to do this effect directly without having 50-100 readbacks per frame, which is very very slow, this emulates the effect they're trying to achieve (G->A shuffle with palette)
Test Cabela's African Safari, The History Channel - Battle for the Pacific, SeaWorld Adventure Parks - Shamu's Deep Sea Adventure
If you have other Cabela games, it would be interesting to know if any of them have a lot of readbacks and also require this, I don't have them to check, but I don't suspect they all do and don't want to blindly add it.  Keep in mind it may only be the pause screen.
Edit: Added the following games:
Cabela's Big Game Hunter 2007
Cabela's Legendary Adventures
Cabela's Monster Bass
Cabela's Trophy Bucks
No.
Expecting performance to be …

GS/HW: Add CRC for Sand Grain Games palette shuffle effect.

---

pcsx2-qt/QtHost.cpp
pcsx2/ImGui/ImGuiOverlays.cpp

Fixes the overlay showing VPS when there was no FPS detection taking place.
Previously when there was no way to detect the internal FPS it would show the stat for VPS while the host window status bar would show 0. This has been changed to show N/A on both when no internal FPS method can be used.
Make sure FPS detection works correctly in a variety of situations.
I used Kam does that count?

ImGuiOverlays: Internal FPS stat regression fix

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSVertexTrace.cpp
pcsx2/GS/Renderers/Common/GSVertexTrace.h
pcsx2/GS/Renderers/Common/GSVertexTraceFMM.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Remove the handling of provoking first vertex in early pipeline GSState and GSVertexTrace (and other helper classes) and move it later pipeline GSRendererHW. This is mainly for DX11-12, Vulkan (when it doesn't support fast vertex provoking), and Metal. It should not affect OGL.
There is unnecessary code complexity added early in the pipeline in GSState/GSVertexTrace (e.g., keeping track of when vertices are swapped in primitives and when not). Since provoking first vertex is a graphics API quirk, it is better to handle it in lower level code in GSRendererHW.
Also, the way provoking first vertex was implemented gave incorrect results in some cases since it swapped vertices in the draw. This could cause incorrect drawing of line primitives since lines may (and are usually) not drawn the …

GS/HW: Remove handling of provoking first vertex in early pipeline.

---

bin/resources/GameIndex.yaml

Fixes graphical corruption and overall alignment issues. Fixes #13044 
Before:
After:
N/A
No

GameDB: Kamen Rider Kabuto fixes

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml
.github/ISSUE_TEMPLATE/emu_bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Added `type` key to issue templates.
Thought this can improve QoL for searching issues.
Not sure, can anyone suggest?
No.

GitHub: Add types to issue templates

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml
.github/ISSUE_TEMPLATE/emu_bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Reverts PCSX2/pcsx2#13042
Cannot create issues anymore, so reverting

Revert "GitHub: Add types to issue templates"

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

MTL: Add missing shader case for RGB5A1_TO_8I.
GL: Comment out vendor Nvidia.
Fixes warnings.
Bugfixes.
Smoke test Harry Potter on Metal.
No.

GS/GL/MTL: Misc fixes.

---

pcsx2-qt/Debugger/Memory/MemorySearchView.cpp

To prevent crashes.
I like to accelerate my debugger searches by spamming the filter button. However, doing so while PCSX2 was actively searching crashed PCSX2. This PR fixes said issue, by preventing filter searches while filter-searching is active.
Filter search/search and ensure the button is activated, disabled, and re-activated correctly.
No.

Debugger: Disable filter search button while filter search is active

---

bin/resources/shaders/dx11/shadeboost.fx
bin/resources/shaders/opengl/shadeboost.glsl
bin/resources/shaders/vulkan/shadeboost.glsl
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Metal/convert.metal
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/ShaderCacheVersion.h

- Add a Gamma parameter to ShadeBoost shaders (OpenGL & Vulkan).
- Expose a Gamma slider in the Qt Graphics Settings and the fullscreen in-game menu.
Gamma control lets users adjust mid-tones independently of brightness/contrast/saturation. Fulfills feature request #12515.
- Open PCSX2.
- Emulate a game.
- Open graphics settings.
- Go to Postprocessing.
- Adjust Gamma as you see fit.

GS: Add gamma control to ShadeBoost

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/Config.h

Qt: Fix default post processing values.
Brightness, contrast, gamma, saturation.
Bugfix.
Test post processing using default settings, make sure to reset.
No.

Qt: Fix default post processing values.

---

bin/resources/GameIndex.yaml

Changed title for SLES-54435 to "Casper and the Ghostly Trio" in GameIndex.yaml.
Wrong title bad.
Fixes https://github.com/PCSX2/pcsx2/issues/13070
Re-scan game library for title to update.
No.

GameDB: Fix #13070 wrong title for SLES-54435

---

pcsx2/GS/GSState.cpp

Minor fix. Use std::array instead of std::vector for fixed size array.
Don't heap allocate when its not needed.
Changes should be (transparently) equivalent so testing is not required.
Yes

GS: Use std::array for fixed size array.

---

.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json

Upgrade the KDE runtime to 6.9, which bumps Qt to version 6.9.
PCSX2 supports 6.9 since https://github.com/PCSX2/pcsx2/pull/12476.
being up-to-date is good.
Run the flatpak.
No

CI/Flatpak: Upgrade runtime to 6.9

---

pcsx2/Config.h
pcsx2/Gif_Unit.h

Adds a compile-time define that is forced to `false` on non-x86 builds or is equal to the vu1 rec toggle on x86 builds.
Uses that define where the GIF was previously using `Recompiler.EnableVU1` (which can be true on ARM, despite there being no VU1 recompiler)
This caused chaos when you would try an ARM PCSX2 with games / non-trivial homebrew
Try a game on an ARM PCSX2 build with the VU1 recompiler turned on in the settings.
No

GS: Properly check for a VU1 recompiler.

---

pcsx2/IopBios.cpp

Send the correct remaining buffer size to snprintf
Less buffer overflows
Run Burnout 3 on a fortified build of PCSX2 with iop logging enabled and check if it crashes with a buffer overflow error
No

iop: Fix wrong limit given to snprintf

---

pcsx2/USB/usb-msd/usb-msd.cpp

* Changes the current OSD message for a failure to open a USB mass storage device from `usb-msd: Could not open image file '[path]'` to `USB mass storage: Could not open image file '[path]'`
* Adds a separate condition for an empty path: `USB mass storage: No image path specified`
* `usb-msd` is not legible to most users. I had to ask somebody what it meant because I didn't realize I had the option enabled.
* Previously, the empty path message was `usb-msd: Could not open image file ''`.
* This looks confusing to the user, especially one who might've selected the MSD by accident.
* The current message implies it's tried and failed to open a file when, in reality, it has nothing to try.
* Try opening a game with an empty path on both MSD device types.
* Try opening a game with a garbage …

usb-msd: separate message for empty image path

---

pcsx2-qt/Settings/AchievementSettingsWidget.cpp
pcsx2-qt/Settings/AchievementSettingsWidget.ui
pcsx2/Achievements.cpp
pcsx2/Config.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp

Adds a separate toggle for in-game leaderboard overlays, as suggested in #12676.
Being able to separately use achievement and leaderboard overlays, so that one can keep only the information they care about on the screen.
Toggling both settings on and off and checking whether they correctly affect the overlays.
No.

Achievements: Add in-game leaderboard overlay toggle

---

bin/resources/GameIndex.yaml

Added preloadFrameData to the gamedb for every version of Final Fantasy X as well as removing the obsolete SoftwareRendererFMVHack setting.
Fixes an issue where FMVs flicker black whenever subtitles appear on screen.
Fixes https://github.com/PCSX2/pcsx2/issues/10887
no

GameDB: Final Fantasy X FMV Fix

---

bin/resources/GameIndex.yaml

Add a memcard filter to the following games.
- Mobile Suit Gundam - Meguriai Sora [Limited Edition]
- Mobile Suit Gundam Ver.1.5 [Limited Edition]
Couldn't load savedata due to a different game ID.
Absorbs the difference between the title and save data game IDs, which is common in limited editions.
The following tests were performed on v2.5.121.
1. Save.
2. Restart PCSX2 and launch the game.
3. Load.
No

GameDB: Add memcard filters for Gundam series (Limited Edition)

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

GS/HW: Partially remove GSC_UrbanReign that skips draws.
Fixes lightning issues, tex in rt properly fixes the black rain/lightning.
Fixes https://github.com/PCSX2/pcsx2/issues/13149
Test the linked issue dump.
The other crc might also be useless but can't confirm, RCLAMP.MAXU value seems to be 639 before being clamped.
No.

GS/HW: Partially remove GSC_UrbanReign that skips draws.

---

bin/resources/GameIndex.yaml

Fixes bloom alignment and duplication by adding ATNWTO and NS Normal.
Before:
After:
Bloom misaligned is gross.
Watch CI.
No

GameDB: Meet the Robinsons fixes

---

bin/resources/GameIndex.yaml

Fixes black garbage and improves brightness by swapping ATN for ATNWTO and recommending the use of Medium blending.
Before:
After:
CI needs watching it's suspicious,
No

GameDB: Onimusha Dawn of Dreams fixes

---

pcsx2/DebugTools/SymbolImporter.cpp

Honour the state of the "Automatically Select Symbols To Clear" checkbox.
This is clearly the right solution.
- Launch a game with symbols.
- Open the debugger.
- Click the "Analyze" button in the toolbar.
- Uncheck the "Automatically Select Symbols To Clear" checkbox.
- Uncheck all the symbol source checkboxes below.
- Recheck the "Automatically Select Symbols To Clear" checkbox.
- Click the "Analyze" button at the bottom of the dialog.
- The symbols shown in the Functions view should not all be duplicated twice.
No.

Debugger: Fix Automatically Select Symbols To Clear checkbox

---

pcsx2/Memory.cpp

- Sets `HostMemoryMap::VUmem` to use `VUmemOffset` instead of `VUmemSize`
- Corrected the offsets used for dumping the VTLB Virtual Map and VTLB Address Map in `SysMemory::DumpMemoryMap`
Accurate data is dumped and a valid address will be exported for access to VU Memory
If built without the change to the VUMem offset the export is effectively useless as its pointing to the wrong region of memory
The image below shows myself trying to access VUMemory unsucessfully as the pointer is the wrong location. If you look in the PCSX2 debug log however the correct address is dumped
no.

Fix vumem export and offsets used in SysMemory::DumpMemoryMap

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

Detect when a game (maybe just Colin McRae Rally 2005) is doing a texture shuffle and (a) flipping pixels locations horizontally in columns and (b) correcting the pixels locations by flipping pixels horizontally again. Ignore both flips so that they cancel out.
The flipping coordinates where throwing off the heuristics to detemine which channels to shuffle. By ignoring them we obtain correct heuristics. Aims to address some of the issues here: https://github.com/PCSX2/pcsx2/issues/1546. In a dump run only Colin McRae Rally 2005 seems to be affected by the PR.
Master:
PR:
[Colin McRae Rally 2005_SLES-52636_20230403172639.gs.xz.zip](https://github.com/user-attachments/files/21820025/Colin.McRae.Rally.2005_SLES-52636_20230403172639.gs.xz.zip)
So far tested on dumps run with OpenGL and about …

GS/HW: Handle texture shuffle with pixel reversals.

---

pcsx2/Hotkeys.cpp

The FileMcd_Swap function is now kicked off to run at a later time instead of while the input manager is inside its event processing loop.
FileMcd_Swap triggers the following calls: VMManager::ApplySettings -> VMManager::LoadSettings -> VMManager::LoadInputBindings -> InputManager::ReloadBindings. This causes iterator invalidation for s_binding_map so when FileMcd_Swap returns and InputManager::ProcessEvent tries to start walking through the map again it may crash.
This bug may only be visible on certain platforms due to the implementation of std::unordered_mutlimap being different. I'm testing this on Linux.
I found this a while ago but forgot to open an issue.
Load both memory card slots, bind a key for swapping memory cards, press that key while a game is running. Test on Linux.
No.

Hotkeys: Fix crash when swapping memory cards

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
.github/workflows/scripts/windows/build-dependencies-arm64.bat
.github/workflows/scripts/windows/build-dependencies.bat

Updates our Qt from 6.91 to 6.9.2 on Windows and Linux.
Bug fixes and security fixes wahoo.
Make sure nothing goes catastrophically wrong with the interface.
No

Deps: Update Windows and Linux to Qt 6.9.2

---

bin/resources/shaders/dx11/tfx.fx
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/ShaderCacheVersion.h

GS/DX: Fully implement tex is fb on dx11, extend partially on dx12.
Always use tex is fb for dx11.
Partial support for dx12 if prims don't overlap.
Previously it didn't work on dx because we used input.t which is interpolated, instead of absolute cords when fb sampling.
Accuracy, bugfixes, parity with VK/GL.
Some games will be faster, others slower on dx11 depending on overlap, dx12 games will be faster affected.
This finishes sw blending parity with gl/vk 100%, next up optimizations.
Fixes Haunting Ground shadows on dx11.
Fixes Jak games shadows when not using autoflush on dx11.
Fixes Star Ocean shadows when upscaling on dx11.
Dump run didn't show anything broken, test various games on dx11 and 12.
No.

GS/DX: Fully implement tex is fb on dx11, extend partially on dx12.

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/DX11: Post dx11 multidraw fb copy cleanup.
Don't clear stencil for stencil date.
We don't want to do this unless we always sample with stencil date like vk/gl.
Only swap primid date with barrier date if there is overlap, stencil date might send the wrong alpha on a previous draw which could be wrong when we use the alpha to sample from.
Bugfixes, cleanup.
Test games that had issues with primid + sw blending like GT4 car reflections on higher blends, test other stuff.

GS/DX11: Post dx11 multidraw fb copy cleanup.

---

pcsx2-qt/Debugger/SymbolTree/SymbolTreeDelegates.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeDelegates.h
pcsx2-qt/Debugger/SymbolTree/SymbolTreeModel.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeModel.h
pcsx2-qt/Debugger/SymbolTree/SymbolTreeNode.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeNode.h
pcsx2-qt/Debugger/SymbolTree/SymbolTreeViews.cpp
pcsx2-qt/Debugger/SymbolTree/SymbolTreeViews.h

Adds context menu options to the relevant symbol trees the change the base of integers displayed, and to show leading zeroes.
Closes #13059.
Open the debugger, create some global variables with integer types (char, unsigned char, etc) and verify the options all work correctly.
No.

Debugger: Add Integer Base and Show Leading Zeroes options to the symbol trees

---

pcsx2/CDVD/InputIsoFile.cpp

Fixes a failed attempt at string interpolation in an error message in InputIsoFile.cpp.
Saw this error message Jordan got where what's clearly supposed to be two unsigned ints are printed as the string literal `%u`. InputIsoFile.cpp has two versions directly beside each other using the `ERROR_LOG` function: one uses `{}` for interpolation, while the other ostensibly incorrectly uses `%u`.
If you're somehow able to reproduce this error organically, see how it prints to the log.
I %d%i%d n%ot %u%s%e a%i %f%or t%hi%s %pr.

CDVD: Fix block index past EoF error message

---

bin/resources/GameIndex.yaml

Fixes the grid like pattern over the screen.
Fixes #13031 
Before:
After:
No

GameDB: Deadly Strike fixes

---

pcsx2-qt/Settings/HotkeySettingsWidget.cpp
pcsx2/Hotkeys.cpp

Splits the overloaded `System` hotkey header into `System`, `Navigation`, `Speed`, and `Audio`. Within those headers, sorts the hotkeys so that related ones are closer together (e.g. `Toggle Pause` is now adjacent to `Frame Advance`, as they're used in conjunction). In order, the headers are:
* Navigation (menus, VM shutdown, etc.; anything that navigates you through the UI)
* Speed (anything that changes the speed of the VM)
* System (due to `Graphics` having a hold on screenshot/video capture, the best solution was to keep `System` and keep memcard swap and input recording mode in it)
* Save States (untouched by this PR)
* Audio (intuitively coupled with graphics)
* Graphics (untouched by this PR)
Currently, the `System` section is a 19-item landfill of items that, yes, are related to …

Hotkeys: Better organize hotkeys page

---

bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/dx11/shadeboost.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/vulkan/convert.glsl

GS/shaders: Fix false positive warning for pow being negative. 
Replaced pow with exp2 log2.
Fixes warning:
warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
GS/shaders: Fix types mismatch for ps_convert_rgb5a1_8i shader.
Fixes shader compile errors and warnings on mesa, also synch vk and dx shaders for consistency.
Fixes https://github.com/PCSX2/pcsx2/issues/13230 , fixes shader compile errors and warnings on gl and dx.
Test harry potter games on GL on mesa linux or mesa3d software renderer for windows and run a dump using gl.
Test Post processing brightness, contrast, gamma, saturation if it still works on all renderers.
Test dx11, dx12, gl, vk and make sure they still work.
No.

GS/shaders: Fix shader compile errors and warnings.

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.ui

Adds a 'Hotkeys' action to the Qt toolbar to the right of the 'Controllers' action.
#13243 prompted a discussion where we realized that, although this is 100% clear when using the menu bar, a user primarily using the toolbar would have no reasonable idea how to find hotkeys:
* Scan the toolbar for `Hotkeys`. Nothing.
* See a `Settings` button; check that; nothing.
* From there, while there are very good reasons (both technical for us and logistical for the end user) to keep `Hotkeys` within the controllers settings, almost no end user would think to click the `Controllers` button in the toolbar to get to the hotkeys.
With this button, said user can readily find hotkeys, and the toolbar still has abundant empty space for this on a 16:9 display.
Make sure the button appears and works, and …

Toolbar: Add 'Hotkeys' action

---

pcsx2-qt/MainWindow.ui
pcsx2-qt/Settings/GraphicsSettingsHeader.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/GS/Renderers/DX11/D3D.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/VMManager.cpp

Changes Renderer to Graphics API and Software to Software Renderer. Also adds warnings for Force 32 bit Dithering dithering being disabled and Integer Scaling being enabled.
We already call Renderer API in description text so this makes far more sense to more people what it actually does and is more consistent with existing texts. Warnings are just nice for users who don't under force 32 bit dithering can blow up games.
Test new warnings and names to make sure they are correct.
No

Qt/FSUI: Various changes

---

pcsx2/GS/GSVector4i.h
pcsx2/GS/GSVector4i_arm64.h
pcsx2/GS/GSVector8i.h
pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.arm64.cpp

Avoids using the mulhrsw instruction, since it rounds instead of truncating
Fixes #5898
Helps #11477
Accurate fog
Test the things in the referenced issues
Running copilot helped remind me that we had an ARM implementation that needed fixing as well

GS:SW: Use accurate fog equation

---

pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS: Backport and unify CopyRect optimizations to avoid redundant copies.
Moved the shared code in GSDevice where it can be shared between renderers.
Backported optimizations to DX11/GL/Metal:
Source is cleared, destination is a render target, and it's a full copy we can clear it instead.
Source is cleared, destination is a render target, destination is cleared, if it's the same colour and rect, we can just avoid this entirely.
Optimizations.
The two dumps will benefit the most since those trigger the bigger optimizations, test various games see if anything broke, test dx11/gl on max blend for any potential improvements.
Breath of Fire Dragon Quarter,
MTV Music.
[Dumps.zip](https://github.com/user-attachments/files/22367211/Dumps.zip)
Might be worth adding some logs to find more games. …

GS: Backport and unify CopyRect optimizations to avoid redundant copies.

---

pcsx2/SIO/Pad/PadBase.h
pcsx2/SIO/Pad/PadDualshock2.cpp
pcsx2/SIO/Pad/PadDualshock2.h
pcsx2/SIO/Pad/PadGuitar.cpp
pcsx2/SIO/Pad/PadGuitar.h
pcsx2/SIO/Pad/PadJogcon.cpp
pcsx2/SIO/Pad/PadJogcon.h
pcsx2/SIO/Pad/PadNegcon.cpp
pcsx2/SIO/Pad/PadNegcon.h
pcsx2/SIO/Pad/PadNotConnected.cpp
pcsx2/SIO/Pad/PadNotConnected.h
pcsx2/SIO/Pad/PadPopn.cpp
pcsx2/SIO/Pad/PadPopn.h

Removes duplicate declarations of analogLight and analogLocked from all the subclasses of PadBase, instead just make one protected declaration for each in PadBase.
Adds const public methods to expose these to the rest of the program.
A bit of sanitation and exposing these attributes for some work Kam is doing.
Try out games which do allow you to toggle the analog light, verify they still do. Run some games which use analog sticks, verify they still work as expected.
No, I would rather step on Legos.

Pad: De-duplicate analog light/lock attributes, add public getters

---

bin/resources/GameIndex.yaml

SLES-55675 has Greek (and Italian) in menu, not German (and Italian).
SLES-55674 has German (and French).
https://github.com/PCSX2/pcsx2_patches/pull/616
http://redump.org/disc/51722/

Correct lingual-code

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS/HW: Abort copy if rect is empty as a precaution.
Bugfixes, we shouldn't initiate a copy if rect is empty as that will cause validation errors/crashes.
Also provides a small speed bump as we now skip the affected copy.
Note: This doesn't solve the origin of the issue that needs to be tackled, but this also needs to be put in place for any future potential copies having empty rectangles.
Affected games by this pr: Onimusha - Dawn of Dreams.
Games that have an empty draw area rect but not doing a copy for future reference: SengokuBasara, The Simpsons, TOCArd2, Urban Reign.
Smoke test anything else, see if validation errors are fixed on dx11/12 (dx affected because blending is done with copies, for vulkan/gl you have to disable texture barriers to test).
Test some other stuff as all hw …

GS/HW: Abort copy if rect is empty.

---

pcsx2/GS/GSDrawingEnvironment.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSUtil.cpp
pcsx2/GS/GSUtil.h

Forgot to add the fog coefficient in https://github.com/PCSX2/pcsx2/pull/13088 so added it here.
Made the vertex list a bit more readable by adding spacing between every 2, 3 line depending on the primitive.
Some small formatting improvements.
Make debugging a better experience. Make the fog pipeline better : P
Dumping info in Settings>Debug>GS (after enabling Dump GS Draws). "00003_vertex.txt" and such should look like this:
```
flush_reason: "CLUT CHANGE (RELOAD REQ)"
vertex: # TRIANGLE
- {X:   128.9375, Y:   -90.8750, Z:     375437, U:             128, V:           133.5, R:  49, G:  49, B:  49, A: 128, F: 255} # 0
- {X:   143.6875, Y:  -123.3750, Z:     387402, U:             128, V:           121.5, R:  51, G:  51, B:  51, A: 128, F: 255} # 1
- {X:   252.0000, Y:     8.8125, Z: …
```

GS: Small additions to vertex dumping

---

pcsx2/Patch.cpp

If any dynamic patches are enabled, clear the R5900 recompiled code cache after updating patches.
This makes it so the dynamic patches are applied immediately instead of when the patched block is next recompiled.
- Disable compatibility patches (Advanced page).
- Load Ratchet & Clank 2 (PAL).
- Throw out a few (upgraded) megaturrets, observe them bugging out.
- Enable compatibility patches.
- After this PR, the change should be immediately visible.
No.

Patch: Clear R5900 recompiler cache after updating dynamic patches

---

pcsx2/GameList.cpp

Swaps the priority for finding cover art.
Previously:
* Serial
* File title
* GameDB title
* GameDB English title
Now:
* File title
* Serial
* GameDB title
* GameDB English title
Fixes very minor oversight introduced in #6214 with the introduction of serial image names.
For modded games that retain the serial, it was not possible to simultaneously (1) have the base game and the modded game, (2) have separate cover art for the modded version, *while* (3) retaining the base, unmodded cover name as `serial.extension` which is the most common default name with the downloader.
If, for example, you have an existing base game whose cover named `serial.extension` was imported through the cover downloader and then have a separate modded version of the game (same serial), you have to simultaneously …

GameList: Prioritize file title over serial for covers

---

pcsx2-qt/Debugger/DebuggerView.cpp
pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2-qt/Debugger/DebuggerWindow.h

Fix the logic for setting font sizes so that the font size stored in the config file is no longer relative to the system font size. The default font size will probably also appear a bit smaller now, depending on your system.
The logic I had before for this was confused: It was calculating a font size relative to the system font size for the overall window but was using an absolute one for the individual views. 
This meant that if you set a system font size wildly different to the default, the text in the window would scale but not the text in the views.
I think a slightly smaller default font size makes sense anyway to take into account monitors with a lower pixel density.
Try with all sorts of different system font sizes and debugger font sizes (modifiable from the View menu). After …

Debugger: Improve logic for applying custom font sizes

---

pcsx2-qt/Debugger/DisassemblyView.cpp
pcsx2-qt/Debugger/DisassemblyView.h

In the debugger's disassembly view, added a new "Paste Instruction Text" item in the context menu. This allows a user to paste one or more lines of assembly instruction text from their clipboard into the disassembly view. The instructions are pasted starting at the currently selected disassembled instruction. 
The assembly instructions must be split by new line characters. When using the existing "Copy Instruction Text" item in the context menu, the instructions are split by new line characters when copied into the clipboard. 
Assembly instructions are validated before they are pasted. This means that if several instructions are attempted to be pasted from the clipboard and one of the instructions is invalid, no instructions will actually be pasted. The error presented to the user in this …

Debugger: Paste assembly instruction text

---

pcsx2-qt/MainWindow.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/VMManager.cpp

Fixes #13273  
- Fully block save state loading, frame advance, and cheats when Hardcore Mode is active  
- Disable Load State UI buttons while in Hardcore Mode (with an OSD message if bypassed)  
- Standardize OSD warnings for most Hardcore restrictions I could see in VMManager.
Totally up to suggestions with all of this just wanted to try to prevent any issues from happening again. And if you would like me not to remove asking the user if they want to turn off Hardcore let me know (Did this just in case somehow they were able to cheat the UI)
This PR enforces stricter RetroAchievements Hardcore compliance by preventing restricted actions both in the UI and at the core level. It also improves consistency in how users are notified through OSD messages.
Previously, users were prompted to …

Achievements: Harden RetroAchievements Hardcore Compliance

---

bin/resources/shaders/dx11/tfx.fx
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/ShaderCacheVersion.h

GS/DX12: Backport depth test and sampling from dx11.
Unlike in dx11 where we create a separate dsv as read only we can transition the current dsv as read only which is cleaner.
GS/DX12/VK: Fix CopyRect partial clear regression.
Partial clears texture type should be either render target or depth stencil.
Oversight, I thought I did this but it looks like I only did it for the common process clears.
Fixes games crashing on dx12/vk with texture barriers disabled on some games.
GS/HW: Remove rebinding read only dsv after framebuffer optimizations
on dx11.
The condition would never be triggered so useless.
Clean up SendHWDraw across renderers.
Recycle tex for rt copy if colclip tex fails.
Set flags for colclip CreateRenderTarget clear to false on dx11, consistent across renderers.
GS/DX11: Add …

GS/HW: Backport depth test and sampling from dx11 to dx12, crash/bug fixes and some cleanup.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Make sure we use date barrier on sw fbmask instead of primid date.
Edge case when we have sw fbmask but no sw blending.
Bugfix and optimization.
Only RE Outbreak is affected but we already optimize that game with a gamefix patch.
Will save a couple of draw calls/render passes.
No.

GS/HW: Make sure we use date barrier on sw fbmask instead of primid date.

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

GS/TC: Optimize block offset calculations in ComputeSurfaceOffset.
Same deal as before, swap the fast linear loops to be second since they will be faster.
GS/TC: Check for y offset when calculating block offset.
Make sure the rect starts at the beginning.
GS/TC: Add caching to block offset calculation for TranslateAlignedRectByPage and DirtyRectByPage.
Speed/optimizations.
Follow up from https://github.com/PCSX2/pcsx2/pull/13339
Test games/benchmark from https://github.com/PCSX2/pcsx2/pull/13339
Also test/benchmark games provided in the log file:
[block offscreen calculations v2.zip](https://github.com/user-attachments/files/22683224/block.offscreen.calculations.v2.zip)
No.

GS/TC: Optimize block offset calculations v2.

---

pcsx2-qt/Settings/GraphicsOnScreenDisplaySettingsTab.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2/Config.h
pcsx2/GS/GS.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/Patch.cpp
pcsx2/Patch.h
pcsx2/Pcsx2Config.cpp

This PR adds the indicator for currently activated game patches.
Preview:
DB = GameDB patches
P  = Patches (Widescreen, No-Interlacing, etc)
C  = Cheats
Useful during user supports to check if a user has enabled patches for their games.
Test if the amount counter is correct, try combinations of patches/cheats, etc.
To enable: `Settings -> Graphics -> OSD -> Show Patches`
NB: `Show Settings` must also be enabled in conjunction.
Ora

OSD: Add ability to show the amount of activated patches

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/TC: Point m_from_target to new target if it's also a source in CombineAlignedInsideTargets.
Issue is it was erasing the source which doesn't get passed back to the main draw function, so we should be setting m_from_target to null because it is linked.
GS/HW: Update manual deswizzle detection.
Check if a draw is either a palette or 32bit depth format, also check for swizzle format is 16 or 32bit.
Expand/update quadrant detection, use the quadrant size of what it should be from the page size and compare it to the actual quadrant size from the vertex positions.
Crash fixes.
Fixes Stolen crashing and swizzle issues.
Fixes https://github.com/PCSX2/pcsx2/issues/13348
Test mentioned games/issues with the dumps provided, test some other random stuff, dump run no issues.
Dump to crash test: …

GS/HW: Point m_from_target to new target if it's also a source in CombineAlignedInsideTargets, update manual deswizzle.

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/DX12: Backport dx11 full rt copy optimizations.
We are copying the whole RT so just call CopyResource instead of CopyTextureRegion which will be faster.
Speed.
Test /benchmark games, as well as the list in the file, may also benefit the most as it also uses copies for blending.
[full rt copies list.txt](https://github.com/user-attachments/files/22747920/full.rt.copies.list.txt)
No.

GS/DX12: Backport dx11 full rt copy optimizations.
