- plugins/GSdx/GSDevice11.cpp
- plugins/GSdx/GSDevice11.h
- plugins/GSdx/GSDevice9.cpp
- plugins/GSdx/GSDevice9.h
- plugins/GSdx/GSTexture11.cpp
- plugins/GSdx/GSTexture11.h
- plugins/GSdx/GSTexture9.cpp
- plugins/GSdx/GSTexture9.h
- plugins/GSdx/GSdx.cpp
Fixues issue with full mipmapping on D3D11 with textures appearing broken.
Some code still remains to be ported but at least the broken textures issue has been resolved.
Issue #2150 
GSdx-d3d: Update nvidia hack with vendor id detection.
Hack will no longer be active on Intel or AMD gpus.
Close #1026
Commits by: @KrossX
> GSdx-d3d: Port max_layer mipmap calculation from opengl, update nvidia d3d hack

- bin/GameIndex.dbf
This PR resolves bad shadows and random sprite/HUD corruption in SOCOM 1.
> GameDB: Add VU Clamp Mode and GIF FIFO Hack to SOCOM 1

- plugins/GSdx/res/glsl/tfx_fs.glsl
- plugins/GSdx/res/tfx.fx
Another commit from @KrossX oh nice.
Follow up on issue #2057 
Commit:
https://github.com/PCSX2/pcsx2/commit/a8968257db0b3cfaeafa872cdeddd455280802c8
Related PR ?
https://github.com/PCSX2/pcsx2/pull/782
Fixes texture flickering in Oni on d3d11.
Close ##2057
> GSdx-d3d: Keep fract in [0;1] range port from OpenGL.

- plugins/GSdx/res/glsl/tfx_fs.glsl
- plugins/GSdx/res/tfx.fx
@KrossX showing GSdx some more love.
Makes UV coord be on the range [0, SIZE) before applying mask and
offset. This fixes Xenosaga's hair for example, which has negative UV
coords.
Xenosaga Example
Master HW:
PR:
SW:
Needs to be tested for any regressions.
@atomic83GitHub I leave the testing to you.
> GSdx: Wrap negative UV on region repeat wrap mode.

- plugins/GSdx/GSRendererDX9.cpp
Might be better.
`#maked3d9greatagain`
> GSdx-d3d: Use Colormask instead of GSDXRecoverableError on d3d9 texture shuffle

- plugins/dev9ghzdrk/Linux/Linux.cpp
- plugins/dev9ghzdrk/Linux/dev9ghzdrk.ui
- plugins/dev9ghzdrk/Win32/Config.cpp
- plugins/dev9ghzdrk/Win32/Win32.cpp
- plugins/dev9ghzdrk/pcap_io.cpp
- plugins/dev9ghzdrk/smap.cpp
Follow on to #2586 which ensures that MAC address is unique on Xlink Kai when using Windows. Apparently the old GetAdapterInfo() API is deprecated after Windows XP. Previous build was returning last two bytes as 00:00 rather than last two bytes of host adapter's MAC as highlighted below
> Get host mac correctly on Windows

- plugins/GSdx/GSHwHack.cpp
Change the code so that some crc hacks on some games that remove
ghosting/blur issues on upscaled resolutions are disabled on native
resolution if crc hack level is below Aggressive state (most of the time).
They aren't needed then so why don't we aim for better accuracy.
Edit: @mirh I believe you'd like this change :smile:
> GSdx: Change how some crc hacks work on native resolution

- plugins/GSdx/GSdx.cpp
Suggested by @MrCK1 
This should make things a bit easier for users when picking resolutions.
> GSdx-gui: Change internal resolution drop down list names

- plugins/GSdx/GSHwHack.cpp
- plugins/GSdx/GSRendererDX.cpp
- plugins/GSdx/GSRendererOGL.cpp
We can't do a full port because channel shuffle and depth sampling need
to be ported to d3d but at the very least we can do a partial port that
skips the bad draw calls.
This way we can remove all the remaining crc hacks for ICO in GSHwHacks.
> GSdx-d3d: Partial port of the ICO HLE workaround

- plugins/GSdx/GSDevice.h
- plugins/GSdx/GSRendererOGL.cpp
Maybe both ShaderConvert and ChannelFetch enums can be moved to GS.h.
@tadanokojin I believe you were looking for something like this ?
> GSdx: Add an enum for channel fetch

- 3rdparty/wxwidgets3.0/include/wx/generic/wizard.h
- 3rdparty/wxwidgets3.0/src/generic/wizard.cpp
This is a partial fix for #1207, as described in "Bug no. 1".
Back/Cancel buttons were initialized only once when wizard was constructed, so translations were also applied only once at that time. However, Next/Finish buttons had its string replaced when switching pages (so Next can become Finish when appropriate), and that triggered retranslation every time. If translation changed between those two events, you'd end up with a frankenstein navigation bar in two languages:
This PR caches translated strings for Next and Finish at the time of initial creation of those buttons. This has two added benefits:
- Not triggering retranslation every time string changes.
- "Next>" and "Finish" strings are not duplicated in the code anymore - and they could be considered "magic values".
#1207 also …
> Cache strings for "Next>" or "Finish" buttons in wxWizard

- locales/pt_BR/pcsx2_Main.po
Fixed typos, grammatical errors, several inconsistencies with words and terms, changed some words that had a wrong translation or could be improved according to context, and translated some untranslated terms.
> Update Brazilian Portuguese translation

- bin/GameIndex.dbf
Removing this CRC check allows the patch to work with another version containing the same serial but a different CRC (as noted in https://forums.pcsx2.net/Thread-bug-report-Forbidden-Siren-2-Pal?page=2)
> GameDB: Remove CRC check for Forbidden Siren 2 patch

- pcsx2/DebugTools/DebugInterface.cpp
This PR is _not_ tested! I have not looked into how PCSX2 handles memory accesses, so reading from kernel memory (`0x80000000` and above) may cause issues.
Currently, none of the EE kernel is viewable from the debugger, which poses issues for me when debugging code that makes use of syscalls. This PR should allow the memory region `0x80000000 - 0x800FFFFF` to have readable disassembly.
> Debugger: Make EE kernel region accessible to debugger

- plugins/GSdx/GSTextureCache.h
Removed three useless virtual specifier added wrongly to operators and destructor in #2344, as highlighted thanks to @turtleli.
The modifiers presence shouldn't be cause of bugs, but it slows down the accesses to the functions and pollutes the code, so its removal is necessary.
> GSdx-TC: Remove useless virtual specifiers

- plugins/GSdx/GSTextureCache.cpp
- plugins/GSdx/GSTextureCache.h
Enabled caching of clut copies with `PaletteMap` also in the case 8-bit texture is disabled, which is the default (on #2344 the caching of clut copies _and palette textures_ was done only when 8-bit texture was enabled).
Brings moderate speedups ~10% in the most concitated parts of the ZoE2 Anubis benchmark, but may improve performances in all the cases when there are many `Source` objects created with clut copies to be stored.
The quality of the comments has been improved to better highlight the mechanics of the caching system.
> GSdx-TC: Use PaletteMap also when 8-bit texture is disabled

- bin/GameIndex.dbf
This'll potentially fix "Unplayable Bug" caused by COP2. (This patch exists in NTSC-U, but confirmed this patch work on NTSC-J.)
> GameIndex: Add Ace Combat 5 COP2 Patch on NTSC-J.

- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/Panels/GSWindowPanel.cpp
gui: Move the Off option to the top instead of bottom for FMV Aspect Ratio Override.
It's not ideal for it to be at the bottom.
Adjust the logic how the button works, there was an issue if both aspect ratios
were the same the aspect ratio chosen was selected to Fill.
Also adjust the code so the button better responds to realtime toggling.
If disabling the button realtime during a fmv then the normal aspect ratio
should be chosen.
There's still an issue left where if the fmv button is changed first and then
the aspect ratio button the button would would not work in realtime. Switching it off
seems to reset and make it work again.
Note: even the old 4:3 option had these same issues with realtime toggling.
> pcsx2: Fix some issues on FMV Aspect Ratio Override

- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
Idea is to allow Alpha Stencil to work with Fast Date.
Let Fast Date run for the supported calls since it's more accurate, let
Alpha Stencil take care of the rest.
This might fix some issues where Alpha Stencil caused some issues making
it a bit more accurate.
> GSdx-d3d: Update Fast DATE and Alpha Stencil behaviour

- CMakeLists.txt
In the comments in the cmake file, it said that it had already been changed to support the new policies, but it hadn't been tested. Eventually, those depreciated policies will no longer be there, so switching is something that should be done at some point.
I switched both on, and built with all the extra plugins and with gtk 2 and gtk 3. It seemed to work both times. Doing as a PR request do it can get a bit of testing before being turned on in the main system. (And so I can see a travis cl build before committing.)
> Switch to using the current cmake policies, not depreciated ones.

- plugins/GSdx/Renderers/Common/GSTextureCache.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSTexture11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureCache11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureCache11.h
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Window/GSSettingsDlg.cpp
- plugins/GSdx/res/convert.fx
Code is ported from OpenGL.
Note: Depth fmt is still not yet supported but after this has been merged it should be a lot easier to do.
Collaborators: @KrossX , @tadanokojin , @gregory38
> GSdx-d3d: Add support for Depth Conversion on Direct3D11

- plugins/GSdx/Renderers/OpenGL/GSTextureCacheOGL.cpp
Get rid of duplicate code in switch cases.
> GSdx-TCOGL: Adjust depth format cases in Texture Cache GL

- plugins/GSdx/Renderers/Common/GSTextureCache.cpp
- plugins/GSdx/Renderers/Common/GSTextureCache.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Refactor and fix palette management.
1. Improve ICO hack by using palette cache for depth sampling, removing only point of creation of palette textures outside TC (removes conditional deletion of `Source::m_palette` in `~Source()`),
2. Purge comments,
3. Reformat parts of the code,
4. Centralize CLUT comparison logic in `PaletteKey` equality operator,
5. Fix and rationalize palette texture or clut copy attachment and update with respect to pre-`PaletteMap` behavior,
6. Make `PaletteMap` capable of managing at the same time Palette with and without `GSTexture`,
7. Handle possible case of `Source` lookup hit with `psm.pal` value changed.
Closes #2702 , Closes #2736 and prevents possible similar regressions.
> GSdx: Palette management refactor and fix (v2)

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSRendererDX11.h
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/DX9/GSRendererDX9.cpp
- plugins/GSdx/Renderers/DX9/GSRendererDX9.h
- plugins/GSdx/Renderers/DXCommon/GSDeviceDX.h
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.h
- plugins/GSdx/res/tfx.fx
Note the feature is still not yet complete, copy function needs to be
implemented (suggested by Gregory) but it can be done at a later date,
this still fixes a bunch of issues on various games even in it's current state.
Related: https://github.com/PCSX2/pcsx2/issues/1318
> GSdx-d3d: Add support for Channel Shuffle on Direct3D11

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/DXCommon/GSDeviceDX.h
- plugins/GSdx/res/tfx.fx
tfx.tx: Add support for Tales of Abyss and Urban Chaos HLE shader. 
Add sample_depth function, note only Tales of Abyss and Urban Chaos
depth sampling is supported, full depth fmt will need to wait a little
longer.
GSdx-d3d11: Add support for Tales of Abyss and Urban Chaos shader bit  and shader macro.
GSdx-d3d11: Plug the TOA and Urban Chaos code in to channel shuffle.
On Tales of Abyss it fixes blur,
On Urban Chaos it fixes fog/transparent layer.
Note: Depth needs to be enabled on d3d11 to emulate the effect.
No support for d3d9 ofc.
> GSdx-d3d11: Add Tales of Abyss and Urban Chaos HLE channel workarounds

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSTexture11.cpp
- plugins/GSdx/Renderers/DX11/GSTexture11.h
Check for FB read on slot 4.
If it happens, copy the render target and replace slot 4.
This is useful for properly emulating the channel shuffle effect on dx11.
Much thanks to @gregory38 for his help on this.
> GSdx-d3d11: Detect FB read on Slot 4

- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
- plugins/GSdx/res/tfx.fx
Dfmt in texture shuffle function already picks the 16 format on slot 2
so it's better to let it call the shader instead of aout.
We can keep old aout code until FbMask emulation is added on d3d11. We
can purge aout along with alpha hack then.
> GSdx-d3d11: Redo destination format and alpha output

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/DXCommon/GSDeviceDX.h
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- plugins/GSdx/res/tfx.fx
tfx.fx: Remove datst (DATE).
Code was never hit on D3D11. D3D11 uses stencil operations.
GSdx-d3d11: Adjust DATE code.
Remove DATE shader macro and bit.
Remove useless HasStencil case. If DATE is enabled stencil is also
enabled, this check is useless.
Also remove leftover rtCopy , RTCopy sampler and rt cases.
> GSdx-d3d11: Adjust DATE code, remove RTCopy sampler

- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
Texture scaling for x/y values wasn't being set in all cases.
This ensures that it is to fix a bug in finding nemo (and possibly others).
Current master:
After patch:
EDIT: Almost forgot, thank you greg for pointing out the bug.
> gsdx-d3d11: Fix Depth FST

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
Update `CopyOffscreen` to accept the `ps_shader` value when doing `StretchRect`.
This fixes an issue where it was selecting the wrong PS for depth cache read.
Should (hopefully) fix SMT.
And once again thanks Greg for pointing this bug out to me.
> gsdx-d3d11: Fix CopyOffscreen bug

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
Enables live debugging for D3D11 shader code.
> gsdx-d3d11: Enable HLSL debugging on development builds

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.h
- plugins/GSdx/Renderers/SW/GSRendererSW.h
Remove GSCrc.h include in GSRendererHW and GSRendererDX11, file is
already included in GSState.h.
Remove GSRenderer.h include from renderers except Null and CL, file already
included in TextureCache hw/sw.
Remove resource.h include from GSRendererDX11, already included in GSDevice11.
Remove GSOsdManager.h from GSDeviceOGL, already included in GSDevice.
> GSdx: Cleanup file includes

- plugins/dev9ghzdrk/pcap_io.cpp
Previous MAC was registering as PS3 with the new version of XLink. This allows XLink to detect as PS2 again
> Dev9ghzdrk: MAC updated to work with XLink 7.4.32

- plugins/GSdx/Renderers/Common/GSTexture.h
- plugins/GSdx/Renderers/DX11/GSTexture11.cpp
- plugins/GSdx/Renderers/DX11/GSTexture11.h
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/Null/GSTextureNull.h
- plugins/GSdx/Renderers/OpenGL/GSTextureOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSTextureOGL.h
- plugins/GSdx/Renderers/SW/GSTextureSW.cpp
- plugins/GSdx/Renderers/SW/GSTextureSW.h
This allows d3d11 to dump textures in a similar fashion to OGL.
Previous behavior was to output the texture with alpha.
Instead, let's split it as outputting the texture with alpha can produce a completely transparent texture which is useless for debugging.
> gsdx-d3d11: enable splitting of alpha in dumps

- plugins/spu2-x/src/ADSR.cpp
Get rid of GetLinearSrAr code, it wasn't used anywhere so I don't see a
reason why to keep it, other than clogging up the code, if someone wants
to work on it they can re add the function in the future.
I happen to spot this by chance in one of the compile warnings on travis.
> spu2-x: Remove unused GetLinearSrAr code

- cmake/BuildParameters.cmake
The warnings issue should be resolved now thanks to arcum.
Fixes compiling issues on some systems/distros using gcc 8.2+
Idea by turtleli.
Also add -mfxsr flag suggested by Gregory.
Issue https://github.com/PCSX2/pcsx2/issues/2669
> cmake: Re add mxsave and add mfxsr flag to compiler flags.

- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/DXCommon/GSDeviceDX.h
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.h
- plugins/GSdx/res/convert.fx
- plugins/GSdx/res/tfx.fx
Remove colclip and negative blend algo.
Code was old and inefficient. HDR colclip will do a better job.
GSdx-d3d11: Add/port HDR colclip support.
It helps render shadows a lot better compared to the old code.
convert.fx: Update main4 shader to better support hdr colclip.
Credits to @gregory38 and  @tadanokojin for helping with the code.
> GSdx-d3d11: Remove old colclip algo and add support for HDR colclip

- bin/GameIndex.dbf
The PR fixes black box issues when going ingame with UEFA Euro 2004.
I only apply it on the fr-g version as it's the only I can test.
Without the fix:
With it:
> GameDB: UEFA Euro 2004 black box fix

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DXCommon/GSRendererDX.cpp
Port of the ICO HLE fix and update to fb copy on slot 4
> gsdx-d3d11: ICO depth HLE

- pcsx2/Patch.cpp
- pcsx2/Patch.h
- pcsx2/windows/cheats/browser.cpp
Pnach had a limit that, while increased at some point to 2048, is still not enough for everyone. This uses a vector to avoid that limit, as there is no reason to keep it and people loading pnach with over 2048 patches most likely know what they are doing.
Inipatch group member was also unused in the whole codebase so I did some cleanup and removed it.
> PCSX2: Remove the arbitrary limit on patches by converting the patch list to a vector

- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Sprites are flat so aniso is likely useless (it would save performance for others primitives).
PR: Needs to be tested, mostly on 2D rpg games.
master vs pr with anisotropic filtering enabled.
Idea by @gregory38
> GSdx-ogl: Enable anisotropic filtering only for triangles

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
Improved handling of frame buffer copy by accounting for fb read on all slots.
- implement before/after draw functions
- defer setting of resources on the api to just before the draw
- use a bitfield to keep track of set/copied resources
- recycle copies after draw
Fixes: RE4 and Tales of Abyss
> gsdx-d3d11: Framebuffer copy improvements

- plugins/LilyPad/Config.cpp
Fixes an issue with the window size and Show/Hide special inputs button
resetting when lilypad was closed and reopened, this was because the
code was executed only when the button was actually clicked.
The values will be properly stored in cache along with the rest already
working properly buttons.
I don't know if this is actually proper, not sure if I should move a bit more of the code as well.
> LilyPad: Adjust Special Inputs window and button behavior

- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/res/glsl/tfx_fs.glsl
1. Allow hrd colclip to also run on the unsupported
cases which should be pretty rare.
2. Remove colclip from high sw blending.
3. Disable the hdr colclip shader which may not be
actually required to run.
Note: I didn't run any tests to compare raw dump, only performance comparison which was within margin.
Idea by @gregory38
> GSdx-ogl: Small colclip improvements

- pcsx2/gui/AppCoreThread.cpp
- VuClipFlag hack is only used by the SuperVU1 Recompiler, let's avoid enabling it when it's not used.
Previously a console message would be provided stating that `(GameDB) Enabled Gamefix: VuClipFlagHack` even when the user is using the Interpreter (or) MicroVu Recompiler. The following patch prevents such confusions.
> PCSX2: Avoid enabling VuClipFlag at some scenarios

- plugins/dev9ghzdrk/Linux/net.cpp
I'm a bit suprised this code ever worked before (did it?). I got crashes on startup and decided to look into it.
It turns out the `rx_thread` handle was being overwritten by the returned status.
I did not add code to handle any errors (and I wouldn't know how). The original code also didn't handle this, so I assume this will be fine.
---
I'm having some issues with the networking dialog in the bios; so I'm still unable to test if network traffic actually works. There are also some other issues that need to be addressed, like non-descriptive errors if opening the adapter with pcap fails; however, I'll probably leave that to someone else.
*CC @lowlyocean who wrote the original code (in #2586)*
> dev9ghzdrk: pthread_create returns status, not thread handle

- bin/GameIndex.dbf
PlayStation Underground 4.4 is a set of 2 discs:
* SCUS-97120: PS1 CD (disc 1)
* SCUS-97121: PS2 DVD (disc 2)
Specific changes:
* Remove disc 1 since it's out of scope
* Change 4.3 to 4.4 in disc 2's name (4.3 doesn't include any PS2 discs)
> GameDB: Fix PlayStation Underground 4.4 entries

- tools/GSDumpGUI/Forms/frmMain.Designer.cs
- tools/GSDumpGUI/Forms/frmMain.cs
This change adds a function to handle the main form being closed, in which all processes are forcibly killed if not already killed.
> (GSDumpGUI) Make sure all child processes are closed when closing main form

- bin/GameIndex.dbf
This PR add:
- A Emotion Engine timing fix for World super police (Tested by @prafullpcsx2 and Discord member)
- The rounding fix for the international version of Final Fantasy X (Tested by @Mensa41 Close https://github.com/PCSX2/pcsx2/issues/2891)
- A Emotion Engine Clamping fix for let's make a soccer team (Tested by @atomic83GitHub)
- A Emotion Engine rounding fix for Eternal Ring (Tested by @atomic83GitHub)
- Add the WRC avec Sebastien Loeb patch. (Made by @prafullpcsx2, tested by @atomic83GitHub)
There are also several additons about Winback fixes for various regions.
> [GameDB] Fixes, serial and patches update.

- plugins/GSdx/GSdx.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
Enable automatic breaking on d3d11 messages:
- `D3D11_MESSAGE_SEVERITY_CORRUPTION`
- `D3D11_MESSAGE_SEVERITY_ERROR`
- `D3D11_MESSAGE_SEVERITY_WARNING`
- `D3D11_MESSAGE_SEVERITY_INFO`
Hidden option `dx_break_on_severity` bitfield
Debug build only.
> GSdx-d3d11: Enable break on D3D message

- bin/GameIndex.dbf
- pcsx2/x86/ix86-32/iR5900-32.cpp
Continuation from https://github.com/PCSX2/pcsx2/pull/1783
pcsx2: Fix stall on branch .. in delay slot.
Fixes stall when loading a stage in WRC 3.
Gamedb: Remove stall delay branch patches from WRC3, WRC Rally Evolved/WRC avec Sebastien Loeb.
Bonus, add XgKickHack for the French version of WRC Rally.
> PCSX2: Fix stall on branch in delay slot

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Single triangle draw can now hit the tex_is_fb path.
Primitive Overlap will return no overlap  for single primitive (triangle).
Ratchet and Clank, Jak, tri-Ace games.
It should improve shadow rendering.
Idea by Gregory.
Issue #2889
> GSdx-ogl: Check if primitives are triangles instead of overlapping

- bin/GameIndex.dbf
This PR add a modified patch to "WRC avec sebastien loeb", this fixes a very bad performance problem with a delay slot instruction which for an unknow reason (Timing?) tanks the performances when using physics in the playground mode.
With the delay slot instruction:
Without the delay slot instruction:
> GameDB: WRC avec sebastien loeb performance fixes

- plugins/GSdx/Renderers/HW/GSHwHack.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
- plugins/GSdx/Renderers/HW/GSTextureCache.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.h
Proof of concept. It should provide a huge speedup when accurate
blending is enabled for tri-ace / Jak / R&C series (shadow rendering)
See #2894
Need PR #2892
> gsdx ogl: bypass the texture cache when the frame buffer will be sampled

- plugins/onepad_legacy/wx_dialog/dialog.cpp
There was assumption in code, that SDL enumerate left horizontal axes as 0, vertical as 1,  right horizontal as 2 and right vertical as 3. In general case it is not true.
> Fixing stiks state monitor in onepad (legacy) configuration dialog.

- plugins/onepad_legacy/Linux/linux.cpp
- plugins/onepad_legacy/controller.h
- plugins/onepad_legacy/wx_dialog/GamepadConfiguration.cpp
Sensibility slider now can be used to set sensibility of gamepad axis in linux version of OnePad plugin. Perhaps it is done in wrong way at wrong place.
> Onepad (legacy) sensibility implementation for linux

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
> gsdx-d3d11: ensure texture size of at least 1x1

- plugins/GSdx/GSDrawingContext.cpp
- plugins/GSdx/GSDrawingContext.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
It is quite complex to handle rescaling on ComputeFixedTEX0
so this function is less stricter than GetSizeFixedTEX0,
therefore we remove the reduce optimization,
and we don't handle bilinear filtering which might create wrong interpolation at the border.
Fixes FFX upscaling issues on Bilinear filter during cutscenes.
Fixes #2961
> GSdx-hw: Fix border issue on ComputeFixedTEX0.

- bin/docs/debugger.txt
- pcsx2/gui/Debugger/CtrlMemView.cpp
- pcsx2/gui/Debugger/CtrlMemView.h
You can now paste a hex string into the memory view (with Ctrl+V). Needs testing on Windows.
> debugger: Muti-byte hex strings can now be pasted into the memory view

- pcsx2/GameDatabase.h
- pcsx2/ps2/BiosTools.cpp
- plugins/dev9ghzdrk/Win32/tap.h
in vs 2019, the system xhash used by unordered_map uses _Target_ in its template definition. pcsx2 #defines this in the r5900 and r3000 headers which leak cause a cryptic compilation error. A quick fix here is just to undef it in gamebase.h. A better fix would be to encapsulate the definition or use something more c++ to avoid the pre-processor.
tap.h did not have string defined. I guess this was included transitively somewhere with an earlier set of system headers.
Finally in biostools, the file is opened in text mode which causes the bios to be partially read. I'm not sure that's vs2019 specific but it's wrong in any case. Maybe the default mode parameter changed at some point. Maybe wxFile would be a better choice here rather than WxFFile because wxFile always open s in binary mode.
> changes required to compile and run using VS 2019

- tools/GSDumpGUI/Forms/frmMain.cs
GsDump file can be optional in case you just want to launch the plugin config dialog
Throw with a meaningful error message in case validation layer fails
> [skip ci] Handle dumpPath as optional.

- plugins/GSdx/Renderers/Common/GSDevice.cpp
- plugins/GSdx/Renderers/Common/GSDevice.h
- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSRendererDX11.h
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/Null/GSDeviceNull.h
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/res/tfx.fx
Changes:
GSDevice11.h:
- class PSConstantBuffer: Removed variable (MinF) that was not being used and structured to be closer to OGL side.
- class PSSelector: Added variable to for selecting accu blend in the shader.
GSRenderer11.cpp:
- EmulateTextureSampler(): Removed variable (MinF) that was not being used and structured to be similar to OGL.
- DrawPrims(): Added checking/enabling accu blend. Small restructure to alpha test code so it is clearer.
GSRendererOGL.cpp:
- DrawPrims(): Same restructure as above for alpha test clarity.
GSDeviceOGL.h:
- class PSConstantBuffer: Some things seem incorrect here, I'm not sure. Seems as if Update() does not fully update the buffer as it is. I put in a FIXME comment.
GSTextureFX11.cpp:
- SetupPS(): Added defines for shader to enable accu blend.
- …
> GSDX-DX11: Partial port of OGL SW blend to DX11 / changes to blend map of both OGL/DX11.

- bin/GameIndex.dbf
Added VU clamping to none for Ulitmate Ninja 2 to fix minor visual issues with lights.
- Tested by @boberto5888
Added VU clamping to extra for Ulitmate Ninja 3 to fix minor visual issues with lights as well as missing QTE.
- Tested by @boberto5888
Added beta trial serials.
- Tested by @atomic83github
> GameDB: Naruto games fixes and beta trial updates

- cmake/BuildParameters.cmake
Fixed a typo in BuildParameters.cmake file.
> CMake: fix typo in BuildParameters.cmake

- bin/GameIndex.dbf
- Added EETimingHack to Popcap hits vol1 and 2 to fixes random crashing in the game.
Tested by @atomic83github and discord memeber "Jacoby".
> GameDB: Popcap crashing fixes

- bin/GameIndex.dbf
- serials update along with a minor modification to siphon filter patches typo.
- Pac Man world 2 Timing fixes to avoid hangs at various levels. Tested by atomic83github.
- Missing VU clamping fixes for some EA sports titles. Tested by atomic83github.
Note: Pac man World 2 still hangs during tutorial.
> GameDB: Serial update

- plugins/GSdx/Renderers/Common/GSDevice.h
- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/HW/GSHwHack.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- Purge existing crc hack for Sonic Unleashed
- Add support for rgba channel selection to StretchRect d3d11/gl
- Add an OI hack for Sonic Unleashed that will allow us to replace draws by a copy, it will allow to render the shadows properly now on Sonic. Requires crc level above minimum for it to work.
Collaborators/credits to Gregory and Kojin for helping with the code.
> GSdx-hw: Sonic Unleashed OI hack

- tools/GSDumpGUI/Forms/Helper/GsDumpFinder.cs
Log error in console instead of having the application crashing when the selected GSdx dumps directory is not found.
How to reproduce the error without this fix:
1. Select a GSdx dumps directory
2. Close GSDumpGUI
3. Delete selected directory
4. Open GSDumpGUI
5. Crash
> GSDumpGUI - GsDumpFinder: fix error when dir not found

- README.md
While it should be possible to run PCSX2 on Vista, it belongs in an OS graveyard as MS dropped support of it along with XP. So let's drop official mention of it and not continue to worry if future commits will break it.
> Readme: Drop official support of Vista

- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/res/tfx.fx
gsdx-d3d11: Extend sw blending to BLEND_NO_BAR which is also free and doesn't require rt sample nor any barriers.
It helps light rendering in SW Battlefront 2, VP2 also triggers it but needs to be further tested what it does.
gsdx-d3d11: Extend BLEND_NO_BAR to also hit on clamp 0, it's faster than standard HDR algo.
GOW shows a nice fps improvement. Spyro too maybe.
> GSdx-d3d11: Enable Blend no barrier support on d3d11

- bin/GameIndex.dbf
This commit add FPU clamping fixes for Bully/Canis Canem Edit to fix the inability to take the bottle in the trophy case in Chapter 2: Hattrick vs Galloway.
Tested by atomic83github.
> GameDB: Bully/Canis Canem Edit unbeatable Chapter 2 level fixes.

- pcsx2/x86/microVU_Log.inl
A [previous commit](https://github.com/PCSX2/pcsx2/commit/ea38e2eba58ba87e8e245c8cc795363fb95cb3be#diff-136d6ae872176c8acc158d97dc2cea19L31) inadvertently removed a vsprintf call necessary for microVU debug logging to function properly.
> Fix microVU debug logging.

- bin/GameIndex.dbf
This PR clean a bit the GameDB and add 2 fixes for:
-Ratatouille:  Add vu round to positive to fix very minor lines appearing at certain points during the game.
tested by atomic83github
-Dog's Life: Add vu clamping mode to extra+preserv sign to fix minor white SPS problem on characters.
Tested by discord member: LastBreath
> GameDB: Various updates/cleanup and gamefixes for Ratatouille and Dog's life

- pcsx2/gui/Panels/PluginSelectorPanel.cpp
When there's no previous plugin set, auto select the GSdx plugin in order AVX2 -> SSE4 -> SSE2. Might help avoid having the wrong plugin selected on the first time wizard.
PS: No idea if it works, I only get the SSE2 plugin.
> pcsx2: Auto select GSdx during plugin selection

- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
Developed a new SW sprite render function, which is used to fix Jak and Daxter colors in Jak games and to remove the old Jak games hack which yielded wrong colors and clashed with TC search texture in RT function.
- Remove OO_JakGames hack for palette readback from framebuffer (slow,
clashes with texture in RT TC function, clashes with Target readback logic)
- Developed new method SwSpriteRender with CPU rendering logic
- Add OI_JakGames method using SwSpriteRender for CPU palette rendering (fast, does not clash with
texture in RT TC function, no readback required)
Performances (SSE2, OGL HW, Intel UHD 620, i7-8550U, Win10x64):
|  Jak 3     | Before | After | Change |
|--------|--------|-------|-------|
| Ingame | 22 fps    | 25 fps  | +3 fps |
| Cutscene | 19 fps    | 24 fps   | +5 fps | …
> GSdx-hw: New SW sprite render function, used in Jak games

- .travis.yml
- Update Ubuntu version to Xenial as Trusty is EOL as of April
- Drop GCC 4.9
> Travis: Bump Ubuntu version to Xenial

- bin/GameIndex.dbf
Patches HookOrDie()
Emulator can't boot this without the patch. All Jak X builds have this problem, but soon I will patch the few remaining ones too.
> Gamedb: Patch for Jak X NTSC Public Beta

- plugins/spu2-x/src/Mixer.cpp
Fixes the noise generator outputting a 4.8 kHz tone instead of white noise. The random number generator used in GetNoiseValues currently repeats every 10 samples, which is really really awful for a random number generator.
Here's what it sounded like before the fix: https://streamable.com/pa1fi
Here's what it sounds like after the fix: https://streamable.com/u5zhi
Here's what it sounds like on a real PS2: https://streamable.com/ipi5s
Not entirely accurate but a massive improvement over playing a 4.8 kHz tone.
> Spu2-x: Fix noise generator

- plugins/LilyPad/Tooltips.cpp
This commit add the Xbox One controller mention in the Xinput description. This include the Mediatek wireless adapter. PS, yeah this is for the unkown,special and unique guy.
> [Lilypad] Update Xinput description

- bin/GameIndex.dbf
This PR add an emotion engine rounding fix for Super Monkey Ball Deluxe to fix object balls never stoping in the Monkey Billiards DX minigame.
Tested by atomic83github
> GameDB: Super Monkey Ball Deluxe Monkey Billiards DX minigame fixes

- plugins/GSdx/Renderers/HW/GSHwHack.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
Idea is to add an offset so the shadows get rendered properly at the half bottom screen.
Ease the crc hack to only skip misdetection of texture shuffle.
Issue #2449
> GSdx-hw: Add OI rendering fix for Big Mutha Truckers

- pcsx2/gui/Panels/BiosSelectorPanel.cpp
- pcsx2/gui/Panels/PluginSelectorPanel.cpp
This builds on the auto GS plugin selection to automatically set a pad plugin as well, picking the non-legacy version of onepad on Linux and lilypad on windows. (I'm largely doing this because it's possible to build lilypad for Linux, and it *shouldn't* be the default, but l is before o alphabetically...)
I also added some code to pick the bios by default. This isn't perfect; if you never go to the screen where it shows the bios, it's still not set. If you do go to that window, it'll automatically pick the first bios in the list, though, which is probably the only one.
This needs testing on Windows.
> PCSX2: Set pad plugin and bios defaults automatically.

- bin/GameIndex.dbf
This PR add a VU rounding mode fix to MTX Mototrax which solve glitchy graphics ingame.
Tested by forum member: wheninrome
> GameDB: MTX Mototrax glitchy graphics fixes

- tools/GSDumpGUI/Core/Program.cs
- tools/GSDumpGUI/Forms/Helper/GsDumpFinder.cs
- tools/GSDumpGUI/Forms/frmMain.Designer.cs
- tools/GSDumpGUI/Forms/frmMain.cs
- tools/GSDumpGUI/GSDumpGUI.csproj
- tools/GSDumpGUI/GSDumpGUI.sln
- tools/GSDumpGUI/Library/GSDXWrapper.cs
- tools/GSDumpGUI/Library/GSDump/GSDump.cs
- tools/GSDumpGUI/Library/NativeMethods.cs
> GSDumpGUI: Usability improvements

- pcsx2/gui/AppMain.cpp
- pcsx2/gui/GlobalCommands.cpp
Attempt to fix issue #370.
Setting the toggle variable is now at the vsync point. FMV toggle should still work as usual, but the F9 toggle should have to wait the full period of around 32 frames. This seems short enough while also depends on how fast those frames can rendered, avoiding having to set a timer in ms.
Fixes #370
> PCSX2: Wait some frames between F9 SW render toggles

- bin/GameIndex.dbf
This PR add a FPU negative div hack to Crazy Frog Racer 2 to fix black fade effects and some overlays texts in the menus.
It also add EETimingHack on some missing Alone in the Dark revisions which fixes game hanging at boot.
Tested by Forum member:
- LoStraniero1991
> GameDB: Crazy Frog Racer 2/Alone in the Dark fixes

- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
Two small fixes in the `GSRendererHW::SwSpriteRender` method:
- Avoid asserting on Q coords equality if texture coordinate system is UV and not STQ, when checking that no rasterization is required (rasterization is not supported).
- Always use the rectangle of the draw to compute width and height of the draw; Assert that there is no offset (not supported yet), and that if texturing is enabled, the reported texture size is big enough (no junk reads).
These fixes do not have impact on `GSRendererHW::OI_JakGames` (which is calling the renderer only if specific conditions are met, like STQ coords and 16x16 rectangle draw without offset), but nevertheless are essential for extending the usage of the method to other games that might benefit from it (like Dragon Ball Z: Budokai Tenkaichi 2).
> GSdx-hw: fix sw sprite renderer

- plugins/GSdx/GSCrc.cpp
- plugins/GSdx/GSCrc.h
- plugins/GSdx/Renderers/HW/GSTextureCache.cpp
- plugins/GSdx/Renderers/HW/GSTextureCache.h
Fixes eyes rendering in Jak games both ingame and in cutscenes.
Previous method yielded no eyes in Jak 2/3/X cutscenes and no eyes invalidation in any Jak game (i.e. no blinking).
- Keep track of Target TBP0 in Source built from Target
- Invalidate Source using also from Target TBP0 information
- Generalized offset search logic with caching system (works for BW > 1 and any PSM, limited to PSMCT32 for now)
- CRC Flags mechanism for default behavior enabling in Jak games
https://www.youtube.com/watch?v=lXlOzzE7Qhw
Various:
- Fix texture end block computation around the code, using the block of the bottom right texel as last valid block
- Fix Target::Inside method which is now inclusive both on start and end blocks
> GSdx-hw TC: improve search/invalidate tex in RT

- plugins/GSdx/Renderers/SW/GSDrawScanlineCodeGenerator.x86.cpp
~~It seems SEL.LTF was beign set to the mipmap filter while SEL.MMIN was being set to the texture filter. Setting LTF to the first bit and MMIN to the last one instead, fixes Hot Pursuit 2 mipmap on SW.~~ That was just fine.
Problem seems to be a typo in a duplicated code of the SSE2 code generator part.
Before:
After:
> GSdx SW: Fix SSE2 mipmap code generation.

- 3rdparty/pthreads4w/autostatic.c
This fixes a semi-consistent regression introduced by #3056, where `on_process_exit` would execute before other destructors relying on pthreads.
Now `on_process_init` has been moved to an earlier section of static initializers, **ensuring** it will be initialized first. Previously, this initializer was placed in the same section as any other initializer, making their order of execution non-deterministic across compilations - for example, I was unable to reproduce this issue as soon as I forced `pthreads4w.c` to recompile last!
> 3rdparty/pthreads4w: Ensure on_process_init early execution

- 3rdparty/pthreads4w/autostatic.c
This reverts commits:
https://github.com/PCSX2/pcsx2/commit/88a02941f698577ecc45450308269f57e1d066ad
https://github.com/PCSX2/pcsx2/commit/af6f04020225eaf3239bc9b4542f4afd84560540
It actually causes more issues instead of fixing so just revert the new
code. Porting to std::thread for 1.8 would be a far better alternative.
Current master is broken and hangs on pcsx2 launch.
> 3rdparty/pthreads4w: Revert recent pthreads changes/commits

- pcsx2/gui/AppMain.cpp
- pcsx2/gui/GlobalCommands.cpp
This fixes a hang (deadlock?) when using the F9 key on certain situations. For example, going from SW render to HW during the codec scenes in MGS3.
However, the FMV software toggle still runs the code from the same place. This might lead to the same problem when using that option.
> PCSX2: Avoid hang when switching renders with hotkey.

- plugins/GSdx/Renderers/OpenGL/GSTextureOGL.cpp
Fix `PboPool::Map` method by rounding up the size for alignment before computing the offset for the writes, thus avoiding memcpy after the end of PBO buffer.
Bonus: an error log and a TODO are added in the case that the size of the write will exceed the size of the PBO segment (currently 16MB), in which case not all the required memory fences will be synchronized, thus texture data corruption may occur.
Special thanks to @gregory38 for spotting the issue and proposing the solution, and to @atomic83GitHub for the intense testing.
Closes #2916
> GSdx-hw OGL: fix PBO pool map size.

- bin/GameIndex.dbf
This PR add some explaination about what the EETiming hack does in "Enter the Matrix" and add a missing serial with corresponding fixes to it.
Tested by atomic83github
> GameDB: Enter the Matrix changes

- pcsx2/CDVD/CDVDaccess.cpp
- pcsx2/CDVD/CDVDisoReader.cpp
- pcsx2/CDVD/InputIsoFile.cpp
- pcsx2/CDVD/IsoFileFormats.h
- pcsx2/PluginManager.cpp
- plugins/cdvdGigaherz/src/CDVD.cpp
- plugins/cdvdGigaherz/src/CDVD.h
- plugins/cdvdGigaherz/src/ReadThread.cpp
Changes:
* Fix a few off by one errors.
* Fix loading for some games that attempt to read past the end of disc by doing nothing instead of erroring out. Seems to fix All Star Baseball 2005. cdvdGigaherz change isn't tested since I only have a blockdump.
Fixes #2113.
> cdvd: Fix end-of-disc issues

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/OpenGL/GSTextureOGL.cpp
d3d10 = 8192
d3d11 = 16384
Seems it is easier to hit the limit. Champions of Norrath with 8x upscale for example.
> GSdx-d3d11: Adjust maximum texture size limit based on available feature level

- plugins/GSdx/GSdx.cpp
- plugins/GSdx/GSdx.h
Partially replace the Linux ini code so that it:
- works on both Windows and Linux
- is backwards compatible with older GSdx inis
- properly handles UTF-8 ini pathnames
This fixes an issue with GSdx on Windows not being able to handle non-ASCII ini pathnames.
This should mean that only dev9ghzdrk is unable to handle non-ASCII ini pathnames though GSdx does still have Unicode issues (external shader/capture filenames).
Related to #2478.
> gsdx: Use the same ini code on both Windows and Linux

- build.sh
- cmake/BuildParameters.cmake
- plugins/GSdx/CMakeLists.txt
- plugins/GSdx/GSdx.cpp
- plugins/GSdx/res/tfx.cl
Easy as adding `--opencl` when running `./build.sh`.
Removed #error hello since latest 32-bit version of OpenCL is 1.2 anyway and there isn't any significance noted for it.
This doesn't improve the renderer but I thought this might help.
> GSdx-ocl: Enable OpenCL build option on Linux

- pcsx2/Patch_Memory.cpp
The parsing error results in type 6 codes with more than one offsets getting terminated early.
> Corrected Parsing Error in Pnach Type 6 Code Parsing

- cmake/SearchForStuff.cmake
For Slackware stable (`14.2`) it has the older `cmake-3.5.2` which does not seem to support `GREATER_EQUAL`. So I replaced it with `VERSION_EQUAL` and `VERSION_GREATER` which is more verbose, but works with both newer and older cmake versions.
Unfortunately I am stuck testing against older cmake versions until Slackware 15.0 is out (When its ready).
```
CMake Error at cmake/SearchForStuff.cmake:225 (if):
if given arguments:
"GCC_VERSION" "GREATER_EQUAL" "9.0" "AND" "GCC_VERSION" "LESS" "9.2"
Unknown arguments specified
Call Stack (most recent call first):
CMakeLists.txt:27 (include)
-- Configuring incomplete, errors occurred!
See also "/tmp/SBo/pcsx2/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/SBo/pcsx2/build/CMakeFiles/CMakeError.log".
```
> cmake: Fix build with cmake-3.5.2.

- pcsx2/IPU/IPU.cpp
The pack command converts from RGB32 to RGB16/INDX4, not RAW8 to RGB16/INDX4.
Also, the VQ conversion (still unimplemented) only occurs when the output format is 0, so fix that as well.
> pcsx2: Partially fix IPU PACK command

- common/include/x86emitter/x86_intrin.h
Fixes a build issue with `clang-9.0.0`. Please see this comment https://github.com/PCSX2/pcsx2/issues/3096#issuecomment-536298922.
Note that it still doesn't build with clang, but it gets as far as the original issue now.
> Fix build error with clang9.

- pcsx2/gui/GlobalCommands.cpp
Hitting F4 toggles the master framelimiter and the `AlsoApplyToGui` property causes `AppApplySettings()` to be called. This makes it unresponsive compared to turbo keys and locks the application.
Setting it to false, I assumed the use of F4 will not be reflected in the UI but if you open the settings panel it shows as expected. So no bad side effect, possibly.
> Avoid hang when spamming F4 (Frame Limiter Toggle)

- plugins/GSdx_legacy/CMakeLists.txt
This silences many annoyingly verbose warnings using clang and the legacy GSdx plugin copying the code in the newer GSdx.
https://github.com/PCSX2/pcsx2/blob/e2d899231019ecb9e93af77cb0d57acd6fbb10c2/plugins/GSdx/CMakeLists.txt#L21
```
[107/641] Building CXX object plugins/GSdx_legacy/CMakeFiles/GSdx-legacy-1.0.0.dir/stdafx.cpp.o
warning: unknown warning option '-Wno-class-memaccess'; did you mean '-Wno-class-varargs'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-packed-not-aligned'; did you mean '-Wno-over-aligned'? [-Wunknown-warning-option]
2 warnings generated.
```
> gsdx_legacy: Silence very verbose clang warnings.

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Hit unsafe instead of safe path for sw fbmask when there is no alpha blending.
It affects the games listed:
```
Fbmask no ABE, texture shuffle
Dragon Quest VIII
Final Fight streetwise
Finding Nemo
Rogue Galaxy
Scarface
Fbmask no ABE
Crash Twinsanity
Finding Nemo
Ford Racing 2
MGS2 Thermal vision (red)
Mission Impossible - Operation Surma
Scarface
Sly 2
Resident Evil Outbreak
Spiderman 3
Monster Hunter
```
So far notable performance improvement show Spiderman 3 and Scarface of 1-2 fps when using basic blending.
Improve https://github.com/PCSX2/pcsx2/issues/3083
> GSdx-ogl: Hit unsafe instead of safe path for sw fbmask when there is no blending

- bin/GameIndex.dbf
This PR add various VU rounding modes to various Asobo games which produces small lines ingame.
> GameDB: Asobo VU Rounding mode fixes

- plugins/spu2-x/src/Linux/Config.cpp
Fixes https://github.com/PCSX2/pcsx2/issues/3124
This will default to `SDLOut` to match the current default and also its unlikely that someone will use PCSX2 without SDL installed since its required for onepad.
> spu2-x: Fix crash with an invalid output module.

- common/include/Utilities/gtkGuiTools.h
- common/include/x86emitter/x86_intrin.h
This silences many duplicate and very noisy trivial warnings with clang, silencing them is helpful because they make viewing potentially more serious warnings harder.
```
[3/641] Building CXX object plugins/spu2-x/src/CMakeFiles/spu2x-2.0.0.dir/Linux/Dialogs.cpp.o
In file included from ../plugins/spu2-x/src/Linux/Dialogs.cpp:20:
In file included from ../plugins/spu2-x/src/Linux/Dialogs.h:23:
../common/include/Utilities/gtkGuiTools.h:37:19: warning: unused function 'ps_gtk_hbox_new' [-Wunused-function]
static GtkWidget *ps_gtk_hbox_new(int padding = 5)
^
../common/include/Utilities/gtkGuiTools.h:46:19: warning: unused function 'ps_gtk_vbox_new' [-Wunused-function]
static GtkWidget *ps_gtk_vbox_new(int padding = 5)
^
../common/include/Utilities/gtkGuiTools.h:56:19: warning: unused function …
```
> common: Silence -Wunused-function clang warnings.

- plugins/GSdx/Renderers/HW/GSHwHack.cpp
Previous skip value 6 wasn't enough and caused some visual issues on the
ntsc version. Use value of 8 instead.
Issue reported by ozzie212121 on discord.
> gsdx-hw: Adjust GSC_Bully crc hack

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
Match opengl behavior.
Stumbled on this when testing Burnout Revenge and got a different result for DX11.
> GSdx-d3d11: Fetch the texture PSM format rather than the context format in texture sampler

- pcsx2/Patch_Memory.cpp
I removed the special case for when the data field is 0 for an extended code that is pointer type. I tested this case on hardware with Codebreaker V10 and it worked normally.
> Removed Special Case in Pnatch Parser for Pointer Commands When Data Field is 0

- appveyor.yml
Adds a VS2019 build job and removes the VS2015 build job.
When this is merged, support for compiling with VS2015 will be dropped.
> ci:appveyor: Add VS2019 and remove VS2015

- bin/GameIndex.dbf
On Direct3D11 FMVinSoftwareHack in combination with FXAA or External
shader enabled cause the emulator to hang. This is only a temporary
solution, a real solution would be to fix the fmv issue instead.
Issue #2635
> Gamedb: Remove FMVinSoftwareHack gamefix for Silent Hill 3

- bin/GameIndex.dbf
---------REMOVALS--------
EETimingHack:
- Blade 2 (replace EE TimingHack with GIF FIFO Gamefix)
- Buffy the Vampire Slayer
- Drakan The Ancient Gates
- Euro Rally Champion
- Obscure
- R-Type Final
- Muppets Party Cruise (replace EETimingHack with mVUFlagSpeedHack)
OPHFlagHack:
- Sphinx and the Cursed Mummy
- Buffy the Vampire Slayer
- Motorstorm Arctic Edge
------ADDITIONS```````
- Evergrace (NTSC-J only) (Full EE Clamping - fixes hanging going in-game.)
> GameDB: Update/Remove outdated gamefixes for the following titles:

- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
Xenosaga handles the half bottom as an vertex offset instead of a buffer
offset which does the effect twice.
Half bottom won't trigger a cache miss that skip the draw because it is
still the normal buffer but with a vertices offset.
Close #3147
> GSdx-hw: Disable half screen TS fix for Xenosaga 3

- bin/GameIndex.dbf
This PR add multiples patch for various games.
F1 Racing championship - Fixes IPU hanging.
Sprint Cars 2 - Rearrange COP2 instructions to fix bad mac flag stuff. Fix for bouncing vehicles.
Knockout Kings 2002 - Fixes DMA loop causing Hanging at start of fight.
> GameDB: Patches update

- bin/GameIndex.dbf
Fixes respawn issues as well as SPS.
Also add a missing DB entry for a JAP release of SC3 Trial. The demo
discs may not actually need the gamefixes so they aren't included.
Wasn't able to verify if the gamefixes are required for SC3.
> Gamedb: Add vuClampMode 2 gamefix to Soul Calibur 2

- bin/GameIndex.dbf
This PR add a patch for the game : Ecco the Dolphin - Defender of the Future
This resolve a race condition causing the game to hang on the main loading screen.
> GameDB: Ecco the dolphin - Defender of the Future patch

- bin/GameIndex.dbf
Fixes issue regarding a missing blade in Castlevania Curse of Darkness. User reported in Discord that any EE clamping modes besides full would work (they used Extra + Preserve sign, so we've done that here as well)
> GameDB: Resolve missing blade issue in Castlevania Curse of Darkness

- bin/GameIndex.dbf
- pcsx2/x86/iCOP0.cpp
Core: Fixes booting issues in the following games:
Jak X, Namco 50th anniversary, Spongebob the Movie, Spongebob Battle for Bikini Bottom,
The Incredibles, The Incredibles rize of the underminer, Soukou kihei armodyne, Garfield Saving Arlene, Tales of Fandom Vol. 2.
The games will no longer require a patch to boot.
Gamedb: remove gamefix patches for DI execution fixes. Jak X, Spongebob Squarepants( The movie  and Battle for Bikini Bottom), namCollection - Namco 50th Anniversary, Soukou kihei armodyne, garfield saving arlene.
Credits go to Refraction, fix was backported from Dobiestation, original contributors Refraction and PSI
> pcsx2: DI execution is delayed by one instruction

- pcsx2/Vif_Unpack.cpp
The relevant VIF_LOG statement previously printed the packet size from the structure relating to VIF0, regardless of whether the log message was for VIF0 or VIF1. I'm pretty sure this is just a typo.
> Fix VIF unpack log message in Vif_Unpack.cpp

- pcsx2/gui/Debugger/CtrlMemView.cpp
Feature was never implemented, option served no purpose to remain there.
Issue #3186
> pcsx2-gui: Remove Dump memory option from Debugger

- bin/GameIndex.dbf
This prevents the DMA transfer from being corrupted intentionally from values written in cached memory (that require the EE data cache).
> GameDB: Add patch for Nascar 09

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
Previous behaviour:
Anisotropic filtering was continuing to run even with Nearest filtering.
On opengl it doesn't run on nearest filtering. The gui for both
renderers also greys out aniso when nearest is selected.
Anisotropic filtering being able to run on palette texture. This caused
to break the rendering on palette textures for games that use it.
PR behavior:
The PR corrects both of these behaviors, Aniso won't run on palette
textures as well as nearest filtering.
Test cases for observing the issues were used: Star Ocean 3, Fifa
Street.
Visual issue representation below is when anisotropic filtering runs on palette textures.
Comparison master, Bilinear PS2, Aniso 16x:
Comparison PR, Bilinear PS2, Aniso 16x:
> GSdx-d3d11: Adjust anisotropic filtering handle

- plugins/GSdx/Renderers/HW/GSHwHack.cpp
- plugins/GSdx/Window/GSSetting.cpp
gsdx-hw: Move GSC_XenosagaE3 crc hacks to Aggressive state.
It will allow D3D11 to render Texture shuffle effects.
Keep the crc hacks on aggressive instead of removing them as they might
still be useful.
gsdx-gui: Update crc hack level and Image load store tooltips to reflect recent changes.
> GSdx: Adjust GSC_XenosagaE3 crc hacks and some gui tooltips to reflect recent changes.

- bin/GameIndex.dbf
This PR add several fixes for several games as well as some serial updates:
- Batman Vengeance - patch removal and the addition of EETiminghack to fix slow videos.
- Musashiden 2 - Several fixes which reduce by a large margin the amount of graphical issues.
- F1 2001 - Adjustment of the patch to make it fully working as well as the addition of the NTSC-U patch.
- Sprint Car 2 - Added a patch to make it playable without bouncing cars.
- Wakeboarding Unleashed - Added 2 fixes to fix various graphics issues (still unplayable on retail builds).
- Netsu Chu! Pro Baseball 2003 - Added a patch to fix game hanging when going ingame.
- Hisshou Pachinko-Pachislot series - Added the EETiminghack to solve crashing videos.
> GameDB: New fixes/patches

- bin/GameIndex.dbf
This patches some values in Powerdromes VU microprogram, which restores the 3d models of the characters.
The game uses the extended PS2 float range to do some culling calculations, so I have brung them down to be usable by x86, no other way to really fix this game.
> Added VU patch for Powerdrome PAL

- plugins/GSdx/res/tfx.fx
The change should've been pushed in #3091
Fixes regression with fog rendering.
> gsdx-d3d11: Truncate fog in tfx.fx shader.

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/OpenGL/GSTextureOGL.cpp
This reverts commit 99f814d3764bc4ce87491ebeedac84762b3d68f3.
The assert gets triggered on Linux and so debug build can't be used properly.
Would be nice to investigate why in the first place but until then revert the
entire commit. We have checks for texture limits anyway so it shouldn't be an issue.
> Revert "gsdx-ogl/d3d11: Add a assert when texture is too small or too big."

- plugins/GSdx/GSState.cpp
Mask A+D addresses. Fixes network configuration tool screen, closes #287.
> GSdx: Mask A+D addresses

- CMakeLists.txt
- build.sh
- cmake/BuildParameters.cmake
- cmake/FindHarfBuzz.cmake
- pcsx2/CMakeLists.txt
This does the following:
The Harzbuzz module is updated, resolving issue #3313 
The cmake minimum version is now a range, causing it to use the newer flags by default on newer versions up to 3.17, resolving Issue #3310
There's a new option to compile with flag -ftime-trace with clang, which can be useful for determining things that slow compile time.
If you are on gcc and cmake 3.16+, actually precompile PrecompiledHeader.h.
> Fix various cmake issues

- plugins/GSdx/vsprops/common.props
Fast floating point behaviour can optimise out handling for special floating point values e.g. NaNs. As GSdx needs to handle NaNs in a few places, precise floating point behaviour should be used instead.
Fixes a flashlight regression in Silent Hill 2/3 that was caused by VS2019 optimising out NaN handling.
Related #2817
> gsdx:windows: Use precise floating point behaviour

- pcsx2/HwRead.cpp
> Allow reading of 8bit timers (and other hardware pages)

- plugins/GSdx/GSState.cpp
> gsdx: mirror RGBAQ to 0x11

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.h
gsdx-d3d11: Always enable sw colclip for BLEND_NO_BAR.
- Free blending and it's faster than standard hdr algo when Blending
Accuracy is disabled.
- Add assert when disabling hw blending, hw blending should only be disabled
on free/no barrier blending. D3D11 lacks other types of blending.
- Use const to get rid of some warnings.
gsdx-ogl:
- Always enable sw colclip for BLEND_NO_BAR.
Free blending and it's faster than standard hdr algo when Blending
Accuracy is disabled.
- Enable sw colclip for Safe FBMASK SW emulated.
instead of hdr mode with accumulation blend so we don't use a mix of sw
and hw blending. It is more accurate.
Test case: Superman Shadows of Apokolips
- Use const to get rid of some warnings.
> GSdx-hw: Colclip adjustments

- plugins/GSdx/Renderers/Common/GSDevice.cpp
- plugins/GSdx/Renderers/Common/GSDevice.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Since we use it on d3d too it will better fit the naming.
> gsdx: Rename BLEND_NO_BAR to BLEND_NO_REC.

- pcsx2/gui/App.h
- pcsx2/gui/Saveslots.cpp
- pcsx2/gui/Saveslots.h
- pcsx2/gui/SysState.cpp
- pcsx2/gui/UpdateUI.cpp
Only update the backup when freezing or defrosting or changing active save slot, not when updating the ui. Gets rid of potential latency. 
I also refactored the saveslot code a bit to be more readable and use a ranged for.
> Don't check the backup save slot when updating the ui.

- pcsx2/x86/ix86-32/iR5900-32.cpp
This change makes the EE recompiler not hardcoded to working with 32 MB of RAM, and instead work with the amount of RAM set in Ps2MemSize::MainRam. The rest of PCSX2 seems to work fine with more than 32 MB of RAM - it is only the EE recompiler that has trouble. If the Ps2MemSize::MainRam value is not changed from the default 32 MB, there should be no change: 32 MB / 0x10000 = 0x200, the value that was there previously.
This may be helpful if anybody else in the future wants to emulate a PS2 dev kit with 128 MB or RAM, or maybe the PSX dvr thing which I think has 64 MB of RAM. I've confirmed that with the change, you could set Ps2MemSize::MainRam to 128 MB, and execute code with the recompiler that's above the first 32 MB of RAM, and do VIF and scratchpad DMA transfers from this upper …
> Make recLUT not hardcoded to 32 MB.

- plugins/GSdx/GSDrawingContext.cpp
- plugins/GSdx/GSDrawingContext.h
- plugins/GSdx/Renderers/OpenCL/GSRendererCL.cpp
- plugins/GSdx/Renderers/SW/GSRendererSW.cpp
Opengl debug macro already provides draw number so it is esentially
useless.
> GSdx-sw: Remove s_n (draw number) parameter from GetSizeFixedTEX0.

- bin/GameIndex.dbf
Fix for terrible performance in US versions of Primal (all the time) and Ghosthunter (when encountering Teddy Bear and in the moment of Gator-Man's rush attack, maybe few other cases). Both games use shared code with pretty dumb wait loops in the microcode, those are absolutely unnecessary and significantly kill performance on the emulator.
> Performance fix for Primal and Ghosthunter. 

- plugins/GSdx/GSdx.cpp
- plugins/GSdx/Renderers/Common/GSRenderer.h
- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
gsdx-d3d11: Remove Dispatch function, was never used.
gsdx-d3d11: Remove exclusive fullscreen code used in legacy gsopen.
> GSdx-d3d11: Remove exclusive fs from gsopen legacy. Remove Dispatch function, was never used.

- plugins/GSdx/GSdx.cpp
- plugins/GSdx/Renderers/Common/GSRenderer.cpp
- plugins/GSdx/Renderers/Common/GSRenderer.h
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/res/glsl/common_header.glsl
- plugins/GSdx/res/glsl/tfx_fs.glsl
- plugins/GSdx/res/tfx.fx
WIP: Initial basic implementation of dithering on the hardware renderers.
There's currently no check for dither matrix changes for buffers to be updated. **Edit: done.**
There's also no check for framebuffer format, in case it should only be enabled on some. **Edit: done.**
It currently does not scale with increased internal resolution. I kinda like the smaller dithering though.  **Edit: done, setting.**
SW renderer shows a darker more pronounced dithering although pattern seems to match.   **Edit: OpenGL can be pretty close to SW dithering.**
There should also be a setting to toggle dithering off, as many people seem to dislike the effect.  **Edit: done, setting.**
~~**TODO:** Move dither matrix to its own buffer.~~ Should be done when doing a constant buffer overhaul.
> GSdx-HW: Dithering on Hardware

- pcsx2/CMakeLists.txt
- pcsx2/IPU/IPU.cpp
- pcsx2/IPU/IPUdither.cpp
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
Changes:
- Adds dithering to the RGB32->RGB16 conversion (see images from Hisshou Pachinko PachiSlot Kouryaku Series Vol 10)
- Adds SSE2 implementation of RGB32->RGB16 conversion (speed on the opening FMV in the above mentioned game goes from ~175% to ~275% with frame limiter disabled on my system using GSdx software mode)
- Implements VQ (see images from Klonoa 2)
Dithering before:
Dithering after:
VQ before:
VQ after:
Side note:
10ee832dc13c7aee9623aaf2e0d2875ceecc4797 might be revertable and Klonoa 2 patches might be removable because of #3119 (needs to be checked).
> IPU Improvements

- common/src/Utilities/IniInterface.cpp
This is a PR to fix what could be considered a voodoo issue that occurs on Arch Linux with the AUR. I say voodoo as this issue is known not to happen to everyone and has happened with different circumstances. If I build the PKGBUILD file with the clang compiler the crash this amends will occur but not with GCC. As of issue #3408 it's discovered this can occur with the GCC compiler as well. Language selection has no known effect on the issue.
The issue this pr is stated to amend is thus. For previous users of pcsx2 there are settings files that pcsx2 will attempt to load. Doing so causes the WXstring in IniInterface.cpp Ln 173 to report an incorrect length thus crashing pcsx2. Clearing all settings files and folders is known to work around the issue being discussed. 
```
12:49:07: Warning: …
```
> This is a fix for a Voodoo issue that occurs on Arch Linux AUR.

- bin/GameIndex.dbf
- pcsx2/IPU/IPU.cpp
- pcsx2/IPU/IPU_Fifo.cpp
Changes:
- Removes GameDB patches for Klonoa 2
- Reverts workaround for Klonoa 2 crashes.
I believe #3119 made both of these unnecessary.
> Remove/revert Klonoa 2 workarounds

- common/include/PS2Eext.h
- plugins/GSnull/Linux/Config.cpp
- plugins/PadNull/Linux/Config.cpp
- plugins/PadNull/Linux/PadLinux.cpp
- plugins/SPU2null/Linux/Config.cpp
I left the windows code as-is because I didn't want to accidentally break the windows build, though if anyone else wants to make windows use the wx code as well, it'd be a good idea.
I'd largely like to get rid of as much gtk code as we can, regardless of whether we end up getting rid of wx at some point.
Naturally, other plugins should be converted to wx dialogs as well, but one step at a time...
> Switch over the null plugins dialog code to use wxWidgets instead of gtk on Linux.

- plugins/GSdx/Renderers/SW/GSDrawScanline.cpp
- plugins/GSdx/Renderers/SW/GSDrawScanlineCodeGenerator.x86.avx.cpp
- plugins/GSdx/Renderers/SW/GSDrawScanlineCodeGenerator.x86.avx2.cpp
- plugins/GSdx/Renderers/SW/GSDrawScanlineCodeGenerator.x86.cpp
- plugins/GSdx/Renderers/SW/GSRendererSW.cpp
- plugins/GSdx/Renderers/SW/GSScanlineEnvironment.h
Follow up from #3414. SW renderer port.
Fixes SW renderer on #2623, #2271
> GSdx-sw: Add Z clamping to GSdx SW mode

- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/res/glsl/common_header.glsl
- plugins/GSdx/res/glsl/tfx_fs.glsl
- plugins/GSdx/res/glsl/tfx_vgs.glsl
- plugins/GSdx/res/tfx.fx
gsdx-d3d11: Port/add depth mask support to EmulateZbuffer.
Add support for depthmasking to EmulateZbuffer, previous old code had
support but wasn't ported properly with the new code a few years back.
VS Constant buffer is now properly setup.
gsdx-hw: Clamp zbuffer to depthmask instead of wrapping.
The behavior was verified on Dobie to be correct.
The code needs to be ported to SW renderer too to
improve rendering on SW side.
Current PR will fix plenty of games on HW renderer
that had/have zbuffer issues before.
v2. Set DepthMask to the maximum the current depth format allows.
Will properly clamp for 16bit and 24bit formats.
v3. gl: Fix uniform buffer upload/cache for VSConstantBuffer.
gsdx-hw: Remove the code block for the bad Z sise check in EmulateZbeffer.
Also fixes Itadaki Street text …
> GSdx-hw: EmulateZbuffer changes

- plugins/GSdx/Renderers/HW/GSHwHack.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
Improve and use `GSRendererHW::SwSpriteRender` for rendering sprites in DBZ:BT2, replacing the current OO and CU methods with an OI method, similar to what has been done for Jak games.
This both improves the performances and correctly renders some effects such as kaioken and character outlines also at upscaled resolutions.
Function `GSC_DBZBT2` in `GSHwHack.cpp` has been removed, as it clashes with the new OI method (if it is not removed, blur builds up around characters models).
Some assertions in `GSRendererHW::SwSpriteRender` have been improved to ease debugging.
An handy method `GSRendererHW::CanUseSwSpriteRender` has been implemented, to factorize the checks that are needed to be performed prior calling the `GSRendererHW::SwSpriteRender` to replace current draw call.
Looking forward …
> GSdx-hw: improve and use sw sprite render in DBZ:BT2, replacing OO & CU with OI

- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
In GSRendererHW, use SwSpriteRender for DBZBT3 to improve palette rendering.
Closes #2001.
> GSdx-hw: use SSR in DBZBT3.

- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/res/glsl/common_header.glsl
Bigger value comes first, then smaller to fill the gap so the alignment
can be proper.
vec3
float
> gsdx-ogl: Fix MaxDepthPS byte alignment.

- plugins/GSdx/Renderers/HW/GSTextureCache.cpp
- plugins/GSdx/Renderers/HW/GSTextureCache.h
Improve texture cache `Source` objects invalidation logic taking into account overlapping with current draw.
Fixes eyes rendering for the Major in Jak 1.
> GSdx-hw, TC: invalidate Source w overlapping draw.

- plugins/GSdx/GSCrc.cpp
- plugins/GSdx/GSCrc.h
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
The hack didn't properly work and it is a core issue.
> GSdx-hw: Remove Itadaki Street hw hack.

- plugins/GSdx/Window/GSSettingsDlg.cpp
v1 It won't allow users to try to input a value that isn't supported
osd (size, timeout, max), tc offsets (x, y), rendering threads.
v2 Use const if applicable for variables throughout
GSSettingsDlg.cpp. Will cleanup some warnings.
Close #3492
> GSdx-gui: Limit spin buttons input properly.

- bin/GameIndex.dbf
(#2774) Fixes flickering.
Fixes #2774
As discussed:
https://www.reddit.com/r/PCSX2/comments/his6i0/yakuza_1_tiling_glitch_on_power_up_menu/
> GameDB: Add EETimingHack gamefix to Yakuza.

- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Convert sprites on the cpu instead of the gpu when applicable on HW renderer. Port from
Opengl.
Lines: GPU conversion.
Triangles: CPU conversion.
Disable Geometry shader when conversion is done on the cpu.
Needs re testing #1921
Issue #551
> GSdx-d3d11: SetupIA, allow sprite conversion to be done on the cpu when applicable.

- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/stdafx.h
Updates the d3d device and swapchain creation to more modern methods.
- Use `CreateDXGIFactory2` to create the factory and store in member
- **Note:** `CreateDXGIFactory2` **is windows 8.1 and higher, this officially kills Windows 7 and Windows 8.0 support for GSdx**
- Use `CreateSwapChainForHwnd`
- Add messages for failures to the console
- Some general formatting improvements
> gsdx-d3d11: Modernize swapchain and device creation

- bin/GameIndex.dbf
Adds the Xenosaga save point crash patch to GameDB.
Patch location on the forums: https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?pid=603236#pid603236
The two questions that need answered:
1. Is the patch proven to be stable?
2. Is it a good idea to, even though PCSX2 accuracy makes it worse than a real PS2, patch something that's technically correct behavior for a better user experience?
My answers:
1. Yes, it's been in the field for a while and there's been several hundred downloads with no reported issues.
2. I do think so, simply in that users would appreciate not having to manually search up and retrieve the patch.
There's probably plenty of conflicting opinions, so lets discuss. To merge, or not to merge?
> GameDB: Add Xenosaga save point crash patch

- plugins/GSdx/GS.cpp
- plugins/GSdx/GSUtil.cpp
- plugins/GSdx/GSUtil.h
- plugins/GSdx/Renderers/DX11/GSDevice11.cpp
- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/vsprops/common.props
Further cleanup following #3508
> gsdx-d3d11: Remove legacy d3dcompiler code

- pcsx2/gui/ConsoleLogger.cpp
Makes it relatively darker by 30%
dev117 / PR 3446:
This PR:
Comparison slider:
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=fea2a7ce-c464-11ea-bf88-a15b6c7adf9a
> pcsx2-gui: Modern Dark Themed Console v2

- common/src/Utilities/Linux/LnxHostSys.cpp
- pcsx2/gui/RecentIsoList.cpp
I feel like the change for the shutdown crash I made should work on linux as well, but [the comment in `MmapResetPtr`](https://github.com/PCSX2/pcsx2/blob/5903ee95fe05df1684791ac32da3dcd1707414f3/common/src/Utilities/Linux/LnxHostSys.cpp#L181-L182) makes me doubt myself...  Does anyone know why mmap with `MAP_FIXED` might not do what we want?  For now it's ifdef'd for macOS only but if it does work on Linux we could use it all the time
> Fix a few crashes in macOS

- .gitignore
PCSX2-linux.sh is generated when building
GSdx debug files are created when running
> Update gitignore for Linux

- common/include/x86emitter/tools.h
`x86emitter/tools.h` is included by PCSX2's main `PrecompiledHeader.h`, meaning that it (and everything it includes) is a dependency of practically every file in PCSX2.
Removing its dependency on `x86emitter/x86emitter.h` reduces the rebuild time from editing other headers in `x86emitter` from 200s to 45s on my laptop (4c8t 2.8GHz Haswell)
> Reduce header dependencies on x86Emitter

- common/src/Utilities/CMakeLists.txt
- common/src/x86emitter/CMakeLists.txt
- pcsx2/CMakeLists.txt
Full compile of PCSX2 (without plugins) on my laptop: 230s → 85s
@arcum42 When you added PCH you said it wasn't working with Clang, what was breaking for you?
> Use precompiled headers with Clang

- bin/GameIndex.dbf
- pcsx2/Counters.cpp
- pcsx2/IopCounters.cpp
Don't interrupt if compare/overflow flag is already set
Removed patches for Harry Potter Prisoner of Azkeban and Chamber of Secrets as they should no longer be required.
Note - Some harry potter games still have the EE Timing Fix which may also not be required
Thanks to PSI for finding this solution
Fixes #1360
> EE/IOP Timer Interrupt Handling

- pcsx2/gui/AppAssert.cpp
closes #2796
Tested with resident evil 4 and on a musl system
> Allow running on systems without wx stackwalker

- plugins/spu2-x/src/wx/wxConfig.cpp
PCSX2 with no portaudio was failing to build because of an undeclared variable.
> Fix no portaudio build

- bin/GameIndex.dbf
24 : The game
Amplitude
Freaky Flyers
Free Running
Ghosthunter
Next Generation Tennis 2003
NHL 2K6
NHL 2K9
Primal
Ruff Trigger
Salt Lake 2002
Savage Skies
SOCOM 3
Tomb Raider: Angel of Darkness
True Crime: Streets of LA
Yanya Caballista: City Skater
GameDB: Patches for 22 games (or 16 individual games)
Workaround #1001 (fixed on 1.6 for NTSC-U already, this PR ports that to the PAL)
Workaround #3049 (fixes Socom 3)
> GameDB: Patches for multiple games

- bin/GameIndex.dbf
- pcsx2/IPU/IPU.cpp
Doing this reset performs a forced command end, meaning the IPU will run through the procedure of ending any command running and telling the core that it is done, even if there is no command currently active.
Fixes Fightbox
> IPU: Perform an interrupt on IPU_CTRL Reset.

- .clang-format
People were turning it off because it was doing stupid things, hopefully it will now do less stupid things
I added `BraceWrapping: AfterCaseLabel: true`, which makes this happen:
```cpp
switch (something) {
case option: // { doesn't go here
{ // goes here instead
}
```
Not sure what we prefer, and it wasn't in the style guide, but it seems like we mostly put them on separate lines for everything else
Also set `ReflowComments` to `false` to better match the `ColumnLimit: 0`, though I'm not sure if it does anything with `ColumnLimit: 0` anyways.
> Update .clang-format to better match upcoming style guide

- plugins/GSdx/res/glsl/tfx_vgs.glsl
Makes the code more like D3D, centering the offset for the line expansion.
Close #3574 
Close #2964
> GSdx-hw: Fix OGL line scaling

- 3rdparty/baseclasses/baseclasses.vcxproj
- 3rdparty/freetype/builds/windows/freetype.vcxproj
- 3rdparty/libjpeg/libjpeg.vcxproj
- 3rdparty/libpng/projects/vstudio/libpng/libpng.vcxproj
- 3rdparty/opencl/opencl.vcxproj
- 3rdparty/portaudio/build/msvc/portaudio.vcxproj
- 3rdparty/pthreads4w/build/pthreads4w.vcxproj
- 3rdparty/wxwidgets3.0/build/msw/wx30_adv.vcxproj
- 3rdparty/wxwidgets3.0/build/msw/wx30_base.vcxproj
- 3rdparty/wxwidgets3.0/build/msw/wx30_config.vcxproj
- 3rdparty/wxwidgets3.0/build/msw/wx30_core.vcxproj
- 3rdparty/xz/liblzma.vcxproj
- 3rdparty/zlib/zlib.vcxproj
- common/build/Utilities/utilities.vcxproj
- common/build/x86emitter/x86emitter.vcxproj
- common/vsprops/WinSDK.props
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- plugins/FWnull/Windows/FWnull.vcxproj
- plugins/GSdx/GSdx.vcxproj
- plugins/LilyPad/LilyPad.vcxproj
- plugins/USBnull/Windows/USBnull.vcxproj
- plugins/cdvdGigaherz/src/Windows/cdvdGigaherz.vcxproj
- plugins/dev9ghzdrk/Win32/DEV9ghzdrk.vcxproj
- plugins/dev9null/Windows/DEV9null.vcxproj
- plugins/spu2-x/src/Windows/Spu2-X.vcxproj
- tools/bin2cpp/bin2c.vcxproj
Makes the project build with the latest win10 SDK on the system. Uses a workaround for vs2017 to be replaced whenever we drop that build.
Doing this to address build issues in #3549
> vs-build: use the win10 sdk

- bin/GameIndex.dbf
Fixes out of bounds jumping glitch, solution proposed in issue #3544.
NTSC-U tested to be working.
PAL has yet to be tested.
No other glitches noticed, including cutscene audio that previous clamping adjustments had caused.
> [GameDB] Rogue Galaxy out of bounds fix in Myna

- common/include/Utilities/PageFaultSource.h
- common/src/Utilities/VirtualMemory.cpp
- pcsx2/IopMem.cpp
- pcsx2/Memory.cpp
- pcsx2/System.cpp
- pcsx2/System.h
- pcsx2/System/RecTypes.h
- pcsx2/VUmicroMem.cpp
- pcsx2/vtlb.cpp
- pcsx2/vtlb.h
- pcsx2/x86/iR3000A.cpp
- pcsx2/x86/ix86-32/iR5900-32.cpp
- pcsx2/x86/microVU.cpp
- pcsx2/x86/newVif.h
- pcsx2/x86/newVif_Dynarec.cpp
- pcsx2/x86/newVif_Unpack.cpp
- pcsx2/x86/newVif_UnpackSSE.cpp
Another part of #3451
Note: While this shouldn't change how anything works, it's been the #1 source of breakage of 32-bit builds in #3451 (it was the cause for the failure of win32 to allocate memory and the failure of linux-32 afterward) so we should definitely make sure it gets tested
There are a number of solutions to the problem so I'd like to list them here
The problem: On x86-64, most instructions that reference memory do it with a 32-bit offset from the current instruction pointer.  This means that code in the memory allocated without requesting a specific location probably won't be able access variables in global variables without a large and unwieldy `mov tmpRegister, address` before each usage (which would bloat access to the EE registers horribly)
Possible solutions
1. Move all …
> Allocate memory in an x86-64-compatible way

- pcsx2/Cache.cpp
- pcsx2/vtlb.cpp
- pcsx2/vtlb.h
- pcsx2/x86/ix86-32/recVTLB.cpp
Another small piece of #3451 
Moves all VTLB pointer manipulation into dedicated classes for the purpose, which should allow the algorithm to be changed much more easily in the future (only have to change the class and recVTLB.cpp assembly since it obviously can't use the class)
Also some of the functions that manipulated the VTLB previously used `POINTER_SIGN_BIT` (which `1 << 63` on 64-bit) while others used a sign-extended `0x80000000`.  Now they all use the same one (`POINTER_SIGN_BIT`)
Note: recVTLB.cpp was updated to keep it compiling but the rest of the x86-64 compatibility changes were left out
Also, Cache.cpp seems to assume VTLB entries are both sides of the union at the same time, which is impossible.  Does anyone know how this actually worked (and if this patch breaks it) or …
> Move VTLB pointer manipulation to a class

- debian-packager/control
Ubuntu 20.04 onwards stopped pulling in libx11-xcb-dev with libx11-dev
Close #3618
> Explicitly add libx11-xcb-dev to Debian packager

- bin/docs/PCSX2.1
```
man: ./PCSX2.1:65:9: STYLE: no blank before trailing delimiter: Fl h,
man: ./PCSX2.1:119:9: WARNING: skipping no-space macro
man: ./PCSX2.1:180:72: WARNING: skipping no-space macro
```
Reproduced with `mandoc-1.14.5.`
```
man -Tlint -l ./PCSX2.1
```
https://mandoc.bsd.lv/
The only cosmetic change is the first warning where `man(1)` no longer recognizes the option as `-h,` and now shows `-h` correctly.
__Original__
__PR__
> man: Silence warnings.

- pcsx2/gui/App.h
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/ConsoleLogger.cpp
- pcsx2/gui/ConsoleLogger.h
- pcsx2/gui/Debugger/DisassemblyDialog.cpp
- pcsx2/gui/Debugger/DisassemblyDialog.h
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- pcsx2/gui/UpdateUI.cpp
This pretty much rearranges the menus a bit in a way that makes sense to me.
Descriptions of the changes follow, though you'd probably get a better idea from compiling and running it.
The System menu is now the PCSX2 menu, and has been substantially rearranged. At the top, we have Boot ISO, Pause/Resume, Shutdown, and Run ELF. Fast Boot is now a checkbox, followed by "Create Blockdump", and then a Game Settings submenu with the other settings that used to be directly in the menu. then you have the normal save state menus, the backup save item, and exit, as normal.
CDVD, I didn't touch, as I didn't want to interfere with the CDVD plugin merge.
Config is mostly the same, except that Change Language is now in there.
Misc and Debug are gone.
Next we have the Window Menu, with "Show Debug", …
> pcsx2-gui: Some menu changes

- plugins/GSdx/GSCrc.cpp
Added missing CRC for Jak II PAL Preview and Review builds. Due to the protection, the CRCs are identical.
Added mention of Jak 3 Review build in comments. Same CRC as two other builds, due to its protection.
Added a missing Jak X Demo CRC.
> Updated Jak CRCs

- bin/GameIndex.dbf
- pcsx2/COP2.cpp
- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/VU.h
- pcsx2/VU0.cpp
- pcsx2/VU0micro.cpp
- pcsx2/VU0microInterp.cpp
- pcsx2/VU1micro.cpp
- pcsx2/VU1microInterp.cpp
- pcsx2/VUmicro.cpp
- pcsx2/VUmicro.h
- pcsx2/Vif0_Dma.cpp
- pcsx2/Vif_Codes.cpp
- pcsx2/Vif_Transfer.cpp
- pcsx2/gui/Panels/GameFixesPanel.cpp
- pcsx2/x86/iR5900.h
- pcsx2/x86/ix86-32/iR5900-32.cpp
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/microVU.cpp
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_Execute.inl
- pcsx2/x86/microVU_Macro.inl
Changes by Refraction:
Implement basic cycle counting for COP2 operations, implement COP2 detection while not interlocking, implement Mbit, change drastically cycles required to run every microprogram. Improved flag handling while COP2 update them.
Additionally:  
As explained here: [Link](https://www.patreon.com/posts/shadow-of-fixing-33354075). Hardware tests proved that VU run at the same speed as EE mips core. So lets set that in pcsx2 where it is possible.
Fixed games in this commit:
- (VIF) Hitman games - Could have potentially crashed randomly with TLB misses or FIFO errors, no longer happening
- 24 The game, Primal, Ghosthunter - No longer need patches to get full speed
- Air Rescue Ranger - Textures are now displayed correctly
- Amplitude - SPS on characters fixed
- Gift, Woody …
> Make VU run closer in sync with EE, implement Mbit

- pcsx2/x86/microVU_Lower.inl
Fixes an assertion failure in microVU from using an `xEmptyReg` as a value
> microVU: Fix empty register use

- bin/GameIndex.dbf
Gran Turismo Concept has a feature where it can drop money & passed licenses to the Gran Turismo 3 save, so it needs to see them.
I was only able to test the PAL version so I only applied a filter to that. If needed, I can source game serials from the wiki and add those pre-emptively too.
> GameDB: Add GT Concept 2002 memcard filter

- appveyor.yml
Add skip_branch_with_pr reference.
- Do not build feature branch with open Pull Requests.
Remove VS2017 32bit build, will allow appveyor to finish
jobs/work faster.
> ci-appveyor: Some tweaks.

- pcsx2/gui/ConsoleLogger.cpp
- pcsx2/gui/ConsoleLogger.h
Before, when changing the Console Logger's color theme, the text's background would not change.  This seems to be because `wxTextAttr` is not being used to set both background and foreground, which appears to be a separate concern from just `TextCtrl.SetBackground()`.
The caveat is that once text is written to the screen, it retains whatever color it used originally.  Meaning that **new** console logs will use the updated theme.  There is a way to solve this:
```cpp
m_TextCtrl.SetStyle(0, m_TextCtrl.GetLastPosition(), wxTextAttr(wxNullColour, darkThemeBgColor));
```
This will update the background color of all existing lines.  The problem with this, is the foreground color is potentially different on every line/character.  So lines are mostly unreadable (white text on a white background …
> pcsx2-gui: Change the console logger's theme on the fly

- pcsx2/Counters.cpp
- pcsx2/Counters.h
Fixes the Titantron's on the WWE games (Except Shut Your Mouth)
Fixes the frame order for the following games, so they look less blurry and don't need the interlacing mode swapped.
* Soul Calibur 2
* World Rally Championship
* Mike Tysons Heavyweight Boxing
* Urban Reign
* Mortal Kombat Shaolin Monks
Based on data gathered from PS2 console tests.
> GS/Counters: Fix CSR Swap and VBlank Interrupt timing

- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecording.h
- pcsx2/Recording/InputRecordingFile.cpp
- pcsx2/Recording/InputRecordingFile.h
- pcsx2/Recording/PadData.cpp
- pcsx2/Recording/RecordingControls.cpp
- pcsx2/Recording/RecordingInputManager.cpp
- pcsx2/Sio.cpp
- pcsx2/gui/AppInit.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/MainMenuClicks.cpp
An extended version of @xTVaser's original PR of the same name.
Original:
> These are the major issues that this PR resolves:
>
>- Forbid playing a recording that starts on a save-state if there is no game currently active
>- Previously, if a recording was attempted to be played, but failed, the menu options would still be modified as if the recording was successfully played
>- Similarly, if the dialog to play a recording was cancelled, the active recording would be cancelled which it shouldn't have been
>- Correctly pause/unpause emulation around theses scenarios (especially resuming emulation in the event of aborting playing/creating a recording)
>
>In order to accomplish some of these (especially the last one), modifications had to happen to InputRecordingFile and I took this …
> Resolve issues around playing and creating input recordings under certain scenarios (Extended)

- plugins/spu2-x/src/wx/wxConfig.cpp
- plugins/spu2-x/src/wx/wxConfig.h
Now that I've gone and spent a bunch of time on the GSdx dialog, the wx one I did for spu2-x felt like I could do it better. Here it what it currently looks like:
So, lets make this have a tabbed interface, combine all the extra dialogs into the main dialog, and add Ok/Cancel buttons.
> Revamp the wx spu2-x dialog.

- pcsx2/Gif_Unit.h
- pcsx2/Vif.cpp
- pcsx2/Vif0_Dma.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif_Codes.cpp
Removes an old VIF hack
Fix GIF resets
Fixes the memcard screen on Onimusha Blade Warriors, no longer invisible.
Gets rid of the vifcmd error spam in Ratchet & Clank when completing the game, doesn't totally fix it (at least I don't think the behaviour is completely correct) but it stops it being so messy.
> VIF: Set decoding status on VIF stall

- pcsx2/IopBios.cpp
- pcsx2/System/SysCoreThread.cpp
On express demand of @tadanokojin this fixes an issue where PCSX2 was not closing file handles used by the Host Filesystem subsystem until the process was closed, which was then freed by the OS.
As the ioman HostFS is implemented under a namespace I unfortunately can't put the reset into a destructor and had to put it in the core, which, while the changes are minimal, seems pretty dirty.
We should eventually move to a class for this as it assumes an array is initd at 0 when it very possibly cannot, but this requires basically rewriting the entire HostFS codebase, which I'm not very fond of doing at the moment.
I'll let you review and try to find a solution not quite as dirty
> HostFS: free fds when shutting down vm

- .travis.yml
- appveyor.yml
Keep them around for now, we will remove them along the way.
Replaced by Github Actions.
Webhook settings were adjusted as well, pr events have been disabled.
> ci appveyor/travis: Build only master branch.

- pcsx2/CMakeLists.txt
- pcsx2/Config.h
- pcsx2/IPC.cpp
- pcsx2/IPC.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/System/SysCoreThread.cpp
- pcsx2/System/SysThreads.h
- pcsx2/gui/App.h
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
This pull request implements a small socket based IPC for pcsx2.
Among the years [several](https://github.com/GovanifY/Teamod/blob/master/Teamod_2/PCSX2_DMA.cs) [tools](https://www.youtube.com/watch?v=6Ust-45nOWc) [have](https://www.youtube.com/watch?v=snDEzmUciZw) been developed by various romhacking communities to, say, test mods in real time and/or expand on the game features. They all have been implemented by using the equivalent of `ptrace pcsx2` and scanning the memory to find the correct addresses.
Needless to say this was prone to breakage, could differ between versions (and emulators) and was simply a bad idea. If you need to visualize the context think about tools that rewrote the JIT region in realtime.
An IPC for a tool->game communication makes sense, but the opposite is also …
> Socket IPC implementation

- .github/workflows/linux-workflow.yml
- .github/workflows/windows-workflow.yml
The `.git/modules` folder was not being cached/restored, which caused the post-cleanup of the `Checkout` step to flag an error at the end.  Caching this folder and thus completely caching anything submodule related, should eliminate this warning.
Also allowed submodules to be pulled in parallel when they aren't cached.
Current error:
From:
> ci: Resolve git-submodules related Actions warning

- common/include/PS2Edefs.h
- pcsx2/gui/GlobalCommands.cpp
- pcsx2/gui/MainMenuClicks.cpp
- plugins/GSdx/GS.cpp
- plugins/GSdx/GSCapture.cpp
- plugins/GSdx/GSCapture.h
- plugins/GSdx/Renderers/Common/GSRenderer.cpp
- plugins/GSdx/Renderers/Common/GSRenderer.h
- plugins/GSdx/Window/GSCaptureDlg.cpp
- plugins/GSdx/Window/GSCaptureDlg.h
- plugins/GSdx/Window/GSDialog.cpp
- plugins/GSdx/Window/GSDialog.h
- plugins/spu2-x/src/PS2E-spu2.cpp
- plugins/spu2-x/src/PS2E-spu2.h
- plugins/spu2-x/src/SndOut.h
- plugins/spu2-x/src/Wavedump_wav.cpp
Before, if you were to insert a filename in the dialog box, it would be taken as is. As a result, pcsx2 would export the avi file with a different extension or no extension althogether. This simply fixes that.
Additionally, the filename set for the AVI will be transfered over to the WAV allowing them to match up. No more overrding an alreadt existing recording.wav file.
> Address filename issues relating to capturing Video (.AVI) & Audio (.WAV)

- .gitignore
- common/include/PS2Edefs.h
- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/Linux/DriveUtility.cpp
- pcsx2/Hw.cpp
- pcsx2/HwWrite.cpp
- pcsx2/PluginManager.cpp
- pcsx2/ps2/pgif.cpp
- pcsx2/ps2/pgif.h
- plugins/spu2-x/src/PS2E-spu2.cpp
- plugins/spu2-x/src/PS2E-spu2.h
- plugins/spu2-x/src/SndOut.cpp
- plugins/spu2-x/src/SndOut.h
- plugins/spu2-x/src/Windows/Spu2-X.def
This is a simple fix that moves ps1 mode initializer to hwWrite.cpp and disables the incorrect CDVD one
> Got ps1 mode init function to exist in correct location. Added stubbed reset for spu that currently breaks sound if used

- .github/workflows/scripts/validate-vs-filters.ps1
- .github/workflows/windows-workflow.yml
msbuild does not use the project in it's entirety to build the app.  This means problems can slip through, so an easy solution is just to ensure the XML is well-formed.  More sophisticated validation could be done with something like `xmllint` but seems overkill (and more of a challenge to get installed on windows than linux of course).
Hopefully this will help to avoid issues like this getting into master:
- https://github.com/PCSX2/pcsx2/commit/2a292fdc05d037533e3db6bd9cebde33dca5aa59
A failure-test: https://github.com/xTVaser/pcsx2-rr/pull/39/commits/487af547c439145e9c78c25d2c1fe6d3ba52b445
> ci: Validate VS filter files in buiild

- pcsx2/IPC.cpp
- pcsx2/IPC.h
This adds an MsgVersion command to the IPC protocol allowing you to query pcsx2 version.
I also fixed a small boundings bug that was present in the initial merge, even though it couldn't do OOM operations it could still reuse old cached commands if you supplied a command whose size was inferior to what you said it was.
> IPC: Implement MsgVersion

- plugins/GSdx/GS.cpp
- plugins/GSdx/GS.h
- plugins/GSdx/GSLocalMemory.cpp
- plugins/GSdx/GSdx.cpp
- plugins/GSdx/GSdx.h
- plugins/GSdx/Window/GSSettingsDlg.cpp
1.6.0:
This PR:
1.6.0:
This PR:
F9 has been modified on Windows to have the following functionality:
- If the renderer in the config is D3D11, switch between D3D11 and SW
- If the renderer in the config is OGL, switch between OGL and SW
- If the renderer in the config is SW, switch between SW and the renderer returned by GetBestRenderer()
> GSdx: Purge D3D11 Software

- pcsx2/PluginManager.cpp
- pcsx2/Plugins.h
- pcsx2/gui/AppCorePlugins.cpp
- pcsx2/gui/AppInit.cpp
- pcsx2/gui/Panels/PluginSelectorPanel.cpp
Nothing too critical. I just noticed the same while loop over and over again, and figured there had to be a way to factor it out.
So I did.
If you want to loop through the plugins, pass the ForPlugins function a lambda with [&] (const PluginInfo * pi), and do everything with the plugin info from pi. If you want to loop through and halt when something is true, use IfPlugins instead, and return a bool.
I think it's more readable than:
const PluginInfo* pi = tbl_PluginInfo; do {
...
}  while(++pi, pi->shortname != NULL);
Especially since there's the weirdness that tbl_PluginInfo actually has all the plugins in it, then NULL, to cause the loop to halt, and then the memory card "plugin".
I could use to make sure it doesn't break anything, though, since I did have to make changes to anything …
> Refactor a repeatedly used plugin loop.

- nsis/SectionVersionCheck.nsh
- nsis/SharedDefs.nsh
- nsis/SharedShortcuts.nsh
- nsis/pcsx2_shared_init.nsi
Fixes #3431 
- Fixes `/D` install directory override, works for both portable and install
- Fixes `/S` silent install, defaults to install
- Adds `/?` and `/H` which show a help message with the available flags
- Adds `/NoStart` and `/NoDesktop` which respectively disable the creation of start menu and desktop shortcuts.
- Adds `/Portable`, which switches the installer over to portable mode if it is silent(`/S`) as opposed to the default mode of install.
> NSIS: Add support for command line flags and fix silent install

- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.h
It will allow to run sw blending with DATE draw which was previously
DATE_GL42 by default.
Fix #3738
> gsdx-ogl: Swap DATE_GL42 with DATE_GL45 on sw blending draw.

- pcsx2/IPC.cpp
This fixes windows only warnings about the IPC code that I hadn't picked up on until now.
> IPC: fix windows warnings

- pcsx2/x86/iR3000A.cpp
Fix wrong mappage values for ROM1, and ROM2 in recResetIOP(). 
For ROM1 is very old bug, for ROM2 is mistake from my previous PR.
> IOP: Fix recLUT_SetPage in recResetIOP for ROM1, and ROM2

- pcsx2/IopHw.cpp
Also cleaned up a bit of white space
For details please see this post: https://www.patreon.com/posts/sins-of-ps2-2001-42262496
Fixes Knockout Kings 2001 hang on boot
Based on information provided by Dobiestation author PSI.
> IOP DMA: Always fire interrupts for SIF0/SIF1

- pcsx2/gui/App.h
- pcsx2/gui/AppAccelerators.h
- pcsx2/gui/AppCorePlugins.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/GSFrame.h
- pcsx2/gui/GlobalCommands.cpp
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
This makes the recording tools a little more intuitive to use since there still is no proper documentation around it.
In the process, I found out that the current way of adding the keyboard shortcuts to the menu items would omit modifiers such as `shift`.  So I fixed that in both places.
By default wxWidget's `ToString` will return the keyboard character in it's correct case.  For example, if the bind is `Shift+p` it will be printed as such.  However, in most UI's I've seen, the key is capitalized anyway.  So I had to write a small routine to do so.
New menu options (note that the keybinds will only appear once the GS window has been opened, as this is when the majority of pcsx2's keybindings are assigned)
Existing binds are still set properly after my changes:
> GUI/Recording - Add menu items for recording controls with keyboard shortcuts.

- plugins/dev9ghzdrk/Win32/tap-win32.cpp
- plugins/dev9ghzdrk/Win32/tap.h
when ethernet is disabled we did not initialize a TAP interface so we check that we have an init'd interface before closing it
> DEV9: fix crash when closing game window with ethernet disabled

- bin/GameIndex.dbf
Fixes Character SPS.
Without it:
With the gamefix:
Probably other games who will need it, people can make issue for them that it needs them.
> GameDB: VU0 Kickstart to Beyond Good and Evil

- .github/dependabot.yml
Due to the recent CVE, our Windows workflow is now being flagged.
I've created an issue in the offending dependency https://github.com/microsoft/setup-msbuild/issues/26 and once updated, dependabot should pick it up and make a PR to update it and eliminate the CVE annotation.
> Actions: Add dependabot to automatically keep actions dependencies up to date

- plugins/GSdx/Renderers/Common/GSOsdManager.cpp
not a good fix but fixes the crashing for now.
OSD is calculating the wrong texture size and it is causing d3d11 to crash.
Note to self: replace OSD with something sane.
> gsdx-osd: fix crashing on d3d11

- pcsx2/Counters.cpp
Smooths out frame pace and keeps average framerate closer to target.
Comparing PCSX2's old framelimiter with RTSS showed there was room for improvement. Frametimes regularly would jump up and down in various situations. This PR smooths out frame pace substantially (easily visible in RTSS) and, drum roll please, may appease the input lag folks for a time. We'll find out.
Extensive user tests required; some vsync functions were shuffled around, and this was tested on a high performance system. We should test low end systems, and a wide variety of games to make sure there are no outlier games that needed the old behavior for some reason.
Shoutout to Refraction for greasing the wheels and helping with the various vsync aspects.
Before (above) and after (below) of Xenosaga Ep. 1 save point …
> Counters: Tighten tolerances on framelimiter

- pcsx2/ps2/pgif.cpp
The PGIF registers are 20 bits, but the bitmasks allowed 21 bits to be written.
> Correct PGIF Register bit masks

- bin/GameIndex.dbf
- pcsx2/Config.h
- pcsx2/IPU/IPU.cpp
- pcsx2/Pcsx2Config.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/Panels/GameFixesPanel.cpp
**Rationale:**
The hack was recently broken on master. We could fix it, but it's sort of pointless. Additionally, #3549 will break it as it forces the window to close when the renderer switches. This is desired as sharing a surface between different renderers is bad behavior.
At it's best, it offered a users a way to work around that some FMVs are not properly displayed by the HW renderer due to limitations of the cache by automatically switching to the more compatible sw renderer when they played.
At it's worst, it's a threading nightmare that barely worked and was never going to be a long term solution especially seeing as it conflicts with future changes that we would like to make.
Instead, I'll purge it and we'll work on making the HW renderer better instead of relying on a hack. …
> pcsx2: purge fmv in sw hack

- pcsx2/Sif.h
- pcsx2/Sif0.cpp
Also fix the amount of words written to temporary junk
Fixes Ghosthunter, possibly Primal which were broken in the recent SIF commit
> SIF: Fix attempting to write junk when FIFO full

- bin/GameIndex.dbf
- pcsx2/x86/microVU_Lower.inl
- pcsx2/x86/microVU_Macro.inl
Fixes Yanya Caballista running slow (patches removed)
Fixes Disney's Treasure Plantet's crazy camera (that flies off) and ground displacement. Fixes #3441
> Cop2: Make sure the status flag gets updated on DIV/SQRT/RSQRT

- pcsx2/CMakeLists.txt
I think this was broken after PR https://github.com/PCSX2/pcsx2/pull/3756.
> cmake: Fix the build without portaudio (Again).

- pcsx2/Recording/InputRecording.cpp
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
The SaveState handler in `InputRecording` is always accessible because it needs to be, even if input-recording tools are disabled.  However, the extra code within it, should not be executed if the recording tools are disabled, so I fixed that.
Also at the same time I noticed that since I didn't specify a filter for the new VirtualPad image files, they get shoved into the top level project folder so fixed that up at the same time.
> Recording: Fix VS filters on new image files and safeguards around save-state code

- pcsx2/CMakeLists.txt
- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/Recording/InputRecordingFile.cpp
- pcsx2/Recording/Utilities/InputRecordingLogger.h
- pcsx2/gui/FrameForGS.cpp
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
This adds OSD logs around input recording actions, specifically:
- Pausing (note that since its pausing emulation, the log won't show up until the next frame)
- Resuming
- Recording Mode Toggling
- Starting a new Recording
- Playing an existing Recording
- Stopping a Recording
I did not include actions for frame-advance, because it would just fill the screen with logs and as mentioned before, the log will only show up the next frame.
I also added a small logging utility header which simplifies the logging story.
> Recording: Add on-screen-display logging around appropriate Input Recording actions

- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/Recording/InputRecordingControls.h
- pcsx2/gui/AppCoreThread.cpp
I believe the intention of the cheats/settings reloading is for the conventional pause/resume from the MainFrame's menu.
However, with input recording, nothing ever actually gets closed so I doubt the settings need to be reloaded.  These changes stop that from happening on every individual frame advance.  
However, in case im wrong and it is needed, they do get re-applied when emulation is fully resumed (Shift+P by default).  This just dramatically reduces the console spam.
Now:
Before:
fyi - @sonicfind
> recording: Don't reload cheats/settings on every frame-advance

- pcsx2/gui/App.h
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- plugins/GSdx/GS.cpp
- plugins/GSdx/Renderers/Common/GSRenderer.cpp
This was a new feature that was dropped from the initial recording tools PR as it was out of scope, adding it back now https://github.com/PCSX2/pcsx2/commit/64104ca9fdeec1b5b19b26e75b5c564ed230613b
Allows you to specify where you want the screenshot to be saved via a file browser. 
This also changes GSdx to save screenshots with the `png` extension, as that is actually the compression used - https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSPng.cpp
> Add "Screenshot As..." feature to Capture options

- .travis.yml
- CMakeLists.txt
- pcsx2/CMakeLists.txt
Not quite sure why this didn't fail in actions...different cmake version?  
I pushed a commit to run Travis here as my fork's master differs in some respects (just README changes, but not risking anything this time)
Passing Travis Build - https://travis-ci.org/github/xTVaser/pcsx2-rr/builds/736561988
> CI/Travis: Fix newly introduced cmake failure in Travis-CI after adding {fmt}

- plugins/GSdx/GSState.cpp
After some tests on a PS2 it has been determined that PRIM and PRMODE are in fact not separate registers but a method of setting one register in two different ways to allow switching of environment information in the middle of triangle strips without clearing out the vertex queue.
Previously it was considered to be two separate registers to provide 2 different contexts for drawing, this however is not the case, so GSDX has been updated to reflect this.
Fixes #3258
> GS: Fix handling of PRIM/PRMODE on PRMODECONT switching

- bin/GameIndex.dbf
PSI patch ported to PAL version (PAL use the same offset). 
There is not much that can be done from pcsx2 code side without EE/DMA cycle accuracy, so... fixes #1743
> GameDB: Patch for Ecco the Dolphin PAL

- pcsx2/CDVD/CDVD.cpp
Previously iLinkId was writen/overwriten to .nvm only when user not supplied own file.
But when user supplied file with empty iLinkId, then value is never set. So games fail to get correct data.
That implementation return hardcoded ilinkId when read is requested, and correct iLinkId is not found.
fixes #2475
> CDVD: Fix iLinkId issues (.nvm)

- bin/GameIndex.dbf
1. ChaosLegion
Fixes SPS in the item menu. Found by EspeonScottie  :)
2. Dragons's lair
Fixes hang and SPS
3. Astro Boy (Atom)
Fixes character behaviour.
> GameDB: Multigamefixes (ChaosLegion, Dragons lair, Astroboy)

- plugins/GSdx/GSClut.cpp
- plugins/GSdx/GSClut.h
If testers test it they will be rehired.
GS reads lower 3 bits of PSM to determine if format is 8/4 bit and thus whether to write the clut into the clut buffer. This PR correctly emulates this behavior.
I added a log for ignored writes but I might remove it if it becomes to noisy.
[test (zip)](https://github.com/PCSX2/pcsx2/files/5427477/clut_reload.zip)
PR mimics real hw and reloads the clut for the following formats:
**As 8bit:** `0x3`, `0xB`, `0x13`, `0x1B`, `0x23`, `0x2B`, `0x33`, `0x3B`
**As 4bit:** `0x4`, `0xC`, `0x14`, `0x1C`, `0x24`, `0x2C`, `0x34`, `0x3C`
TODO: CSM2 and undocumented formats (FFX uses `0x9` as an alias for CT24)
> gsdx: properly init clut ptrs v2

- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_Execute.inl
- pcsx2/x86/microVU_Lower.inl
- pcsx2/x86/microVU_Macro.inl
Also properly normalise Status flags when exiting a VU program.
Flag instances:
Fixes State of Emergency 2 black screens and BIOS reboot and physics issues in Driving Emotion Type-S as outlined in #3694 
Status Flag Normalisation and COP2 flag clearing:
Fixes #2077 Ratchet Gladiator shadows
Finally Fixes #1638
> microVU: Save valid flag instances at the end of a VU0 program.

- bin/GameIndex.dbf
Add patches for Idea Factory games. 
Explanation by PSI: 
Games run function that initializes SIF clients associated with the MEDIA.IRX module.
It allocates an array on the stack, does some manipulation with the stack variable, then sends some data using it to the MEDIA module. One of these variables appears to be a buffer that MEDIA transfers data to - 0x2XXXXXXX - which can also be seen in the SIF0 tag when the EE cache is enabled.
The stack manipulation is the problem. If it detects that the variable is not aligned on a 64-byte boundary, it will re-align the address by subtracting (0x40 + (addr & 0x3F)) from it. This causes the stack address to be lower than the current stack pointer. When sceSifCallRpc is called, it will decrease the stack pointer and corrupt the data being sent to …
> GameDB: Add patches for Idea Factory games

- pcsx2/x86/iFPUd.cpp
This fixes https://github.com/PCSX2/pcsx2/issues/3872 and klonoa related bugs on x64.
As this eats up some bytes of cache and is unneeded on 32bit, those changes are 64bit only.
> JIT: fix FPU IEEE float conversion on x64

- plugins/GSdx/GSdx.cpp
- plugins/GSdx/Window/GSSetting.cpp
GL only, D3D11 doesn't have Full level.
It is more accurate and there likely isn't any speed impact.
Rename Fast level to Basic.
> gsdx-hw: Set Full DATE accuracy as default.

- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
d3d11: Directly calculate blend index in rendererdx11, and send the value to
SetupOM. Get rid of duplicate calculation and abcd variables.
Code is cleaner this way.
hw: EmulateBlending -> add [[fallthrough]] attribute to switch cases.
> gsdx-hw: Clean up blending code a bit.

- pcsx2/COP0.cpp
- pcsx2/IPU/IPU.cpp
- pcsx2/IPU/mpeg2lib/Mpeg.cpp
- pcsx2/Sio.cpp
- pcsx2/System/SysThreadBase.cpp
- pcsx2/Vif1_MFIFO.cpp
- pcsx2/Vif_Codes.cpp
- pcsx2/gui/AppConfig.cpp
- pcsx2/ps2/Iop/PsxBios.cpp
- plugins/GSdx/GSState.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/onepad/state_management.cpp
- plugins/onepad_legacy/state_management.cpp
Silences warnings about not having breaks on switch cases.
Added a few missing ones too.
Previously comments worked on gcc only.
> misc: Replace Fall through comments with c++17 attribute.

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSRendererDX11.h
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.h
v1 Code is identical so no need to have separate functions for gl and d3d11.
v2 Change pass integer parameter with bool that checks for pass 2.
v3 Early return when there is no testing at the start of the function.
> gsdx-hw: Move EmulateAtst in common hw renderer code.

- .travis.yml
- cmake/SearchForStuff.cmake
- travis.sh
Changes:
* Fix compilation errors due to WX and GTK mismatches.
* Update the Travis CI build (There is a temporary commit on top to test that is supposed to show that it works but seems to highlight other issues (EDIT: See https://travis-ci.org/github/turtleli/pcsx2/builds/741138728). EDIT: Temp commit has been removed.)
> linux: Fix compile issues due to wxWidgets and GTK version mismatches

- .github/workflows/scripts/linux/install-packages.sh
Tracking - https://bugs.launchpad.net/ubuntu/focal/+source/apt/+bug/1871268
I'm not familiar with Canoical's package release process, but i assume they would test something in 20.10 before rolling it to 20.04.  It seems like this issue has been resolved and is currently baking in 20.10.
> Debugging 32-bit Ubuntu Package installation Failure

- bin/GameIndex.dbf
- plugins/GSdx/GSCrc.cpp
- plugins/GSdx/GSCrc.h
- plugins/GSdx/Renderers/HW/GSRendererHW.cpp
- plugins/GSdx/Renderers/HW/GSRendererHW.h
EE patches work also in software mode. 
Note: CRC 0x137C792E seems to be some mistake. That game have only one version for US region.
Close #3175
> Replace Star Wars - Force Unleashed CRC hack with GameDB patch. 

- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Value will be read only when zclamp is enabled. It will avoid an extra upload to buffer maybe.
> gsdx-hw: Don't always set MaxDepth on ps/fs.

- CMakeLists.txt
- cmake/SearchForStuff.cmake
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: pcsx2/CMakeFiles/PCSX2.dir/gui/FrameForGS.cpp.o: in function `GSPanel::InitRecordingAccelerators()':
FrameForGS.cpp:(.text+0x4ffd): undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: pcsx2/CMakeFiles/PCSX2.dir/Recording/InputRecording.cpp.o: in function `inputRec::consoleLog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
InputRecording.cpp:(.text+0x1685): undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)' …
```
> Support build with system fmt

- pcsx2/Counters.cpp
- pcsx2/GS.cpp
timing adjustments for double strike analog modes
fixes #450
> counters: account for vertical frequency differences in non-interlaced anolog modes

- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/Window/GSSettingsDlg.cpp
Aniso filtering doesn't work with textureLod so use texture
(automatic_lod) instead.
Credits to KrossX.
Note: Won't work on AMD because the driver is broken.
> gsdx-ogl: Fix anisotropic filtering.

- cmake/BuildParameters.cmake
- pcsx2/DEV9/flash.cpp
- pcsx2/DebugTools/DisassemblyManager.h
- pcsx2/SPU2/spu2replay.cpp
- pcsx2/SPU2/wx/wxConfig.h
- pcsx2/USB/USB.cpp
- pcsx2/USB/configuration.cpp
- pcsx2/USB/linux/config-gtk.cpp
- pcsx2/USB/qemu-usb/USBinternal.h
- pcsx2/USB/qemu-usb/usb-ohci.cpp
- pcsx2/USB/shared/inifile_usb.cpp
- pcsx2/USB/shared/ringbuffer.h
- pcsx2/USB/usb-eyetoy/cam-linux.cpp
- pcsx2/USB/usb-hid/evdev/evdev-gtk.cpp
- pcsx2/USB/usb-hid/evdev/evdev.cpp
- pcsx2/USB/usb-hid/usb-hid.cpp
- pcsx2/USB/usb-mic/audiodev-pulse.cpp
- pcsx2/USB/usb-mic/audiodev-pulse.h
- pcsx2/USB/usb-mic/usb-headset.cpp
- pcsx2/USB/usb-msd/usb-msd.cpp
- pcsx2/USB/usb-pad/evdev/evdev-ff.cpp
- pcsx2/USB/usb-pad/evdev/evdev-gtk.cpp
- pcsx2/USB/usb-pad/evdev/evdev.cpp
- pcsx2/USB/usb-pad/evdev/shared-gtk.cpp
- pcsx2/USB/usb-pad/joydev/joydev.cpp
- pcsx2/USB/usb-pad/usb-seamic.cpp
- pcsx2/gui/AppAccelerators.h
- plugins/onepad/wx_dialog/JoystickConfiguration.h
Clean up various warnings, largely in the recently merged USB code. Unused variables have had [[maybe_unused]] added or been deleted, various variables were cast due to sign mismatches, member variables were rearranged in places to match the class initialization, and so on.
This brings the warnings in gcc and clang down to a much more reasonable level.
I ignored several warnings along the line of:
../pcsx2/USB/USB.cpp:520:10: warning: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
520 |   strncpy(usbd.freezeID, USBfreezeID, strlen(USBfreezeID));
As well as various preexisting warnings (Such as Lilypad doing sizeof on a pointer :P ).
> [USB+] Clean up Warnings

- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
gsdx-ogl: Check MinMax for PSConstantBuffer.
Fixes #2871
> GSdx-ogl: Check MinMax for PSConstantBuffer.

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD.h
- pcsx2/R5900OpcodeImpl.cpp
- pcsx2/R5900OpcodeTables.h
Should fix bad fonts when booting a game fast
Selects correct language for games depending on your BIOS setting when using fast boot
Stops games such as Guitar Hero 2 from crashing on fast boot.
PR also now corrects timezones in games.
Fixes #480
> BIOSHLE: Use BIOS settings on fastboot

- pcsx2/R5900.cpp
Workaround for delay slot for ERET, and SYSCALL opcodes in isBreakpointNeeded/isMemcheckNeeded. Currently pcsx2 debugger treat next instruction as a delay slot, which is wrong behavior. 
Before: 
After:
> Debugger: Remove delay slot for ERET and SYSCALL opcodes

- pcsx2/Patch.h
- pcsx2/System/SysCoreThread.cpp
There is no real reason to make the behavior of type-{0,1} pnach different on load. Keeping the behavior consistent not only makes more sense but also avoids some weird edge case we could run into.
> PNACH: New patch type: apply repeating codes also on load

- .github/workflows/linux-workflow.yml
- .github/workflows/scripts/linux/generate-cmake.sh
- common/include/Utilities/SafeArray.h
- common/include/Utilities/pxEvents.h
- common/include/x86emitter/tools.h
- pcsx2/Config.h
- pcsx2/PathDefs.h
- pcsx2/Plugins.h
- pcsx2/USB/configuration.h
- pcsx2/USB/linux/config.cpp
- pcsx2/USB/usb-eyetoy/cam-linux.cpp
- pcsx2/USB/usb-hid/evdev/evdev.h
- pcsx2/USB/usb-msd/usb-msd-gtk.cpp
- pcsx2/USB/usb-pad/evdev/evdev.h
- pcsx2/USB/usb-pad/joydev/joydev.cpp
- pcsx2/USB/usb-pad/joydev/joydev.h
- pcsx2/gui/AppConfig.h
- pcsx2/gui/pxEventThread.h
- plugins/GSdx/GSVector4i.h
- Adds a no-pch build to GitHub Actions
- Switches GitHub Actions from a matrix to a main x86 gcc build plus each of the other options with only the one change (so there's an x86 clang build, x64 gcc build, but no x64 clang build or no-pch clang build)
- Makes GitHub Actions use ccache properly (important as the no-pch build takes like 20 minutes)
- Disables march=native for GitHub Actions builds (required for ccache)
- Fixes #3096 (build failure with Clang + SSE2)
Note: An alternative fix for clang SSE2 is to flex our C++17ness and use `if constexpr`.  Preferences?
> Add no-pch build to GitHub Actions

- cmake/BuildParameters.cmake
-Wno-format-security is required on top of -Wno-format, otherwise our compiler defaults to thinking we enabled format-security but not format and craps itself.
-Wno-overloaded-virtual is only for objc and is used when, eg, trying to compile test programs, which didn't help the situation.
> CMake: fix generation due to warnings treated as errors

- cmake/SearchForStuff.cmake
- pcsx2/CMakeLists.txt
- pcsx2/USB/usb-mic/api_init_linux.cpp
Fixes the build when pulseaudio is not installed. Sound when playing games still works fine.
> Fix build without pulseaudio.

- pcsx2/SPU2/Dma.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2sys.cpp
- pcsx2/SaveState.h
Fixes The Simpsons, the game does a DMA read of the Core 0 output in memory, but because the DMA is instant it overruns the core updating memory, so we will delay the DMA read until the estimated time has passed.
Fixes #3937
> SPU2: Delay DMA Reads to prevent overrun

- pcsx2/FiFo.cpp
- pcsx2/Vif.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif_Transfer.cpp
Also don't decrement/change VIF1 QWC on VIF1 FIFO write
This involves removing an old VIF reset hack which was put in for Donald Duck Quack Attack, but doesn't seem to be needed anymore (game uses T-Bit on VU which has been fixed since this hack was placed in and could likely have been the problem)
Fixes #3954
> MFIFO: Maintain VIF DMA status and Empty condition on VIF reset

- bin/GameIndex.dbf
- pcsx2/Dmac.h
- pcsx2/Gif.cpp
- pcsx2/IPU/IPUdma.cpp
- pcsx2/Vif0_Dma.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif1_MFIFO.cpp
- pcsx2/ps2/LegacyDmac.cpp
This removes 2 hacks on the IPU for Enter the Matrix and Mana Khemia
On the PS2 is a NORMAL DMA transfer is started with QWC 0, the DMA overflows and transfers another 0xFFFF quadwords on top of the underflowed one, this correctly emulates that.
I did have to do a "kind of" hack to make Mana Khemia work properly, the game relies on the IPU to take some time to decode macroblocks, but we handle them instantly, so I had to place an artifical delay on starting the DMA to let it catch up and do what it needs to do. It shouldn't have any negative impacts.
> DMA: Correctly emulate QWC 0 on NORMAL transfers

- pcsx2/IPU/IPU_Fifo.cpp
- pcsx2/IPU/IPUdma.cpp
Fixes bad slowdowns in Ratchet games when using EE Timing fix caused by bad IPU streams
> IPU: Stop IPU0 looping when there's no data for it to read

- pcsx2/MTVU.cpp
- pcsx2/SaveState.h
- pcsx2/VU.h
- pcsx2/VU0micro.cpp
- pcsx2/VU0microInterp.cpp
- pcsx2/VU1micro.cpp
- pcsx2/VU1microInterp.cpp
- pcsx2/VUmicro.h
- pcsx2/Vif_Codes.cpp
- pcsx2/x86/microVU.cpp
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_Tables.inl
Also fix some M-Bit stuff to reduce programs created and fix them happening on branches.
Hopefully shouldn't be much in the way of compatibility changes, but should cut down the recompilation of MicroVU0 programs due to the change in how VU0 operates and how things are going to work going forward. MGS3 went down from 115 (and climbing) to around 13. Crash Twinsanity went down from 32 by the main menu to about 15.
This also sets up some future work of synchronising VU1
Savestate version bump due to new parameter
Also fixes a bug in VIF when using MTVU, fixes Def Jam Fight for NY when using MTVU, maybe others.
> mVU: Keep start PC, modify prog search to avoid recompilation + MTVU bug

- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/gui/MainMenuClicks.cpp
This gets around users having crashes because they haven't configured the language in their BIOS
Expected behaviour: First time you run this version it will ask you to configure then force a full boot, next time (and subsequent times) it will fast boot as normal, including if you shut down the emulator.
> GUI: Force Full Boot on first run of new version

- plugins/GSdx/GSState.cpp
Removes some code that was meant to correct a condition on the GS where 8-bit and 4-bit formats are assigned a buffer width that is not divisible by 2. Given that the code just forced it to be even (almost certainly not correct) and was some kind of workaround dating back 13 years I'm opting to remove it. If someone can give me an example of a game that is broken without this code I'll look into it again but it seems like a fairly rare condition. The examples I could find aren't particularly interesting:
- namcoXCapcom doesn't appear to have any problems absent this code and no one documented the problem to begin with so it's near impossible to track down. If anyone can point me to an issue in this game I'd appreciate that.
- Geomon is clearly broken regardless of this code and spams a …
> GSdx: Remove some broken buffer width correction code

- pcsx2/USB/USB.cpp
When the address is equal to the max value of a unsigned integer, this check will overflow leading to a false negative and crashes PCSX2 when we then try to read that address.
Cast addr to a 64bit integer to enforce a 64bit comparison.
This issue occurs when launching a game via OPL (tested OPL version was 1020)
> USB: Fix integer overflow on IOP memory range check

- pcsx2/Vif0_Dma.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif1_MFIFO.cpp
Also Fix missing VIF status check on MFIFO
Fixes hang in Batman Vengeance, game stalls the VIF during an MFIFO transfer then stops and starts VIF while it's stalled, in the old code this causes it to ignore the stall and continue as normal, this PR fixes that behaviour.
> VIF: Don't start transfer if VIF1/0 is stalled

- bin/GameIndex.dbf
- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD_internal.h
Fixes Shadowman 2 Second Coming textures
Fixes Arctic Thunder loading problems
Fixes looping music on ONI title screen and skipping dialogues
Fixes Klonoa 2 missing audio
Fixes SPS at the beginning of matches in Next Generation Tennis 2003 (Ronald Garros) - This one surprised me too
Original comments mentioned Silent Hill 2 being starved during videos, but seems fine to me, but if somebody could test further in to the game, that'd be great.
Edit: It does cause the second video (and later ones) to hang, however this isn't being starved of data, I can run the CDVD at 0.3x the normal speed and it works, so there's some sort of annoying timing issue going on.  Can be gotten around by setting the EE cycle rate to -1 or enabling the Fast CDVD speedhack
Edit 2: Okay Silent Hill 2 seems to be …
> CDVD: Adjust read speed depending on if in inner/outer edge

- bin/GameIndex.dbf
- pcsx2/COP2.cpp
- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/R5900.cpp
- pcsx2/VU0.cpp
- pcsx2/VU1micro.cpp
- pcsx2/VUmicro.cpp
- pcsx2/VUmicro.h
- pcsx2/Vif0_Dma.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif1_MFIFO.cpp
- pcsx2/Vif_Codes.cpp
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppCoreThread.cpp
- pcsx2/gui/Panels/ConfigurationPanels.h
- pcsx2/gui/Panels/SpeedhacksPanel.cpp
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_Macro.inl
This synchronises VU1 with the EE and VU0 (as close as we can).  A new speedhack has been added to replicate the old behaviour, which is on by default unless you're using the Safest preset.  Games which require the new behaviour have an entry in the GameDB to disable it.
Fixed Games:
Fixes SPS in Shadowman 2encond Coming
Fixes "Noodles" in Parappa the Rapper 2 (box in the top left)
Fixes floor corrupt textures and console error spam in Dropship
Slightly improves World series baseball 2k3 but it's still broken, just doesn't run at sub 1fps anymore
Broken Games:
Wakeboarding unleashed will only boot with MTVU enabled for now, however there's a hack in the code (disabled) which can fix the booting problem and fixes the waves in the game (with MTVU off and VU1 Instant off), will add it as a …
> VU: Synchronise VU1, added speedhack for old behaviour

- common/include/x86emitter/x86types.h
- common/src/x86emitter/jmp.cpp
- common/src/x86emitter/x86emitter.cpp
- pcsx2/x86/ix86-32/recVTLB.cpp
- pcsx2/x86/microVU_Lower.inl
The virtual method dispatch made it incredibly hard to make a method return a register with a dynamic size from a method, as to be a dynamic size the register would have to be a pointer, which meant someone had to hold on to the memory.  This resulted in the xRegister64 having to hold an xRegister32 with the same ID inside of it, just to return a pointer to in the off chance that someone called `GetNonWide()`, along with some fairly messy code in the xLEA implementation to attempt to match the sizes of two registers
In addition, this meant that an `xRegisterLong` was 32 bytes on x86-64 (8 byte vtable, 4 byte ID, 4 bytes padding, 16 byte xRegister32) compared to just 8 bytes on x86-32 (4 byte vtable, 4 byte ID), leading to an increase in stack overflows in compilers that weren't very good …
> x86emitter: register class improvements

- pcsx2/gui/GlobalCommands.cpp
- pcsx2/gui/MainMenuClicks.cpp
Fixes recording keybind menu options not disabling when `pause` is selected or when the `ESC` key is used (a consequence of the "Close All Windows" fix). Once a more long-term fix for it can be done - these can be removed.
> GUI: Apply missing recording menu option disablers

- pcsx2/SPU2/Windows/Config.cpp
This will change the jumps from 42 to 5, scroll wheel will still be 2 and all the arrows keys on 1. If you click and hold and  then move just outside of the slider you now get nice jumps of multitudes of 5. It will affect the value for pagesize which is the number of steps the slider moves when the user pages up or down. Taking a part from #3787
> SPU2: Change VolumeSteps from 42 to 5

- pcsx2/Gif_Unit.cpp
- pcsx2/Gif_Unit.h
- pcsx2/MTVU.cpp
- pcsx2/MTVU.h
- pcsx2/SaveState.h
- pcsx2/VUmicro.cpp
PR Attempts to improve compatibility with games that use FINISH/SIGNAL/LABEL on the GS through VU1 when using MTVU. 
Performance impact is reasonably minimal, within a couple of percent of master.  Although I cannot guarantee the reliability although it looks good, it's a huge improvement and a vast majority of the games listed are now playable with MTVU.
If a game does a double SIGNAL, that still won't work.
Fixed Games when using MTVU:
Backyard Basketball
Baroque
Batman: Vengeance
Crash Nitro Kart
Gradius V
Heatseeker
King's Field IV
Marvel Ultimate Alliance
Medal of Honor: Rising Sun
MTVs Celebrity Deathmatch
Summon Night Gran-These: Horobi no Ken to Yakusoku no Kishi
Tony Hawk games
X-Men Legends 2
Yu-Gi-Oh! Capsule Monster Coliseum
Slowdown in games using MTVU Fixed:
007 Agent Under …
> MTVU: Improve compatibility with games that do GS SIGNAL/LABEL/FINISH

- pcsx2/GS.cpp
Puts in the correct behaviour for GS reads.
To my knowledge fixes nothing but Supadoopa's Funslower demo.
Fixes #1307
> GS: Properly mirror GS reads to CSR

- pcsx2/DEV9/Win32/tap-win32.cpp
- pcsx2/DEV9/Win32/tap.h
- pcsx2/DEV9/net.cpp
- pcsx2/DEV9/net.h
As above, only deals with the issue on windows.
winPcap (and thus Linux) needs to be looked at separately (and also isn't fixed on CLR_DEV9)
The implementation of the fix differs from what CLR_DEV9 does as I mostly used C#'s filestream, instead of direct Win32 calls.
This should speed up closing rx thread significantly.
I've only done minimal testing, just fyi
> DEV9: Cancel read of TAP device on suspend/shutdown

- pcsx2/Gif_Unit.cpp
- pcsx2/MTVU.cpp
- pcsx2/MTVU.h
- pcsx2/SaveState.h
Fixes atomic usage and ensures all communication goes in one direction
Also removed some forced 4-byte alignment, for 4-byte types it's unnecessary and for 8-byte types it's either unnecessary or harmful
> MTVU: Clean up GS SIGNAL/LABEL/FINISH communication

- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecording.h
- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
One of the problems with the current implementation was that it never accounted for a failed savestate load. If you were to load a recording that was based on a savestate that no longer works (corrupted or outdated), the emulator would not know to cancel loading the recording. This now accounts for that by forcing most input recording elements to wait until confirmation.
> Properly cancel an input recording on a bad initial savestate

- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecording.h
- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/Recording/PadData.h
The call for the virtualPads to redraw their visual assets originally required for the sio to provide a `bufCount` of **20** to `controllerInterrupt` - the last value index used for polling controller data (reinterpreted as **17**). However, for some of the games that do not utilize button pressure, that value will only ever reach a max of  **8** (Ex: Sonic Mega Collection Plus); consequently, the virtual pad will never be drawn.
By unhooking the padData logging and virtualPad redrawing from this conditional and instead calling it from a static location, both will now occur regardless of max `bufCount` value. `ControllerInterrupt` was also rearranged to allow virtualPads to be utilized outside of the limited frame window of an input recording (with limitations in record mode).
> recording: Resolve VirtualPads not drawing for some games

- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecording.h
- pcsx2/Recording/InputRecordingFile.cpp
- pcsx2/Recording/InputRecordingFile.h
- pcsx2/Recording/NewRecordingFrame.cpp
- pcsx2/Recording/NewRecordingFrame.h
- pcsx2/gui/App.h
- pcsx2/gui/AppInit.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainMenuClicks.cpp
Simplifies virtualPad access by solely holding the virtualPad window pointers in the g_inputRecording object. This will be useful later down the line when more virtualPads are added.
NewRecordingFrame has improved functionality:
* Users can now only choose to create a savestate-based recording if GS is open.
* Forced file browsing in certain situations.
Also, forces a game to have been loaded before being allowed to mess with input recordings.
> pcsx2-gui: Internalize VirtualPad and Upgrade NewRecordingFrame

- bin/GameIndex.yaml
- pcsx2/IPU/IPU.cpp
- pcsx2/IPU/IPU.h
This is based on the work by @PSI-Rockin on Dobiestation but modified based on my theory that it always returns the first 32bits of the FIFO unless an FDEC/VDEC command is executed, however FDEC is basically doing this anyway, but VDEC returns decoded information.
Fixed videos for probably all broken EA games, but namely:
F1 2001
F1 2002
Neo Contra
Shox
Theme Park Rollercoaster/World
Unrelated PR but a note for myself when removing video skip patches for games which are no longer broken:
Simple 2000 Series Vol.59 - The Uchyujin to Hanashi Sou!
> IPU: Return contents of the bottom of the FIFO in CMD except FDEC/VDEC

- pcsx2/IopCounters.cpp
- pcsx2/IopDma.cpp
- pcsx2/SPU2/Dma.cpp
- pcsx2/SPU2/ReadInput.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2.cpp
- pcsx2/SPU2/spu2sys.cpp
Fixes The Simple 2000 Series Vol 51 - The Senkan (AKA The Battleship) which was not booting with anything but ZeroSPU2
Fixes The Simpsons (For real) problem was due to an ADMA refill bug.
Don't know what other games will be affected.
> SPU2: Improve DMA/IRQ timing.

- pcsx2/SPU2/Mixer.cpp
- pcsx2/SPU2/SndOut_Portaudio.cpp
WASAPI is terrible and doesn't support sample rate conversion in shared (normal) mode and requires exclusive mode.
This PR basically attempts to double the PS2 sample rate of 48khz to 96khz as this tends to be the other windows default.  If this fails it will put a log message to say you need to use Exclusive mode.
Note: When using PS1 game emulation you will need to use exclusive mode, nothing I can do about this (44.1khz doesn't divide nicely from 48khz or 96khz)
> SPU2: Attempt 96khz sample rate if 48khz fails (WASAPI)

- pcsx2/GameDatabase.cpp
- pcsx2/GameDatabase.h
This was a mistake from the original migration, for some reason i thought this list was comma delimited but no, it's slash delimited.
I tested via RaC3, with this fix, i was able to load my save files successfully.  Also nicely cleans up the `join` logic thanks to `fmt`.
Resolves - https://github.com/PCSX2/pcsx2/issues/4098
> gamedb: Delimit memcard filters with '/' instead of ','

- pcsx2/gui/MemoryCardFolder.cpp
Don't keep the DataClusterInUse bit when accessing the next cluster.
With this folder memcards work on 64bit, but I'm confused why they would have worked on 32bit in the first place.
fixes #3839
> Fix out of bounds array access in folder memcards

- pcsx2/DebugTools/Breakpoints.cpp
- pcsx2/DebugTools/Breakpoints.h
- pcsx2/DebugTools/DebugInterface.cpp
- pcsx2/DebugTools/DebugInterface.h
- pcsx2/Interpreter.cpp
- pcsx2/R3000A.cpp
- pcsx2/R3000A.h
- pcsx2/R5900.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/Debugger/BreakpointWindow.cpp
- pcsx2/gui/Debugger/CtrlDisassemblyView.cpp
- pcsx2/gui/Debugger/DebuggerLists.cpp
- pcsx2/gui/Debugger/DisassemblyDialog.cpp
- pcsx2/x86/iR3000A.cpp
- pcsx2/x86/ix86-32/iR5900-32.cpp
Breakpoints on the IOP will now actually break, and you can now step through it and shizz. I've only implemented this on recompiler, and not the interpreter.
Fixes #1746
> Implements IOP breakpoints

- pcsx2/gui/AppCorePlugins.cpp
SysExecEvent_SaveSinglePlugin would close the plugin, but not reopen it
Should fix the issue of lilypad input breaking after configuring during emulation
Fixes #3989
> Core: Plugin resume after configure

- pcsx2/DEV9/Win32/tap-win32.cpp
- pcsx2/DEV9/net.cpp
- pcsx2/DEV9/net.h
- pcsx2/DEV9/pcap_io.cpp
A unique MAC is needed for full compatibility with XLink Kai.
Uses a method similar to what was done for pcap.
> DEV9: Generate unique MAC for TAP

- pcsx2/USB/shared/rawinput_usb.cpp
Currently the console is a little cluttered by these messages that are useless and essentially meaningless to the end-user:
```
******      WM_KILLFOCUS        ****** 00040328
******      WM_SETFOCUS        ****** 00040328
```
I believe that shifting these messages to the Dev console is harmless and tidies up console output a little.
> rawinput_usb.cpp: removed unused WM_ACTIVATE/SETFOCUS/KILLFOCUS logging

- .github/workflows/windows-workflow.yml
Add PR title if applicable, limit the length of the file to avoid file-name length issues.
Also put all contents of the artifact into a folder with the same name to simplify extraction.
> ci: Improve windows artifact naming

- bin/GameIndex.yaml
Pal region, SCES-52677
Without the speedhack, I see this;
With the log getting spammed with `Gif Unit - GS packet size exceeded VU memory size!`
With the speedhack, it renders correctly and with no log spam. So add it to the gameDB.
> GameDB: 'Network Access Disc & Hardware - Online Arena' needs InstantVU1

- bin/GameIndex.yaml
- pcsx2/gui/Panels/GameFixesPanel.cpp
- pcsx2/ps2/LegacyDmac.cpp
Aim of this PR is to adjust how the DMA Busy hack works to deal with some DMA issues (described later)
Pilot Down Behind Enemy Lines is the main focus of this PR, the game starts important DMA transfers off then almost immediately overwrites the DMA information.  Either the DMA is has internal handling for the current transfers (this the registers are ignored until later transfers) or the game expects the DMA to maintain bus control before it overwrites the information.  Currently I'm unsure how to fix this properly, so I have adjusted the DMA hack to wait until the current transfer has finished. 
Handling of IPU is a tricky one, but because IPU_FROM pauses when there is no data waiting, it's possible that the QWC register gets rechecked once the transfer restarts, however I believe the …
> GameFix: Adjust function of DMA Busy hack

- pcsx2/Counters.cpp
- pcsx2/MTGS.cpp
- pcsx2/gui/Panels/ConfigurationPanels.h
- pcsx2/gui/Panels/VideoPanel.cpp
New UI option (ini option has been there a while) so users can choose between a little bit extra performance or better input lag. Also added the PAD Update to the VSync call in Counters as it seemed to improve Input lag marginally.
Improves #3008
> PAD/Counters: Make VSync Queue adjustable in the UI. Extra Pad update.

- .github/workflows/macos-workflow.yml
Homebrew periodic cleanup and containers don't mix well, as the "every 30 days" turns into "every time", ends up wasting 1-2m of build time
> ghactions:macos: Disable homebrew cleanup

- pcsx2/SPU2/Mixer.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2sys.cpp
- pcsx2/SaveState.h
This algorithm comes from pcsxr and is an implementation of Dr. Hell's research. It's supposed to be very accurate.
Bumps savestate because of new SPU core struct members.
The previous implementation was a simple LFSR and did not use the provided noise clock from the ATTR register.
> SPU2: Switch to a more accurate noise algorithm

- pcsx2/System/SysCoreThread.cpp
- pcsx2/System/SysThreadBase.cpp
- pcsx2/gui/AppCoreThread.cpp
Turns out there is more to CDVD than just DoCDVDOpen()
Hopefully this fixes #4119, and doesn't break anything else.
> Core: Attempt to fix CDVD regression

- pcsx2/CMakeLists.txt
- pcsx2/DEV9/ATA/ATA.h
- pcsx2/DEV9/ATA/ATA_Info.cpp
- pcsx2/DEV9/ATA/ATA_State.cpp
- pcsx2/DEV9/ATA/ATA_Transfer.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdExecuteDeviceDiag.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdPIOData.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdSMART.cpp
- pcsx2/DEV9/ATA/Commands/ATA_Command.cpp
- pcsx2/DEV9/ATA/Commands/ATA_SCE.cpp
- pcsx2/DEV9/ATA/HddCreate.cpp
- pcsx2/DEV9/ATA/HddCreate.h
- pcsx2/DEV9/DEV9.cpp
- pcsx2/DEV9/DEV9.h
- pcsx2/DEV9/Linux/Config.cpp
- pcsx2/DEV9/Linux/Linux.cpp
- pcsx2/DEV9/Linux/dev9.ui
- pcsx2/DEV9/Win32/DEV9WinConfig.cpp
- pcsx2/DEV9/Win32/DEV9ghzdrk.rc
- pcsx2/DEV9/Win32/Win32.cpp
- pcsx2/DEV9/Win32/resource.h
- pcsx2/DEV9/flash.cpp
- pcsx2/DEV9/net.cpp
- pcsx2/DEV9/pcap_io.cpp
- pcsx2/DEV9/smap.cpp
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
This is mostly the code from CLR_DEV9, with some tweaks and changes that I spotted during the porting process.
While CLR_DEV9 had split the speed emulation into a separate file, I chose to not do so for bringing in my changes to the speed code.
The emulator will auto create the file if it is missing
As a todo list
> DEV9: Add HDD emulation

- pcsx2/R5900OpcodeImpl.cpp
This fixes #2865 
This makes the syscall iterate through the format string which can be considered "slow" but this syscall is only going to be used for debugging purposes anyways :) 
Works with my little crude example program
> Core: Implement proper %s handling for syscall 117 (0x75)

- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/GSFrame.h
- pcsx2/gui/MainMenuClicks.cpp
Prior to this, if you enabled input recording after already having the GS window open, the title bar would continue to use it's slow default until you restarted the entire emulator.
This fixes that, and also should put the frequency back down when disabled.
To test this, you don't need to even do any recording, the speed difference should be obvious.  These steps should cover most cases:
- Open Game > Enable Recording Tools > Title should update quickly.
- Disable Recording Tools, title should go back to being slow
- Restart Emu > Disable Recording Tools > Open Game > Title should update slowly
- Restart Emu > Enable Recording Tools > Open Game > Title should update quickly
> recording: Update the GS Frame's freq. properly on enabling/disabling input recording

- pcsx2/SPU2/Mixer.cpp
Neither the output buffer nor OutX should use this crest calculation thing. It was probably implemented in the first place because of confusing terminology in the manual.
> SPU2: Fix pitch modulation

- cmake/Translation.cmake
- pcsx2/CMakeLists.txt
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppInit.cpp
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/i18n.cpp
MacOS was using linux paths rather than wx's macOS-specific subclass, which doesn't match how the app is installed in macOS (all paths should be relative to the executable).  Also adds steps to copy missing resources into the app bundle
Specific changes: 
- Save directory to `~/Library/Application Support`
- Localization files now included
- GameIndex.yaml now included
> Fix paths on macOS

- pcsx2/SPU2/Dma.cpp
- pcsx2/SPU2/ReadInput.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2.cpp
- pcsx2/SPU2/spu2sys.cpp
- pcsx2/SaveState.h
Seems to have a positive impact on The Simpsons (I know I keep saying this)
Hopefully improves the crackling in burnout 3, Fixes #2341
Apparently fixes music looping in Ratatouille
Fixes #3846 Vexx clicking sound (Partial ADMA transfers)
Fixes the Dolby Pro Logic video missing sound in Primal (Partial ADMA transfers)
Splinter Cell panning audio problem and high pitched noises in cutscenes, Fixes #2056
Myst 3 panning audio problem, Fixes #4160
Dynasty Warriors 5 stuttering videos when Dolby is enabled
If you have any other games which had constantly crackly audio or missing audio, especially in videos, this might help.
> SPU2: Improve ADMA behaviour/timing

- pcsx2/x86/microVU_Lower.inl
Someone accidentally used bad function to analyze ESIN opcode on microVU, that generated bad values due to wrong register field being used. This Pr fix it. 
Fixes #4081
> microVU: Fix Esin opcode

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CdRom.cpp
This is a quick PR to remove the incorrect and since unused reset function for ps1 mode that was commented out in CDVD as well as to clean up log statements in CDVD and cdrom
> ps1 mode: Logging and old code cleanup

- pcsx2/SPU2/Mixer.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2sys.cpp
- pcsx2/SaveState.h
Also delay key on events by 2T, tested on hardware and this seems to be the case.
Savestate bump again
Fixes behaviour with loop address writes within 4T's of a voice keying on which is what the old Delay Cycles tried to address, if the voice sets its own loop point the write from hardware is ignored.
Fixes Mafia music loops.  Fixes #4159
> SPU2: Ignore LSAL/H Writes after key on if voice sets loop point

- pcsx2/SPU2/Mixer.cpp
- pcsx2/SPU2/defs.h
Caching blocks of ADPCM is a bit sketchy because the previous samples (which it uses to generate the new ones) can change depending on if it's the start of the voice on or if it has looped around, so you can end up with blips and glitches in the sample stream, this should avoid that problem whilst not making the cache completely unusable.
Should get rid of clicking and popping noises in loops samples.
Fixes #4197
Also fixes remaining blips in Vexx
> SPU2: Make sure cache hits match previous block decoded samples

- pcsx2/PAD/Linux/wx_dialog/GamepadConfiguration.cpp
- pcsx2/PAD/Linux/wx_dialog/GamepadConfiguration.h
- pcsx2/PAD/Linux/wx_dialog/JoystickConfiguration.cpp
- pcsx2/PAD/Linux/wx_dialog/JoystickConfiguration.h
On macOS it prevents the parent window from regaining focus
Also, JoystickConfiguration had an incredibly complicated system for setting preferences as the user clicked checkboxes and undoing them if they clicked cancel.  Replaced with just setting preferences at the end if the user clicks `OK`
> Don't `Destroy()` modals

- pcsx2/SPU2/Mixer.cpp
These seems to be have been adjusted to match the output of catmull-rom
which is really the one in the wrong by being twice as loud.
As a result of the the interpolated output being at a reasonable level
we can use ApplyVolume to apply the ADSR volume.
> SPU2: Adjust interpolation implementations.

- plugins/GSdx/Renderers/DX11/GSDevice11.h
- plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp
- plugins/GSdx/Renderers/DX11/GSTextureFX11.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.cpp
- plugins/GSdx/Renderers/OpenGL/GSDeviceOGL.h
- plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
- plugins/GSdx/res/glsl/tfx_fs.glsl
- plugins/GSdx/res/tfx.fx
Both hw renderers, dx11 maybe less, depending if blending is free.
Fixes #4181 
Fixes Strawberry Shortcake character lighting.
Fixes Cartoon Network Racing shadows.
Credits to Kojin.
> gsdx-hw: Implement per pixel alpha blending (PABE).

- pcsx2/DEV9/DEV9.cpp
- pcsx2/DEV9/DEV9.h
- pcsx2/DEV9/Linux/Linux.cpp
- pcsx2/DEV9/Win32/Win32.cpp
- pcsx2/DEV9/net.cpp
- pcsx2/DEV9/net.h
Previously, the ethEnable config value was not checked before starting network RX net thread.
This PR merges the platform specific  ``_DEV9open()`` into``InitNet()``, ``_DEV9close()`` into ``TermNet()`` and adds a check before calling InitNet()
> DEV9: Merge _DEV9*() functions into *Net(), and check ethEnable before calling InitNet()

- common/include/PS2Eext.h
- pcsx2/DEV9/DEV9.h
- pcsx2/DEV9/Linux/Linux.cpp
wx (and GTK iirc) will crash on Linux if a dialogue box is shown off the UI thread (even a modal dialogue)
This doesn't seem to be an issue on windows, as it appears to allow modal dialogues to be shown off the UI thread.
Not sure if there is a cleaner way of doing this, but it gets the job down.
fixes https://github.com/TheLastRar/CLR-DEV9/issues/35 (No this wasn't a CLR_DEV9 issue afaik, despite being opened there)
> DEV9: Fix crash on Linux when we fail to open the adapter

- pcsx2/ps2/pgif.cpp
PS1DRV handles bit 28 of GPU Status register, not PGIF. This fixes several games.
> PGIF- Fix Castlevania SoTN

- plugins/GSdx/Renderers/OpenGL/GSTextureOGL.cpp
Wasn't properly changed when `Large framebuffer -> !Conservative buffer allocation`
> GSdx: Update OOM message for Conservative buffer allocation

- bin/GameIndex.yaml
I was expecting to add some more serials to SLUS (NTSC) but it seems to be more well maintained than the SLES (PAL). Most additions are demos but there are some normal full entries . Minor fixups on SLUS and other regions for names.
> GameDB: Cleanup names ( + add serials)

- pcsx2/CDVD/CDVD.cpp
This pr HLEs the temperature command of the mechacon and returns a fixed value instead of spitting out "**Unknown Mecacon Command**..."
After a lot of thought, 30.5 C is the optimal temperature for pcsx2.
> CDVD: Implement mechacon command 0xEF

- pcsx2/SPU2/Reverb.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2sys.cpp
- pcsx2/SaveState.h
The reverb runs at half the the samplerate of the rest of the SPU so a change of samplerate is required. They way this is currently done is by decimating when downsampling and duplicating samples when upsampling without doing any filtering.
This adds proper filtering to this process,  the filter coefficients are from mednafen but I *think* they were originally found by Neill Corlett.
I have not yet compared to real PS2 behavior and don't know when I'll get around to so I'm PR'ing this now.
> SPU2: Resample reverb input/output.

- pcsx2/IPU/IPU.cpp
Fixes Dance Summit 2001 - Bust a Move
So basically what the game does is it does some IPU stuff, but the DMA is left with 1 QWC left to be read on the DMA, on the hardware this will normally be flushed in to the FIFO.  The game then does a FIFO reset (To get rid of it) then starts another DMA.
The problem we have is because we still had the DMA pending for 1 QWC, it ignored the new DMA start and the IPU would hang up waiting for data to be fed in.  This PR resolves that problem.
Also added DMA 4 (To IPU) being flushed if BCLR is called without first stopping the DMA, fixes Test Drive
Set the Picture type on VDEC to I-Picture if set to 0 in the IPU_CTRL, this fixes a bunch of Eyetoy games which incorrectly set this register.
Fixes #3432 
Fixes #4125
Fixes #3700
Fixes #1863
> IPU: Fill Input FIFO on command end ready for next command

- pcsx2/gui/AppConfig.cpp
Reapplies the currently applied vsync mode when changing preset options, same as what we already do for the framelimiter setting.
Blocked by #4005 
Closes #4183
> Prevent Vsync setting from being wiped on preset changes

- bin/GameIndex.yaml
Description by kojin: 
Fix for Depth precision.
Game fills upper 16bits of depth with 0xFFFF.
This results in a really high 32 bit value which is then converted to float because both hw and sw renderers lack double precision the lower 16 bits of the initial 32 bit value lose precision.
> GameDB: Add patches for KOF series

- pcsx2/gui/AppConfig.cpp
The VsyncQueueSize setting is currently affected by presets, would revert to default on start as well. Since the setting is not grayed out, this change makes it be unaffected.
> Avoid presets from resetting VsyncQueueSize

- pcsx2/COP0.cpp
- pcsx2/COP0.h
- pcsx2/x86/iCOP0.cpp
The read-only bits in question are the Instruction cache size (IC) and the Data cache size (DC)
Before this pr, MTC0 would freely write to the entire config register.
> Core: Preserve read only bits in the COP0 config register

- pcsx2/DEV9/Win32/pcap_io_win32_funcs.h
This got accidentally re-added in 4b722cc253e1605d633d2642fed186f8e9095853
It is a function that Npcap has, but winPcap doesn't.
This should fix the winPcap computability reported in discord
> DEV9: Don't import pcap_bufsize

- bin/GameIndex.yaml
Update KOF98 patches to fix remaining issues.
> GameDB: Fix KOF98 patches

- pcsx2/Patch.cpp
- pcsx2/Patch.h
- pcsx2/Patch_Memory.cpp
Allows users to use the leshort, leword, and ledouble datatypes inside their patches. Using these datatypes ensures that values in the memory view appear the same as the values in the patch.
This was made with easing patch development in mind as now developers can make patches without having to reverse endianness. This is especially useful when using programs like ghidra who display an instructions bytes in little endian.
> Added support for little endian data for patches

- bin/GameIndex.yaml
~~Only updated for NTSC-U so far. If anyone would be able to collaborate on updating this for NTSC-J, that would be super cool but until then the old "nuke the quality completely" patch will remain.~~ li comes to the rescue again, NTSC-J is now included.
Updated patch rewrites a chunk of game code to decrement JPEG quality, rather than just immediately floor it. Allows thumbnails to still look kind of okay.
> GameDB: Add improved Xenosaga save crash prevention patch

- pcsx2/IPC.cpp
- pcsx2/IPC.h
This avoids port overfills on windows, while increasing perf substantially on platforms that do port overfills. 
This is NOT a breaking change, despite its looks.
Tested by Juhn, requires an up-to-date pcsx2_ipc implem
> IPC: Socket reusability

- pcsx2/CMakeLists.txt
- pcsx2/IPC.cpp
- pcsx2/IPC.h
- pcsx2/System/SysCoreThread.cpp
- pcsx2/System/SysThreads.h
- pcsx2/gui/App.h
- pcsx2/gui/Dialogs/IPCDialog.cpp
- pcsx2/gui/Dialogs/ModalPopups.h
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
This allows multiple emulator sessions to run at the same time and windows user to configure their used port to their preferred one.
While slotting looks like ports they are not, they are simply used for compatiblity on systems that use TCP sockets to communicate, on linux for example unix sockets are used and the slot is transferred into the name of the socket.
> IPC: add a slot system

- bin/GameIndex.yaml
Adds patch from kozarovv to KOF '94 Rebout - NTSC-J, the normal version (not the special disc)
> Update GameIndex.yaml - KOF '94 Rebout NTSC-J

- .codacy.yaml
- README.md
I set it up on my fork to offer a demonstration - https://app.codacy.com/gh/xTVaser/pcsx2-rr
Steps to turning this on **(do this before merging this PR)**:
1. You need to be someone with admin access to the PCSX2 repo / org
2. Set up the free OSS plan for the organization - https://github.com/marketplace/codacy
3. Log-in via GitHub if it doesn't already redirect you (can't recall) here - https://www.codacy.com/
4. Add the PCSX2/pcsx2 repo
5. If annotations on PRs are desired, enable them here - https://app.codacy.com/gh/PCSX2/pcsx2-rr/settings/integrations
- They will look like this - https://github.com/xTVaser/pcsx2-rr/pull/61/files
6. That's it!  Codacy checks will start appearing on PRs and master commits should be scanned and the issues in the repo should be tracked overtime / the …
> CI: Static Analysis -- Add Codacy

- pcsx2/gui/Dialogs/IPCDialog.cpp
- pcsx2/gui/MainFrame.cpp
Some versions of wxWidgets are more sensitive than others on dynamic casting, so instead I used a C style cast to prevent any crash.
> IPC: Fix type polymorphism & checkbox

- pcsx2/gui/Saveslots.cpp
- pcsx2/gui/Saveslots.h
- pcsx2/gui/UpdateUI.cpp
I noticed this very small issue when working on something bigger than involved savestates.  When PCSX2 is first opened, and a game is launched saveslot `0` is selected, but even if there is a backup for slot 0 the menu option is not enabled (until you perform other savestate actions)
I deleted the comment labeling the function as potentially problematic because after simplifying the function and thinking through the possibilities, it looks fine to me.  The only hairy path is during saving:
- If backups are disabled, we look for an existing `.backup` savestate which shouldn't be touched by the save routine (and we don't expect a new one to be created)
- If backups are enabled, the `.backup` file will have already been created via renaming the original save-state.  The asynchronous process …
> gui: If available, enable menu option to load backup savestate when a game is first launched

- pcsx2/Counters.cpp
- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/Recording/InputRecordingControls.h
- pcsx2/gui/AppMain.cpp
Splits the checking of pause status and the actual pausing of emulation to separate functions called at different points during VSync. `VSyncEnd` is called once per frame, so checking for `g_FrameCount` increments is no longer required.
> Reorganize and realign InputRecordingControls

- common/include/PS2Edefs.h
- pcsx2/PluginManager.cpp
- pcsx2/SPU2/SndOut.h
- pcsx2/SPU2/Wavedump_wav.cpp
- pcsx2/SPU2/spu2.cpp
- pcsx2/SPU2/spu2.h
- pcsx2/gui/App.h
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/GlobalCommands.cpp
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- plugins/GSdx/GS.cpp
- plugins/GSdx/GSCapture.cpp
- plugins/GSdx/GSCapture.h
- plugins/GSdx/GSUtil.cpp
- plugins/GSdx/GSdx.def
- plugins/GSdx/Renderers/Common/GSRenderer.cpp
- plugins/GSdx/Renderers/Common/GSRenderer.h
- plugins/GSdx/Window/GSCaptureDlg.cpp
Addresses some oversights involving transferring a file name between the GS & SPU2 recording setups.
Adds a new audio toggle setting that allows a user to control whether a wav file should be generated alongside a video recording. In doing this, behavior for when SPU2 recording fails to be setup becomes more defined and consistent.
Additionally, F12 will now route to sMainFrame if gui is active as to keep the capture menu gui accurate to the current state. This change resolves #3729.
> Capture: Optimizations with file names, SPU2 recording, and capture menu gui

- bin/PCSX2_keys.ini.default
- pcsx2/Recording/InputRecording.cpp
- pcsx2/Recording/InputRecording.h
- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/GlobalCommands.cpp
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
* Originally, a user would have to navigate through a few menus to load up the file dialog and then manually select to load the savestate. To rectify this, a new `GoTofirstFrame()` function (along with the accompanying command code `Shift + L`) has been added. Calling this will automatically search for and attempt to load the base savestate. This command will be tied to the Boot option with a recording active and will also change its label to "Load savestate" when appropriate.
* If an attempt to explicitly load the base savestate fails due to it not being located, a file dialog will prompt the user for a new one. Whatever savestate gets chosen will be saved as the new base for the rest of the session. **Note: changing the savestate mid session will NOT change the starting frame count.**
* …
> GUI Improvements around savestate-based input recordings

- bin/GameIndex.yaml
Self explanatory. Function is at the same location on Director's Cut as on NTSC-U and PAL, so same patch.
> GameDB: renamed Rogue Galaxy Director's Cut and added kozarovv's patch

- pcsx2/gui/Debugger/DisassemblyDialog.cpp
> Debugger: Require emulator start before enabling Break/Run button

- pcsx2/ps2/BiosTools.cpp
If anyone has a BIOS that isn't supported, I'll be happy to add it.
Examples:
> Misc: Support more BIOSes for the Debugger Thread View

- .github/workflows/linux-workflow.yml
- .github/workflows/windows-workflow.yml
- cmake/SearchForStuff.cmake
Issues have been reported surrounding the `{fmt}` library which seem to be environment specific https://github.com/PCSX2/pcsx2/pull/4295 .  These build errors occurred on the latest version `7.1.3`, and while there are people that have experienced no issues on this version and CI passes, it would be wise for us to keep the submodule up to date to ease troubleshooting.
> Dependencies: Bump {fmt} to `7.1.3`

- pcsx2/CDVD/InputIsoFile.cpp
We want this to be visible at all times so ISO damage issues are more visible without enabling advanced logs. Conversely, we don't want this to show up as a big red error, since it is not necessarily a critical error as mentioned in li's comment.
> Change visibility of end of file error

- pcsx2/USB/usb-pad/dx/dinput-config.cpp
- pcsx2/USB/usb-pad/dx/dinput.cpp
- pcsx2/USB/usb-pad/dx/dx.h
This PR modifies DirectInput USB Force Feedback test not to block the UI. Instead of performing the test synchronously on the UI thread, a timer gets created which advances the test every half a second.
Closes #3926. With this change in place, all the points from this meta-issue are resolved.
EDIT: `AutoCenter` was removed because it doesn't work when the application submits custom FFB data anyway.
> USB: Improve Force Feedback test so it doesn't block UI

- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/Saveslots.cpp
- pcsx2/gui/Saveslots.h
- pcsx2/gui/UpdateUI.cpp
Resolves https://github.com/PCSX2/pcsx2/issues/4247
Comments on some of the ideas in that issue:
- Changing the active slot via the GUI
- To me, this can already be accomplished with the current GUI.  If you save or load a savestate, it will switch and make that the active slot.  Having a way to select the active slot first in the GUI, doesn't really solve anything, it just adds an extra step that i think most people would avoid?  (ie. why switch to a slot, then save it, when you could just save it in one step)
- However, I do think it would be cool to retain the select slot between sessions in the config, instead of always defaulting to `0`
- And agreed, I think having a separate active slot for loading/saving would get too confusing and im not sure what the use-case would be.
fyi …
> gui: Visually indicate the current savestate slot in the load/save menu

- 3rdparty/libchdr/libchdr.vcxproj
- common/vsprops/3rdpartyDeps.props
I don't know what PublicIncludeDirectories is, it's not documented anywhere by MS.
Even if it doesn't fix the bot, it's at least consistent now.
> msbuild: fix libchdr include directory

- pcsx2/PAD/Linux/state_management.cpp
- pcsx2/PAD/Linux/state_management.h
- pcsx2/PAD/Windows/PAD.cpp
- pcsx2/SaveState.h
Seems to be enough to fix Warriors of Might and Magic.
Fixes #4026
Increased savestate version since it changes the size of the PadFreezeData struct.
> PAD: Add one more byte to umask.

- common/include/PluginCompatibility.h
- plugins/GSdx/GSCapture.cpp
- plugins/GSdx/Window/GSCaptureDlg.cpp
- plugins/GSdx/Window/GSCaptureDlg.h
- plugins/GSdx/Window/GSDialog.cpp
- plugins/GSdx/Window/GSDialog.h
- plugins/GSdx/Window/GSSettingsDlg.cpp
- plugins/GSdx/Window/GSWndWGL.cpp
Changes:
* Adds a UTF-16 to UTF-8 conversion function on Windows;
* Handles the shader dialog filenames properly by storing them as UTF-8 in the ini, converting them to/from UTF-16 as necessary, and fixing the buffer overflows that were introduced when GSdx was switched over to Unicode on Windows.
Should fix #4317.
> gsdx:windows: Fix dialog filename handling

- pcsx2/DebugTools/Debug.h
- pcsx2/DebugTools/DebugInterface.cpp
- pcsx2/DebugTools/DebugInterface.h
- pcsx2/DebugTools/DisR5900asm.cpp
- pcsx2/GS.cpp
- pcsx2/GS.h
Fixes #4336 
Introduces a new register category based around GS Privileged registers.
Note: The memory view still shows the mirrored CSR values and writing to the registers using the memory view does not work.
> Misc:Debugger: Support write-only GS priv reads

- pcsx2/gui/Panels/ConfigurationPanels.h
- pcsx2/gui/Panels/SpeedhacksPanel.cpp
MTVU checked + Instant VU1 checked = MTVU is on
MTVU checked + Instant VU1 off = MTVU is on
Essentially it doesn’t matter for Instant VU1 be checked or unchecked if MTVU is checked.
MTVU off + Instant VU1 checked = Instant VU1 is on
MTVU off + Instant VU1 off = both are off
Instant VU1 enabled is the old behaviour (so think of it always being enabled in the past). Some games however don’t like this and for those few games they should be off, those kind of games should’ve normally been added as an automatic gamefix or will be in the future.
> GUI-Speedhacks: Grayout Instant VU1 when MTVU is enabled

- pcsx2/SPU2/Linux/Config.cpp
- pcsx2/SPU2/Windows/Config.cpp
Linux: 300 to 100 (which should be fine for everyone), windows was already 100ms.
Windows: Change the steps to start from 3 and increment on higher numbers instead of 0.5 steps which is just stupid to be that granular.
> SPU2: Change default of latency slider

- plugins/GSdx/GSdx.cpp
- plugins/GSdx/Window/GSSetting.cpp
Normal users shouldn't really need to choose partial or full since
automatic already does that.
Keep the options on debug for testing only.
> gsdx-gui: Remove partial and full crc hack levels on release builds.

- pcsx2/Elfheader.cpp
- pcsx2/IPC.cpp
- pcsx2/IPC.h
- pcsx2/gui/AppCoreThread.cpp
- pcsx2/gui/AppCoreThread.h
This implements 2 new IPC commands, to get the current status of the emulator (whether running, paused and whatnot) and retrieve the version of the game.
> ipc: implements GameVersion and Status

- pcsx2/IPC.cpp
- pcsx2/IPC.h
I was using strcat on a getenv pointer which was reused by the system's lib instead of providing a new one.
Because of this behaviour and me mistakenly appending to this pointer, I ended up corrupting the stack if called enough times.
tl;dr: code bad
> ipc: remove possible memory corruption due to strcat on provided pointer

- pcsx2/PAD/Linux/state_management.cpp
- pcsx2/PAD/Windows/PAD.cpp
Another try into Fix #4026
As far as I know, CMD 0x4F sets response byte masks and pressure mode, DS2 0x79 (includes pressure report, 18 bytes total), without any conditionals which is how I set it up on Pokopom [(code)](https://github.com/KrossX/Pokopom/blob/2f3f6a3b3dd02d73762b1c7badd1d4cae0984103/Pokopom/playstation_dualshock2.cpp#L120). I excluded this change before trying to keep the changes to a minimum as the game seemed to work fine, probably tested the wrong build.
pcsx2.exe build: [pcsx2_1164_pad4F.zip](https://github.com/PCSX2/pcsx2/files/6216352/pcsx2_1164_pad4F.zip)
> PAD: Just enable pressure on CMD 0x4F

- .github/labeler.yml
- .github/workflows/pr-triage.yml
I'm a bit late on this, but with https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ Github Actions finally has a path forward on doing things that require the repo's write-token on forked pull requests (ie. applying labels).  In the past, this lacking feature made these types of triaging efforts impractical.
I verified this actually works in my fork:
https://github.com/xTVaser/pcsx2-rr/pull/74
And got someone to make a PR to my fork who didn't have write-access:
https://github.com/xTVaser/pcsx2-rr/pull/75
I went through the repo's label list sorting by most-issues and i think i got the majority of the useful ones, but of course this can be iterated on https://github.com/PCSX2/pcsx2/labels?sort=count-desc
> ci: Automatically label pull requests

- .clang-format
A few common issues I saw while formatting GSdx:
When formatting GSdx code, I found that clang-format found random unrelated comments that just happened to be next to each other and decided to align them much more often than it found related comments that actually made sense to try to align, so defaulting to off decreases the number of cases that we have to disagree with clang-format.
This changes the default alignment of multiline function calls from this
```cpp
longFunctionName(param1, param2
param3, param4)
```
to this
```cpp
longFunctionName(param1, param2
param3, param4)
```
Two reasons for this:
1. Clang-format currently does this with tabs instead of spaces, causing the alignment to fail to align on e.g. the GitHub website.  #4000 does fix this but after having used that mode on …
> clang-format: change alignment settings

- pcsx2/gui/MainFrame.cpp
Renamed the window menu item to debug and move the block dump option to the new Debug menu.
Because it fits there more.
complie/ open  the pull request find the  debug option , open said menu item and  create a block dump and create one .
> GUI: change window to debug in the menu and  move blockdump to  the debug menu 

- pcsx2/DEV9/smap.cpp
Remove the byte swapping done to TX/RX FIFO writes/reads performed via registers.
Removing this fixes https://github.com/PCSX2/pcsx2/issues/3192, which now completes connecting to the network.
I suspect this setting is only for reads/writes to the SMAP_BD_TX/SMAP_BD_RX registers.
It was also brought to my attention that a demo version of Frequency, included on one of the Network Setup Discs, also needs this change to connect to the network.
Test various Network/LAN games for any regressions.
> DEV9: Do not apply byteswapping to TX/RX FIFO writes/reads

- pcsx2/gui/MainFrame.cpp
There's already a `PCSX2` menu on macOS, adding a second one is incredibly confusing
> Rename main menu back to System

- pcsx2/gui/MemoryCardFolder.cpp
- pcsx2/gui/MemoryCardFolder.h
**~This PR depends on #3950 because of its addition of yaml-cpp. Do not merge it before that PR.~**
This PR adds an index file for folder memory cards in order to track timestamps and order of files in the FAT partition properly. This normally shouldn't matter, but there are at least a few games (ie. GTA games) which rely on the order of files on the memory card. Previously, folder memcards would not care about the order and populate the partition in whatever order the host filesystem provided the files (so, in the case of NTFS partitions, alphabetically). In reality, FAT partitions don't specify the order of files, which means in practice they are sorted by the order of creation.
I added a YAML based index file to every subdirectory in folder memory cards to retain the original order in …
> Folder memcards: Add an index file to track order of files

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pr-triage.yml
- .github/workflows/windows-workflow.yml
Assumes there is a label made already with the name `First Time Contribution` (leave feedback if a different name is preferred)
I removed the comment from the PR template because it now feels redundant, the comment links them to the document (its clickable!) and explains the CI situation.  Lastly, it adds the label.
Improvement from a link in a markdown comment, removes it from non-first timers PR drafting.
Label makes it more visible that a maintainer needs to take action.
I tested here - https://github.com/xTVaser/pcsx2-rr/pull/83
> Github/CI - Add first-time contributor PR message  and label

- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/Recording/InputRecordingControls.h
- pcsx2/gui/MainMenuClicks.cpp
The gist is we paused the CoreThread without resuming it (input recording's `Resume()` method will resume on the next VSync), the shutdown routine triggers it when all required window elements are already cleaned up, hence the crash.
Solves a bug that results in an unexpected GUI error window when closing the emulator after very specific/edge-casey steps.
Reproduction Steps:
- boot game so gs window is open
- close the GS window
- open the dialog for a new input recording, then close it
- close pcsx2, should error.
fyi @sonicfind incase this breaks something to do with input-recording's frame locking behaviour.
> Input Recording: Resolve crash when closing emulator involving GUI elements

- bin/GameIndex.yaml
add Nearest EErounding to SSX and SSX tricky (NTSC-U & PAL &NTSC-J) to the  GameDB
To fix SSX and SSX tricky(NTSC-U & PAL &NTSC-J)
> GameDB: add Nearest EErounding to SSX and SSX tricky 

- pcsx2/gui/AppRes.cpp
Swap the GUI options Ask when booting and Browse... in CDVD. Ask when booting is also no longer on by default.
Old:
New:
Makes more sense for muscle memory. It does seem cleaner as well, though perhaps biased.
Test some games and swap between them. Disabling checkbox at another test to see if the GUI updates properly.
> CDVD-GUI: Swap buttons `Browse...` and `Ask when booting` and default to unchecked state.

- 3rdparty/include/ghc/filesystem.h
Updates `ghc::filesystem` dependency to 1.5.4
Makes the wchar-based implementation default on Windows, and makes it possible to initialize a `fs::path` from a `wchar*`
> Update ghc::filesystem to 1.5.4

- pcsx2/DEV9/ATA/ATA_Info.cpp
- pcsx2/DEV9/ATA/ATA_State.cpp
- pcsx2/DEV9/ATA/ATA_Transfer.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdPIOData.cpp
- pcsx2/DEV9/ATA/Commands/ATA_CmdSMART.cpp
- pcsx2/DEV9/ATA/Commands/ATA_Command.cpp
- pcsx2/DEV9/ATA/Commands/ATA_SCE.cpp
- pcsx2/DEV9/DEV9.cpp
- pcsx2/DEV9/Linux/Config.cpp
- pcsx2/DEV9/Win32/pcap_io_win32.cpp
- pcsx2/DEV9/flash.cpp
- pcsx2/DEV9/net.cpp
- pcsx2/DEV9/pcap_io.cpp
- pcsx2/DEV9/smap.cpp
Around half of the debug and console output from the DEV9 tree already
had this prefix. Adding it everywhere for consistency. Also fixed
misspelling of "Unknown" whilst there.
This is a follow-on from https://github.com/PCSX2/pcsx2/pull/4364 as requested by @lightningterror
> DEV9: consistently prefix all console output with `DEV9: `

- pcsx2/CMakeLists.txt
- pcsx2/Recording/Utilities/InputRecordingLogger.cpp
- pcsx2/Recording/Utilities/InputRecordingLogger.h
- pcsx2/windows/VCprojects/pcsx2.vcxproj
- pcsx2/windows/VCprojects/pcsx2.vcxproj.filters
When these utility functions / namespace were originally made it wasn't done in the ideal way, this just quickly cleans that up.
> Input Recording: Cleanup inputRec utility namespace

- pcsx2/DEV9/Win32/Win32.cpp
Correctly populate DNS2 field with DNS2 IP in the DHCP section of the network ui
Discovered this while testing my DNS pr after rebase.
This was probably a copy & past error, as it populated the field with DNS1 instead of DNS2
Manually configure DNS1 and DNS2 (with different IPs), apply and reopen the UI.
> DEV9: Correctly populate DNS2 field with DNS2 IP

- pcsx2/gui/AppInit.cpp
Save the last elf path when using the `--elf` command-line argument.
Helpful when you do something like this
`emu: $(EE_BIN)`
`<TAB>/path/to/pcsx2.exe  --elf="P://path/to/elf.elf"`
(I use wsl)
And instead of running `make emu` again, you can just easily open the elf browser without digging through your unorganized directories.
> Misc: Save ELF last path when auto-running an elf

- pcsx2/IopHw.h
- pcsx2/SPU2/Dma.h
- pcsx2/SPU2/ReadInput.cpp
- pcsx2/SPU2/defs.h
- pcsx2/SPU2/spu2.cpp
- pcsx2/SPU2/spu2.h
- pcsx2/SPU2/spu2sys.cpp
- pcsx2/SaveState.h
- pcsx2/ps2/Iop/IopHwRead.cpp
- pcsx2/ps2/Iop/IopHwWrite.cpp
The SPU was managing its own DMA Addresses, this makes it use the iopHw functionality for this instead.
Removes two functions in the SPU and some special case code in iopHw.
Check for any SPU breakage.
> SPU: Make SPU use the DMA registers from iopHw

- pcsx2/ps2/pgif.cpp
This PR removes the extra commands that were added for the V2 PSX GPU. 
Previously it was thought that the PS2 would emulate the v2 GPU, but hardware tests show that it emulates the V0 GPU.
> Fix Emulated PSX GPU Version

- pcsx2/x86/iR3000A.cpp
- pcsx2/x86/ix86-32/iR5900-32.cpp
Prefix the "Impossible block clearing failure" with "[IOP]" or "[EE]" depending on the recompiler
I managed to trigger this error and ignored it without looking at the assert message and now my emulog.txt has this error and I don't know where it's from. I also can't reproduce it now.
Not applicable here unless you can generate this error
> Misc: Differentiate Impossible block clearing message from IOP & EE

- bin/GameIndex.yaml
GameDB: add missing  'Official Playstation Magazine - Demo Disc 40'entries
EDIT:also adds entries form @atomic83GitHub 
To make the gameDB more complete 
download or compile the PR to check for console errors
> GameDB: add missing GameDB entries 

- .github/workflows/windows-workflow.yml
- buildbot.xml
When debugging a recent PR we ran into issues where the CI build would consistently produce an exception that could not be replicated conventionally via the local Visual Studio build.  It seems valuable to me to easily flip on these artifacts going forward, to make it easier to attach a debugger to the process and get a stacktrace at a minimum.
However, enabling these does increase the artifact size by 4x (numbers in the actions summary pages are the uncompressed file-size which are much larger).  So I've left them still off by default.
An example commit/build that flips this flag to `true` - https://github.com/xTVaser/pcsx2-rr/actions/runs/508048107
> CI: Add an explicit flag to retain debugging artifacts (.pdb, .exp, .lib, etc) in Windows builds

- pcsx2/gui/Dialogs/CreateMemoryCardDialog.cpp
- pcsx2/gui/Panels/MemoryCardListView.cpp
Remove PSX references to distinguish between PS1 and DVR
> Remove PSX references to distinguish between PS1 and DVR

- pcsx2/DEV9/DEV9.cpp
- pcsx2/DEV9/Linux/Linux.cpp
- pcsx2/DEV9/Win32/Win32.cpp
Use wchar instead of UTF8 for ghc::filesystem::path constructor on windows
The GHC dependency got updated to a version that uses wchar instead of UTF8 on windows, see https://github.com/PCSX2/pcsx2/pull/4422
Test unicode paths with HDD files (including testing with the inis folder in a unicode path)
> DEV9: Update ATA code for wchar GHC

- pcsx2/Recording/InputRecordingControls.cpp
- pcsx2/Recording/InputRecordingControls.h
- pcsx2/gui/App.h
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
Adds a GUI configurable setting to control how many frames the frame-advance feature should advance.
It's not unreasonable to imagine a use-case where you may want to advance frames in multiples other than `1s`.  So this gives that ability to the user.
In the future, it would probably be nice to have 2 key-bindings, one that always advances by `1s` and another that uses a custom/configurable value.  Wouldn't be too difficult to add but I think I'm tempted to wait until PCSX2 in general has better key-binding configuration for features like that.
Easier to confirm the right amount of frames are being advanced if you are recording/playing back a recording.  Change the value, restart the emulator (should persist), etc.
> Input Recording - Allow configuration of the frame advance amount

- pcsx2/DEV9/InternalServers/DHCP_Server.cpp
Fix an off-by-one error for array access.
If DNS1 was manually specified, but DNS2 set to be automatically assigned, an off by one error could result in an out of bounds access to an array of adapter DNS addresses.
Enable DHCP intercept
Test manual DNS1 & automatic DNS2 with an adapter that has DNS addresses assigned to it.
> DEV9: Fix potential out of bounds access when manual DNS1 & automatic DNS2 are used together.

- pcsx2/DEV9/ATA/ATA_State.cpp
Previously the file was only opened in binary mode if it existed before starting emulation.
If the image file was created during emulation startup (where the original file is missing or wasn't created), the file would not be opened in binary mode.
This PR addresses that, always opening the file in binary mode.
Opening the file in binary mode is the intended behaviour (and was done in the most common situation),
Test HDD enabled games,
Also test situations where the configured HDD image is missing on emulation startup.
> DEV9: Always use binary mode for HDD file

- bin/GameIndex.yaml
GameDB:adds VU clamping mode extra to 'Enthusia Professional Racing'
i have no idea if other version of 'Enthusia Professional Racing' needs the same VU clamping 
Fixes #4386
boot up the game in question and see if it works fine and complete a race  ( it dosent freeze )
> GameDB:adds VU clamping mode extra to 'Enthusia Professional Racing'

- pcsx2/R5900.cpp
Fixes #4459
This hackfixes the BIOS to avoid a Data Cache bug caused by a DMA buffer being overwritten during a transfer without waiting, which messes up the fonts in the BIOS.  Fixing this correctly would require implementing the Data Cache, which is something which would make the emulator basically unusable, so this is a reasonable solution, it is only enabled during the BIOS screen.
Thanks to the work of @tadanokojin and @PSI-Rockin we can now hackfix this, a proper fix isn't feasible without making the entire emulator slow to a crawl.
> Core: Make DMA's instant during the BIOS

- pcsx2/Recording/NewRecordingFrame.cpp
- pcsx2/Recording/NewRecordingFrame.h
Adds a brief warning explaining why you may want to avoid save-state recordings, and what would have to be done if a bad state is achieved.
Save-states are volatile from emulator version-to-version and likely should not be used if you are creating a full-game recording.
Try using the dialog / switch between options, etc.
> Input Recording - Add warning when creating a save-state recording

- pcsx2/x86/ix86-32/iR5900-32.cpp
Fixes an issue where recConstBuf was too far away from the main recompiler to LEA in 64-bit builds
Fixes #4497
Note: This implementation leaves an extra 64kb allocated for the table at all times.  There are alternate solutions if anyone thinks that's a problem
See above
1. Use an OS that likes to put its malloc buffer more than 4GB away from the main code region
2. Run Just Cause
> iR5900: Move recConstBuf memory near recompiler memory

- pcsx2/CDVD/CDVDdiscReader.cpp
- pcsx2/CDVD/Windows/DriveUtility.cpp
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/MainMenuClicks.cpp
* Fixes the disc path handling on Windows, where the path is not always converted to the correct format.
* Simplifies how the disc path stuff is handled.
* Fixes #3910 (Regression only affects Windows).
* Fixes an issue where the drive choice is cleared if there is no disc in the selected drive when PCSX2 is first opened (Should only affect Windows, but non-Windows only code is touched too).
* Start PCSX2 without a disc in the optical drive.
* Insert Disc
* Boot from Disc
or
* Start PCSX2 without a disc in the optical drive.
* Boot from Disc
* Insert Disc
> cdvd: Fix disc drive path issues on Windows

- pcsx2/DEV9/pcap_io.cpp
in pcap, check size of read packet. If the size exceeds the buffer we are using, drop the packet.
Jumbo frames could exceed the size of the buffer, leading to an overflow.
Test networked games with the pcap backend
Fixes https://github.com/PCSX2/pcsx2/issues/4467
> [DEV9] pcap, check size of read packet

- pcsx2/SPU2/Dma.cpp
- pcsx2/SPU2/spu2.cpp
- pcsx2/SPU2/spu2.h
- pcsx2/SPU2/spu2sys.cpp
This just changes the SPU2 to get the current IOP cycle directly instead of through a pointer. The non-pointer path seems to have been given up on anyway and there seems to be little reason for hiding it behind a pointer.
This removes the path where SPU2 runs off the provided cycle argument to SPU2Async, but that was unused anyway.
> SPU2: Remove cycleptr, grab current cycles directly

- pcsx2/PAD/Linux/wx_dialog/GamepadConfiguration.cpp
The rumble test using either the checkbox or the slider in the gamepad
configuration GUI always causes the first gamepad to rumble, even if
other gamepads are selected in the drop-down menu.
This change causes the currently selected gamepad to rumble instead of the first one.
Rumble test running on the currently selected gamepad is the expected behavior.
- connect multiple gamepads;
- select each one and perform the rumble test;
Without this change the first gamepad will always be the one with rumble. With this change it will be the currently selected gamepad.
> Fix gamepad choice not affecting rumble test on Linux

- pcsx2/windows/VCprojects/vsprops/common.props
Currenty it only works because of portaudio linking it with a pragma.
> Explicitly link setupapi

- common/include/Utilities/Dependencies.h
- common/src/Utilities/pxTranslate.cpp
Removed a warning that occurred if a string is translated via pxGetTranslation() and is > 128 characters
This was left behind when the translation process changed and started using wxGetTranslation()
See if long messages such as the input recording savestate warning is translated properly
> Translations: Remove unnecessary warning regarding string length

- pcsx2/DebugTools/BiosDebugData.cpp
- pcsx2/R5900OpcodeImpl.cpp
- pcsx2/R5900OpcodeTables.h
- pcsx2/ps2/BiosTools.cpp
- pcsx2/ps2/BiosTools.h
Instead of using hardcoded BIOS addresses, pattern match instructions in the kernel to find the correct address.
This allows BIOSes that have weird checksums or BIOSes that haven't been hardcoded to use the thread tools!
I do this by hooking two thread-related syscalls, `StartThread` and `ChangeThreadPriority`. When either of these are called for the _first time_  it will pattern match the kernel. If you don't know what this means and are worried, don't worry, you will not notice perf loss. 
Hard coding the addresses poses a problem when a BIOS is modified or has been dumped in a way that messes with the checksum.
Test the thread and stack views in the debugger with your bios, if they are blank, something is wrong. If it is showing garbage data, something is wrong. There will be a message …
> Misc: Pattern match to find the BIOS thread address

- pcsx2/MTGS.cpp
Fixes an issue where the entire emulator could freeze attempting to shut down.
The waitGS function (called by the MTVU thread) waits for the MTGS work queue to empty entirely by spinning on a lock that the MTGS thread normally holds while it's working.  This caused two issues:
- If the MTGS thread pauses with work in the queue, it drops the lock causing the MTVU thread to spin instead of waiting patiently
- If the MTGS thread exits with work in the queue, the MTVU thread will wait forever for a nonexistent MTGS thread to empty the queue
While we don't really care about MTVU state in the case of an exit, we would like to not abort in the case of a pause since otherwise unpausing will not work.
Based on this, there are two possible solutions:
1. Make waitGS verify that the the MTGS thread …
> MTVU: Fix freeze on shutdown

- .github/workflows/scripts/validation/lint-gamedb/lint-gamedb.py
- bin/GameIndex.yaml
- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/gui/Panels/GameFixesPanel.cpp
- pcsx2/x86/microVU.cpp
- pcsx2/x86/microVU_Compile.inl
Consolidates the Scarface and Crash Tag Team Racing I bit hacks in to 1 generic function.
To cut down on gamefixes and to stop the "hey lets add an I Bit hack for X game" talk, plus it's cleaner.
Find games which constantly recompile, you can turn off the auto game fixes if it's Crash or Scarface to check, then enable the I Bit Hack in the gamefixes tab and see if it stops recompiling constantly (some occasional ones is okay)
> microVU: Consolidate I-bit hacks in to one generic one

- pcsx2/Gif_Unit.cpp
- pcsx2/MTVU.cpp
- pcsx2/MTVU.h
- pcsx2/VU1micro.cpp
- pcsx2/VUmicro.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/x86/microVU.cpp
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_Misc.inl
Enables T-Bit stops to work with MTVU enabled as before some games which required it would just hang/crash
Due to the threading nature of MTVU and the fact it has always kept the "busy" bit kept off, games which used T-Bit would get out of sync and mess up quite wildly, this fixes that.
Try games which use T-Bit (maybe test some other game too for performance regressions), here's a short list of games which should work better now, however they may have been unaffected before.
The Sims
Spiderman 3
Sharks Tale - Confirmed to now work in MTVU
Maybe Over the Hedge
Pitfall (both demo and full game) - Confirmed to now work in MTVU
Gumball 3000 (maybe, can't remember)
Evolution Snowboarding
> microVU: Enable T-Bit to work with MTVU

- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
Enable pabe bit only when sw blending is enabled.
Minor optimization, no need to enable pabe when sw blending is not detected.
> GS-hw: Enable pabe bit only when sw blending is enabled

- common/src/Utilities/Windows/WinMisc.cpp
Microsoft has deprecated `GetVersionEx`.
We use `GetVersionEx` to print the current build number and _that's all_.
According to the docs [here](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversion).
`GetVersion may be altered or unavailable for releases after Windows 8.1. Instead, use the Version Helper functions. For Windows 10 apps, please see Targeting your applications for Windows.`
Unfortunately, the Version Helper Functions aren't a solution for us, and we aren't a UWP app (thank god).
This PR suppresses the warning for just that line.
If there's a sane, non-deprecated way to expose the current build version that'd be the best solution here.
> Misc: Suppress a warning regarding GetVersionEx

- pcsx2/gui/Panels/BiosSelectorPanel.cpp
- pcsx2/gui/Panels/ConfigurationPanels.h
Instead of blocking the UI, show the text "Enumerating..." and run a thread to enumerate through the BIOSes
It can look like PCSX2 has crashed when verifying BIOSes in a directory.
Expensive file I/O shouldn't be on the UI thread
Duplicate your BIOS bin files and put them in a single directory.
Go to the BIOS selection page and set the BIOS directory to said directory.
You should see "Enumerating BIOSes..." as the first item in the BIOS list, the UI shouldn't freeze
Once the thread is done working, the list box should contain your BIOSes
> UI: Asynchronous BIOS enumeration

- .github/workflows/lint-gamedb.yml
- .github/workflows/linux-workflow.yml
- .github/workflows/macos-workflow.yml
- .github/workflows/pr-triage.yml
- .github/workflows/windows-workflow.yml
- README.md
Doubles our windows builds, but increases parallelism.  A good interim solution until we can truly improve the compile times and remove unnecessary builds.
I also adjusted the naming of the Workflows a bit to make them categorized (via emojis) and reduces unnecessary words (ex. obviously windows builds are running on windows) since we now have a substantial number of them.
> ci: Split avx2 and non-avx2 windows builds

- common/src/Utilities/Windows/WinMisc.cpp
Attempt # 3
Throw out the old version fetching we used to do.
Report if the user is on a version < 8.1
GetVersionEx is deprecated, and we only need to know if the user is < 8.1 anyways
Start the application, check the os version printed.
My example: `Operating System =  Microsoft Windows 10, 64-bit`
> Utilities: Remove dependency on GetVersionEx

- pcsx2/IPU/IPU.cpp
According to available sources its 8:0 for transparency, and 24:16 for translucency.
Currently pcsx2 is masking bits 8 and 24 making them always 0.
Improve IPU color space conversion accuracy.
Testing FMVs for regressions/improvements. Possibly affect IPU texturing (rare thing afaik).
> IPU: Fix SETTH threshold masks

- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/GSFrame.h
Passing focus on the focus message instead of the activate message resolves an issue where external processes (e.g. NVIDIA overlay) forced a focus change to the GS Frame, requiring the window to be refocused in order for keyboard inputs to work again.
Currently, GSFrame rejects focus messages and instead passes it to the child GSPanel.
To better illustrate the changes, let's compare the GSFrame message flow before and after this change:
* Do nothing special. GSFrame receives focus and accepts it.
* Continue with default window procedure.
* Set focus to GSPanel. This prevents `WM_ACTIVATE` from setting focus to GSFrame (as it is contractually done by the default window handler).
* Continue with default window procedure.
* Set focus to GSPanel. This prevents GSFrame from getting focused at. …
> GSFrame: Pass focus to GSPanel once Frame receives focus

- bin/GameIndex.yaml
- Adding the hack fix for Oni (Spanish).
- Adding the proper name for GoldenEye Rogue Agent on the Spanish disc.
Seems like the Spanish version of Oni was the only one that did not have the hack to go past the intro video, so now it goes past that. As for the other game, the issue should be self-explanatory.
Boot Oni [PAL-S] [SLES-50179].
> GameDB: Changing some Spanish-exclusive disc content.

- pcsx2/VUmicro.cpp
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/microVU_Macro.inl
This tightens the VU Sync with the EE when Kickstart is enabled to fix some SPS in PAL Ratchet games, also loosened it slightly when Kickstart is disabled to improve the speed of games which don't require it.
Ratchet games were broken since the VU Sync changes, this resolves it.
Test any games you can (Especially those that require Kickstart or have M-Bit), check for SPS and freaky Physics problems.
> VU: Improve sync with VU Kickstart, loosen without kickstart

- .github/workflows/scripts/validation/lint-gamedb/lint-gamedb.py
- bin/GameIndex.yaml
- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/SPR.cpp
- pcsx2/gui/Panels/GameFixesPanel.cpp
- pcsx2/x86/ix86-32/iR5900-32.cpp
Removed IPUWait hack as it is no longer required
Added dynamic patching system in the recompiler for Ratchet & Clank games toggled by gamefix. Fixes various shadow and SPS problems, improves spawn logic in Q9 station arena challenges, also problems with Ammu-nation in Up Your Arsenal.
Ratchet & Clank dynamically allocates memory for the program to run from, so traditional patching is not possible and can cause TLB misses.
Play the Ratchet & Clank games (Aside from Size Matters), places where it went a bit loopy should be okay now.  Turret is still broken, but may be able to add a patch for that before this PR is merged.
> GameDB: Add dynamic patching for Ratchet & Clank games

- bin/GameIndex.yaml
Adding Forbidden Siren (PAL demo disc) as well as the Bonus Demo 8 (old) demo disc, which was included with an updated Network Disc.
NOTE: The "(old)" part is written verbatim on the disc. Reference picture:
> GameDB: Adding a couple of demo discs.

- pcsx2/Docs/Debugger.md
- pcsx2/gui/Debugger/CtrlDisassemblyView.cpp
- pcsx2/gui/Debugger/CtrlMemView.cpp
- pcsx2/gui/Debugger/DebuggerLists.cpp
- Disassembly view:  hotkeys don't need to be used with CTRL (they are still usable with CTRL, however)
- Memory view: Goto address hotkey (G) doesn't need to be used with CTRL
- Disassembly view: To reassemble an opcode, you  can press `M` or go through the context menu, pressing any non-hotkey letter won't trigger this anymore.
- You can now delete a breakpoint through its context menu. (See image)
If you use Ghidra for example, you'd know that depending on CTRL for goto is odd.
Why not have delete as a context menu option for breakpoints?
Use the various debugger hotkeys, see if they work.
Make sure the delete breakpoint button works properly.
~~The debugger pdf is outdated. Sorry, but why use pdfs when they are probably the worst format to edit?~~
> Debugger: Modify hotkeys and add delete breakpoint context action

- CMakeLists.txt
- pcsx2/gui/AppCoreThread.cpp
Leftovers from the plugin merge, SPU2init call was redundant, we might want some light testing through some SPU2 lifecycles to ensure this doesn't break anything
> AppCoreThread: remove unneeded includes & unneeded double init call

- pcsx2/R3000AInterpreter.cpp
Whenever there is a branch to zero, put a warning in the console. 
The interpreter can start executing garbage, and this will tell us why.
(Also helps me debug my poor IOP code :P)
Make the IOP branch to zero.
> IOP Interpreter: Warn on branches to zero

- pcsx2/GS/GS.h
It now checks if __rdtsc is defined before trying to define it.
Since __rdtsc already *is* defined, GS.h is included a lot, and __rdtsc is brought in in the pch with the compiler's version, gcc isn't very happy about this situation.
If anyone has any idea when the gcc 4.8 crash mentioned in the comments happened, try to reproduce it?
> Remove __rdtsc define. Gets rid of 30 million warnings on Linux while compiling.

- .github/workflows/macos-workflow.yml
Attempts to install packages without updating package lists and only updates package lists if that fails
Updating package lists was done to fix issues during the Homebrew package provider transition, but it adds anywhere from 30s to 3-4m to the build depending on how recently GitHub updated Homebrew in its images, since you can end up with things like "GTK requires Python" → "Python has update" → "Updating python requires all dependents of Python also get updated" → "Update LLVM" → takes forever.
Most of the time, old versions of packages still remain on the package servers and there are no problems with skipping the package list update
Make sure CI works
> Don't update homebrew when not necessary

- common/include/Utilities/PersistentThread.h
- common/src/Utilities/Darwin/DarwinThreads.cpp
- common/src/Utilities/Linux/LnxThreads.cpp
- common/src/Utilities/Windows/WinThreads.cpp
- pcsx2/CDVD/ChdFileReader.cpp
- pcsx2/CDVD/ChdFileReader.h
- pcsx2/CDVD/CsoFileReader.cpp
- pcsx2/CDVD/CsoFileReader.h
- pcsx2/CDVD/ThreadedFileReader.cpp
- pcsx2/CDVD/ThreadedFileReader.h
- pcsx2/CMakeLists.txt
- pcsx2/gui/Resources/Info.plist.in
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
Closes #4319
When loading from a mostly-LZMA CHD (SSD, i7-4980HQ w/ turbo boost off)
Time to play P3FES intro cutscene (disk-heavy, linear, timed with phone stopwatch)
- Uncompressed ISO: 57s
- Async + Readahead: 57s
- Asyncronous: 61s
- Synchronous: 65s
I was expecting hunk size to make more of a difference, but results were about the same for both my default settings (~20kb hunks) chd and max size one (~1mb hunks, chdman refuses to make bigger ones), however this FMV reads 100% linearly, so that might be why.
Also for anyone on slow HDDs, this also means that using compressed formats won't take away your async file reading (previously none of the compressed disk readers used async file APIs.  They still don't but now they don't block the EE thread calling them)
> Move ISO decompression to a separate thread

- pcsx2/System.cpp
- pcsx2/System.h
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
- pcsx2/windows/WinPowerProfile.cpp
Print the current power profile and the current min/max processor state
This can help aid users who are experiencing slowdowns and can aid helpers in diagnosing possible slowdown reasons.
You should get a message stating your current power profile and processor min/max states.
> System | Windows: Print active power profile on application launch

- pcsx2/CDVD/ChdFileReader.cpp
It was crashing in some string conversion function.
Apparently you can't use the constructor to concat a literal and a wxString like that.
> CHD: Fix parent search on windows

- pcsx2/SPU2/spu2.cpp
remove   an unused variable in SPU2
it fixes  the cmake warning  `warning: pClocks’ defined but not used [-Wunused-variable]  44 | static u32 pClocks = 0;`
boot up a game and make sure Audio works
> SPU2: remove   unused variable

- pcsx2/IPU/IPU.cpp
- pcsx2/SaveState.h
Store color conversion thresholds in u16 instead of u8. Bump save state version.
Fix accidentally created UB from my previous PR.
While SETTH command was accepting 8:0 and 24:16 bits after merging #4526 , I didn't noticed that variable is declared to store only 8 bit values. So SETTH in result still masked bit 8, and 24, additionally creating risk of overflow.
This PR fix it.
Testing FMVs for regressions/improvements. Possibly affect IPU texturing (rare thing afaik).
> IPU: Store thresholds for color conversions in u16, bump savestate version.

- .github/workflows/linux-workflow.yml
Updates Linux CI names to not have dashes in the build names
Build names were previously updated to use spaces instead of dashes but the `detail` section was left out for some reason
If this breaks something other than the CI, I don't know what to say
> GHActions: Remove dashes from build names

- pcsx2/Counters.cpp
Whenever TN_COUNT = TN_COMP, reset TN_COUNT regardless of Interrupt Target bit in TN_MODE
Accuracy
?
> Counters: Reset Timer Count Regardless of Interrupt Enable

- pcsx2/IopBios.cpp
- pcsx2/IopBios.h
This PR basically fully implements the IOP driver for `host` unit.
Currently `host` unit was barely supported making some homebrews fail, as `RetroArch`, with this PR all the basic IO files/folder functions are working.
The PR implements:
- mkdir
- rmdir
- dopen
- dclose
- dread
- getStat
*I couldn't test the changes in Linux and Windows because I'm using MacOS*
Thanks in advance!
> Extending Host filesystem

- pcsx2/GS/GS.cpp
- pcsx2/GS/GS.h
- pcsx2/GS/Renderers/Common/GSRenderer.cpp
- pcsx2/GS/Renderers/Common/GSRenderer.h
- pcsx2/gui/AppMain.cpp
- pcsx2/gui/FrameForGS.cpp
- pcsx2/gui/GSFrame.h
- pcsx2/gui/GlobalCommands.cpp
Instead of having a second subwindow inside the GS window which is rendered into, resulting in a mix of software/Win32 and hardware surfaces, this PR makes the GS panel take up the full client area of the window, and the renderer performs the aspect ratio correction instead.
This is (imo) cleaner, as well as enabling fullscreen optimizations/directflip. It also removes the redundant code from GS.
Make sure all aspect ratios work, hotkey switching functions, ensure that FMV auto switching isn't broken.
> GS: Manage draw rectangle in GS instead of wx

- bin/GameIndex.yaml
GameDB: Patches for 18 games (or 15 individual games)
- Arctic Thunder (NTSC-U)
- Evolution Snowboarding (PAL, NTSC-J, NTSC-U)
- From Software First Previews (NTSC-J)
- Growlanser Generations (NTSC-U, NTSC-U)
- ICO (NTSC-C)
- Major League Baseball 2K5 (NTSC-U)
- Major League Baseball 2K10 (NTSC-U)
- Musashiden II - Blademaster (NTSC-J)
- Musashi Samurai Legend (PAL)
- NHL 2K5 (PAL)
- NHL 2K6 (PAL)
- NHL 2K7 (PAL)
- NHL 2K8 (PAL)
- NHL 2K9 (PAL)
- Virtua Fighter 4 (NTSC-U)
Also fixed some wrong serials and a wrong patch.
Needed game patches which improve emulation experience.
Run with correct serial.
> GameDB: Patches for 18 games (or 15 individual games)

- bin/GameIndex.yaml
- pcsx2/FiFo.cpp
- pcsx2/Gif.cpp
- pcsx2/Gif.h
- pcsx2/Gif_Unit.h
- pcsx2/Hw.cpp
- pcsx2/HwWrite.cpp
- pcsx2/SPR.cpp
- pcsx2/SaveState.h
- pcsx2/Vif.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif_Codes.cpp
- pcsx2/gui/Panels/GameFixesPanel.cpp
Reworks the GIF FIFO to always be enabled and only kick in when needed.  Savestate version bumped
The old GIF FIFO was a bit janky/broken and it was quite slow when used, the new changes allow it to always be on without impacting performance.
Test mainly games which used to have the GIF FIFO hack entry in the GameDB, or games which use PATH3 masking, these will be impacted the most
> GIF: Reimplement GIF FIFO to enable only when it is needed.

- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.h
Instead of relying on bools for checks rely on the pixel shader pointer, also merge the functions.
Clean stuff up.
Make sure FXAA and External shader work properly  on Direct3D11
> GS-d3d11: Cleanup fxaa and external shader.

- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
Set blend index to 0 when hw blending is enabled,
Move BlendEnable toggle inside the alpha blend check, cleaner this way.
Optimizations.
Test blending on Direct3D 11.
> GS-d3d11: Minor Blend changes

- pcsx2/CDVD/CdRom.cpp
Fix mistake from https://github.com/PCSX2/pcsx2/pull/3899 , where path for PS1 games with CDDA was changed to real CD audio path. PR should affect only PS1 games.
Fix Legend of Dragoon (PS1), combined with (#4642) fix Tenchu. Maybe more.
Testing PS1 games
> CDVD: Fix CdlReadS for PS1 games with CDDA.

- pcsx2/Hw.cpp
- pcsx2/HwWrite.cpp
- pcsx2/SPU2/spu2.cpp
- pcsx2/SPU2/spu2.h
This PR combines the previously separate sample rate functions for PS2 and PSX modes into a single one.
> SPU2: Simplify reset function for sample rate

- pcsx2/DebugTools/DebugInterface.cpp
- pcsx2/gui/Debugger/CtrlRegisterList.cpp
- pcsx2/gui/Debugger/CtrlRegisterList.h
Add an option to the VU0f context menu that allows you to toggle the float view
Add a title to the VU0f register list that identifies the registers w/z/y/x subsections
Reading float values as hex sucks
Play around with the VU0f register section
New VU0F hex view
New VU0F float view
Display as float context menu
Display as float context menu (when display as float is disabled)
Also supports 32 and 64 bit views!
32 bit
64 bit
Also, large floating point numbers are kind of weird.
If anyone has a solution (maybe using %g as the format specifier?) I couldn't get a good result however.
Closes #2779
> Debugger: Add option to display VU0F registers as floats

- common/src/x86emitter/cpudetect.cpp
Use __rdtsc compiler extension on all compilers
GCC 4.8 isn't supported anymore (we are c++ 17 now), the supposed crash related to it is not a problem anymore.
Compile using gcc / clang and see if there is a crash.
I tested this on clang 12.0.1 and gcc 11.1.0 (64-bit) with no apparent crashes.
> X86Emitter: Use __rdtsc define on non-msvc compilers

- pcsx2/CDVD/CDVD.cpp
Implement SCMD 0x27 to allow PS1 games to boot on SCPH-50009, and DTL-H50009 bios.
According to krat0s this command should return PS1 Disc Serial.
Disc Serial is later used by ps1drv itself to find matching game config. 
Note: While DTL consoles are known to use region free PS1 bios, SCPH-50009 use Asia/Japan PS1 bios, and region lock apply here.
Fix PS1 mode for SCPH-50009, and DTL-H50009.
Launch PS1 game using BIOS dumped from SCPH-50009, or DTL-H50009.
> CDVD: Implement SCMD 0x27

- pcsx2/Counters.cpp
- pcsx2/Counters.h
Corrects the number of H-Blanks (H-Blank clock rate) for 1080i mode
previously it was doing 525 lines per frame, which is too slow, the clock frequency is 33.75khz not 31.469khz, so it actually does 562.5 lines per V-Blank or 1125 lines every 2 frames, this covers the whole 1080 required lines, before it was only covering 1050.
Run anything with a 1080i mode, make sure it works okay.
Also updated a comment regarding Interrupt delays on VBlank with some updated infromation
> Counters: Correct H-Blank for 1080i mode

- 3rdparty/GL/glcorearb.h
- 3rdparty/GL/glext.h
- 3rdparty/GL/khrplatform.h
- 3rdparty/GL/wglext.h
Update glcorearb.h from 7 February 2019
Update wglext.h from 33248 (10-24-2016) to 20200813 (13 August 2020)
Update glext.h from 33248 (10-24-2016) to 20210420 ( 20 April 2021)
Creation of khrplatform.h
Update the headers to a more recent version while it brings no improvements at this moment, it can in the future.
This is a preliminary step for OpenGL improvements.
Shouldn't be needed as it boots and they are just headers anyway.
> Dependencies:GL

- pcsx2/HwRead.cpp
- pcsx2/ps2/pgif.cpp
- pcsx2/ps2/pgif.h
- Fixed GP1(00h), ps1drv do most job for us.
- Fixed GP1(01h)
- Fixed GP1(04h), since ps1drv do nothing here, we need to care about all possible options.
- Fixed BCR BA 0 transfers (really 0x10000, based on duckstation solution)
- Fixed BCR BA decrementing, previously BA was decremented by 1 every transfered word. This is wrong (1BA = 1BS, which can be up to 10 words for GPU).
- Fixed From GPU DMA transfers using wrong addressess. That one improve many games.
- Cleaned up getUpdPgifCtrlReg to just update fifo state before returning result. Previous implementation was really overdone. 
- Moved DREQ (DMA Request bit) handling from getUpdPgpuStatReg to handleGp1Command. Since this bit is dependent on GP1(04h) it seems to be best to take care of that as soon as GP1(04h) is read by GPU.
- …
> PGIF: Code refactoring/cleanup.

- linux_various/PCSX2.desktop.in
In certain Linux desktop environments, in order to pin application to a task bar, presence of StartupWMClass= line is expected in .desktop file. (Reference: solus-project/budgie-desktop#750)
This change allows pinning of PCSX2 application to Budgie Desktop Environment, but I think that having this is generally a good thing.
Use Linux Budgie Desktop and experiment with if pinning PCSX2 of possible in task bar. (task bar feature being called "Task List Applet")
> Add StartupWMClass to desktop file

- pcsx2/PAD/Windows/KeyboardQueue.cpp
Removes Windows-specific code from `KeyboardQueue.cpp`.
The comment about `std::mutex` being slower than `CRITICAL_SECTION` is not true at least since VS2015 - nowadays, `std::mutex` is implemented via a SRW Lock that is both more lightweight and faster than legacy-ridden critical sections.
-
> KeyboardQueue: Remove a Windows-specific critsec

- pcsx2/x86/microVU_Lower.inl
MicroVU was emitting `add reg, 0`, which is redundant (apart from setting flags, which aren't used). These could also be changed to a 32-bit add (instead of 16-bit), but it's written using the 16-bit form, so afaik there's no partial register stall here.
Smaller code size.
Make sure nothing breaks running a few games.
> microVU: Don't emit add reg, 0 in a few instructions

- pcsx2/x86/ix86-32/iR5900MultDiv.cpp
MULT1 incorrectly uses an unsigned multiply when performing in-block constant propagation. This probably doesn't affect much, since it's unlikely that the inputs to the MULT1 will be constant anyway. The second commit makes it clearer that the assignment to the constant register is in fact sign extending.
MULT1 incorrectly uses an unsigned multiply when performing in-block constant propagation.
Make sure games boot.
> iR5900: Use a signed multiply for MULT1 const prop

- pcsx2/gui/AppInit.cpp
There was a chance that doing `--elf="P://dir1/dir2/elf.elf"` would save the last path as `P://dir2/elf.elf`, completely voiding the functionality of #4444 
Also verify that an ELF file exists before trying to execute it.
#4444 was no longer working in certain scenarios 
Currently, running an invalid ELF (one that doesn't exist for example) would put the emulator in a strange state with no immediate explanation for the user.
Run ELF files from the command line and see if opening an elf file via gui brings you to the directory specified in the command line.
Try running non-existent ELF files and verify that PCSX2 no longer breaks.
> Misc: Fix lastpath updating when using the --elf cmdline arg

- common/src/Utilities/wxGuiTools.cpp
Makes the start up position validation multi-monitor aware. Just sort of a personal annoyance for me so I thought I would make an attempt to address it.
Fixes #2840
Previously `pxIsValidWindowPosition` would only compare against a single display. This would cause a condition where the application could be closed on another monitor and would default to the primary display when opened.
~~I'm not 100 percent the way I've done it is the best way, but absent anything else it seems to work okay. There seems to be no function in wx for getting the area of both displays (as `GetScreenPosition` returns relative to)~~
Scratch that. Seems less wise to check the sum since the resolutions might be different. 
- Make sure you can close the main pcsx2 window on both displays and have it be remembered …
> wx: make position validation multi-monitor aware

- pcsx2/PAD/Linux/Device.cpp
- pcsx2/PAD/Linux/Global.h
- pcsx2/PAD/Linux/InputManager.cpp
- pcsx2/PAD/Linux/InputManager.h
- pcsx2/PAD/Linux/linux.cpp
- pcsx2/PAD/Linux/wx_dialog/GamepadConfiguration.cpp
- pcsx2/PAD/Linux/wx_dialog/JoystickConfiguration.cpp
Fixes crash on PAD shutdown when using libc++
Crashes are not fun, even if they happen when the emulator is shutting down
Compile with libc++, and try to close the emulator
> Fix crashes in pad with libc++

- pcsx2/GS/GS.cpp
This will enable the checkbox for the software renderer, it has far more pros than cons (negligible performance hit)
Some games got better visuals but not limited to;
**Trapt:**
Left is correct, Right is wrong
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=eb0d1130-0113-11ec-abb7-b9a7ff2ee17c
**Toro games:**
Relevant: https://github.com/PCSX2/pcsx2/issues/4674
Wrong:
Correct:
**FFX:**
Relevant: https://github.com/PCSX2/pcsx2/issues/3341
Wrong:
Correct:
There are multitude of areas broken like on the stairs of the forest boss:
Relevant: https://github.com/PCSX2/pcsx2/issues/983
Wrong:
Correct:
And other games i don't know which are affected on SW.
Test any games that have an effect on Edge anti-aliasing (Software renderer only)
> GS-GUI: Enable Software Edge-Aliasing by default

- pcsx2/CMakeLists.txt
Re-add link against librt
Was accidentally removed in #4373
Try to build if you had trouble with librt failing since #4373 
@sjnewbury please test
> cmake: Fix missing librt include

- pcsx2/IopBios.cpp
Instead of blindly trusting whatever is given to us when RegisterIntrHandler is called, check to see if the IRQ line is in bounds with the `intrname` array.
Fixes the `kernel/iop/interrupt/register` ps2autotest.
The test would create an interrupt handler on line -1 and we would therefore index into `intrname[-1]`.
None.
> IOPBios: Fix OOB read when IRQ line is invalid.

- bin/GameIndex.yaml
Fixes #4650
Add EETiming to Ratchet and clank to avoid TLB misses.
Improvements ofcourse.
Run the right serial with and without automatic gamefixes.
> GameDB: Ratchet and Clank (EEtiming)

- cmake/FindVtune.cmake
- common/src/Utilities/CMakeLists.txt
- pcsx2/CMakeLists.txt
Utilities needs to include/link Vtune. 
Also update the search paths to the modern setup for intel tools.
> Cmake: Fix ENABLE_VTUNE build.

- pcsx2/gui/AppMain.cpp
Pass the ELF we are loading instead of whatever is in g_conf->CurrentIso if we are booting an ELF
This prevented no$ .sym files from being loaded for elfs and instead it would look for ones for whatever is in g_conf->CurrentIso
Try loading no$ symbols from elfs and isos
An easy format for a .sym file is
\<address> \<function name>
\<address> \<function name>
Name the .sym file <isoname>.sym or <elfname>.sym and have it in a folder _with the iso or elf_
MyShinyHomebrew.elf -> MyShinyHomebrew.sym
MyRippedGame.iso -> MyRippedGame.sym
> AppMain: Fix no$ symbol loading for elfs

- pcsx2/CMakeLists.txt
Fixes Windows CMake build
File was removed between the Windows CMake PR being made and getting merged
It's good when the CI builds
Make sure things build
> CMake: Match recently removed files from vcxproj

- linux_various/PCSX2.desktop.in
Disable gl threaded optimizations in Linux
Due to recent issues with Nvidia driver in Linux breaking the optimization. Pcsx2 has not run correctly with it enabled
Run Nvidia Linux and compare master to this performance-wise. Preferably in rolling release distros with the latest drivers
> Disable gl threaded optimization

- .github/workflows/linux-workflow.yml
- .github/workflows/scripts/linux/compile.sh
Moves ccache config environment variables from the build script to global across all CI steps
Also lowers the maximum cache size as one build is only 17mb of cache max
New testing step was missing the config, and causing ccache to complain and fail CI builds every now and then (no clue why it was so sporadic though)
Make sure CI builds
> GHActions:Linux: Make ccache config global

- pcsx2/SPU2/Dma.cpp
- pcsx2/SPU2/spu2sys.cpp
This also gets rid of a little kinda hack thing that was in there.
Modifies the timing value used when doing a read/write to use the size of the data transferred, but also adjusted it so IRQ's don't happen immediately after the transfer, which was technically incorrect.  Also gets rid of a small hack that was added a while back, which wasn't even done correctly anyway! yay me.
Fixes #4698 which was crashing on some PAL regions due to an IOP timing issue, probably caused by the DMA changes, but this should fix it.
Run games, make sure the sound works fine, especially if you know a game that's had audio problems in the past.
> SPU2: Adjust DMA timings for IRQ's and small packets

- pcsx2/SPU2/spu2.cpp
When changing the configuration for Audio when the emulator wasn't running caused the output modules (mainly port audio) to freak out.
Sound was going to hell if you went in to the sound config without the GS window being open causing a bit of mess with the output modules.
try changing SPU settings, output modules etc in different scenarios, like the game running, escaped from the game, before you start any game, after starting a new game, stuff like that.
> SPU2: Don't initialise sound buffer if it's not open

- pcsx2/SaveState.h
- pcsx2/VU.h
- pcsx2/VUmicro.cpp
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/microVU.cpp
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Macro.inl
Keeps note on how many cycles it needs for the next block to save exiting the EE JIT and entering the microVU JIT for no reason
Entering/exiting a JIT is slow, this hopefully reduces it at least a little, especially when COP2 is being hammered.
Test EE bound games, if your game isn't EE bound, you probably won't notice any difference.
Some example performance increases on my end
Ratchet & Clank
Master: 86-89fps
PR:	95-100fps
Tekken Tag
Master: ~73fps
PR:	~87fps
My Street
Master: 148-157fps
PR:	153-160fps
> VU: optimise entering VU JITs

- pcsx2/CMakeLists.txt
- pcsx2/PCSX2.rc
- pcsx2/SysForwardDefs.h
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
- pcsx2/resource.h
Adds PCSX2 version information to windows executables
Windows gets kinda fussy about exe's with no signature and no version information or description, this makes it a little less fussy.
Right now it shares version number with the rest of the app, but it cannot get the GIT revision because linux hates me and I can't think of a way to do it, but honestly 1.7.0 is enough information for the EXE properties.
Make sure it compiles, make sure the exe loads, check the windows properties->details for the exe, make sure it says PCSX2 PS2 emulator and version 1.7, all that fun stuff
> App: Add Windows exe version information

- pcsx2/GS/GS.cpp
7x was bullied for far too long (2520P / 4.5K resolution) is added for end-users.
Beyond 8x is debatable if there is a benefit or maximum framebuffer sizes that the API/PC/emulator can allow.
Open GS settings and change to 7x, then boot a game. Watching titlebar resolution or even the program log will help.
> GS-GUI: Add 7xMultiplier

- pcsx2/x86/microVU_Lower.inl
Unlike the interpreters, mVU shares an instruction table (is it a table?) and currently VU1 only instructions could execute on VU0.
With this change, on pass 1 in MicroVU IR it'll check if we are running in the VU0 rec and if so, NOP the instruction.
The instructions were
`xgkick`
All EFU instructions (including `waitp` and `mfp`)
`xtop`
Accuracy
[vu0xgkick.elf.zip](https://github.com/PCSX2/pcsx2/files/7095299/vu0xgkick.elf.zip)
Run this program, it uploads data to VU1 data memory and then calls `xgkick` on VU0.
In the current, broken, implementation your screen should turn blue. In a proper implementation it'll be black.
I haven't developed tests for EFU and TOP instructions, as I believe that would be unnecessary.
> MicroVU: Skip VU1 instructions on VU0

- bin/GameIndex.yaml
Update patches for Musashi Samurai Legend and Musashiden II
Previous patches caused TLB misses, which was unacceptable, this new version of the patch does not.
Run either of the two mentioned games, make sure they run okay, we need to check all regions.
If you have the following versions let us know
SCAJ-20137 (some NTSC version, not known)
SLPM-61117 Japanese trial version
This PR may require updates when I get information on who ported the EU and J versions of the patch.
> GameDB: Update patches for Musashi Samurai Legend/Musashiden II

- bin/GameIndex.yaml
- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD_internal.h
PR correctly sets the CDVD Status after a Pause command and corrects how the CDVD Status is handled during N-Commands. Also adjusted game fixes as necessary for known fixed games (below).
Several parts of Status handling were broken either due misunderstanding or not finding games it affected (in the case of the Pause command at least). I have also added an explanation of the bits in the status register to explain what they mean.
Run games, make sure they play okay.
Known fixed games:
Yoake no Mariko 2nd Act
ICO (China)
Fixes #4015
> CDVD: Fix up Pause and some Status behaviour

- common/IniInterface.cpp
fix a bug introduced by https://github.com/PCSX2/pcsx2/commit/38f1a9a762cea8e936351ae9e96384271d8abd90
I made an oversight and saved the ini in locale specific format which broke when the system locale didn't match PCSX2 locale
make sure you can change zoom/NTSC and PAL base framerate adjust and not have any issues.
fixes #4713
> common: fix locale oversight in IniInterface

- pcsx2/gui/Debugger/CtrlRegisterList.cpp
- pcsx2/gui/Debugger/CtrlRegisterList.h
Remove the option to view > 32 bit registers as 32 bit or 64 bit and instead display the _entire_ register value
There is no need to hide the upper bits of the registers, it also _greatly_ simplifies how the register list is drawn (or sized to be specific)
Launch a game, go to the debugger, and within the register view, play around with the categories, enabling and disabling resolving of string pointers and displaying VU0F registers as floats.
> Debugger: Purge 64 / 32 bit register view options

- pcsx2/R5900OpcodeImpl.cpp
This was zero extending because of the implicit promotion from signed->unsigned, causing incorrect high bits in the GPR.
Funnily enough, this was noted in the source, but implemented incorrectly.
It was incorrect :)
Probably not much dependent on this, and it's interpreter only.
> R5900: Fix LWL not sign extending in interpreter

- pcsx2/GS.cpp
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/Panels/VideoPanel.cpp
Changes the way the limiter values are saved and stored such that they match the stored values from before https://github.com/PCSX2/pcsx2/commit/38f1a9a762cea8e936351ae9e96384271d8abd90.
After an internal discussion, it has been decided to drop the policy that we don't support using older configs between versions and making recommendations against it as it has proved too impractical and an unreasonable burden to our users. As such, moving forward we will support them doing so and maintain backwards compatibility with older inis (at least until such time that doing so becomes impossible due to a change to a different system such as yaml). This PR makes the limiter settings backwards compatible with settings before https://github.com/PCSX2/pcsx2/commit/38f1a9a762cea8e936351ae9e96384271d8abd9 …
> config: normalize limiter values before saving

- bin/GameIndex.yaml
- pcsx2/Gif.cpp
- pcsx2/Gif.h
- pcsx2/Gif_Unit.h
- pcsx2/SaveState.h
- pcsx2/VU.h
- pcsx2/VU0.cpp
- pcsx2/VU0micro.cpp
- pcsx2/VU0microInterp.cpp
- pcsx2/VU1microInterp.cpp
- pcsx2/VUflags.cpp
- pcsx2/VUmicro.cpp
- pcsx2/VUmicro.h
- pcsx2/VUops.cpp
- pcsx2/VUops.h
- pcsx2/Vif0_Dma.cpp
- pcsx2/Vif1_Dma.cpp
- pcsx2/Vif_Codes.cpp
- pcsx2/Vif_Dma.h
- pcsx2/Vif_Transfer.cpp
- pcsx2/Vif_Unpack.cpp
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_IR.h
- pcsx2/x86/microVU_Macro.inl
- pcsx2/x86/newVif_Unpack.cpp
Overhauls the VU interpreters to be as accurate as microVU, and then some.  Still some clean up work to do (could make the new XGKick stuff one function, for example), but should be head and shoulders above master and be twice as fast too.
Our interpreters were old, unfinished, broken and slow, this PR aims to resolve all of that.
Just test any games, compare them to microVU in terms of compatibility, make sure they are as good or better.
Games fixes by this (only in the interpreters currently)
WRC World Championship no longer needs patches
Tennis Court Smash no longer has SPS
Fixes #1851
> Vu int improve

- common/vsprops/CommonLibrary.props
when I merged the utils and emitter project in #4707 I neglected to update the SVNRootDir macro so it was causing common libraries to not be written to the correct directory.
don't use this macro anymore so just remove it make output relative to solution dir instead
fixes bug
build
> vs: fix an oversight

- bin/GameIndex.yaml
Patch for Playmobil: Hype - The Time Quest
Rounding was off for text elements on the screen rendering them invisible, this patch adjusts that so the text is visible
Play the game, check the text
Fixes #2944
> GameDB: Patch rounding problem in Playmobil Hype The Time Quest

- bin/GameIndex.yaml
The automatic gamefixes were incorrect as it would SPS. Fix the SPS with nearest VuRound and then Extra + Preserve sign for VuClamp. God will be pleased.
Spikies are not a fun way for gamers.
Set vuround to nearest and vuclamp to highest  / check automatic gamefixes
> GameDB: Katamari Games

- bin/GameIndex.yaml
Fixes SPS (Spiky Polygon Syndrome) for quite some sports games.
Mostly missing RTL sports clamp modes. People knew the fixes on the forum but don't make PR or didn't tell anyone. Testers hoarding bugs :P
Check if you have any weird graphical overlays.
Relevant SPS:
This is an **unrelated** SPS:
If you see this on any game, it's either fixed with any of the following settings:
> GameDB: Sports (RTL)

- pcsx2/SPU2/spu2sys.cpp
Disallow KeyOn less than 2T (768x2 cycles) of the previous KeyOn for a voice.
Fixes Legend of Spyro New Beginning hang
KeyOn/Off events shouldn't happen within 2T's of the last one for each voice (possibly the whole register, but unsure on that, per voice seems okay)
uhh, any games you know had problems previously with delay cycles, that would be great.
> SPU2: Disallow KeyOn within 2T of last KeyOn

- bin/GameIndex.yaml
- pcsx2/Gif_Unit.h
- pcsx2/VU.h
- pcsx2/VUops.cpp
- pcsx2/VUops.h
- pcsx2/gui/Panels/GameFixesPanel.cpp
- pcsx2/x86/microVU_Analyze.inl
- pcsx2/x86/microVU_Branch.inl
- pcsx2/x86/microVU_Compile.inl
- pcsx2/x86/microVU_IR.h
- pcsx2/x86/microVU_Lower.inl
- pcsx2/x86/microVU_Misc.h
- pcsx2/x86/microVU_Misc.inl
Replaces XGKick hack option with an XGKick Sync option which provides accurate behaviour for the VU
Fixes Tennis Court Smash and Love Smash games which previously couldn't be fixed.
WRC no longer requires a patch, just the xgkickhack option.
Simple 2000 Series Vol.26 - The Pinball X 3 SPS and console spam.
Note: it's not a hack anymore, it just has to be called that in the gamedb :P
Some games couldn't be fixes with the traditional hack.
Try games that require the XGKick hack, make sure they still work (you can search the gamedb for "XGKick" if you need an aid).
If you have games that have always experienced errors in the console (GS packet exceeds VU memory) or spikey polygons, give the new XGKick Sync option a try, it might fix it.
> microVU: Replace XGKick hack with synced XGKick option

- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
Added SDR/SDL, LDR/LDL instructions, in all their evilness (most of the code is just reading/writing the value in memory)
Stops the EE JIT dropping down to the interpreter for these instructions, theoretically faster
Play games, make sure no new bad graphics or crashes happen.
> EE JIT: Implement SDR/SDL, LDR/LDL instructions

- bin/GameIndex.yaml
- pcsx2/SPR.cpp
- pcsx2/VU0.cpp
- pcsx2/VUmicro.cpp
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/microVU_Macro.inl
Recent VU timing changes have made things a bit of a mess in the pursuit of speed, this aims to increase the sync where required, mainly when VU Kickstart is disabled.  This does mean some games will be slightly slower than recent changes, but not by too much, hopefully. There isn't much I can do about that, sorry.
A few games were breaking easily due to recent timing loosening, this resolves that to an appropriate level.
test games, especially those whos physics freaked out recently.
> VU: Sync tighter when VU Kickstart is disabled + Improved M-Bit Sync

- bin/GameIndex.yaml
GameDB: add VU clamping to 'Enthusia Professional Racing'
adds VU clamping to 'Enthusia Professional Racing'
Fixes games 
look at the CI
> GameDB: add VU clamping to 'Enthusia Professional Racing'

- pcsx2/gui/Panels/BiosSelectorPanel.cpp
When you enumerate through your folder with your bios(es), highlight the first bios in the bios list, **UNLESS one of the bioses match the currently loaded one.** (The bold here is current behaviour and not new).
Stops things like this from happening for first time users. (Not my picture)
With this PR, that bios would be selected and they wouldn't have had to ask why their bios was invalid.
Delete your configuration, do a first time setup, and see if a bios is selected automatically.
> UI: Select a bios by default

- pcsx2/x86/iCore.cpp
- pcsx2/x86/iCore.h
- pcsx2/x86/iR5900.h
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/ix86-32/iR5900Templates.cpp
- pcsx2/x86/microVU_IR.h
- pcsx2/x86/microVU_Macro.inl
- pcsx2/x86/microVU_Misc.h
- pcsx2/x86/microVU_Upper.inl
Removes the flushes from COP2 calls and instead backs up the registers the EE is using
Flushing kind of destroys EE optimisations, we could possibly do this better, but it's a start point.
just make sure games still work and don't glitch out.
> COP2: smart register allocation for COP2 commands

- bin/GameIndex.yaml
Seems there were still some missing serials, it's pretty hard to track if there are dozen more but it did had a console ban there after short-lived debut.
I like thicc gamedatabases
Doubt many even have a chinese version but you can see if it displays in the program log.
> GameDB: Add missing chinese entries v2

- common/Pcsx2Defs.h
- pcsx2/CMakeLists.txt
- pcsx2/Cache.cpp
- pcsx2/Cache.h
- pcsx2/HwRead.cpp
- pcsx2/IPU/IPU.cpp
- pcsx2/IPU/IPU.h
- pcsx2/Memory.cpp
- pcsx2/Memory.h
- pcsx2/SingleRegisterTypes.h
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
- pcsx2/ps2/HwInternal.h
- pcsx2/vtlb.cpp
- pcsx2/vtlb.h
- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
- pcsx2/x86/ix86-32/recVTLB.cpp
Switches loading of large memory values to go through xmm registers instead of pointers
Also adds a few optimizations for swl/swr/sdl/sdr that skips loading the previous value if it won't be needed
Slightly faster in some cases, especially for the newly added ldl/ldr/sdl/sdr which previously had to store to memory and then immediately reload
Make sure things still work
> Load 64-bit/128-bit values through xmm registers

- 3rdparty/portaudio/build/msvc/portaudio.vcxproj
Standalone DirectSound was removed a while ago, Portaudio one was still available and it seems broken. Since Portaudio API is backend agnostic, it's rather unlikely that PCSX2 is doing something wrong and more likely that DS is just crap.
DirectSound is legacy and has zero advantages over WASAPI (offered via Portaudio) and XAudio2 (offered standalone).
Verify that sound on Windows works.
> PortAudio: Remove DirectSound backend

- pcsx2/gui/AppAssert.cpp
- pcsx2/gui/Dialogs/ConfirmationDialogs.cpp
- Prevents a crash caused by our stack trace code not being equipped to handle stack traces outside of PCSX2
- Removes ineffective right alignment flags that cause an assertion failure when displaying our assertion failure dialog on wx 3.1.5
If I wanted PCSX2 to crash on assertion failure I could have used libc `assert()`
Compile with wx 3.1.5 and trigger an assertion, PCSX2 should display an assertion dialog and not crash
> Fix crash on assertion in newer wx

- common/Console.cpp
- common/Console.h
- pcsx2/gui/ConsoleLogger.cpp
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
Enables the "Program Log to Stdio" menu option on macOS
Also makes it check the console for color support before trying to use color escapes
It's useful on macOS too
Make sure option works on macOS and Linux
> Stdio console on mac

- pcsx2/GS/GSState.cpp
previous code didn't test TH which was a problem for vampire nights because they upload a c16 texture to the same address but with a different height
fixes #4805
make sure nothing has any perf issues
> gs: test for th for tex0 flush

- pcsx2/AsyncFileReader.h
- pcsx2/Darwin/DarwinFlatFileReader.cpp
Updates DarwinFlatFileReader to fall back to a synchronous read if the aio read fails for any reason
Even on systems where everything is working, it's possible to get an `EAGAIN` if the system is out of async reading resources.  We've had one report so far of such a thing happening.
Test on macOS or BSD and make sure things still work.  I don't expect to get much testing of the failure case as I have yet to see an `EAGAIN` on my computer, but it does still work for me if I define `DISABLE_AIO`
> macOS: Fix async file reader error handling

- common/Darwin/DarwinMisc.cpp
Clean out half-broken attempts to single-initialize values that only ever get read once
New ones are much smaller and cleaner looking
(Mac only): Confirm that the system info printout hasn't changed
> Clean up DarwinMisc

- bin/GameIndex.yaml
GameDB: add EEclamping to the 'Virtual On' series
adds  EEclamping to the 'Virtual On' series and corrects gameDB names ,  
fixes #4806 
look at CI , test said games
> GameDB: add EEclamping to the 'Virtual On' series

- pcsx2/DebugTools/DebugInterface.cpp
- pcsx2/GS.h
- pcsx2/GS/GSCapture.cpp
- pcsx2/GS/Renderers/DX11/GSTexture11.cpp
- pcsx2/MTGS.cpp
- pcsx2/PAD/Windows/PAD.cpp
- pcsx2/SPU2/SndOut_Portaudio.cpp
- pcsx2/SPU2/spu2.cpp
- pcsx2/System/SysCoreThread.cpp
- pcsx2/System/SysThreadBase.cpp
- pcsx2/System/SysThreads.h
- pcsx2/gui/AppCoreThread.cpp
- pcsx2/gui/AppCoreThread.h
- pcsx2/gui/MainMenuClicks.cpp
- pcsx2/gui/SysState.cpp
This PR fixes two regressions caused by the ATL -> WIL migration (#4523):
* A "loudly failing" `wil::CoInitializeEx_failfast` revealed that subsystems (SPU, PAD etc.) initialization/cleanup was all over the place threading wise - initial setups were done on the **EE Core** thread, while teardown/reinit caused by opening settings was done on the **Main Thread**. This didn't play nice with COM initializations (and maybe other things), so I made sure PCSX2 delegates teardown/init to an appropriate thread.
* `GSSource` is implemented in means of `CUnknown`, which appears to violate one of COM rules and creates an object with a refcount of 0 instead of 1. I updated the code to account for this, together with a lengthy comment explaining what needs to be changed if this ever changes (as then …
> Fix regressions from WIL migration

- pcsx2/x86/microVU_Analyze.inl
Amendment of #4724 
I reverted something and didn't look closely enough, `if (branchType <= 2 && branchType >= 9)` is always going to be false.
I broke it.
No need, this was old behaviour before my revert.
> MicroVU: Fix branch type detection

- pcsx2/SPU2/Windows/SndOut_XAudio2.cpp
This PR refactors SPU2's XAudio2 implementation:
* Code cleaned up wherever possible, using more modern C++ features such as `override`.
* Over-cautious if checks and a critical section used to work around the actual issues, and have now been removed.
* Fixed shutdown flow that would cause the code to hit a race condition when destroying the source voice - `DestroyVoice` forces all buffers to end, and the current implementation of `OnBufferEnd` could have hit a nullptr and/or reference freed memory when executed before teardown.
* Added a `XAUDIO2_DEBUG` define to enable debug breaks in XAudio2, might be useful if any XA2 issues ever appear anywhere.
Easier to maintain code, and most importantly - no random memory corruptions/crashes on shutdown.
Verify that XAudio2 still works fine, …
> SPU2: Refactor SndOut_XAudio2.cpp

- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
Fix a minor regression that made the OGL renderer crash on linux (pr #4740 )
It made OGL HW no longer useable, so it needed a fix.
See if it doesn't crash anymore.
> GS-ogl: Fix regression that broke linux HW mode

- common/Perf.cpp
Perf.cpp relies on the _1kb,_4kb, etc constants defined in common/Dependencies.h
Building with USE_VTUNE defined were broken
(ENABLE_VTUNE is set when USE_VTUNE is defined)
Try to build with vtune stupport
On linux it would be `cmake <your cmake params> -DUSE_VTUNE=1`
Works for me(tm)
> Perf: Fix missing include breaking builds with USE_VTUNE enabled

- pcsx2/CMakeLists.txt
- pcsx2/DEV9/Config.h
- pcsx2/DEV9/DEV9.cpp
- pcsx2/DEV9/DEV9.h
- pcsx2/DEV9/DEV9Config.cpp
- pcsx2/DEV9/InternalServers/DNS_Logger.cpp
- pcsx2/DEV9/InternalServers/DNS_Logger.h
- pcsx2/DEV9/InternalServers/DNS_Server.cpp
- pcsx2/DEV9/InternalServers/DNS_Server.h
- pcsx2/DEV9/Linux/Config.cpp
- pcsx2/DEV9/Linux/Linux.cpp
- pcsx2/DEV9/PacketReader/IP/UDP/DNS/DNS_Enums.h
- pcsx2/DEV9/Win32/DEV9WinConfig.cpp
- pcsx2/DEV9/Win32/Win32.cpp
- pcsx2/DEV9/Win32/tap-win32.cpp
- pcsx2/DEV9/net.cpp
- pcsx2/DEV9/net.h
- pcsx2/DEV9/pcap_io.cpp
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
Using the CLR-DEV9 approach to resolve https://github.com/PCSX2/pcsx2/issues/4151
Depends on (and includes) #4301
This is a port of CLR-DEV9's DNS server, adapted to work with TAP and pcap (CLR-DEV9's was winsock only)
This PR adds an internal DNS server, that can be opted in by setting you DNS in the PS2 Network config to 192.0.2.1.
It features its own host list (DEV9Hosts.ini), allowing you to remap a url to a different IP address.
Note that while CLR-DEV9 used XML for its settings, this version uses PCSX2's iniInterface format for its host file.
If the internal DNS fails to find an url in its host list, is uses OS specific functions to look up the address.
The internal DNS will replace 127.0.0.1 with the PC's local IP (specifically the address assigned to the selected adapter), …
> DEV9: Add Internal DNS server

- .github/workflows/scripts/validation/lint-gamedb/lint-gamedb.py
- bin/GameIndex.yaml
- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/gui/Panels/GameFixesPanel.cpp
- pcsx2/x86/microVU_Upper.inl
Moves the VU Overflow checks for MAC and Status flags to a game fix so it can be optionally enabled. Also rearranged the game fixes panel to make a bit more sense by grouping fixes together.
x86 can't really check for overflowed PS2 floats because we don't have the range and it's not really possible to guess. Turns out our implementation breaks Chronicles or Narnia - Prince Caspian, but it's required for Superman Returns.
Fixes #4841
Not really much needs testing beyond Superman Returns and Chronicles of Narnia - Prince Caspian. I guess make sure the UI doesn't explode and the hacks turn on the correct hack when you manually enable them.
> Move Vu overflow flag checks to a Gamefix + reorganise panel

- pcsx2/gui/Debugger/CtrlRegisterList.cpp
- pcsx2/x86/iCore.cpp
Fix some Wsign-compare warnings in iCore , fix Wimplicit-fallthrough warning in debugger.
The less warnings the better.
See if gcc complains still
> Core: Fix some Wsign-compare warnings, fix Wimplicit-fallthrough warning

- pcsx2/Patch.cpp
When PCSX2 cannot find a cheats file, `Not found Cheats file: C:\\pcsx2\cheats\xxxxxxxx.pnach` should be displayed.
On master, however, if you uncheck "Use default setting" and select a different folder in Folder Settings, that line will not be displayed.
`PathDefs::GetCheats()` should be used only for default value initialization. 
Enable PCSX2 Program Log >Sources>Dev/verbose. Set non-default cheats folder, and make sure this folder is empty.
Run the game, enable cheats and check if the log `Not found Cheats file:<FILEPATH>.pnach` is displayed.
> Fix Patch file path check when default setting is not used

- pcsx2/USB/usb-eyetoy/cam-windows.cpp
- pcsx2/USB/usb-eyetoy/cam-windows.h
Initialize multi-threaded COM using `wil` helpers.
Fix crashing caused by single/multi-threaded CoInitialize conflict.
Set USB to EyeToy with directshow api and run a game.
> USB: dshow: Initialize multi-threaded COM libs

- common/Mutex.cpp
Going through my Qt branch and pulling out stuff that isn't dependent on the library refactor. This one only happens when you compile without `wxUSE_GUI` (which is done for Qt).
Preparation for a future without wx gui being compiled.
None needed, since this code isn't compiled in current pcsx2 builds.
> Common/Mutex: Fix compiling without wxUSE_GUI

- common/StringHelpers.h
`pxsPtr` currently truncates 64-bit pointers to 32-bit. This is noticeable when printing the virtual addresses on startup, for example.
Long term I want to get rid of all this wxString nonsense, but this is a stopgap solution for now.
It's displaying truncated/incorrect values.
Nothing to really test here, it's just debugging as far as I'm aware.
> Common/StringHelpers: Fix printing of 64-bit pointers

- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
Don't write clamped depth test value to depth buffer when ZMSK is enabled.
We shouldn't write the clamped depth test value to the depth buffer when ZMSK is enabled.
Fixes missing shadows in Kingdom Hearts: Chain of Memories.
https://forums.pcsx2.net/Thread-Kingdom-Hearts-Re-Chain-of-Memories-USA-shadow-and-black-line-bug
> GS-hw: Don't write clamped depth test value to depth buffer when ZMSK is enabled.

- pcsx2/CDVD/CDVDaccess.cpp
I noticed this one when I had reads broken - if you manage to load an invalid ISO image, it'll throw this exception on the CPU thread.
Also replaced an explicit unique_ptr construction with make_unique.
This shouldn't be an exception in the first place, but at least now it doesn't kill the CPU thread/SIGABRT.
None really needed, since it's an exceptional (hah) scenario. I guess you could try loading a disc image without a valid ISO structure.
> CDVD: Fix possible uncaught exception in CheckDiskTypeFS

- common/CMakeLists.txt
- common/FastJmp.asm
- common/FastJmp.cpp
- common/FastJmp.h
- common/Pcsx2Defs.h
- common/common.vcxproj
- common/common.vcxproj.filters
- pcsx2/R5900.cpp
- pcsx2/x86/ix86-32/iR5900-32.cpp
Currently exiting the recompiler (e.g. toggling frame limiting) crashes the emulator in 64-bit Windows builds, as it attempts to longjmp across the recompiler stack frames, which don't have any unwind information.
> Unhandled exception at 0x00007FFB7D43042D (ntdll.dll) in pcsx2x64-dbg.exe: 0xC00000FF: A malformed function table was encountered during an unwind operation.
This PR adds a replacement implementation for longjmp which simply saves/restores registers, and doesn't care about unwinding the stack. You shouldn't be creating any complex C++ objects between the recompiler exit point and where the execution state is checked anyway.
I used inline asm for Linux, and a separate asm file for Windows, mainly just to avoid the headache of cmake and supporting .s files. Strictly speaking we …
> EE: Fix JIT exits on 64-bit Windows

- pcsx2/GS/GS.cpp
- pcsx2/GS/Renderers/OpenGL/GSVertexArrayOGL.h
- pcsx2/gui/Debugger/DisassemblyDialog.cpp
- pcsx2/gui/Panels/BiosSelectorPanel.cpp
- tools/bin2cpp/bin2cpp.cpp
These have been pestering me for a while.
Making MSVC shush.
Shouldn't be any functional changes here.
> Fix some compile warnings spewed by MSVC x64

- pcsx2/ps2/Iop/IopHwRead.cpp
- pcsx2/ps2/pgif.cpp
Remove GP0 ringbuffer clear on commands GP1 (00), and GP1 (01). 
Additionally remove annoying log from devbuilds, this one can be read from pgifLogs now. 
This is done internally in ps1drv. First fifo_GP0_ready_for_data bit is set to 0, then driver read GP0 fifo into void until fifo is empty. 
Test some PS1 games for eventual regressions. But this shouldn't affect too much in terms of compatibility. Castlevania SOTN, THPS2, and RE2 still work like before.
> PGIF: Remove force fifo clear on GP1 (00-01)

- .github/workflows/linux-workflow.yml
- .github/workflows/macos-workflow.yml
- .github/workflows/windows-workflow.yml
- cmake/BuildParameters.cmake
- pcsx2/CMakeLists.txt
Add option to cmake that runs LTO on the core emulator but nothing else, and enable it in the CI
The intermediate files for LTO on everything on Windows+Ninja manage to take up so much disk space we fill up the entire CI runner, which isn't great.  Running LTO on core only uses up about 230MB of (zstd-compressed) buildcache, so I assume 1-2gb of disk, which isn't anywhere close to the ~12GB we're allotted, so I don't expect to run out of space any time soon.
Test CMake binary and compare to msbuild SSE4 binaries, make sure performance is similar
> Add partial LTO to CMake

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD.h
- pcsx2/CDVD/CDVD_internal.h
- pcsx2/CDVD/CDVDaccess.h
- pcsx2/IopHw.h
- pcsx2/R3000A.cpp
Implement correct SpindleCtrl handling
Semi decouple end of CDVD DMA's
Fix alternative reading method for reading not picking the correct speeds for DVD's
Restores partially working Audio CD playback we had before.
CDVD was always full speed all the time regardless of the spindle settings which could have caused problems in reading on some games.  Also the CDRead function was not exclusive for CD's but it was using CD timings.
Test games and stuff, especially ones listed in #4117  (sorry but Silent Hill 2 still sucks, something else going on)
Seems to resolve the Digital Devil Saga videos not playing
Also the DMA timing change resolved the remaining texture issues on Shadowman
> CDVD: Implement correct SpindleCtrl handling

- pcsx2/pcsx2.vcxproj
CMake does this by default.  This way we can make non-pch builds not take forever by only including what's required instead of the entire pch
> Force-include pch on vs

- common/emitter/cpudetect.cpp
- common/emitter/tools.h
- pcsx2/GS/Renderers/Common/GSFunctionMap.h
- pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
- pcsx2/GS/Renderers/SW/GSDrawScanline.h
- pcsx2/GS/Renderers/SW/GSRasterizer.cpp
- pcsx2/GS/Renderers/SW/GSRasterizer.h
Makes the printout made by this line easier to read https://github.com/PCSX2/pcsx2/blob/ab64023e56ea31164396148272da721559888bbc/pcsx2/GS/Renderers/SW/GSRendererSW.cpp#L140
<details>
<summary>Before</summary>
```
GS stats
[0d1515112e8864]*   0.00%  0.00% f   60 t       131380 p            0 w            0 tpp    0 tpf      2189 ppf         0
[11151b3fce8164]*   0.01%  0.00% f   60 t       287660 p          180 w        60660 tpp 1598 tpf      4794 ppf         3
[0910193fce8064]*   0.01%  0.00% f   60 t       315968 p          240 w        21300 tpp 1316 tpf      5266 ppf         4
[0d181b3fce8164]*   0.00%  0.00% f  120 t       214132 p            0 w            0 tpp    0 tpf      1784 ppf         0
[09181f112e8764]*   0.01%  0.01% f   60 t       350288 p           60 w          780 tpp …
```
> Improved stats printout from sw renderer

- pcsx2/GS/Renderers/Common/GSOsdManager.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/HW/GSRendererHW.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
Use clamp instead of min max for OSD and Shade Boost.
Don't allow negative value for upscale multiplier, avoids a black screen.
Cleaner code, avoids a black screen if upscale multiplier is negative.
Make sure Shade boost, osd, upscaling still works.
Note: these changes are mostly for editing ini manually.
> GS: Cleanup ini ranges for some values.

- pcsx2/gui/Debugger/CtrlMemView.cpp
Was I drunk?
I was going to address 1 when you click "Goto in Disasm" in the memory view
It's wrong and broken
Try the "Goto In Disasm" Context menu option in the memory viewer.
Fixes #4864
> Debugger: Fix Goto in Disasm option for memory view

- pcsx2/Config.h
- pcsx2/MemoryCardFile.cpp
- pcsx2/MemoryCardFolder.cpp
- pcsx2/Pcsx2Config.cpp
- pcsx2/gui/Dialogs/ConvertMemoryCardDialog.cpp
- pcsx2/gui/Panels/MemoryCardListPanel.cpp
- pcsx2/gui/Panels/MemoryCardPanels.h
Fixed memory card folders being flagged as a non-present memory card if booting without opening the config dialog.
Also converted the type enum to a scoped enum, since I missed this in the other PR.
Regression from #4786.
Make sure memory card folders load on a clean boot. I've checked it myself and they seem okay now.
Fixes #4862
> Config: Fix folder memory cards initial load

- pcsx2/GS/Window/GSSettingsDlg.cpp
Fix OSD, Shade Boost slider values not showing.
Fixes #4775
Test OSD, Shade Boost sliders if the values now display properly.
> GS: Fix OSD, Shade Boost slider values not showing.

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD.h
- pcsx2/CDVD/CDVD_internal.h
- pcsx2/R5900.cpp
- pcsx2/gui/AppCoreThread.cpp
Inspired by the work by fldef in the repo here https://github.com/fldef/pcsx2-fldef and extended to work well with physical discs too
Disc Swapping was completely broken in games which required it. This should hopefully resolve that.
Test swapping discs in games which need it, or the BIOS.  Dance Factory kinda works, but it doesn't display the track names, or something.
Fixes #3533
Fixes #3355
Fixes #91
Fixes Dance Factory (kinda, track names kinda freak out but not sure why that is, could be an issue with the DVD reader code, or just lack of track names)
Hopefully fixes everything on #4851
> CDVD: Implement Disc Swapping

- pcsx2/GS.h
- pcsx2/System/SysThreads.h
- pcsx2/gui/AppCoreThread.h
fixes warning spam on gcc
be nice to see warnings we actually care about instead of a bunch of spam about not using `override`
if it builds it builds
> Fixup a bunch of warning spam

- pcsx2/Config.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
More regression fixes from the decoupling PR - this time, trace logs weren't being saved to the correct section, and memory cards setting changes weren't applying.
I also clang-formatted Config.h and Pcsx2Config.cpp, as they were an inconsistent mess. First two commits are the ones to look at.
Regressions :(
Make sure memory card hotswitching works as expected now.
> Fix memory card saving and trace log setting loading/saving

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD_internal.h
- pcsx2/IopHw.h
- pcsx2/R3000A.cpp
Changes the block/sector timing to be based on sector per second instead of bytes per second
Also added rotational latency for reads which are not sequential to simulate waiting for the disc to go around, it's probably slower than it needs to be, but better safe than sorry (Shadowman)
Doing timing by sectors per second is pretty much staple for PS1 emulators, but also calculating by the sector size based on a base CD speed (specifically) is incorrect, as a CD can read 75 sectors per second if in Data mode or CD Audio mode, despite CD Audio sectors being bigger.  This eradicates that problem.  The rotational latency adjusts the read timings for games such as Shadowman.  Also removed the DMA timing after the read, that probably isn't really needed.
Uhh test timing sensitive games I guess …
> CDVD: Time reads by sectors per second instead of bytes + Some rotational latency

- pcsx2/GS/GSState.cpp
Allow draws to happen regardless of frame/z format, log invalid draws that matter
Star Ocean 3 was setting the Z Buffer to an invalid storage format, but the Z was masked and there was no depth test, so its format was irrelevant. Previously the draw got skipped, but if the draw is wrong, it's going to be broken anyway.
Test Star Ocean 3 battle transitions, uhh, not sure what else it'll affect, so just try random stuff to make sure it's okay I guess.
Fixes #4948
> GS: Let draw happen even if invalid, log invalid draws

- pcsx2/GS/GSState.cpp
- pcsx2/SaveState.h
Fixes compatibility with old savestates + remove PRMODE which is no longer used.  Also bumps savestate version.
Recent changes temporarily broke compat with older states since it was merged before the PR was completely ready.
Test GS Dumps and savestates from PCSX2 to make sure they all work ok.
> GS: Further state cleanup + fixes for older dump compatibility

- pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Changes the texture propagation on GS download to not modify 24bit format avoiding alpha loss
The previous change for Shattered Memories, while correct, didn't account for 24bit textures which have no alpha
Test Mana Khemia and Silent Hill games that had flashlight problems, make sure everything is still ok
Fixes #4928
Also fixes text on Fatal Frame 2 disappearing.
> GS: Don't propagate 24bit textures on download

- pcsx2/GS/GSVector4.h
- pcsx2/GS/Renderers/Common/GSVertexTrace.cpp
- pcsx2/GS/Renderers/Common/GSVertexTrace.h
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
*when you spend a bunch of time optimizing a function because you think it accounts for 30% of runtime but that was actually due to the compiler being stupid and not issues with the algorithm*
This PR contains the following changes:
- Prevents clang from optimizing out our denormal-removal shuffles (10x faster than before for people who compile with clang!)
- Run divides on four elements at a time instead of two elements and two useless numbers
- ~~Run per-vertex instead of per-primitive for all things that need to apply to all vertices of a primitive anyways (prevents double-checking vertices in triangle strips, and also reduces pointer chases in the main loop)~~ This broke stuff
- Remove inaccurate stq
- With the above division improvements, on processors with partially-pipelined …
> GSVertexTrace::FindMinMax improvements

- pcsx2/GS/GS.cpp
- pcsx2/GS/Renderers/OpenGL/GLLoader.cpp
- pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp
- pcsx2/GS/config.h
Remove extension checks for:
GL_ARB_compute_shader,
GL_ARB_shader_storage_buffer_object,
GL_ARB_texture_view,
GL_ARB_vertex_attrib_binding,
GL_ARB_multi_bind
Put GL_ARB_get_texture_sub_image check under a define.
Not yet used, code debt.
Opengl just works, make sure extensions really aren't used.
> GS-ogl: Remove checks for extensions we don't yet use.

- pcsx2/x86/ix86-32/iR5900LoadStore.cpp
Fixes condition on LDL/LDR instruction where if _Rs_ is constant and _Rt_ is the same register, we would lose the shift value due to the logic of the instruction
Disaster Report Michigan was broken due to the shift value being lost on aforementioned instructions
Make sure games work okay I guess, especially Disaster Report
> EE JIT: Backup shift on LDR/L if rs==rt

- pcsx2/GS/GSClut.cpp
- pcsx2/GS/GSClut.h
Fixes CLUT writing for games which use an offset to write to sections of the CLUT in PSMCT32 mode with I8. Wraps CLUT memory when reading with an offset
Writing with offset was broken and previously used the "clut_reload_on_draw" hack, which wasn't really the solution. Also remove CLUT memory wrapping code (by duplicating it) didn't really work, so now it properly wraps.
Test games mentioned, make sure the colours are correct. Test other games just to make sure nothing is broken.
Games which previously needed the load_clut_before_draw hack
Cabela's Hunting games
Harley Davidson
Fixes #1597
Also fixes Romance of the Three Kingdoms games colours.
Fixes #1628
Fixes #2390
The History Channel: Battle for the Pacific 
Fixes #4396 
Other games apparently fixed
NPPL Championship Paintball 2009 …
> GS: Fix up CLUT offset handling in 32bit I8 mode

- .github/workflows/scripts/releases/announce-release/index.js
Some polish on the new webhook:
- remove redundant text from the link text (its obvious it's pcsx2, and the version number is already stated, its under a platform header, and the file extension will be apparent when its clicked)
- add the release notes to the announcement which are:
- links to relevant PRs
- in the absence of a PR (direct commit) it uses the commit message.
Better is better
I ran it locally with the payload from here https://api.github.com/repos/PCSX2/pcsx2/releases/tags/v1.7.2010
Before:
After
> actions: cleanup discord embed links and add release body

- pcsx2/System.cpp
adds  compile date to the  program log of nightly builds
to make it  easier for users to find when the nightly build was built
> CI:Add build date to program log of nightly builds

- cmake/BuildParameters.cmake
- common/Darwin/DarwinThreads.cpp
- pcsx2/GS/GSPerfMon.cpp
- pcsx2/SaveState.cpp
Fixes a number of random minor issues on macOS
Also increases the macOS deployment target so the CI stops complaining at people who use `std::optional`'s `value()` method
Fixes things
Nothing in particular
> Miscellaneous fixes for macOS

- pcsx2/PAD/Linux/wx_dialog/dialog.cpp
- pcsx2/PAD/Linux/wx_dialog/dialog.h
Adds the ability to abort ‘set all buttons’ by pressing ESC, currently the user has to cycle the the entire mapping to regain control.  
The screen was also cutting off abit of the lower buttons and controller label so just bumped up the default height.
Also it seems to be a bit unclear as to if the gamepad keys can be remapped in the GUI (as seen in these  issues: #4414 #4714  ) so just clarified in the dialog box to hopefully reduce frustration. 
Note: made the 'if' comment style consistent within the file. Translated the french comment, was translated before but removed in a merge?
Adding quality of life improvements to the linux Gamepad Settings
Open up the ‘Gamepad Settings’ config, select ‘Set All Buttons’, press the ESC key to abort
> GUI(linux): Abort 'set all buttons' & fixed window size

- bin/GameIndex.yaml
adds EE clamping to 'Shadow of Zorro' and 'Evil Twin - Cyprien's Chronicles'
fixes said games
look at the CI
> GameDB: add EE clamping to 'Shadow of Zorro' and 'Evil Twin - Cyprien's Chronicles'

- pcsx2/CDVD/CDVD.cpp
When making an input recording, boot the game with a constant RTC.
It's recommended to make recordings from booting - rather than from save-states.  This is to ensure maximum backwards compatibility across emulator versions (save-states often break).
However, there is a problem with that approach currently.  Everytime you boot, the wall clock time obviously changes and for games that use the RTC to seed RNG, etc, that's a problem.  So the solution is simple, make it always the same.
- Make a recording from boot -- you should see the added log, showing that it used the constant rtc instead.
- The log should not fire (and therefore, wall-clock RTC is used) when booting a game outside of an input recording
- Test games that are sensitive to this sort of thing (ie. MGS3)
- Make sure the log …
> input-rec: Use a constant RTC for power-on recordings

- pcsx2/CDVD/CDVD.cpp
I committed the wrong year...oops
The current code most likely would prevent booting on certain games (MGS3 for example), as the year would always be 2002.
Double check that im not lying this time.
> CDVD: set the correct RTC year when input recording

- pcsx2/gui/Debugger/CtrlRegisterList.cpp
- pcsx2/gui/Debugger/CtrlRegisterList.h
On DPIs that weren't 100%, the register list would be cut off. 
This was 125% dpi for example
Note how you're missing the X column
This is the fixed version:
The debugger was unusable for people running things other than 100% DPI
Test different DPIs and make sure the register list isn't cut off.
> Debugger: Make the register list DPI aware (Windows)

- cmake/BuildParameters.cmake
- pcsx2/GS/GSClut.cpp
- pcsx2/GS/GSDrawingContext.h
- pcsx2/GS/GSLocalMemory.cpp
- pcsx2/GS/GSLocalMemory.h
- pcsx2/GS/GSState.cpp
- pcsx2/GS/GSTables.cpp
- pcsx2/GS/GSTables.h
- pcsx2/GS/GSVector.h
- pcsx2/GS/GSVector4i.h
- pcsx2/GS/Renderers/DX11/GSTextureCache11.cpp
- pcsx2/GS/Renderers/HW/GSRendererHW.cpp
- pcsx2/GS/Renderers/HW/GSTextureCache.cpp
- pcsx2/GS/Renderers/HW/GSTextureCache.h
- pcsx2/GS/Renderers/OpenGL/GSTextureCacheOGL.cpp
- pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
- pcsx2/GS/Renderers/SW/GSDrawScanline.h
- pcsx2/GS/Renderers/SW/GSRendererSW.cpp
- pcsx2/GS/Renderers/SW/GSRendererSW.h
- pcsx2/GS/Renderers/SW/GSScanlineEnvironment.h
- pcsx2/GS/Renderers/SW/GSTextureCacheSW.cpp
- pcsx2/GS/Renderers/SW/GSTextureCacheSW.h
- pcsx2/pcsx2.vcxproj
- tests/ctest/GS/swizzle_test_nops.cpp
Should fix #2686, please test
The non-cached calculations are pretty fast, but generally not quite as fast as the cached versions.  I haven't noticed any slowdown in anything I've tested, but it might be good for others to test.
Also this makes heavy use of lambdas hoping they'll be inlined, so we should performance test MSVC and make sure it actually does
Finally, we haven't used them much before, so what are people's thoughts on formatting lambdas passed to functions? I went with this (indented like you would the content of a loop):
```cpp
s->m_pages.loopPages([this, s](uint32 page)
{
s->m_erase_it[page] = m_map[page].InsertFront(s);
});
```
but we could also go with this
```cpp
s->m_pages.loopPages([this, s](uint32 page)
{
s->m_erase_it[page] = m_map[page].InsertFront(s);
});
```
or …
> Replace cached GSOffset with live calculations

- pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
Fixes a bug where `f` would be incorrect for the blue channel when fogging was enabled on the rendering of a sprite on avx2 x64
Fixes #4996
Makes things less broken
Look at grass in the background of Hitman Blood Money title screen and see if it's blue
> GS:SW: Fix fog on x64 avx2

- pcsx2/SaveState.cpp
Reset the SkipFirst breakpoint stuff when a savestate is loaded, this was causing breakpoints to not activate when you load a savestate.
Fixes #4961 
Test breakpoint functionality, follow the steps in the bug report above. etc.
> Debugger: Reset breakpoint skip on savestate load

- pcsx2/gui/Debugger/BreakpointWindow.cpp
Using SetLabel on a wxTextCtrl doesn't set the value of the text control on linux.
The breakpoint window was not working properly on linux
Edit breakpoints, create breakpoints. Make sure the text boxes are not blank.
> Debugger: Fix breakpoint edit window on linux

- common/BitCast.h
- common/common.vcxproj
- common/common.vcxproj.filters
- pcsx2/CMakeLists.txt
- pcsx2/Utilities/BitCast.h
- pcsx2/gui/Debugger/CtrlDisassemblyView.cpp
- pcsx2/gui/Debugger/CtrlMemSearch.cpp
- pcsx2/gui/Debugger/CtrlMemSearch.h
- pcsx2/gui/Debugger/CtrlRegisterList.cpp
- pcsx2/gui/Debugger/DisassemblyDialog.cpp
- pcsx2/gui/Debugger/DisassemblyDialog.h
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
Implement memory search functionality
Closes #996
#4954 
#2906
I'm a sadist and work on the debugger...
Search around for stuff, make sure it doesn't crash, make sure things make sense, play around with the GUI.
---
Floating point numbers are compared between +0.001 -0.001 just to solve rounding errors.
Finding a float with double select as your type will point you to an address a little offset from the floating point address. This is due to the fact that a double is bigger than a float. It's 'correct'.
It uses virtual addressing. I was initially going to use physical addressing but the memory viewer uses virtual.
I'm expecting criticism on my implementation, specifically the comparison code. It was thrown together today in hmm let's see
8 hours
> Debugger: Initial memory search implementation

- pcsx2/GS/Window/GSwxDialog.cpp
- pcsx2/GS/Window/GSwxDialog.h
Undoes an accidental swap of config options when switching the GS config to WX
\+ some more ui changes that didn't make it into the first PR
It's nice when config options change the thing they say they change
Try using the config to change half pixel offset / half screen fix and make sure they change accordingly
> GS: Fix Half Pixel Offset and Half Screen Fix config swap

- pcsx2/DebugTools/DebugInterface.cpp
Show more of the kernel in the debugger memory view and disassembly views
Give @Nobbs66 their sanity back
What is the point of blocking this memory anyways?
Try to access previously 'invalid' addresses such as ` 0xBFC000000`
> Debugger: Allow access to all of 0xBXXXXXXX

- pcsx2/GS/GSState.cpp
- pcsx2/GS/GSState.h
- pcsx2/pcsx2.vcxproj.filters
Only update the MIP addresses automatically if the texture address changes.
Reloading every time TEX0 written when MTBA was enabled was causing false MIP level memory addresses to be set in Parappa the Rapper 2, this was due to a misunderstanding of how the MTBA bit worked.
Test games in software mode with mipmapping enabled, check the console for "MTBA reloading" messages and make sure no graphics are broken.
Fixes the roof/fog for Parappa The Rapper 2, the disco type room.
Fixes background texture flicker in Ape Escape 3
Parappa The Rapper 2:  (Look at the ceiling)
Before:
After:
Ape Escape 3: (The field behind the fence is the most obvious place, and the bushes to the right just behind that)
Before:
After:
> GS: Only reload Auto MIPs on TEX base change

- common/vsprops/CodeGen_Debug.props
- common/vsprops/CodeGen_Devel.props
- common/vsprops/CodeGen_Release.props
- common/vsprops/IncrementalLinking.props
Enables /MP for all build types, on all projects. Previously, Release builds of non-core projects were built serially.
Faster build times. But probably not too much difference for CI.
Make sure CI doesn't get upset.
> VSProps: Set MultiProcessorCompilation in CodeGen props

- pcsx2/GS/GS.cpp
- pcsx2/GS/Window/GSSetting.cpp
Change blending option from None to Minimum, update tooltip.
Accurate representation. None doesn't actually fully disable sw blending, so the option is a bit inaccurate, rename it to Minimum instead.
> GS-gui: Change blending option from None to Minimum.

- pcsx2/gui/Debugger/DisassemblyDialog.cpp
Was supposed to do this in my initial memory search pr but ended up removing while fighting with git accidentally.
Makes the background of the memory area transparent
Checkboxes / Labels are not the system colour in the memory search.
See if the check boxes are the system background colour for you.
> Debugger: Make memory dialog transparent

- pcsx2/gui/Panels/DirPickerPanel.cpp
- pcsx2/gui/wxGuiTools.cpp
- pcsx2/gui/wxGuiTools.h
Makes `pxExplore` work correctly on macOS
It didn't work
Make sure you can still use the "Open in Explorer" buttons in the settings window
I would think `wxLaunchDefaultApplication` will work at least as well as the old solution on all platforms but who knows
> wx: Fix `pxExplore` on macOS

- 3rdparty/libsamplerate/config.h
Correct the license header on the config.h file in libsamplerate
Got missed in an update as they switched to auto generation of the config.h file, but the license was switched prior to us last updating the library. See this commit: https://github.com/libsndfile/libsamplerate/commit/819c6a8d680d7385ce54f5e0d4ff62266d349d05#diff-dcf9d0451a6397210424fc9699e209255660a4d3b3072c2f1b35048df8df4092
Look at the file, make sure the license says BSD.
> 3rd Party: Update rogue file to correct BSD license

- pcsx2/Gif.cpp
Modifies the timing of FIFO reading so it always has a delay when reading before it does anything else.
Timing was slightly broken in some situations, this resolves it.
Test games, look out for flashing textures which weren't there before. if you know games which use PATH3 masking, it will be advantageous.
Fixes some glitching in Need for Speed Underground 2
> GIF: Modify fifo read behaviour

- pcsx2/CDVD/CDVD.cpp
- pcsx2/Elfheader.cpp
- pcsx2/Elfheader.h
- pcsx2/R5900.cpp
- pcsx2/SaveState.cpp
- pcsx2/SaveState.h
- pcsx2/System.cpp
- pcsx2/gui/AppConfig.cpp
- pcsx2/gui/AppConfig.h
- pcsx2/gui/AppCoreThread.cpp
- pcsx2/gui/Saveslots.cpp
- pcsx2/gui/Saveslots.h
- pcsx2/gui/SysState.cpp
- pcsx2/gui/UpdateUI.cpp
- pcsx2/ps2/BiosTools.cpp
- pcsx2/ps2/BiosTools.h
- Organized user-created savestates by saving into subfolders with game name and serial.
- Detect PSX CRC properly, format console titlebar.
- Fix bug with g_GameStarted and g_GameLoading not being reset on recompiler shutdown.
- Fix bug with g_GameStarted and g_GameLoading not being set to proper status when loading savestate.
Cleaner directory for savestates, improve ease of saveestate management. Improve management of game state variables in regards to functionality.
Save/load savestates, look for errors in directory/savestate creation or directory naming. Check for errors/crashes switching games.
Closes #4625, #4744
> Savestates: Small refactoring

- pcsx2/gui/Panels/GSWindowPanel.cpp
Fixes regression from https://github.com/PCSX2/pcsx2/pull/4140
I like clean and helpful GUI.
Test some games, maybe touch upon hotkey remapping or just ignore it as the others strings seem fine.
> GUI: Bring back F6 string (Aspect Ratio)

- pcsx2/gui/Debugger/CtrlMemSearch.cpp
Print size_t with %zu instead of %d
There was a ghost assert complaining about the format not matching the type (Can't reproduce anymore)
Make sure the hit counter still works.
> Debugger: Format search hits with proper specifier

- pcsx2/GS/Renderers/OpenGL/GLLoader.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
Apparently using glCopyTextureSubImage2D was causing memory leaks in Evolution Snowboarding on NVIDIA and Intel drivers. For some reason it's fine for me on AMD...
Fixes #5017 
Leaks bad
Make sure games which need colclip clamping off aren't affected (e.g. FFX-2 opening FMV).
> GS/OpenGL: Use shader+draw for CopyRectConv

- 3rdparty/xbyak/xbyak/COPYRIGHT
- 3rdparty/xbyak/xbyak/xbyak.h
- 3rdparty/xbyak/xbyak/xbyak_mnemonic.h
- 3rdparty/xbyak/xbyak/xbyak_util.h
Upgrades xbyak from 5.11 to 6.00
Keep code up to date
Check for bugs, compile.
> 3rdparty: Upgrade xbyak to 6.00

- 3rdparty/soundtouch/COPYING.TXT
- 3rdparty/soundtouch/README.html
- 3rdparty/soundtouch/soundtouch/FIFOSampleBuffer.h
- 3rdparty/soundtouch/soundtouch/STTypes.h
- 3rdparty/soundtouch/soundtouch/SoundTouch.h
- 3rdparty/soundtouch/source/SoundTouch/BPMDetect.cpp
- 3rdparty/soundtouch/source/SoundTouch/FIFOSampleBuffer.cpp
- 3rdparty/soundtouch/source/SoundTouch/FIRFilter.cpp
- 3rdparty/soundtouch/source/SoundTouch/FIRFilter.h
- 3rdparty/soundtouch/source/SoundTouch/InterpolateCubic.h
- 3rdparty/soundtouch/source/SoundTouch/InterpolateLinear.cpp
- 3rdparty/soundtouch/source/SoundTouch/InterpolateLinear.h
- 3rdparty/soundtouch/source/SoundTouch/InterpolateShannon.h
- 3rdparty/soundtouch/source/SoundTouch/PeakFinder.cpp
- 3rdparty/soundtouch/source/SoundTouch/RateTransposer.cpp
- 3rdparty/soundtouch/source/SoundTouch/RateTransposer.h
- 3rdparty/soundtouch/source/SoundTouch/TDStretch.cpp
- 3rdparty/soundtouch/source/SoundTouch/sse_optimized.cpp
Upgrades soundtouch lib to 2.3.1
Keep code up to date
Test compile on CMake/Windows. Ensure audio functionality is not broken.
> 3rdparty: Upgrade soundtouch lib to 2.3.1

- pcsx2/GS/GSDrawingContext.cpp
Improves the accuracy of TEX0 when calculating texture sizes
Previously it expected the values to be too small and would overcompensate, but since we are now using Accurate STQ it gives good numbers and it broke this behaviour in Final Fantasy X (Possibly others)
Test games using upscaling, preferably 3x or 4x, make sure everything looks okay.
> GS: Improve FixedTEX0 accuracy

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CdRom.cpp
Adjusts the CDVD DMA (3) timing to that based on PS1 tested numbers.
Bus width is 16bit on the PS2 between the DVD drive and the DSP, it is 8bit on PS1, so serves to reason the DMA would be twice the speed. (PS1 is 24 cycle per word)
test games, make sure they still work and don't die horribly.
Fixes Spongebob Lights, Camera, Pants!
> CDVD: Adjust DMA timing based on PS1 timings.

- pcsx2/GS/res/glsl/tfx_fs.glsl
- pcsx2/GS/res/tfx.fx
ogl:
Get rid of Color_pabe vector, makes more sense to use As and Cs in pabe code.
d3d11:
Use As and Cs in pabe code, makes more sense.
Get rid of Cv vector, use Color parameter for operations instead like on gl.
Minor optimization.
Make sure hw renderer blending still works on both renderers.
> Gs-hw: Adjust/minor optimization on sw blend shader a bit

- pcsx2/GS/GSState.cpp
- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
There is no hw implementation of AA1.
Alpha blending shouldn't be enabled by AA1 flag, only ABE and PABE flags.
This caused alpha blending to be enabled when it shouldn't have.
Also disable Blending when AA1 and ABE or PABE are on on lines.
Lines aren't drawn so no need to do blending on them.
Mask out AA1 on triangles in GSState
AA1 is not supported on hw renderers so ignore flushing the prims on triangles.
Should provide a nice speed boost on games that use AA1 on triangle prims.
When AA1 flag is enabled Z is not written on lines since coverage is always less than 0x80.
Accuracy, improves how we handle aa1 draws, while there's no actual aa1 hw implementation yet we can make sure the draws are handled properly.
Improves #4674
Master
PR
Test games which use AA1.
> GS-hw: Improve how we handle AA1 draws

- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
Partially reverts the AA blending change in #5061
The BIOS light trails broke with this change and weren't needed, the Z Writes were the important part of the PR.
Make sure the AA'd games still look as good as they do on master
> GS: Partial revert of #5061

- .gitmodules
Shallow clones tend to be 5-10s slower
GHActions Windows submodule checkout run time (seconds):
Linux:
macOS (never used GH cache on submodules):
Why waste 10 seconds when you don't have to?
Watch the CI run
> GHActions: Don't shallow clone submodules

- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
Probably won't change much, except maybe with sparse textures, where it'll use less video memory.
It was wrong before.
Make sure colclip games are still fine (e.g. sly 2, ffx-2 opening)
> GS/OpenGL: Use CreateRenderTarget() for temp HDR target

- pcsx2/GS/Window/GSwxDialog.cpp
- pcsx2/GS/Window/GSwxDialog.h
Fix interaction of Anisotropic filtering with Nearest Texture Filtering and GPU Palette Conversion.
Fix interaction of Trilinear Filtering with selected renderer.
Options should gray out properly now.
Fixes #5071
Test the GS options if they gray out properly now as described in the linked issue.
> GS-wx: Fix some gui interaction.

- cmake/BuildParameters.cmake
Defaults the `CMAKE_BUILD_PO` option to off for all build modes
Git files getting modified by build is just as much of a pain in release builds as it is in devel builds
Build in release and see if it modifies files tracked by git
> CMake: Always default `CMAKE_BUILD_PO` off

- pcsx2/CMakeLists.txt
- pcsx2/GS/GS.cpp
- pcsx2/GS/GSAlignedClass.h
- pcsx2/GS/GSRingHeap.cpp
- pcsx2/GS/GSRingHeap.h
- pcsx2/GS/Renderers/SW/GSRasterizer.cpp
- pcsx2/GS/Renderers/SW/GSRasterizer.h
- pcsx2/GS/Renderers/SW/GSRendererSW.cpp
- pcsx2/GS/Renderers/SW/GSRendererSW.h
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
Some allocators really didn't like the SW renderer's allocation pattern
Replaces the system allocator with an overly specialized one that works very well at its one purpose
Hitman Blood Money title screen on i7-4980HQ with 2 SW renderer threads:
Windows:
29% → 31% (MTGS thread time in _aligned_malloc: 10% → 3.5%)
MacOS:
22% → 30% (MTGS thread time in _aligned_malloc: 30% → 3.5%)
Linux (default glibc allocator with Fedora 34):
22% → 30% (My perf flame graph was very broken, so no stats here)
There's one more malloc call from `GSOffset::GetPages`, which will get cleared up with #4348
(Note: I'm expecting the most performance increase on things that also benefitted from the spin wait PR)
Faster software renderer, yay
Make sure everything works
Watch the console for `GSRingHeap: Refusing to …
> GS: Use custom allocator for SW renderer

- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/DX11/GSRendererDX11.h
Accumulation blend -> afix is already handled in shader, no need to set it for hw blending too.
SW blending -> done in shader.
HW blending - > set only when it is actually used, Alpha C.
Proper handling, optimization.
Test games on hw (minimum blending) and sw (basic+ blending) on Direct3D11 to make sure everything still works.
> GS-d3d11: Properly set afix in EmulateBlending.

- common/CMakeLists.txt
Makes GCC link it correctly in LTO mode
Vroom vroom
Build with LTO if you want
> Fix compilation with LTO on GCC

- pcsx2/gui/AppInit.cpp
Before only absolute paths worked.
> Allow relative elf file paths on command line

- .github/workflows/macos-workflow.yml
Adds glib to the list of packages installed on macOS
GitHub Actions must have changed the set of preinstalled packages as glib is now missing
Make sure the CI works
> GHActions: Fix Mac build

- .github/ISSUE_TEMPLATE/app_bug_report.yaml
- .github/ISSUE_TEMPLATE/emu_bug_report.yaml
- Added Windows 11 to the issue templates
- Changed version example to match what we have going on now
- Made a new template for when the bug is unrelated to emulating a game.
I noticed a few things when making an issue, also that if you aren't making a bug report pertaining to a game, a lot of the fields are irrelevant, so a stripped down template would be ideal.
See my fork - https://github.com/xTVaser/pcsx2-rr/issues/new/choose
> GitHub: Update and add new issue template for non-game related bug reports

- pcsx2/SPU2/Mixer.cpp
- pcsx2/SPU2/spu2sys.cpp
Stolen sets voice pitch to 0 to pause the voice, toggles key on, and only then DMA's the sample data to it. This means that grabbing the next sample must be delayed until the voice is unpaused by setting pitch to a non-zero value.
When i changed the comparisons for SP in order to fix the interpolation the behavior changed and it started grabbing the new block instantly on key on.
This restores the old behavior by initializing SP to -1 on key on.
> SPU: Fix videos in Stolen

- pcsx2/GS/res/glsl/tfx_fs.glsl
- pcsx2/GS/res/tfx.fx
Split color clamp/wrap in it's own function. 
Use the function for both sw blending and dithering, less code duplication.
Less code duplication.
Make sure dithering, blending(mostly shadows) still work on hw renderers.
> GS-glsl/fx: Split color clamp/wrap in it's own function.

- .github/workflows/scripts/releases/announce-release/index.js
If the release is a stable release -- don't announce it to the discord.
I want to flesh out some of the old tags in the repo into releases with artifacts, but I don't want them being announced and labelled as nightlies.
A little bit inconvenient to test this unfortunately.  Sometime soon I should pull these out into individual actions that have unit-tests.  I'd say:
- Look at the code, i just did some basic cleanup with a new variable
- Ensure `prerelease` is a valid key in the release payload - https://docs.github.com/en/rest/reference/repos#get-a-release
> actions: Only announce `pre-release` releases

- .github/workflows/linux-workflow.yml
Linux builds are failing, 30minutes is not enough with a cache-miss. For example - https://github.com/PCSX2/pcsx2/runs/4128702348?check_suite_focus=true
We can't rely on the cache properly until the following issue is resolved - https://github.com/actions/cache/issues/342#issuecomment-673371329
Once we can, we should be able to dynamically set the timeout accordingly based on the cache-hit/miss
Do builds still pass
> actions: increase max linux build times as well until cache-hit rate is reliable

- pcsx2/DEV9/pcap_io.cpp
Don't shadow dwStatus in PCAPGetWin32Adapter
Shadowing dwStatus for the return value of GetAdaptersAddresses will prevent the return value of second call from being inspected in the following if statement
If the user had a large amount of network adapters, this would prevent the code from getting the adapter information of a the selected pcap adaptor.
The equivalent TAP adapter code is already correct.
Test pcap adaptor on a system with lots of adapters installed
> DEV9: Don't shadow return value of GetAdaptersAddresses (Pcap)

- pcsx2/DEV9/pcap_io.cpp
Uses non-blocking mode for pcap
When trying to close PCSX2, The Rx networking thread would hang trying to receive a packet
Use non-blocking mode to avoid the hang
Test network enabled games using pcap
Test intercept DHCP or the internal DNS, as non-blocking mode uses a different path (seemed fine in my testing)
Test performance between master and this PR when networking is enabled
> DEV9: Enable pcap non-blocking

- pcsx2/GS/Window/GSwxDialog.cpp
- pcsx2/GS/Window/GSwxDialog.h
End of Dump is actually Length of Dump, don't set minimum value of start of dump, it's annoying, don't want to dump 1k draw.
Set min value of 1 as 0 will create endless dumps.
Makes the GS debugger suck less.
> GS Debugger: Fix Length of dump.

- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
- pcsx2/GS/res/glsl/tfx_fs.glsl
- pcsx2/GS/res/tfx.fx
Sample depth on green channel.
Update channel buffer only when GXBY channel is used, and cleanup some variables.
Fixes #4540
Test #4540, maybe Stolen and other games that hit the same code path.
> GS-hw: Sample depth on green channel

- pcsx2/GS/GSAlignedClass.h
- pcsx2/GS/GSRingHeap.h
Fixes a memory leak we could have gotten if we used GSRingHeap::SharedPtr with exception-throwing constructors
(I don't think any of our constructors actually throw exceptions, but hey better safe than sorry)
Also clears an MSVC compiler warning
Less compiler warnings
Look at CI, see if compiler warnings are gone
Run the SW renderer and make sure nothing breaks horribly
> GS: Fix compiler warning

- bin/GameIndex.yaml
adds patches to the 'K-1 World' series games and adds ee clamping  full to  'D1 Professional Drift Grand Prix Series'
Fixes said games 
look at CI/ try said games
> GameDB: add patches to the 'K-1 World' series games add EE clamping full to 'D1 Professional Drift Grand Prix Series'

- pcsx2/GS/Renderers/Common/GSDevice.cpp
- pcsx2/GS/Renderers/Common/GSDevice.h
- pcsx2/GS/Renderers/DX11/GSDevice11.h
- pcsx2/GS/Renderers/DX11/GSRendererDX11.cpp
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
- pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp
```
Do Cs*F or Cs*As in shader.
Do Cs*(As + 1) or Cs*(F + 1) in shader.
Do Cs*(1 - As) or Cs*(1 - F) in shader.
```
Try to make Direct3D11 suck less, try to use a mix of hw/sw blending if we can, will help improve many games.
For OpenGL it is an optimization as gl now will require less barriers.
Test many games on hw renderers.
> GS-hw: Try to use a mix of hw/sw blending in more situations.

- pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
- pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
- pcsx2/GS/Renderers/SW/GSNewCodeGenerator.h
- pcsx2/GS/Renderers/SW/GSRendererSW.cpp
- pcsx2/GS/Renderers/SW/GSScanlineEnvironment.h
- pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp
Improve handling of large values for Z on the SW renderer by using integer Z for flat triangles.
Large floats are not handled very well in the software renderer due to the range being limited by signed integers but also some precision is lost by being single floats which only have a precision of 24bits.  This PR makes it so flat triangles are treated like sprites and the Z values are passed as integer so no precision is lost, which fixes games which use flat triangles to draw UI/2D screens.
Test games in software mode, including 007: Agent Under Fire, make sure no graphics are missing or more broken than previous.
Fixes #3662
Fixes #4164
Also probably fixes issue with Raw Danger requiring integers on flat prims as mentioned in #1562 Fixes #2980
Also hugely improves the 2D UI in Hana to …
> GS SW: Handle flat prims without float conversion

- cmake/BuildParameters.cmake
Changed -fno-operator-names to only be passed to C++ files.
3rd party libraries we compile no longer spew out a bunch of warnings that C files don't use that flag.
Compile pcsx2.
> Only pass C++ flags to C++ files.

- pcsx2/x86/iFPUd.cpp
This was generating a 0-distance jmp at the end of the adjustment for add/sub insturctions.
Useless code.
Make sure full FPU games are unaffected (e.g. Bully, NFS Carbon). But it was literally an `EB 00` encoding so it shouldn't have any negative effects.
> EERec: Remove zero-distance jmp in full fpu mode

- pcsx2/GS/GS.cpp
- pcsx2/GS/Renderers/Common/GSDevice.cpp
- pcsx2/GS/Renderers/Common/GSDevice.h
- pcsx2/GS/Renderers/Common/GSRenderer.cpp
- pcsx2/GS/Renderers/Common/GSRenderer.h
- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.h
- pcsx2/GS/Renderers/DX11/GSTexture11.cpp
- pcsx2/GS/Renderers/HW/GSRendererHW.cpp
- pcsx2/GS/Renderers/HW/GSRendererHW.h
- pcsx2/GS/Renderers/HW/GSTextureCache.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
- pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp
- pcsx2/GS/Renderers/SW/GSTextureSW.cpp
Added an OI hack to perform some point list (CLUT) and sprite (~~CLUT,~~ sky tex) draws via CPU directly in GS local memory, tested only on Burnout 3.
Solves the black sky issue also when TC is cleared.
Update: added on OO hack to download the cloud texture from GPU after rendering during level loading, which solves the missing clouds issue. Tested only in Burnout 3 PAL (50Hz and 60Hz), might need adjustments for different games ~~/regions~~ .
~~Update 2: added a CU hack to avoid upscaling of the clouds drawn during level loading.~~
Update 3: Fixed a bug in TC which assigned a wrong scale factor to native resolution draws.
Update 4: Fixed a bug in the HW renderer which provided too small RT to fit the current draw (upscaled clouds).
Update 5: Reworked and refactored the GS device surface …
> GS-hw: fix Burnout games black sky.

- .github/workflows/macos-workflow.yml
- cmake/SearchForStuff.cmake
- pcsx2/CMakeLists.txt
Remove gio dependency on macOS
gio is no longer needed on macOS
Make sure the CI builds
> CMake: Remove gio dependency on macOS

- pcsx2/CMakeLists.txt
- pcsx2/Config.h
- pcsx2/PINE.cpp
- pcsx2/PINE.h
- pcsx2/Pcsx2Config.cpp
- pcsx2/System/SysCoreThread.cpp
- pcsx2/System/SysThreads.h
- pcsx2/gui/App.h
- pcsx2/gui/AppCoreThread.cpp
- pcsx2/gui/Dialogs/ModalPopups.h
- pcsx2/gui/Dialogs/PINEDialog.cpp
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
This is a long coming change related to our ipc implementation: as the protocol is slowly getting adopted by other projects/other contributors stepped in the name had to stop being related to pcsx2 specifically. 
PINE (Protocol for the Instrumentation of Emulators) was chosen, this patch reflects that.
> ipc: rename to pine

- pcsx2/CDVD/CDVD.cpp
Adjusts some of the reading logic to correct the timing of some events
Also don't set "READ" state when buffering, doing this breaks Pro Yakyuu Spirits 5 which does CD Standby and expects it to not be reading.
In some scenarios it would spend too long reading/seeking when it shouldn't do since we'd already accounted for it.
Check games, especially CDVD sensitive ones, make sure they're still okay, not actually expecting much change.
SH2 is still janky, seems okayish for me with MTVU off... but I don't know what the proper fix is for that, just to jump in there first.
> CDVD: Fix some read timing logic

- pcsx2/pcsx2.vcxproj
- pcsx2/pcsx2.vcxproj.filters
Fixes the shaders in VS project so they can be open
Nobody updated it when the shaders were moved, this resolves that.
Open VS and make sure you can open all the shader files from the solution tree
> VS: Fix location of shaders in project

- pcsx2/GS/GSClut.cpp
- pcsx2/GS/GSState.cpp
- pcsx2/GS/Renderers/HW/GSRendererHW.cpp
- pcsx2/GS/Renderers/SW/GSRendererSW.cpp
Check CLUT dirty write on vertex kick instead of during the actual draws.
Previously the CLUT dirty check was done during the draw, however this is way too late and we're not *actually* invalidating memory at this point, just marking the CLUT as dirty, it will then flush the draws THEN invalidate the CLUT, meaning it is in the correct state for the upcoming draws.  Virtual On was modifying the CLUT in quick succession causing it to end up with an invalid version of the CLUT.
Test games with colour issues in the software renderer (Hardware maybe too, but that has other problems, especially with the Sega games).  General games worth testing too, just to make sure I didn't bust anything.
Fixes #4826
> GS: Check CLUT dirty write on vertex kick

- pcsx2/ps2/BiosTools.cpp
Restore "BIOS Found:" message in console log window
It got removed, probably by accident, but it's good for support
boot a game or go in to your settings, make sure the BIOS prints the found BIOS file.
> Log: Restore BIOS Found message

- pcsx2/CDVD/InputIsoFile.cpp
If you loaded an invalid file, particularly with compression, the file open may fail, leading to a division by zero (on block size), or trying to read from nothing.
> CDVD: Check file actually opened before proceeding

- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp
This wasn't an issue in wx, since the whole context/device gets torn down and recreated when you pause/unpause, or change settings.
But on Qt it is, since the context/device is preserved for a faster/lighter settings apply.
> GS/OpenGL: Fix incorrect VAO cleanup

- bin/resources/shaders/dx11/tfx.fx
- bin/resources/shaders/opengl/common_header.glsl
- bin/resources/shaders/opengl/convert.glsl
- bin/resources/shaders/opengl/tfx_fs.glsl
- pcsx2/GS/Renderers/Common/GSDevice.cpp
- pcsx2/GS/Renderers/Common/GSDevice.h
- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.h
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
- pcsx2/GS/Renderers/HW/GSRendererNew.h
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
Trying to claw back some of the performance loss (~5% in extreme cases) from #5138. Copying all those structs around up to 20,000 times a second isn't free. Brief testing suggests a 10% performance uplift in draw call bound scenarios when running GSDumps.
Better performance, less code.
Test a range of games to make sure no regressions were introduced. GS dumps would be fine too.
> GS: Unify constant buffers between renderers

- common/FileSystem.cpp
Fixes an issue where `GetWorkingDirectory` would return a `std::string` containing null characters at the end
Fixes #5163
When you concatenated those strings with other strings, the null characters would make most C utilities not notice the concatenation
Attempt to make a block dump in Linux
> Common: Fix GetWorkingDirectory on unix

- pcsx2/GS/GSLocalMemory.cpp
- pcsx2/GS/GSLocalMemory.h
Fixes an issue where GS crashed with games that used textures that wrapped around GS memory multiple times
Fixes #5143 
Less crashy more runny
[Test this GSdump](https://github.com/PCSX2/pcsx2/files/7738567/gs_20211217165447.zip) (and yes it's compressed twice because GitHub doesn't let you upload xz files)
Test the actual game in #5143
Test other games listed in #5179 (who knows, maybe they had this issue too)
> GS: Fix looping over pages of textures with massive strides

- pcsx2/GS/GSState.cpp
- pcsx2/GS/GSState.h
- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
GS: Redo GetAlphaMinMax.
Cleaner this way, also fix recent regression on Full Blend with alpha max.
GS-hw: Move the blend mix alpha check after sw blending selection.
Optimization.
Fix recent regression and optimization.
Test blending and make sure still works on both renderers.
> GS-hw: Fix recent alpha max check.

- .github/workflows/scripts/linux/appimage.sh
- .github/workflows/windows-workflow.yml
- .gitignore
- linux_various/PCSX2-linux.sh
- linux_various/PCSX2.desktop.in
- pcsx2/CMakeLists.txt
bin/PCSX2 is now bin/pcsx2 -- update your scripts!
Everything in Linux land is lowercase
Build PCSX2 and see if it is lowercase
-- I believe I got everything covered for this change? PCSX2-Linux.sh still works
> Linux and Windows CMake Builds: Change output executable to lowercase

- bin/resources/GameIndex.yaml
- pcsx2/IPU/IPU.cpp
- pcsx2/IPU/IPU.h
- pcsx2/IPU/IPU_Fifo.cpp
- pcsx2/IPU/IPUdma.cpp
- pcsx2/IPU/IPUdma.h
- pcsx2/IPU/mpeg2lib/Mpeg.cpp
- pcsx2/SaveState.h
Change IPU DMA to only refill on request, also tidied up and bugfixed.  Also changed the internal FIFO to only contain the amount of data required to complete the currently in process command. 
Savestate bump required
Some games expect the DMA to be in an exact state in order for it to clear itself and continue, else they hang. Top Trumps being one of the said games, but also Test Drive (Had to change how this functions). Additionally previously the internal fifo was always kept at 2 quadwords, even when it didn't need it, this caused some strange/bad behaviour when pausing/resuming the IPU, so it now only keeps enough data to process the command.
Also the DMA design was kind of terrible, so I rewrote it and it fixed some bugs, so that's cool!
Test videos, make sure ones that are known to …
> IPU: Overhaul DMA transfers

- bin/resources/shaders/dx11/tfx.fx
- bin/resources/shaders/opengl/tfx_fs.glsl
- pcsx2/GS/GSState.cpp
- pcsx2/GS/GSState.h
- pcsx2/GS/Renderers/Common/GSDevice.h
- pcsx2/GS/Renderers/Common/GSRenderer.cpp
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/SW/GSRasterizer.cpp
- pcsx2/GS/Renderers/SW/GSRasterizer.h
- pcsx2/GS/Renderers/SW/GSRendererSW.cpp
This adds simulation of a PS2 scanline masked drawing on hardware renderer. Masked drawing allowed to skip rendering of primitives on even/odd lines (depending on the mask). As different games may have used this mask for different techniques several options were implemented:
**1. Off (current behaviour)**
Ignores the scanmask. For cases when the end result is just fine without it.
**2. Unscaled (set as a default setting as this is what PS2 does)**
Do the masking with PS2 resolution in mind. The prohibited lines are skipped by failing depth test in fragment shader/pixel shader.
**3. Scaled**
Same as above except actual internal resolution is used.
**4. Transparent**
Suitable if masking was used to create an illusion of transparency.
No lines are skipped when drawing. Geometry is rendered …
> GS: Simulate scan mask (fix transparency in MGS2 & MGS3)

- bin/resources/GameIndex.yaml
add VU clamping to "Ultimate Spider-Man" , adds fixes for Ridge Racer V , EyeToy - Bob the Builder , Klonoa 2 , Fight Night and remove parts of patches  adds a patch for Super Shanghai 2005
Fixes: #5186 
Fixes: #5122
>  GameDB: add VU clamping to "Ultimate Spider-Man" and fixes to other games

- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
Move SW blending check of AFIX > 128 to High blend mode
Fixes #5193
Vertex trace check can have false positives but afix check cannot, so it makes sense to separate them
Check games on OpenGL with SW blending set to High.  Compare graphics to Full and performance to previous High.
> GS: Move afix check to high blend level

- build.sh
build.sh now defaults to a native build (64 bit unless run on a 32 bit system). The switch "--clean-plugins" was removed, as we no longer have plugins.
32 bits is going to be going away, and this makes it default to the version that should be used going forward.
Make sure it builds as 32 bit and 64 bit. Make sure it doesn't break distributions building pcsx2.
> Make native builds default on Linux when using build.sh. Remove unused switch.

- pcsx2/gui/App.h
- pcsx2/gui/MainFrame.cpp
- pcsx2/gui/MainFrame.h
- pcsx2/gui/MainMenuClicks.cpp
- pcsx2/gui/RecentIsoList.cpp
- pcsx2/gui/RecentIsoList.h
Adds an option to the recent ISO list to remove all entries that can no longer be found in their original location.
Solution for #4963. I decided on using the term "prune" instead of "clean" because it sounds too similar to the existing "clear". Would welcome input on what the terminology for this function should be.
1. Load an ISO file into PCSX2
2. In a separate file browser window, move that file to a different location on disk
3. Click the "Prune ISO list" option and the file will be removed from the list
> Add "Clear missing files" option to recent ISO list

- pcsx2/gui/Dialogs/GSDumpDialog.cpp
Length() internally calls fseek() to end, ftell(), and fseek() back again (really slow).
Shaves several seconds off loading large gs dumps.
> GSDumpDialog: Cache length instead of querying every packet

- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
Add an early condition to check if alpha is lower than 128, if so then no blending so early exit.
Optimization, accuracy on hw blending.
Test the following games: SOTC, Breath of Fire Dragon Quarter, Strawberry Shortcake, Super Robot Wars, Cartoon Network Racing.
> GS-hw: Optimize pabe (per pixel alpha blending)

- common/FileSystem.cpp
Following changes should fix FreeBSD build after [a083343](https://github.com/PCSX2/pcsx2/commit/a083343c6e918b890395ab463de1e0c1b030ddf2) and [9533fa2](https://github.com/PCSX2/pcsx2/commit/9533fa25c3f0c93a71d20c2fe5289ce94997bae2):
Imported version of Rapid YAML doesn't build on Unices without `CLOCK_MONOTONIC_RAW`, which [should be Linux specific](https://linux.die.net/man/2/clock_gettime).
[450a27f](https://github.com/biojppm/c4core/commit/450a27f8b18ee23b18a3b102be90d542bc887b68) addresses this issue, so it is the current target.
Fixes FreeBSD `ifdef` so it doesn't use `countof`. Instead, follow c++17 and use `std::count`, which is available in base clang compiler for all supported releases, and fits perfectly according to [`sysctl(3)`](https://www.freebsd.org/cgi/man.cgi?query=sysctl …
> FreeBSD: fix compilation

- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.h
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
- pcsx2/GS/Window/GSwxDialog.cpp
- pcsx2/GS/Window/GSwxDialog.h
GS-d3d11: Mirror anisotropic filtering behavior on Direct3D11. 
Don't run aniso filter on m_convert.pt and m_convert.ln samplers.
Running m_convert.pt broke shadows on color clipping.
Also use the aniso bit from hw renderer.
Aniso will now behave the same as on OpenGL.
GS-wx: Aniso can run with nearest texture filtering so let's leave it. 
Option just disabled the toggle, it would still run on opengl.
Fixes issues with color clipping when using aniso, accuracy.
Test and make sure anisotropic filtering still works on Direct3D11, also make sure you can still toggle Ansiso filter even on nearest texture filtering.
> GS-hw: Mirror anisotropic filtering behavior on Direct3D11 like OpenGL, and allow it to run on Nearest texture filtering

- pcsx2/GS/GS.cpp
- pcsx2/GS/GS.h
- pcsx2/GS/GSUtil.cpp
- pcsx2/GS/GSUtil.h
- pcsx2/GS/Renderers/DX11/D3D.cpp
- pcsx2/GS/Window/GSwxDialog.cpp
- pcsx2/GS/Window/GSwxDialog.h
- Moves adapter list and default renderer selection to GSUtil.cpp, and out of GSwxDialog.cpp+GS.cpp
- Adds a separate option to be the default-selected adapter, rather than defaulting to adapter 0
- Enables the adapter selector list on all platforms.  I can disable this on platforms with no adapter-supporting graphics APIs if we'd prefer that.
- This will be important for non-DX11, non-OGL APIs.
- On dual-gpu Macs, adapter 0 is the integrated GPU while adapter 1 is the discrete GPU, so it's probably better to let the API tell us what should be the default instead of picking 0 for ourselves
- Look at the graphics settings dialog and make sure everything still works
- Make sure F9 renderer switching still works
> GS: Add dedicated functions for choosing renderers and adapters

- .gitignore
Add to gitignore the new GS debug OpenGL filename and remove the old ones.
The GS debug OpenGL filename has been changed but the gitignore not, this fixes that.
Just compile and run in debug mode with the OpenGL renderer, check that the `GS_opengl_debug.txt` is ignored by git.
> gitignore: update gs debug gl filename.

- pcsx2/GS/GSLocalMemory.h
Fix the last iteration detection logic in `GSOffset::PageLooper::loopPagesWithBreak`.
Thanks to @tellowkrinkle for pointing out where the issue was (I just did the testing here, speaking of which, unit testing for these functions may be suggested in the future).
The GS page looping was seldom buggy.
This fix will correct it.
SW and HW GS texture caches will benefit from the fix. 
Test some games and check that nothing regressed.
I'm not aware of any regression induced by this bug.
> GS: fix loopPagesWithBreak last iteration logic.

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD.h
- pcsx2/CDVD/CDVD_internal.h
- pcsx2/CDVD/CDVDaccess.h
- pcsx2/SaveState.h
Implements the functionality of 0x2013 which is the speed register based on how the dsp handles it.  Also handle the SpindleCtrl value set by reads properly, though these codepaths are very rare and unlikely.
Also Set the drive as not spinning when ejected.
The Speed (0x2013) was wrong/hardcoded/unknown, this implements it, other stuff is mostly error handling. Drive also wasn't set as not spinning when the drive was ejectected
Uhh run games, i guess, probably wont' affect anything.
> CDVD: Implement speed register, fix up SpindleCtrl

- pcsx2/System/SysThreadBase.cpp
Typical pcsx2 threading nonsense.
Changing discs sets g_CDVDReset, which ends up double-opening PAD. So,
1) it never gets closed properly, and
2) when you change renderers, it should get reinitalized due to the window change (because it's nasty and hijacks the window thread), but because it has a gross "openCount" which never reaches zero, that never happens
3) hotkeys don't work
:rage:
Fixes #5267
Cry in a corner
> SysThreadBase: Fix double init of SPU2 etc

- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
OpenGL:
Check for fbmask and do accurate path DATE_GL45.
Check for FBA, all pixels will be 128 or more so use Fast path DATE_one.
Direct3D:
Check for fbmask, accurate path isn't supported so just to DATE.
Check for FBA, all pixels will be 128 or more so use Fast path DATE_one.
Optimization
Test shadows, transparency.
> GS-hw: Improve DATE selection

- cmake/BuildParameters.cmake
Linking with the address sanitizer fails otherwise 
🤧
> CMake: Pass -fsanitize=address as a link option when USE_ASAN is used

- pcsx2/CDVD/CDVD.cpp
- pcsx2/CDVD/CDVD_internal.h
Add timing to error calls and modify error for reading past end of the disc
Games do terrible, terrible things. I don't know if this is right, but it seems to mimic PS2 behaviour on the Silent Hill 2 Black Ribbon demo disc.
test stuff that tries to read past the end of the disc
Fixes #5280
> CDVD: Adjust error timing and modify error used for high sector.

- bin/resources/shaders/dx11/tfx.fx
- pcsx2/GS/GSExtra.h
- pcsx2/GS/GSState.cpp
- pcsx2/GS/Renderers/Common/GSDevice.cpp
- pcsx2/GS/Renderers/Common/GSDevice.h
- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.h
- pcsx2/GS/Renderers/DX11/GSTexture11.cpp
- pcsx2/GS/Renderers/DX11/GSTexture11.h
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
- pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp
- pcsx2/GS/Renderers/OpenGL/GSTextureOGL.h
- pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
- pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
- pcsx2/GS/Window/GSwxDialog.cpp
More fixes to the mess that mipmapping is in the hardware renderers.
- Out of bounds uploads were occurring, probably the cause of device loss in #5286.
- DX11 wasn't clamping the LOD, leading to undefined texels being loaded when mipmapping was enabled (e.g. SOTC).
- Enables trilinear filtering in DX11.
Test Jak II, SOTC, other games which currently have issues.
> GS: More mipmapping fixes

- bin/resources/shaders/dx11/tfx.fx
- bin/resources/shaders/opengl/tfx_fs.glsl
- bin/resources/shaders/vulkan/tfx.glsl
Early return when there is no sw blending, no need to run the blend code.
Optimization.
Test games that use PABE.
> GS-hw: Move PABE shader bit to the top of sw blending.

- pcsx2/GS/Renderers/HW/GSRendererNew.cpp
Don't enable blending when only alpha is written.
Optimization.
Check if games didn't break.
> GS-hw: Don't enable blending when only alpha is written.

- pcsx2/windows/WinPowerProfile.cpp
Converts the string returned by the "Get friendly power plan name" to UTF-8 from wide string
Trying to print funny characters from a wide string does not work very well, at least for us, and it was causing the entire string not to be printed at all.
On windows only, start PCSX2, see if it says your power plan settings in the console window.
> GUI: Convert Power plan name to UTF-8

- pcsx2/Gif.cpp
- pcsx2/Gif_Unit.h
Removes DMA reset stuff from a GIF reset.
The two shouldn't be reset together anyway, the GIF has no control over the DMA, it was incorrect and causing currently running DMA's to get stuck in an infinite loop.
Run games, make sure they still work, no specific games here (Except Air Ranger 2) was known to be affected directly, but the adverse is unknown.
Fixes Air Ranger 2 - Rescue Helicopter infinite loop on boot.
> GIF: Separate GIF Reset and GIF DMA Reset

- pcsx2/USB/usb-pad/usb-pad.h
- pcsx2/USB/usb-printer/usb-printer.cpp
- pcsx2/USB/usb-printer/usb-printer.h
Got rid of some warnings in gcc over in the usb code. I decided clang warnings could wait for another time.
Less warnings while compiling.
Compile pcsx2.
> Fix some gcc warnings.

- pcsx2/GS/GSPerfMon.h
- pcsx2/GS/Renderers/SW/GSRasterizer.cpp
Fixes crash when scanline count wasn't divisible by thread count (common with odd thread counts like 5)
Less crashy more runny
Run SW renderer with weird thread counts
> GS:SW: Fix crash when scanline count wasn't divisible by thread count

- bin/resources/GameIndex.yaml
*Changes memcard filters for Ratchet & Clank 2 & 3, renames NTSC-K Ratchet & Clank to Ratchet & Clank - Size Matters.
*Adds HUD/Menu patch for the Russian version of The Legend of Spyro: The Eternal Night.
*Adds eeRoundMode: 2 to Teen Titans and Scaler.
*Fix a few minor grammar issues.
*Ratchet & Clank 1 didn't have an NTSC-K release, so memcard filters were changed accordingly, and the title for the NTSC-K version of Size Matters was wrong, so this has been changed as well.
*The Russian version of TLoS: The Eternal Night didn't have the HUD/menu patch, so I simply ported it myself.
*eeRoundMode is needed for Teen Titans and Scaler to fix some missing texts which was reported here: https://wiki.pcsx2.net/Teen_Titans
*More games made by Artificial Mind & Movement may need eeRoundMode …
> GameDB: Add eeRoundMode to Teen Titans & Scaler and fixes to other games

- pcsx2/gui/GlobalCommands.cpp
Keyed messages don't pile up so spamming turbo/frame limiter keys will not generate multiple messages now.
OSD spam makes messages less clear to the end user.
Switch GS options via hotkeys, like aspect ratio, frame limiter, frame skipping, zoom etc.
> GUI: Make aspect ratio/frame limiter OSD messages keyed

- pcsx2/GS/GSTables.cpp
- pcsx2/GS/GSTables.h
Extends GS row offset tables to 4096 entries for wrapping
Fixes issue introduced by new GSOffset
Test WWE SmackDown vs. Raw 2008
> GS: Support wrapping off-the-end offsets in new GSOffset

- common/CMakeLists.txt
- common/D3D11/ShaderCache.cpp
- common/D3D11/ShaderCache.h
- common/D3D11/ShaderCompiler.cpp
- common/D3D11/ShaderCompiler.h
- common/common.vcxproj
- common/common.vcxproj.filters
- pcsx2/GS/Renderers/DX11/GSDevice11.cpp
- pcsx2/GS/Renderers/DX11/GSDevice11.h
- pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
Adds a shader cache for DX11, similar to the other renderers.
Switching hardware/software renderers is slow in DX11 because it recompiles a bunch of shaders every time.
Test software/hardware renderer switching, make sure it's faster, and that there's no random rendering errors in games.
Test shaders (fxaa/externalfx/shadeboost).
> GS/DX11: Add a shader cache

- pcsx2/GS/Renderers/HW/GSTextureCache.cpp
- pcsx2/GS/Renderers/HW/GSTextureCache.h
The custom clut content hasher for the palettes was dropped in favour of xxHash.
xxHash provides less collisions and is already used for texture hashing in the codebase.
Test some games and check that no visual regression occurs.
> GS: use xxHash to hash palettes.
