cmake/SearchForStuff.cmake, linux_various/pcsx2.desktop.in
The commit messages are quite verbose when compared to the amount of changes I did but in short.
- In some rare cases EGL can't be found and GSdx does not get built.
- Enhance desktop file to make gnome maintainers/developers happy.
I also have another pull request in the works to clean up cross compiling from amd64 to i386 but since that one is bigger I'm sending this one first.
=> Fix GSdx build and enhance the desktop file.

plugins/GSdx/GSWndWGL.cpp
WGL GSdx forward compatible bit
=> WGL GSdx forward compatible bit

plugins/dev9ghzdrk/Win32/smap.cpp
See discussion in https://github.com/PCSX2/pcsx2/issues/439
Hopefully I've created this pull request correctly.
=> Fix warped read code

bin/shaders/GSdx.fx, bin/shaders/GSdx_FX_Settings.ini
Just a few small post processing updates, to improve the bloom and tonemapping. Plus a small fix for the output order.
=> Some post-processing updates.

plugins/GSdx/GSSettingsDlg.cpp
I left out a BREAK.
Blame it on working in FreeBASIC where cases don't fall through. >_<
=> GSdx: Hacks UI: Add missing BREAK that I left out

common/include/Utilities/StringHelpers.h, common/src/Utilities/vssprintf.cpp, pcsx2/DebugTools/DisR5900asm.cpp
Clean some useless function on linux. And likely in the future for windows :)
=> C++11 vssappendf

plugins/GSdx/GSCapture.cpp, plugins/GSdx/GSCapture.h
=> gsdx-recorder: use recursive mutex

linux_various/PCSX2.desktop.in
Trivial change to match uppercase conversion
=> Fix .desktop file

plugins/GSdx/GSDeviceOGL.cpp, plugins/GSdx/GSRendererHW.cpp, plugins/GSdx/GSRendererHW.h, plugins/GSdx/GSTextureCache.cpp, plugins/GSdx/GSTextureCache.h
=> Gsdx half screen snow engine

plugins/GSdx/GLLoader.cpp, plugins/GSdx/GSCrc.cpp
Some minor grammar fixes to OpenGL prints and removed Shadow Hearts CRC
which has been left behind, there is no patch for it in GSstate anymore.
=> OpenGL printf wording corrections, removed Shadow Hearts CRC

pcsx2/gui/AppMain.cpp
This fixes a lockup for Windows wxWidgets 3.0 builds. This is pretty much the same as the previous BIOS error lockup I had, just for plugin open this time.
Here's what I think happens:
* BIOS/plugin open error occurs.
* Modal messagebox pops up.
* GSframe is sent a close message.
* Messagebox intercepts close message and hides itself.
* Messagebox is still running and intercepting all events.
So this commit rearranges the order in which the events happen.
=> Fix plugin open error handling for wx3.0 on Windows

locales/pt_BR/pcsx2_Iconized.po, locales/pt_BR/pcsx2_Main.po
Signed-off-by: Rafael Ferreira <rafael.f.f1@gmail.com>
=> Updated Brazilian Portuguese translation

common/build/Utilities/utilities_vs2012.vcxproj, common/build/Utilities/utilities_vs2012.vcxproj.filters, common/build/Utilities/utilities_vs2013.vcxproj, common/build/Utilities/utilities_vs2013.vcxproj.filters, common/include/Utilities/Math.h, pcsx2/MMI.cpp, pcsx2/x86/iMMI.cpp
Because someone had to do it.
```
git cherry-pick --no-commit 5287de9
git cherry-pick --no-commit -X renormalize d608d97
git commit -m "text"
```
Edit:
For reference next time do this
```
git log  bbf4b58^..bbf4b58 --stat
```
Look for the commit that you actually wanted to revert and don't revert the "merge" commit. The merge you reverted had 3 merges inside of it.
=> Fix the messy revert.

plugins/GSdx/GSDevice11.cpp, plugins/GSdx/GSDevice9.cpp, plugins/GSdx/GSDeviceOGL.cpp, plugins/GSdx/GSRendererDX.cpp, plugins/GSdx/GSRendererHW.cpp, plugins/GSdx/GSRendererOGL.cpp
@prafullpcx2
Could you check 50 cents and a couple of games? Please test DX too, I don't want to introduce some segmentation fault in the main renderer.
=> Depth color direct write

plugins/onepad/CMakeLists.txt, plugins/onepad/GamePad.cpp, plugins/onepad/GamePad.h, plugins/onepad/KeyStatus.cpp, plugins/onepad/KeyStatus.h, plugins/onepad/Linux/dialog.cpp, plugins/onepad/Linux/ini.cpp, plugins/onepad/Linux/linux.cpp, plugins/onepad/SDL/joystick.cpp, plugins/onepad/SDL/joystick.h, plugins/onepad/controller.h, plugins/onepad/joystick.cpp, plugins/onepad/keyboard.cpp, plugins/onepad/onepad.cpp, plugins/onepad/onepad.h
@gregory38 
Okay, clean version of previous PR. Indent are fixed, Everything is in separated commits, change some not so clean change I did to be cleaner. The only redundant stuff that is left is to make sure that every commits compile while keeping each commits coherent.(emptying the DoHapticEffect before time).
SDL is also isolated in its own little class now so that I can proceed to make evdev backend.
Commits contains roughly the same thing as before otherwise. Sorry I closed previous one, I thought I could reopen it... But it is not possible after a force push. I will remember that one.
For GUI, it will be another PR(and according to all logic, not by me as I may contribute there too(since he is 3 meters away) but I am not the one who did the dev.
As for me, I will focus on …
=> Implement rumble and isolate SDL code path

plugins/spu2-x/src/Windows/Config.cpp
@ramapcsx2 : seems like your code ;)
=> SPU2-X: Fix a "Fixme" part of the code.

common/include/Utilities/TraceLog.h, pcsx2/CDVD/InputIsoFile.cpp, pcsx2/CDVD/IsoFileFormats.h, pcsx2/DebugTools/Debug.h, pcsx2/DebugTools/DisassemblyManager.h, pcsx2/gui/MainFrame.h, pcsx2/gui/MemoryCardFolder.cpp, pcsx2/gui/Panels/LogOptionsPanels.h, pcsx2/gui/Panels/MemoryCardListPanel.cpp, pcsx2/gui/Panels/MemoryCardPanels.h, pcsx2/gui/Panels/PluginSelectorPanel.cpp, plugins/GSdx/GSState.cpp, plugins/spu2-x/src/SndOut_Portaudio.cpp
CID numbers are provided in the commit messages.
=> Coverity: Initialize class members 

pcsx2/x86/microVU_Misc.h, pcsx2/x86/microVU_Misc.inl
It might help to increase the speed on linux but it requires extensive tests.
=> Mvu custom search

pcsx2/x86/ix86-32/iR5900-32.cpp
Previous behavior apply the patch when first block is executed (it is
already too late)
V2: First tentative crash some games :(
Fix #627
=> pcsx2: apply patch when first block is compiled

plugins/GSdx/GSTextureCache.cpp
DONT MERGE IT
The goal is to check the impact on game that have wrong RT content.
It helps a bit Smash Court Tennis Pro Tournament 2 but the game suffers
another texture cache bug. (RT BW is 10 whereas texture BW is 8)
Note: Armored Core: Last Raven must be tested (only game so far
that rely on the option and I didn't want to add a new one).
=> gsdx-tc: extend preload frame hack to load target too

plugins/LilyPad/LilyPad.cpp, plugins/onepad/onepad.cpp, plugins/xpad/xpad.cpp
Only bit0 matters for the small motor. Fixes RE4 rumble on movies / map.
Was already fixed on xpad.
=> Fix for odd DualShock rumble (Untested)

bin/GameIndex.dbf
Patches for 7 games have been added including default settings
modifications for Disney's Treasure Planet to prevent few issues.
Thanks to Prafull for the patches !
=> GameDB: Add prafull's Gamefix patches

plugins/spu2-x/src/Windows/SndOut_XAudio2.cpp
Changes:
- GSPanel now uses the CS_OWNDC style - it's apparently required for OpenGL. Might fix some OpenGL pause and resume/renderer switching crashes.
-  An extra LoadLibrary call for XAudio2_7.dll is used in the SPU2-X XAudio2 backend - Might fix the XAudio2 crashes. See http://blogs.msdn.com/b/chuckw/archive/2015/10/09/known-issues-xaudio-2-7.aspx
Needs testing since I don't experience the above crashes on my system, though neither change should make things worse. Build at https://ci.appveyor.com/project/turtleli/pcsx2/build/1.50-test-build/artifacts
=> Windows: Potential fix for XAudio2.7 unload crashes

pcsx2/R3000AInterpreter.cpp, pcsx2/x86/iR3000Atables.cpp
Turns out branches that link do always link, even if the branch is not taken.
=> Fix IOP bltzal and bgezal opcodes

CONTRIBUTING.md
Added the wiki link and better description.
Fix broken link of 'todo'.
Formatted 'Coding Style' to 'Code Formatting Guidelines' for consistency.
Added the Commenting Etiquette link as well.
=> Fixed broken link; Add wiki link; Formatting

common/include/x86emitter/implement/jmpcall.h, common/include/x86emitter/instructions.h, common/src/x86emitter/jmp.cpp, common/src/x86emitter/x86emitter.cpp, pcsx2/x86/iCOP0.cpp, pcsx2/x86/iFPU.cpp, pcsx2/x86/iFPUd.cpp, pcsx2/x86/iMMI.cpp, pcsx2/x86/iR3000A.cpp, pcsx2/x86/iR3000Atables.cpp, pcsx2/x86/iR5900Misc.cpp, pcsx2/x86/ix86-32/iR5900-32.cpp, pcsx2/x86/ix86-32/iR5900Branch.cpp, pcsx2/x86/ix86-32/recVTLB.cpp, pcsx2/x86/microVU.cpp, pcsx2/x86/microVU_Branch.inl, pcsx2/x86/microVU_Compile.inl, pcsx2/x86/microVU_Execute.inl, pcsx2/x86/microVU_Lower.inl, pcsx2/x86/microVU_Macro.inl
Use various helper function to ease arch porting.
=> Recompiler abi wrapper

locales/ru_RU/pcsx2_Iconized.po, locales/ru_RU/pcsx2_Main.po
Updated Russian translation (added not-translated strings and fixed existing ones).
=> Fixes some mistakes in Russian translation

README.md
Just what the title says! :smile: 
Tell me if I missed anything, and make sure to point me to other stuff that could be revised by me. :smiley:
=> Update README for the latest version, and fix a few things

pcsx2/Reference/PS2-MemoryCardFileSystem.htm
This was requested a while ago in #840.
Originally from http://www.csclub.uwaterloo.ca:11068/mymc/ps2mcfs.html. It's public domain, so there's no problem with just putting it in here.
=> Add Memory Card File System documentation to repository for easy reference.

bin/shaders/GSdx.fx, bin/shaders/GSdx_FX_Settings.ini
Updated the GSdx effect suite; improved cel edges of the cel shader; added a debanding shader, and Timothy Lottes' CRT emulation shader, by request.
=> GSdx: Update Post-Processing

pcsx2/gui/Debugger/DisassemblyDialog.cpp
=> StepOut breakpoint fix

common/include/PS2Eext.h
I forgot to edit the other strings, last time.
=> Typo correction #2

locales/fr_FR/pcsx2_Iconized.po, locales/fr_FR/pcsx2_Main.po
Fixed strings @gregory38 mentioned plus other ones, thank you Greg!
=> French localization update, 2nd try

plugins/GSdx/GSRendererHW.cpp
**Summary of changes:**
* Get height/width from display rectangle in case of non-referencable values.
* Minimize the size of rendering target to the minimum required for native scaling resolutions. ( impacts less on performance at 2X native).
* Fixes scaling issues with games which use weird width and height values. closes #1167  (Thanks to @FlatOutPS2 for testing )
Needs testing on whether it causes any other regressions.
build download link: [here](https://ci.appveyor.com/api/buildjobs/jqurlvqea7tcni4t/artifacts/pcsx2-v1.5.0-dev-346-ga867751-master-481-vs2015-Win32-AppVeyor.7z)
=> GSDX: Detect RT size based on display and frame registers.

bin/GameIndex.dbf
**Summaru of changes:**
* Remove some unneeded older patches , prafull's new patch fixes all the older issues.
=> GameDB: Remove some unnecessary old patches

plugins/GSdx/GSRendererHW.cpp
There are likely few games (RE4) which constantly change the FBW register value causing the framebuffer width to be updated at every interval. Adding a safe limit (512) similar to frame buffer height would prevent such constant changes of the framebuffer width when FBW changes once again to an even lower value. 
Might fix #1224 
Build download link: [here](https://ci.appveyor.com/api/buildjobs/ddu3msnyjdtwfgp8/artifacts/pcsx2-v1.5.0-dev-415-g900ed88-master-615-vs2015-Win32-AppVeyor.7z)
=> GSDX: set a safe limit to Framebuffer width

pcsx2/CDVD/CDVDisoReader.cpp
Needs lots of testing. I tried it on my ISOs and it seems to work, but I only have one DVD9 game (GT4), the rest are single layer.
Changes:
* Uses a non brute force approach to find the DVD layer break address.
* No longer caches the layer break address.
The DVD layer 0 sector count is stored in the Volume Space Size field of the Primary Volume Descriptor on DVD layer 0. This value is the same as the total sector count for a single layer DVD and the first layer 1 LSN of a dual layer DVD. So we should be able to use that to quickly find the layer break instead of starting from the middle of the ISO and searching outwards for the layer break (which may not exist).
Fixes #799
=> cdvd:iso: Use Primary Volume Descriptor to find DVD layer break

common/include/x86emitter/tools.h, common/src/Utilities/ThreadTools.cpp, common/src/x86emitter/cpudetect.cpp, pcsx2/DebugTools/DisassemblyManager.h, pcsx2/DebugTools/MipsAssembler.cpp, pcsx2/DebugTools/MipsAssembler.h, pcsx2/Gif_Unit.h, pcsx2/PluginManager.cpp, pcsx2/gui/ExecutorThread.cpp, pcsx2/gui/MemoryCardFile.cpp, pcsx2/x86/microVU_IR.h, plugins/GSdx/GSCapture.cpp, plugins/GSdx/GSRendererOGL.cpp, plugins/GSdx/GSTextureOGL.cpp, plugins/onepad/Linux/GamepadConfiguration.cpp, plugins/onepad/Linux/GamepadConfiguration.h
Various init improvements to reduce Coverity Noise.
=> Coverity uninitialized members

pcsx2/gui/AppCoreThread.cpp
**Summary of changes:**
* Implement all of willkuer's suggestions mentioned over [here](https://github.com/PCSX2/pcsx2/pull/1266#issuecomment-203932894)
* ~~Prioritize cheats_ws archive over cheats_ws folder for displaying status of widescreen hacks found.~~ ``Removed``
* also make the placement of braces consistent throughout the file.
=> PCSX2-Core: Change trigger condition for certain console messages 

plugins/GSdx/GSTextureSW.cpp
=> textureSW: fix Map with offset

bin/GameIndex.dbf
Add XGKicks for Formula One 2001-2003 and World Of Outlaws - Sprint Cars to GameIndex file.
=> GameDB: Add several XGKick hacks

plugins/GSdx/GSDevice.cpp, plugins/GSdx/GSDevice.h, plugins/GSdx/GSDevice11.cpp, plugins/GSdx/GSDevice9.cpp, plugins/GSdx/GSDeviceOGL.cpp, plugins/GSdx/GSHwHack.cpp, plugins/GSdx/GSRenderer.cpp, plugins/GSdx/GSRenderer.h, plugins/GSdx/GSRendererHW.cpp, plugins/GSdx/GSRendererHW.h, plugins/GSdx/GSRendererOGL.cpp, plugins/GSdx/GSState.cpp, plugins/GSdx/GSState.h, plugins/GSdx/GSTextureCache.cpp, plugins/GSdx/GSTextureCacheOGL.cpp, plugins/GSdx/GSTextureOGL.cpp, plugins/GSdx/GSdx.h, plugins/GSdx/stdafx.h
A couple of cleanup to remove some instructions in main draw function
Add basic support of exception. Still need to find a way to hookup with opengl
=> Gsdx cleanup

plugins/GSdx/GSLocalMemory.cpp, plugins/GSdx/GSLocalMemory.h, plugins/GSdx/GSTextureCache.cpp, plugins/GSdx/GSTextureCache.h
Small optimization. I don't expect any speedup but code feel more logical this way.
=> Gsdx array coverage

plugins/GSdx/GS.h, plugins/GSdx/GSRenderer.cpp, plugins/GSdx/GSRenderer.h, plugins/GSdx/GSRendererHW.cpp, plugins/GSdx/GSState.cpp, plugins/GSdx/GSState.h
**Summary of changes:**
* Prevent usage of non-standard / weird DW register values.
Fixes #1073 
**Master branch:**
**Pull request branch:**
**Build download link:** [here](https://ci.appveyor.com/api/buildjobs/x1wt04c52m4249an/artifacts/pcsx2-v1.5.0-dev-444-g39a0e19-master-652-vs2015-Win32-AppVeyor.7z)
=> GSDX: Improve CRTC width detection

pcsx2/DebugTools/Breakpoints.cpp
Fixes #1374
temp bp were not previously handled
=> GetBreakPointCondition handle temp breakpoints

pcsx2/CDVD/CDVD.cpp, pcsx2/Config.h, pcsx2/Counters.cpp, pcsx2/GS.cpp, pcsx2/GS.h, pcsx2/Pcsx2Config.cpp, pcsx2/R5900OpcodeImpl.cpp, pcsx2/gui/FrameForGS.cpp
Reverts PCSX2/pcsx2#1368
I thought I had tested it but aparently I tested some other pr instead.
This still needs work. All my "HDTV" (480p) games run too slow.
=> Revert "PCSX2-Counters: Some Changes to Video mode counter stuffs"

plugins/GSdx/GSTextureOGL.cpp, plugins/GSdx/GSTextureOGL.h
=> gsdx ogl: replace eight 8MB PBO with a single fat 64MB PBO

plugins/GSdx/GSRenderer.cpp
**Summary of Changes**:
* Improve width offset detection of ouput circuits (Fixes #1389)
=> Merge Circuit: Improve offset detection of output circuit

plugins/GSdx/GSRenderer.cpp
Fixes blurring issue on Tenchu Fatal Shadows caused by multiplying
GetScale with the diffence when baseline and display rectangle offsets
differ by a few pixels.
Example of blurring issue resolved by this PR(left master branch, right PR branch):
You should be able to see the difference rightaway, but it's most noticable on the names of the characters in the distance.
**Fixes blurring issues in:**
Tenchu Fatal Shadows
Worms 3D
ProStroke Golf
Vexx
Tribes: Aerial Assault
Gauntlet: Dark Legacy
NHL Hitz Pro
Tak and the Power of Juju
**Fixes (blurring) regression in:**
The Bouncer (same regression as FFXII, but with offset of 2 instead of 1)
**List of games which need to be tested for regressions**:
=> Merge Circuit: Enhance offset detection of output circuit

pcsx2/CDVD/BlockdumpFileReader.cpp, pcsx2/Linux/LnxFlatFileReader.cpp, pcsx2/gui/Debugger/CtrlRegisterList.cpp, pcsx2/gui/Debugger/CtrlRegisterList.h, pcsx2/gui/SysState.cpp, plugins/GSdx/GSDeviceOGL.cpp, plugins/GSdx/GSDeviceOGL.h, plugins/onepad/Linux/GamepadConfiguration.cpp, plugins/onepad/Linux/GamepadConfiguration.h, plugins/onepad/Linux/JoystickConfiguration.cpp, plugins/onepad/Linux/JoystickConfiguration.h, plugins/onepad/Linux/dialog.cpp, plugins/onepad/Linux/dialog.h
Correct a couple of valgrind issue
* mem leak due to missing destructor
* unitilialised value
Only minor stuff but it helps to keep a sane status.
=> Valgrind memleak

common/include/Utilities/Threading.h, common/src/Utilities/Mutex.cpp, common/src/Utilities/ThreadTools.cpp, common/src/Utilities/Windows/WinThreads.cpp, common/src/Utilities/wxHelpers.cpp, pcsx2/GS.h, pcsx2/MTGS.cpp, pcsx2/MTVU.cpp, pcsx2/MTVU.h, plugins/GSdx/GSRendererHW.cpp, plugins/GSdx/GSRendererSW.cpp, plugins/GSdx/GSState.cpp, plugins/GSdx/GSState.h, plugins/GSdx/GSTextureSW.cpp
Related to issue #1437 and #998 
Relax atomic operation to avoid memory barrier.
Edit: require MTGS / MTVU and GSdx-SW heavy test.
Edit2: require VU cycle stealing test too.
=> Atomic relax

pcsx2/CDVD/CDVD.cpp
Pro:
* check read/write status
* close file handle in case of exception
* handle the file is a directory bad case
* barely improved logging
=> Pcsx2 high level fopen

build.sh
1. All POSIX shells support $(...) syntax [1], including /bin/sh. shellcheck
warns about it.
2. [[ won't work in /bin/sh [2], so use [ everywhere. I wonder why it worked
now, perhaps the test was running on a system where /bin/sh -> /bin/bash.
3. In POSIX sh, string indexing is undefined. [SC2039]. Unfortunately, this
means we require a subprocess: https://wiki.ubuntu.com/DashAsBinSh. Very
ugly.
4. In POSIX sh, arrays are undefined. We seem to use $flags as an array
after constructing it by string concatenation. I tried to verify that
this has the same effect as just passing the quoted string in bash:
bash-3.2$ flags="-DCMAKE_GOOK"
bash-3.2$ flags="$flags -DCMAKE_MOARMA"
bash-3.2$ flags="$flags -DCMAKE_URURURUR"
bash-3.2$ ./argv $flags
0: ./argv
1: -DCMAKE_GOOK
2: -DCMAKE_MOARMA
3: …
=> build.sh: simplify and semi-modernize

build.sh
Also suppress spurious output from command -v.
As requested.
=> build.sh: parallelize clang-tidy

plugins/GSdx/GSRendererDX.cpp
Port for Direct3D renderers of PR #1538.
=> GSdx DX: extend ATE to better support additional corner case DX port

plugins/GSdx/GSCrc.cpp, plugins/GSdx/GSCrc.h, plugins/GSdx/GSRendererOGL.cpp
It will work for both Jak and Ratchet&Clank and without CRC
Alternative to PR #1587
=> gsdx ogl: trigger the special RW framebuffer shader when only Alpha is written

plugins/GSdx/GSState.cpp
Game: harley davidson
* write tex0 ctx0
* write tex0 ctx1
* draw  ctx 0
Previous GSdx behavior will load the clut every write of TEX0. In the
above case the draw will take the wrong clut.
To be honest, it could be a wrong emulation on the EE core emulation.
The hardware likely got a single clut (1KB cache is quite expensive)
So clut loading must be skipped if the context is wrong.
Next draw will use the ctx1 clut so I apply TEX0 when the context is switched
Please test harley davidson :)
=> gsdx state: TEX0 write behavior might depends on the context

ISSUE_TEMPLATE.md
* Add an issue template to allow normal users report bugs more efficiently.
Assigned the PR to all the Grammar Nazi's I could find. FWIW, I also enabled the ``edit from maintainer`` option, so in case anyone is interested, feel free to make improvements to the template ;)
Closes #1196
=> PCSX2-Git: Add an issue template file

plugins/GSdx/GSTextureCache.cpp
Likely impact issue #83/#694
Try to play few game to ensure no regression on scaling behavior.
=> gsdx tc: miss a set scaling call

plugins/cdvdGigaherz/src/Windows/IOCtlSrc.cpp
A multi sector raw disk sector read that reads data from two tracks of different types will not complete successfully. Reading the sectors one at a time should fix the issue.
@MrCK1 Could you test the PS1 game(s) that previously had read errors?
=> cdvdgigaherz: Read raw CD sectors one by one

pcsx2/ps2/Iop/PsxBios.cpp
Pretty ghastly code imo, also clearly in the wrong place, this should be a generic per source thing in the console, but @ramapcsx2 wants this badly apparently?
=> IOP: PSX bios console output filtering of repeated and empty lines.

cmake/Pcsx2Utils.cmake, common/vsprops/preBuild.cmd, pcsx2/gui/MainFrame.cpp
Shorter than date and give all the useful info
Require windows test
close #1043
=> pcsx2 gui: use git desribe as version name

plugins/GSdx/GSRenderer.cpp
Fixes screen shaking in Tenchu: Wrath Of Heaven, and graphical issues in NASCAR 09.
=> GSdx Merge Circuit: Fix regressions

plugins/GSdx/GSRenderer.cpp
EDIT: Fixes graphical issues in NASCAR 09 and reverses changes that caused a regression in Time Crisis 2/3 split screen mode.
https://github.com/PCSX2/pcsx2/pull/1683 should prevent the Software mode crashes in the EA NASCAR games.
=> GSdx Merge Circuit: Fix regression and issue

linux_various/PCSX2.desktop.in
Add Simple Chinese translation in .desktop file
Change "Playstation" to "PlayStation". (Official name)
=> Translate Simple Chinese in .desktop file

plugins/GSdx/GSTextureCache.cpp
This reverts commit
https://github.com/PCSX2/pcsx2/commit/d6383e6c211e03a9bb036c6fc8655cd6bba8b9ff
Link to original pull request:
https://github.com/PCSX2/pcsx2/pull/1472
It created a regression in Everybody's Golf 4/Hot Shots Golf 4, breaking the renderering when depth emulation is disabled/when using a Direct3D Hardware renderer.
=> Revert "gsdx tc: partial support of pseudo depth for Dx"

locales/es_ES/pcsx2_Iconized.po, locales/es_ES/pcsx2_Main.po
Updating Spanish translation with latest changes.
=> Updating Spanish translation

bin/docs/PCSX2.1
I updated the man page a bit and rewrote it using mdoc macros.
=> man-page: Update and use mdoc macros

plugins/GSdx/GSState.cpp, plugins/GSdx/GSState.h, plugins/GSdx/GSTextureCache.cpp, plugins/GSdx/GSVector.h, plugins/GSdx/config.h
* Improve auto selection of the output circuit when ``GetDisplayRect()`` is called without any parameter.
**(refer the commit message for more details)**
* Update a debug message on ``GetFrameRect()``.
* Remove some redundant conditional checks.
=> GSdx-PCRTC: Improve output circuit auto selection

plugins/GSdx/GSDialog.cpp
* Prevent comboboxes from reaching an indeterminate state **(Refer commit message for more details)**
=> GSdx: Improve robustness of ComboBoxInit()

plugins/GSdx/GSWndWGL.cpp, plugins/GSdx/GSWndWGL.h
Hopefully it will support more drivers #1813 
Need to check compilation and the above issue.
=> gsdx wgl: retry to create a context without advance flag

README.md
Because changing them with one commit fails for some magical reason -_-
=> Removing broken images - Adding new ones 1/2

plugins/GSdx/GSRendererDX.cpp, plugins/GSdx/GSRendererOGL.cpp
* Properly enable alpha testing when necessary. (_Refer commit message for more details_)
**(**Closes #1847**)**
=> GSdx: Fix Alpha test value initialization

locales/nb_NO/pcsx2_Iconized.po, locales/nb_NO/pcsx2_Main.po
Here's the pull request, as I was told to do on the forums. :)
=> Norwegian translation update

plugins/GSdx/xbyak/xbyak_util.h
=> gsdx: disable GCC optimization when checking SSE/AVX support

plugins/GSdx/GSDrawScanline.cpp
See commit for the full details.
I will likely open a GCC bug.
Edit: actually it is a regression of GCC4.9. GCC4.8 is fine (unoptimal code is generated)
=> gsdx: workaround AVX2 generated code by GCC

common/src/Utilities/ThreadTools.cpp
Issue: wait of the semaphore timedout. However semaphore was properly posted
counter is 1.
To workaround the issue, only throw an error if semaphore counter is 0.
Note: I reduced the timeout to 100ms by threads to avoid huge startup delay
Close #1939
=> common: workaround to start ASAN with recent glibc

plugins/GSdx/GS.cpp, plugins/GSdx/GSUtil.cpp, plugins/GSdx/GSUtil.h
Close #1935
@orbea could you test it ?
=> gsdx: defer init of GSUtil global object

plugins/GSdx/GLLoader.cpp
Follow up to
https://github.com/PCSX2/pcsx2/commit/ec63b04719fd9c05a6aeeacb55dc1c54f5ef145b
Add intel broken driver wiki link message , print intel and amd buggy
driver message once , pring texture barrier and viewpoint array info
once.
Some other minor edits.
=> GSdx-ogl: Printing console messages v2

plugins/GSdx/GSDeviceOGL.cpp, plugins/GSdx/GSDeviceOGL.h, plugins/GSdx/GSRendererOGL.cpp, plugins/GSdx/res/glsl/tfx_fs.glsl, plugins/GSdx/res/glsl/tfx_vgs.glsl
Fix depth effect regression on Nemo (issue #1979)
=> gsdx ogl: handle float integral coordinate for depth sampling

plugins/GSdx/GSState.cpp
**Summary of changes**
* Improve framebuffer height calculation by also consider the DBY value of the DISPFB register. (For more information, check the commit message) **Fixes software mode issue mentioned on #1986**
Tested GS Dumps of Nascar, Beyond Good and Evil, [FMV bottom issue](https://github.com/PCSX2/pcsx2/issues/1562#issuecomment-270256331) reported by @MrCK1 and Crash Bash. All of them are fine with this, more tests would also be nice.
Also I added this to the 1.6 milestone list as this needs to be merged before the 1.6 release, not because it's a big progress or anything. :P
=> GSdx: Rework framebuffer height calculation

plugins/GSdx/GSSettingsDlg.cpp
Fix a small oversight on my part. (Closes #2019)
=> GSdx-Windows: Fix Shadeboost text bug

plugins/GSdx/GSDevice11.cpp, plugins/GSdx/GSDevice11.h
=> GSdx-D3D11: Avoid undefined behavior in swapchain

locales/fr_FR/pcsx2_Iconized.po, locales/fr_FR/pcsx2_Main.po
Update French translations.
By @atomic83GitHub
Improve/Close #2020
=> Translations: French Language Update

plugins/GSdx/GSTextureCache.cpp
Extent support of HW hack Preload Frame Data to work on Direct3D.
Fixes glitchy water in Rogue Galaxy in Direct3D.
Fixes car reflection in Test Drive Unlimited.
Other games that have a similar issue might be fixed as well.
@bositman did the testing and it seems it works. I'd like for @Ryudo300 to test the PR as well :smile: 
gsdumps also indicate that it works.
Close #462 
Close #1125
=> GSdx: Extend support of "Preload Frame Data" for Direct3D

common/src/Utilities/Windows/WinMisc.cpp
Roses are red, violets are blue, if I can't rebase properly; why should you 😛
=> Flag XP as an unsupported OS.

bin/GameIndex.dbf
Fix some typo issue with positive.
This PR can be merge.
[skip ci]
=> GameDB: Beyond good and evil fix 2

bin/GameIndex.dbf
Add some fix for these 2 games along with a comment for Nascar 09
[skip ci]
=> Game DB: fix for Star Wars Bounty Hunter and Petz-horsez 2

plugins/GSdx/GSHwHack.cpp
Oh no, not another CRC hacks PR ...
Merge CRC hacks of Wild Arms 4 and 5 in to one.
It's better to avoid duplicate code.
=> GSdx: Merge CRC hacks of Wild Arms

common/include/Utilities/FixedPointTypes.inl
Relevant issue:
https://github.com/PCSX2/pcsx2/issues/2305
=> FixedPoint: Subtraction operations fix

bin/GameIndex.dbf
A long time that I want to post these fix for this major game.
It will need a least 1 test per version (PAL,NTSC,NTSC-J), I have tested the Pal F version and Round mode to negative fix some reverse boss and control issue. The International version is not supported in this PR.
Close https://github.com/PCSX2/pcsx2/issues/760
=> GameDB: Final Fantasy X fix

bin/GameIndex.dbf, pcsx2/gui/Panels/GameFixesPanel.cpp
Fixes performance drops and short freezes in adventure mode.
Alas, there is no Crash Tag Team Wrestling, so I replaced it with the
correct title.
Updates Gamefixes Panel entry of VU I bit Hack.
Closes #1785
=> GameDB: Update Crash Tag Team Racing

bin/GameIndex.dbf
EE clamping mode to full fix Max Payne from crashing and freezing.
VU clamping mode to extra fix some reflexion issue in Klonoa 2.
Can be merge, I have done a lot of testing.
Close #2141
=> GameDB: Max Payne, Klonoa 2, Evolution Snowboarding, Mana Khemia and Fifa Street 2 fixes

pcsx2/gui/Panels/LogOptionsPanels.cpp
Minor lingual correction of a Trace Logging text-string.
=> PCSX2: Minor lingual correction of a Trace Logging text-string.

bin/GameIndex.dbf
Removes intro and end credits FMVs.
Fixes hanging caused by FMVs.
https://forums.pcsx2.net/Thread-Quake-3-Revolution-SLUS-20167-U--29913
https://forums.pcsx2.net/Thread-Quake-3-Revolution-SLES-50126-E
=> GameDB: Add Quake 3 Revolution patch

plugins/GSdx/GSCrc.cpp
=>  GSdx: Add Sly 3 demos crc ids

bin/GameIndex.dbf
Added "same CRC" info to SLES-51192 & SLUS-20576.
=> Added the ScarfaceIbitHack to the Scarface NTSC-U discs.

common/include/x86emitter/x86_intrin.h, common/src/x86emitter/cpudetect.cpp
Work around the GCC _xgetbv bug.
See #2425.
EDIT: Assigned to myself since I need to add more info to the commit description.
=> common: Work around GCC8 _xgetbv bug

bin/GameIndex.dbf
A short version of the closed pull request with some new adds, this was made in order to save the time of the devs and for avoid users to manualy add these folowing hacks.
All games have been tested, can be merge.
=> GameDB: Vampire Night fixes and code formatting.

plugins/GSdx/res/tfx.fx
Commit b0af54d3
Fixes shadows in Star Ocean 3 in Direct3D10/11.
Tested the shadows no longer appear stretched with stripes and are
properly projected on the ground on the first level.
Note: It works properly on native res only just like on GL.
PR:
Master:
Dump for testing:
[Star Ocean 3 Shadows.zip](https://github.com/PCSX2/pcsx2/files/2042458/Star.Ocean.3.Shadows.zip)
Fixes #374
=> GSdx: Port better support of palette from OpenGL to Direct3D

bin/GameIndex.dbf
This PR brings some Patches to fix various unplayable games (made by Prafull). It also add some comment for Savage skies to warn users to use the interpreter + cache and missing rounding fix for some version of Shin Megami Tensei 3.
=> GameDB: Various patches update.

plugins/GSdx/GSCrc.cpp, plugins/GSdx/GSHwHack.cpp
Ease the crc hack and skip less effects.
=> GSdx: Adjust Ghost In The Shell SOC crc hack

plugins/GSdx/GSCrc.cpp
Kunoichi\Nightshade RU,
Tenchu Fatal Shadows Beta version RU,
Urban Reign RU,
Ghost In The Shell SAC RU.
=> GSdx: Add some missing crc ids.

plugins/GSdx/GSCrc.cpp
GSdx: Add missing CRC id.
Add TombRaiderUnderworld RU.
=> GSdx: Add missing CRC id.

plugins/GSdx/GSCrc.cpp, plugins/GSdx/GSHwHack.cpp
Less effects are missing (post-processing is restored and interface in 60hz mode). Add crc id CrashBandicootWoC RU
=> GSdx: Adjust Spartan crc hack

pcsx2/DebugTools/DebugInterface.cpp
Spent more time manually working around this issue than I care to admit.
=> Debugger: Fix issue #1572 (display correct VU values in debugger)

pcsx2/Docs/readme-Docs.txt
I'm new to here. Even though I can't help much in coding, so I do try to correct some grammars and typos for easier understanding.
=> Grammar corrections in readme-Docs.txt

pcsx2/DebugTools/Debug.h, pcsx2/Gif.cpp, plugins/GSdx/GSDeviceOGL.cpp, plugins/GSdx/GSTextureOGL.cpp, plugins/GSdx/GSTextureOGL.h, plugins/onepad/SDL/joystick.cpp, plugins/onepad_legacy/SDL/joystick.cpp, plugins/spu2-x/src/Wavedump_wav.cpp
Fixes some clang compilation warnings.
=> Reduce clang compilation warnings

pcsx2/DebugTools/DebugInterface.cpp
Displays/allows ACC VU0f register to be set.
=> Debugger: Display ACC register

pcsx2/Config.h, pcsx2/MTVU.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/gui/AppConfig.cpp, pcsx2/gui/Panels/ConfigurationPanels.h, pcsx2/gui/Panels/SpeedhacksPanel.cpp, pcsx2/x86/microVU_Execute.inl, pcsx2/x86/sVU_zerorec.cpp
A bit of rephrasing to the EE cyclerate and VU cycle stealing tool tips to try and combat some false opinions based on the current phrasing.
=> PCSX2: Change EE cyclerate and VU cycle stealing tool tips

plugins/GSdx/res/glsl/tfx_fs.glsl, plugins/GSdx/res/tfx.fx
Follow up to https://github.com/PCSX2/pcsx2/pull/2608#issuecomment-426311409
=> GSdx: Limit Wrap negative UV when PS_FST is 0 only

travis.sh
=> Update Travis CI for Linux networking addition

plugins/GSdx/GSRendererDX.cpp
Commits:
https://github.com/PCSX2/pcsx2/commit/7979dec5b089ef7435f344c7d3eead521efe1f3c
https://github.com/PCSX2/pcsx2/commit/15b934eb2a85b680e9e61dad7fc6138b60321bc7
=> GSdx-d3d: Optimize colclip 0 port from OpenGL

plugins/GSdx/GSDeviceDX.cpp, plugins/GSdx/GSTextureFX11.cpp, plugins/GSdx/GSTextureFX9.cpp
Commit:
https://github.com/PCSX2/pcsx2/commit/97b38d9e1bf0a26bff41766d0206a5498393698e
=> GSdx-d3d: Port directly set impossible blend in the blending table from OpenGL

plugins/GSdx/GSdx.vcxproj.filters
VS filter fixes for you arcum.
=> Update Visual Studio project filters

plugins/GSdx/GSCrc.cpp
Add missing RU crc id: RedDeadRevolver
=> GSdx: Add a CRC id for RedDeadRevolver RU

README.md
=> Minor README edit by TheTechnician27

bin/GameIndex.dbf
Sorry, but I found Error on my commit of Ace Combat V Patch file.
I apologize.
=> GameDB: Fix Ace Combat V Patch Address

plugins/GSdx/Renderers/HW/GSHwHack.cpp
Create a Aggressive state function instead of adjusting the hacks
separate, move the aggressive only there, also use "else if" checks
instead. It's more efficient this way.
=> GSdx: Adjust Aggressive state crc level.

tools/GSDumpGUI/Core/Program.cs, tools/GSDumpGUI/Forms/frmMain.cs
=> GSDumpGui: Update code to share only one gsdx config for all dlls

plugins/GSdx/res/fxaa.fx
=> fxaa.fx: Purge d3d9 shader code

plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp, plugins/GSdx/Renderers/HW/GSRendererHW.cpp, plugins/GSdx/Renderers/HW/GSRendererHW.h, plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp, plugins/GSdx/res/tfx.fx
Bonus: fix m_vt value
Miss Dx and some tests ;)
=> gsdx hw:move vertices fixup for texture shuffle in RendererHw

pcsx2/R5900OpcodeImpl.cpp
More readability of logging.
Suggested by ssakash
=> PCSX2-EE: Improve SetGSCrt logging

pcsx2/CDVD/CDVD.cpp, pcsx2/Config.h
=> cdvd: Get rid of code that disabled loading psx discs

bin/GameIndex.dbf
JayBee requested the pnach file and confirmed it worked.
=> GameIndex: Add PSI's fix for Panzer Dragoon

pcsx2/Patch.cpp, pcsx2/Patch.h
(actually ref to @lightningterror  and my conversation)
You can use it to add Author to indicate who made this patch.
=> Pnach: Add Author line

README.md
Replace GHz with STR requirements,
Mention that 1.4 is the last version to support D3D9.
=> Readme.md: Update system requirements info

locales/pt_BR/pcsx2_Main.po
- A lot of grammatical errors were fixed;
- Several sentences were reformulated for a better understanding and a better quality of the translation.
=> Br. Portuguese Translation - Update

tools/GSDumpGUI/Core/Program.cs, tools/GSDumpGUI/Forms/frmMain.cs, tools/GSDumpGUI/Library/TCPLibrary/Base/Server.cs
Fixes multiinstance crash as now every instance has its own port
=> GSDumpGui: Automatically find the next free TCP port by setting requested port to 0

bin/GameIndex.dbf
This PR allow each fixes to by apply in all situations (such as exiting from the NETGUI utility). It makes these games completely playable in all cases.
=> [Game DB] Visual concept games hanging fixes.

plugins/GSdx/Window/GSSetting.cpp
* fixes typos on the tooltip for disabling safe features
=> Fix 2 minor typos

pcsx2/Config.h, pcsx2/Pcsx2Config.cpp, pcsx2/gui/Panels/GameFixesPanel.cpp, pcsx2/x86/microVU.cpp, pcsx2/x86/microVU_Compile.inl
This PR fixes constant recompilation problems in Crash Tag Team Racing. Closes #2903.
All credit goes to hibye8313 ;)
=> microVU: Add gamefix for Crash Tag Team Racing

plugins/GSdx/Renderers/HW/GSRendererHW.cpp
=> Gsdx: Check for null texture before commit in hacks

bin/GameIndex.dbf
Allow pass the initial splash screen
EETimingHack = 1
=> Fix for Mafia (S) SLES-52282

3rdparty/pthreads4w/autostatic.c
This PR modifies a **third party module** - I realize normally those should be fixed upstream, but I **really** doubt pthreads4w would a) consider it a valid bug and b) fix it. To make all my changes easily visible, I wrap them all in `#if PCSX2_FIX`.
This PR fixes a process exit routine in pthreads. This third party module exploits CRT initialization order to inject their initializer/deinitializer earlier than the others by putting their functions in `.CRT$XCU` and `.CRT$XPU` pseudo regions. The problem comes when a module gets build with dynamic CRT (`/MD` or `/MDd`), like most of PCSX2 plugins, it doesn't actually use `.CRT$XPx` regions as terminators, and instead lets dynamic CRT handle them.
This PR corrects this issue by registering the terminator via `atexit`, so it works with both …
=> 3rdparty/pthreads4w: Fixup process exit logic

pcsx2/Counters.cpp
This fixes timing issues Jak II, Fatal Fury Battle Archives (1) and
Shadow Of Rome.
Follow up from #2275
I tested Shadow of Rome ntsc demo and it does fix the fmv in the intro.
Close: #360
Close: #1712
Close: #2135
=> PCSX2-Counters: Revert to older VRender/VBlank timings

bin/GameIndex.dbf
This PR add a patch to solve a crash in the game "Fahrenheit".
Tested by atomic83github
=> GameDB: Fahrenheit asylum crashing fixes.

plugins/GSdx/GSCrc.cpp, plugins/GSdx/GSCrc.h, plugins/GSdx/Renderers/HW/GSRendererHW.cpp
Fixes flashing / strobing windows.
Fixes #1342
=> GSdx-hw: Add Persona 3 to automatic mipmapping (basic level)

bin/GameIndex.dbf
This PR add various GameDB fixes.
This contain tha addition of several game patches, the removal of some unused/deprecated hacks, the addition of some new gamefixes/hacks and some serial updates.
=> GameDB: Various updates

bin/GameIndex.dbf
This adds  burnout3 demo , International Cue Club 2 and Telly Addicts  to  Game DB
=> GameDB: add International Cue Club 2 and burnout3  demo and telly addics 

nsis/SharedDefs.nsh, nsis/pcsx2_full_install.nsi, nsis/pcsx2_shared_init.nsi
Updated the installer for the VS redistributable to use the newer variant. Clarified some comments and removed unused defines for the PDF docs.
=> NSIS: Update VC Redist URL, misc.

tools/GSDumpGUI/Forms/Helper/ExtensionMethods.cs, tools/GSDumpGUI/Forms/frmMain.Designer.cs, tools/GSDumpGUI/GSDumpGUI.csproj
=> GSDumpGUI: Add context menu to GSdx and Internal log.

cmake/SearchForStuff.cmake
=> cmake: Fix issue with Harfbuzz not being found

pcsx2/gui/MainFrame.cpp
Makes UI more consistent as per #3262
Close #3262
=> Change order of "Video (GS)" submenu

ISSUE_TEMPLATE.md, README.md
Update issue template with newer release versions.
Update readme, list windows 7 and 8 as no longer supported.
=> Misc documentation updates.

bin/GameIndex.dbf
#3391 Sorry for the mess. I bluescreened and not sure whats happened. Should be fixed now
=> GameDB: Fix Multiple Games

bin/GameIndex.dbf
=> [GameDB] add Slam Tennis 

pcsx2/COP0.cpp
This makes Next Generation Tennis 2003 (Roland Garros French Open 2003) work.
=> Implemented memory mode check in cop0.cpp

bin/GameIndex.dbf
GameDB: adds fixes to
- Tiger Woods PGA Tour 06
=> GameDB: Add manual gamefixes

bin/GameIndex.dbf
=> GameDB: Butt Ugly Martians

bin/PCSX2_keys.ini.default
Revise gsdx hotkeys (dithering) and others.
=> [skip ci] Update PCSX2_keys.ini.default hotkey info comments for gsdx.

plugins/GSdx/Renderers/HW/GSRendererHW.cpp
In GSRendererHW, reuse the method CanUseSwSpriteRender for OI_JakGames.
As in current master, 16x16 "flat" sprite draws are performed via CPU: those are palette rendering better emulated with the SwSpriteRender.
Jak games do also many 64x64 "flat" draws, but mostly for render to texture effects that are already correctly emulated in the TC, so those draws are not done via CPU (as on the contrary happens for DBZ BT games).
=> GSdx-hw: use CanUseSwSpriteRender in OI_JakGames.

bin/GameIndex.dbf
This will make it more uniform.
=> Cleanup and fixing formatting of GameDB.

bin/GameIndex.dbf
GameDB: King of Colosseum Green (3492) Fixes #3448.
=> GameDB: King of Colosseum Green

pcsx2/gui/ConsoleLogger.cpp
Adds a modern dark mode to the console that is atleast usable while not burning my eye sockets.
=> Modern Dark Console

bin/GameIndex.dbf, pcsx2/Vif0_Dma.cpp, pcsx2/Vif1_Dma.cpp
Fixes:
The Sims
Spiderman 3
Sharks Tale
Maybe some bits of Over the Hedge
Pitfall (both demo and full game)
Gumball 3000
Enter the Matrix
=> VIF MSCAL instructions wait on VU T-Bit stop

bin/GameIndex.dbf
=> GameDB: Test Drive Unlimited.

common/src/Utilities/Windows/WinMisc.cpp
List Windows 8.1 and Windows 10 as supported OSes only.
Windows 8.0 and lower as unsupported.
Simplify/clean up the code.
Alternative of #3372
Close #3372
=> pcsx2: Adjust windows OS support logs.

bin/GameIndex.dbf
fixes the gamedb for KOF: Maximum Impact - Maniax
Close #3511
=> KOF: Maximum Impact - Maniax GameDB

bin/GameIndex.dbf
Unecessary Since USBQemu can do eyetoy emulation
=> GamesDB: Remove Eyetoy Check

bin/GameIndex.dbf
Add missing Crash Tag Team Racing I bit hack description, and add automatic VU Full clamping for Persona 4 EU. 
fixes #3487
=> GameDB: Add CTTR hack description, add Persona 4 PAL VU clamping

pcsx2/x86/microVU_Compile.inl
microVU: Fix state saving when m-bit is reached
microVU: Fix range merging to encompass whole ranges of programs
Fixes Ridge Racer V lights in tunnels (Regression from PR #3593
Fixes shadows in The Shadow of Zorro
Fixed slight SPS in Totally Spies Totally Party! Still needs Cyclerate +3 however
=> microVU: Fix m-bit state and range merging

bin/GameIndex.dbf
- Spiderwick Chronicles
- Amplitude
=> Gamedb: Remove patches and add manual gamefixes

pcsx2/Gif.cpp, pcsx2/IPU/IPUdma.cpp, pcsx2/SPR.cpp, pcsx2/Sif0.cpp, pcsx2/Sif1.cpp, pcsx2/Vif1_Dma.cpp, pcsx2/ps2/LegacyDmac.cpp
Implemented SIF0 and SIF1 DMA Stall handling
Only required message has been moved to development builds only
=> DMAC: Improve DMA Stall handling

plugins/GSdx/GSState.cpp
Confirmed to be a core issue.
See: #3568
=> GSdx: Purge International Star Soccer Hack

PCSX2_suite.sln
A conflict was inadvertently merged in https://github.com/PCSX2/pcsx2/pull/3518, thanks to @Florin9doi for noticing it. This PR fixes it.
=> CDVD: fix conflicts merging

.github/workflows/linux-workflow.yml, .github/workflows/windows-workflow.yml, README.md
Examples:
- On a commit - https://github.com/xTVaser/pcsx2-rr/actions/runs/261579862
- On a PR - https://github.com/xTVaser/pcsx2-rr/actions/runs/261579862
=> Github Actions: Cache submodules and fix artifact naming

bin/GameIndex.dbf
update Legend of Kay in gameDB
=> GameDB: Fix trees in Legend of Kay

CMakeLists.txt, cmake/BuildParameters.cmake, pcsx2/CMakeLists.txt, plugins/GSdx/CMakeLists.txt, plugins/GSnull/CMakeLists.txt, plugins/LilyPad/CMakeLists.txt, plugins/PadNull/CMakeLists.txt, plugins/SPU2null/CMakeLists.txt, plugins/USBnull/CMakeLists.txt, plugins/dev9ghzdrk/CMakeLists.txt, plugins/dev9null/CMakeLists.txt, plugins/onepad/CMakeLists.txt, plugins/onepad_legacy/CMakeLists.txt, plugins/spu2-x/src/CMakeLists.txt
_This does not implement c++17 std::filesystem!_
=> Bump up C++ version to c++17 for gcc & clang

nsis/SharedDefs.nsh
Separate message boxes for v1.4.0 and v1.6.0.
=> [skip ci] nsis: Update message box for minimum supported os.

pcsx2/System/SysCoreThread.cpp
Probably fixes https://github.com/PCSX2/pcsx2/issues/3758
=> CDVD: fix for loading games in BIOS

bin/GameIndex.dbf, pcsx2/SaveState.h, pcsx2/Sif.h, pcsx2/Sif0.cpp
Fixes True Crime: Streets of LA
Backported from Dobiestation
=> SIF: Transfer SIF0 junk for partial QW transfers from IOP

bin/GameIndex.dbf
=> GameDB: VU0Kickstart to 24 the game

bin/GameIndex.dbf
Fixes main character model SPS.
=> GameDB: VU0 Kickstart to Blood Will Tell

plugins/GSdx/GSClut.cpp
fix international superstar soccer properly this time
=> gsdx: properly init gsclut function ptrs

pcsx2/System/SysCoreThread.cpp, pcsx2/System/SysThreadBase.cpp, pcsx2/System/SysThreads.h, pcsx2/gui/MainMenuClicks.cpp
Let us hope this one works for once.
=> CDVD: fix ISO swapping, round 4

bin/GameIndex.dbf
=> GameDB: corrects sly 3 name 

pcsx2/x86/microVU_Compile.inl
=> microVU: Make sure flags are exact on M-bit

pcsx2/SPU2/Linux/CfgHelpers.cpp
Hopefully this appeases travis
=> SPU2: missing pch

pcsx2/SPU2/Linux/Alsa.cpp, pcsx2/SPU2/Linux/Config.cpp, pcsx2/SPU2/Linux/ConfigDebug.cpp, pcsx2/SPU2/Linux/ConfigSoundTouch.cpp, pcsx2/SPU2/Linux/Dialogs.cpp, pcsx2/SPU2/SndOut_SDL.cpp
This should fix travis for good this time
=> SPU2: more missing PCH

pcsx2/gui/MainFrame.cpp
=> pcsx2: enable hostfs on release builds

bin/GameIndex.dbf
- Galerians Ash (NTSC + PAL)
- Gladiator: Sword of Vengeance (NTSC)
- IHRA Professional Drag Racing 2005 (NTSC)
- Musashi Samurai Legend (NTSC)
- Pilot Down: Behind Enemy Lines (PAL)
- Superman Returns (NTSC + PAL)
- Test Drive (NTSC)
- TD Overdrive: The Brotherhood of Speed (PAL)
- WRC 4 (PAL)
=> GameDB: Patches for 12 games (or 9 individual games)

plugins/GSdx/GSClut.cpp
=> Revert "gsdx: properly init gsclut function ptrs"

pcsx2/x86/microVU.cpp, pcsx2/x86/microVU_Compile.inl, pcsx2/x86/microVU_Misc.h
Fixes constant recompilation in
IHRA Drag Racing
Dawn of Mana
=> microVU: Fix program range wrapping

pcsx2/Cache.cpp, pcsx2/Cache.h, pcsx2/SaveState.cpp
Major cache rewrite, it successfully boots the bios but it should be tested with games that need cache emulation to make sure it doesn't break those.
Fixes #3812
=> Update cache emulation for 64 bits

bin/GameIndex.dbf
=> GameDB: Remove IHRA 2005 patch

bin/GameIndex.dbf
-VuClamp to extra to fix minimap HUD.
=> GameDB: 24 The game

pcsx2/CDVD/CDVD.cpp, pcsx2/CDVD/CDVD.h, pcsx2/CDVD/CdRom.cpp, pcsx2/CDVD/CdRom.h, pcsx2/HwWrite.cpp
Fix to CD speed courtesy of Ref. Restored amount of old pcsx code for CDDA
=> Check register 14 (ps1 status register) for cd speed and CDDA 

common/src/x86emitter/cpudetect.cpp, plugins/GSdx/Renderers/SW/GSDrawScanlineCodeGenerator.x64.avx.cpp
Comment out the unused variables.
=> Misc: Fix a few warnings on x64 build.

pcsx2/SPU2/Linux/Config.cpp, pcsx2/SPU2/Windows/Config.cpp
also switched fprintf to Console.Warning
=> SPU2: default to XAudio when failing to read conf

pcsx2/CDVD/CdRom.cpp
Full commit hash: ada804741957e813602bd33f2989b5bceea42913
=> CDVD: fix logic bug introduced in ada80474

pcsx2/USB/Win32/Config_usb.cpp, pcsx2/USB/configuration.cpp, pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp, pcsx2/USB/usb-hid/usb-hid.cpp, pcsx2/USB/usb-mic/usb-headset.cpp, pcsx2/USB/usb-mic/usb-mic-logitech.cpp, pcsx2/USB/usb-mic/usb-mic-singstar.cpp, pcsx2/USB/usb-pad/dx/dinput-config.cpp, pcsx2/USB/usb-pad/usb-pad.cpp, pcsx2/USB/usb-pad/usb-seamic.cpp
Fixes https://github.com/PCSX2/pcsx2/issues/3921 and probably a few other issues.
Testers will henceforth be fired.
=> USB: misc fixes on settings string conversion

pcsx2/System/SysThreadBase.cpp
This was causing DEV9 code to crash
Possibly also fixes some CDVD issues that where apparently happening?
=> Don't reopen everything when we just want to reopen the CDVD

bin/GameIndex.dbf
Partial revisioning and adding new entries, first commit mostly focused on SLES. Others will be checked as well later.
=> GameDB: Add new entries part 1

common/include/PS2Edefs.h, pcsx2/gui/GlobalCommands.cpp
=> core: send osd log event when snapshot is taken

.github/workflows/linux-workflow.yml, pcsx2/USB/usb-mic/audiodev-pulse.cpp
=> Fix build with old libsamplerate

common/src/x86emitter/x86emitter.cpp, plugins/GSdx/Renderers/SW/GSDrawScanlineCodeGenerator.x64.cpp, plugins/GSdx/Window/GSSettingsDlg.cpp
=> Misc: Again more warnings cleanup.

pcsx2/SPU2/Mixer.cpp
PR lowers the overall volume, stopping it being insanely loud and reduces distortion
=> SPU2: Adjust final mix volume

pcsx2/SPU2/Linux/Config.cpp, pcsx2/SPU2/SndOut.h, pcsx2/SPU2/Windows/Config.cpp, pcsx2/SPU2/defs.h, pcsx2/SPU2/spu2sys.cpp
Properly handle KeyOn/KeyOff happening in quick succession.
Hopefully fixes everything in #2371
Fixes #3795
=> SPU2: Get rid of the need for delay cycles

bin/GameIndex.dbf
Add patches for another Idea Factory games.
Info here: https://github.com/PCSX2/pcsx2/pull/3854
=> GameDB: Add patches for Idea Factory games

pcsx2/gui/AppCorePlugins.cpp, pcsx2/gui/AppMain.cpp
=> GUI: Resolve issue causing a crash when using `Close All Windows` while a game is running

pcsx2/gui/Panels/ConfigurationPanels.h, pcsx2/gui/Panels/SpeedhacksPanel.cpp
attempt to fix the speedhacks panel
=> core: fix speedhacks panel

bin/GameIndex.yaml
Fixes bad polygons on characters. Closes https://github.com/PCSX2/pcsx2/issues/4020
=> GameDB: Add VU0 Kickstart for King Kong

bin/GameIndex.yaml
=> GameDB: Add GIF FIFO Hack for Fight Night Round 3

pcsx2/USB/USB.cpp, pcsx2/USB/USB.h, pcsx2/USB/Win32/Config_usb.cpp, pcsx2/USB/configuration.cpp, pcsx2/USB/linux/config-gtk.cpp, pcsx2/USB/platcompat.h, pcsx2/USB/shared/rawinput_usb.cpp, pcsx2/USB/shared/shared_usb.cpp, pcsx2/USB/usb-hid/evdev/evdev.cpp, pcsx2/USB/usb-hid/evdev/evdev.h, pcsx2/USB/usb-hid/raw/rawinput.cpp, pcsx2/USB/usb-hid/usb-hid.cpp
Fix some things I noticed. There could be lurking more.
=> USB: Fix some issues with save states

pcsx2/MTVU.cpp, pcsx2/Vif_Codes.cpp
Fixes graphical issues in Fatal Frame 2 when swapping to MTVU
=> VIF: Always update MTVU thread with Row/Col Changes

bin/GameIndex.yaml
Adding punctation, removing duplicate serial and making english language more happy for reading.
=> GameDB: Cleanup comments

pcsx2/PAD/Windows/PAD.cpp
Remove some leftover code that was related to resizing the game window. Also removed code that was used for displaying a title on the game window. No longer needed since this is merged into core.
=> PAD (Windows): Remove obsolete code related to the output window

plugins/GSdx/GSCrc.cpp, plugins/GSdx/GSCrc.h
=> GS: Remove Unofficial CRCs

3rdparty/include/ghc/filesystem.h, common/build/Utilities/utilities.vcxproj, common/src/Utilities/CMakeLists.txt, common/vsprops/3rdpartyDeps.props
This is a PR to add GHC filesystem to pcsx2 common utilittes
=> Add GHC Filesystem 

pcsx2/IopCounters.cpp, pcsx2/SPU2/Dma.cpp, pcsx2/SPU2/ReadInput.cpp, pcsx2/SPU2/defs.h, pcsx2/SPU2/spu2.cpp, pcsx2/SPU2/spu2sys.cpp, pcsx2/SaveState.h
Savestate bump, sorry
Should fix the games broken by the recent work hopefully.....
=> SPU: Fix bugs in recent commits, redesign DMA slightly

build.bat, mscompile.cmd
The code no longer compiles with VC2015 anyway.  You only actually need "4aa702d", but I'm a bit of a git neophyte.
=> Update mscompile.cmd to build with VC2019

pcsx2/DEV9/DEV9.cpp
Using the same code as 8bit reads/writes
This improves https://github.com/PCSX2/pcsx2/issues/3192, the online beta now sends a DHCP Discover packet, although it appears to invalid.
I wasn't able to figure out any further than that, but here is a PR regardless.
=> DEV9: Support 16bit reads/writes to SPD_R_PIO_DATA & SPD_R_PIO_DIR

pcsx2/gui/MainFrame.cpp
Blockdump gets a bit too much love which hampers with playing normally.
=> PCSX2-GUI: Move blockdump to game settings

bin/GameIndex.yaml
=> GameDB: Add korean Crash Bandicoot The Wrath of Cortex

pcsx2/CDVD/Windows/IOCtlSrc.cpp
Also added some extra messages if that fails (and not because it's a CD)
Fixes #4143
=> CDVD: Increase buffer for DVD_LAYER_DESCRIPTOR

bin/GameIndex.yaml
=> GameDB: VU0Kickstart for Spartan Total Warrior

pcsx2/gui/AppAccelerators.h, pcsx2/gui/GlobalCommands.cpp, pcsx2/gui/MainFrame.cpp, pcsx2/gui/MainFrame.h, pcsx2/gui/Panels/GSWindowPanel.cpp, pcsx2/gui/Panels/VideoPanel.cpp
This will add extra hotkeys to the GUI. You can look up https://wiki.pcsx2.net/Hotkeys for all of them (not everything is added from there)
Fixes #3212 (Doesn't allow mapping in GUI yet, only from ini at this moment)
#3631 is for another PR
#3214 setting to none may also be possible in future PR
=> GUI: Keyboard Shortcuts Strings

pcsx2/SPR.cpp
Fixes #4153
Also gets rid of the MFIFO spam in Hitman games
=> SPR: Wrap transfers which would have read outside of SPR memory

pcsx2/gui/MainFrame.cpp
=> GUI:fix capitalisation in GUI

bin/GameIndex.yaml
=> GameDB: various additions 

pcsx2/x86/R5900_Profiler.h
=> Fix compile of eeProfiler

bin/GameIndex.yaml
https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=609412#pid609412
I somehow forgot to add these from the forum. Whoops.
=> GameDB: Add missing Speed Kings patches

.github/ISSUE_TEMPLATE/feature_request.md
Exclude libretro feature requests.
=> misc: Update feature request template.

bin/GameIndex.yaml
corrects  SingStar R&B entry's
=> GameDB:corrects various singstar enteries 

pcsx2/SPU2/SndOut_SDL.cpp
buffer provided by the SDL callback.
I at least can't see a reason for it existing and it's working fine without it.
=> SPU2/SDL: Remove intermediate buffer and write samples directly to the

bin/GameIndex.yaml
adds "Tourist Trophy [Demo]" and "Gran Turismo 3 Trial Disk Volume 1" to GameDB
=> GameDB:adding various entries 

pcsx2/R3000AInterpreter.cpp
Added as a compile-time option, it's pretty friggin slow.
=> IOP: Execute breakpoints for the interpreter

bin/GameIndex.yaml
GameDB: Remove patches from LMA  manger 2003 and flipnic
=> GameDB: Remove patches from LMA  manger 2003 and flipnic

plugins/GSdx/Window/GSSetting.cpp, plugins/GSdx/Window/GSSetting.h
I didn't test the tooltips on #4188 (oops)
=> GSdx: Switch tooltips to unicode

pcsx2/IPC.cpp, pcsx2/IPC.h, pcsx2/gui/AppCoreThread.cpp, pcsx2/gui/AppCoreThread.h
https://github.com/PCSX2/pcsx2/pull/4262 needs to be merged first, a recent version of pcsx2_ipc needs to be used to get savestates support.
=> IPC: Add savestate support & more

pcsx2/IPU/IPU.cpp, pcsx2/IPU/IPU.h, pcsx2/IPU/IPUdma.cpp
Minor clean up of some IPU files
=> IPU: Remove useless define and includes/externs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md, README.md, pcsx2/Docs/Debugger.md, pcsx2/Docs/GameIndex.md, pcsx2/Docs/PCSX2_FAQ.md, pcsx2/Docs/README.md, pcsx2/USB/readerwriterqueue/LICENSE.md, pcsx2/USB/readerwriterqueue/README.md
Not the worst issues, we could still block the styling rules where it's complaining. Or just ignore specific/all issues on MD.
=> Misc: cleanup MD codacy issues

pcsx2/DEV9/Win32/pcap_io_win32.cpp, pcsx2/DebugTools/BiosDebugData.cpp, pcsx2/DebugTools/DisassemblyManager.cpp, pcsx2/DebugTools/DisassemblyManager.h, pcsx2/DebugTools/MipsAssembler.cpp
I also added a little dev9 fix.
=> Misc: Fix various DebugTools Codacy complaints

plugins/GSdx/GSState.cpp
Really tired of my debugger crashing due to known behavior.
=> gs: remove some pesky asserts

pcsx2/ps2/BiosTools.cpp
Also wrote a helpful (hopefully to others too) note
=> Misc: Support another bios for the debugger threadlist

plugins/GSdx/GSVector4.h
=> gsvector: fix forgotten elif during purge

bin/GameIndex.yaml
adds fixes for Energy Airforce - Aim Strike , K-1 World Grand Prix 2006  game fixes  into the  gameDB
would it be possible for people to test  if they have K1 World GP 2005 to see if it has some issues 
To update the GameDB  with gamefixs
=> GameDB:adds gamefixes for various games 

bin/GameIndex.yaml
=> GameDB:fix errors in GameDB

pcsx2/DEV9/ATA/ATA.h, pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp, pcsx2/DEV9/ATA/Commands/ATA_Command.cpp
Fixes https://github.com/PCSX2/pcsx2/issues/4358
=> DEV9: add ATA Idle Immediate (E1) stub

plugins/GSdx/Renderers/DX11/GSRendererDX11.cpp, plugins/GSdx/Renderers/HW/GSRendererHW.cpp, plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
Cleanup some minor annoyances.
const variables and some initializations.
=> GSdx-hw: Some minor cleanups

bin/GameIndex.yaml
=> GameDB:fix yaml error

.github/CONTRIBUTING.md
Fix typos and make PCSX2 forum link https.
See description.
Read it.
=> CONTRIBUTING.md: Typo fixes, https

pcsx2/USB/usb-eyetoy/cam-linux.cpp, pcsx2/USB/usb-eyetoy/cam-windows.cpp, pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
Don't start sending the same frame again, and send NAK instead until a new frame is available
Why were these changes made?  What problem does it solve / area does it improve?
#4239
#4239
=> Eyetoy: Apply first improvement for #4239

pcsx2/gui/MainFrame.cpp
change  'Console to Stdio' to 'Program Log to Stdio' in  UI
to keep naming conventions the inline  with #4377
compile the pull request on linux and look at the menu item
=> GUI: change  'Console to Stdio' to 'Program Log to Stdio' in UI 

pcsx2/USB/usb-eyetoy/cam-windows.cpp, pcsx2/USB/usb-eyetoy/cam-windows.h, pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
=> usb: Fix a few more warnings.

bin/GameIndex.yaml
remove 'OPHFLagHack' for "Naruto - Uzumaki Chronicles 2" entries  in  the GameDB
The gamefix isnt needed anymore 
Open the PR and look at the program log
=> GameDB- remove 'OPHFLagHack' for "Naruto - Uzumaki Chronicles 2"

.github/labeler.yml
Fixes auto pr labeler after gs merge for gs related stuff.
=> CI: Update pr labelers to match gs merge

.github/CONTRIBUTING.md, bin/PCSX2_keys.ini.default, cmake/SearchForStuff.cmake, linux_various/check_format.sh, linux_various/gen_gl_func_ptr.pl, linux_various/validate_glsl.sh, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/PAD/Windows/PAD.cpp, pcsx2/gui/AppMain.cpp
Update stuff to match recent gs merge.
Outdated.
=> misc: Update stuff to match recent gs merge

bin/docs/debugger.txt, pcsx2/gui/Debugger/DisassemblyDialog.cpp
A bit easier and nicer to look at but still needs some work.
Old:
New:
The help tab is abysmal to look at, and with Step Into + Step Over hotkey it's less to look up. Though there are still quite some hotkeys left todo.
Open the EE Debugger look at the buttons and click on the tab Help
=> Debugger-GUI: Resize help window + add 2 hotkeys

pcsx2/SPU2/Linux/Config.cpp, pcsx2/SPU2/Mixer.cpp, pcsx2/SPU2/SndOut_Portaudio.cpp, pcsx2/SPU2/SndOut_SDL.cpp, pcsx2/SPU2/Windows/Config.cpp, pcsx2/SPU2/Windows/SPU2.rc, pcsx2/SPU2/spu2.cpp, pcsx2/SPU2/wx/wxConfig.cpp, pcsx2/SPU2/wx/wxConfig.h
Cleanup some comments, clang format, change copyright date headers and add Gaussian in the comments it did list the other ones.
=> SPU2: Clean up + add Gaussian value in comment

bin/GameIndex.yaml
adds missing GameDB serials 
To have a more complete GameDB
open the  Pull request  and look at the program log to check for errors
=> GameDB: add missing serials

bin/GameIndex.yaml
Adds missing serials to gameDB
To have a more complete  GameDB
look at CI
=> GameDB: add missing serials to GameDB

bin/GameIndex.yaml
Adds a bunch of missing magazine demos.
Increasing entries
Run one or more of those demos if you own a copy.
=> GameDB: Official Playstation Demo serials

3rdparty/libsamplerate/libsamplerate.vcxproj
Cleans up the libsamplerate vs project
The old project was generated and difficult to read
Make sure chd still works I guess?
=> vs: clean up libsamplerate project

3rdparty/3rdparty.props, 3rdparty/baseclasses/baseclasses.vcxproj, 3rdparty/fmt/fmt.vcxproj, 3rdparty/freetype/builds/windows/freetype.vcxproj, 3rdparty/libchdr/libchdr.vcxproj, 3rdparty/libjpeg/libjpeg.vcxproj, 3rdparty/libpng/projects/vstudio/libpng/libpng.vcxproj, 3rdparty/portaudio/build/msvc/portaudio.vcxproj, 3rdparty/pthreads4w/build/pthreads4w.vcxproj, 3rdparty/soundtouch/SoundTouch.vcxproj, 3rdparty/wxwidgets3.0/build/msw/Common.props, 3rdparty/wxwidgets3.0/build/msw/wx30_adv.vcxproj, 3rdparty/wxwidgets3.0/build/msw/wx30_base.vcxproj, 3rdparty/wxwidgets3.0/build/msw/wx30_core.vcxproj, 3rdparty/xz/liblzma.vcxproj, 3rdparty/yaml-cpp/yaml.vcxproj, 3rdparty/zlib/zlib.vcxproj, common/build/Utilities/utilities.vcxproj, common/build/x86emitter/x86emitter.vcxproj, common/vsprops/IncrementalLinking.props
Clean up a number of vs project files that had been polluted with duplicate settings.
I want this to be cleaner
If it doesn't build it doesn't work
=> vs: properly disable gm and warnings

pcsx2/USB/usb-pad/usb-pad.cpp, pcsx2/USB/usb-pad/usb-pad.h
Build fix for master.
I guess this was added in between me making the PR and it getting merged.
=> USB: Freeze mode enum for keyboardmania

pcsx2/gui/MainFrame.cpp
Re-order config setting to older order.
Master:
PR:
Visual clarity between option and also muscle memory.
=> GUI: Re-order config settings

pcsx2/pcsx2.vcxproj, pcsx2/pcsx2.vcxproj.filters
Includes shaders in vs project.
=> vcxproj: Include shaders in vs project.

pcsx2/SPU2/Mixer.cpp
This optimization is disabled and not really safe. Lets just remove it
and clean up the function that uses it.
=> SPU: Remove NEVER_SKIP_VOICES

bin/GameIndex.yaml
GameDB: add 'XGKickHack' to Super Monkey Ball Adventure
Fixes #4624
look at  the CI
=> GameDB: add 'XGKickHack' to Super Monkey Ball Adventure

pcsx2/pcsx2.vcxproj.filters
Cleans up project, organizing gs files in solution explorer.
Easier to navigate, cleaner.
It can be better but it's a good start for now.
=> vcxproj: Cleanup file includes, makes the solution a bit more tidy.

pcsx2/x86/microVU_Compile.inl, pcsx2/x86/microVU_Misc.inl
=> microVU: Clean up a few warnings.

pcsx2/DebugTools/Debug.h, pcsx2/HwWrite.cpp, pcsx2/SourceLog.cpp, pcsx2/gui/ConsoleLogger.cpp, pcsx2/ps2/pgif.cpp
Adds the option to turn pgif logs on or off and adds extra missing error reports
pgif unrestrained tends to eat the console hiding any other useful output
play a game you know eats ass on pgif errors and try with it off
=> PGIF Logging

pcsx2/IopBios.cpp
This PRs just add the remove file functionallity over the IOPBIOS, sorry guys I forgot to create it.
Thanks!
=> HostFS: Add remove file functionality

.github/workflows/linux-workflow.yml, .github/workflows/macos-workflow.yml, pcsx2/GS/GSClut.h, tests/ctest/CMakeLists.txt, tests/ctest/GS/CMakeLists.txt, tests/ctest/GS/swizzle_test_main.cpp, tests/ctest/x86emitter/codegen_tests.cpp, tests/ctest/x86emitter/codegen_tests_main.cpp
Adds tests for GSdx block swizzle functions
Allows edits to be made to the functions without worrying about accidentally breaking games
Watch the CI test things for us
=> Add tests for GSdx block swizzle functions

bin/GameIndex.yaml
add 'EEtiming hack' to "Way of the Samurai &Sega Soccer Slam### Rationale behind Changes
look at the CI , test Way of the Samurai &Sega Soccer Slam to see if hack is applied correctly
=> GameDB: add 'EEtiming hack' to Way of the Samurai & Sega Soccer Slam

pcsx2/DebugTools/DisR5900asm.cpp
Changes are lazily done using Web-UI, so changes are untested and I don't plan to do any further work on it.
=> Misc:Debugger: Fix vmulai and vmaddai disassembly

common/src/x86emitter/CMakeLists.txt
clears some cmake warnings
cmake kept complaining about them
make sure everything builds
=> Clear some cmake warnings

bin/GameIndex.yaml
add 'EETimingHack' for Marvel Super Hero Squad and positive EE and VU rounding  forPac-Man Fever
Fixes #4653
check the  CI , try Pac-Man Fever
=> GameDB: add 'EETimingHack' for Marvel Super Hero Squad and positive EE and VU rounding  for Pac-Man Fever

pcsx2/Docs/GameIndex.md
Update/correct GameIndex.md
To have a more correct GameDB documentation 
none
=> Docs: correct GameIndex.md

3rdparty/include/ghc/filesystem.h
Make ghc act more like std::fs +  + consistency with C++17 and other fixes.
https://github.com/gulrak/filesystem/releases has some interesting fixes like issues with mounted folders and more wchar support.
Test with MacOS and see if everything works fine.
=> Dependencies: Update GHC 1.5.4 to 1.5.8

common/src/Utilities/Linux/LnxMisc.cpp
Adds Distro information to  the program log for linux 
Master:
PR:
It helps finding out what  distro a linux user is using if they need help with a particular issue 
run the PR or use the appimage on a linux OS , make sure i havent broken windows
=> add Linux distro information to program log 

pcsx2/GS/GSBlock.h, pcsx2/ps2/pgif.cpp, pcsx2/ps2/pgif.h
Cleans up compiler warnings on gcc/clang.
Cleans up compiler warnings on gcc/clang.
Compile using gcc/clang or see actions compile.
=> Misc: Warnings cleanup

bin/GameIndex.yaml
Fixes hangs in certain locations like building under construction.
Discord user report issue and tested itself.
Try PR with automatic settings for Powerpuff Girls Relish Rampage.
=> GameDB:Powerpuff Girls

bin/GameIndex.yaml
add'EE timing hack' to Spartan: Total Warrior
fixes a game issue  
look at the CI
=> GameDB: add 'EE timing hack' to Spartan: Total Warrior

pcsx2/GS/GSBlock.h, pcsx2/GS/GSCapture.cpp, pcsx2/GS/GSState.cpp, pcsx2/GS/GSVector4i.h
Cleanup remaining stuff from sse2/3 purge.
Cleanup remaining stuff from sse2/3 purge.
=> gs: Cleanup remaining stuff from sse2/3 purge.

pcsx2/GS/GS.cpp, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h
remove this stupid hack
I said I would remove it if people keep trying to use it and someone suggested I add it to the gui so I'm removing it instead.
don't test anything today, especially not my patience.
=> gs: purge clut reload before draw hack

pcsx2/GS/Window/GSSetting.cpp
update the tooltip not to reference DirectX
to make it  the tooltip  more correct ,  fixes #4705 
open/complie    the PR and read the tooltip
=> GS: update tooltip to remove refernce  to DirectX

bin/GameIndex.yaml
Fixes game pieces (positions) in the mini-game
The obvious reasons
Run the game on automatic settings and test the mini-game.
=> Gamedb:Kuon

pcsx2/x86/microVU.cpp, pcsx2/x86/microVU.h
Combine mVU0cacheReserve and mVU1cacheReserve
Cleaner, both use same value.
=> microVU: Combine mVU0cacheReserve and mVU1cacheReserve.

bin/GameIndex.yaml
add positive EE&VU rounding to Simple 2000 Series Vol.48
it needed to fix the game 
look at the CI
=> GameDB: add positive EE&VU rounding to Simple 2000 Series Vol.48

pcsx2/x86/microVU_Analyze.inl
This reverts commit 6800753f09f7302f4c8a846c2fe6d652af4fd907.
=> [MicroVU] Revert "bla"

bin/GameIndex.yaml
disables in InstantVU in the gameDB  for Dropship - United Peace Force
To make the game better 
look at the CI
=> GameDB:  Disable InstantVU for Dropship - United Peace Force

pcsx2/x86/microVU_Misc.h, pcsx2/x86/microVU_Misc.inl
Remove a disabled, and apparently broken speed hack
Absolutely none, I'm losing my mind
=> MicroVU: Purge Min/Max speed hack

common/IniInterface.h
=> Fix IniInterface warnings

pcsx2/x86/microVU.cpp, pcsx2/x86/microVU_Alloc.inl, pcsx2/x86/microVU_Analyze.inl, pcsx2/x86/microVU_Branch.inl, pcsx2/x86/microVU_Execute.inl, pcsx2/x86/microVU_Flags.inl, pcsx2/x86/microVU_Misc.inl
Removed some year old comments and commented out code.
Who doesn't like a cleaner code base.
It should work, I've only removed comments.
=> MicroVU: Cleanup stale comments and code

pcsx2/gui/Debugger/CtrlRegisterList.cpp
Fixed an msvc warning, added some curly brackets and formatted.
The code sucks currently (oops)
Test debugger register list
=> Debugger: CtrlRegisterList: Fix warning and screw up

common/Pcsx2Types.h, pcsx2/GS/GS.cpp, pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/SaveState.h, pcsx2/USB/USB.cpp, pcsx2/gui/Dialogs/GSDumpDialog.cpp, pcsx2/gui/GlobalCommands.cpp, pcsx2/gui/MainMenuClicks.cpp, pcsx2/gui/SysState.cpp
And fix up compiler errors caused by this.
Fixes #4716
=> Change s8 definition to be int8_t

bin/GameIndex.yaml
Changes to recent VU timings have upset the punisher, this will quench his issues with VUKickstart.
Unless you like SPS:
Or flying characters:
https://user-images.githubusercontent.com/24227051/133175563-157e9c76-a6a4-459d-82ae-27ff36d37753.mp4
Either use VuKickstart on latest dev or use this PR.
=> GameDB: Punisher

bin/GameIndex.yaml
adds 'VUKickstartHack'  to of path of neo
to fix the game 
try path of neo or check the CI
=> GameDB: add 'VUKickstartHack' to path of neo

bin/GameIndex.yaml
adds 'VUKickstartHack' to the Full Spectrum games
fixes games
look at CI
=> GameDB :add 'VUKickstartHack' to the Full Spectrum games

bin/GameIndex.yaml
fixes serial for 'Panzer Elite Action - Fields of Glory'
a more correct gameDB
look at CI
=> GameDB:fix serial for 'Panzer Elite Action - Fields of Glory'

.github/CONTRIBUTING.md
Correct spelling mistake in CONTRIBUTING.md
To ensure docs are correct
none
=> Docs: correct CONTRIBUTING.md

bin/GameIndex.yaml
adds  EE clamping to 'Max Payne 2 - The Fall of Max Payne'
Fixes the bullet holes in walls
look at CI
=> Gamedb: add EE clamping to 'Max Payne 2 - The Fall of Max Payne'

common/emitter/implement/movs.h, common/emitter/instructions.h, common/emitter/movs.cpp, common/emitter/x86emitter.cpp, pcsx2/x86/iCOP0.cpp, pcsx2/x86/iR5900.h, pcsx2/x86/ix86-32/iR5900-32.cpp, pcsx2/x86/ix86-32/iR5900Arit.cpp, pcsx2/x86/ix86-32/iR5900AritImm.cpp, pcsx2/x86/ix86-32/iR5900Branch.cpp, pcsx2/x86/ix86-32/iR5900LoadStore.cpp, pcsx2/x86/ix86-32/iR5900Move.cpp, pcsx2/x86/ix86-32/iR5900MultDiv.cpp, pcsx2/x86/ix86-32/iR5900Shift.cpp, pcsx2/x86/microVU_Macro.inl, tests/ctest/x86emitter/codegen_tests_main.cpp
Adds dedicated x64 implementations for things that can be done more easily on x64
Minor speed and code size improvements
Test x64 builds and make sure nothing broke
=> Use 64-bit operations on x64

bin/GameIndex.yaml
adds  'VUKickstartHack' to SOCOM II entries
fixes the said games 
look at CI
=> GameDB:add 'VUKickstartHack' to SOCOM II entries

pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
GSDevice : Cleanup a bit, use const when possible.
GSDeviceOGL: Use const, constexpr if possible, isolate m_debug_gl_file code in debug level only, shorten some functions and S-GSDevice11: Use const if possible, declare and initialize HRESULT at the same time when possible.
Cleaner code.
Test if renderers work properly, and it compiles.
=> GS: Cleanup GSDevice common, ogl, d3d11.

pcsx2/SPU2/spu2.cpp
fixes Wsign-compare warning
to have less warnings 
Compile or check CI on gcc.
=> SPU2:fix Wsign-compare warning

pcsx2/DEV9/Win32/tap-win32.cpp, pcsx2/DEV9/pcap_io.cpp
Add missing flag to GetAdaptersAddresses() call in pcap backend
Hopefully fixes https://github.com/PCSX2/pcsx2/issues/4828
Attempt to reproduce issue https://github.com/PCSX2/pcsx2/issues/4828, if connection succeeds then issue is fixed
=> DEV9: Auto Gateway Fix for winPcap backend

pcsx2/Pcsx2Config.cpp, pcsx2/gui/Panels/VideoPanel.cpp
Makes Synchronized MTGS' UI settings exclusive to  debug/devel  
Because it's slow and only required for debugging purposes anyways 
run  the GS panel in general settings both in release and debug
=> UI: Make ' Synchronized MTGS' UI settings exclusive to debug/devel

.github/workflows/macos-workflow.yml
Bump macos version to 11.
https://github.com/actions/virtual-environments/issues/4060
Make sure ci runs.
=> ci-mac: Bump macos version to 11.

common/SettingsWrapper.h, pcsx2/gui/AppConfig.cpp, pcsx2/gui/GlobalCommands.cpp, pcsx2/gui/wxSettingsInterface.cpp
Fixes the regression from the settings PR.
=> Wx: Fix GS hotkeys losing values after reboot

bin/GameIndex.yaml
add missing gamedb entry
a more complete 
look at CI
=> Gamedb :add 'SingStar ABBA' entry

bin/GameIndex.yaml
Adds clamping to Monster Rancher 3
fixes game 
check CI
=> GameDB :add VU clamping to Monster Rancher 3

cmake/SearchForStuff.cmake, common/General.h, common/Linux/LnxMisc.cpp, pcsx2/CMakeLists.txt, pcsx2/DEV9/DEV9.cpp, pcsx2/DEV9/DEV9Config.cpp, pcsx2/DEV9/InternalServers/DHCP_Server.cpp, pcsx2/DEV9/InternalServers/DNS_Server.cpp, pcsx2/DEV9/Linux/Config.cpp, pcsx2/Recording/NewRecordingFrame.cpp, pcsx2/SPU2/SndOut_SDL.cpp, pcsx2/SPU2/spu2.cpp, pcsx2/SPU2/wx/wxConfig.cpp
make freebsd compile again
I want to put it on CI and tellow wants to fix the recs
if it builds it builds
=> FreeBSD fixup

bin/GameIndex.yaml
adds missing GameSB entry 
a more complete GameDB 
look at CI
=> GameDB :add missing entry

bin/GameIndex.yaml
:bow:  Gomenasai ore-tachi no Nipponjin. Typo fixes from across all regions, especially japanese side.
General clean-up and to be more accurate.
Check the serials with redump.
=> Gamedb: Typo Cleanup

.github/workflows/scripts/linux/appimage.sh, .github/workflows/scripts/linux/generate-cmake.sh, .github/workflows/scripts/linux/install-packages.sh
Cleans up unneeded dependencies on the Linux CI
Faster builds, less messy looking dependency list
Make sure appimage builds still run
=> Clean up Linux CI dependencies

bin/GameIndex.yaml
We like higher GameDB numbers
I noticed we had a ton of missing SingStar serial + minor other fixes.
Run SingStar games and look on the program log if it says a name and if it is , is it correct.
=> GameDB: Add and fix SingStar Entries

bin/GameIndex.yaml
I added missing entries and fixed some entries with consistent title name.
It makes GameDB better.
Check if nothing is broken.
=> GameDB: Add and fix Power Pros series

pcsx2/GS/Renderers/OpenGL/GLLoader.cpp, pcsx2/GS/Renderers/OpenGL/GLLoader.h
GPU and driver info is already handled elsewhere, this just duplicates the info.
Cleanup some useless code.
Duplicate code, cleaner.
Make sure gl still works, logs are proper with gpu/driver info.
=> GS-ogl: Remove device, driver checks in GLLoader.

bin/GameIndex.yaml
add nearest rounding to 'Hitman - Contracts' and add various correction to the Gamedb 
fixes said game and fixed some errors in the Gamedb 
look at CI
=> GameDB: add nearest rounding to 'Hitman - Contracts' and various fixes 

bin/GameIndex.yaml
Adds GIFFIFOHack' to 'Gunfighter 2 - Legend of Jesse James'
look at CI and test said game
=> GameDB:add 'GIFFIFOHack' to 'Gunfighter 2 - Legend of Jesse James'

bin/GameIndex.yaml
Adds Vu clamping and ee rounding to games that need them 
Fixes  #4959
look at the  CI and check said games
=> GameDB: add  ee-rounding and vu-rounding to various entries

pcsx2/Docs/PCSX2_FAQ.md
General editing, cleanup and updates to the FAQ.
Some information in the FAQ was incorrect or out of date, and the document felt like it could be polished up a bit.
Reading the document.
=> Update the FAQ, as well as some general cleanup.

bin/GameIndex.yaml
Adds various patches which fixes games 
fixes said games 
look at the  CI and test said games
=> Gamedb : add various fixes for various games and remove not needed patches 

pcsx2/GS/GSState.cpp
Reimplement the Texture Min Max optimisation to reduce texture sizes read
Original code was slightly janky and didn't cover all scenarios, but it also didn't deal with erroneous situations, this should address that.
Test games, make sure no textures are corrupted, see if the performance is any better. Chronicles of Narnia, Test Drive Unlimited, Kaan are games known to be affected.
Note: The Test Drive Unlimited dump has a black bit on the road in the distance, I believe this is correct, the PS2 does this with distant road, but it is the correct colour.
=> GS: Redo the Texture min/max opt

pcsx2/x86/microVU_Compile.inl
Preserve XGKick cycles calculated when there is a memory write in a delay slot, also added handling for xgkick sync on single instructions
Previously there was no handling on single instructions (evil blocks) so that's sorted. The other problem was if there was a mem write in a branch delay slot, it would add the xgkick cycles it needed to run, then erase them! causing the sync to go out, this resolves it.
Try games with XGKick sync enabled, especially ones which require it in the gamedb.
Fixes #5047
=> microVU: Preserve XGKIck cycles in delay slot

bin/GameIndex.yaml
add 'GIFFIFOHack' to 'FIFA 2005
The hack helps the game 
look at CI
=> Gamedb : ADD fixes for various games 

bin/GameIndex.yaml
removed the patch for Virtua Fighter 4
its not needed anymore
Check CI
=> Gamedb: remove the patch for Virtua Fighter 4

bin/GameIndex.yaml
purge patches for 'Knockout Kings 2002'
their not needed
look at the CI
=> GameDB: purge patches for 'Knockout Kings 2002'

bin/GameIndex.yaml
fix Fuuraiki 2 patch
i made a mistake >.>
look at CI
=> GameDB : fix Fuuraiki 2 patch

README.md
update link on readme 
look at the changed link
=> Readme : update links

bin/GameIndex.yaml
adds 'EETimingHack' to 'Shadow Man - 2econd Coming'
fixes issues 
look at CI test said game
=> GameDB: Add fixes for 'Shadow Man - 2econd Coming' and 'Ghosthunter' games.

bin/GameIndex.yaml
Adds VIFFIFOHack to Men in Black II: Alien Escape
look at the CI / check the game
=> Gamedb: add 'VIFFIFOHack' to 'Men in Black II: Alien Escape'

bin/GameIndex.yaml
add 'VUKickstartHack' to 'Crash Twinsanity'
look at CI/ check said game
=> GameDB: add 'VUKickstartHack' to 'Crash Twinsanity'

bin/GameIndex.yaml
add EEclamping full to 'Shinobido Takumi'
stop it  crashing after main menu 
make sure CI completes /check the game
=> GameDB:add EEclamping full to 'Shinobido Takumi'

bin/GameIndex.yaml
add VU clamping to 'MVP Baseball 2003'
Fixes #5113 
check said game / check CI
=> GameDB: add VU clamping to 'MVP Baseball 2003'

pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h, pcsx2/GS/Renderers/OpenGL/GSRendererOGL.cpp, pcsx2/GS/res/glsl/common_header.glsl
Couple MaxDepthPS with TA and Af vector.
Vectors are free so let's use them.
Optimization.
Test opengl hw, make sure nothing broke.
=> GS-ogl: Optimize fragment shader uniform buffer.

bin/resources/GameIndex.yaml
add EE timinghack to 'MGS2' and change VU and EE rounding for 'Primal' and adding some missing entries 
makes said games work better 
Check the CI /test said games
=> Gamedb: add EEtiminghack to 'MGS2' and change VU and EE rounding for 'Primal' and add missing entries 

bin/resources/GameIndex.yaml
adds patches to the 'Netsu Chu!' series of titles and the 'Samurai 7' series
it fixes said games 
fixes #5144 
look at CI/ check said games
=> GameDB: add patches to the 'Netsu Chu!' series and  'Samurai 7' series

bin/resources/GameIndex.yaml
add EE clamping to 'Chou Saisoku! Zokusha King B.U.'
look at CI /test game
=> Gamdb:add EE clamping to 'Chou Saisoku! Zokusha King B.U.'

bin/resources/GameIndex.yaml
add EEclamping to 'Dark cloud 2'
fixes an issue with the game 
look at CI / text the game
=> Gamedb: add EEclamping to 'Dark cloud 2'

bin/resources/GameIndex.yaml
I forgot this one.
Check if nothing is broken.
=> Add "Jikkyou Powerful Pro Yakyuu 2009" to GameDB

bin/resources/GameIndex.yaml
add patches to various 2k games 
fixes said games 
look at CI/ test said games
=> Gamedb: add patches to 2k games

bin/resources/GameIndex.yaml
adds more patches to 2k games 
fixes the said games 
look at CI/try said games
=> Gamedb: add more 2k games patches

bin/resources/GameIndex.yaml
add gamefixes to 'Titeuf Mega-compet' and patch 'Yamiyo ni Sasayaku - Tantei Sagara Kyouichirou' series
fixes #5171 
fixes #5167 
look at CI /test said game
=> Gamedb add gamefixes to 'Titeuf Mega-compet' and patch 'Yamiyo ni Sasayaku - Tantei Sagara Kyouichirou' series

bin/resources/GameIndex.yaml
Gamdb: add eeclamping to 'Digimon Battle Chronicle' and fixes to other games
Fixes #5175 
look at CI /test said game
=> GameDB: Add EE Clamping to 'Digimon Battle Chronicle' and fixes to other games

bin/resources/GameIndex.yaml
GameDB: change VUclamping on "Sled Storm"
a more appropriate fix 
look at CI/ check said game
=> GameDB: change VUclamping on "Sled Storm"

pcsx2/GS/Renderers/Null/GSRendererNull.cpp, pcsx2/GS/Renderers/Null/GSRendererNull.h, pcsx2/GS/Renderers/Null/GSTextureNull.h, pcsx2/GS/Renderers/OpenGL/GSTextureOGL.h, pcsx2/GS/Renderers/SW/GSTextureSW.h
Warning cleanup.
Not really needed, it won't break anything.
=> GS: Add missing override specifier to a few files

.github/workflows/scripts/linux/AppRun, .github/workflows/scripts/linux/app-variables.sh, .github/workflows/scripts/linux/appimage.sh
Fixes change to Appimage, requiring second boot to use the custom config file folder.
fix a feature that changed
=> Create AppRun hook to handle variables

pcsx2/GS/GSState.cpp
Fix -Wreorder warning.
Begone warning.
See if warning is gone on gcc CI.
=> GS: Try to fix -Wreorder warning.

.github/workflows/update-controller-db.yml
Fixes the game controller db updater
Last scheduled controller db update failed (https://github.com/PCSX2/pcsx2/runs/4643371117)
Merge and wait a week?
=> GHActions: Fix game controller db updater

bin/resources/GameIndex.yaml
remove patches for  'Neo Contra' and adds EE rounding and claming
The patches  arent needed any more and the issue can be fixed with EE clamping and rounding 
look at CI / make sure the game works as intended
=> GameDB: remove patches for  'Neo Contra' and add EE rounding and clamping

pcsx2/gui/FrameForGS.cpp
Should not be seen anymore
Useless message when the behavior has been changed
Run game and see if you see it somewhere around here:
=> ProgramLog: Comment out deleted keymapping

3rdparty/include/vk_mem_alloc.h
=> 3rdparty: Add Vulkan Memory Allocator

3rdparty/include/xxhash.h
=> 3rdparty: Add xxhash.h

pcsx2/vtlb.cpp
Makes ppmap allocation accessible from 64-bit JIT
Fixes goemon on 64-bit
Test goemon
=> VTLB: Fix ppmap allocation in 64-bit

pcsx2/IPU/IPU.cpp
See title.
Make it work as you expect.
=> IPU: Fix software renderer FMV hack without AR change

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
Intel and Nvidia don't need it, get rid of it for them.
So intel and nvidia don't suffer.
Check if point sampler still works on amd.
=> GS-d3d11: Enable amd broken point sampler hack only for amd.

pcsx2/pcsx2.vcxproj, pcsx2/pcsx2.vcxproj.filters
vcxproj: Add vulkan shaders and group shaders in renderer category.
Cleaner.
Make sure it still builds in vs.
=> vcxproj: Add vulkan shaders and group shaders in renderer category.

bin/resources/GameIndex.yaml
Adds  missing serials to gameDB
a more complete gameDB
=> GameDB: add some missing serials

bin/resources/GameIndex.yaml
correct some serials 
mistakes were made
make sure things are correct
=> GameDB: fix  some entries

bin/resources/shaders/dx11/convert.fx, bin/resources/shaders/dx11/merge.fx, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/SW/GSRendererSW.cpp, pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp, pcsx2/GS/Renderers/Vulkan/GSTextureVK.h
This was missing before, and is needed now since we default to DX11 SW on Windows.
Test games which uses it. I've checked the Xenosaga dream sequence gs dump.
=> GS/DX11: Implement merge feedback write

bin/resources/GameIndex.yaml
adds game fix to Cocoto Funfair
check CI  
@gilderoylockhart01 can you make sure this is fine :)
=> Gamedb: add gamefix to  Cocoto Funfair

pcsx2/GS/Renderers/HW/GSRendererNew.cpp, pcsx2/GS/Renderers/HW/GSRendererNew.h
DATE_GL42 -> DATE_PRIMID
DATE_GL45 -> DATE_BARRIER
Consistency between renderers.
Make sure nothing broke.
=> GS-hw: Rename DATE_GL42 DATE_GL45.

bin/resources/GameIndex.yaml
adds a patch to MX Unleashed Migrated and missing serial s
look at CI/ check said game
=> GameDB: add patch to MX Unleashed Migrated and missing serials 

bin/resources/GameIndex.yaml
add EETiming to Kya: Dark Lineage to fix smoke effects 
fixes said effects 
test the said game / look at CI
=> GameDB:  add EETiming to 'Kya: Dark Lineage'

bin/resources/GameIndex.yaml
adds VUKickstartHack to Ghosthunter
look at CI /check the  game
=> GameDB: add VUKickstartHack to Ghosthunter

pcsx2/GS/Renderers/Common/GSRenderer.cpp
Fixes The Suffering video monitors "bouncing" up and down
Code accuracy (hopefully) :P
Test all games, look for visual artifacts and regressions
=> GS: Don't apply offset when using SLBG

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Optimize xxHash usage in palette hashing as suggested by @stenzek.
Optimization.
I guess code review is enough here.
=> GS: optimize xxHash usage in palette hashing.

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
=> GS/Vulkan: Fix combining DATE/barriers with HDR

bin/resources/GameIndex.yaml
adds SkipMPEGHack to  David Beckham Soccer
fixes #5357
look at the CI /check said game
=> GameDB: add 'SkipMPEGHack'  to "David Beckham Soccer"

bin/resources/GameIndex.yaml
adds fixes for Simple Series vol.7 , Petz - Horsez 2 
Fixes #5319
make sure said games are correct / look at CI
=> GameDB: add fixes for Simple Series vol.7 and other games

pcsx2/GS/GSState.cpp
Fix clamping alpha blending factors
Previous code had a typo and accidentally did nothing
Off by one errors are fun
[Test this GSdump](https://cdn.discordapp.com/attachments/612095738712817665/934263303969067018/RC_Blarg_death_particles.gs.xz)
=> GS: Fix alpha blend factor clamping

bin/resources/GameIndex.yaml
adds EETimingHack to  Indiana Jones and the Emperor's Tomb 
fixes issue the games(s) had
check CI / check said game(s)
=> GameDB: add 'EETimingHack' to 'Indiana Jones and the Emperor's Tomb'

.github/workflows/windows-workflow.yml
So I stop being a derp and pushing changes which don't compile.
=> CI: Build Qt binaries on Windows

bin/resources/GameIndex.yaml
add eerounding to 'Neopets - The Darkest Faerie'
fixes issues with the game 
check CI /check said game
=> GameDB: add eerounding to 'Neopets - The Darkest Faerie'

pcsx2/MemoryCardFolder.cpp
Someone reported issues in GTA, i looked into it and found some bugs that were not caught during the migration to rapidyaml.  I believe they didn't come up because not all games care about the index file.
- the index file would not be initially created properly
- the index file wouldn't get updated properly when saving to slots
In the old file, `%ROOT` was used to keep track of metadata about the entire folder memory card, unfortunately rapidyaml has a small bug I'll need to upstream and it does not quote this key. `%` is a directive in YAML which are non-data args for the yaml processor, so the line gets discarded, screwing up the assumed syntax.
- to fix this in the meantime (but i see no reason it can't remain) -- I switched to `$ROOT`
Also if the yaml file failed to parse, it would be …
=> memcard: Fix folder memory card regressions

README.md
add note about Vulkan drivers to the readme 
read said note / check for grammar/punctuation errors
=> Readme: add note about Vulkan drivers

pcsx2-qt/EmuThread.cpp, pcsx2-qt/EmuThread.h, pcsx2-qt/QtUtils.cpp, pcsx2-qt/QtUtils.h, pcsx2/VMManager.cpp, pcsx2/VMManager.h
=> Qt: Add save state loading/loaded/saved events

.github/labeler.yml
This will label PRs that touches upon Qt-related files.
Easier tracking and keep it organised
Any rebase or new PR changing Qt-related files should be labeled by the bot
=> CI: Automatically label Qt

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
Regression from channel shuffle stuff, fixes Mercenaries with ultra blending.
=> GS/DX11: Fix binding depth as tex + fbmask

bin/resources/GameIndex.yaml
Adding missing entries so that Ziemas can be happy.
More entries, the merrier
Launch game and see if it gives correct name.
=> GameDB: Beatmania entries

pcsx2/GS/Renderers/HW/GSRendererNew.cpp
GS-hw: Properly enable/disable each channel based on fbmask, adjust fbmask detection when to do blending for 16bit/24bit.
More optimizations.
Test basic blending on gl/vk, medium on d3d11.
=> GS-hw: Properly enable/disable each channel based on fbmask, adjust fbmask detection when to do blending for 16bit/24bit.

bin/resources/GameIndex.yaml, pcsx2/GS/GSCrc.cpp
Add to GameDB and GSCrc.
It is same content as SCPS-17001.
=> Gran Turismo 4 [PlayStation 2 Racing Pack]

common/Vulkan/Context.cpp, common/Vulkan/Context.h, common/Vulkan/SwapChain.cpp, common/Vulkan/SwapChain.h, common/Vulkan/Util.cpp, common/Vulkan/Util.h, pcsx2-qt/MainWindow.cpp, pcsx2/Frontend/D3D11HostDisplay.cpp, pcsx2/Frontend/D3D11HostDisplay.h, pcsx2/Frontend/OpenGLHostDisplay.cpp, pcsx2/Frontend/OpenGLHostDisplay.h, pcsx2/Frontend/VulkanHostDisplay.cpp, pcsx2/Frontend/VulkanHostDisplay.h, pcsx2/HostDisplay.h, pcsx2/Pcsx2Config.cpp, pcsx2/System/SysCoreThread.cpp, pcsx2/gui/AppHost.cpp
Vsync was flaky since the frontend/host display refactoring (my fault). This fixes it and makes it reliable again.
Also adds adaptive vsync (FIFO_RELAXED) for Vulkan.
Fixing my bugs.
Make sure vsync works as expected now.
=> Fix some vsync related issues, implement Vulkan adaptive vsync

bin/resources/GameIndex.yaml
disabled mVUFlagHack for Maken Shao
Fixes said games 
make sure CI passes and the game is fixed
=> GameDB: disable mVUFlagHack for Maken Shao

bin/resources/GameIndex.yaml
adds EETimingHack to Obscure 2 and a patch to 'Snoopy Vs Red Baron'
fixes said game (s)
look at CI / make sure the works as intended
=> Gamedb: add EETimingHack to 'Obscure 2' and patch to 'Snoopy Vs Red Baron'

bin/resources/GameIndex.yaml
add VUKickstartHack to Jet Li - Rise to Honor
make sure CI is ok / test said game
=> Gamedb: add 'VUKickstartHack' to 'Jet Li - Rise to Honor'

pcsx2/HwRead.cpp, pcsx2/HwWrite.cpp
removes logging thats not needed anymore 
look at CI / build pcsx2
=> Core: remove not needed logging

pcsx2-qt/Settings/GraphicsSettingsWidget.ui
typo
typo
one character in a string affects nothing
=> Qt: Fix type on graphics panel

common/Vulkan/SwapChain.cpp
Makes Vulkan initialize properly on macOS+wx
Nice to not have a black screen
Test Vulkan renderer on macOS
=> GS:Mac: Fix Vulkan init

bin/resources/GameIndex.yaml
add a COP2 Rearrangement patch for Cars  
check CI/game
=> Gamedb: add patch for Cars

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererNew.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fix warnings.
Warnings.
Compiles, warnings are fixed.
=> GS-hw: Fix some warnings.

pcsx2/GS/Renderers/HW/GSRendererNew.cpp
[GS-hw: Optimize blending when ALPHA.A is equal to ALPHA.B.]
Set ALPHA A B to 0 (Cs), and ALPHA.C to 0 (As).
Optimization.
Make sure blending still works as expected.
=> GS-hw: Optimize blending when ALPHA.A is equal to ALPHA.B.

bin/resources/GameIndex.yaml
Gamedb: add VU clamping to 'DT Racer' and update MGS2 hack
fix said game(s)
check said games / look at CI
=> Gamedb: add VU clamping to 'DT Racer' and update MGS2 hack

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
I've been meaning to do this for a while, but kept forgetting. GS-HW doesn't provide a depth texture to the backend when depth testing is effectively disabled, which causes unnecessary render pass restarts for Vulkan. Originally I was going to change the base hw renderer, but Tellow's Metal renderer just does it in the device instead, which is safer.
I still think it may be worth doing it in the base class at some point, as that would avoid the restart when the first draw has no depth, but subsequent draws do. However, if the subsequent draws didn't, we'd waste memory on an unnecessary buffer allocation (and clear+store).
Brr.
Test Vulkan renderer across a range of games, look for any performance difference (probably near none). Burnout 3 is a good test case for render pass spam.
=> GS/Vulkan: Elide render pass restarts on depth buffer toggle

pcsx2/GS/GSState.cpp
Fix up behaviour of MTBA (Automatic Mipmap addressing) based on the results of PS2 hardware tests.
The behaviour was pretty much wrong and misunderstood.
Test games make sure there's no new Mipmapping garbage in the distance or anything.
Note: Parappa The Rapper 2 might have a glitch in hardware mode, the mipmaps aren't handled properly so it shows a horrible white poly in the corners instead of blending, software mode looks perfectly correct.
Fixes Cartoon Network Racing properly (before we just skipped the mipmapping, you will unlikely notice any difference)
=> GS: Improvements to MTBA Mip Mapping

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h
Fix for linux
Linux doesn't like things sometimes for dumb reasons
wait for CI
Fixes #5637
=> GS-Build: Fix Dump Verticles for linux

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Loosens requirement to enable half bottom
I broke Jak 3 :(
Test games listed in #5628 make sure they all still work
=> GS: Loosen requirement for half bottom

bin/resources/GameIndex.yaml
correct and update serials
a more correct GameDB
look at CI
=> GameDB: correct and update serials

bin/resources/GameIndex.yaml
Adds half roundsprite to make upscaled HW more like software mode such as minimap while fighting.
Accuracy in visuals
Play any Rogue Galaxy variant.
=> GameDB: Rogue Galaxy

pcsx2/GS/Renderers/HW/GSRendererNew.cpp
Gs-hw: Optimize blending equations based on alpha value.
It will allow us to use free sw blending without texture barriers.
Will be especially helpful for opengl/vulkan.
Optimization, brr.
Test blending, opengl/vulkan should see a speed bump.
=> GS-hw: Optimize blending equations based on alpha value.

pcsx2/GS/GSLzma.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
GS: Fix Wunused-variable warnings.
Warnings.
It compiles, warnings are gone from compilers.
=> GS: Fix Wunused-variable warnings.

bin/resources/GameIndex.yaml
Some extra comments for Monster Lab and SSX Tricky.
New entries:
- Alter Echo
- Beyond Good and Evil
- Dragon Ball Z - Budokai Tenkaichi 2
- Fatal Frame 1 / 3
- Ghost in the Shell - Stand Alone Complex
- Global Defence Force
- Xenosaga 1 / 2 / 3
Less tinkering
Nobody will test this.
=> GameDB: More GS HW Fixes

bin/resources/GameIndex.yaml
Co-Authored-By: RedDevilus <martensregis@gmail.com>
add hardware fix for lines going down the screen in Tales of Symphonia
tell configuring for end user
try game
=> GameDB: Add gsHWFixes for Tales of Symphonia

bin/resources/GameIndex.yaml
Ranging from blurriness to font artifacts.
- 50cent - Bulletproof
- Dark Cloud 1 / 2
- Haunting Ground
- Rogue Galaxy
- Tomb Raider - Legend
Test the relevant games.
=> GameDB: Haunting Ground + 50 Cent and Level 5

pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
Fixes LOD on x64 sw renderer
Fixes #5025
Nice to have things working
Test things mentioned in #5025
=> GS:SW: Fix LOD on x64

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.ui
Some missing strings from the renaming.
Consistency is key
/
=> Qt: Partial Invalidation

bin/resources/GameIndex.yaml
Gamedb: remove  no longer needed comments
the comments were no longer needed 
look at CI
=> Gamedb: remove  no longer needed comments

pcsx2/Hw.h, pcsx2/VUops.h, pcsx2/x86/iR5900.h, pcsx2/x86/ix86-32/iR5900-32.cpp, pcsx2/x86/microVU_Macro.inl
Removes some code that is no longer necessary
Cleaner code
Make sure nothing is broken ;)
=> Core: Remove unused code

.github/labeler.yml
No more manual adding GUI/WX
Less manual editing
Change relevant files
=> CI: Update labeler to expand WX

bin/resources/GameIndex.yaml
Affects:
- Ape Escape 3
- Armored Core Last Raven
- Berserk
- Forever Kingdom
- Front Mission 4 / 5
- Need For Speed Underground 1 / 2
- Kings Field 4 - The Ancient City
- Test Drive Unlimited
- Jak 2 / 3 / X
Test the relevant games.
=> GameDB: Even more GS HW Fixes

bin/resources/GameIndex.yaml
adds 'VUSyncHack' to Panzer Elite Action - Fields of Glory
Helps fix SPS still needs EE+3
look at CI
=> GameDB: adds 'VUSyncHack' to Panzer Elite Action - Fields of Glory

pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/HW/GSRendererNew.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
Invert a check that was accidentally not inverted
Make things less broken (and not spam you with warnings about pipelines failing to compile)
Test games that broke in the recent fbfetch changes
=> GS: Fix inverted dsb check

bin/resources/GameIndex.yaml
Relevant:
- Bully
- Colosseum - Road to Freedom
- Dark Chronicle (Dark Cloud 2)
- Killzone	
- God of War
- Gun
- Midnight Club 3	
- Mortal Kombat - Deadly Alliance
- Need for Speed Carbon / Most Wanted / Undercover
- Prince of Persia - Sand of Time / The Two Thrones / Warrior Within
- Resident Evil 4 (BioHazard 4)
- Thrillville / Off the Rails
=> GameDB: GS HW Batch X

bin/resources/GameIndex.yaml
Special texture to:
- Midnight club 3
- Evangelion - Jo
Test the relevant games.
=> GameDB: Fix Midnightclub 3 + Add Evangelion Jo

pcsx2-qt/EmuThread.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.ui, pcsx2-qt/QtHost.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
=> Qt: Misc fixes

bin/resources/GameIndex.yaml
fixes SLES-54453 title 
look at CI
=> Gamedb: Fix 'SLES-54453' title

bin/resources/GameIndex.yaml
Megaman X - Command Mission flickering FMV fix and fix for the lighting in the game Nicktoons Unite!
=> GameDB: Megaman + Nicktoons

README.md, pcsx2/Docs/PCSX2_FAQ.md, pcsx2/gui/MainMenuClicks.cpp
Updates  compatibility URLs in GUI/Docs
Fixes #5734
make sure links work
=> GUI/Docs : update compatibility URLs

pcsx2-qt/EmuThread.cpp, pcsx2-qt/EmuThread.h, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2/GSDumpReplayer.cpp, pcsx2/GSDumpReplayer.h, pcsx2/PAD/Host/PAD.cpp, pcsx2/VMManager.cpp
What the title says. GS dumps won't confirm shutdown, or require bios.
Errors are better than crashing.
qt yolo
=> Qt: Implement BIOS check and shutdown hotkey

bin/resources/GameIndex.yaml
various game improvements
look at CI
=> GameDB : various game improvements

build.sh
Removed the flags on build.sh to cross compile and to build natively.
As 32 bit builds have been dropped, these flags are not needed.
Make sure it still builds.
=> Build: Remove cross compiling from build.sh.

bin/resources/GameIndex.yaml
=> GameDB: Add Zwei AutoFix

bin/resources/GameIndex.yaml
Reduces ghosting but on normal vertex causes the rainbow corruption at the screen sides
Less tinkering
Test Narnia - Prince Caspian.
=> GameDB: Caspian

pcsx2/GS/GS.cpp, pcsx2/GS/Renderers/Common/GSRenderer.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/Pcsx2Config.cpp
GS-hw: Purge custom resolution entirely.
Code debt, not used anymore, get rid of it.
Custom resolution is not used anymore, get rid of it.
Make sure upscale multiplier still works.
=> GS-hw: Purge custom resolution entirely.

pcsx2/ps2/BiosTools.cpp
Easy one. Strings in the BIOS loader weren't bounds checked, resulting in crashes if corrupted BIOS dumps were loaded.
Crash bad, even if the user is silly and didn't check the hash of their dump before using it.
Make sure BIOS loading works as expected (and expansion ROMs).
=> BiosTools: Bounds check strings in LoadBiosVersion()

bin/resources/GameIndex.yaml
Fixes the blurry characters in Metal Gear Solid 3
=> GameDB: Metal Gear Solid 3 PAL - Fix blurry characters

bin/resources/GameIndex.yaml
Corrects title errors and adds missing entries.
They were incorrect or missing. Titles chosen are from the general consensus on the internet (or people who speak Japanese)
Look at it and make sure it's good.
=> GameDB: Update Simple Series entries

bin/resources/GameIndex.yaml
add missing Gamdb serials
a more complete GameDB 
look at CI
=> Gamedb: fix missing serials

bin/resources/GameIndex.yaml
Align sprite for water vertical lines.
The GameDB changes were reverted but then the CRC hacks were removed so this fixes it.
Test God Of War games
=> GameDB: God Of War 1 / 2

bin/resources/GameIndex.yaml
Gamedb: add 'VUSyncHack' to 'Next Generation Tennis 2003'
check the game/look at CI
=> Gamedb: add 'VUSyncHack' to 'Next Generation Tennis 2003'

bin/resources/GameIndex.yaml
Fixes Ar Tonelico II and adds comments for Legion - The Legend of Excalibur
=> GameDB: Fix name + add comment

pcsx2/GS/GS.cpp
GS: Remove unused default configs.
Cleanup.
Make sure they really aren't used anywhere.
=> GS: Remove unused default configs.

bin/resources/GameIndex.yaml
=> GameDB: add missing serials 

common/GL/ContextEGL.cpp
* Manipulation of array indexes to assign data, changed to be more standardised and to strengthen `const`ness.
* Method to locate particular `EGLConfig`-data, changed to be more C++ standardised.
* Standardisation, to use more C++ standard algorithms and IIFE (Immediately invoked function expressions).
* This makes the source-code easier-to-read, as it is using common-abstracted C++ concepts.
* Much reduced code-size to maintain.
* Stronger `const`-correctness.
* CI should pass and build with no problems.
* _Structurally, nothing has changed, only replaced previous code with refactored C++ common algorithm code._
---
_P.S. This is a great project! :smile_cat: Thank you for all your work so far! :tada:_
=> Common: Removed array-index manipulation logic for more standardised abstractions

bin/resources/GameIndex.yaml
Adds a bunch of gamefixes and upscaling fixes to games as well as just entries.
- 0 Story
- Amagami
- Bleach Blade Battlers 2nd
- Chobits
- D.C. Da Capo The Origin
- Pandora - Kimi no Namae o Boku wa Shiru
- Katekyoo Hitman Reborn! Nerae!? Ring x Vongola Trainers
- Kateikyoushi Hitman Reborn!! Let's Ansatsu! Nerawareta 10 Daime!
- Kino no Tabi - The Beautiful World
- Kyuuketsu-hime Yui - Sen'yashou
- Shikigami no Shiro - Nanayozuki Gensoukyoku
- Secret of Evangelion
Pictures:
Amagami;
Before:
After:
Bleach Blade Battlers 2nd;
Before:
After:
Chobits;
Before:
After:
DC Da Capo Origin;
Before:
After:
Kateikyoushi Hitman Reborn!! Let's Ansatsu! Nerawareta 10 Daime!;
Before:
After:
Katekyoo Hitman;
Before:
After:
Kino no Tabi - The Beautiful World;
Before:
After:
Less tinkering
Test relevant …
=> GameDB: Japanese entries Batch 1

pcsx2/Patch.cpp, pcsx2/gui/AppCoreThread.cpp
=> Wx: Fix widescreen patch loading

pcsx2/GS/GS.cpp, pcsx2/GS/Renderers/Common/GSRenderer.cpp
Interlacing to Deinterlacing
Oversight in having the correct config for the ini.
Test games in different modes from the GUI and cycle with F5.
=> PCSX2: Fix Interlacing Ini

bin/resources/GameIndex.yaml, pcsx2/GS/GS.cpp
GameDB Black roundsprite to half for lighting + minor cleanup variable
Less tinkering
Test black
=> GameDB: Black + minor cleanup

pcsx2/GS/Renderers/Common/GSRenderer.cpp
Fixes BFF deinterlacing behaviour
It got broke in #5810 because I made it go negative, like a FOOL
test different interlacing modes, make sure you don't just get black screens.
=> GS: Fix undefined behaviour on interlacing

pcsx2/GS/GSLzma.cpp, pcsx2/GS/GSLzma.h, pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp, pcsx2/SPU2/Dma.cpp, pcsx2/SPU2/ReadInput.cpp, pcsx2/SPU2/defs.h, pcsx2/SPU2/spu2freeze.cpp, pcsx2/SPU2/spu2sys.cpp, pcsx2/ps2/BiosTools.h
Clean up some warnings and put in a missing break which may not have mattered, but should have been there.
Less warnings in compilation.
Check the CI and make sure it's happy.
=> Build: Clean up warnings, fix a small error.

pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/Recording/InputRecording.cpp, pcsx2/SPU2/defs.h, pcsx2/USB/usb-pad/evdev/evdev-ff.cpp, pcsx2/USB/usb-pad/evdev/evdev.cpp, pcsx2/USB/usb-printer/usb-printer.cpp, pcsx2/gui/AppInit.cpp, pcsx2/ps2/BiosTools.cpp, pcsx2/x86/microVU_Flags.inl
Clean up more warnings, mostly with GCC/Clang
Less warnings = good
Check CI if it's reporting warnings still
=> Build/Various: Clean up warnings

pcsx2/Frontend/OpenGLHostDisplay.cpp
clang likes to whinge about this one.
Less noise.
Make sure it still compiles.
=> Frontend/OpenGLHostDisplay: Remove unused variables

pcsx2/GS/GS.cpp, pcsx2/GS/GSPerfMon.h, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
Commit which I had on my branch and apparently forgot to PR. Also adds a stat for barriers.
Slightly more brr.
Check games in Vulkan with barriers on and off.
=> Vulkan: Support primid DATE without barriers, skip feedback loop, elide some barriers

bin/resources/shaders/dx11/convert.fx, bin/resources/shaders/dx11/merge.fx, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp
=> GS/DX11: Fix MMOD=1 merge background color

bin/resources/GameIndex.yaml
add 'EETimingHack' to 'Harry Potter and the Chamber of Secrets'
make sure ci passes or check the game
=> GameDB:add 'EETimingHack' to'Harry Potter and the Chamber of Secrets'

pcsx2/PINE.cpp, pcsx2/SPU2/SndOut_Cubeb.cpp
Warning cleanups.
Make it sparkly clean.
It compiles.
=> Misc: Fix some more warnings.

pcsx2-qt/QtHost.cpp
Makes PCSX2-Qt follow the same data directory selection as the wx interface, i.e. `Documents/PCSX2` for Windows, `~/.config/PCSX2` for Linux, and `~/Library/Application Support/PCSX2` for Macs (not sure if correct).
Of course, `portable.ini` will continue to override and use the program directory.
I don't want to bikeshed about whether things should go in `XDG_CONFIG_HOME` or `XDG_DATA_HOME`, I'm just making Qt the same as WX. If you want to argue to change it, you can do so with a follow-up PR ;)
Consistency, making it easier to migrate to Qt.
Test Windows and Linux Qt in both portable and non portable mode (I've tested Windows).
=> Qt: Implement proper data directory selection

bin/resources/GameIndex.yaml
GameDB: game fixes for 'DMC', 'Fatal Frame' and 'MX vs. ATV - Untamed'
Fixes #5960 
look at CI , test said games
=> GameDB: game fixes for 'DMC', 'Fatal Frame' and 'MX vs. ATV - Untamed'

bin/resources/GameIndex.yaml, pcsx2-qt/Settings/SystemSettingsWidget.ui
Change Vu clamp from nearest to Extra+Preserve sign.
Fixes https://github.com/PCSX2/pcsx2/issues/5944
Fixes SPS and invisible/flickering characters as nearest wasn't good enough.
Play any SOCOM 3 title.
=> GameDB: SOCOM 3 + Combined Assault

bin/resources/GameIndex.yaml
GameDB: Add preload frame data for Ninja Assault.
Fixes intro captions not displaying.
Fixes #5965
Test #5965
=> GameDB: Add preload frame data for Ninja Assault.

bin/resources/GameIndex.yaml
Adds missing serial form the GameDB 
a more complete Gamedb 
=> GameDB: Japanese entries Batch 2

bin/resources/GameIndex.yaml
Adds missing serial form the GameDB
a more complete Gamedb
look at CI
=> GameDB: Japanese entries Batch 3

bin/resources/GameIndex.yaml
add 'XGKickHack' to 'WRC II - Extreme'
look at CI
=> Gamedb:add 'XGKickHack' to 'WRC II Extreme'

bin/resources/GameIndex.yaml
The FMV has black frames when upscaled.
Fixes #5899
=> GameDB: HW fixes for KOF Orochi/Nests

bin/resources/GameIndex.yaml, pcsx2/GS/GSCrc.cpp, pcsx2/GS/Renderers/HW/GSHwHack.cpp
Adds missing gamefixes that influenced random corruptions and the famous fog wall.
Less tinkering
Test Crash Bandicoot wrath of cortex.
=> GameDB: Crash Bandicoot - Wrath of Cortex

pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
Squish two functions into one
Less code that's not used half the time and easy to accidentally forget to update
Enable the C rasterizer and make sure nothing broke
=> Merge SSE4 and AVX2 C Rasterizer

bin/resources/GameIndex.yaml
adds 'VIF1StallHack' to 'Ikusa Gami
look at CI / try said game
=> GameDB: add 'VIF1StallHack' to 'Ikusa Gami'

pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
GS: Cleanup variable declarations/initalizations.
Prettier to look at, consistency.
It compiles
=> GS: Cleanup variable declarations/initalizations.

pcsx2-qt/EmuThread.cpp, pcsx2-qt/EmuThread.h, pcsx2-qt/Main.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/Settings/ControllerBindingWidget_DualShock2.ui, pcsx2-qt/Settings/ControllerBindingWidgets.cpp, pcsx2/Frontend/GameList.cpp, pcsx2/Frontend/GameList.h, pcsx2/Pcsx2Config.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
Bunch of stuff from my working branch which I'm too tired to write separate descriptions for.
More stuff for Qt.
It works for me.
=> Qt: Random assorted work

pcsx2/x86/microVU.cpp
corrects logging and remove not needed comments in microVU
look at CI
=> microVU : correct logging and remove not needed comments

common/Dependencies.h, common/TraceLog.h, pcsx2/DebugTools/Debug.h, pcsx2/gui/pxCheckBox.cpp, pcsx2/gui/pxCheckBox.h, pcsx2/gui/pxStaticText.cpp, pcsx2/gui/pxStaticText.h, pcsx2/gui/pxWindowTextWriter.cpp, pcsx2/gui/wxGuiTools.h, pcsx2/gui/wxHelpers.cpp
Deleted some code that isn't used in pcsx2 anywhere.
Less code, mostly written by air.
Compile without said code.
=> Remove a few pieces of dead code.

bin/resources/GameIndex.yaml
VuClamp Extra+Sign for Monster Hunter 1
Before:
After:
Fixes lighting on character models as caves and other locations don't turn mobs into glow-in-the-dark creatures by themselves.
Test Monster Hunter
=> GameDB: Monster Hunter 1

bin/resources/GameIndex.yaml
GameDB: add VUclamping to 'Monster Hunter 2' and 'Monster Hunter G'
fixes said games 
look at CI
=> GameDB: add VUclamping to 'Monster Hunter 2' and 'Monster Hunter G'

pcsx2/Docs/PCSX2_FAQ.md, pcsx2/gui/MainMenuClicks.cpp
Update hyperlink that was 404ing in WX
Make sure option works
=> GUI: update hyperlink in WX

CMakeLists.txt, cmake/Pcsx2Utils.cmake, common/vsprops/preBuild.cmd, pcsx2-qt/AutoUpdaterDialog.cpp, pcsx2-qt/CMakeLists.txt, updater/CMakeLists.txt, updater/Updater.cpp, updater/Updater.h, updater/UpdaterExtractor.h
Fixes broken Qt build, my bad.
=> Build: Fix revision extractor for Qt auto updater

pcsx2-qt/EmuThread.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h
Hooks up the screenshot button/menu item in QT.
The screenshot button should work.
Take a screenshot.
=> Qt: Hook up screenshot button.

bin/resources/GameIndex.yaml
updates EyeToy - Play 2 compat in Gamedb 
GameDB wasnt updated when eyetoy emulation was fixed 
look at CI
=> GameDB: update EyeToy - Play 2 compat

bin/resources/GameIndex.yaml
GS (HW) Fixes:
- R - Racing Evolution
- Lemony Snicket's A Series of Unfortunate Events
- Free Running
- Sopranos
Before:
After:
Before:
After:
Before:
After:
Before:
After:
New Serials:
- Shadow Hearts II [Demo]
- GI Jockey 2 [Demo]
- Hajime no Ippo - Victorious Boxers
=> GameDB: Add new serials, GS (HW) Fixes

bin/resources/GameIndex.yaml
fixes a mistake from @RedDevilus 
fixes the  gamedb 
make sure the CI passes
=> GamDB:  fix 'Racing Evolution' serial

bin/resources/GameIndex.yaml
Fixes game serials 
check if i haven't missed anymore and make sure CI passes
=> Gamedb: fix 'Hajime no Ippo - Victorious Boxers' serial

common/StringUtil.cpp, common/StringUtil.h, pcsx2/CDVD/GzippedFileReader.cpp
See title, regression from wx ripout.
=> GzippedFileReader: Fix index creation

pcsx2/Counters.cpp, pcsx2/Dmac.cpp, pcsx2/HwWrite.cpp, pcsx2/ps2/HwInternal.h, pcsx2/ps2/Iop/IopHwWrite.cpp
Removes some old defines and modernize some switch statements
Cleaner code
Make sure I didn't break anything, test OPH flag hack.
=> DMAC: Remove some old defines, optimize case statements

pcsx2-qt/AutoUpdaterDialog.cpp, pcsx2-qt/GameList/GameListWidget.cpp, updater/Updater.cpp, updater/Updater.h, updater/Windows/WindowsUpdater.cpp
Fixes https://github.com/PCSX2/pcsx2/issues/6141
Fixes https://github.com/PCSX2/pcsx2/issues/6136
Fixes https://github.com/PCSX2/pcsx2/issues/6127
=> Qt: Various issue fixes

bin/resources/GameIndex.yaml
upscaling fixes for 
before:
with fixes :
=> GameDB: upscaling fixes for 'KimiKiss'

pcsx2-qt/EmuThread.cpp, pcsx2-qt/Main.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/QtHost.cpp, pcsx2-qt/Settings/EmulationSettingsWidget.cpp, pcsx2-qt/Settings/EmulationSettingsWidget.ui, pcsx2/CDVD/InputIsoFile.cpp, pcsx2/MultipartFileReader.cpp, pcsx2/R5900Exceptions.h
Fixes #6146 .
Fixes #6158 .
Fixes #6160 .
Fixes #6147.
=> Qt: More issue fixes

bin/resources/GameIndex.yaml
With Qt being released there were still illegal characters being used in the name (which stops you from using covers and more), also found some random typo mistakes.
Fixes https://github.com/PCSX2/pcsx2/issues/6170
GsHWFixes:
- Ratatouille
- Wild Arms series
- Tony Hawk Downhill Jam
Ratatouille;
Before:
After:
So it's not perfect, but you can use roundsprite to full but will give vertical line effect or you could use texture offsets.
Wild Arms Series;
Upscaled (no changes):
Half Roundsprite (used currently which wasn't perfect):
Wild Arms (new one for whole series):
Tony Hawk Downhill Jam;
Before:
After:
Test ratatouille.
=> GameDB: Revise serial names + GSHWFixes

bin/resources/GameIndex.yaml
=> GameDB: add 'disablePartialInvalidation' to 'Shadow Hearts 2'

bin/resources/GameIndex.yaml
missed these form the  last batch
=> GameDB: more removal of software FMV fixes from games

common/D3D12/DescriptorHeapManager.cpp, common/D3D12/DescriptorHeapManager.h, pcsx2/GS/Renderers/DX12/GSDevice12.cpp
Noticed this with the debug layer enabled on UWP.
Fixing errors.
Make sure DX12 still works.
=> DX12: Couple of misc fixes

bin/resources/GameIndex.yaml
fixes game names in the GameDB
check said game
=> GameDB: fix up game names

pcsx2/GS/GSState.cpp
Bug fix for #6229
Coding at 4am, U's look like V's
I've already tested it, it's fine.
=> GS: Bug fix Scissor Optimization

bin/resources/GameIndex.yaml
=> Gamedb: fix up some game titles

bin/resources/GameIndex.yaml
Fixes #6245
make sure everything is ok
=> GameDB: update 'Growlanser Generations' name

pcsx2/Config.h
remove unused  variable from superVU
make sure pcsx2 works as intended
=> Config: remove unused  variable from superVU

bin/resources/GameIndex.yaml
=> GameDB: remove gameFixes from'NFL Street 2'

bin/resources/GameIndex.yaml
=> GameDB: remove gameFixes for 'nfl street 3'

bin/resources/GameIndex.yaml
Fixes said game when upscaling 
=> Gamedb: add upscaling fixes for ' The Sims 2 pets'

bin/resources/GameIndex.yaml
=> Gamedb: upscaling fixes for 'Need for Speed: Hot Pursuit 2'

bin/resources/GameIndex.yaml
=> Gamedb: Fix up some game names and add upscaling fixes for 'Xenosaga'

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fixes GPU crash for DX12 in Ridge Racer V. Game still has broken car textures.
Crashing the whole emulator is bad.
Test RRV on DX12. Make sure no blowupy.
=> GS: Clamp tex-in-rt source rectangle to rt bounds

bin/resources/GameIndex.yaml
its not needed anymore 
look at CI
=> Gamedb: remove patch from 'Boku to Mao'

bin/resources/GameIndex.yaml
=> Gamedb: Chou! Rakushii Internet Tomodachi Nowa

bin/resources/GameIndex.yaml
a more correct DB
make sure its correct
=> Gamedb: fix game  title typos

bin/resources/GameIndex.yaml
=> GameDB: upscaling fixes  for 'Tokyo Xtreme Racer Drift 2'

bin/resources/GameIndex.yaml
Read the description
Less tinkering needed.
Test all the Jak games.
=> GameDB: Fix line in the sky for Jak games

bin/resources/GameIndex.yaml
Fixes: #6273
make sure  CI passes ,  @githubribbon45  can you just double check i haven't made a mistake
=> GameDB: add patches for  'Harry Potter and the Half-Blood Prince'

bin/resources/GameIndex.yaml
Fixes vertical lines in-game (merge sprite) and FMV (software renderer gamefix)
=> GameDB: Forbidden Siren 2

README.md
Updated 'more than ten years old' to 'more than twenty years old'. Groundbreaking stuff. Eat your heart out, @stenzek.
The project is more than twenty years old now.
Make sure the word 'twenty' is spelled correctly and that the project is, indeed, more than twenty years old.
=> Documentation: Update README.md to reflect project's age.

.github/workflows/macos_build.yml, .github/workflows/macos_build_matrix.yml, .github/workflows/release_pipeline.yml, .github/workflows/scripts/macos/build-dependencies.sh, cmake/BuildParameters.cmake, cmake/Pcsx2Utils.cmake, cmake/SearchForStuff.cmake, common/CMakeLists.txt, common/CocoaTools.h, common/CocoaTools.mm, common/Vulkan/SwapChain.cpp, pcsx2-qt/CMakeLists.txt, pcsx2-qt/DisplayWidget.cpp, pcsx2-qt/EmuThread.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/MainWindow.ui, pcsx2-qt/Settings/GameSummaryWidget.ui, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/InterfaceSettingsWidget.cpp, pcsx2/CMakeLists.txt, pcsx2/Frontend/InputManager.cpp, pcsx2/Frontend/InputManager.h, pcsx2/Frontend/InputSource.h, pcsx2/Frontend/SDLInputSource.cpp, pcsx2/Frontend/SDLInputSource.h, pcsx2/Frontend/XInputSource.cpp, pcsx2/Frontend/XInputSource.h, pcsx2/VMManager.cpp
Adds a macOS Qt build
Nice to have the new UI working on macOS
- Make sure I didn't break anything
- Make sure I properly set everything up so the builds show up on the website and stuff
=> Mac Qt build

bin/resources/GameIndex.yaml
add HW fixes for snowblind engine games
Make sure CI is happy
=> GameDB: add HW fixes for snowblind engine games

bin/resources/GameIndex.yaml
Fixes: #6333
make sure CI pases , @githubribbon45  make sure i haven't made any mistakes
=> Gamedb: fixes for 'Call of Duty - Le Jour de Gloire'

bin/resources/GameIndex.yaml
=> Gamedb: add patch for 'Transformers - Revenge of the Fallen'

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
Qt: Add tooltips to Graphics section.
Most of them are ported from WX.
Adds tooltips to Graphics section.
Make sure tooltips work.
=> Qt: Add tooltips to Graphics section.

pcsx2/IPU/mpeg2lib/Mpeg.cpp
Waits for IPU0 to be wanting data before filling the output fifo
Timing/request annoyances with how our IPU works, killed Tekken 4 US.
Make sure videos work as well as they did.
=> IPU: Wait for IPU_FROM to be ready

bin/resources/GameIndex.yaml
=> Gamedb:add upscaling fixes for 'Test Drive'

bin/resources/GameIndex.yaml
helps said game 
make sure CI is happy , test said game
=> GameDB: add HW fixes for 'Raging Bless'

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
~~Based on #3895.~~
Avoid discarding the entire target upon incompatible format write (same block pointer), just mark the related rectangle as dirty.
See #5317.
Check that #5317 is fixed.
Make sure no regressions occur.
=> GS: preserve target on different format write. 

bin/resources/GameIndex.yaml
=> Gamedb: add disablePartialInvalidation to snowblind engine games

bin/resources/GameIndex.yaml
=> Gamedb: fix up 'Deadly Skies III' name

bin/resources/GameIndex.yaml
helps said game upscale 
make sure CI  is happy
=> Gamedb: add upscaling fixes  to 'Fast and the Furious'

bin/resources/GameIndex.yaml
=> Gamedb: remove not needed patches

bin/resources/GameIndex.yaml
=> Gamedb: Fix games names

bin/resources/GameIndex.yaml
=> GameDB: add 'Axel Impact - The Extreme Racing'

bin/resources/GameIndex.yaml
=> Gamedb: remove patches and add upscaling fixes for  'Onimusha - Dawn of Dreams'

pcsx2/Config.h, pcsx2/Counters.cpp, pcsx2/GS.cpp, pcsx2/GS.h, pcsx2/GS/GS.cpp, pcsx2/GS/GS.h, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/MTGS.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/gui/AppConfig.cpp, pcsx2/gui/FrameForGS.cpp, pcsx2/gui/GlobalCommands.cpp, pcsx2/gui/Panels/ConfigurationPanels.h, pcsx2/gui/Panels/VideoPanel.cpp
GS/Core: Purge frameskipping.
Get rid of frameskipping, won't be added to Qt.
Follow up from #5011
Make sure nothing got broken.
=> GS/Core: Purge frameskipping.

bin/resources/GameIndex.yaml
as mentioned in  #3496  the games now work as intended in SW mode without the patches   , thus the removal 
@Immersion95  can you make sure i haven't missed any patches that needs to  be removed 
=> Gamedb: remove no longer needed patches

bin/resources/GameIndex.yaml
=> Gamedb: remove gamefixes form "Axel Impact - The Extreme Racing"

bin/resources/GameIndex.yaml
=> Gamedb: fix 'Sega Sports Tennis' name

bin/resources/GameIndex.yaml
corrects GameDB and fixes said game 
=> GameDB: Fix game names "ICO" and  add "Monster Rancher Evo" fixes

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
Fixes the Metal ImGui renderer for more complicated things
Less broken
=> Metal: Fix ImGui renderer

bin/resources/GameIndex.yaml
=>  Gamedb: add "EETimingHack" for "Strikers 1945 1-2" and gamefixes for "Star wars episode 3"

pcsx2/VMManager.cpp
Automatically switches the aspect ratio to 16:9 when set to auto, and widescreen patches are found for the running game.
Saves manually setting the aspect ratio as well.
Test games with WS patches with AR set to auto.
=> VMManager: Auto switch to 16:9 when ws patches are enabled/found

pcsx2/MTGS.cpp
See title. Would happen because the emu thread would read GS local memory while it was being reopened.
Crashing is bad.
Test game with heavy readbacks, and hw readbacks disabled. Change any GS setting (e.g. resolution) => shouldn't crash, when it was probable before.
=> GS: Fix possible crash when changing settings with readbacks disabled

bin/resources/GameIndex.yaml
=> Gamedb: DB Updates

bin/resources/GameIndex.yaml
said games were missing said upscaling fixes 
=> GameDB: add missing upscaling fixes to "Xenosaga Episode III"

pcsx2/CDVD/CDVD.cpp, pcsx2/Frontend/VulkanHostDisplay.cpp, pcsx2/GS/GSState.cpp
Misc: Clean up warnings.
Wsign-compare, Wunused-variable, Wunused-variable.
Less warnings.
CI builds.
=> Misc: Clean up warnings.

.github/workflows/scripts/linux/appimage.sh
fix Appimage-checkrt link
Was broke due to upstream changes and hotlinking
watch CI
=> Build: Fix appimage.sh

bin/resources/GameIndex.yaml
=> GameDB: upscaling fixes for "Mike Tyson Heavyweight Boxing"

bin/resources/GameIndex.yaml
=> Gamedb:Add missing  serials

pcsx2/x86/BaseblockEx.cpp, pcsx2/x86/iFPUd.cpp, pcsx2/x86/iR3000A.cpp, pcsx2/x86/ix86-32/iR5900Templates.cpp
Core: Cleanup remaining variable scope warnings on Codacy.
I believe that's all of the scope warnings.
Make codacy happier.
Nothing got broken.
=> Core: Cleanup remaining variable scope warnings on Codacy.

bin/resources/GameIndex.yaml
fixes game name in gamedb
none needed
=> Gamedb: Fix game names

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fixes formats such as PSMT4HL giving different hashes depending on what the overlapping/shared pixels in local memory contain.
Enable this unconditionally, rather than only when dumping, because unswizzling and hashing is around 25% faster on AVX2 builds than hashing the backing local memory for larger textures (e.g. Star Ocean 3 menus). Also has the added bonus of hitting the cache more often in such cases too.
Fixes #6451 (possibly).
Test texture dumping and replacement. Make sure no existing texture packs are broken (only those which used these texture formats will have any hash changes, and they would have been unreliable to begin with).
=> GS/TextureCache: Unswizzle shared texture formats when hashing

pcsx2/USB/linux/ini.c, pcsx2/USB/qemu-usb/usb-ohci.cpp, pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp, pcsx2/USB/usb-pad/usb-pad-ff.cpp
USB: Cleanup more variable scope warnings.
Codacy.
Looks like I missed some.
Less warnings, cleaner code.
CI builds.
=> USB: Cleanup more variable scope warnings.

bin/resources/GameIndex.yaml
=> GameDB: fix up wrong titles

pcsx2/GS/Renderers/Common/GSRenderer.cpp
Adjusts the offset for the interlacing when upscaled to be half the upscale amount when in FFMD mode (which uses half height framebuffers)
Baldurs Gate DA 2 3D became blurry after #6498 due to me pulling a value out of my butt which I didn't even really think properly about.
Test Baldurs Gate games for blurring
=> GS: Adjust interlacing offsets to something more sensible.

pcsx2-qt/Settings/AdvancedSystemSettingsWidget.cpp, pcsx2-qt/Settings/EmulationSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2-qt/Settings/SystemSettingsWidget.cpp
Add tooltips  to Emulation, Advanced System and System Settings.
Adding tooltips.
Make sure tooltips work.
=> Qt: Add second batch of tooltips.

bin/resources/GameIndex.yaml
=> Gamedb: add VUclamping to "NCAA March Madness 2003/2004"

bin/resources/GameIndex.yaml
=> GameDB:  fix game titles and add an entry

pcsx2-qt/MainWindow.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.ui, pcsx2-qt/Settings/InputBindingDialog.cpp, pcsx2-qt/Settings/InputBindingDialog.h, pcsx2-qt/Settings/InputBindingWidget.cpp, pcsx2-qt/Settings/InputBindingWidget.h, pcsx2/PAD/Host/Global.h, pcsx2/PAD/Host/KeyStatus.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
Based on the comments in the other PR thread, this seems like a reasonable thing to do.
Also fixes some minor drag and drop issues.
Why not.
Test pressure modifier again (it should update existing button pressure when pressed).
Test drag/drop GSdumps.
=> PAD: Adjust existing button pressure when modifier activated

bin/resources/GameIndex.yaml
=>  Gamedb: fixup wrong titles and add game fixes 

bin/resources/GameIndex.yaml
=> Gamedb: upscaling fixes for Kingdom Hearts - Final Mix

pcsx2-qt/Settings/SettingsDialog.cpp
Adds missing settings descriptions in QT 
make sure QT builds and wording is correct
=> QT: settings descriptions

pcsx2/CDVD/ThreadedFileReader.cpp
Should hopefully fixes a crash reported during scanning from a user a while back.
> finally looked at that random crash during scanning from a while back, reader thread is doing chd_read(), and the scanner thread has already done chd_close(). both m_running and m_quit were true, m_requestCancelled was true.
> 
> So what I'm guessing happened was:
> 1. request got added, thread still sleeping
> 2. read got cancelled by the close, which locked the mutex, saw m_running was false, and returned
> 3. thread woke up, but before the destructor ran, so m_quit was still false, picked up the request, and started reading it
> 4. scanner thread destructs the reader object, which closes the chd, then calls the base destructor (which joins the thread)
> 5. UAF happens in chd_read()
Setting …
=> ThreadedFileReader: Fix a low-chance race when closing file

pcsx2-qt/Settings/AdvancedSystemSettingsWidget.cpp, pcsx2-qt/Settings/EmulationSettingsWidget.cpp
adds more missing QT descriptions
make sure QT builds and wording is appropriate
=> QT: more missing descriptions

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
Just giving the user more information about the OSD/Post Processing Options. 
Check if the additional descriptions are in proper form.
=> QT: Adds descriptions to OSD/Post Processing Settings

pcsx2-qt/Settings/EmulationSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.ui
more missing descriptions  
make sure QT builds
=> QT: more settings descriptions part 3

bin/resources/GameIndex.yaml
corrects GameDB
fixes #6586
none
=>  Gamedb: fix up game names and add HWfixes 

bin/resources/GameIndex.yaml
=> Gamedb: fix game titles

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
Fixes some minor typos from a recent change.
Less typos good.
=> UI: Minor typo fixes

bin/resources/GameIndex.yaml
=> GameDB: fix memcard filters

bin/resources/GameIndex.yaml
=> Gamedb: add EEclamping for "Cowboy Bebop" and  autoflush for burnout 3

bin/resources/GameIndex.yaml
=> Gamedb: add missing  MGS3 HWfixes

bin/resources/GameIndex.yaml
=> Gamedb: autoflush for  Burnout Dominator/ Revenge

bin/resources/GameIndex.yaml
1269c80
* SLES-52856 "10 Most Wanted"
* SLPM-55014 "Aria - The Origination - Aoi Hoshi no El Cielo"
* SLPM-55282 "Armen Noir"
* SLPM-62320 "2003-nen Kaimaku - Ganbare Kyuukai-ou - Iwayuru Pro Yakyuu desu ne"
* SLPM-62323 "AI Shougi 2003"
* SLPM-62329 "AI Igo 2003"
* SLPM-62330 "AI Mahjong 2003"
* SLPM-65037 "Angelique Trois - Aizouban [Shokai Gentei Package]"
* SLPM-65151 "Akudaikan"
Consistent and accurate gamedb
=> Gamedb: additions & fixes

pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/PAD/Windows/DualShock3.cpp, pcsx2/SaveState.h, pcsx2/USB/qemu-usb/usb-ohci.cpp, pcsx2/USB/usb-eyetoy/jo_mpeg.cpp, pcsx2/USB/usb-pad/usb-seamic.cpp, pcsx2/x86/iCore.cpp
Cleans up misc codacy warnings.
Less warnings.
Everything still works.
=> Misc: Another batch of codacy warnings fixes.

bin/resources/GameIndex.yaml
a more correct GameDB
make make sure CI passes
=> GameDB: various GSHWFixes

pcsx2/IPU/mpeg2lib/Mpeg.cpp
Adjusts the timing of IDEC/BDEC following the end of an IPU_FROM transfer.
The command was continuing/ending immediately at the end of an IPU transfer which is poor timing, causing Shin Megami Tensei - Devil Summoner 2 to have an IPU error during a video following the third boss (could have also been avoided by speeding up the EE, but not recommended).
Test videos, make sure nothing is broken.
=> IPU: Adjust timing on IDEC/BDEC after IPU0 transfer

bin/resources/GameIndex.yaml
add missing serial
a more complete Gamedb 
=> Gamedb: missing serial

.github/ISSUE_TEMPLATE/app_bug_report.yaml, .github/ISSUE_TEMPLATE/emu_bug_report.yaml
clean-up  issue templates
make sure it looks correct
=> Github: clean-up  issue templates

bin/resources/GameIndex.yaml
=> Gamedb: GShw fixes for Spider-Man 2

bin/resources/GameIndex.yaml
Addition of missing serials and fixes of some titles.
Consistent and accurate gamedb.
...
=> GameDB: addition of missing serials (from H to J) & fixes of titles

bin/resources/GameIndex.yaml
Adds autoflush to God Of War 2.
Fixes the sun occluding through walls.
=> GameDB: God Of War 2 Fixes

bin/resources/GameIndex.yaml
Adds texture inside RT to Urban Reign.
Fixes corruption in game.
=> GameDB: Urban Reign fixes

bin/resources/GameIndex.yaml
Adds VU clamping to Arena Football
Fixes missing crowds ingame.
=> GameDB: Arean Football fixes

bin/resources/GameIndex.yaml
Adds autoflush to God of War.
Stops the sun from peeking out from behind walls.
=> GameDB: GoW Fixes

pcsx2-qt/MainWindow.cpp, pcsx2-qt/Settings/ControllerSettingsDialog.cpp
See commit list.
Fixes #6692.
Test stuff mentioned in commit list.
=> Qt: More bug fixes

.github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/macos/build-dependencies.sh, .github/workflows/windows_build_qt.yml, common/CMakeLists.txt, common/LRUCache.h, common/common.vcxproj, common/common.vcxproj.filters, common/vsprops/QtCompile.props, pcsx2-qt/GameList/GameListModel.cpp, pcsx2-qt/GameList/GameListModel.h, pcsx2-qt/GameList/GameListWidget.cpp
Also updates all platforms to 6.3.1 for consistency.
Fixes #6490.
Test scrolling with a larger number of covers, general UI functionality (due to version bump).
=> Qt: Asynchronous loading of covers (and 6.3.1 update)

bin/resources/GameIndex.yaml
fixes said game and correct Gamedb 
=> GameDB: add gamefixes to cod 2 and fix titles

bin/resources/GameIndex.yaml
Fixes said game  , 
make sure CI passes @stoniemahonie can you check this for me :slightly_smiling_face:
=> GameDB: add  'VUSyncHack' to  Air Ranger - Rescue Helicopter

bin/resources/GameIndex.yaml
=> GameDB: Correct title for Mushihimesama

pcsx2-qt/Settings/BIOSSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/SystemSettingsWidget.cpp
Fixes some missing or incorrect recommended boxes.
Missing text is bad.
=> Qt: Recommended text fixes

bin/resources/GameIndex.yaml
Fixes misaligned text and car shadow softness.
Misaligned text is bad.
=> GameDB: WRC 4 Fixes

bin/resources/GameIndex.yaml
helps Performance for Hitman  Contracts
make sure CI is happy :)
=> Gamedb: add partial preload to "Hitman  Contracts"

bin/resources/GameIndex.yaml
=> Gamedb:upscaling fixes for "dot hack  Infection Part 1"

bin/resources/GameIndex.yaml
Fixes some more problems with Kya - Dark Lineage Wild Arms 5 Kingdom Hearts Re Chain of Memories Conflict Desert Storm 2 Shadow the Hedgehog and Need for Speed ProStreet.
Some fixes are incorrect or outright missing from the db.
=> GameDB: Misc fixes and additions

bin/resources/GameIndex.yaml
Adds fixes and adds a missing entry in the DB for the Korean version.
Fixes are good, a more complete GameDB is even better.
=> GameDB: Maximo vs Army of Zin Fixes

bin/resources/GameIndex.yaml
Fixes FMV's in Dual Hearts
Improved FMV quality.
Only applied to NTSC-U version.
Don't know if NTSC-J is affected, unable to check.
Fixes #6715.
=> GameDB: Fixes Dual Hearts FMV's not being deinterlaced

bin/resources/GameIndex.yaml
Fixes some out of date compat levels
More correct DB more good.
=> GameDB: Misc compat level fixes

bin/resources/GameIndex.yaml
Fixes a misnaming of a game.
More correct DB more good.
=> GameDB: Fix to the name of Asterix & Obelix XXL

bin/resources/GameIndex.yaml
remove not needed upscaling fixes 
=> Gamedb: remove not needed upscaling  fixes for God of war

bin/resources/GameIndex.yaml
=> Gamedb: add basic mipmap to Blood Omen 2

bin/resources/GameIndex.yaml
Corrects the name of the PAL version of The Incredible Hulk and adds missing demo version to the db
More correct db more good.
=> GameDB: Correct The Incredible Hulks name

pcsx2/GS/GSCrc.cpp, pcsx2/GS/GSCrc.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp
GS-hw: Purge MidnightClub3 crc hacks.
arent needed anymore 
Test the mentioned game
=> GS-hw: Purge MidnightClub3 crc hacks.

pcsx2/GS/GSCrc.cpp, pcsx2/GS/GSCrc.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp
GS-hw: Purge SkyGunner crc hacks.
arent needed anymore 
test said game
=>  GS-hw: Purge SkyGunner crc hacks.

bin/resources/GameIndex.yaml
Adds Special HPO to Devil Kings
Misaligned bloom is bad.
=> GameDB: Fixes for Devil Kings

bin/resources/GameIndex.yaml
fixes said game when upscaling 
=> Gamedb: upscaling fixes for Poison Pink/ Eternal Poison

bin/resources/GameIndex.yaml
upscaling fixes for said game 
=> Gamedb: upscaling fixes for Shadow of Rome

bin/resources/GameIndex.yaml
Adds texture preloading partial to Ace Combat 5 for better performance.
Brrr
=> GameDB: Ace Combat 5 Fixes

bin/resources/GameIndex.yaml
=> Gamedb: add missing Alpine Racer 3 entries

bin/resources/GameIndex.yaml
=> Gamedb: add missing 'Ace Combat 04' entry

bin/resources/GameIndex.yaml
=> Gamedb: add fixes for 'World Rally Championship' NTSC-J versions

pcsx2/GS/GSCapture.cpp, pcsx2/GS/GSCapture.h, pcsx2/PAD/Host/KeyStatus.cpp
GS: Fix Wunused-private-field warning.
PAD: Fix Wsign-compare warning.
Less warnings.
CI compiles, warnings are gone.
=> Misc: Warnings cleanup as usual

bin/resources/GameIndex.yaml
=> Gamedb: add upscaling fixes to 'Charlie's Angels'

pcsx2-qt/Settings/EmulationSettingsWidget.cpp
Just changing checked to Checked
=> QT: Fixing a minor typo in Emulation Settings

pcsx2/GS/GSState.cpp
GS: Cleanup GSState.cpp.
constants, scope, duplicate declarations, initializations.
Cleaner code.
Still compiles, nothing broke.
=> GS: Cleanup GSState.cpp.

bin/resources/GameIndex.yaml
Adds autoflush to restore the lava fire effect
Fire hot.
=> GameDB: Tomb Raider Angle of Darkness effect fixes

bin/resources/GameIndex.yaml
Adds software FMV switch to The Thing JP and texture preloading partial to Osouji Sentai Clean Keeper H.
Flashing lights tend to be bad for the epileptic.
=> GameDB: Various game fixes and missing entrys

bin/resources/GameIndex.yaml
Adds some missing PAL demos.
More complete gameDB more good.
=> GameDB: Add some missing demos

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
GS-hw: Cleanup GSRendererHW.cpp.
constants, scope, duplicate declarations, initializations, null pointers.
Cleaner code.
Compiles, nothing broke.
=> GS-hw: Cleanup GSRendererHW.cpp.

.github/workflows/linux_build_matrix.yml, .github/workflows/macos_build.yml, .github/workflows/scripts/common/name-artifacts.sh, .github/workflows/windows_build_matrix.yml, .github/workflows/windows_build_wx.yml, cmake/BuildParameters.cmake, pcsx2/CMakeLists.txt
- LTO more things
- PDB generation
- More optimization flags
This should hopefully get CMake builds to the same level of performance as MSBuild builds
Test CMake builds and see if they're as fast as SSE4 MSBuild builds
=> CMake MSVC improvements

bin/resources/GameIndex.yaml
Fixes some previous fixes so those fixes actually work or don't break the game
Mipmapps Full just made Dominator look blocky and even worse than just not having mipmapping at all.
=> GameDB: General clean up

bin/resources/GameIndex.yaml
Added memcardFilters to Armored Core - Last Raven
for converting data from previous series when using Folder memcard
=> GameDB: Added memcardFilters to Armored Core - Last Raven
