PCSX2/pcsx2

pcsx2/CDVD/IsoFS/IsoFS.cpp
pcsx2/DebugTools/Breakpoints.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/SW/GSTextureCacheSW.cpp
pcsx2/MemoryCardFile.cpp
pcsx2/MemoryCardFolder.cpp
pcsx2/PAD/Linux/wx_dialog/GamepadConfiguration.cpp
pcsx2/PAD/Windows/DirectInput.cpp
pcsx2/PAD/Windows/WndProcEater.cpp
pcsx2/gui/AppConfig.cpp
pcsx2/gui/AppCoreThread.cpp
pcsx2/gui/AppInit.cpp
pcsx2/gui/ConsoleLogger.cpp
pcsx2/gui/IsoDropTarget.cpp
pcsx2/gui/SysCoreThread.cpp
pcsx2/gui/i18n.cpp

Misc: Fix variable initializations.
Try to fix codacy warnings: Variable 'variable' is assigned in constructor body. Consider performing initialization in initialization list.
Less warnings.
Nothing broke.

Misc: Fix variable initializations.

---

pcsx2/PAD/Linux/wx_dialog/JoystickConfiguration.cpp
pcsx2/gui/AppConfig.cpp
pcsx2/gui/AppRes.cpp

More variable initializations fixes that were left out.
Less codacy warnings.
Everything runs.

Misc: Fix variable initializations v2.

---

bin/resources/GameIndex.yaml

Re-ordering of Star Wars Episode 3 Gshwfixes.
Fixes https://github.com/PCSX2/pcsx2/issues/6813
Less hassle.
Test relevant game.

GameDB: Re-ordering gshwfix

---

pcsx2/CDVD/IsoFS/IsoDirectory.h
pcsx2/CDVD/IsoFS/IsoFS.cpp
pcsx2/USB/shared/inifile_usb.cpp
pcsx2/USB/shared/inifile_usb.h

Misc: Cleanup const reference warnings.
Codacy warning: Function parameter should be passed by const reference.
Less warnings.
Nothing broke.

Misc: Cleanup const reference warnings.

---

.github/CONTRIBUTING.md
pcsx2/Docs/README.md

fix some codacy warnings
less codacy warnings
look at the codacy report

Misc: fix some codacy warnings

---

common/FileSystem.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/DEV9/InternalServers/DHCP_Server.cpp
pcsx2/Frontend/ImGuiManager.cpp
pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GameDatabase.cpp
pcsx2/SPU2/Debug.cpp
pcsx2/ps2/pgif.cpp

Fixes up some listed codacy errors and warnings
code safety and styling
Make sure nothing explodes

Fix codacy errors and warnings

---

bin/resources/GameIndex.yaml

GameDB: add missing serial for 'Hyper Sports 2002 Winter'

---

bin/resources/GameIndex.yaml

Changes the region from NTSC-Unk to the correct NTSC-HK.
Correct region good.

GameDB: Fix "Curious George" region

---

bin/resources/GameIndex.yaml

Gamedb: fix incorrect korean serials

---

bin/resources/GameIndex.yaml

Fixes various titles and adds autoflush to Yumeria.
More correct GameDB more good.
Closes #6962
Closes #6966 

GameDB: Various title fixes and game fixes

---

bin/resources/GameIndex.yaml

Some title fixes.
GameDB accuracy.
...

GameDB: some title fixes letter A + SCAJ-30004 + SLPM-62346

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Enables the accumulation blend flag for more situations when alpha is known to be 1
- More hardware blending opportunities for maximum blending
- The new truncation-free blend_mix algorithm doesn't always give the correct values for a (255 - DstColor) color inversion on AMD GPUs.  This is used by some games to invert depth.  Conveniently, such inversions tend to use 1.0 afix alpha (since they're just trying to invert, not scale), which means they get caught by the new detection and pushed off of blend_mix onto the accumulation blend path, working around the issue.
Test the following trace in DX11, DX12, or barrier-free Vulkan on an AMD gpu:
[GodOfWar-MissingFloor.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/9439132/GodOfWar-MissingFloor.gs.xz.zip)
<details> …

GS: Use accumulation blend when alpha is known to be 1

---

pcsx2/IopBios.cpp

See title. Stops uLaunchELF from getting denied access to the root.
Also prevents host access when `hostRoot` is empty (potential vulnerability if hostfs is enabled, or if you had a malicious bios).
Should be able to access the root of the elf directory via `host:`.
Test anything which tries to read the root host directory.

IopBios: Fix opening host: or host:. as a directory

---

bin/resources/shaders/opengl/tfx_fs.glsl

Move rt fetching to a separate function
Avoid the `#if FRAMEBUFFER_FETCH` every time we need to fetch an rt value
Test OGL on systems with and without framebuffer fetch and verify that I didn't break anything

GS:OGL: Shader cleanup

---

bin/resources/GameIndex.yaml

Many title fixes in letter B.
GameDB accuracy.
CI checks OK

GameDB: fixes letter B

---

bin/resources/GameIndex.yaml

Gamedb: Fix  'Muppets Party Cruise'

---

pcsx2/Frontend/MetalHostDisplay.h
pcsx2/Frontend/MetalHostDisplay.mm
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSTextureMTL.h
pcsx2/GS/Renderers/Metal/GSTextureMTL.mm

- GPU usage tracking
- Image saving (I accidentally overrode a working method with a TODO... oops)
- Barrier counts in stats
More features yay
Test Metal renderer

Implement missing features in Metal renderer

---

pcsx2/Frontend/FullscreenUI.cpp

It doesn't exist anymore.
It doesn't exist anymore.
Make sure it compiles.

FullscreenUI: Remove accurate DATE option

---

bin/resources/GameIndex.yaml

Adds align sprite to Death by Degrees to fix FMV lines.
FMV lines are kinda spooky.

GameDB: Death by Degrees FMV line fixes

---

bin/resources/GameIndex.yaml

Adds round sprite half preload frame data and partial texture preloading to Deus Ex.
Graphical issues bad brrr good.

GameDB: Deus Ex various fixes

---

bin/resources/GameIndex.yaml

Upscaling fixes 
make sure CI happy

Gamedb: upscaling fixes for 'Urbz, The - Sims in the City'

---

pcsx2/Frontend/FullscreenUI.cpp

Fixes a typo in cycle skip in the full screen UI.
Self explanatory.

UI: Fullscreen UI typo fix

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h

See title.
Crash bad.
Closes #7027.
Test the stuff.

Qt: Fix fullscreen/window size being enabled in game list

---

bin/resources/GameIndex.yaml

Many title fixes in letter C + some missing fixes in letters A/B.
GameDB accuracy.
CI checks OK

GameDB: fixes letter C + some missing A/B fixes

---

bin/resources/GameIndex.yaml

Adds various missing entry's.
Missing games bad.

GameDB: Add missing TC NYC entry

---

pcsx2/IopBios.cpp

ioman and iomanx have different file mode values.
This caused home-brew that relied on stat() to return directories as files, or files as directories, or something. It was **wrong** nonetheless.
Improving iomanx support
Test home-brew that relies on the host filesystem.

IOPBios: Implement the different iomanx stat file modes

---

bin/resources/GameIndex.yaml

helps said game 
test said game

GameDB:add HWFixes to Steel Dragon EX

---

bin/resources/GameIndex.yaml

GameDB: Add a bunch of Korean games.
Closes 
https://forums.pcsx2.net/Thread-Bug-Report-GameIndex-yaml-is-needed-to-be-modified-PCSX2-Nightly-v1-7-3329
https://forums.pcsx2.net/Thread-Bug-Report-GameIndex-yaml-is-needed-to-be-modified-PCSX2-Nightly-v1-7-3327
https://forums.pcsx2.net/Thread-Bug-Report-GameIndex-yaml-is-needed-to-be-modified-PCSX2-Nightly-v1-7-3329-ADD
gamedb check passes.

GameDB: Add a bunch of Korean games.

---

pcsx2/USB/usb-pad/dx/dinput.cpp
pcsx2/gui/AppCoreThread.cpp

Misc: Codacy warnings batch cleanup.
Less warnings.
Compiles.

Misc: Codacy warnings batch cleanup.

---

bin/resources/GameIndex.yaml

Gamedb: fixes for 'Guitar Hero - World Tour'

---

pcsx2/CDVD/CDVD.cpp

Account for cycles lost from integer inaccuracy with small values.
Simulate a short delay with drive speed changes.
Closer to actual drive performance, seems to fix Digital Devil Saga's FMV transition hangs (maybe Shadow Hearts also)
Test Digital Devil Saga or Shadow Hearts.
Fixes #6914

CDVD: Fix integer inaccuracies + delay on drive speed change.

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.ui
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/VMManager.cpp
pcsx2/VMManager.h

Backup save states was missing (implemented in wx).
Delete option enables users to reclaim disk space.
Feature parity.
Test new features.
.

Qt: Add delete and backup save states options

---

bin/resources/GameIndex.yaml

Adds missing clamp mode fix to PAL version of Spiderman WoS.
Missing fixes bad.

GameDB: Add missing Spiderman Web of Shadows fix

---

bin/resources/GameIndex.yaml

Gamedb: add EE rounding to 'Ty the Tasmanian Tiger 3'

---

pcsx2-qt/Settings/AchievementSettingsWidget.cpp
pcsx2/Frontend/Achievements.cpp
pcsx2/Frontend/Achievements.h
pcsx2/Frontend/ImGuiFullscreen.cpp
pcsx2/Frontend/VulkanHostDisplay.cpp
pcsx2/VMManager.cpp

See commit list.
Reliability.
Make sure achievements still work.

Achievements: Fix a couple of random issues

---

pcsx2/GS/GSState.cpp

Fixes a couple of bugs introduced in #6389 with Assault Suits Valken.
There was a typo in the XYZF2 skip check, and flushes on write were incorrect.
Test stuff, make sure things are ok.  Known to mainly be used by Assault Suits Valken an Fast and the Furious.
Fixes most of #7005 (but not the lines, idk what that is)

GS: Fixes for flushes from PR #6389

---

pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp

GS-hw: Remove condition to enable upscaling hacks on Aggressive crc.
Not really needed, favor accuracy.
GS-hw: Cleanup GSHWHack.cpp
Declare functions noexcept, initialize variables.
Cleanup GSHWHack.cpp.
Make sure crc hacks still work.

GS-hw: Cleanup GSHWHack.cpp 

---

bin/resources/GameIndex.yaml

gamedb: add autoflush to 'The Simpsons: Hit & Run.'

---

pcsx2/INISettingsInterface.cpp

I thought I'd done this in PCSX2, but apparently I only did it in DuckStation.
This commit makes the settings save atomic, i.e. writes the new contents to a new file, then moves/renames it over the top of the old file.
That way, you don't end up with a half-written config file if PCSX2 crashes while saving, or you terminate it in the debugger (like I did...).
Improving reliability.
Spam some setting changes, make sure it saves.

INISettingsInterface: Write changes atomically

---

bin/resources/GameIndex.yaml

Gamedb: miscellaneous missing entries

---

pcsx2/Frontend/FullscreenUI.cpp

Fixes a possible deadlock when enabling achievements via the big picture UI.
Also adds a controller-based confirmation for enabling hardcore mode. 
Less confusion that it's enabled when it's actually not.
Test toggling achievement settings, make sure nothing deadlocks and the confirm popup works as expected.

FullscreenUI: Deadlock fix and add reset confirm for HC enable

---

bin/resources/GameIndex.yaml

Gamedb : add upscaling fixed to Call of duty 3

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Causes the validation layer to get angry, even though it's not used in the current draw.
Violating spec is bad.
Try a couple of games in Vulkan/DX12 renderer.

GS/Vulkan: Ensure we don't leave a bound texture in copy state

---

bin/resources/GameIndex.yaml

Fixes:#7208
Fixes:#6501
let CI run

GameDB: add fixes for Eternal Ring and Spongebob SquarePants Featuring Nicktoons - Globs of Doom

---

pcsx2/gui/Resources/Info.plist.in

add PCSX2 to Launchpad Game Category
fixes #7204
make sure CI dosent explode

Mac: add PCSX2 to Launchpad Game Category

---

bin/resources/GameIndex.yaml

adds missing  patch to Asobi ni Iku yo! Chikyuu Pinch no Kon'yaku Sengen
fixes #7224 
make sure CI runs  @retroNUC can you check this  :)

GameDB: add  missing patch to Asobi ni Iku yo! Chikyuu Pinch no Kon'yaku Sengen

---

bin/resources/GameIndex.yaml

Copy's over the existing patch that was missing from the limited edition version.
Missing patch bad.
Happy is CI sure make.

GameDB: Copy missing "Game ni Nattayo! Dokuro-chan" patch

---

pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Window/GSwxDialog.cpp

GS-wx: Misc fixes.
Add Hardware Download Mode option.
Remove Disable Hardware Readbacks.
Set dump decompression to LZMA.
And some other misc fixes.
Parity with Qt.
Make sure the options work.

GS-wx: Misc fixes.

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Use the image layout instead of start-of-render-pass, because the image may already be in general, or it could be restarting the RP from a render area change.
Regression from #7228.
Check affected gs dumps (e.g. King's Field).

GS/Vulkan: Fix condition for skipping first barrier

---

common/FileSystem.cpp
common/FileSystem.h
common/HeterogeneousContainers.h
pcsx2-qt/GameList/GameListModel.cpp
pcsx2-qt/GameList/GameListModel.h
pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/MainWindow.cpp
pcsx2/Frontend/CommonHost.cpp
pcsx2/Frontend/CommonHost.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/GameList.cpp
pcsx2/Frontend/GameList.h
pcsx2/Frontend/ImGuiOverlays.cpp

See title. Nothing fancy, it's just stored in a text file in the ini directory.
Personally: Sort by most recently played games, makes iterating quicker.
Test new feature.

Qt: Add play time tracking based on serials

---

common/GL/ContextWGL.cpp
common/ScopedGuard.h
common/Vulkan/Context.cpp
pcsx2-gsrunner/Main.cpp
pcsx2-gsrunner/test_run_dumps.py
pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtHost.cpp
pcsx2/Frontend/Achievements.cpp
pcsx2/Frontend/LogSink.cpp
pcsx2/Frontend/LogSink.h
pcsx2/Frontend/VulkanHostDisplay.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/x86/microVU_Misc.inl

First commit title is self-explanatory.
Second - if you had hardcore mode on, then turned achievements off, it'd still block you from resuming a state.
Third - Regression from #7176, dunno if it broke anything but it definitely wasn't corect.
Fixing my mistakes.
Very quick test based on the titles. Nothing serious, should be safe.

Few assorted regression fixes

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

purge DBZBT3 upscaling CRC hack
isnt needed snymore
check said game and make sure CI passes

GS-hw: purge DBZBT3 upscaling CRC hack

---

common/Linux/LnxHostSys.cpp
common/Linux/LnxMisc.cpp

Here are 3 patches necessary to build recent pcsx2 on FreeBSD. I've already updated the port upstream, see:
https://www.freshports.org/emulators/pcsx2/
Cheers,
Ganael.

Free bsd fixes

---

bin/resources/GameIndex.yaml

Gmaedb: add WRC4 patch to NTSC-J version
helps said game 
look at CI

GameDB: add WRC4 patch to NTSC-J version

---

pcsx2-qt/MainWindow.cpp

Qt: Add translate tag to shutdown message

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Invalidates local memory for render targets whose memory regions overlap with the requested one, instead of just checking for the same TBP.
Games like Shadow Hearts Covenant offset their GS downloads by specifying source Y coordinate that is beyond the texture size. Without this change, the game experiences semi-random rendering issues when displaying the Judgement ring in battle, as detailed in #3437. This PR essentially fixes that issue. 
While this PR fixes #3437, it could easily introduce new issues to other games, which is something that needs to be tested. For Shadow Hearts Covenant, enter a battle and try to attack/use skill or item, the game shouldn't display any black screen or wrong shots when the Judgement ring appears.

GS: Check memory overlaps with targets for GS downloads (Texture cache)

---

bin/resources/GameIndex.yaml

GameDB: add missing serial

---

bin/resources/GameIndex.yaml

add upscaling fixes to F1 2001/2002 and F1 Career Challenge

GameDB: add upscaling fixes to F1 2001/2002 and F1 Career Challenge

---

bin/resources/GameIndex.yaml

a more correct Gamedb
look at CI

GameDB: some minor corrections

---

bin/resources/GameIndex.yaml

GameDB:Fix minor typos

---

bin/resources/GameIndex.yaml

GameDB : add upscaling fixes to 'Headhunter - Redemption'
look at CI

GameDB : add upscaling fixes to 'Headhunter - Redemption'

---

pcsx2/CDVD/CDVD.cpp

Moves the rotational delay to the read following a seek, rather than being on the seek itself (not that it did anything)
The rotational delay was being skipped due to the delta being 0 on the read, and the seek didn't do any delay either, so it was kinda ignored.
Test CDVD timing sensitive games, see if they're improved/broken.

CDVD: Modify seek/rotational delay behaviour

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Checks if the surface has actually become invalid by the write, if so, delete it.
Code was added in #5349 for Destruction Derby Arena to get the correct area of a surface and set the exact parts which needed invalidating, unfortunately it doesn't then check if it's still valid after the write, where it does actually need deleting, which broke Onimusha Warlords, but it was masked by an accidental double flush in the Host->Local write function.
Test foggy stuff in Destruction Derby Arenas (have already but good to double check) and check Onimusha Warlords with texture preloading set to none or partial (there's a bug in full atm :( ) and make sure there's no repeating happening or partially transparent characters.
Test other stuff To I guess

GS-TC: Invalidate videomem still if surface becomes invalid

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Avoids doing a hardware mode of data which isn't on hardware.
Some games try to copy data from outside the texture, prime example being Fifa 2002. Usually this function will expand the texture to fit everything in on the destination side, but not the source, so this just makes sure we don't copy black void. but not only this, it can then expand the destination, so next time it tries this dirty trick, it thinks it DOES have the data.
Test FFXII shadows, make sure they're okay, and Fifa's main menu
Fixes #7378 Fifa 2002
Before:
After:

GS-TC: Don't shufflemove data which isn't in the texture.

---

pcsx2/GS/GSClut.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS: Fix Wsign-compare, Wunused-variable warnings.
Cleanup warnings.
Compiles.

GS: Warnings cleanup.

---

pcsx2/Frontend/ImGuiOverlays.cpp

Adds the last of the fixes to the ImGuiOverlay.
More information on what settings are on is always good especially hacks.
Make sure CI passes and that the settings display correctly.

ImGuiOverlays: Add missing fixes

---

bin/resources/GameIndex.yaml

Adds Round Sprite Full and Auto Flush to Shadow Hearts Covenant to help fix the position of monster sprites.
Sprites misaligned look gross lets try to fix that a bit.

GameDB: Add fixes for Shadow Hearts Covenant

---

pcsx2/Gif.cpp

Properly sets stalls for the correct DMA event when MFIFO stalls.
Fixes the case where the guest sets the PSE bit and tries to do a transfer with `Instant DMA` enabled. The transfer wouldn't succeed (the GIF is paused), but the DMAC emulation wouldn't know that and we'd be deadlocked, not allowing the EE to run (due to the transfer being 'instant').
I've also moved some logging I was seeing to DevCon, due to the fact that it's not helpful for end users.
It improves compatibility with `Instant DMA`
I've tested locally with homebrew and it fixes the deadlock I was experiencing.

GIF: Fix MFIFO DMAStalls. Fix InstantDMA with PSE bit set

---

bin/resources/shaders/dx11/interlace.fx
bin/resources/shaders/opengl/interlace.glsl
bin/resources/shaders/vulkan/interlace.glsl
common/Linux/LnxHostSys.cpp
pcsx2/GS/Renderers/Metal/interlace.metal
pcsx2/MemoryCardFolder.cpp
pcsx2/MemoryCardProtocol.cpp
pcsx2/MultitapProtocol.cpp
pcsx2/Sio.cpp
pcsx2/ps2/Iop/IopHwRead.cpp
pcsx2/x86/ix86-32/iR5900Templates.cpp
pcsx2/x86/ix86-32/recVTLB.cpp
pcsx2/x86/microVU_Macro.inl

Misc: Another batch of warnings cleanup.
Less warnings.
Compiles, warnings are gone in ci.

Misc: Another batch of warnings cleanup.

---

pcsx2-qt/Settings/InputBindingDialog.cpp
pcsx2-qt/Settings/InputBindingWidget.cpp
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/InputManager.cpp
pcsx2/Frontend/InputManager.h
pcsx2/Frontend/InputSource.cpp
pcsx2/Frontend/SDLInputSource.cpp
pcsx2/Frontend/SDLInputSource.h
pcsx2/Frontend/XInputSource.cpp

Allow use of buttons outside of normal defined GameController range
This might allow DS3s to use analog axes
Test DS3s and see if they can use analog axes

Input:SDL: Allow use of axes and buttons outside the normal range

---

pcsx2/Frontend/DInputSource.cpp

Fix broken builds
See if it builds successfully

Input:DInput: Fix build after adding FullAxis support for SDL

---

bin/resources/GameIndex.yaml

Gamedb: add fixes to 'Sega Rally 2006'

---

.github/workflows/windows_build_qt.yml
cmake/SearchForStuff.cmake
common/vsprops/QtCompile.props
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp

See title.
So Red stops asking.
Make sure Qt builds run.

Qt: Switch to 6.4.0 on Windows

---

bin/resources/GameIndex.yaml

fixes some graphical issues in game 
make sure CI  passes

GameDB: add fixes to 'Car Racing Challenge'

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h

See title.
I'm not sure what the point of it ever was..
Make sure compile succeeds.

GS/OpenGL: Remove disable_hw_gl_draw option

---

bin/resources/GameIndex.yaml

GameDB:Fixing some minor typos

---

pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiFullscreen.cpp

Going parent directory all the way up to the filesystem root previously didn't work on Linux.
And game fixes were showing regardless of the advanced setting mask being set. Makes it match Qt.
Consistency.
Test stuff mentioned above.

FullscreenUI: Fix root navigation on Linux and hide game fixes by default

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Makes sure if an old frame has already been perfectly matched and it finds another target that it is inside, make sure either end matches the pointer to properly identify a double buffer.
Shadow Hearts 2 was mis detecting false targets between scenes.
test stuff, make sure no new flickering happens.

GS-TC: Make sure if we have an old frame check bounds of other frame

---

pcsx2/CDVD/CDVD.cpp

Correctly sets the timing of DMA reads if the delta is very small and data is buffered.
It was possible to set a timing of 0 which just, doesn't work and is of course wrong, it should be the time the DMA takes to transfer a block at very minimum.
test games make sure they boot etc.
Fixes Haven - Call of the King regression from #7471

CDVD: Correct DMA timing if sectors are buffered.

---

common/RedtapeWindows.h

RedtapeWindows: Lowercase includes for linux fs

---

common/FileSystem.cpp

FileSystem: Use _stat64 routines

---

common/RedtapeWindows.h
common/Windows/WinMisc.cpp
common/Windows/WinThreads.cpp
pcsx2/CDVD/CDVDdiscReader.h
pcsx2/DEV9/DEV9.cpp
pcsx2/DEV9/DEV9.h
pcsx2/DEV9/Win32/tap-win32.cpp
pcsx2/DEV9/pcap_io.cpp
pcsx2/Frontend/D3D11HostDisplay.cpp
pcsx2/Frontend/D3D12HostDisplay.cpp
pcsx2/SPU2/SndOut_Cubeb.cpp
pcsx2/VMManager.cpp

Fixes **incorrect** casing from #7481. As well as slimming down the includes.
Faster compile times.
Make sure build succeeds.

Common: Slim down RedtapeWindows and correct case

---

pcsx2/GS/Renderers/SW/GSRendererSW.h
pcsx2/PAD/Windows/PAD.cpp
pcsx2/USB/usb-pad/dx/dinput-config.cpp
pcsx2/USB/usb-pad/raw/raw-config.cpp
pcsx2/USB/usb-pad/raw/usb-pad-raw.cpp
pcsx2/x86/iR3000A.cpp

Misc: Another batch of warnings, mostly codacy.
Less warnings.
CI builds, warnings are solved within codacy/ci.

Misc: Another batch of warnings, mostly codacy.

---

bin/resources/GameIndex.yaml

Fixes freezing and stuttering in MLB 2K5 and ghosting and vertical lines in Harry Potter Order of The Phoenix. 
No fixes is bad.

GameDB: Mixed fixes for games

---

pcsx2/MemoryCardFile.cpp
pcsx2/Sio.cpp

Misc: And another batch of warnings fixup.
Less warnings.
Compiles.

Misc: And another batch of warnings fixup.

---

.codacy.yaml

codacy: Exclude md files.
No need to run on md files, it pollutes us with useless warnings.
md files are ignored?

codacy: Exclude md files.

---

bin/resources/GameIndex.yaml

Adds EE full clamping for Shinobido
Game needs it
Check CI

GameDB: Add EE clamping for Shinobido - Way of the Ninja

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Just some minor UI changes.
Default should be specified for most settings if there is a default.
Make sure CI doesn't explode.

Qt: Tiny UI changes

---

bin/resources/GameIndex.yaml

correct naming  of some games 

GameDB: fix naming of Castlevania LoI games

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/PerformanceMetrics.cpp
pcsx2/PerformanceMetrics.h

What the title says. Can be useful in debugging stuttering/frame pacing issues.
Useful features without having to use external tools.
Test new feature.

ImGuiOverlays: Add frame time graph

---

pcsx2-qt/Settings/ControllerBindingWidgets.cpp

This was moved to the settings tab a while back.
Unnecessary code.
Make sure compile succeeds.

Qt: Remove dead code from ControllerBindingWidget_Base

---

bin/resources/GameIndex.yaml

Adds a comment to the game fix on P3 Fes to mention the flashing windows it fixes.
Comments are nice to know why things got added.

GameDB: Add comment for Mipmapping on P3 FES

---

pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp

Qt: Add tooltips to memcard checkbox options.
Adds missing tooltlips frop wx.
Tooltips work.

Qt: Add tooltips to memcard checkbox options.

---

bin/resources/GameIndex.yaml

fixed said game 
make sure ci passes

GameDB : add fixes to 'Conspiracy - Weapons of Mass Destruction'

---

bin/resources/GameIndex.yaml

GameDB: add VUclamping to 'NHL 2004'

---

bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/vulkan/convert.glsl
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/GS.h
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSRenderer.h
pcsx2/GS/Renderers/Metal/convert.metal
pcsx2/MTGS.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/SaveState.cpp
pcsx2/gui/AppConfig.cpp
pcsx2/gui/GlobalCommands.cpp
pcsx2/gui/Panels/ConfigurationPanels.h
pcsx2/gui/Panels/GSWindowPanel.cpp

And you can revert to the old un-aspect-corrected behaviour if you want to for some weird reason...
You also get the option of PNG or JPEG.
Zoom is gone because I needed more space in the page, and it was redundant with crop.
Decent looking screenshots.
Test new screenshot options.

GS: Add internal resolution screenshot option

---

pcsx2/GS/GS.cpp
pcsx2/GS/GSClut.cpp
pcsx2/GS/GSCodeBuffer.cpp
pcsx2/GS/GSExtra.h
pcsx2/GS/GSLocalMemory.cpp
pcsx2/GS/GSLocalMemory.h
pcsx2/GS/GSRingHeap.cpp
pcsx2/GS/Renderers/SW/GSRasterizer.cpp

Simplifies things since we don't need to care about <Win10 support now.
Also gets rid of vmalloc() in favor of the common routines.
Less duplicate code.
Test software renderer.

GS: Always allocate wrapped local memory

---

bin/resources/GameIndex.yaml

GameDB : add EE Nearest Rounding to Blood Omen 2

---

bin/resources/GameIndex.yaml

Adds round sprite to Violet no Atelier - Gramnad no Renkinjutsushi
Fixes text box alignment when upscaling
Check CI

GameDB: Add upscaling fix for Violet no Atelier

---

pcsx2/Frontend/OpenGLHostDisplay.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp

Was leaving the PBO bound, breaking regular uploads.
I broke it in with yesterday's GL changes.
Test covers in big picture mode with GL.

GS/OpenGL: Fix texture uploads in big picture mode

---

bin/resources/GameIndex.yaml

Adds missing entry's for Energy Airforce.
Missing entry bad.

GameDB: Add missing Energy Airforce entrys

---

bin/resources/GameIndex.yaml

GameDB: Add autoFlush to Syphon Filter - The Omega Strain

---

pcsx2/StateWrapper.h
pcsx2/USB/qemu-usb/qusb.h
pcsx2/USB/usb-eyetoy/videodev.h

Fixes build with GCC / without pch

Add some missing includes

---

pcsx2/Frontend/FullscreenUI.cpp

The sliders weren't appropriate for controller/keyboard navigation and incremented in large steps.
Test new crop dialog in big picture UI.

FullscreenUI: Use spinboxes for crop

---

common/HeterogeneousContainers.h
common/MemorySettingsInterface.cpp
common/MemorySettingsInterface.h

Needed for the GS runner.
It wouldn't build after the SDL hints PR.
None needed, since GS runner isn't built by the CI. But you can clone and build it yourself if you really want to :)

MemorySettingsInterface: Add {Set,Get}KeyValueList

---

pcsx2/USB/usb-hid/usb-hid.cpp

fixes some keyboard issues
look at ci

USB :fix some keyboard issues

---

bin/resources/GameIndex.yaml

Fixing weird vertical and horizontal artifacting while racing with round sprite half.
Less tinkering
Test Nascar Thunder 2003

GameDB: Nascar Thunder 2003

---

pcsx2-qt/Debugger/BreakpointDialog.cpp
pcsx2-qt/Debugger/CpuWidget.cpp
pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2-qt/Debugger/DisassemblyWidget.cpp
pcsx2-qt/Debugger/MemoryViewWidget.cpp
pcsx2-qt/Debugger/RegisterWidget.cpp

More translatable strings, more fun.
This change is made for adding new translatable strings
No broken strings in Debugger menus.

Translation: Add translation notation for all translatable strings in debugger

---

common/Pcsx2Defs.h

Add missing <cassert> include

---

README.md
pcsx2/Docs/README.md

README:update Technical Notes

---

.github/labeler.yml

was missed
make sure i haven't broken anything

actions: remove  WX in auto labeler

---

3rdparty/svn_readme.txt

Misc: update svn readme

---

bin/resources/GameIndex.yaml

GameDB: Update Utility Disc names

---

.github/workflows/scripts/macos/build-dependencies.sh

remove mention to wxWidgets in MAC build-dependencies
watch ci

CI : remove mention to wxWidgets in MAC build-dependencies

---

common/emitter/x86types.h
pcsx2/x86/iCore.cpp
pcsx2/x86/iCore.h
pcsx2/x86/iR5900Analysis.cpp
pcsx2/x86/iR5900Misc.cpp
pcsx2/x86/ix86-32/iCore-32.cpp
pcsx2/x86/ix86-32/iR5900Move.cpp
pcsx2/x86/microVU.cpp
pcsx2/x86/microVU.h
pcsx2/x86/microVU_Alloc.inl
pcsx2/x86/microVU_Branch.inl
pcsx2/x86/microVU_Compile.inl
pcsx2/x86/microVU_Execute.inl
pcsx2/x86/microVU_Flags.inl
pcsx2/x86/microVU_IR.h
pcsx2/x86/microVU_Lower.inl
pcsx2/x86/microVU_Macro.inl
pcsx2/x86/microVU_Misc.h
pcsx2/x86/microVU_Misc.inl

Bunch of stuff to make the micro mode VU recs faster.
Vroom vroom.
Find broken games. Probably a few.

Emotion Wars Part 2: The Vector Unit Strikes Back

---

bin/resources/GameIndex.yaml

SW CLUT fixes post processing and HPO Normal aligns the post processing.
The blur is absolutely disgusting and deserves to be fixed.

GameDB: Add SW CLUT to The Incredibles

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp

UI/AudioSettings: Correct recommended value for overlap

---

pcsx2/x86/microVU.cpp
pcsx2/x86/microVU_IR.h

Fixes hang going ingame in Gitaroo Man.
Regression from #7599.
Test Gitaroo Man.

x86/microVU: Fix incorrect VI being backed up when uncached

---

pcsx2/x86/microVU_Execute.inl

Saves reloading it when the EE and VU0 rounding modes are the same.
Minuscule better codegen.
Check a couple of games with gamedb round mode changes, make sure no SPS soup says hello. But should be fine.

x86/microVU: Only update MXCSR when it's different

---

bin/resources/GameIndex.yaml

GameDB: remove SoftwareRendererFMVHack from Onimusha - Dawn of Dreams

---

.github/workflows/scripts/macos/build-dependencies.sh

gh-workflows-macos: Remove leftover wx dependencies.
Also remove qt gui check since it's the only gui we use.
wx.
ci builds.

gh-workflows-macos: Remove leftover wx dependencies.

---

pcsx2/GS/Renderers/DX12/GSDevice12.h

See title.
Leftovers which were never deleted.
Make sure build passes.

GS/DX12: Remove undefined functions from header

---

pcsx2/x86/ix86-32/iR5900-32.cpp

In all cases except for GetOsdConfigParam/GetOsdConfigParam2 the HLE syscall handler will raise the CPU exception, changing the PC.
So, there's no point compiling the rest of the block, especially when it may contain garbage code. No point checking the PC either, as in almost every case, it will have changed. So just go straight to the dispatcher.
Note this will have a slight behavioral change - both SYSCALL/BREAK will check the cycle count for an event test now, whereas before only BREAK did. But I doubt this'll cause any issues.
Fixes #4543.
Test This is Football, but also a few other random games and make sure performance wasn't affected (it shouldn't be).

x86/iR5900: Always break rec blocks on SYSCALL/BREAK

---

bin/resources/GameIndex.yaml

GameDB: add fixes to Syphon Filter - The Omega Strain

---

pcsx2/CDVD/GzippedFileReader.cpp

removes commented out WX code
make sure ci builds

GzippedFileReader : remove commented out WX code

---

.gitignore

removes wx mentions in gitgnore
make sure ci builds

gitignore: remove wx mentions

---

pcsx2-qt/pcsx2-qt.vcxproj.filters

remove missed  wx vs filters
not needed anymore
make sure i havent broken  vs filters

Misc : remove missed  wx vs filters

---

pcsx2/MemoryCardFile.cpp
pcsx2/MemoryCardFile.h
pcsx2/MemoryCardFolder.h

Remove commented out WX code
not needed anymore
make sure ci builds

memory card: Remove commented out WX code.

---

bin/resources/GameIndex.yaml

GameDB:: fixes for 'Obscure II - The Aftermath'

---

pcsx2/Frontend/FullscreenUI.cpp
pcsx2/SPU2/spu2.cpp

See commit titles.
It was wrong.
YOLO

Fix volume on startup / threaded presentation title

---

common/emitter/cpudetect.cpp
pcsx2/System.cpp

Removes old unused bits of code or extensions that are no longer used or never got used in the first place.
Cleaning up old code is good.

Misc: Remove old and unused code

---

bin/resources/GameIndex.yaml

 GameDB: fixes for Hawk Kawasaki Racing

---

bin/resources/GameIndex.yaml

GameDB: fixes for Battle for Volcano Island

---

bin/resources/GameIndex.yaml

help said game 
watch ci check said game

GameDB: fixes for Made Man

---

.github/workflows/scripts/linux/appimage-qt.sh
.github/workflows/scripts/linux/functions.sh
.github/workflows/scripts/linux/install-packages-qt.sh

The Azure Ubuntu package server, in particular, seems to be very unreliable. Hopefully within 10 attempts it'll complete the package download in such cases.
Hopefully stopping the random failures.
Make sure CI for Linux completes successfully.

CI: Retry downloading commands on Linux

---

pcsx2/Dmac.cpp

Fixes tutorial level in Naruto - Uzumaki Chronicles.
Regression from #7678.
Test Naruto.

Dmac: Fix incorrect condition for OPH flag hack

---

pcsx2-qt/Debugger/CpuWidget.cpp
pcsx2-qt/Debugger/CpuWidget.h

Fix regression from #7777
It should work 👍 
Test step out

Debugger: Fix step out

---

pcsx2/SPU2/SndOut.cpp

Regression from a603aed7dbaba2ee478eaa1cb2bf1872adcd282c

SPU2: Fix sound output

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Adds more text descriptions for various options to help understand what a setting does better.
_Also nicked a few from Duckstation sorry Sten._
More descriptions for options are better.

UI: More text descriptions for options

---

pcsx2-qt/Debugger/DebuggerWindow.cpp
pcsx2-qt/MainWindow.cpp
pcsx2/DebugTools/Breakpoints.cpp
pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DebugInterface.h
pcsx2/R5900OpcodeImpl.cpp
pcsx2/R5900OpcodeTables.h

Executes the ELF /  Game and pauses once the entry point is executed
(Sound on)
https://user-images.githubusercontent.com/29295048/212521820-47db5689-ea2f-4606-ade4-683ac63b73ad.mp4
Another neat feature for modders and reverse engineers
Try using the boot and debug context menu option in the game list

Debugger: Implement boot and debug

---

bin/resources/GameIndex.yaml

Fixes slight blur on people and depth bleed that happens on the right hand side.
"Johnny looks like he could use some HPO"
Make sure the CI is happy boi.

GameDB: Add HPO Normal to WWE 2008 and 2009

---

bin/resources/GameIndex.yaml

GameDB: fixes for 'Dreamworks Madagascar'

---

bin/resources/GameIndex.yaml

upscale  fixes for 'Lord of the Rings, The - The Two Towers'
watch ci

GameDB: upscale  fixes for 'Lord of the Rings, The - The Two Towers'

---

bin/resources/GameIndex.yaml

GameDB: upscaling fixes for 'TOCA Race Driver'

---

bin/resources/shaders/vulkan/tfx.glsl

GS-vk: Fix sample_4_index shader.
Macro conditions conditions should return a value.
Fixes bad shader issues on games that trigger it.
Fixes Star Ocean shadows.
Fixes bad shader issues on games that trigger it.
Fixes Star Ocean shadows.
Fixes Keroro Gunsou - Mero Mero Battle Royale text.
Test Star Ocean, Keroro Gunsou - Mero Mero Battle Royale.

GS-vk: Fix sample_4_index shader.

---

bin/resources/GameIndex.yaml

Adds a missing fix for the NTSC-U version of the game.
Self explanatory. 

GameDB: Add missing Bratz The Movie fix

---

.github/labeler.yml

labeler: Add labels to shader files changes based on renderer.
Better auto labeling.
N/A

labeler: Add labels to shader files changes based on renderer.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

GS-hw: Cleanup GS memory clear.
Create IsConstantDirectWriteMemClear function to reduce code duplication and making code cleaner.
Cleanup, reduces code duplication.
Gs memory clear still works.

GS-hw: Cleanup GS memory clear.

---

bin/resources/GameIndex.yaml

GameDB: fixes for 'Snowboard Heaven'

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Don't optimise clamps on texture/channel shuffle
Time Crisis 2 was a victim of this, the clamps were being optimised to only read 1 page of data, but it was a shuffle which we optimise to dot he whole screen, so it ended up shuffling everything in to the top left. So we need to check if this is a shuffle before we try to optimise the clamps.
True Time Crisis 2, especially the GS Dumps in the issue linked below.
Fixes #5966
Before:
After:

GS-HW: Don't optimise clamp on shuffle

---

bin/resources/GameIndex.yaml

Fixes for black loading screens and misaligned bloom.
Brokeness is bad for the soul.

GameDB: Fixes for TC SC Pandora Tomorrow

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GT4 does a bunch of transfers next to a render target during some of the screen transitions, which leads to the RT blowing out to 2000+ high at 1x (and probably 16k+ at 8x).
So, instead, we'll limit the expand logic to only do so when the PSM matches, as then it's likely to actually be needed (e.g. for a FMV).
I've checked Castlevania and it doesn't seem to be any more broken than master (i.e. it'll break with a gs dump/state, but booting from scratch is fine). Also did a runner pass.
Blowing up VRAM usage isn't ideal, nor is the wasted bandwidth when clearing.
Check VRAM usage with GT4 at high upscale.

GS/TextureCache: Only expand target on write on TBW match

---

bin/resources/GameIndex.yaml

clean up comments  in the GameDB
N/A , watch ci

GameDB:  clean up comments

---

pcsx2/Frontend/DInputSource.cpp
pcsx2/Frontend/DInputSource.h

Support for up to 128 buttons using DInput

DInput: Support for up to 128 buttons

---

.github/workflows/linux_build_matrix.yml
.github/workflows/linux_build_qt.yml
.github/workflows/macos_build.yml
.github/workflows/release_pipeline.yml
.github/workflows/scripts/common/name-artifacts.sh

We have multi-isa builds, now we just have to publish them
Do not merge until #7532 has been merged for long enough that most users running auto update have it
Test the release pipeline (@xTVaser)

GHActions: Update release pipeline for MultiISA

---

bin/resources/GameIndex.yaml
pcsx2/Docs/README.md

Fixes to names of games depth line fixes and misaligned bloom galore.
Names being wrong is gross depth lines also gross and misaligned bloom is just the worst.

GameDB: A variety of fixes

---

bin/resources/GameIndex.yaml

Uses the correct flag instead of a spooky question mark.
Self explanatory. 

GameDB: Correct use of Norway PAL code

---

pcsx2-qt/QtHost.cpp
pcsx2/GSDumpReplayer.cpp

See title.
Fixes #7976.
Already tested, change is obvious.

Qt: Fix GS dump frame limit / -nogui/-batch

---

bin/resources/GameIndex.yaml

No texture preloading for Harry Potter and the chamber of secrets to improve performance.
Bad performance is bad.
Test any variant of the game. (There are 11 variants)

GameDB: Harry Potter and the Chamber of Secrets

---

bin/resources/GameIndex.yaml

GameDB:fixes for Dragon Quest VIII - Journey of the Cursed King

---

bin/resources/GameIndex.yaml

GameDB: fixes for Megaman X Command Mission

---

pcsx2/GS.cpp
pcsx2/GS.h
pcsx2/Gif_Unit.cpp

fix my stuff
I'm a dumbass
No need

GS: Correct GSIMR/GSCSR reg init, regression from previous release

---

bin/resources/shaders/opengl/tfx_fs.glsl

Triggers somewhere in the gs runner...
Whoops
Issue is obvious, safe to merge.

GS/OGL: Fix syntax error in fragment shader

---

.github/labeler.yml

Beats doing it manually labels for Rcheevos.
Less manual handholding and more categorisation
Make PR in future.

CI: Add RetroAchievements/Rcheevos labels for PRs

---

.github/labeler.yml
pcsx2-qt/MainWindow.cpp
pcsx2/Counters.h

remove old comments
Add labels for Translations
watch ci

Misc : label & comment fixes

---

bin/resources/GameIndex.yaml

Fixes the name of GT-R 400 and adds round sprite to fix lines in menus and text and corrects the name of 40k Fire Warrior to correctly have a space.
The db is a mess and so is my life.

GameDB: Assorted fixes

---

bin/resources/GameIndex.yaml

GameDB: fixes for 'Tom & Jerry - War of the Whiskers' & 'Brave - The Search for Spirit Dancer'

---

bin/resources/GameIndex.yaml

Fixes vertical lines.
Lines bad.

GameDB: Add Align Sprite to Football Kingdom

---

bin/resources/GameIndex.yaml

Fixes for Transformers The Game to fix bloom and mipmapping issues and add missing db entry's.
Missing stuff bad.

GameDB: Various small fixes

---

bin/resources/GameIndex.yaml

Adds missing fixes for other entry's of The Godfather.
Red is a silly goose and forgot to add these.

GameDB: Add missing The Godfather fixes

---

pcsx2/GS/Renderers/Common/GSDirtyRect.cpp
pcsx2/GS/Renderers/Common/GSDirtyRect.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Separate dirty rect processing, but also try to fix a ton of TC bugs I came across along the way.
Processing all dirty rects as one huge rect could invalidate valid data, causing the TC to consume bad data.
Test everything you can, make sure nothing is broken.
Fixes #2026
Stuff it fixes:
Ape Escape (3 maybe?)
Master:
PR:
Dragon Quest VIII:
Master:
PR:
Jak 3:
Master:
PR:
Kingdom Hearts:
Master:
PR:
Test Drive Unlimted:
Master:
PR:
Wild Arms 4 (PAL mode selection):
Master:
PR:
Zone of Enders 2 (Possibly):
Master:
PR:

GS-HW: Process dirty rects separately, improved Tex in RT compatibility

---

pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp

See commit descriptions.
Closes #8074.
Test Gradius and Densha De Go GS Dumps.

GS/OGL: Fix broken readbacks and potential upload crash

---

bin/resources/GameIndex.yaml

GameDB: Add Autoflush hw fix to MGS3 Subsistence.
Fixes lens flare.
Fixes #8081
Test the dump in the linked issue.

GameDB: Add Autoflush hw fix to MGS3 Subsistence.

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Be more strict with what invalidation dirty's different format textures and which ones just erase.
I broke Dragon Quest 8 with this by trying to erase them less, this is all heuristics (always has been), but it's very difficult to tell when writes are replacing a texture with a new one, or just writing partial textures in a different format.
Test anything, including Dragon Quest 8.

GS-HW: On overwrite of large incompatible format texture, erase old.

---

pcsx2/PAD/Host/KeyStatus.cpp
pcsx2/PAD/Host/PAD.cpp

Deadzone was being read as sensitivity, and had no actual effect.
me big fail
Tested myself, but check the code, it's fairly obvious what the issue was.

PAD: Fix trigger deadzone/scale setting

---

pcsx2-qt/Debugger/Models/StackModel.cpp
pcsx2-qt/Debugger/Models/ThreadModel.cpp
pcsx2-qt/Debugger/Models/ThreadModel.h
pcsx2/DebugTools/BiosDebugData.cpp
pcsx2/DebugTools/BiosDebugData.h
pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DebugInterface.h
pcsx2/IopBios.cpp
pcsx2/R5900OpcodeImpl.cpp
pcsx2/ps2/BiosTools.cpp
pcsx2/ps2/BiosTools.h

Implements reading IOP threads and creates an abstraction for the GUI to use for both EE and IOP threads.
IOP debugger needs love.
Check if the debugger broke or not.

Debugger: Implement thread listing for IOP

---

pcsx2/DebugTools/BiosDebugData.h

Debugger: Fix missing return path.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Vaguely (probably wrongly, let's be honest :P) supports copying 16bit source in to a 32bit target with a shuffle.
This one is a bit of a weird one and this is probably going to take some iteration to get perfectly right, but in the cases below it seems to work absolutely fine.
Test stuff, make sure it's not broken.
AFL Premiership 2007
Master:
PR:
Gaelic Games: Football
Master:
PR:
Not a huge fix but gets rid of the corner stripes
NFS Undercover:
Master:
PR:

GS: Detect 16bit source copy in to 32bit target shuffle

---

common/Vulkan/Context.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/R5900OpcodeImpl.cpp

But only for local memory sources (not targets), it causes issues with upscaling otherwise.
Less GPU load.
Test capcom games (e.g. #5851). I've checked the dumps in that thread, they seem okay.

GS/HW: Use sampler for clamp/repeat when it's redundant

---

bin/resources/GameIndex.yaml

not needed anymore  , the issue was fixed 
watch ci go brrrrr

Gamedb: remove skipdraw from Need for Speed - Undercover

---

pcsx2/Frontend/InputManager.cpp

Regression from #7910.
Having working scrolling in the big picture game list is nice.
Test scrolling in game list (done myself).

InputManager: Restore passing wheel events to ImGui

---

bin/resources/GameIndex.yaml

Fixes sun occlusion in V-Rally 3 and fixes missing subtitles in FMVs in Berserk.
The sun hurts my eyes.

GameDB: Fixes for V-Rally 3 and Berserk

---

bin/resources/GameIndex.yaml

Some fixes I missed in the last PR because I am a doughnut and can't remember what I needed to do.
No mipmapping looks gross and graphical corruption is very naughty.

GameDB: Fixes for UEFA 04-05 and Freestyle BMX 2

---

pcsx2/Counters.cpp

Sometimes great ideas don't always go smoothly to plan, this is one of those, but it will be back when we work out what's up with Soul Calibur 2 and DBZ BT3 :)
Stuff broke that we didn't catch, and we're not currently sure why, so need to investigate.
Check the CI passes

GS: Partial revert of #8101 pending investigation.

---

bin/resources/GameIndex.yaml

Lines bad must fix lines.
Lines should not be in cutscenes.

GameDB: Add HPO Special to 007 EON

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

its not needed anymore 
check Metal Slug 6 and check if CI passes

GS-HW:purge MetalSlug6 CRC

---

bin/resources/GameIndex.yaml

Fixes #2612
there is a problem in credits screen.
EETimingHack fixes it.
already tested and it worked.

GameDB: Add EETimingHack to Crazy Taxi

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

isnt needed  anymore 
test said game , make sure ci builds

GS-HW: remove Fighting Beauty Wulong & Spartan Total Warrior CRC

---

bin/resources/GameIndex.yaml

Rename Europe serial and fix offset and blooming.
- Upscaled, no fixes:
- Normal (Vertex):
- Only CPU clut:
- CPU clut + Normal (Vertex) Halfpixel offset:
- Software Renderer:
Less tinkering
Test Ruff Trigger

GameDB: Ruff Trigger

---

bin/resources/GameIndex.yaml

Fixes misaligned bloom that looks gross.
Bloom gross.

GameDB: Add HPO Special to Arthur and the minimoys

---

common/Linux/LnxHostSys.cpp
pcsx2/Frontend/CommonHost.cpp

Hello,
Here are two small changes that fixes build (and usage) on FreeBSD. Those patches are part of the latest port update I just made, see:
https://cgit.freebsd.org/ports/tree/emulators/pcsx2/files
Thanks,
Ganael.

FreeBSD fixes

---

bin/resources/GameIndex.yaml

GameDB : remove skipdraw  from  Need for Speed - Undercover

---

bin/resources/GameIndex.yaml

Gamedb: update Armored Core - Nexus

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fixes downloads which are using an offset base pointer or different widths
This wasn't handled at all, and actually ignored when the BP was higher than the TBP of the texture, the rect for the different width (BW) wasn't corrected for so not all the data was downloaded, so my recent changes to only download bits it needs broke things in Final Fantasy and Chaos Legion, it only worked before because it was forcing entire rect downloads, which happened to be enough.
Test the FFX pause screen, chaos legion (when it does Readbacks, usually when the screen gets flooded with white), and any other games doing readbacks.
FFX:
Master:
PR:
Chaos Legion:
Master:
PR:

GS-HW: Fix downloads in offset BP and different widths

---

pcsx2/GS/GSState.h

Handle extended height when there's a negative offset.
This was omitted from the PCRTC rewrite.
Test Salt Lake 2002 or Hokuto no Ken, especially in software.

GS-PCRTC: Handle extended height when there's a negative offset

---

pcsx2/USB/usb-pad/usb-seamic.cpp

Fix Sega Seamic buttons
closes #8154

USB: Fix Sega Seamic buttons

---

bin/resources/GameIndex.yaml

The clown now has more colors now.
Adds texture inside RT which helps a specific area with the clown.
- Before:
- After:
Less tinkering

GameDB: Dark Cloud 2 + Dark Chronicle

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS-tc: Fix Wreorder-ctor warning.
Fix tc warning.
Compiler warning is gone from ci.

GS-tc: Fix Wreorder-ctor warning.

---

bin/resources/GameIndex.yaml

GameDB:  remove disable partial invalidation from fatal frame

---

bin/resources/GameIndex.yaml

Forces Adaptive TFF to stop bouncing/shaking vertical screen.
- Before:
https://user-images.githubusercontent.com/24227051/221389598-ae1896ea-0bd3-409a-925c-a955e46085d8.mp4
- After:
https://user-images.githubusercontent.com/24227051/221389601-8bd59f37-f425-4326-9ffc-2ea331d8bd3f.mp4
Test Nascar 06.

GameDB: NASCAR '06 Total Team Control

---

bin/resources/GameIndex.yaml

fixes grphical issues  
watch CI

Gamedb: remove  HPO normal from Dragon Ball Z Budokai - Tenkaichi 2

---

bin/resources/GameIndex.yaml

fixes #8222
and add some missing serials 
watch CI

GameDB: various fixes

---

bin/resources/GameIndex.yaml

GameDB: add textureInsideRT to NBA '07 featuring The Life Vol.2

---

bin/resources/GameIndex.yaml

GameDB: upscaling fixes for Springdale

---

bin/resources/GameIndex.yaml

GameDB: add fixes to Knight Rider - The Game

---

bin/resources/shaders/vulkan/convert.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

None of these were errors, but it's still good to have clean output.
Making validation layer shush.
Test a game with vulkan, make sure it ain't broke. Runner says it's okay.

GS/Vulkan: Fix a bunch of validation warnings

---

bin/resources/GameIndex.yaml

Fixes for rainbowing at the edges of the screen missing bloom intensity and alignment and reflections on water and ground textures.
This game sucks and radiosity was a mistake.

GameDB: Gun fixes

---

bin/resources/GameIndex.yaml

- Steambot Chronicles has quite an extensive hack for a game doing weird stuff with their Z-buffer, it does mess with the sea being green which is incorrect but the game also looks off for the rest of the cutscene. This change WILL NOT AFFECT ANYTHING if you use CRC Hack, easy to recognise that software renderer has fog but hardware renderer never does on any setting.
- Default HW with CRC hack:
- Hardware Renderer with CRC level fix disabled:
- Hardware Renderer with CRC level fix disabled and half roundsprite (to fix 3D anaglyph bleed):
Relevant pictures:
- Weird effect:
- Hardware renderer without CRC Hack:
- Software Renderer:
- One more with CRC Disabled:
- Initial Scene with Software Renderer:
- Initial Scene with Hardware Renderer Defaults:
- misalgined typo to misaligned
Less …

GameDB: Steambot Chronicles + typo fix

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

remove not needed CRC and add upscaling fixes
watch CI

GS/CRC: purge Oneechanbara2Special CRC

---

bin/resources/GameIndex.yaml

fixes the FMVs for said game 
watch CI

GameDB: add fixes to Crouching Tiger, Hidden Dragon

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Align page aligned end blocks to page boundaries, especially for Z formats, where block ordering leaves it half way through a page.  Pulled out of #8289 as it's needed for other things.
end block is used to decide if invalidation amongst other things is inside a texture, and if the format has changed (for example C32 instead of Z32), the block order is different and the end block can end up too low, causing the "overlap" check to fail. This make sure the "used" blocks are all covered.
Shouldn't need testing, done a GS dump run for prosperity.

GS-Hw: Correct page aligned end blocks

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes crash in Radiata Stories.
Fixes #8378.
Test Radiata Stories (start game, wait for FMV to finish).

GS/HW: Move old-target invalidation to after draw

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Qt: Fix crash when changing renderer

---

pcsx2/Frontend/FullscreenUI.cpp

Move CRC hack, paltex, hide manual fixes by default.
Consistency with Qt settings UI.
Make sure manual fixes is gone from global settings in big picture UI.

FullscreenUI: Mirror Qt graphics settings changes

---

pcsx2/GS/Renderers/OpenGL/GLState.cpp
pcsx2/GS/Renderers/OpenGL/GLState.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp

- ~~Commented all the `available_vram` out~~
- Removed all the `available_vram` parts
- Discussed in #8367 
- I'm not sure

GS-OGL: Remove available_vram

---

bin/resources/GameIndex.yaml

GameDB: fixes for Biker Mice from Mars

---

bin/resources/GameIndex.yaml

fixes game soft lock 
fixes  #8401
fixes #6988
fixes #8405 
fixes  #8406
test said game , watch CI

 GameDB: add fixes for Lupin III - Columbus no Isan wa Akenisomaru and fix game names

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

make sure ci passes & check said game

GS/CRC : purge Yakuza CRC hack

---

bin/resources/GameIndex.yaml

its not needed anymore 
watch CI

GameDB: remove SoftwareRendererFMVHack from Siren 2

---

bin/resources/GameIndex.yaml

GameDB: fixes for True Crime - Streets of L.A.

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui

Regression from 2b49614df935bfd383e893bce93171e8b224e01e

Qt: Fix graphics settings opening to other pages

---

bin/resources/GameIndex.yaml

GameDB: fixes for Metal Gear Solid 3  Snake Eater

---

pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp

Precaching option never really worked properly, it injected everything into the hash cache, regardless of whether it was requested, which can easily lead to running out of VRAM.
This PR changes the behaviour so it only loads to RAM/the cache list, not the GPU.
**You still shouldn't use this option.** Loading is asynchronous and won't cause hitches in the first place. It's only really there if you have a really slow hard drive, and tons of RAM.
Running out of VRAM and having a mess of half loaded texture replacements isn't nice.
Test texture replacements with and without precaching.

GS/HW: Fix texture replacement precaching option

---

pcsx2/Frontend/CommonHotkeys.cpp
pcsx2/Frontend/FullscreenUI.cpp

Makes the no achievements config build again
Fixes #8457
Successfully building is good
@DNDEBUG @LeCharlatan please test

UI: Fix build with achievements disabled

---

bin/resources/GameIndex.yaml

Fixes broken pause menu.
Before:
After:
Check CI.

GameDB: Ratchet & Clank 1&2

---

bin/resources/GameIndex.yaml

GameDB: fixes for various games

---

bin/resources/GameIndex.yaml

Adds the text fix to WWE 2007 to 2010
text bad not good
ci happy good

GameDB: More WWE text fixes

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

What the title says. Also documents what it's doing.
Regression from https://github.com/PCSX2/pcsx2/pull/8209.
Test GT4 and T5 in DirectX renderers.

GS/HW: Fix GT4/T5 CRC hacks in DirectX renderers

---

bin/resources/GameIndex.yaml

To help alleviate text misalignment and glitches when upscaling
Dump:
[sw2.zip](https://github.com/PCSX2/pcsx2/files/11101183/sw2.zip)

GameDB: Add roundsprite to Samurai Warriors 2

---

3rdparty/rainterface/CMakeLists.txt
cmake/SearchForStuff.cmake
pcsx2/CMakeLists.txt

Title
Closes #8517
Test -raintegration parameter

CMake: Enable RAIntegration on Windows builds

---

bin/resources/GameIndex.yaml

GameDB: fixes for Super Trucks Racing

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Handles large memory clears made of triangles without creating nonsense render targets.
Dropship does 2 huge triangle draws to clear a 2048x2048 (16mb) area of memory, which it was mistakenly making a massive texture for, and causing crashes.  It was massively wrong anyway, so now we're just avoiding it.
Try Dropship in DX11 and OGL (already done), also had done a GS Dump run of over 1000 GS dumps.

GS-HW: Handle triangle memory clears

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml

updates issue template to let users know that the patches  repository exists 
its better to have Widescreen/no-interlace  issues in one place rather than  over  2 repositories  
N/A

Github: Update issue template

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Copies suck. I missed the half_right case in my other PR.
Fewer copies.
Check snowblind games.

GS/HW: Allow region targets for half-right fix

---

pcsx2-gsrunner/test_run_dumps.py

GSRunner: Don't skip dumps with dots in their filename

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/EmulationSettingsWidget.cpp

Fixes menu transparency when using high blending also changes the wording on MTVU to prevent further confusion.
Silly arguments over words are silly.

GameDB: Soulcalibur 2&3 blending recommendations

---

common/Vulkan/Context.cpp
common/Vulkan/Context.h
common/Vulkan/SwapChain.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Nothing super risky here, but still invalid nonetheless.
We shouldn't be submitting invalid GPU commands.
Go ingame in a couple of games with Vulkan renderer, make sure it still works.

GS/Vulkan: Fix a bunch of validation errors

---

pcsx2/GS/GSExtra.h

GS: Warning fix

---

bin/resources/GameIndex.yaml

fixes for Dark cloud
Fixes #8689
test Dark Cloud

GameDB: fixes for Dark cloud

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp

What the tile says.
UB-chan says hi.
yolo

GS/HW: Fix missing init of non-CLUT replacement textures

---

bin/resources/GameIndex.yaml

fixes said game in HW mode 
watch CI

GameDB : fixes for Hanjuku Hero 4

---

pcsx2/CDVD/InputIsoFile.cpp

fixes a small error in a console output 
when it gives errors you should see what is causing the error
load up the emulator with the console on and the automatic directory scan should work with full file names in errors

CDVD: Fix Error Message in InputIsoFile.cpp

---

bin/resources/GameIndex.yaml

Fixes glitched ground texture in Air Ranger: Rescue Helicopter (All region/version)
SW:
HW (Glitched, Master):
HW (Fixed, PR):
Real PS2:
GSdump:
[GSD.zip](https://github.com/PCSX2/pcsx2/files/11296743/GSD.zip)
glitched texture is bad.
Tested as written above.
I only tested SLPS-20083

GameDB: Fixes for Air Ranger: Rescue Helicopter

---

bin/resources/GameIndex.yaml

Fixes for vertical lines in Ring of Red and invisible text in Dynasty Warriors 2.
Fixes #8285 
Big stupid line bad.

GameDB: Ring of Red fixes

---

pcsx2/Docs/GameIndex.md
pcsx2/Docs/gamedb-schema.json

adds missing gamefix
It was missing
watch CI

GameDB: Add FullVU0SyncHack to the linter

---

pcsx2/GS/GS.cpp
pcsx2/GS/GSPerfMon.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Also gets rid of some redundant pointer chasing in Metal (since I moved that stuff from HostDisplay to GSDevice).
Can be useful in diagnosing bad performance.
Check new stat.
Make sure Metal still works.

GS: Add Render Pass stats

---

bin/resources/GameIndex.yaml

Fixes for broken player textures and some missing fixes.
Broken texture bad.

GameDB: Various FIFA 2001-2004 fixes

---

bin/resources/GameIndex.yaml

Fixes for grass rendering to match software with mipmapping and trilinear filtering.
Ugly grass begone,

GameDB: Disney Golf Fixes

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Updates any dirty areas of a texture if it's in the area to be downloaded, also ignore dirty parts which are outside the read area.
Van Helsing was downloading 640x112 of a texture, then dirtying the start, then reading an offset amount, which was failed due to it not allowing you to download anything which is dirty at all.
Splashdown also updated parts of textures then tries to invalidate parts of memory those are in so, we need to update the texture before the read.
Test Splashdown and Van Helsing, plus any other games which do readbacks to make sure nothing broke.
Note for Splashdown: You need to be in native resolution (it will crash otherwise) and you need to toggle software mode going ingame for this to work, it's kinda working by luck in this PR but it gets complicated, so this is …

GS-TC: Update dirty read overlap on local mem invalidate

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Never going to get this right at this rate...
Did it actually work before?
@JordanTheToaster

GS: Fix hang when switching renderer while fullscreen

---

common/Vulkan/Context.cpp
common/Vulkan/Context.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Hopefully stops a crash on broken drivers.
Less code.
Make sure adapter selection still works in Vulkan.

GS/Vulkan: Simplify GPU selection

---

pcsx2/x86/ix86-32/iR5900-32.cpp

God of War 2 and other games (e.g. NFS series) have these timeout loops which just spin for a few thousand iterations, usually after kicking something which results in an IRQ, but instead of cancelling the loop, they just let it finish anyway. Such loops look like:
```
00186D6C addiu  v0,v0, -0x1
00186D70 nop
00186D74 nop
00186D78 nop
00186D7C nop
00186D80 bne    v0, zero, ->$0x00186D6C
00186D84 nop
```
Skipping them entirely seems to have no negative effects, but we skip cycles based on the incoming value if the register being decremented, which appears to vary. So far I haven't seen any which increment instead of decrementing, so we'll limit the test to that to be safe.
Reduces EE thread CPU usage by up to 40% when not VU bottlenecked in God of War 2.
Test GOW2, and see if any other …

x86/iR5900: Fast forward timeout loops

---

bin/resources/GameIndex.yaml

was missed last time 
@ccwcm91 please check

GameDB: Fixes for Shin Sangoku Musou Series Collection Joukan

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Introduced in #8767.
Crash bad
@Mrlinkwii

Qt: Fix crash in graphics settings on Linux

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp

GS: Cleanup GSRenderer.
Constants, casting.
Cleaner code.
GS works as expected, CI compiles.

GS: Cleanup GSRenderer.

---

bin/resources/GameIndex.yaml

Fixes for the sun going through buildings.
Master:
PR:
The sun poking it's head through buildings is bad it shouldn't be doing that.

GameDB: True Crime LA Fixes

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui

Qt: Sort checkbox upscale and renderer hw hacks in alphabetical order.
Cleaner look, they used to be in order before.
Display as intended.

Qt: Sort checkbox upscale and renderer hw hacks in alphabetical order.

---

bin/resources/GameIndex.yaml

Fixes for broken headlights and enforcing high blending for more accuracy.
Game work better look better. More gooder :)

GameDB: More Juiced 1 FIxes

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/VKContext.h
pcsx2/GS/Renderers/Vulkan/VKSwapChain.cpp
pcsx2/GS/Renderers/Vulkan/VKSwapChain.h
pcsx2/GS/Renderers/Vulkan/VKUtil.cpp
pcsx2/GS/Renderers/Vulkan/VKUtil.h

Can make things slightly less messy now that it's out of common.
Less code.
Make sure Vulkan still works, fullscreen transitions, vsync on/off, that kinda thing.

GS/Vulkan: Simplify and refactor swap chains

---

pcsx2/SPU2/ADSR.cpp
pcsx2/SPU2/Debug.cpp
pcsx2/SPU2/Debug.h
pcsx2/SPU2/Dma.cpp
pcsx2/SPU2/Dma.h
pcsx2/SPU2/DplIIdecoder.cpp
pcsx2/SPU2/Global.h
pcsx2/SPU2/Mixer.cpp
pcsx2/SPU2/Mixer.h
pcsx2/SPU2/ReadInput.cpp
pcsx2/SPU2/Reverb.cpp
pcsx2/SPU2/SndOut.cpp
pcsx2/SPU2/SndOut.h
pcsx2/SPU2/SndOut_Cubeb.cpp
pcsx2/SPU2/SndOut_XAudio2.cpp
pcsx2/SPU2/Wavedump_wav.cpp
pcsx2/SPU2/defs.h
pcsx2/SPU2/interpolate_table.h
pcsx2/SPU2/regs.h
pcsx2/SPU2/spdif.h
pcsx2/SPU2/spu2.cpp
pcsx2/SPU2/spu2.h
pcsx2/SPU2/spu2freeze.cpp
pcsx2/SPU2/spu2sys.cpp

SPU2: Cleanup spu2.
Constants, initializations, casts, switch cases not handling default case, unused functions.
Cleanup.
Make sure spu2 still works, I tested it and sound was fine.

SPU2: Cleanup spu2.

---

bin/resources/GameIndex.yaml

fixes Midnight Club memcard filters
refraction tested all combinations with a normal memcard
N/A

GameDB: fix up Midnight Club memcard filters

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes primitive cover without gaps check
The zero start check was incorrect, but also it only handled vertical strips (because of the merge code it borrowed).
You can just test random games if you like. Gran Turismo 4 was the one the original commit was for fixing, check the VRAM usage.
Did a dump run, out of 1296 dumps, there was only 1 change for 1 frame, which is going to be basically a false positive.

GS-HW: Fix bug in Prim cover with no gaps + allow horizontal strips

---

pcsx2/pcsx2core.vcxproj.filters

Tidies up some of the file filters for visual studio.
Stuff was in the wrong place, kept annoying me, been meaning to move it for a while.
Uhh, not really anything to test.

VS: Reorganise some file filters

---

bin/resources/GameIndex.yaml

add missing Gran Turismo fixes 
was missed 
check said games

GameDB : add missing Gran Turismo fixes

---

bin/resources/GameIndex.yaml

adds game fixes for Formula One 2003 on Bonus Demo 6
fixes #8866 
N/A

GameDB : fixes for Bonus Demo 6

---

bin/resources/GameIndex.yaml

GameDB: Correct a couple of regions for games.
From PAL-E to PAL-A.
From NTSC-J to NTSC-K.
Correct regions, and to close relevant issues.
Fixes #6982
Fixes https://forums.pcsx2.net/Thread-Bug-Report-GameIndex-yaml-is-needed-to-be-modified-PCSX2-Nightly-v1-7-3329-MOD
Fixes remaining issues on https://forums.pcsx2.net/Thread-Bug-Report-Super-Monkey-Ball-Adventure-NTSC-U-PAL
CI passes

GameDB: Correct a couple of regions for games and add gamefixes.

---

bin/resources/GameIndex.yaml

add a  missing entry in the gamedb 
missing entries bad 
N/A

GameDB:  add missing entries

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml
.github/ISSUE_TEMPLATE/emu_bug_report.yaml

mentions the fact to add  crash logs and .dmp to emulation bug reports and application bug report
wasn't included  before 
read said text

github: update issue templates

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

GS-Metal: Fix Wunused-variable warnings.
Less warnings.
CI passes.

GS-Metal: Fix Wunused-variable warnings.

---

bin/resources/GameIndex.yaml

a more complete gamedb
watch CI

GameDB: add various entries

---

bin/resources/GameIndex.yaml

GameDB: Fixes for  Onimusha Warlords

---

bin/resources/GameIndex.yaml

GameDB: Fix up some names

---

pcsx2/VMManager.cpp

Fixes widescreen/no-interlace patches not applying when booting with a state.
Regression from #8902.
Test booting with a state (i.e. right click in game list).
Make sure ws patches still work.

VMManager: Fix patches when booting with a state

---

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp
pcsx2/Gif.cpp
pcsx2/Gif.h
pcsx2/SPR.cpp
pcsx2/SPR.h

Misc: Cleanup unused code, warnings, constants, initializations, declarations.
Cleaner code.
CI builds.

Misc: Cleanup unused code, warnings, constants, initializations, declarations.

---

bin/resources/GameIndex.yaml

 GameDB: add missing entry for Nuga-Cel 

---

bin/resources/GameIndex.yaml

GameDB: correct Frogger Rescue serial

---

pcsx2/GS/GSCapture.cpp

Noticed this while sorting out the flatpak, the handling when samples don't need conversion was completely wrong.
Crashing trying to memcpy to an invalid pointer is never good.
Can't really test it unless you find a codec which crashes on master. But I verified it no longer crashes with the flatpak ffmpeg.

GS/Capture: Fix audio encoding without format conversion

---

bin/resources/GameIndex.yaml

Correcting info about same CRC for Devil May Cry 2.

GameDB: minor correction

---

pcsx2/VMManager.cpp

State was still initializing at settings load time.
Fixes the ugly text.
Check BIOS text.

VMManager: Fix game fixes not getting applied to BIOS

---

pcsx2/GS/GSLocalMemory.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSVector4.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSTexture.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX11/GSTexture11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/DX12/GSTexture12.cpp
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSTextureOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp
pcsx2/GS/Renderers/Vulkan/VKContext.cpp
pcsx2/MTGS.cpp

See commit list for details.
The less risky changes from my clear PR.
Make sure all renderers still work. Dump runner says no changes, except GL, where there was a bunch of oddball fixes, like below:

GS/HW: Various fixes

---

bin/resources/GameIndex.yaml

Fixes broken post processing by using autoflush.
Master:
PR:
Broke game bad.

GameDB: Matrix Path Of Neo Fixes

---

pcsx2-qt/Settings/CreateMemoryCardDialog.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2-qt/Translations/pcsx2-qt_en.ts
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/MemoryCardFile.cpp
pcsx2/MemoryCardFolder.cpp
pcsx2/Sio.cpp
pcsx2/VMManager.cpp

Fixes some typos
Typos are nope-o's
not a lot, just make sure it compiles.

UI: Fix some typo's in UI comments

---

.github/workflows/lint_gamedb.yml
.github/workflows/linux_build_matrix.yml
.github/workflows/macos_build_matrix.yml
.github/workflows/windows_build_matrix.yml
crowdin.yml

Some fixes that I noticed after this PR https://github.com/PCSX2/pcsx2/pull/9030
Also the crowdin project now has languages that share the same code, so locale has to be used.

ci: don't build the localization branch on push

---

pcsx2/DEV9/ATA/ATA_Info.cpp
pcsx2/DEV9/ATA/ATA_State.cpp
pcsx2/DEV9/ATA/ATA_Transfer.cpp
pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
pcsx2/DEV9/ATA/HddCreate.cpp
pcsx2/DEV9/DEV9.cpp
pcsx2/DEV9/InternalServers/DNS_Server.cpp
pcsx2/DEV9/Win32/pcap_io_win32.cpp
pcsx2/DEV9/Win32/tap-win32.cpp
pcsx2/DEV9/flash.cpp
pcsx2/DEV9/smap.cpp
pcsx2/DEV9/sockets.cpp

DEV9: Dev9 cleanup part 1.
Cleans up initializations, functions, casts and such.
Cleaner code.
DEV9 works as expected, CI passes.

DEV9: Dev9 cleanup part 1.

---

pcsx2/MemoryCardFolder.cpp
pcsx2/MemoryCardFolder.h

UB-chan says hi (call site was getting a string view from the temporary)

MemoryCardFolder: Fix saved message displaying junk

---

bin/resources/GameIndex.yaml

Fixes for missing post processing by using autoflush and HPO Normal.
Master:
PR:
Ghosting bad gross ew.

GameDB: Spartan Total Warrior Fixes

---

bin/resources/GameIndex.yaml

Adds missing demos and fixes to fix SPS on demos.
Fixes #9066 
SPS bad.
CI happy boy.

GameDB: Add missing WRC II Fixes

---

bin/resources/GameIndex.yaml

God help me.
Fixes #9068 
Why did I label a PAL demo disc as NTSC-J? 

GameDB: Add missing WRC 3 serial

---

pcsx2-qt/Settings/FolderSettingsWidget.ui

Qt: Adjust cache folder help text

---

.github/workflows/linux_build_flatpak.yml
.github/workflows/scripts/linux/install-packages-flatpak.sh

Add push to workflow.
Next step in using our CI to publish flatpak builds.
Tested on my fork, so just make sure CI passes.

CI/Linux: Push to Flathub beta

---

bin/resources/GameIndex.yaml

fixes #9087 
@benderscruffy please check above demos

GameDB: add missing demos

---

bin/resources/GameIndex.yaml

fixes #9070
@benderscruffy please check said demos

GameDB: fixes for WRC4 demos & update patches

---

.github/workflows/macos_build.yml

#9047, macOS edition
Fixes #9090
Fixes #9092 
Less broken
Test the linked issues, as well as #9045

GHActions:Mac: Update to macOS 13 / Xcode 14.3

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Lookup creating targets doesn't a lot of much sense.
Making the TC ever so slightly easier to reason about.
Dump run says it's fine, but check GTA LCS and make sure performance didn't regress.

GS/HW: Split LookupTarget() and CreateTarget()

---

pcsx2/Elfheader.cpp

Came across this when shoveling exceptions out.
Might be the reason for #9084.
Possible bugfix.
Check debugger.

ElfObject: Fix inverted condition

---

pcsx2/Interpreter.cpp
pcsx2/Sio.cpp

Sio: Fix Wunused-variable warning.
Interpreter: Cleanup constants, casts, formatting.
Less compiler warnings, cleaner code.
CI passes, everything works.

Core: More compiler warnings fixup.

---

pcsx2/VMManager.cpp

VMManager: Fix cheats warning showing with per-game HC mode

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

It could end up set to -1.
Regression from #9115.

GS/Vulkan: Set line width unconditionally on line draw

---

pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Forgot to check this with the earlier PR.
Correctness.

GS/OpenGL: Fix potentially-incorrect line width

---

.github/workflows/linux_build_flatpak.yml
.github/workflows/scripts/linux/generate-metainfo.sh
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.ui
pcsx2-qt/SettingWidgetBinder.h
pcsx2-qt/Settings/AchievementLoginDialog.ui
pcsx2-qt/Settings/ControllerBindingWidgets.cpp
pcsx2-qt/Settings/DEV9SettingsWidget.cpp
pcsx2-qt/Settings/GameCheatSettingsWidget.ui
pcsx2-qt/Settings/GamePatchDetailsWidget.ui
pcsx2-qt/Settings/GamePatchSettingsWidget.ui
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Settings/MemoryCardConvertDialog.cpp
pcsx2-qt/Settings/MemoryCardConvertDialog.ui
pcsx2-qt/Settings/PatchDetailsWidget.ui
pcsx2-qt/SetupWizardDialog.cpp
pcsx2-qt/Translations/pcsx2-qt_en.ts
pcsx2/USB/USB.cpp
pcsx2/USB/usb-mic/audiodev-cubeb.cpp

See individual commits.
Fixes most of the issues in #9062.
~~Make sure toolbar still works.~~ Checked all buttons myself.
Remainder has to wait until Crowdin pulls the new base xml.

Qt: Various translation fixes

---

bin/resources/GameIndex.yaml

was missing 
watch CI , @benderscruffy please check

GameDB: add more missing demos

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Gran Turismo 4 Online uses it.
ZBP is set to FBP+1, and a pattern of 64..nothing..64..nothing is drawn. Z fills in the gaps.
Gran Turismo 4 Online Public Beta uses it.
Check a couple of games, make sure they render (runner says it's fine)

GS/HW: Detect one-page-offset RT+Z clear

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

So many edge cases....
Details in comments in the source.
Closes #9147.
Closes #9149.
Also fixes GOW2 issue mentioned in #8961.
Check affected games.

GS/HW: Fix some regressions from #8961

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/SaveState.cpp

Cleans up compiler warnings.
Warnings are bad mkay.
CI passes.

Misc: Compiler warnings fixup.

---

bin/resources/GameIndex.yaml

Fixes for Redump lying to me and for a black screen in Giant Robot The Animation.
Fixes #6994 
Redump bamboozled me.

GameDB: Some fixes

---

bin/resources/GameIndex.yaml

Fixes for crusty textures by using Full mipmapping and trilinear filtering.
Crust is bad especially on pizza.

GameDB: X Squad Fixes

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Caused flickering/black frames/etc.
Regression from something recent.
Check GTA:SA or GT4:O in DX12.

GS/DX12: Fix targets getting stuck undirtied

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

We don't want to invalidate targets when the clear doesn't cover the whole thing.
Unfortunately this means a bunch of games get non-optimal clears now, because TextureMinMax is a couple of pixels out..
But better than killing unrecoverable data.
Fixes shadows in Persona 3 again.
Check Persona 3.

GS/HW: Don't invalidate buffers on partial clear

---

.github/workflows/scripts/common/name-artifacts.sh
.github/workflows/scripts/releases/rename-release-assets.py
pcsx2-qt/AutoUpdaterDialog.cpp

Unbreak the updater
It broke, changed too much too quick for the old girl.
Not much to test, just make sure the changes are all there that are needed.

Updater: Make it not care about the Qt extension

---

bin/resources/GameIndex.yaml

Fix my previous patch to not read corrupted data from stack. 
Fixes #9223
Test intro scene with carton boxes, test going to first floor in library (attached card).
https://github.com/PCSX2/pcsx2/files/9310139/Mcd002.zip

GameDB: Fix patch for Michigan: Report from Hell

---

pcsx2/Patch.cpp

Seeing #9243 gave me the idea that we should display cheats/patches from all ELFs, otherwise anything that doesn't exist in the primary ELF file won't be visible in the UI. So this PR changes it to scan all files.
Note that you'll need to use the new `SERIAL_CRC.pnach` format for this to work - game properties has no idea what the other CRCs on the disc are, it just matches on the first part of the filename.
Also get rid of duplicates from the list.
Different cheats for different ELFs.
Create two pnach files, with different CRCs but the same serial. Make sure both sets of cheats show up in game properties.

Qt: Show cheats/patches for all CRCs in game properties

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/R3000A.cpp

Compiler warnings cleanup.
Warnings cleanup.
CI passes.

Misc: More warnings fixup.

---

common/FileSystem.cpp

Replaces a `fseek`/`ftell`/`fseek` dance with a proper size call on Windows, since a function is available there.
It's easier.
?

FileSystem: Use _filelengthi64 to get the file size on Windows

---

pcsx2/GS/GS.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

See commits for details.
Crash fixes, improving debugging.
Make sure video recording doesn't blow up on reset and state load.

GS: Various minor fixes

---

.github/workflows/scripts/macos/build-dependencies.sh

Patch Qt to not inspect files when macOS asks it whether a file should be selectable in open/save dialogs
(This is asked for every file that's visible in the dialog, not just user-selected files)
Note: This removes all file filtering functionality except the ability to filter by file extension.  (e.g. globs for not-file-extension things, filter by permissions, etc).  I don't think we used any of that though.
The file inspection Qt did would trip the macOS sandbox permission system, and spam users with requests for access to things like documents, downloads, calendar info, etc.
(I've [reported this to Qt](https://bugreports.qt.io/browse/QTBUG-114919), so hopefully they'll properly fix it eventually)
- Run `tccutil reset All net.pcsx2.pcsx2` to reset PCSX2's permissions
- Try out file …

Qt: Stop open/save dialogs from spamming users with permission requests

---

bin/resources/shaders/common/fxaa.fx
bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/dx11/imgui.fx
bin/resources/shaders/dx11/interlace.fx
bin/resources/shaders/dx11/merge.fx
bin/resources/shaders/dx11/present.fx
bin/resources/shaders/dx11/shadeboost.fx
bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/opengl/imgui.glsl
bin/resources/shaders/opengl/interlace.glsl
bin/resources/shaders/opengl/merge.glsl
bin/resources/shaders/opengl/present.glsl
bin/resources/shaders/opengl/shadeboost.glsl
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/opengl/tfx_vgs.glsl
bin/resources/shaders/vulkan/convert.glsl
bin/resources/shaders/vulkan/imgui.glsl
bin/resources/shaders/vulkan/interlace.glsl
bin/resources/shaders/vulkan/merge.glsl
bin/resources/shaders/vulkan/present.glsl
bin/resources/shaders/vulkan/shadeboost.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/pcsx2.vcxproj
pcsx2/pcsx2.vcxproj.filters

vcxproj: Add missing shader filters. 
All renderers: present and imgui.
Vulkan: shadeboost.
GS-shaders: Add missing copyright headers.
Consistency.
CI passes.

Misc: Vs filters and shader copyright headers.

---

pcsx2-gsrunner/Main.cpp
pcsx2-gsrunner/comparer.css
pcsx2-gsrunner/comparer.js
pcsx2-gsrunner/test_check_dumps.py

Click on a dump to open.
Left/right arrow keys switch between dumps.
Space bar toggles between before/after.
Escape closes.
Makes going through many diffs much less painful.
CI passes.

GSRunner: Add modal comparison

---

pcsx2/SIO/Sio0.cpp
pcsx2/SIO/Sio0.h
pcsx2/SIO/Sio2.cpp
pcsx2/SIO/Sio2.h
pcsx2/SaveState.cpp
pcsx2/SaveState.h
pcsx2/StateWrapper.h

Also fixes the crash due to serializing pointers.
Master serializes pointers = boom boom.
Check saving+loading states.

Sio: Migrate to StateWrapper

---

pcsx2-qt/AutoUpdaterDialog.cpp

Adds an instruction to save any progress to memory cards before proceeding. 
Here, hoping people read the warning and actually do the thing.
Check if i didn't bodge the formatting.

Qt: Add an instruction to the autoupdater pop up.

---

pcsx2-gsrunner/Main.cpp

GSRunner: Fixes runner compile.
Pad include from previous refactor.
Bugfix.
GSRunner compiles.

GSRunner: Fixes runner compile.

---

pcsx2/Achievements.cpp

This PR fixes notification popups for leaderboard submissions when multiple leaderboards are updated at once. It's common for games where leaderboards for score+time co-exist, for example [Grand Theft Auto: San Andreas](https://retroachievements.org/game/2772).
Before:
After:
This bug was **only visual**, no wrong RetroAchievements submissions were made.
```cpp
// RA API doesn't send us the leaderboard ID back.. hopefully we don't submit two at once :/
if (s_submitting_lboard_id == 0)
return;
```
hehe
I deleted `s_achievements_mutex` from the call because `s_submitting_lboard_id` is gone, so global achievements state is now not modified from `Achievements::SubmitLeaderboard`.
Verify that in the case of multiple leaderboards updating at once, multiple notifications show and their contents …

Achievements: Fix Leaderboard submission UI when multiple leaderboards update at once

---

bin/resources/GameIndex.yaml

Fix naming of demo disc
Bad name Bad
Just make sure CI is happy I guess...

GameIndex: Fix PoPoLoCrois Naming

---

pcsx2/SaveState.cpp

Stores the PCSX2 version the state is created with in the save state file.
Means we can tell users an example version to download, rather than just "older".
While it might not technically be the last version which can load the file, it's close enough.
Check saving and loading states works.

SaveState: Store the current PCSX2 version in the save state

---

pcsx2/SIO/Pad/PadDualshock2.cpp

Changes vibration handling to respect games flipping the motors around. Also fixes incorrect vibration capability reporting, and a slight difference in digital pad button capability reporting.
Fixes #9659 
Fixes FFX vibrating itself to death, possibly other games which try to tamper with the vibration motor order for no good reason.
Boot FFX, make sure controller does not shake itself off your desk. Try other games known to have vibration, make sure it still vibrates.

Pad: Respect non-standard vibration mappings and pure digital button query

---

pcsx2-qt/Settings/ControllerBindingWidgets.cpp
pcsx2-qt/Settings/ControllerBindingWidgets.h
pcsx2-qt/SetupWizardDialog.cpp
pcsx2/Config.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/Input/InputManager.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/SIO/Memcard/MemoryCardFile.cpp
pcsx2/SIO/Pad/Pad.cpp
pcsx2/SIO/Pad/Pad.h
pcsx2/SIO/Pad/PadTypes.h
pcsx2/SIO/Sio2.cpp

Core settings getting reloaded on ELF change were wiping out the multitap enables. So let's clean it up.
Closes #9657.
Test multitap and input profiles (done myself).

Pad: Move multitap into its own config section

---

bin/resources/GameIndex.yaml

Doesn't appear to do anything currently and causes the game to do almost 100 readbacks totally killing performance in hardware mode.
Fixes #8819 
Running at 18 fps for no visual difference is kinda pointless yeah?

GameDB: Remove CCLUT from Raw Danger

---

pcsx2/Achievements.cpp
pcsx2/VMManager.cpp

See title.
Closes #9733.
Test conditions in linked issue.

VMManager: Fix achievements HC mode not applying on reset

---

pcsx2/DEV9/ATA/ATA.h
pcsx2/DEV9/ATA/ATA_Info.cpp
pcsx2/DEV9/ATA/HddCreate.cpp
pcsx2/DEV9/ATA/HddCreate.h
pcsx2/DEV9/InternalServers/DNS_Server.cpp
pcsx2/DEV9/InternalServers/DNS_Server.h
pcsx2/USB/usb-eyetoy/cam-linux.cpp
pcsx2/USB/usb-eyetoy/cam-windows.cpp
pcsx2/USB/usb-eyetoy/cam-windows.h

Fix function parameter should be passed by const reference warnings.
Less warnings.
CI passes.

Misc: More codacy warnings fixes.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

with it gone it matches SW 
watch CI/ play game

CRC/HW: remove god hand GSC

---

bin/resources/GameIndex.yaml

GameDB: Add full mipmap plus triliear ps2 to The Godfather.
Improves building textures to match sw renderer.
Improves building textures to match sw renderer.
CI passes.

GameDB: Add full mipmap plus triliear ps2 to The Godfather.

---

pcsx2-qt/Settings/SettingsDialog.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes compiler warnings.
Fixes compiler warnings.
CI passes.

Misc: Fix compiler warnings.

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui

removes left missing UI mentions  from #9745
was forgotten about 
make sure CI passes / looks correct

UI: remove mention of Half Screen Fix

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

On target overlap, only preserve the valid part.
Making non-valid data valid is bad.
Smoke test + GT4 Online. Dump run only showed a diff with GT4
Fixes #9798

GS/HW: Only preserve valid channels on target overlap

---

bin/resources/GameIndex.yaml

**Rationale behind Changes**
Fixes sun appearing in front of everything and bloom effect.
Software
Hardware (master)
Hardware (with fixes)
[GS dump](https://drive.google.com/file/d/1QerfzHMnAuc3b5rKdWGFIOiZO7wq_pRf/view?usp=sharing)
Btw this is my first contribution and I barely use GitHub so if something is off, y'all tell me.

GameDB: Hardware Fixes for Burnout 2

---

bin/resources/GameIndex.yaml

Games have the same issues and fixes, also normal vertex introduces some texture gaps whilst full roundsprite looks to be better, also add Vu0clampmode for some of the bad dialog backgrounds.
Naruto Ultimate Ninja 4 (Ultimate Accel 1)
- Master HW (normal vertex):
- New Master HW (replaced with full roundsprite):
- Software Renderer:
------
Bugged text background for Ultimate Ninja 4
- Before:
- After:
Naruto Ultimate Ninja 5 (Ultimate Accel 2)
- Master HW (normal vertex):
- New Master HW (replaced with full roundsprite):
- Software Renderer:
See also: https://github.com/PCSX2/pcsx2/pull/9803
Better fixes and I like pictures
Test relevant games

GameDB: Naruto Ultimate Ninja 5 + same for 4th

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Skips DATE if the alphas are too high/low (depending on DATE test)
Just a small optimisation to make things suck a little less.
Just test random stuff, if you know games that use DATE, great.
Some improvements from GS Dump run, may result in tiny speed boosts, but don't hold your breath
Driv3r_SLUS-20587_20221006000803
Draw Calls: -6 [2035=>2029]
Render Passes: -6 [955=>949]
Barriers: -4 [20=>16]
Eternal Poison_SLUS-21779_20220808145024
Barriers: -2 [5=>3]
Haunting_Ground (HG_texture_cache_bug)
Draw Calls: -3 [273=>270]
Render Passes: -1 [28=>27]
Barriers: -3 [18=>15]
Juiced_SLES-53044_20221224185027
Draw Calls: -3 [2023=>2020]
Render Passes: -1 [58=>57]
Barriers: -2 [106=>104]
Midnight Club 3 - DUB Edition Remix_SLUS-21355_20230314104412
Draw Calls: -1 [308=>307]
Barriers: -1 [8=>7] …

GS/HW: Skip DATE/draw if not required

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Further adjust how we handle RT alpha in blending.
Check whenever RT alpha min is equal or higher than RT alpha max / 2. This will allow us to use the min value as a more accurate option than the actual value since it will be less accurate.
SW blend with barriers will be always preferred.
Accuracy using hw blend, useful especially when using D3D.
Xenosaga 3, GT4 with 1080i (no diff), Urban Reign (no diff), Dragonball Z Budokai 2.
Dump run showed only those.

GS/HW: Further adjust how we handle RT alpha in blending.

---

bin/resources/GameIndex.yaml

Normal (Vertex) causes align sprite artifacting, also Special aggressive reduces blurriness even more.
GSdump:
[Soul_Calibur_III_SLUS-21216_20230818104717.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12380663/Soul_Calibur_III_SLUS-21216_20230818104717.gs.zst.zip)
- Before:
- After:
- Software Renderer Reference:
Less tinkering
Test any SoulCalibur 3

GameDB: SoulCalibur III

---

bin/resources/GameIndex.yaml

It was missing. 
Fixes #9821
Make sure everything is written and formatted correctly.

GameDB: Add missing patch for Myst III

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp

See title.
Closes #9861.
Try to reproduce linked issue.

Qt: Fix global volume slider overriding per-game

---

pcsx2/ImGui/FullscreenUI.cpp

What the title says. Also some other minor improvements, such as focusing the first item in the menu when it's opened automatically.
Closes #9794.
Test FSUI with gamepad, pressing O/B should go back to the pause menu when going into settings/achievements.

FullscreenUI: Make back button go back to pause menu

---

pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp

Noticed this happening when digging into Destroy All Humans for the invalidation PR.
Spec violation => bad.
Smoke test.

GS/Vulkan: Prevent transition back to Undefined layout

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp

Fixes the GSC for handling the FMV's in these games, specifically for the NTSC editions.
I had hard coded it for PAL like a moron.
Test Blue Tongue Entertainment games, make sure they're okay
Fixes #9879

GS/HW: Fix up FMVs for Blue Tongue Entertainment games

---

pcsx2/IPU/IPU_MultiISA.cpp

Move the macroblock decoding delay to after the decode.
Motorstorm seems to have some timing problems with how it was, but it seems fine with the delay being after, I guess some DMA data is being overwritten quickly.
Test FMV's, make sure they're okay, test Motorstorm - Arctic Edge and Lord of the Rings - Return of the King, make sure they're okay (quickly tested)

IPU: Move decode delay to after the decode

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Allow some lenience in double half clear detection for odd width framebuffers.
Final Fantasy 7 - Dirge of Cerberus has a buffer width of 448 (FBW 7) which is an odd amount, but uses a half width to clear it, since you can't do 3.5 it does 4, so the clear half doesn't line up and is not quite centre, so they slightly over clear (you can see this by the half way point on master being tot he right of the middle).  These changes allow for it as long as the half point is less or equal to the calculated half.
Test random games, plus FF7 - DoC
Fixes #9873
Master:
PR:

GS/HW: Round up when checking odd width double half clears

---

bin/resources/GameIndex.yaml

replace skipmpeg with eeCycleRate  for  David Beckham Soccer
check said games

GameDB : replace skipmpeg with eeCycleRate  for  David Beckham Soccer

---

bin/resources/GameIndex.yaml

Adds mipmapping full and trilinear for better ground texture for battlefront, also missing a '-' with new entry with missing fixes and region.
- Before (No gamefixes added):
- After (with full mipmapping and trilinear):
- After (with full mipmapping and trilinear + recommended blending mention):
Lara Croft Tomb Raider Legend, gets higher minimum blending as it looks better and is less than 500 readbacks so should be fine, also had missing gamefixes for entries.
- Before (Basic blending):
- After (Full blending):
- Before (Basic blending):
- After (Full blending):
- Before (Basic blending):
- After (Full blending):
Also fix Counter Terrorist - Fire For Effect smoke particles (Fixes https://github.com/PCSX2/pcsx2/issues/9885)
Test Battlefront 1 or Lara Croft Legend.

GameDB: Star Wars Battlefront + Lara Croft Legend + Counter Terrorist Fire for Effect

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Improve half point check for existing target and improve the check for half width clears.
Kind of a regression from #9875 which caused misdetection in some cases, though it may have also been wrong before but luckily didn't trigger.
Test random games + any you know do double half clears.  Dump run says it's good (Spider-man 2 must have some target resizing on the shadow, however it looks better now, imo)
Fixes Fast & the Furious background
Master:
PR:

GS/HW: Check for half point on double half clear, improve width check

---

pcsx2/x86/iR3000A.h

Fixed undefined behaviour warning  in codacy 
watch CI

Misc : Fixed undefined behaviour warning

---

bin/resources/GameIndex.yaml

fixes upscaling issues 
Watch CI

GameDB:  upscaling fixes for Club Football 2005 series

---

pcsx2-qt/Settings/AudioSettingsWidget.ui
pcsx2/ImGui/FullscreenUI.cpp

fixes some typos mentioned in   #9062 
N/A

Translations : some typo  fixes

---

pcsx2/Elfheader.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/Input/SDLInputSource.cpp
pcsx2/x86/ix86-32/iR5900.cpp

Codacy warnings and code cleanup, details in commits.
Less warnings, cleaner code.
CI passes, everything works.

Misc: Codacy warnings and code cleanup.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Adjust scissor for BeginHLEHardwareDraw.
Was wrong before, according to sten and ref.
455 dumps showed no diffs.

GS/HW: Adjust scissor for BeginHLEHardwareDraw.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Calculate the texture width before checking if the shuffle is doubled in width or height.
This was errantly going over by 1 pixel in One Piece Grand Adventure and causing misdetection of half right (instead of half height), so pre-clamping the size avoids this.
Smoke test mostly, dump run was fine, check One Piece - Grand Adventure
Master:
PR:

GS/HW: Improve half right detection on shuffles

---

pcsx2-qt/Translations.cpp

Add Croatian to the Translations UI menu
was missing
watch CI

Translations: Add Croatian to the UI menu

---

bin/resources/GameIndex.yaml

Still some weird overlaps that need to be checked:
redump doesn't know every PAL-unk for some reason
Less tinkering and more feature complete
Added missing fixes (new entries so not unexpected) but probably fine:
-WRC3 
-God of war 2 
- gran turismo Geneva something
- Destruction Derby Arenas
-  MotoGP 3 
- Primal 
- Ratchet and Clank 3

GameDB: Add missing fixes and unknowns for EU

---

pcsx2/SPU2/Mixer.cpp
pcsx2/SPU2/RegTable.cpp
pcsx2/SPU2/Reverb.cpp
pcsx2/SPU2/defs.h
pcsx2/SPU2/spu2sys.cpp
pcsx2/SaveState.h

Should fix 18 wheeler and the suffering.
Fixes #6769 
Make sure the music keeps playing in 18 wheeler and that reverb is consistent in the suffering intro.
And that nothing else in the vast PS2 library broke? :^)

SPU: Rework reverb buffer logic

---

bin/resources/GameIndex.yaml

removes State of Emergency 2 fixes
N/A

GameDB: remove State of Emergency 2 fixes

---

pcsx2/Docs/PCSX2_FAQ.md

The first link redirected to “Page Not Found”.
The second link redirected to a general page.
Use a link to the docs about the BIOS instead.

FAQ: update links to BIOS dumper

---

pcsx2/DEV9/ATA/Commands/ATA_SCE.cpp

Implemented SCE Security Identify correct response.
Some apps like HDD Utility disks checks if SCE Security Identify response is valid.

ATA: implement SCE Security Identify

---

bin/resources/GameIndex.yaml

GameDB: fixes for Minna no Tennis

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

0x2800 target was previously used as only 32 pixels high, so the move got cut off.
yolo?

GS/HW: Resize target in Ico move fix

---

pcsx2/Achievements.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp

Need to use GSTextures here across the board...
Less crashy
Tested locally

Achievements: Fix UI crash with DX11

---

pcsx2-qt/Settings/DEV9SettingsWidget.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Wunused-variable warnings cleanup.
Just your usual warnings cleanup.
CI passes.

Misc: Compiler warnings cleanup.

---

common/FileSystem.cpp
common/FileSystem.h
pcsx2-gsrunner/Main.cpp
pcsx2-qt/QtHost.cpp
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GameDatabase.cpp
pcsx2/Host.h
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiManager.cpp
tests/ctest/core/StubHost.cpp

No more wx, no need to abstract this.
Less code.
Make sure all renderers still work on Windows/Linux. Mac testing isn't needed, Metal shaders are precompiled.
Make sure game list and dump verifier still work.

Host: Remove resource read wrappers

---

bin/resources/GameIndex.yaml

Fixes for broken rendering on replay window and likely other things.
Before:
After:
Game broke bad.

GameDB: MVP NCAA Baseball fixes

---

common/General.h

Common: Fix unused function warning

---

pcsx2/CDVD/CDVD.cpp

CDVD: Fix Wunused-variable warnings.
Fixes compiler warnings.
CI passes.

CDVD: Fix Wunused-variable warnings.

---

bin/resources/GameIndex.yaml

Fixes for misaligned bloom and likely depth issues.
Before:
After:
Gross bloom game looks less gross more good yes.

GameDB: Black Hawk Down fixes

---

bin/resources/GameIndex.yaml

GameDB: Ayakashi-bito needs software clut

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/GameListSettingsWidget.cpp

Qt: Fix re-showing Controller Settings

---

bin/resources/GameIndex.yaml

GameDB: Fixes for Maxxed Out Racing Nitro and Chou Saisoku! Zokusha King B.U.

---

bin/resources/GameIndex.yaml

GameDB: Fixes for FIFA Total Football 2

---

bin/resources/GameIndex.yaml

Adjust fixes for PaRappa the Rapper 2
watch CI

GameDB: Adjust fixes for PaRappa the Rapper 2

---

bin/resources/GameIndex.yaml

fixes for various games
fixes: #10156
watch CI

GameDB: fixes for various games 

---

bin/resources/GameIndex.yaml

This reverts commit e016e3280d727efa26affbd3d58eef99f01f97b1.
could destory saves 
watch CI

Revert "GameDB: Patch to fix Valkyrie Profile 2 PAL FMV timing"

---

bin/resources/GameIndex.yaml

Fixes for texture corruption.
Textures not working is bad.

GameDB: SOCOM II Fixes

---

bin/resources/GameIndex.yaml

Fixes for every other SOCOM game I missed that needs InstantDMA to fix texture corruption.
Textures not working is bad.

GameDB: SOCOM Fixes

---

bin/resources/GameIndex.yaml

This PR fixes corruptions on the bottom of the screen on Kamen Rider Kabuto.
Master:
PR:
garbaj bad
CI happy bois

GameDB: Fixes for Kamen Rider Kabuto

---

pcsx2-qt/GameList/GameListModel.cpp
pcsx2-qt/GameList/GameListModel.h
pcsx2-qt/QtHost.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/MTGS.cpp

Qt: Fix prefer-English-title when changing languages
Qt: Fix Big Picture UI locking up after game list 
GS: Fix reload texture replacements hotkey
Closes #10229.
Closes #10187.
Closes #10184.
Check linked issues are fixed.

Qt: Fix a few issues

---

pcsx2/Interpreter.cpp
pcsx2/IopCounters.cpp
pcsx2/SPU2/ReverbResample.cpp

Cleanup Wunused-variable, Wsign-compare warnings.
Warnings cleanup.
CI passes.

Misc: Warnings cleanup.

---

bin/resources/GameIndex.yaml

adds and fixes some japanese games
5chan requests 
hopefully tests should pass

GameDB: Japanese Games

---

bin/resources/GameIndex.yaml

Games still busted but it at least matches software in hardware now.
Game being less broken is more good.

GameDB: PJ King Kong fixes

---

bin/resources/GameIndex.yaml

fixes said games 
games were broke 
watch CI

GameDB: fixes for XS Junior League Soccer &  Guitar Hero - Van Halen

---

bin/resources/GameIndex.yaml

Fixes for terrain rendering in Ace Combat 4 and Zero. See #10271 for details.
Game brokey bad.

GameDB: Ace combat fixes

---

bin/resources/GameIndex.yaml

Add Auto flush to MGS2 Substance.
Fixes depth of field blur.
Fixes https://github.com/PCSX2/pcsx2/issues/10270
CI passes

GameDB: Add Auto flush to MGS2 Substance.

---

pcsx2/CDVD/CDVD.cpp

Removing the inclusion of read times in seeks, which shouldn't have been in there.
the CD_SEEK command is looking for a sector, there is no read involved beyond the sector it's looking for (which is included in the rotation). This might have caused bad timing in Digital Devil Saga.
Test Digital Devil Saga, see if it randomly hangs still.

CDVD: Don't include read times during seeks

---

bin/resources/GameIndex.yaml

Fixes for excessive texture uploads and massive hash cache sizes.
Game do more brrr.

GameDB: Sega Ages 2500 Fixes

---

bin/resources/GameIndex.yaml

updates Driving Emotion fixes
watch CI

GameDB : update Driving Emotion fixes

---

bin/resources/GameIndex.yaml

Round sprite from half to Full.
Fixes textboxes and character portraits.
Fixes https://github.com/PCSX2/pcsx2/issues/8364
CI passes, test https://github.com/PCSX2/pcsx2/issues/8364

GameDB: Update Ar tonelico upscaling fixes.

---

bin/resources/GameIndex.yaml

Fixes random incorrect model position.
Fixes #8601

GameDB: Radiata Stories fixes

---

pcsx2/Achievements.cpp

Also bumps to latest rcheevos commit.
Fixes #10337.
Make sure achievements still work. It's difficult to test the linked issue, because it requires disabling the hardcore-disable-on-load-state behaviour. I've tested that part, so testers just need to make sure the version bump didn't break anything. Try logging out and logging in, and also intentionally failing with incorrect credentials.

Achievements: Fix multiple leaderboard trackers

---

bin/resources/GameIndex.yaml

Fixes for right edge artifacts in Katamari Damacy.
Less broke more good.

GameDB: Misc fixes

---

.github/workflows/triage_pr.yml
bin/resources/GameIndex.yaml

Fixes broken player textures.
Less break more good.

GameDB: FIFA World Cup 2006 Fixes

---

3rdparty/d3d12memalloc/CHANGELOG.md
3rdparty/d3d12memalloc/README.md
3rdparty/d3d12memalloc/include/D3D12MemAlloc.h
3rdparty/d3d12memalloc/src/D3D12MemAlloc.cpp

Updates D3D12 memory allocator to latest master commit.
Less date up to update more good.
Make sure DX12 still works and it compiles.

3rdparty: Update D3D12 memory allocator

---

bin/resources/GameIndex.yaml

Upscaling fixes for  X-Men 2 - Wolverine's Revenge
watch CI

GameDB : Upscaling fixes for  X-Men 2 - Wolverine's Revenge

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Turns out there's two variants of the whacky channel shuffle that GT4 uses. One where it applies the effect immediately, which is what we previously handled, but some transitions use a variant where it stores the three colours to the alpha channels of 3 targets, then applies them later.
So, extend the HLE to handle the variant as well. Also fixes a spec violation with preloading, hit by GT4. Dump runner says there's no casualties.
Closes #10144.
Check GT4 in both NTSC and PAL, with linked issue scenario, as well as normal gameplay.

GS/HW: Handle GT4 alpha channel shuffle

---

bin/resources/GameIndex.yaml

adds missing  memcardFilters for Ratchet&Clank series best as i can 
Fixes #8410
watch CI ,

GameDB: memcardFilters for Ratchet&Clank series

---

bin/resources/GameIndex.yaml

Add monster hunter memcard filters for online an extra content 
Watch CI

GameDB: Add  monster hunter memcard filters

---

pcsx2/GS/Renderers/Common/GSVertexTraceFMM.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/OpenGL/GLContextEGL.cpp
pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSTextureCacheSW.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/VKLoader.cpp
pcsx2/GS/Renderers/Vulkan/VKShaderCache.cpp

Replace implicit with explicit captures.
Fixes warnings.
Make sure renderers work, and software performance is unchanged.

GS: Fix more lambda capture warnings

---

pcsx2/CDVD/CDVD.cpp

Adjust abort action behaviour when triggered via action.
Regression from #10262 I missed a bunch of behavioural changes.
Test Cy-Girls (already done)

CDVD: Adjust abort behaviour on action.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp

Misc: Compiler warnings fixes.
Fixing compiler warnings.
CI passes, dump run on 456 no difference,  vulkan, hw renderers still work.

Misc: Compiler warnings fixes.

---

pcsx2/GS/Renderers/DX11/D3D.cpp

Xe and Arc GPUs don't have broken Vulkan drivers, which means that blending will actually work if we default to Vulkan on these GPUs.
Both pre and post Xe is the same feature level, but sampler feedback tier 0.9 is only present in Tiger Lake/Xe/Arc, so we can use that to differentiate between them.
Working blending for users with newer Intel GPUs.
Make sure autodetection works as intended.

GS: Autodetect Vulkan for Intel Xe GPUs

---

bin/resources/GameIndex.yaml

Fixes dastardly lines appearing on the ground at certain viewing angles.
LINES BE GONE.

GameDB: Sims 2 Castaway fixes

---

pcsx2-gsrunner/test_check_dumps.py
pcsx2/GS/GSState.cpp

Fix height fetched for framebuffers, moreso affects the hardware renderer.
Maximum height didn't consider the offset to the framebuffer read, so it could cut the read short.
Also fixed the dump runner comparison script to handle directories containing [ ]
Try any of the games below, make sure the FMV's don't have a weird glitched bit at the bottom.
Fixes Chaos Field - New Order
Fixes Mashed - Fully Loaded
Fixes Mega Man X8
Fixes Meiwaku Seijin Panic Maker
Fixes #9912 Taiko no Tatsujin - Tatacon de Dodon ga Don
Fixes Yuusei kara no Buttai X - Episode II
Screenshots (Look at the bottom of the images)
Chaos Field:
Master:
PR:
Mashed:
Master:
PR:
Mega Man X8:
Master:
PR:
Meiwaku Seijin Panic Maker:
Master:
PR:
Taiko no Tatsujin:
Master:
PR:
Yuusei kara no Buttai X - Episode II:
Master:
PR:

GS/PCRTC/HW: Correct height of framebuffer reads

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Only copy valid parameters for channels which got copied in hardware moves
we were copying alpha valids for PSMCT24 moves from a PSMCT32 target, so the target did have valid alphas, but the copy did not, so this was giving false information on the destination target.
Test Armored Core games going in to menus and back out, where it used to corrupt the UI.
Fixes #9715
Armored Core 2 (after choosing to quit and cancelling):
Master:
PR:

GS/HW: Only copy valid channels for copied channels in hw move

---

bin/resources/GameIndex.yaml

Match up the casing on Vol vs. vol for JP versions, and fix a typo in 절대포위
Just tidying up the titles some more

GameDB: Add a couple more dothack title adjustments

---

pcsx2-qt/AutoUpdaterDialog.cpp
pcsx2-qt/pcsx2-qt.vcxproj

Qt: Fix AutoUpdaterDialog building

---

bin/resources/GameIndex.yaml

Hopefully fixes most issues besides the sun going through planes because apparently that is just a step too far and will refuse to be fixed by anything that wouldn't break something else.
Fixes #9937 
Hopefully this will be the last time I have to do this but knowing my luck.
Make sure CI is happy and I guess the games work? Already tested all 3 but someone will probably find something else broken by this.

GameDB: Ace Combat 4/5/0 fixes

---

pcsx2/VMManager.cpp

VMManager: Fix disc change path message

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2/Counters.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSUtil.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiOverlays.cpp
pcsx2/MTGS.cpp
pcsx2/MTGS.h
pcsx2/Pcsx2Config.cpp

- Fix automatic renderer causing delay when changing settings.
- Make the Debug -> Switch Renderer menu actually save.
Making auto renderer suck less.
Hammer renderer switching, per-game renderer configuration, changing settings while PCSX2 is running, etc.

GS: Refactor renderer switching

---

pcsx2/DEV9/pcap_io.cpp

PCAP: Fix a regression from #10448

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Translations.cpp
pcsx2/GameList.cpp

Apparently i DID left some stuff behind. This is why you shouldn't do this kind of stuff at like 12 AM.
I did an oopsie
Make sure i didn't do more oopsies.

Qt: More Translation Fixes

---

bin/resources/GameIndex.yaml

Fixes for complete lack of visuals in menus and game.
Playing a game without any visuals would be hard.

GameDB: Rock Band Track Pack Volume 2 Fixes

---

bin/resources/GameIndex.yaml

fixes issues in the mini games 
watch CI

GameDB: fixes for Mary-Kate & Ashley - Sweet Sixteen - Licensed to Drive

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

purge Knights Of The Temple 2 CRC 
watch CI , try game

HW/CRC: purge Knights Of The Temple 2 CRC hacks

---

pcsx2/SourceLog.cpp

Caused from my previous commit. oops

Core: Remove unused variable

---

pcsx2/SIO/Pad/PadPopn.cpp

SIO: Fix Wunused-variable compiler warnings.
Fixes compiler warnings.
CI passes.

SIO: Fix Wunused-variable compiler warnings.

---

bin/resources/GameIndex.yaml

This PR adds HPO Native which further help reducing the ghosting artifacts.
Also drop Wild Arms hack as it makes the font looks funky.
Software:
HPO Native + RS Full
less 👻-ing
See how does it looks.

GameDB: Fixes for Bully

---

pcsx2/Input/SDLInputSource.cpp

See title.
Can be useful in debugging issues.
CI passes.

SDLInputSource: Log axes/buttons when controller is opened

---

pcsx2/Input/SDLInputSource.cpp

I completely missed this when updating SDL.
Less hardcoding.
CI passes.

SDLInputSource: Replace hint strings with macros

---

pcsx2-qt/Settings/GameCheatSettingsWidget.h
pcsx2-qt/Settings/GamePatchSettingsWidget.cpp
pcsx2-qt/Translations.cpp
pcsx2-qt/Translations/pcsx2-qt_en.ts

And the new messages from #10568 not being translatable.
Regression from #10531.
Already tested, CI passes.

Qt: Fix opening game properties causing patch reload

---

common/TextureDecompress.h
pcsx2-qt/AboutDialog.cpp
pcsx2-qt/Debugger/Models/SavedAddressesModel.cpp
pcsx2-qt/QtHost.cpp
pcsx2/CMakeLists.txt
pcsx2/x86/iFPU.cpp
pcsx2/x86/iFPUd.cpp

Title, and fix a couple of warnings.
Dumbass me didn't think to check them.
Check links in about dialog on all platforms.

Qt: Fix docs file not getting included on Linux/Mac

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

hurr durr
derp derp derp
it didn't werk
CI passes.

GS/HW: Fix incorrect resizing of Ico move target

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Updates alpha information on sources linked to active targets
Wasn't doing this before, which is bad, especially when it's 16bit formats where it relies on TEXA.
Test Fast and Furious and some random other games, maybe check Taiko no Tatsujin Bang Tap - Toomori 7 Daimei, too.
Fixes #10594  Fast and Furious bad lighting
Taiko no Tatsujin Bang Tap - Toomori 7 Daimei picture moved up a little, but matches software now, was incorrect before.
Fast_and_the_Furious
Master:
PR:

GS/HW: Update cached source alpha if linked to target

---

pcsx2/VMManager.cpp

Between each update to played time, we calculate the sum of the deltas between VM resume and pause in order to subtract that off from the total (paused and unpaused) session time. Also, there was one check 'state == VMState::Paused' which already had a corresponding Boolean called 'paused'. There should be no possibility of a difference between this value and 'paused', so there should be no reason to re-perform this comparison here.
This is my first PR that actually affects anything outside of documentation or the GUI, so please take it with a grain of salt. Still, I really want to get into contributing to PCSX2, so I've done my best here.
Hopefully resolves #10497.
Thus, if someone pauses the emulator, that time spent paused will no longer be reflected in the GameList.
Start a game whose …

Update VMManager.cpp to not count paused time toward time played

---

common/SingleRegisterTypes.h
pcsx2/IPU/IPU_MultiISA.cpp

Rewrite it to be not dependent on x86 at the same time.
Should've read the code better.

IPU: Fix regression from #10617

---

pcsx2-qt/MainWindow.cpp
pcsx2/CDVD/CDVDcommon.cpp

Me, or someone else broke this at some point..
Making block dumps work again.

CDVD: Fix block dump path generation

---

bin/resources/GameIndex.yaml

Fixes some of the issues the game has in hardware mode:
Before:
After:
Less broke more good.

GameDB: Flower sun and rain fixes

---

.github/workflows/linux_build_qt.yml

CI/Linux: Use wildcard for AppImage libc downgrade

---

.gitignore

Added Rider solution temp folder to gitignore.
Some people (cough, me) use Rider and don't wanna commit temp files.
-

Adding Jetbrains Rider to Gitignore.

---

bin/resources/GameIndex.yaml

Looks better with the bloom and character shadows
-Before:
-After:
Better visuals
Test Gun

GameDB: Gun Align to Native + typo fix

---

bin/resources/GameIndex.yaml

Revert VP2 changes as they cause issues and fix a shadow issue in Star Wars Force Unleashed.
I am a silly and did not remove HPO Native before it was merged.

GameDB: Various fixes 2: Electric Boogaloo

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Optimizes out some situations where textures are not required.
Sometimes the texture isn't used because of the vertex colours etc wiping them out, so we can omit it.
Not really much to test, the below games might be a little quicker, but honestly probably not really noticable.
GS Dump results:
```007AgentUnderFire ['Uploads: -1 [5=>4]']
007_-_Everything_or_Nothing_SLUS-20751_20230225144134 ['Uploads: -1 [49=>48]']
Armored Core - Nexus [Disc 1]_SLPS-25338_20230815105529 ['Uploads: -2 [7=>5]']
Armored_Core_-_Last_Raven_radartest ['Copies: -3 [6=>3]']
Armored_Core_-_Last_Raven_SLES-53820_20221020170502 ['Uploads: -1 [24=>23]']
Armored_Core_-_Last_Raven_SLES-53820_20221125233142 ['Copies: -3 [6=>3]']
Armored_Core_-_Last_Raven_SLPS-25462_20221124005337 ['Copies: -3 [6=>3]'] …
```

GS/HW: Optimize out some situations of texture loading

---

pcsx2/Config.h
pcsx2/Pcsx2Config.cpp

config: remove  unused variables

---

bin/resources/GameIndex.yaml

Fixes texture corruption light flickering and reflective surfaces.
Before:
After:
Flashbangs directly the eyes is bad.

GameDB: Thrillville fixes

---

bin/resources/GameIndex.yaml

Makes the grass look less sharp and more like grass.
Before:
After:
Sharp grass is ouchie.

GameDB: Hot Shots Golf Fore Fixes

---

pcsx2/ImGui/ImGuiOverlays.cpp

ImGuiOverlays: Fix OSD margin

---

pcsx2-qt/Debugger/DebuggerSettingsManager.cpp
pcsx2-qt/Settings/DEV9SettingsWidget.cpp

Qt: Fix more compiler warnings.
-Wsign-compare, -Wunused-variable.
Almighty warnings purger.
CI passes.

Qt: Fix more compiler warnings.

---

bin/resources/GameIndex.yaml

GameDB: Add gshwfixes to Band Hero.
Fixes character shadow misalignment.
Fixes icons.
Improves https://github.com/PCSX2/pcsx2/issues/10666
Test the linked issue.

GameDB: Add gshwfixes to Band Hero.

---

pcsx2/GS/Renderers/DX11/D3D.cpp

ROG ally is shipping with the Microsoft OpenGL and OpenCL compatibility pack, which provides a GL/CL/VK driver based on Mesa. https://apps.microsoft.com/detail/9NQPSL29BFFF?hl=en-gb&gl=US
It's known to be broken: https://hashcat.net/forum/thread-11357-post-58060.html#pid58060
And in PCSX2's case:
```
amdxc64.dll!00007fffb9bf331f()    Unknown
D3D12Core.dll!CDevice::CheckFormatSupportImpl(enum DXGI_FORMAT,enum D3D12_FORMAT_SUPPORT1 &,enum D3D12_FORMAT_SUPPORT2 &)    Unknown
>    D3D12Core.dll!CDevice::CheckFeatureSupport(enum D3D12_FEATURE,void *,unsigned int)    Unknown
[Frames may be missing, no binary loaded for vulkan_dzn.dll]    
vulkan_dzn.dll!00007ffff9517972()    Unknown
```
which eventually goes down to:
```
00007FF738ABE672 FF 15 28 16 B8 03    call        qword ptr …
```

GS: Check for D3D Mapping Layers and disable Vulkan if present

---

pcsx2/Achievements.cpp

RA uses a fake memory map with the scratchpad directly above physical memory.
The scratchpad is not meant to be accessible via physical addressing, only virtual.
This also means that the upper 96MB of memory will never be accessible to achievements.
Fixes achievements that were reading the scratchpad.
Check achievements.

Achievements: Handle fake memory map

---

pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp

improves memcard  card  error message 
less confusion for the end user 
N/A or if you have a broken memcard see the message

Memory cards :  Update error message

---

bin/resources/GameIndex.yaml

Fixes stadium advertisement banners as well as ghosting and improves performance all in one go.
Master:
PR:
Speed more good yes.

GameDB: FIFA 14 Fixes

---

bin/resources/GameIndex.yaml

Fixes garbage on screen and adds missing fixes to the PAL release.
Before:
After:
Less broke more good.

GameDB: Arc the Lad TOTS Fixes

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Precheck date before updating RT alphas
Saves a couple of barriers here and there, but mostly fixes the RT alpha values when DATE is used
Already tested, will be YOLOing once built

GS/HW: Pre check DATE requirement before updating rt alphas

---

common/FileSystem.cpp
common/HTTPDownloader.cpp
common/HTTPDownloader.h
common/Path.h
pcsx2-qt/QtHost.cpp
pcsx2/GameList.cpp
tests/ctest/common/path_tests.cpp

Utility function that's useful for #10910, and potentially other things.
CI passes, isolated code with unit tests.

Path: Add CreateFileURL()

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

GS/Metal: Fix some Wformat warnings.
Fixes warnings.
Make sure metal still works.

GS/Metal: Fix some Wformat warnings.

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.ui

Various bits and pieces.
Fixes #10897 
Helps #4092 
Fixes #10934 
Fixes #1526 
Performance tanking bad.

Misc: GameDB Various fixes, rename screenshot size options on ui

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

If barriers are already present and it's a texture shuffle then prefer full sw blend, it will be more accurate with no cost for all hw renderers.
One barrier is enough for texture shuffles, no need to do full, which means less texture barriers and draw calls.
**Speed, accuracy.**
For those who have the dump archive can **benchmark** the following games/dumps, will be nice to **compare**, especially on **AMD**. Maybe @JordanTheToaster and @kamfretoz will :)
```
007 russia half screen ['Draw Calls: -825 [2540=>1715]', 'Barriers: -825 [923=>98]']
Armored_Core_-_Last_Raven_SLES-53820_20221020170502 ['Draw Calls: -13 [2534=>2521]', 'Barriers: -13 [18=>5]']
Echo.Night.Flashlight.on ['Draw Calls: -5 [2681=>2676]', 'Barriers: -5 [383=>378]']
Echo_Night_-_Beyond_SLUS-20928_20221019163851 ['Draw …
```

GS/HW: Improve how we handle texture shuffles with barriers.

---

README.md

Self-explanatory, just a simple readme link change.
also ran it through prettier.

README: Update docs link

---

pcsx2/USB/qemu-usb/USBinternal.h
pcsx2/USB/qemu-usb/bus.cpp
pcsx2/USB/qemu-usb/core.cpp
pcsx2/USB/qemu-usb/desc.cpp
pcsx2/USB/qemu-usb/desc.h
pcsx2/USB/qemu-usb/input-keymap-qcode-to-qnum.cpp
pcsx2/USB/qemu-usb/qusb.h
pcsx2/USB/qemu-usb/usb-ohci.cpp

USB: Cleanup usb qemu.
Make it suck less.
Make it suck less, cleaner code.
Test USB Qemu if nothing regressed.

USB: Cleanup usb qemu.

---

bin/resources/shaders/dx11/convert.fx
bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/convert.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/Metal/convert.metal
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Improvements to RTA to make it more functional and accurate.
There were opportunities to improve things, so went ahead and did it.
More followup from https://github.com/PCSX2/pcsx2/pull/10853
Test random games including ones below, make sure everything is good.
Ace Combat:
Master:
PR:
Hitman 2:
Master:
PR:
Need for Speed Underground 2 (previously required medium blending)
Master:
PR:
Tales of the Abyss (difficult to see, look in the top right):
Master:
PR:
Ace Combat:
Master:
PR:
Ape Escape 2:
Master:
PR:
Bully:
Master:
PR:
God of War (This was a recent regression)
Master:
PR:
Hitman 2:
Master:
PR:
Jojo no Kimyou na Bouken
Master:
PR;
Mercenaries:
Master:
PR:
Need for Speed Underground 2:
Master:
PR:
Okage - Shadow King:
Master:
PR:
Spider-Man 3:
Master:
PR:
Star Wars Battlefront 2 (I …

GS/HW: RTA improvements and enhancements

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2-qt/Settings/EmulationSettingsWidget.ui
pcsx2/Pcsx2Config.cpp

Various bits and pieces and also fixes the nasty upscaled sun in NFS Most Wanted.
Fixes #10959 
Fixes #10976 
More good more fix.

Misc: gamedb updates, remove speed limiter setting

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Regression from #11010
Derp
@JordanTheToaster

GS/HW: Fix loading replacement textures

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/BIOSSettingsWidget.cpp
pcsx2-qt/Settings/BIOSSettingsWidget.h
pcsx2-qt/SetupWizardDialog.cpp
pcsx2-qt/SetupWizardDialog.h
pcsx2-qt/Tools/InputRecording/NewInputRecordingDlg.cpp

Qt: Fix BIOS list

---

pcsx2/CMakeLists.txt
updater/Updater.cpp
updater/Updater.h
updater/Windows/WindowsUpdater.cpp

Another regression from #11015.

Qt: Fix updater not cleaning up staging directory

---

common/vsprops/LinkPCSX2Deps.props
pcsx2-gsrunner/pcsx2-gsrunner.vcxproj

GSRunner: Fix build on Windows

---

pcsx2-qt/AutoUpdaterDialog.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtHost.cpp
pcsx2-qt/Settings/SettingsWindow.cpp
pcsx2-qt/Themes.cpp
pcsx2-qt/Translations.cpp
pcsx2/GS/GS.cpp
pcsx2/SIO/Memcard/MemoryCardFile.cpp
pcsx2/VMManager.cpp

This PR attempts to make more untranslatable strings be translatable.
Translation 100
See if the text shows up correctly, mainly the memory card section.

Qt: Translatification

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

herpy derpy the buffer was left undefindery
Fixes depth corruption in Breath of Fire - Dragon Quarter.
@JordanTheToaster

GS/Vulkan: Fix depth not clearing with first colclip draw

---

pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp

for the renderers that nobody uses

FullscreenUI: Fix images in DX11/GL

---

pcsx2/Achievements.cpp
pcsx2/Achievements.h
pcsx2/VMManager.cpp

Fixes #11098. 
Fixes #11101.
Test linked issue.

Achievements: Fix HC mode activating on reset of non-cheevo game

---

.github/workflows/scripts/macos/build-dependencies.sh
pcsx2/GS/GSCapture.cpp

- Adds ffmpeg 7 support (when compiling, the version required for dropping dlls into CI builds hasn't changed)
- ~~Drops ffmpeg 4 support~~
- Adds an option to the macOS CI build script to not build ffmpeg, so users can use their full (massive) homebrew ffmpeg instead of our cut down one
New ffmpeg yay
Make sure video capture still works

FFmpeg 7 support

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

We do a little fixing.
Fixes #11057 
Fixes #11074 
Game fix good.

GameDB/GS: Various fixes for db, remove getaway crc hack from gs

---

bin/resources/RedumpDatabase.yaml
pcsx2/VMManager.cpp

Updates the verification database and adds a warning about texture dumping being enabled.
More hash more verification more gooder.

RedumpDatabase: Update hash database

---

bin/resources/shaders/dx11/tfx.fx
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Use saturate instead of min max, saturate is faster than min max.
Brrr.
Smoke test dx/metal.

GS/HW: Minor shader optimization.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Always make sure rt is checked for date, no need for individual checks.
Code cleanup.
Cleaner code.
Smoke test, already tested with dump runner.

GS/HW: Cleanup date and rt alpha min max function.

---

pcsx2/INISettingsInterface.cpp

Yay for differences between Windows and Linux... the mktemp function Windows doesn't open the file, but Linux does, and returns the file descriptor.
Stops a file descriptor being leaked every time configuration is saved.
Test global and per-game configuration actually saves on Windows and Linux.

INISettingsInterface: Fix file descriptor leak on Linux

---

bin/resources/GameIndex.yaml

Say no more
Fixes #11174 
Missing text bad.

GameDB: Code Lyoko QFI fixes

---

cmake/CopyBaseTranslations.cmake

Unbreak stuff I broke in #11159 
Breaking things is bad
Make sure qt base translations are included in the build

CMake: Unbreak finding base translations

---

bin/resources/GameIndex.yaml

Fixes in game timer and split timer when in internal view.
Fixes #11171 
Timer working is good.

GameDB: CMR 2005 Timer fix

---

bin/resources/GameIndex.yaml

adds missing patches for games 
N/A , for @prafullpcsx2  to check

GameDB: patches for NHL 2K9 and  Major League Baseball 2K9

---

pcsx2-qt/Settings/InterfaceSettingsWidget.cpp
pcsx2-qt/Themes.cpp

Shamelessly ~~stolen~~ backported from Duckstation.
For anyone who doesn't have eyes and also does not like the default Windows 11 theme?

Qt: Add Classic Windows as theme option

---

pcsx2/ImGui/FullscreenUI.cpp

Mark %d ms for translation

---

pcsx2/Achievements.cpp
pcsx2/Gif.cpp
pcsx2/IopBios.cpp
pcsx2/Mdec.cpp
pcsx2/R5900OpcodeImpl.cpp

Misc: Cleanup and codacy warnings fixes.
Cleaner code.
CI passes, nothing broke.

Misc: Cleanup and codacy warnings fixes.

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Being incorrect is bad.
CI passes.

GS/DX12: Fix incorrect resource state of ImGui font

---

pcsx2-qt/Settings/InterfaceSettingsWidget.cpp

Fix a smol mistake because I am blind.
How could I have done this.

Qt: Fix copy paste fail

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/VKSwapChain.cpp
pcsx2/VMManager.cpp
pcsx2/VMManager.h

Also some extra logging to gain some insight into #11280.
Apparently users prefer stutter over tearing for PAL...
Smoke test Vulkan renderer.

GS/Vulkan: Prefer mailbox presentation for vsync-on

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Improves the CRC hack for Street Fighter EX3 to actually do the draw, but correct it for our Texture Cache handling. (and some potential input lag)
Previously we just skipped this effect which seemed to just be a downscale and copy, however after this it blends this copy (which got skipped) over existing frames too, meaning before it was copying old data, so it's possible you might see 1 frame behind what it's actually at, causing input lag.  On top of this it was causing a horrible shimmer every other frame (video below)
Test Street Fighter EX3, make sure everything works ok.
Video demonstration.  The left is the PR, the right is master, observe the horrible shimmering on the backdrop, Ryu and Chun-Li
https://github.com/PCSX2/pcsx2/assets/6278726/45439ff2-be11-43cf-8283-d71b33b11f32

GS/CRC: Improve Street Fighter 3 EX CRC to remove shimmer

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Tweaks offsets on complex clamps to try and reduce edge garbage.
a lot of games do single pixel offsets of textures, which the game things are much bigger, so when we upscale, there's a whole load of rescaling goes on and clamp ranges don't really get adhered to, this compensates for that somewhat making a lot of games which had rainbow garbage when using upscale fixed no longer have a problem.
Test games with Half-pixel Offset Normal or Align to Native (preferred).
Some of the known games affected:
Ace Combat 5 (very slightly)
Barnyard (2x seems to still be crap, very weird)
B-Boy
Devil May Cry 3
Dragonball Z BT3
Finny the Fish
Genji
Ghostrider
Guitar Hero games (all of them from 3 onward)
Hitman Blood Money
Nicktoons Unite
Onimusha 3 - Demon Siege
Outrun
Project Snowblind
Silent Hill …

GS/HW: Compensate for edges in complex clamps to reduce upscale garbage

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Improve some Tex in RT checks and fix a rect bug.
Bug bad, other things just tidy things up a little.
No known fixes after dump run, I guess a smoke test.

GS/HW: Improve some tex in rt handling

---

bin/resources/GameIndex.yaml

Spring? Guess it's summer now-cleanup and fixes with help from Tech and Link to make this mess bearable.
Fixes good.

GameDB: Various bodges

---

.github/workflows/windows_build_qt.yml

Instead of upgrading it, we haven't tested clang-18 with PCSX2 yet.

CI/Windows: Uninstall system LLVM package

---

bin/resources/GameIndex.yaml

Just adds a few fixes for NTSC-K versions of games that were overlooked.
Less glitches, less problems.
Make sure patches work.

GameDB: Some NTSC-K fixes

---

pcsx2-qt/VCRuntimeChecker.cpp

Backport https://github.com/stenzek/duckstation/commit/484c1dccd4ca588ce8b9bd11481695669eb6f5bc
Version check was wrong in #11361.
CI passes.

Qt: Use 64-bit comparison for VC runtime check

---

pcsx2/Achievements.cpp

Achievements: Fix incorrect data source for mastery points

---

common/Darwin/DarwinMisc.cpp

As discussed in #11364.
Less code.
CI passes, already tested.

DarwinMisc: Use template sysctlbyname

---

pcsx2/CDVD/CDVD.cpp

CDVD: Fix -Wsign-compare warnings.
Thanos snap warnings out of existence.
CI warnings are gone.

CDVD: Fix -Wsign-compare warnings.

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Correctly positions target copies when overlapping, also detects if the new target is covering the old target, even if it's not drawing to it (due to the height cache)
Sometimes targets can remain big in the height cache due to FMV's, but the copying code for putting old targets in to the new one was incorrect and putting it in the wrong place as it assumed the overlapping target butted up against the top of the new target.
Also added some code to pick the newer target if not getting exact targets for display.
Smoke test and Another Centurys Episode 3
Fixes Another Centurys Episode 3
Master:
PR:

GS/HW: When detecting target overlap, offset copy from base

---

pcsx2/COP0.cpp

The original implementation would map SPR to the proper eeMem->Scratch buffer ✔️ .
But only if the address was 0x70000000 (default SPR mapping) would it _not_ continue to map the entry normally ❌ .
From my understanding, this would overwrite SPR mappings not at 0x70000000, causing writes to these entires virtual pages to go elsewhere.
~~I needed content for my website 😎 ~~
This is more accurate behaviour.
Smoke test games? If you know of any games that modify TLB entries (SPR in particular) give that a try maybe.
Attached is an ELF that will remap SPR, write to the new SPR virtual page, and try to read back through the DMAs. If everything is good, 'passed' should be on the screen'.
[sprremap.zip](https://github.com/user-attachments/files/15937060/sprremap.zip)

COP0 TLB: Fix mapping ScratchpadRam Entries

---

bin/resources/GameIndex.yaml

3am brain forgot to not change HPO from what I found weeks ago.
I am the big dumb.

GameDB: GOW 2 revert to HPO Special

---

bin/resources/shaders/dx11/convert.fx

I had a noob moment.
Fixes #11482.

GS/DX11: Fix downsample uniform unpack

---

3rdparty/rcheevos/CMakeLists.txt
3rdparty/rcheevos/rcheevos.vcxproj
3rdparty/rcheevos/src/rcheevos/runtime_progress.c

Backports https://github.com/stenzek/duckstation/commit/71c319ccf0b2d45236aaafc31c26e8de6aaab706 and https://github.com/stenzek/duckstation/commit/5c94ab9f227509d7e21a91972decbcda7940926d
Backport fixes good for bones.

Deps: Backport more Duckstation commits

---

pcsx2/DEV9/PacketReader/IP/UDP/DHCP/DHCP_Options.cpp
pcsx2/DEV9/PacketReader/IP/UDP/DHCP/DHCP_Options.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Get rid of GetAFAIL duplicates.
DEV9: Fix function parameter should be passed by const reference warnings.
Cleanup..
CI passes.

Misc: Some cleanup

---

.github/ISSUE_TEMPLATE/emu_bug_report.yaml

mentions users should use the built in game verifier to prevent  not needed issues being made 
N/A

github:  mention to verify games if making an issue

---

bin/resources/GameIndex.yaml

Fixes the sun going supernova over the streets of LA.
Before:
After:
It looks rather gross and wrong.

GameDB: TC SOLA fixes

---

pcsx2-qt/Debugger/MemoryViewWidget.cpp
pcsx2-qt/Debugger/Models/BreakpointModel.cpp

Debugger: Cleanup warnings and casts.
MemoryViewWidget.cpp
BreakpointModel.cpp
Cleaner code.
CI passes, smoke test.

Debugger: Cleanup warnings and casts.

---

pcsx2-qt/Settings/ControllerBindingWidget.cpp
pcsx2-qt/Settings/USBBindingWidget_Buzz.ui
pcsx2-qt/pcsx2-qt.vcxproj
pcsx2-qt/pcsx2-qt.vcxproj.filters
pcsx2/CMakeLists.txt
pcsx2/USB/deviceproxy.cpp
pcsx2/USB/usb-pad/usb-buzz.cpp
pcsx2/USB/usb-pad/usb-buzz.h
pcsx2/USB/usb-pad/usb-pad.cpp
pcsx2/USB/usb-pad/usb-pad.h
pcsx2/pcsx2.vcxproj
pcsx2/pcsx2.vcxproj.filters

- Move Buzz device to dedicated files 
- Create custom UI for Buzz
Configure and test buzz controllers

USB: Move Buzz device to dedicated files and create custom UI

---

.github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in
pcsx2/Docs/PCSX2_FAQ.md
tools/generate_update_fa_glyph_ranges.py
tools/merge_ws_ni_patches.py
tools/texture_dump_alpha_scaler.py

Update the FAQ to reflect changes since v1.6.
FAQ was horribly out-of-date.
Make sure what I'm saying isn't nonsense.

Docs: Update FAQ

---

3rdparty/rcheevos/CHANGELOG.md
3rdparty/rcheevos/include/rc_api_info.h
3rdparty/rcheevos/include/rc_client.h
3rdparty/rcheevos/include/rc_client_raintegration.h
3rdparty/rcheevos/src/rapi/rc_api_common.c
3rdparty/rcheevos/src/rapi/rc_api_info.c
3rdparty/rcheevos/src/rc_client.c
3rdparty/rcheevos/src/rc_client_external.h
3rdparty/rcheevos/src/rc_version.h
3rdparty/rcheevos/src/rcheevos/runtime_progress.c
3rdparty/rcheevos/src/rhash/hash.c

Brings rcheevos up to date with current release.
Fix good.
Make sure achievements still function.

3rdparty/rcheevos: Bump to v11.5.0

---

.github/workflows/cron_update_controller_db.yml

workflows: Update sdl controller db script.
Remove reviewers.
Add proper branch name.
Add branch deletion if there is no open pr(either closed or merged).
~~I want the bot to leave me alone~~
Update script.
N/A

workflows: Update sdl controller db script.

---

bin/resources/GameIndex.yaml

The terrible game has stutters due to VIF1 not terminating so let's fix that with InstantDMA and hopefully never have to touch this game again.
Fixes #11682 
Fixes #10849 
The stuttering is atrocious. 
Pray the CI passes.

GameDB: Snow White and the 7 shovelware PS2 games

---

bin/resources/GameIndex.yaml

fixes CRC for COP2 patch 
stop  Invalid CRC errors 
N/A

GameDB : fix  Test Drive Unlimited CRC for patch

---

3rdparty/imgui/include/imconfig.h
3rdparty/imgui/include/imgui.h
3rdparty/imgui/include/imgui_internal.h
3rdparty/imgui/include/imstb_textedit.h
3rdparty/imgui/src/imgui.cpp
3rdparty/imgui/src/imgui_demo.cpp
3rdparty/imgui/src/imgui_draw.cpp
3rdparty/imgui/src/imgui_freetype.cpp
3rdparty/imgui/src/imgui_tables.cpp
3rdparty/imgui/src/imgui_widgets.cpp
3rdparty/imgui/src/imstb_truetype.h

Bumps imgui to v1.91.0.
New features and bug fixes do be good.
Make sure BPM and other functions work correctly.

3rdparty/imgui: Update to v1.91.0

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

adds a description of texture filtering
old description wasn't a real description
if it compiles and text shows it's fine.

Qt: Update Texture Filtering Description

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Adds a description of trilinear filtering.
Old description wasn't a real description.
if it builds and the text shows it's fine.

Qt: Update Trilinear Filtering Description

---

pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp

Fix Konami Capture Eye assert
Fix Konami Capture Eye assert
none

USB: Fix Konami Capture Eye assert

---

pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/Themes.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/ImGui/ImGuiFullscreen.cpp
pcsx2/ImGui/ImGuiFullscreen.h

Backport from DuckStation.
See commits for list of changes.
Giving love to the UI.
See if i broke anything.

Qt/FSUI: Various Fixes

---

pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/GSBlock.h

Changes video max bitrate to 200,000kbps default audio from 160kbps to 192kbps and adds a missing name I forgot to add previously.
More quality more good.

Misc: Minor cleanup

---

bin/resources/GameIndex.yaml

To fix the sps in #11707 and the rounding bugs in #11528

GameDB: Add multiple fixes

---

pcsx2/IopBios.cpp

An iterator invalidation bug in R3000A::loadcore::ReleaseFuncs has been fixed. My [symbol table PR](https://github.com/PCSX2/pcsx2/pull/10224) introduced it.
Crashing is bad (except if it's Burnout).
N/A

DebugTools: Fix iterator invalidation bug in IopBios.cpp

---

pcsx2/DebugTools/ExpressionParser.h

Add missing include in ExpressionParser.h

---

common/FileSystem.cpp

Skip over the root of the path when creating directories recursively on Windows.
The existing logic would call `CreateDirectoryW()` when it encounters a directory separator
As the path would something like `\\?\C:\foo\bar` we would try to create a directory using an empty string.
As mentioned here https://github.com/PCSX2/pcsx2/issues/11784, only two locations use this,
Once in [QtHost.cpp](https://github.com/PCSX2/pcsx2/blob/7d6f74083ba656f7de0a6a2148be4851bf987620/pcsx2-qt/QtHost.cpp#L1596), which itself is only used to download fonts and currently doesn't need recursive directory creation.
Once in [MemoryCardFolder.cpp](https://github.com/PCSX2/pcsx2/blob/7d6f74083ba656f7de0a6a2148be4851bf987620/pcsx2/SIO/Memcard/MemoryCardFolder.cpp#L2000), which I think gets called when PS2 games …

Common: Fix Recursive CreateDirectoryPath() on Windows

---

pcsx2/ImGui/FullscreenUI.cpp

FullscreenUI: Remove unused function CopyGlobalControllerSettingsToGame.
Cleanup.
CI passes.

FullscreenUI: Remove unused function.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Merge blend ad a mask separate conditions in to one.
Duplicate code.
CI passes.

GS/HW: Merge blend ad a mask separate conditions in to one.

---

.github/workflows/scripts/common/update_base_translation.sh

This PR adds the other translations related housekeeping scripts to our daily translation update Github CI Workflow.
No more forgoring 💀
Hopefully the CI is happy

CI: Add other translations related scripts to the daily workflow

---

pcsx2/DEV9/smap.cpp

Iterate though BDs that are ready to send, instead of using the frame counter.
HW does not use the frame counter to determine how many packets to send.
PSBBN relies on this behaviour.
If any other software had `DEV9: SMAP: WARN : (fc!=cnt || cnt==0) but packet send request was made oO..` this PR may also help them.
Fixes #11895 
Test network games
Test network homebrew

DEV9: Rework tx_process based on HW tests

---

pcsx2-qt/Translations/pcsx2-qt_zh-CN.ts

Translations: hotfix a translation mistake causing fmt to crash

---

pcsx2-qt/Settings/DebugSettingsWidget.cpp

Fixes a minor typo I had
SIF trace logging was broken
Test SIF trace logging

TraceLogging: Fix SIF trace logging

---

bin/resources/GameIndex.yaml

Garbage side-screen on pachislot machines. 
Closes #12004 
Make sure the issue's GSDump is clean

GameDB: Add TexInRT on SLPM-62482

---

pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.cpp
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_In.cpp
pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_Out.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_Session.cpp
pcsx2/DEV9/flash.cpp
pcsx2/DEV9/net.cpp
pcsx2/DEV9/net.h
pcsx2/DEV9/pcap_io.cpp
pcsx2/DEV9/pcap_io.h
pcsx2/DEV9/smap.cpp
pcsx2/DEV9/sockets.cpp

DEV9: Code cleanup.
Casts, constants, unused functions, switch cases.
Code cleanup.
CI passes, dev9 still works.

DEV9: Code cleanup.

---

pcsx2/CDVD/CDVDdiscReader.cpp

Correct DevCon log call
This failed to compile with a Debug build
Build Debug

CDVD: Fix DevCon log typo

---

pcsx2-qt/Debugger/DebuggerWindow.ui
pcsx2-qt/MainWindow.ui
pcsx2-qt/QtHost.cpp
pcsx2-qt/resources/icons/black/svg/magnifier-line.svg
pcsx2-qt/resources/icons/white/svg/magnifier-line.svg
pcsx2-qt/resources/resources.qrc
pcsx2/Achievements.cpp

This PR mainly fixes the Verbose Status formatting that i busted from the last PR (oops!)
Before:
After:
Other changes includes:
- Moving the Video Capture option from Tools to System
- New icon for Debugger Analyze menu
Consistency and better formatting.
Make sure i didn't miss anything obvious this time for real

Qt: Misc Fixes and Additions

---

.github/workflows/cron_update_controller_db.yml

Disables builds on weekly controller database update
make sure i haven't broke anything and thats its done correctly

CI: disable builds on controller database update

---

pcsx2/DebugTools/SymbolGuardian.h

DebugTools: Fix GCC build, missing include

---

bin/resources/RedumpDatabase.yaml

updates redump datatbase tio latest update 
more things update is good 
make sure verifying games works on all platforms

redump : update database

---

bin/resources/GameIndex.yaml

I fixed few wrong Japanese titles and add missing title.
I want make useful game list for Japanese users.
Please, Check diff.

Fix&Add few Japanese Game Titles

---

bin/resources/GameIndex.yaml

fixes some names in the Gamedb
fixes : #12149
watch CI

GameDB: fix some names

---

bin/resources/GameIndex.yaml

GameDB: Rename Dynasty Warriors 3 and 4.
SLES-51441: Dynasty Warriors 3 - Extreme Legends -> Dynasty Warriors 3 - Xtreme Legends
SLUS-20812: Dynasty Warriors 4 - Extreme Edition -> Dynasty Warriors 4 - Xtreme Legends
Fixes https://github.com/PCSX2/pcsx2/issues/12153
CI passes.

GameDB: Rename Dynasty Warriors 3 and 4.

---

pcsx2/x86/iR3000A.cpp
pcsx2/x86/ix86-32/iR5900.cpp

iR3000A/iR5900: Fix dev/debug build compile.
Remove JITCompileInBlock leftovers.
Fix dev/debug build compile.
Dev/debug compile.

iR3000A/iR5900: Fix dev/debug build compile.

---

bin/resources/GameIndex.yaml

- Added VU1 Clamping (Extra + Preserve Sign) to Ougon no Kaze (SLPM-61030, SLPM-65140, SLPM-66853) 
- Changed "Jojo" romanization to "JoJo" in Ougon no Kaze [Best Price] (SLPM-66853) and Phantom Blood (SLPS-25686)
- Changed "Kimyouna" to "Kimyou na" in Ougon no Kaze [Best Price] (SLPM-66853)
The new VU1 Clamping mode set for Ougon no Kaze fixes the shading of the enemy's Stand in Chapter 11-2.
Before:
After:
As for the title changes:
- The second "Jo" in "Jo**J**o" is written capitalized officially across the series since it's derived from the recurrence of "Jo" in their protagonist's names. Ougon no Kaze and Ougon no Kaze [Trial] already used "JoJo", so changing the others makes it consistent.
- Only Ougon no Kaze [Best Price] used "Kimyouna", while other editions used "Kimyou na", so I …

GameDB: Change VU1 clamping on Ougon no Kaze, fix some JoJo names

---

pcsx2/Host.h

host: fix gcc build

---

pcsx2/vtlb.cpp

Like what I did with SSE2 intrinsics, optimize the EE cache lookup function.
This brings the kill.switch main menu from ~9.5 to ~11.5 on my mini M4 pro.
More speed.
Test the EE cache on an ARM64 system, with PCSX2 compiled for ARM64.

R5900: Implement ARM NEON intrinsics for the EE cache

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Check for null when source is either target or depth.
Crash fix for DT racer.
There are other crash related issues but will have to wait after RT in RT is merged.

GS/HW: Check for null when source is either target or depth.

---

.github/workflows/linux_build_matrix.yml

fixes names of linux artifacts 
was wrong 
check build names

CI : fix artifact name on linux builds

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Account for index 0.
Bugfix.
None.

GS/HW: Adjust max valid tex size.

---

pcsx2/x86/Vif_Dynarec.cpp

Fixes non-volatile SSE backup and restore logic that was added in https://github.com/PCSX2/pcsx2/pull/12232
I had introduced a bug in the save/restore logic late in the PRs development while cleaning up code, which potentially nullified the point of the pr.
I had also missed that `makeMergeMask` modifies the passed parameter, this would result in the logic I added to determine if a temporary register was needed, and the logic that actually used that register getting different answers
Test Midnight Club, along with other games

Vif: Fixes to non-volatile SSE backup and restore logic

---

bin/resources/GameIndex.yaml
pcsx2/PerformanceMetrics.cpp

Just some more fixes I forgot to include in the other gamedb PR oops, fixes for Arc the Lad End of Darkness for some reason not having Tex in RT??? Action Mans depth line and forcing high blend on Avatar The Last Air Bender.
Fixes #12281  

GameDB/PerformanceMetrics: Various fixes

---

bin/resources/GameIndex.yaml

The never ending cycle of hate for myself after adding fixes to the approximately 130,000 MGS 2 serials is palpable. Also fixes Tomb Raider Anniversary having broken textures due to HPO ATN and some blending recs for Mercenaries 2 I guess.
The less game that are is broke is good yes.

GameDB: Even more fixes

---

bin/resources/GameIndex.yaml

Fixes light leak and fire intensity in Knighs of the Temple 2.
Fixes #12298 
Before:
After:

GameDB: Knights of the Temple 2 fixes

---

.github/workflows/scripts/releases/announce-release/index.js

Fixes a regression from the dependabot version bumps

CI: Update the announce-release script to use node-fetch

---

.github/workflows/linux_build_qt.yml
.github/workflows/macos_build.yml
.github/workflows/macos_build_matrix.yml
.github/workflows/release_cut_new.yml
pcsx2/CMakeLists.txt
pcsx2/Resources/PCSX2.entitlements

Sign macos binaries
Hopefully 🤞 helps with gatekeeper blocking our release builds
Download the artifact and see if it is signed

MacOS: Sign and notarize macos binaries

---

pcsx2/VUops.cpp
pcsx2/VUops.h

Makes ABS and FTOI handle large floats properly
Also cleanup
Same reasoning as #12322, though the recs were already accurate for these, so even less likely anything will break
Test interpreter, make sure I didn't break anything

Interpreter: Accurate ABS and FTOI

---

pcsx2/VUops.cpp

Replaces 47 functions with 5
Looking at the diff in #12001 was painful
Test interpreter, make sure I didn't break anything

Interpreter: VUops.cpp cleanup

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Modify how the offset for textures is calculated
Before I used kinda weird guess numbers to calculate texture offsets, this is more mathematical :P This fixes some games which weren't quite right. Also some fixes for upcoming changes with RT in RT
test games that use WTO or suffered from it being much worse ATN before.
Improves God of War at higher resolutions, example at x12:
Master:
PR:

GS/HW: Tweak offsets for textures using ATN WTO

---

pcsx2-qt/Debugger/SymbolTree/SymbolTreeWidgets.cpp
pcsx2/Vif_Codes.cpp

Misc: More warning fixes.
Clean up more compiler warnings.
CI passes.

Misc: More warning fixes.

---

bin/docs/ThirdPartyLicenses.html

was missed in #12241
watch CI / read Third-Party Licenses

add KDDockWidgets to Third-Party Licenses

---

3rdparty/cpuinfo/src/arm/mach/init.c

Fixes CPU detection for Apple Silicon SOCs on Mac.
Broken name bad.

3rdparty: Fix Apple Silicon detection with cpuinfo

---

pcsx2-qt/MainWindow.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/VMManager.cpp

Actually enable it by default with new configs for actually realsy this time true true.
It working would be nice.
Make sure it actually works this time _you know who you are_

VMManager: Actually enable file logging by default for real this time

---

3rdparty/imgui/include/imconfig.h
3rdparty/imgui/include/imgui.h
3rdparty/imgui/include/imgui_internal.h
3rdparty/imgui/src/imgui.cpp
3rdparty/imgui/src/imgui_demo.cpp
3rdparty/imgui/src/imgui_draw.cpp
3rdparty/imgui/src/imgui_freetype.cpp
3rdparty/imgui/src/imgui_tables.cpp
3rdparty/imgui/src/imgui_widgets.cpp

Updates ImGui to v1.91.9b.
Keeping this up to date will prevent future migraines trying to fix it when it inevitably breaks.
Make sure the UI OSD big picture ect all still function and the CI is a happy boyo.

3rdparty: Update ImGui to v1.91.9b

---

pcsx2-qt/pcsx2-qt.vcxproj.filters

The source files are now organized better in the Visual Studio solution explorer.
Previously the source files weren't organized well in the Visual Studio solution explorer.
Check that the source files appear to be organized well in the Visual Studio solution explorer.

Debugger: Fix Visual Studio filters

---

pcsx2/ImGui/FullscreenUI.cpp

Apparently this wasn't added to BPM, so now its here.
Parity with Qt.
Make sure the option is working.

BPM: GPU CLUT to FSUI

---

3rdparty/cpuinfo/include/cpuinfo.h
3rdparty/cpuinfo/src/arm/api.h
3rdparty/cpuinfo/src/arm/mach/init.c
3rdparty/cpuinfo/src/arm/uarch.c
3rdparty/cpuinfo/src/arm/windows/init-by-logical-sys-info.c
3rdparty/cpuinfo/src/arm/windows/init.c
3rdparty/cpuinfo/src/arm/windows/windows-arm-init.h
3rdparty/cpuinfo/src/x86/isa.c
3rdparty/cpuinfo/src/x86/linux/cpuinfo.c

Updates CPUInfo to the latest commit which has the local fix for AS SOCs.
Less bodge more worky code good.
Make sure CPU detection still functions correctly.

3rdparty: Update CPUInfo to commit 5e3d2445e6a84d9599bee2bf78edbb4d80865e1d

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Don't use coverage when doing Af or Ad blend.
Bugfix.
Dump run ok, FFX show's minor difference on the minimap, nothing noteworthy.

GS/HW: Don't use coverage when doing Af or Ad blend.

---

pcsx2-qt/QtHost.cpp

Clean up the settings save timer before quitting the GUI event loop.
It seems QTimer doesn't like being destroyed from a global destructor. This silences the following warning which was previously printed if you quit PCSX2 within 1 second of modifying a setting (observed on Linux):
```
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
``` 
Try and reproduce the warning with and without the fix.

Qt: Destroy settings save timer before quitting

---

pcsx2-qt/Themes.cpp

Change the default theme for a nice little bit of eye-candy ;)
NOTE: This will not affect existing installs, only fresh installs.
~~Grey Matter theme aims to be soothing and easy on the eyes.~~
A little touch up for the interface.
See if the theme are correctly set on fresh install.

Qt: Change Default Theme

---

common/Darwin/DarwinMisc.cpp
common/HostSys.h
common/Linux/LnxMisc.cpp
pcsx2/CDVD/ThreadedFileReader.cpp
pcsx2/VMManager.cpp

Follow up from https://github.com/PCSX2/pcsx2/pull/12525 for linux/mac.
Feature parity.
Fixes https://github.com/PCSX2/pcsx2/issues/12532
Check if precaching woks as intended, also check if the log displays proper available ram.

CDVD: Adjust ram requirements when precaching on linux/Mac.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

GS/HW: Rename GSC_Tekken5 to GSC_NamcoGames.
Multiple games use it.
Generalized/consistency.
Smoke test affected games.

GS/HW: Rename GSC_Tekken5 to GSC_NamcoGames.

---

bin/resources/RedumpDatabase.yaml
tools/generate_redump_yaml.py

updates redump datatbase to latest update and updates the  generate_redump_yaml.py script 
more things updated is good
make sure verifying still works

Deps: update redump database

---

.github/workflows/linux_build_flatpak.yml

Addresses https://github.com/flathub-infra/flatpak-github-actions/issues/17
See if the CI passes and check the Flatpak build

CI: Use the upstream Flatpak action

---

.github/ISSUE_TEMPLATE/emu_bug_report.yaml

remove  links to not avaible articles 
the 2 articles in question were removed a good while ago  and theirs no point in linking them 
N/A

issues/Github : remove  unused links

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/HW: Make sure we pass src to PreloadTarget.
Fixes https://github.com/PCSX2/pcsx2/issues/12578
Already tested, dump run is fine.

GS/HW: Make sure we pass src to PreloadTarget.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Enable tex-is-fb on channel shuffles when barriers aren't supported.
Accuracy, make dx suck less.
Dump run on dx11 and vk looks good.
Also expect a speed bump on Hitman and Malice since there are less texture copies.
Fixes Hitman Blood Money on DX.
Fixes SWAT Global Strike on DX.

GS/HW: Enable tex-is-fb on channel shuffles when barriers aren't supported.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GS/HW: Update logs.
Cleanup/remove some logs, name them properly with HW prefix.
Cleanup.
CI passes.

GS/HW: Update rendererhw and tc logs.

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

gs: Missing cmath include

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Adjust blending when tex is fb.
Prefer sw blend when it's a channel shuffle with barriers enabled. Prefer sw blend if it's tex is fb when there is no overlap, fb is already being read so we can use sw blend.
Swap full barriers with one barrier if it's a channel shuffle, prims shouldn't overlap anyway.
Accuracy.
Test Hitman, NFS games, other random stuff that uses shuffles or tex is fb.
Both games are better on DX11 and VK, the difference on VK is very small compared to DX11, much more noticeable.
No barrier or copy increases or decreases in either renderer, will be the same for the other renderers.
Didn't spot anything broke on either dx11 or vk dump runs.
NFS Underground 2
DX11 basic blending master
DX11 basic blending pr

GS/HW: Adjust blending when tex is fb.

---

bin/resources/GameIndex.yaml

Adds fixes such as ATNWTO to around 104 games and adjusts the names of even more. Don't ask me what I fixed I don't even remember at this point.
ATNWTO is pretty good.
Make sure the CI passes.

GameDB: RT in RT Part Deux

---

bin/resources/GameIndex.yaml

Have some more fixes because my memory is that of a goldfish.
More fixes means more good.
Make sure CI is happy boyo.

GameDB: Various Fixes Part 3 Because I Forgot More

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Move texture sampling before EmulateBlending.
Tex is fb setting is done in Texture sampler which resulted in hw blend being applied before with barriers on.
Tex is fb can use sw blend so this optimizes that with no cost.
Also fixes an issue where hw blend was on with fbfetch.
Bugfixes, accuracy improvements.
Dump run looks good, test variety of stuff.
VK test results, basic blending, GL will be the same, sadly no DX improvements this time as the cases were covered in my previous PRs.
Some notable changes, the others are very minor or not visible to the eye so not worth posting.
Eragon Master:
PR:
Knights of the Temple Master:
PR:
Mission Impossible Master:
PR:

GS/HW: Move texture sampling before EmulateBlending.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS/HW: Clean up HandleTextureHazards.
Warnings, initializations, dereferencing null pointers.
Clean up.
CI passes.

GS/HW: Clean up HandleTextureHazards.

---

.github/workflows/triage_pr.yml

fixes broken redirect 
broke things bad 
make sure the link works 
no

[ci skip]   fix a broken link

---

bin/resources/GameIndex.yaml

Game has half screen missing this is bad.
Fixes #12765 
Game not being broken is good.
CI passes is good.
Nein.

GameDB: Fix half right issue with Xtreme Bowling

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Offsets the draw if Z is offset inside the target and FRAME/RT is disabled.
Oversight when doing RT in RT, wasn't expecting this to be a thing, but here we are.
Test Mobile Suit Gundam - One Year War (or attached GS Dump), nothing else is affected.
No
Mobile Suit Gundam - One Year War:
Master:
PR:
Extract this zip file and load it in to PCSX2
[Mobile Suit Gundam - One Year War_SLPS-25478_20250609211212.gs.zip](https://github.com/user-attachments/files/20659927/Mobile.Suit.Gundam.-.One.Year.War_SLPS-25478_20250609211212.gs.zip)

GS/HW: Allow RT in RT offset on Z buffer if FRAME is disabled

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Uses the simpler/faster function when depth matches and it doesn't require any weird swizzling
This is kind of a workaround for a problem in the DirtyRectByPage function if the whole of the depth is covered by the write, where it only invalidates the valid area.  While not completely wrong invalidating the whole target size could be considered wrong too, I suspect that does break a game, but I'm not sure, don't really want to mess with it.  So someone's TODO for the future I guess is to deal with invalidations on resize, but that's a bigger job that I want to put in now.
That said, there was no need to use such an intricate function when the write size, format and dimensions all match the original target.
Test Kamen Rider, possibly FFX too (but this didn't show up on the dump run and …

GS/HW: Correct invalidate function used for depth on match

---

pcsx2-gsrunner/Main.cpp

Fixes broken compilation of the gsrunner.
It being broke is bad.
Make sure it compiles now.
No.

GSRunner: Fix broken compilation

---

.github/ISSUE_TEMPLATE/emu_bug_report.yaml

Updates the OS list to include current and upcoming Mac OS versions. Also updates example hardware to more modern examples.
I don't think Mac OS froze at version 14.
N/A
No

GitHub: Update bug report OS list

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml

Updates the other form with up to date OSes.
Ya boy forgot.
N/A
Beep Boop

[ci skip] Github: Update app bug report OS list

---

pcsx2/GS/Renderers/Vulkan/VKLoader.h
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/IopBios.cpp

Fix/silence compiler warnings, see commits for description.
Fixes/silences compiler warnings.
Check CI, smoke test FSUI.
No.

Misc: Fix/silence compiler warnings.

---

pcsx2/ImGui/FullscreenUI.cpp

Shrink down cover if default size would cause text to be rendered off screen
Adjust text spacing scale with layout
Adjust centring of truncated text
Would be nice if all the details was visible in the selected preview panel
When writing the estimation logic, I noticed some spacing values weren't scaled, now they are.
Add more exact centring logic for title and increase the TextWrapPos.
The UI can behave weirdly If the title is _just_ on the edge of needing wrapped (even after we truncate it)
The above changes tries to give us a little bit of headroom to avoid that.
This was probably an overengineered solution to the problem, but I assume the original height was picked for a reason.
Open the BPM Game list, select a game and look at the selected preview
No

FSUI: Improve layout scaling in games list selected preview

---

bin/resources/GameIndex.yaml

Adjusts fixes for shadow hearts 2 and 3 to fix issues with those games.
Make sure CI is hap boyo
No

GameDB: Shadow Hearts fixes

---

.github/workflows/scripts/linux/appimage-qt.sh

Specify `waylandcompositor` module to trigger a copy of the needed wayland (non-platform) plugins
Remove an unneeded of `libQt6WaylandEglClientHwIntegration`
Swap to the non-depreciated var for libraries.
Moves the plugin deployment work into linuxdeploy and simplifies our scripts
We end up copying an extra file (`libQt6WlShellIntegration`) as a dependency of  `wayland-shell-integration`, which apparently wasn't causing problems before?
`libQt6WaylandEglClientHwIntegration` was already being copied as a dependency of one of the wayland platform plugins.
Test to make sure the appimage still works
extract the appimage to make sure it has the right amount of files
No

CI/Appimage: Simplify how we bundle Wayland plugins

---

3rdparty/fmt/ChangeLog.md
3rdparty/fmt/README.md
3rdparty/fmt/include/fmt/base.h
3rdparty/fmt/include/fmt/chrono.h
3rdparty/fmt/include/fmt/color.h
3rdparty/fmt/include/fmt/compile.h
3rdparty/fmt/include/fmt/format-inl.h
3rdparty/fmt/include/fmt/format.h
3rdparty/fmt/include/fmt/ostream.h
3rdparty/fmt/include/fmt/ranges.h
3rdparty/fmt/include/fmt/std.h
3rdparty/fmt/include/fmt/xchar.h
3rdparty/fmt/src/fmt.cc

Updates fmt to v11.2.0.
Bug fixes and warning fixes yipiee.
Make sure the CI passes and PCSX2 functions as normal.
Nej

3rdparty: Update fmt to v11.2.0

---

pcsx2/DebugTools/BiosDebugData.cpp

Check to see if we have a valid VM before reading IOP memory, and add a maximum iteration count in getIOPThreads.
- Maybe fixes #12962.
- Prevent a crash if the IOP thread list gets corrupted such as to contain a cycle somehow.
See if it fixes the issue referenced.
No.

Debugger: Improve error handling in getIOPThreads and getIOPModules

---

pcsx2/ImGui/FullscreenUI.cpp

https://github.com/user-attachments/assets/264e2e76-3bb7-4e86-b6f4-c8df829142b1
Added memory card creation to FullscreenUI
Before, memory card creation was only available through the Qt interface, requiring users to go to the Qt settings menu to create new memory cards. This made it hard for those using FullscreenUI exclusively.
**Basic Functionality:**
1. Open FullscreenUI and navigate to Memory Card settings
2. Click "Create Memory Card" button
3. Test input validation:
- Try empty names (should show error)
- Try names with dots (should be automatically removed when you make the card)
- Try duplicate names (should show error)
4. Test all memory card types (PS2 8MB/16MB/32MB/64MB, PS1, Folder)
**Windows specific NTFS Compression:**
1. On Windows, create file-based memory cards (PS2 …

FSUI: Add memory card creation dialog

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Valids and drawn since last read doesn't match, keep the target but resize it.
Fixes https://github.com/PCSX2/pcsx2/issues/13118
Fixes https://github.com/PCSX2/pcsx2/issues/13117
Dump run looks fine, the linked issues are fixed.
Test the linked issues above, test other games.
No.

GS/TC: Resize target instead of deleting it.

---

pcsx2-qt/Settings/FolderSettingsWidget.ui

Clarifies what the option does. 
The option effects both screenshots and gs dumps, users should be aware. 
N/A, check the option still works.
No.

UI: Correct game-specific folders option label

---

bin/resources/GameIndex.yaml

Fixes missing shadows and indicators.
Without:
With:
Missing shadows bad.
No

GameDB: Summoner missing shadows fix

---

pcsx2-qt/Debugger/Breakpoints/BreakpointModel.cpp

Debugger: Update description in breakpoint model to be translatable.

---

pcsx2/x86/iMMI.cpp

More fixes for stuff I broke in #13158
Less broken
Test games that were still broken after 2.5.128
No

iMMI: Unbreak MSUBW and MULTW

---

bin/resources/GameIndex.yaml

Fixes half right issues using Tex in RT.
Fixes #13190 
CI pass good.
No

GameDB: Jumanji half right fixes

---

pcsx2-gsrunner/test_run_dumps.py

DumpRunner: Fix race condition when creating files/folders, set process priority to below normal.
Fixes race condition when running in parallel multiple threads when creating dump folder/files.
Makes the process priority below normal so the system remains more usable even with more threads.
Bugfixes, optimization.
Already tested, could run the dump runner, see if you can trigger a race condition, check if old dumps overwrite or not, check if new dumps properly are created.
No.

DumpRunner: Fix race condition when creating files/folders, set process priority to below normal.

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp

Under certain circumstances when RC1 or RC2 are enabled, the output of one or the other will not actually be used (e.g., alpha is set so that the blended image of RC1 and RC2 is just RC2). In such cases do not lookup the texture.
Looking up RC output that is not used can create an invalid target if the RC settings are wrong. The invalid target could hang around in the texture cache and be used in later frames causing graphical bugs.
Fixes https://github.com/PCSX2/pcsx2/issues/13241
Fixes https://github.com/PCSX2/pcsx2/issues/13252
Side note: Might be useful to add one of these dumps to the dump pack.
In a full dump run with HW did not see any other regressions or improvements. No changes in other draw stats noticed.
Testing random games would be helpful to make sure nothing is broken, …

GS: Ignore output on RC1/2 when the data is not used.

---

pcsx2/GS/GSCapture.cpp

Allow users to select the device to use for hardware encoding by setting `vaapi_device=` or `hwaccel_device=` in the video capture parameters
Allow users to use GPUs other than the default to encode
Try to encode with a non-default device
No

GS:Capture: Allow selecting hardware device

---

.github/workflows/linux_build_flatpak.yml

see: https://github.com/flatpak/flatpak-github-actions/pull/231
Not entirely sure, was just told I should update
See if the flatpak still works
No

CI: Update Flatpak builder action version

---

bin/resources/GameIndex.yaml

Fixes some physics issues in the game by using EE Full clamping.
Fix game good and I forgot to add this to an earlier PR woops.
No

GameDB: Hot Wheels Beat That fixes

---

3rdparty/fmt/ChangeLog.md
3rdparty/fmt/README.md
3rdparty/fmt/include/fmt/args.h
3rdparty/fmt/include/fmt/base.h
3rdparty/fmt/include/fmt/chrono.h
3rdparty/fmt/include/fmt/color.h
3rdparty/fmt/include/fmt/compile.h
3rdparty/fmt/include/fmt/format-inl.h
3rdparty/fmt/include/fmt/format.h
3rdparty/fmt/include/fmt/os.h
3rdparty/fmt/include/fmt/ostream.h
3rdparty/fmt/include/fmt/printf.h
3rdparty/fmt/include/fmt/ranges.h
3rdparty/fmt/include/fmt/std.h
3rdparty/fmt/include/fmt/xchar.h
3rdparty/fmt/src/fmt.cc
3rdparty/fmt/src/format.cc
3rdparty/fmt/src/os.cc

Updates fmt from 11.2.0 to 12.0.0
Bug fixes and speed go brr.
Make sure all OSes don't go boom.
No

3rdparty: Update fmt to 12.0.0
