PCSX2/pcsx2

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Remove an unnecessary TBW check that I left in #7283 
That TBW check broke Ape Escape 3's pause menu. I added it originally to combat issues with Dog's Life, but I wasn't sure whether it actually contributed anything to the fix, since I added it along with checking whether source TBP is more or equal to the target's TBP. Turns out Ape Escape 3 is downloading PSMT4 data in parts, so the TBW for that is different, which resulted in the download not going through.
Test Ape Escape 3 by trying to go to the pause menu. It shouldn't have any glitches present.

GS/TextureCache: remove an unnecessary TBW check

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

code does 0-7 for points (inclusive) and 0-8 for anything else (exclusive)
Ace Combat 5 had some misdetection on a 58x64 texture, which in turn broke the UI (for some reason..) anyway, it shouldn't have been detecting it, so I've enforced a size restriction to be the width of possible CLUT's only.
test clutty games, make sure clutty, ain't busty.

GS: Restrict SW CLUT draw widths to multiples of 8

---

bin/resources/GameIndex.yaml

Resident Evil 4 / BioHazard 4: Fixes invisible wall in front of the door leading to East 3F in the 2nd visit of Apartment world preventing Eileen's Nurse Outfit. Some entries had missing fixes or entirely not in GameDB.
Video by Ryudo:
https://user-images.githubusercontent.com/24227051/199619271-3b909ed2-ab78-4db1-8906-d90f1b4bbf89.mp4
Umisho: Minor upscaling line issue fix for QTE event.

GameDB: Resident Evil 4 (BioHazard 4) + Umisho

---

bin/resources/GameIndex.yaml

Silent Hill 4: Fixes invisible wall in front of the door leading to East 3F in the 2nd visit of Apartment world preventing Eileen's Nurse Outfit. (accidentally did Resident Evil 4 instead)
Video from Ryudo:
https://user-images.githubusercontent.com/24227051/199623355-012374ef-2ea4-4c61-a364-b8d6c4fd9295.mp4
Wrong settings were applied.
Testing for Silent Hill 4.

GameDB: Silent Hill 4

---

bin/resources/GameIndex.yaml

To quote comment in gamedb: `Fixes rare bug causing player to respawn when starting the race or during certain car crashes.`
[The bug was originally described here](https://retroachievements.org/viewtopic.php?t=16717&c=134961#134961), I can confirm I encountered it when developing achievements for this game, but didn't bother figuring out the fix. Eventually it was found out clamping setting does help when testing it on the save state provided in that forum thread.
It's rare but gamebreaking bug worth preventing, otherwise player would have to exit and re-enter the race which loses progress.

GameDB: WRC Rally Evolved - Fix rare bug causing player to respawn unexpectedly

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Restricts the age of a target for download to 30 frames (probably still too much tbh!)
While #7283 improved the detection of render targets that were required for download, it also introduced some misdetection because of old targets hanging around in the texture cache. So like the final display target lookups, we can restrict this one to 30 frames or less.  Armored Core - Last Raven was affected by this (targets were 371 frames old!).
Test games with GS downloads (readbacks, in most cases), make sure nothing is broken.

GS: Restrict age of targets for GS Download invalidation.

---

bin/resources/GameIndex.yaml

Add HPO Special Texture to DDA, same for Super Trucks + Half Round Sprite for FMV lines.
Shadows were misaligned when upscaling in DDA.
Fog lines and lines in FMV's with Super Trucks.
Watch CI

GameDB: HPO for Destruction Derby Arenas + Super Trucks Racing

---

bin/resources/GameIndex.yaml

disable MTVU for K1-Dynamite series games
less crashing 
test games , check CI

GameDB: disable MTVU & instantVU for K1 series games

---

bin/resources/GameIndex.yaml

Adds Autoflush to Tales of the Abyss as an auto fix.
Fixes post processing effects for lighting (see below)
Before:
After:
Software:

GameDB: Add autoflush to Tales of the Abyss. Fixes lighting post

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Restricts the widths of detected draws for CLUT SW draw detection
it was still picking up weird sizes like 40px wide which is not valid. Broke True Crime NYC loading screens.
Already tested it.

GS-HW: Further restrict CLUT width to 8, 16, 32, 64

---

pcsx2/SPU2/Timestretcher.cpp
pcsx2/SPU2/Wavedump_wav.cpp
pcsx2/SPU2/spu2.cpp
pcsx2/SPU2/spu2.h
pcsx2/VMManager.cpp
pcsx2/gui/SysCoreThread.cpp

Don't adjust samplerate back to default on config change, use current rate (for PS1 mode). Also fix up some other samplerate related things and turn the soundtouch pointer in to a unique pointer.
resetting to 48000hz when in PS1 mode is annoying.
I don't really care.

SPU: On config change don't reinit sample rate.

---

bin/resources/GameIndex.yaml

Adds COP2 patch to the gamedb
Lighting was broken (possibly other stuff) due to bad COP2 instruction order which PCSX2 doesn't handle, this fixes it up.

GameDB: Add COP2 patch for Donald Duck - Quack Attack

---

bin/resources/GameIndex.yaml

Add COP2 patch for  Donald Duck Goin' Quackers.
Lighting was broken (possibly other stuff) due to bad COP2 instruction order which PCSX2 doesn't handle, this fixes it up. Missed this one in my last PR
Check CI

GameDB: Add COP2 patch for Donald Duck Goin' Quackers

---

bin/resources/GameIndex.yaml

Adds upscaling and graphical fixes to the following games
Battle Assault 3 featuring Gundam Seed
Chou Jikuu Yousai Macross
Dreamworks Madagascar
Driv3r
Driving Emotion Type S
Extermination
Fahrenheit
Ferrari F355 Challenge
Gladiator - Sword of Vengeance
GTR 400
Gumball 3000
Hot Wheels - Velociy X - Maximum Justice
Iridium Runners
Jeep Thrills
Just Cause
Looney Tunes - ACME Arsenal
Lord of the Rings, The - The Third Age
Lotus Challenge
Majo-musume - A La Mode II
Mercenaries - Playground of Destruction
Micro Machines V4
Motocross Mania 3
MTV Music Generator 2
Had upscale issues, or graphical issues (GTR 400 needed XGKick sync)
Check CI

GameDB: Add upscaling fixes for many games B-M

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Loops any height reads around 2048, ignoring any pixels before the loop.
Some EA games use an offset of 2047 to move the picture up 1 pixel for interlacing, and it's really stupid, but the code was clamping to 2048, which isn't really any good either, so this works better and doesn't confuse the TC, no other games known to do this.
Try NASCAR Thunder 2003 or NASCAR 08/09
Fixes #7307

GS-HW: GetOutput loop on 2048 and restrict height.

---

bin/resources/GameIndex.yaml

Removes Half-Pixel Offset from Mercenaries.
While it fixes a bunch of alignment, it also breaks a ton of graphics, so it's not worth it. However we've been down this road before, so I've left it commented out so anybody else trying it knows.
Watch CI

GameDB: Re-remove Half-Pixel Offset from Mercenaries.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Passes the original height to the texture cache for frame lookup when feedback is enabled.
In the code which I never touched when I changed all the PCRTC stuff, whoever did it was passing an upscaled size, so when we changed the lookup to also take the width, it was exploding and breaking, more and more as you upscaled. This corrects it.
Test games which do feedback writes, such as Xenosaga (the black and white cutscenes) and The Suffering - Ties that Bind.

GS: Pass original height for feedback lookup.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Further check the size of draws and make sure it's not using the framebuffer, unless the draw does invalidate the current CLUT.
Reduces readbacks in Burnout by like 75% and a bunch of other games no longer do them.
Test clutty games (actually already done it).
This will break Godfather seethrough lights again, that seems to be misdetection as it reads the framebuffer, but doesn't seem to write to a CLUT, at least directly, but the software draw happeened to fix it. We're coming up with another way of tackling that.

GS-HW: Further restrict CLUT heuristics.

---

bin/resources/GameIndex.yaml

Changed the GameDB to add the Wild Arms Hack upscaling fix to all Kaido Battle games and Racing Battle: C1 Grand Prix. This de-blurs the image when upscaling (examples attached). Genki seems to re-use the same rendering code that requires this ever since Tokyo Extreme Racer 3 / Shutoku Battle 01
I have also corrected the name of Kaido**u** Battle - Nikko, Haruna, Rokko, Hakone to be consistent with the other Kaido games (and to match its actual spelling in Japanese)
Improves the image for these games when upscaling.
I don't have Kaido Battle 2: Chain Reaction/Kaido Racer, but if someone does and reports this as broken I can remove WAH from it.
Off: Kaido Battle 3
On
Off: Kaido Battle
On
Off: Racing Battle: C1 Grand Prix
On

GameDB: Add Wild Arms Hack to Kaido Battle games, and Racing Battle C1GP.

---

pcsx2/GS/GSState.cpp

Wrap transfers around 2048 pixels in either direction.
if you had a really high offset with a really big transfer, it could go out of bounds and cause things to explode.
Test games, make sure nothing is busted.
This *might* fix the random crash in Silent Hill Origins (I believe near the end of the game)

GS: On Local->Local transfer wrap around 2048

---

.github/workflows/scripts/lint/gamedb/lint.py
bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GameFixSettingsWidget.cpp
pcsx2-qt/Settings/GameFixSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Gif.cpp
pcsx2/IPU/IPUdma.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/R5900.cpp
pcsx2/R5900.h
pcsx2/SaveState.h
pcsx2/Sif0.cpp
pcsx2/Sif1.cpp
pcsx2/Vif0_Dma.cpp
pcsx2/Vif1_Dma.cpp
pcsx2/Vif1_MFIFO.cpp
pcsx2/gui/Panels/GameFixesPanel.cpp

Implement Instant DMA hack completely (was previously hacked in for the BIOS only).
Some games with cache problems, like Fire Pro Wrestling Z experience graphical issues or crashes due to missing cache emulation, this should avoid it, to an extent.
Test games with the new Game fix if they have bad graphics or crash on boot/randomly, worth a shot.
Fire Pro Wrestling Z:
Before:
After:
Defender:
Before:
After:

EE: Implement Instant DMA hack for some cache problematic games

---

bin/resources/GameIndex.yaml

Disable gsHWFixes for Growlanser 5 and 6 because of #6797
gsHWFixes do not fix the background issues anymore.

GameDB: Disable gsHWFixes for Growlanser 5 & 6

---

bin/resources/GameIndex.yaml

Set texture preloading to Partial for Keihin Keikyu Train Simulator
Turns out the game hates texture preloading and almost halves the framerate with full hash cache.

GameDB: Set texture preloading to Partial for Keihin Keikyu Train Sim

---

.github/workflows/scripts/releases/announce-release/index.js

Some other discords we are associated with would like our announcements to be mirrored there, this facilitates that.

releases: allow publishing discord announcements to multiple webhooks

---

bin/resources/GameIndex.yaml

Adds CPU CLUT Normal to Bionicle Heroes to fix ghosting.
Without:
With:

GameDB: Add CPU CLUT to Bionicle Heroes

---

bin/resources/GameIndex.yaml

Adds VU Clamp Extra+Sign to Lego Starwars to fix bad coordinate spam.
Spam bad, getting rid of spam good

GameDB: Add VU Clamp Extra+Sign to Lego Starwars

---

common/Perf.cpp
pcsx2/GS/Renderers/Common/GSFunctionMap.h

Some includes were missing when building with profiling
It was broken otherwise.
Try compiling with vtune enabled.

Profiling: Fix QT builds where USE_VTUNE is true

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Removes the increased offset in the lookup for hardware mode when overscan is enabled. 
This can cause mis-detection when Show Overscan is enabled, making it miss the target.  This is still needed for software however, else you get some pretty ugly stretching.
test Silent Hill 2, Crash Nitro Kart, I guess some other rando games.

GS: Don't add overscan to offsets when looking up output texture.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Implements a workaround for the issue described in #3986. Please refer to that issue for a detailed explanation and screenshots. Also enables HPO Special to fix the following upscaling issues:
* The Getaway had outlines around characters, as if their depth did not line up.
* Black Monday had a rainbow border on screen edges.
Before (notice a light outline around the character's forehead):
After:
Hacks are bad, but this one seems to be a low risk one piggybacking on an existing CRC hack. Plus some upscaling goodness.
* Verify that The Getaway and The Getaway: Black Monday display the player shadow fine with no manual fixes enabled.
* Verify that The Getaway and The Getaway: Black Monday upscale without issues.

GameDB & CRC fixes for The Getaway games

---

pcsx2/GS/GSState.cpp

Corrects the height that is read/written when local->local transfer directions are reversed. Also avoid messing around in reverse if there is no overlap.
The code was adding on the height to start from the top, but it doesn't end *exactly* on y + height, it's height-1, but that got missed and caused corruption during the transfer, this resolves it.  However the game didn't even need to do this since it wasn't overlapping, so I added a check for an intersect on the coordinates to avoid it completely.
Try loading Armored Core 2 Nexus (you can't use a GS dump, this is done during a loading screen), make sure there's no missing line. 
Armored Core 2 Nexus (Look at the line in the HUD on the right)
Before:
After:

GS: Correct the height on reversed local->local transfers

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Resets the texture age when it's made dirty by upload.
Some FMV's such as Superman Returns stream the picture via Host->Local transfers, but right now we try to make sure it's new targets only (and they don't get updated because no draws happen) it starts missing and bad things happen.  So this PR will reset the age on the texture so it's still a "fresh" texture when it has dirty parts, so it can retrieve it from GS memory.
Test Superman Returns movies

GS-TC: Reset age on Host->Local dirty textures

---

pcsx2/Frontend/CommonHost.cpp

This change fixes https://github.com/PCSX2/pcsx2/issues/7367. `xdg-screensaver` appears to only work properly in all cases if you give it the top level window ID of PCSX2.
As far as I can tell, this change is only relevant to the Qt client on Linux with X11.
With this change, inhibit screensaver now works with the Qt client on Linux (X11) when a game is fullscreen as well windowed.
Make sure the screensaver is inhibited while a game is both fullscreen and windowed.

Qt: fix inhibit screensaver on Linux (X11)

---

pcsx2/x86/ix86-32/iR5900LoadStore.cpp
pcsx2/x86/microVU_Macro.inl

LQ/SQ were already 16 byte aligned.
The micro recompilers only write as 16 bit, so in case the value in the register was greater than 0xFFFF, we don't want to store higher bits that get stuck.
Consistency.
Test a few games, make sure nothing broke. These changes should be relatively safe I think, but I didn't want to change the behaviour in my EE rec PR.

x86/iR5900: Align LQC2/SQC2 to 16 bytes / Write VIs from CTC2 as 16 bits

---

pcsx2/COP0.cpp

What are the chances that I run into this bug :L
When reading the 32 bit COP0 registers into the 128 GPRs, it sign extends.
It was wrong and made my homebrew not work properly on the interpreter.
:shrug:

Core: Sign extend the interpreter implementation of MFC0

---

bin/resources/GameIndex.yaml

- Area 51: Half Pixel Normal vertex for lighting and other places
Before:
After:
- Shrek 2: Basic mipmapping which kinda half fixes the sun missing.
Before:
After:
- Galaxy Angel II: Normal vertex which reduces misalignment.
Before:
After:
- Forgotten Realms - Demon Stone: Clamping Mode extra + preserve which will solve the occasional SPS + missing demo entry. (Also have 2 nightmare fuel pictures to enjoy)
Before:
After:
- Spyro Dawn of dragon: SW clut + sprite which doesn't make you vomit from the overbloomification and looks similar to the software renderer
Before:
After:
- Castlevania Curse of darkness half sprite which will enlarge the font similar to software renderer + some missing fixes that were available on the Europe and America versions but not Japanese.
- Drakengard 1 + 2 …

GameDB: Fix multiple games + maintenance

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Make sure the texture is at least the size of the resolution and is on a page boundary (as it works in pages).
channel shuffles are sent 1 page at a time, but we HLE it and skip the rest of the draws, but the resize function was only checking the draw size, so we need to resize it to the full size of the shuffle.
Test games with channel shuffle problems, especially those in #1318
Fixes post processing on Prince of Persia Warrior Within
Prince of Persia
Before:
After:

GS-HW: Increase channel shuffle sizes to resolution or higher.

---

pcsx2/Gif_Unit.h

Fixes the GIF unit reset behaviour to abort the currently in-process packet.
It didn't abort properly before, causing misalignment of packets and resulting in either errors or crashes.
Test games and swapping games, make sure nothing crashes.
Fixes the boot issue with Monster Jam - Maximum Destruction

GIF: Fix reset functionality to properly abort the current packet

---

pcsx2/Counters.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp

Expands "progressive" analogue games to the full 448/512 height, so if they aren't really progressive, they still get interlaced properly.
Q-Ball Billiards Masters unsets the interlaced flag, but continues to interlace the signal, but due to some previous changes, we did rightly try to interlace it, it made it half resolution, but didn't expand the size so it interlaced properly, this fixes that.
Test "progressive" games (maybe no-interlace patches too), make sure nothing explodes.
Before:
After:

GS: Expand "progressive" analogue games to full height, in case they lie

---

bin/resources/GameIndex.yaml
bin/resources/shaders/dx11/interlace.fx
bin/resources/shaders/opengl/interlace.glsl
bin/resources/shaders/vulkan/interlace.glsl
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/GameIndex.md
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/CommonHost.cpp
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSMTLSharedHeader.h
pcsx2/GS/Renderers/Metal/interlace.metal
pcsx2/GS/Renderers/Null/GSDeviceNull.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/GameDatabase.cpp
pcsx2/Pcsx2Config.cpp

Adds Motion Adaptive Deinterlacing as an additional deinterlacing option (new default).
Blend deinterlacing tends to blur objects in motion which isn't very desirable, this new method reduces visual artifacts in games that do not output progressive frames and attempts to provide clear and smooth motion, resulting in a superior experience.
Test games which are generally quite blurry, such as GT4, King's Field VI etc. Also check random games to make sure nothing is broken (confirm it's not broken with "none" deinterlacing before reporting)

Implemented Motion Adaptive Deinterlacing and integrated changes with UI

---

pcsx2/x86/microVU.cpp
pcsx2/x86/microVU_Compile.inl
pcsx2/x86/microVU_Misc.h

Cleans up the micro program range merging functions and gets rid of some of the junk in the program comparison function. Also only copy parts of the program which are needed for the current microprogram during compilation, which should reduce compilation time slightly.
Might be slightly faster in some cases? idk, but it's nicer.
Test games, make sure the VU's don't explode.

mVU: Clean up range function and improve merging. Slim down cmpProg.

---

bin/resources/GameIndex.yaml

Bakugan: Deinterlace adaptive tff due to the game attempting to deinterlace FMVs but PCSX2 going nuts
Driv3r: Fixes janky coloured cars with cpuCLUT
Megaman X8: Deinterlace blending tff due to either looking like missing half the text or flicker as how the game handles empty and subtitles
Tales of Destiny 1: Texture preload partial for better performance in certain areas
Less tinkering
Test relevant games

GameDB: Fixes multiple games for Xth time and more

---

pcsx2/COP0.cpp
pcsx2/HwRead.cpp
pcsx2/IopCounters.cpp
pcsx2/IopDma.cpp
pcsx2/R3000A.cpp
pcsx2/R3000A.h
pcsx2/R3000AInterpreter.cpp
pcsx2/R5900.cpp
pcsx2/R5900.h
pcsx2/SaveState.cpp
pcsx2/SaveState.h
pcsx2/x86/iCOP0.cpp
pcsx2/x86/iCore.cpp
pcsx2/x86/iCore.h
pcsx2/x86/iR3000A.cpp
pcsx2/x86/iR3000Atables.cpp
pcsx2/x86/ix86-32/iCore-32.cpp
pcsx2/x86/ix86-32/iR5900-32.cpp
pcsx2/x86/ix86-32/iR5900Jump.cpp

See title. May as well do this while we're breaking save states.
Potentially better locality, keeps everything we're accessing from the rec together.
Test a few games, saving/loading, make sure nothing broke.

x86: Move cycle/writeback fields to CPU structs

---

common/vsprops/BaseProjectConfig.props

Much better parallelism, due to our source files being spread out across multiple folders.
pcsx2core build time on a Ryzen 3900X with 12C/24T:
Before: Time Elapsed 00:01:03.21
After: Time Elapsed 00:00:26.74
Make sure build succeeds.

VSProps: Use MultiToolTask mode

---

pcsx2/SaveState.h
pcsx2/Sio.cpp

[SAVEVERSION+] Regression from #6741.
Replugging all the time in some games is really annoying. Also TAS.
Test saving/loading with and without card changes (e.g. changing to a different card).

Sio: Only eject memory cards when loading state if changed

---

3rdparty/zydis/dependencies/zycore/include/Zycore/Defines.h
pcsx2/x86/ix86-32/iR5900-32.cpp

Silences the zycore warning which gets spammed, and fixes compiling with DUMP_BLOCKS (disabled by default obviously).
Stuff I should've had in the EE rec PR.
Make sure build completes, no functional changes.

3rdparty/zydis: Silence static define warning

---

bin/resources/GameIndex.yaml

Adds mipmapping full and trilinear to Shadow of the Colossus as an automatic fix
Fixes broken water in hardware mode.
check CI
Before:
After:

GameDB: Add Mipmap Full + Trilinear for Shadow of the Colossus

---

pcsx2/MemoryCardFolder.cpp

Happens when using memory card folders and booting God of War. Game does a bunch of 128 byte reads followed by a 12 byte read, ecc gets computed, 16 bytes get copied and overflows.
Heap corruption is bad.
Test GoW with folder memcards.

MemoryCardFolder: Add missing bounds check to Read()

---

pcsx2/R5900OpcodeTables.cpp
pcsx2/x86/iCOP0.cpp
pcsx2/x86/iFPU.cpp
pcsx2/x86/iR5900.h
pcsx2/x86/ix86-32/iR5900-32.cpp
pcsx2/x86/ix86-32/iR5900Branch.cpp
pcsx2/x86/ix86-32/iR5900Jump.cpp
pcsx2/x86/microVU_Macro.inl

Swapping the loadstore could affect the condition of the instruction, leading to incorrect code execution.
Fixes lock up in Oni after intro FMVs. Also fixed the incorrect disassembly of those instructions while I was at it.
Fixes #7417.
Test Oni (already done here).

x86/iR5900: Don't swap loadstore delay slots for BC0/BC2 conditions

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.h

Attempts to fix pink or frozen images of the last frame in games when using MAD with Metal.
Frozen images are bad pink screens too.
Make sure MAD interlacing works when using Metal.

Metal: Attempt at fixing usage of MAD

---

.github/workflows/windows_build_qt.yml
.github/workflows/windows_build_wx.yml

That way it matches what we're using locally.
Make sure CI passes and builds run.

CI: Change Windows builders to VS2022

---

bin/resources/GameIndex.yaml

Adds Blit gamefix to Worms 4 Mayhem to fix internal FPS detection.
The FPS isn't 50 and the game should stop lying.

GameDB: Add Blit gamefix to Worms 4 Mayhem

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp

Allow the merge circuit to apply a negative offset when there's only one display.
Stuntman in all its wisdom was applying a negative offset, but also toggling one of the circuits on and off every other frame, so it was shaking like a madman and looked ugly.
Test games with PCRTC offsets (with screen offsets/overscan turned off)
Before:
After:

GS: Allow negative offset on single display

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Only reset the age of new targets when captures in Tex in RT.
Caused huge GS usage on Urban Reign due to old target.
Test Urban Reign, make sure the GS usage doesn't go through the roof.

GS-TC: Only reset age on new Tex in RT targets.

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.h

Allows the appending of targets from EE writes and improves the overlap check to make sure the given texture does actually overlap, not that the block point matches.
Castlevania Curse of Darkness updates the FMV/Subtitles in chunks, drawing its border from the EE, and t his was getting missed causing the picture to be stretched, but also the overlap check was causing incorrect targets to be written to, causing the screen to flash whenever the subtitles changed since that target was then being missed later on.
Test games (especially FMVs), make sure nothing flickers or looks off.
Fixes #5350
Before:
After:

GS-HW: Expand target on EE write and improve overlap check

---

README.md
common/HTTPDownloaderWinHTTP.cpp
common/Windows/WinMisc.cpp

Mis: Flag Windows 8.1 as unsupported OS.
No longer supported.
Might be worth using the newest sdk(10.0.22000) so we can properly detect win 11.

Mis: Flag Windows 8.1 as unsupported OS.

---

pcsx2/SaveState.h
pcsx2/Sio.cpp
pcsx2/Sio.h

It wasn't saving the FIFO anyway. Sorry for the save state bump, but it's unavoidable :(
Regression from #6741.
Fixes #7433 (hopefully).
Test spamming save/load state.

Sio: Fix host pointer getting serialized

---

pcsx2/MemoryCardFile.cpp

_filthy-frank-its-time-to-stop.mp4_
Make the prompt for when a memcard gets an access denied error, actually explain the problem.
I am sick and tired of being sick and tired of this same problem in Discord every day. Also hopefully users can now figure out possibly maybe slightly a little how to solve this on their own.
Purposely put a memcard in program files and switch your memcard directory to it, slot a card in, make sure prompt pops.
Linux folk... Idk y'all are magical put a memcard in a place where you don't have read perms, and make sure the prompt pops up. Your version of the prompt won't have the program files bit cause that's a wandows thing.

Memory Card: Make access denied pop-up actually explain the problem

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2/Config.h
pcsx2/GS/GS.cpp

Until XZ stops exploding we should default to Zstandard for dump compression.
Explosions when trying to get a dump for support is inconvenient. 

Qt: Change dump compression to Zstandard

---

pcsx2/PAD/Host/PAD.h

Increases the limit of macros from 4 to 16 to fill the UI up.
Not sure why it was limited to 4, I don't think there's a technical reason, and some users were after more than 4, so why not have a screen's worth? :)
Make a bunch of macros for your controller, try them out, see what happens.
Closes #7009

PAD: increase number of macros per controller from 4 to 16

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Adds changes to avoid doing very large clears in hardware, creating huge textures which causes a lot of misdetection.  Also stops incrementing age on frames as they are not being drawn/modified, but also try to avoid using old frames unless nothing better is available.
Fatal Frame and Clock Tower 3 do absolutely huge draws just before FMV's to clear out the memory so the surround for the FMV is black, but this causes a really big texture being detected, when it shouldn't exist (since it's a clear).  The other issue was it was keeping an old frame about instead of offsetting inside a large double buffer used for the FMV's, resulting in flashing.
This also affects the camera flickering problem in Fatal frame due to similar issues.
Test games which need a "safe features" enabled (like …

GS-TC: Avoid large clears in HW + old frames

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2/CDVD/CDVDcommon.cpp
pcsx2/Frontend/Achievements.cpp
pcsx2/Frontend/CommonHotkeys.cpp
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/GameList.cpp
pcsx2/Frontend/GameList.h
pcsx2/Frontend/ImGuiFullscreen.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GameDatabase.cpp
pcsx2/Host.h
pcsx2/MTGS.cpp
pcsx2/MemoryCardFile.cpp
pcsx2/MemoryCardFolder.cpp
pcsx2/Sio.cpp
pcsx2/VMManager.cpp

- Fix Enable Per-Game Settings 
- Make OSD message timing consistent for categories of messages
- Add option to reset play time for games
QOL/consistency improvements.
Test stuff mentioned in list above.

Qt: Fix per-game enable/OSD message timing/reset play time

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.h

Makes sure it's definitely an EE write when resetting the age on textures.
Kind of regression from #7374 as it didn't just happen on EE Writes, but any invalidation, which could have blown up the TC.
Not really much to check... nothing known to be affected. Superman still works and Urban Reign is fine.

GS-TC: Only reset age when it's definitely an EE write

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

Fixes MAD shader on M1 (previously we would use the wrong load action)
Less brokenness
Test MAD on Metal + M1

GS:MTL: Fix mad shader on M1

---

pcsx2-qt/QtHost.cpp
pcsx2/MTVU.h
pcsx2/x86/microVU.cpp

Option will create configuration (if non-existent), and then immediately exit.
Can be used to set up the default configuration and directory structure, without fully starting PCSX2.
Test CLI option (already done myself - but you can run it in a new extracted copy, it should create inis etc).

Qt: Add -testconfig option

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Window/GSwxDialog.cpp
pcsx2/Pcsx2Config.cpp

Modifies bilinear filtering to have a sharper appearance at lower resolutions. if the resolution is lower than the window, it will be integer scaled up then bilinear filtered to fit the window.
Adds upscaling of the picture past the window size by an integer scale, so downsampling back to the window size with bilinear doesn't destroy information or excessively blur the picture while maintaining pixel uniformity.
test stuff in native, compare to master with different window sizes. compare to nearest filtering also (Bilinear Filter on the Display tab of the graphics settings disabled)
Closes #7183

GS: Add sharp bilinear for lower resolutions.

---

bin/resources/GameIndex.yaml

Adds HalfPixelOffset and AlignSprite to Finding Nemo and Haven: Call of the King. Also removes a non-existent NTSC-U Haven serial number. Adds AlignSprite to Kinetica as well, uses God of War's engine.
Less ghosting and vertical lines when upscaling, and less tinkering for users.
Test said games for ghosting or vertical lines.

GameDB: Fixes for Finding Nemo, Haven: Call of the King, Kinetica

---

bin/resources/GameIndex.yaml

Removes round sprite from prince of persia sands of time as it causes lines to appear in post processing.
This is bad it shouldn't do this.

GameDB: Remove Round Sprite from Prince of Persia SOT

---

pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Window/GSwxDialog.cpp

gui-wx: Add default configs for CAS filtering.
gui-wx: Add FidelityFX CAS support.
Add FidelityFX CAS support to wxwidgets.
Rename Texture Filtering of Display to Bilinear filtering.
Remove Debug box.
Misc cleanup.
Parity with Qt.
Fixes #7451
Check if CAS works on wx.

gui-wx: Add FidelityFX CAS support to wxwidgets gui.

---

bin/resources/GameIndex.yaml

- Thrillville + Thrillville Off The Rails: Mad TFF / deinterlace 8 to stop shaking the whole game
- Forgotten Realm Demon Stone: Get rid of more blur.
Before:
After:
- ATV Offroad Fury 3: MTVU disabled which was an odd find to improve FPS
Before:
After:
- Crimson Tears: Wild arms + Full Sprite for reducing bloom misalignment + note that Blending TFF might be better especialy when you use Software.
Before:
After:
- Crimson Tears Extra note
Blending difference note (biggest in SW):
SW with MAD TFF:
SW with Blend TFF:
HW with automatic (basically MAD TFF):
HW with blend TFF:
- Final Fantasy X: Texture in Rt for fixing endgame summons like Anima and The Magus Sisters
Before:
After:
SW (game has other issues which to this day still needs a CRC hack but looks fine on the software renderer) so …

GameDB: Fixes to multiple games yet again

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

e.g. Dark Cloud's menu.
Also prevents an out-of-VRAM situation from crashing.
Generally improves out-of-VRAM for DX12/Vulkan, instead of immediately failing the allocation, flush the texture pool,
and execute/wait for the command buffer. This will clear out any textures which have already been freed, and the storage can be reused for.
VRAM spikes and crashes are bad.
Test Dark Cloud menu.

GS/TextureCache: Better handle batched tiny moves

---

pcsx2/GS/Renderers/Common/GSDirtyRect.cpp
pcsx2/GS/Renderers/Common/GSDirtyRect.h
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Attempts to combine dirty rects and skip duplicates
before it was YOLO adding dirty rects, so if a game did thousands of tiny draws before it became valid, any surface offset calculations were exceptionally slow due to thousands of dirty rects in the list, further to this, it was compounded by repeat writes to the same location.
test stuff, make sure nothing's bust.
Might slightly lower GS thread usage in some cases, might slightly increase it, nobody knows! spin the wheel of chance to find out!
This was the original problem with Urban Reign, but might have also affected Guitar Hero 3 and others.

GS: Combine dirty rects when having matching edges

---

.github/workflows/scripts/linux/AppRun-qt

Prevents relative paths from working.
Should make relative paths work.
Test AppImage + CLI.

AppImage: Don't change current working directory

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS-hw: Further optimize blending equations.
Allow to run free sw blend with no texture barriers, more speed for all renderers.
CLAMP 1, negative result will be clamped to 0.
Condition 1:
(0  - Cs)*Alpha +  0, (0  - Cd)*Alpha +  0
Condition 2:
Alpha is either As or F higher than 1.0f
(0  - Cd)*Alpha  + Cd, (0  - Cs)*F  + Cs
More brr when using blending.
Test blending.

GS-hw: Further optimize blending equations.

---

bin/resources/GameIndex.yaml

Setts texture preloading to partial to almost double the speed of the game because it's stupid and seems to absolutely destroy the HC.
Choo choo
Make sure CI is happy

GameDB: Set texture preloading to Partial for Espagaluda

---

bin/resources/GameIndex.yaml

Fixes an incorrect game name.
Having the wrong name is gross.

GameDB: Fix incorrect name of SLPM-65140

---

common/AlignedMalloc.cpp
pcsx2/x86/newVif_HashBucket.h

Fixes an issue where starting games, and loading save states, and turning MTVU on and off were incredibly slow on M1
On M1...
Time to memalign then free 65536 16-byte aligned 64-byte blocks 100 times: 200ms
Time to memalign then free 65536 16-byte aligned 24-byte blocks 100 times: 180ms
Time to memalign then free 65536 64-byte aligned 64-byte blocks 100 times: 700ms
Time to memalign then free 65536 64-byte aligned 24-byte blocks 100 times: 80s
Further testing indicates that a single run of 65536 allocations varies wildly in speed on M1, ranging anywhere from 7ms to 7s. [Test program](https://github.com/PCSX2/pcsx2/files/10088643/memaligntest.cpp.zip), [Log of the speeds of 100 consecutive runs](https://github.com/PCSX2/pcsx2/files/10088503/results.txt)
On a horribly slow atom computer …

Common: Fix slow emulator startup on M1

---

bin/resources/GameIndex.yaml

The gamefix works well for NTSC, but I had added blit to every version of resident evil doing wrong fixes which were meant for Silent Hill 4 and forget this part where it only gives 10 FPS instead of more.
Fix visual issue
Test Resident evil 4 PAL versions

GameDB: Remove blit from PAL being dumb

---

pcsx2/CDVD/CDVD.cpp

Skips calculating rotational latency if the requested sector is already buffered
No need to wait for rotation when it's buffered the sectors already, will kind of happen in async. Was breaking videos in Godzilla - Save the Earth.
Test CDVD Timing sensitive games make sure nothing is worse, yadda yadda, remind me never to emulate a system with a CD/DVD drive again, thanks.
Fixes Godzilla - Save the Earth video skipping problems.

CDVD: Don't account for rotation if sectors are buffered

---

pcsx2/Patch_Memory.cpp

Adds additional extended codetype functionality that exists in [PS2rd](https://github.com/mlafeldt/ps2rd/blob/master/Documentation/code_types.txt) and is used by Open PS2 Loader, namely:
* Making use of the otherwise unused last 4 digits of the D-codetype data value to also allow for 8-bit and 16-bit multi-line conditionals.
This won't break compatibility with existing D-codes, because PS2rd itself also checks if the lines to skip is 0, and sets it to 1.
* Adds more test conditions 4 - 7 used by PS2rd - NAND, AND, NOR, OR for both D-codetypes and E-codetypes.
PS2rd also has one more C-codetype which is a 32-bit conditional that will block *every* following cheat line if the condition is not met, but at a glance I couldn't see if the function had any way of tracking which line out of how …

Patches: Add extended PS2rd support; used by OPL

---

pcsx2-qt/QtHost.cpp
pcsx2/GS.h
pcsx2/MTGS.cpp

Makes it so you can call `GetMTGS().PresentCurrentFrame()` from anywhere in the CPU thread.
Consistency with the other functions in MTGS.
Test window resizing and fullscreening in Qt.

MTGS: Make PresentCurrentFrame() callable from CPU thread

---

pcsx2/GS/Renderers/DX11/GSTexture11.cpp

Fixes D3D11 box parameters for textures.
mistake from #7477 which apparently the compiler lets you get away with.
test games on DX11, noticed on burnout.

GS-DX11: Fix D3D11_BOX parameters (missing "front")

---

common/CMakeLists.txt

CMake: Lowercase Winmm for case-sensitive fs

---

pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Clamps the draw to the read size to make sure reads aren't done out of bounds of the available texture.
This change didn't need to be done as the th and tw are sized based on the actual sizes anyway, if these are wrong, the software renderer can crash when trying to draw out of bounds, so this needs to stay as it is. Regression from #7104
Test MGS2 in the software renderer, make sure it doesn't explode (was tested using the intro)

GS-SW: Revert software clamp changes from large TH/TW PR.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Corrects the end block and valid rect for textures in the hardware renderer when they are resized.
Some games were missing render targets when displaying FMVs causing flashing. Robot Warlords was one such game. If we're going to increase how much memory a texture covers, the end block should reflect that.
Test games, make sure nothing flashes bad.
Fixes Midas FMV on Robot Warlords.

GS-HW: Update validity when resizing a texture during the draw.

---

pcsx2/CDVD/IsoFS/IsoFS.cpp

Changes the ISO reader to escape from checking the descriptor information if it fails to read the ISO.
Before it continued to loop checking the descriptor so if there was any residue data from a previous read, it would keep that, since the actual sector read would escape, leaving the buffer as-is, but it would continue to process it.  This now escapes.
Try booting a game,  once booted choose shut down without saving, click "boot bios"

CDVD: Escape descriptor read on iso read failure

---

pcsx2/Frontend/MetalHostDisplay.h
pcsx2/Frontend/MetalHostDisplay.mm
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

- Fixes an issue where gpu spinning would randomly be enabled when it wasn't requested or needed (oops)
- Uses `[MTLCommandBuffer presentDrawable:]` instead of `[MTLDrawable present]` when vsync'd or on Ventura
- Previous use was to work around a bug where `presentDrawable:` acted like vsync was on no matter what.  On the other hand, `present` acted like vsync was off no matter what.  This has been fixed in Ventura, and `presentDrawable:` plays nicer with Xcode GPU traces
Test Metal Renderer

GS: More Metal fixes

---

pcsx2/DEV9/ATA/ATA.h
pcsx2/DEV9/ATA/ATA_State.cpp
pcsx2/DEV9/ATA/ATA_Transfer.cpp
pcsx2/DEV9/ATA/HddCreate.cpp
pcsx2/DEV9/ATA/HddCreate.h

Uses sparse files for HDD images.
It will also check for zero writes to the HDD file and hole punch if large enough.
Note that it will not make existing files sparse (although writes may hole punch on Linux & Mac)
Currently only 1mb is allocated, with the remainder of the file left unallocated.
A minimum of 40GB is required for most games, but they won't need most of that size. The storage cost can be mitigated using the OS/filesystem sparse file support.
Resolves https://github.com/PCSX2/pcsx2/issues/4443
Test creating a new HDD file, test HDD enabled games or homebrew
On windows, you can check the "Size on disk" to see the amount of storage actually taken.
Mac and Linux also need testing.

DEV9 HDD Sparse file support

---

bin/resources/GameIndex.yaml

Adds autoflush fix for blur effects and round sprite full to correct positioning of said blur and also text size.
Looked gross, more auto is better.
Check CI

GameDB: Add fixes for Busin 0: Wizardry Alternative games. Fixes titles.

---

common/Darwin/DarwinSemaphore.cpp
common/Threading.h
pcsx2/GS.h
pcsx2/MTGS.cpp
pcsx2/MTVU.h

Adds a semaphore with a userspace fast path and uses it
Improves performance in GS thread limited applications, when MTVU is enabled.  Amount depends on operating system (how slow kernel semaphores were).
In Sly at 1x:
- macOS: +30%
- Windows: +20%
- Linux: +1%
Also fixes high EE thread usage during gsdump playback
Faster yay
Test your GS thread limited games (I recommend sly)

Use semaphores with a userspace fast path

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2/Frontend/Achievements.cpp
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/FullscreenUI.h
pcsx2/Frontend/ImGuiFullscreen.cpp
pcsx2/Frontend/ImGuiFullscreen.h
pcsx2/Frontend/ImGuiManager.cpp
pcsx2/Frontend/ImGuiManager.h
pcsx2/Frontend/InputManager.cpp
pcsx2/Frontend/InputManager.h
pcsx2/GS/GS.cpp
pcsx2/HostDisplay.h
pcsx2/gui/AppHost.cpp

Slightly messy, but it's needed to solve two issues:
- Switching renderers in the fullscreen UI will boot you back to the main landing page.
- Changing renderers while achievements are active (either with game settings or manually) will prevent notifications from being shown until you open the pause menu.
Fixing my design oversights.
Briefly test achievements after switching renderer, or change renderers in the fullscreen UI. It should stay in the settings menu.

FullscreenUI: Don't clear state when switching renderers

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui

Previously it would be disabled, leading to user confusion.
See above.
Make sure it compiles.

Qt: Remove hardware download mode from global settings

---

pcsx2/Frontend/FullscreenUI.cpp

Previously this wasn't possible with a controller, only the mouse.
Follow the same convention as other UI options (alternate action = triangle/Y).
See above.
Make sure it compiles.

FullscreenUI: Allow unbinding a hotkey/controller with Triangle

---

pcsx2/VUops.cpp
pcsx2/x86/microVU_Compile.inl

Fixes the timing when using XGKick Sync
Some games are very sensitive to the timing at the beginning of an XGKick, particularly Resident Evil: Outbreak, CART Fury: Championship Racing and Kingdom Hearts, as the XGKick instruction itself counts for at least one cycle (each XG packet takes 2 cycles to transfer), this being out caused a lot of SPS problems.
Test games which use XGKick in the gamedb, make sure they're fine (Did test WRC PAL briefly and was fine)
Fixes #5328 CART Fury
Fixes #5107 Resident Evil Outbreak

VU: Correct XGKick timing when using XGKickSync

---

pcsx2/CMakeLists.txt

This hasn't been a thing for a while.
See above.
Make sure compile succeeds.

CMake: Drop SPU2X_PULSEAUDIO define

---

bin/resources/GameIndex.yaml

HPO Normal causes really bad glitching on the floor in KH2 round sprite breaks light bloom in Price of Persia WW and WRC Rally Evolved needs round sprite half to fix misaligned text.
This is bad it shouldn't be doing this:
It should look like this with Round Sprite Full:
Happy CI is good yes.

GameDB: A few game fixes and tweaks 

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Prevents hash cache from being disabled due to a large number of custom textures. The VRAM usage from the custom textures will still be shown in the OSD.
Apparently people have some *really* high resolution replacement textures...
Probably a bit difficult to check if you don't have some of these textures.. but you can still check the hash cache usage increases as before with replacements.

GS/HW: Don't consider custom textures in hash cache overflow

---

CMakeLists.txt
pcsx2/CMakeLists.txt

Fixes issues with `DISABLE_ADVANCE_SIMD=ON` builds failing to link on some compiler+linker combinations
Fixes #7543 
Less broken builds
Try to build on Linux with all sorts of compilers and linkers

CMake: Fix issues with linkers failing on Linux

---

pcsx2-qt/MainWindow.ui
pcsx2-qt/Settings/ControllerBindingWidget.ui
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/CDVD/InputIsoFile.cpp
pcsx2/SaveState.cpp

Bigger tooltip window
Controllers button shows up correctly at different DPI percentages 
Rename some options.
More sense and more obvious settings or options.
Check the GUI in Qt

Qt: Resizes + better tooltips + Savestate warning

---

pcsx2-qt/AutoUpdaterDialog.cpp
pcsx2/CMakeLists.txt
updater/Updater.cpp
updater/Updater.h
updater/Windows/WindowsUpdater.cpp

Gives the updater the ability to pick releases that don't perfectly match the current release
Required to be able to update from a current SSE4/AVX2 build to a multi-isa build
Point updater at your own testing server and see if it can update
(Windows updater is tested by me)

Updater: Support multi-isa switchover

---

pcsx2/x86/iFPU.cpp
pcsx2/x86/ix86-32/recVTLB.cpp

Happened when `Rd` was `xmm0`, and `ACC` wasn't populate, leading to `0 == 0` case and it thinking it was writing to `ACC`.
Also make store logging not flush the register cache, which should make it easier to debug these kinds of issues in the future.
Fixes green screen once you get ingame in Psi-Ops - The Mindgate Conspiracy.
Test Psi-Ops (done myself).

x86/iR5900: Fix msub.s/madd.s when ACC isn't live

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp

Stops it anti-blurring in software mode when both PCRTC framebuffers are the same source but one is offset, when anti-blur is off.
Killing the intended by developer behaviour when you don't want it to is bad.
Test Cold Winter in software, Anti-blur vs not.

GS-SW: Don't anti-blur frame rect when same source and not anti-bluring

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Ensure hidden tabs are also disabled so they can't be navigated to.
Fixes #7472.
Scroll through the tabs in the Graphics menu with a game running, try changing renderers while on a tab that should be inaccessible with the renderer you're changing to.

Qt: Fix being able to access hidden tabs in Graphics menu

---

pcsx2/GS/Renderers/Common/GSDevice.cpp

Copy interlace result into `m_merge` to avoid keeping it as `m_current`, `m_merge` is reusable at this point... right?
I think I only notice it when using weave deinterlacing, but when using shadeboost it would seem as if the effect was applied twice every other line. Since weave uses discard, every other line just shows the previous image which is the result of m_current being used for post processing.
Try shadeboost with low brightness and wave deinterlacing, just the BIOS is good enough test. It would give a sort of scanline effect when captured and an overall darker image than no deinterlace. That odd behavior should be gone with this PR.
I don't know how the other deinterlalcing methods are affected, but if there's a discard involved it's probably affected.... maybe.

GS: Preserve deinterlacing render target

---

bin/resources/shaders/common/fxaa.fx
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

Fixes FXAA being broken after https://github.com/PCSX2/pcsx2/commit/b706c25b68b25fe5e4cc84b5420f225f201ac739.
Will be slightly difference since this is using the BT.709 coefficients instead of CCIR 601 - but it matches the non-gather codepath now.
Also gets rid of an additional copy when FXAA/ShadeBoost is active.
Regression fix, ever-so-slight VRAM bandwidth savings.
Test FXAA and also make sure I didn't regress #7565.

GS: Compute luminance in shader for FXAA

---

bin/resources/GameIndex.yaml

Fixes white lines in Drakengard using merge sprite and fixes the name of the Spanish monsters inc scare island and Buzz!.
Lines are bad and Spanish names are different who knew.

GameDB: Game and name fixes

---

pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/GameList/GameListWidget.h
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2-qt/Settings/GameSummaryWidget.cpp
pcsx2-qt/Settings/GameSummaryWidget.h
pcsx2-qt/Settings/GameSummaryWidget.ui
pcsx2-qt/Settings/SettingsDialog.cpp
pcsx2-qt/Settings/SettingsDialog.h
pcsx2/CDVD/CDVD.cpp
pcsx2/CDVD/CDVD.h
pcsx2/Frontend/CommonHost.cpp
pcsx2/Frontend/CommonHost.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/GameList.cpp
pcsx2/Frontend/GameList.h
pcsx2/VMManager.cpp
pcsx2/VMManager.h

Currently, it's not possible to load an ELF and disc at the same time. You have to boot the ELF, then change disc... and that's awful.
This PR makes it possible to set a disc path for ELF game list entries. So, scan your elf, set a disc path (in game properties), double click the elf in the game list, and away you go.
Should make life easier for modders. As an added bonus, both compat and GS game fixes will apply to the modded ELF, as it pulls the serial from the disc.
See above.
Test ELF with disc combination, as well as existing per-game settings to make sure nothing broke.

Qt: Add disc path option for ELF game list entries

---

pcsx2-gsrunner/Main.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GSDumpReplayer.cpp

Was lazy and didn't join the threads before, which could lead to incomplete files.
Also fixes frame advance when playing back a GS dump, it would always advance two frames before.
Fixing my silly mistakes.
Spam a bunch of large screenshots and shut down. PCSX2 should freeze until they're all written.

GS: Ensure screenshots are saved before shutting down

---

pcsx2-qt/Settings/GameSummaryWidget.cpp

Introduced in 9da8e9280f67e0a311b9a8f10d35acc9b0638b70
Crash bad.
Make sure it builds (issue is obvious).

Qt: Fix crash opening ELF game properties

---

bin/resources/GameIndex.yaml

Adds mipmapping/trilinear for said games.
Looks less shitty.
Check CI

GameDB: Add mipmapping fixes for Monster Attack/Chikyuu Boueigun

---

pcsx2/GS/Renderers/Common/GSDevice.cpp

Fixes crash when Bilinear(Sharp) selected along with FXAA or Shadeboost
Crashes are bad. Don't Stretchrect src->src.
Check it doesn't crash with FXAA and Bilinear Sharp

GS: Fix crash if FXAA/Shadeboost enabled with Bilinear Sharp

---

pcsx2/x86/microVU_Misc.inl

Apparently NOT doesn't set flags
Less broken
Test on GCC, which is apparently the one who happened to enter the function with the zero flag cleared

microVU: Fix mVUcustomSearch

---

bin/PCSX2_keys.ini.default
pcsx2/gui/FrameForGS.cpp

wx: Fix console warnings for no longer used hotkeys.
Fixes Kbd Accelerator warnings on pcsx2 console.
Console warnings.
Test pcsx2 on wx, run a dump or game and see if the warnings are gone in the console.

wx: Fix console warnings for no longer used hotkeys.

---

common/D3D12/Context.cpp

If your GPU didn't support DX12, it'd throw an assertion failure, then crash.
Crashing is bad.
None needed, just read the diff.

D3D12/Context: Don't assert-fail when D3D12 is unavailable

---

pcsx2/Frontend/ImGuiManager.cpp

Saves needing to manually write to both the log and the OSD.
Duplicating is gross.
Make sure OSD messages go to the log.

ImGuiManager: Log OSD messages when they're added

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

GS-d3d11: Fix dx11 crashing on dx10 gpus.
CAS requires feature level 11.0.
GS: Move osd log for unsupported cas in Renderer code.
Crashes are bad mkay.
Test dx10 gpus.

GS: Fix dx11 bad shader/crashing on dx10 gpus.

---

common/SettingsInterface.h
pcsx2/Frontend/LayeredSettingsInterface.cpp
pcsx2/Frontend/LayeredSettingsInterface.h
pcsx2/Frontend/SDLInputSource.cpp
pcsx2/Frontend/SDLInputSource.h
pcsx2/INISettingsInterface.cpp
pcsx2/INISettingsInterface.h
pcsx2/PAD/Linux/SDL/joystick.cpp
pcsx2/gui/AppInit.cpp
pcsx2/gui/wxSettingsInterface.cpp
pcsx2/gui/wxSettingsInterface.h

- Default-enabled a hints for HIDAPI PS3 controllers on Linux and Wii controllers everywhere
- PS3 controllers for pressure sensitive button support
- Wii controllers for the ability to use Wii U Pro controllers without a separate program
- Added support for loading custom hints from the INI on Qt builds
- In case users want their Switch controller home buttons glowing or something idk
- Put your hints under `[SDLHints]` in the INI, e.g. `SDL_JOYSTICK_HIDAPI_SWITCH_HOME_LED = 0.5` to make your switch controllers' home buttons glow at half brightness
- Test Wii U Pro controllers, classic controllers, or try to play a PS2 game with a wiimote
- (macOS > 12.0 is known to not be able to pair wiimotes and wiimote-derived controllers, so it's expected to not work there)
- Test PS3 controller …

Better SDL Hints

---

pcsx2/USB/USB.cpp
pcsx2/USB/deviceproxy.h

Prevents DeviceProxy from going backwards from the beginning of an iterator.
If there is no ini file, such as on first bootup, Ports[i].DeviceType is initialized to -1, which will cause the emulator to crash when it reaches this point.
Check to make sure this doesn't cause any issues with usb.

USB: Don't crash and burn if there is no ini file for pcsx2.

---

pcsx2/USB/usb-pad/usb-pad.cpp

Adds the missing three controllers to the buzz binding list.
They were missing.
Test Buzz games. I don't have any.

USB: Add missing extra controller bindings for Buzz

---

pcsx2/USB/usb-pad/usb-pad.cpp

I reordered the buttons in the UI to make the layout more intuitive. 
Rationale: The previous button mapping page hurt my brain
Suggested testing steps: See if this works... I didn't screw up, did I? (I'm quite new to this) 
Before:
After:

USB: Buzz Button reorder

---

pcsx2/USB/usb-pad/usb-pad.cpp
pcsx2/USB/usb-pad/usb-pad.h

Adds a deadzone setting to usb wheel axis handling. Also adds a small bit of feedback to the axis values to ensure that full deflection is registered even at extreme deadzone settings.
Pad mapping to a wheel axis can be extremely twitchy. This will make it more useable for pad users that wish to map wheel support to a modern xbox/ps4 style controller or for wheels with no self centering or force feedback.
Tested on GT3 and 4 with each compatible wheel profile. The 900degree wheels will always have too much range to cleanly map to pads but less precise models behave quite nicely and all profiles will register full deflection for all deadzone values. Should be tested against other games supporting wheels. Ensure that center drift is avoided, the game registers the first post input …

USB: Add deadzone for USB wheel steering axis

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Unnecessary descriptor table updates and/or the wrong sampler being used is never good.
Probably wasn't _super_ common, but one way to reproduce it is to boot Time Crisis 2 in DX12, the image should no longer bob up and down.

GS/DX12: Fix incorrect sampler being used in utility draws

---

bin/resources/GameIndex.yaml

Reduces Hash cache numbers, improving speed in certain areas and reduces GS usage.
An oddity is that it is less effective on 5 and also needs roundsprite half and not Wild arms. I wonder if they made big changes in the engine compared to 3 and 4.
I also fixed the discrepancies between regions (missing fixes probably missed due to having different naming for the Japanese versions)
As well as fixing comments + missing serials for not only limited to Wild ARMs related.
Test any Wild ARMs version for 3 4 5 or Alter Code F.

GameDB: Wild ARMs 3,4,5,F + maintenance

---

pcsx2/USB/usb-lightgun/guncon2.cpp

add screen parameter for PAL versions of Endgame, Vampire Night, Guncom 2, Virtua Cop
for fun
calibrate and play

GunCon2: Add screen parameters for more games

---

pcsx2-qt/Settings/ControllerBindingWidgets.cpp

Needed for #7633.
Can't really test it because nothing's using it yet. But the issue is fairly obvious - the binder was looking for a data value, but none of the items had it set.

Qt: Fix global string list setting not showing in input profiles

---

pcsx2-qt/MainWindow.cpp

A race could happen if the game list was being refreshed on close (e.g. window closed -> play time update -> refresh).
Races aren't fun.
Close main window while a game is running, make sure no crashy.

Qt: Ensure game list refresh is cancelled before destroying

---

pcsx2/USB/usb-lightgun/guncon2.cpp

- Adding PAL values for Dino Stalker, Resident Evil Dead Aim, Crisis Zone.
- Minor text cleanup and unified the sorting order.
Fixing GunCon2 usage on PAL games (until someone does something that does not require manual values).
- Test each game, both on the calibration screen and during gameplay.
- See that the gun calibrates properly and that the cursor perfectly follows the mouse, both horizontally and vertically.
- Confirm that the game detects shots fired at the edges of the screen, not just that the game detects that the gun is offscreen.

Adding PAL values for Guncon2.

---

bin/resources/GameIndex.yaml

Adds CPU CLUT to fix ghosting on basically everything.
Ghosting is bad.

GameDB: Add CPU CLUT to Lego Batman The Videogame

---

pcsx2/x86/ix86-32/iR5900-32.cpp

A user reported a crash in Ico on Discord, turns out it was going into a stack overflow because of recursively compiling `jr ra`.
Full code is:
```
Compiling 00160720 jr   ->ra
Compiling delay slot 00160724 jr        ->ra
Compiling 00192B10 jal  ->$0x001448D8
Compiling delay slot 00192B14 daddu     a0, s5, zero
```
So, a triple jump, yay. While it _could_ be a bad dump, we shouldn't be crashing on such a code sequence regardless.
My understanding is it would execute as `jr ra`, `jr ra`, `jal nnn`, `jal nnn`, `daddu` (basically, the second jr rewinds the pc again). So, in this case, ignoring the first delay slot would have the same observable effect on the guest state by the time that `0x001448D8` executed.
Edit: would the new ra change after the second jal? possibly.... but it doesn't …

x86/iR5900: Ignore double jr/jalr branches like others

---

README.md

Uses the new API from Shields.
See: https://github.com/badges/shields/issues/8671
I think this looks better
Compared to this
Look at the readme https://github.com/PCSX2/pcsx2/blob/5e52339f991cacd4373ff33a673bf44e3daa407c/README.md

README: Use the new API from our badge provider

---

pcsx2/CDVD/CDVDcommon.cpp

Adds a warning to `CDVDsys_SetFile` when windows reports the source drive to be removable.
[GetDriveTypeW](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdrivetypew)
People have been experiencing poor performance when running their games off of removable media such as portable hard drives and thumb drives.
Try running an image on a USB stick, or any other removable media, and see if you get the warning. Please test things such as big picture mode.

CDVD: Warn the user when a selected game image is on a removable drive.

---

bin/resources/shaders/common/fxaa.fx

GS-d3d12: Fix macro redefinition error in fxaa shader.
Shader log warning.
Make sure the warning is gone.

GS-d3d12: Fix macro redefinition error in fxaa shader.

---

pcsx2/GameDatabase.cpp

GameDB: Fix empty could not find serial and searching for serial logs.
Fixes the logs from pasting when the size of the serial is 0 which is invalid.
Fixes the logs from pasting when they shouldn't.
Make sure the logs only paste when they actually detect a missing serial in gamedb.

GameDB: Fix empty could not find serial and searching for serial logs.

---

pcsx2/USB/usb-pad/usb-pad.cpp
pcsx2/USB/usb-pad/usb-pad.h

Adds a power curve option to the steering axis.
Fully linear steering inputs are quite harsh when mapped to pad sticks. This applies an input^n+1/range^n function to damp smaller inputs at the expense of compressing input at higher values. Not recommended for use with a real wheel but helps smooth input for pad users.
Turning your wheel or stick too much shouldn't blow up things.

USB: Power curve option for wheel steering axis.

---

pcsx2/Pcsx2Config.cpp

`__WXMSW__` isn't set when building with Qt because there's no wx.
go away wx go away wx go away wx
Not really needed, changes are obvious.

Config: Fix McdCompressNTFS not getting set in Qt

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Fixes VRAM usage blowing out with high blending.
Running at seconds per frame is never good.
Test good ol' carbon at high blending in DX12/GL/Vulkan with barriers off.

GS/HW: Reuse texture for RT copy in DX12/GL/Vulkan

---

bin/resources/GameIndex.yaml

Fixes the GIFChain hang on Reveal Fantasia by adding Instant DMA.
Games hanging is bad.

GameDB: Add Instant DMA to Reveal Fantasia

---

pcsx2-qt/Settings/ControllerBindingWidgets.cpp
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/InputManager.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/USB/USB.cpp
pcsx2/USB/USB.h
pcsx2/USB/deviceproxy.cpp
pcsx2/USB/deviceproxy.h
pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.h
pcsx2/USB/usb-mic/usb-mic-singstar.cpp
pcsx2/USB/usb-pad/usb-pad.cpp
pcsx2/USB/usb-pad/usb-pad.h
pcsx2/USB/usb-pad/usb-seamic.cpp
pcsx2/USB/usb-printer/usb-printer.cpp
pcsx2/USB/usb-printer/usb-printer.h

What the title says. Adds USB options to the controller settings page of the big picture UI, plus some other minor misc USB fixes.
It was missing and I said I'd do it post-merge.
Test new big picture options.

FullscreenUI: Add USB to controller settings

---

CMakeLists.txt
build.sh
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

This gets rid of two now obsolete flags in build.sh.
Also, the variable s_dump_root was still being used in two places, causing compilation to fail if ENABLE_OGL_DEBUG was defined, and it was trying to install a now non-existant file at the end of building.
Being able to compile pcsx2 is good, as is not having flags in build.sh that don't do anything.
Check to see if OGL debug actually saves to the right directory, as I just made the same changes that were in the rest of the commit that removed that variable.

Clean up issues related to removing wx.

---

bin/resources/GameIndex.yaml

Adds mipmapping full trilinear PS2 and HPO Special to Eragon to fix up the rather terrible looking image quality.
It looks awful and should be fixed by these changes.
Makes sure CI is happy.

GameDB: Add Mipmapping to Eragon

---

pcsx2-qt/Settings/CreateMemoryCardDialog.cpp

Fixes an #ifdef that should have been an #ifndef.
We shouldn't have an option enabled on platforms that it doesn't work on.
Open pcsx2, go to create a memory card, and look at the checkbox for NTFS.

NTFS: Disable the NTFS checkbox on Linux, not Windows.

---

pcsx2-qt/Settings/FolderSettingsWidget.cpp
pcsx2-qt/Settings/FolderSettingsWidget.ui

Allow the cheats directory to be edited from the Qt GUI.
Feature parity with the now-departed wx. Fixes issue #7436
Build, change the cheat folder, and ensure any cheats in that folder load.

Qt: enable editing cheats directory

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Adjust the skip amount to get rid of a weird shadow as a result of the existing CRC. 
Unfortunately although the original effect works, it doesn't upscale at all, so it's better removed, and the original hack caused a strange shadow caused by some depth read but made worse by the original skipped draws.
Already had the testers check the Yakuza 1 & 2 games.

GS-HW: Adjust Yakuza CRC hack to remove weird shadow

---

pcsx2/SaveState.cpp
pcsx2/StateWrapper.h
pcsx2/USB/USB.cpp
pcsx2/USB/USB.h

The current save state system is utterly rubbish and completely incapable of storing variable sized data.
I'd like to rip it all out eventually, but this is a stop-gap solution (with a double copy) for now, so that PCSX2 doesn't crash when saving eyetoy data, which was above the fixed 64K previously reserved for USB devices.
Closes #7689.
Test saving/loading state with USB devices, particularly eyetoy.

SaveState: Partial migration to StateWrapper for USB

---

pcsx2/Frontend/DInputSource.cpp

DInput: Fix incorrect Dpad labels
Down/Left and Right labels are rotated:
Will need to reassign the impacted buttons to work

Pad: DInput: Fix incorrect Dpad labels

---

pcsx2/USB/USB.cpp

Although I made `USBasync()` a decent bit faster in the USB refactor, it's still not free, and wastes CPU time when there's no USB devices connected. So, in theory, we should be able to skip it entirely in such a case.
But I'm not 100% sure yet. From some quick testing, things seem to work fine if you hotplug, but if the game was talking to the USB controller prior to the device being connected, it might get confused.
So, testers, see if you find any games where hotplugging USB devices breaks with this PR.
Saving some valuable EE thread CPU time.
See above.

USB: Only update when devices plugged

---

pcsx2/USB/USB.cpp

See title.
Regression from #7692.
Probably difficult to test unless you have old state lying around. I guess you could manually delete USB.bin from the p2s file.

USB: Fix loading old states without USB.bin

---

pcsx2-qt/Settings/ControllerSettingsDialog.cpp

Corrects the tab it goes to when selecting Settings->Hotkeys
Before USB was added it was tab 3, but now it's tab 5, but this wasn't updated to point to it, so Settings->Hotkeys went to the USB settings.
Test using the Settings menu

UI: Fix selected tab from hotkeys menu shortcut

---

pcsx2/GS/GSRegs.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Handles single page width clears with a large height as a full buffer clear, since HW cannot handle it. Also uses the colour the game wishes to clear with instead of forcing zero.
Superman Returns does single page width clears with a non-zero colour which causes massive textures consuming the entire GS memory to be created, causing bad frames to be selected at the present, resulting in flashing, since we're now more specific on which target we use now.
Test games, make sure nothing is broken, especially games which break if you disable safe features or know of ones which do "double half clear", etc.
Fixes screen flashing on Superman Returns: The Video Game.

GS-HW: Handle clears with single page width better + use vert color

---

common/D3D12/Texture.cpp

Return instead of changing the variable, meant the pitch wasn't initialized and it'd crash.
Crashes are bad.
Easiest way to test is by spamming window resize in big picture mode, but unless your resolution is high, might not be able to trigger the crash.

D3D12/Texture: Fix crash when upload buffer exhausts

---

bin/resources/GameIndex.yaml

Adds timing fixes for Robin Hood 2 - The Siege
Game is broken, this combination of things seems to be enough to make it mostly work.
Watch CI

GameDB: Add fixes for Robin Hood 2 - The Siege

---

bin/resources/GameIndex.yaml
pcsx2/Docs/gamedb-schema.json
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Patch.cpp
pcsx2/Patch.h
pcsx2/Patch_Memory.cpp
pcsx2/VMManager.cpp
pcsx2/x86/ix86-32/iR5900-32.cpp

Reimplement dynamic EE JIT patching as was first attempted in #4541, but better and actually generic for use with any game.
We needed dynamic patching to fix some bugs with Ratchet & Clank 2, specifically the Mega Turret problem.
Test Ratchet & Clank 2 PAL and see if the Mega Turret works. You can also mess with the GameDB and add your own.
To add your own the format is like this
```
dynaPatches:
- pattern:
- { offset: 0x0, value: 0x0280202d }
- { offset: 0x4, value: 0x3c0140d0 }
- { offset: 0x8, value: 0x44810800 }
- { offset: 0x10, value: 0x46000836 }
replacement:
- { offset: 0x4, value: 0x3c013f80 }
```
The important ones here are the pattern and replacement. 
The pattern is the sequence of EE instructions it needs to match in order to apply the patch, each code will be tested at an …

GameDB/Patching: Add dynamic EE JIT patching

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/AdvancedSettingsWidget.cpp
pcsx2-qt/Settings/AdvancedSettingsWidget.h
pcsx2-qt/Settings/AdvancedSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp
pcsx2/System.cpp
pcsx2/System.h
pcsx2/VMManager.cpp
pcsx2/VU0microInterp.cpp
pcsx2/VU1microInterp.cpp
pcsx2/VUflags.cpp
pcsx2/VUops.cpp
pcsx2/x86/microVU_Clamp.inl
pcsx2/x86/microVU_Compile.inl
pcsx2/x86/microVU_Execute.inl
pcsx2/x86/microVU_Lower.inl
pcsx2/x86/microVU_Misc.h
pcsx2/x86/microVU_Upper.inl

As discussed in #7241.
~Untested apart from checking the config loads as expected. Not complete, the big picture UI hasn't been updated, nor have the ints for clamping.~
~Also has no gamedb support yet.~
Note that when testing you'll probably want to disable game fixes (also in the advanced tab), to stop the existing gamedb overriding it (if any). Confirm in the console/log that the correct settings are being applied.
#7241.
None at the moment.
Closes #5188

Config: Add separate VU0/VU1 round/clamp mode options

---

pcsx2/Vif0_Dma.cpp
pcsx2/Vif1_Dma.cpp

Updates the VU's before waiting for them.
Could cause unnecessary delays when Instant VU is off, since the DMA's run before the VU's do, and if the game is running tons of tiny VU programs which are only a few cycles long, we could be inadvertantly waiting too long and wasting cycles.
Test games such as Parappa the Rapper, and random stuff with MTVU disabled.
Fixes #7608

VIF: Make sure VU's are updated when waiting

---

bin/resources/GameIndex.yaml

Adds vu1 nearest rounding to Hitman Contracts to fix missing light cones curtains and certain effects.
Game look bad without effects.

GameDB: Add VU1 Rounding to Hitman Contracts

---

bin/resources/GameIndex.yaml

Adds preload frame to Princess Maker 2
Black screen without it
watch CI, test princess maker 2 if you want

GameDB: Add HW mode fixes for Princess Maker 2

---

pcsx2/USB/usb-mic/usb-headset.cpp
pcsx2/USB/usb-mic/usb-mic-singstar.cpp
pcsx2/USB/usb-pad/usb-seamic.cpp

Limits the lowest value you can set for input/output latency to 1ms
0ms is impossible, but also causes cubeb to crash, so probably best we don't allow it.
try to set stupid tiny values in the usb settings for any of the headset/singstar/seamic adapters, also boot emu and make sure it works.

USB: Limit microphone lower latency to 1ms

---

pcsx2/Vif0_Dma.cpp
pcsx2/Vif1_Dma.cpp

do casting outside of calculation
For some reason it wasn't working on linux, so just doing it like everywhere else.
Test Parappa the Rapper 2 on linux.
Fixes #7723

VIF: use outer cast in VU cycle checks

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h

Qt: Allow to run bilinear filtering when integer scaling is enabled.
Fixes #7180
Fixes #7622
User request
Tested already.

Qt: Allow to run bilinear filtering when integer scaling is enabled.

---

bin/resources/GameIndex.yaml

Adds VU0 Extra + Preserve Sign to Sly 3 to fix the bugged camera and not break the "The Ancestors' Gauntlet" level.
Less broken game more gooder better.
Closes #7241 

GameDB: Add VU0 Clamping to Sly 3

---

bin/resources/GameIndex.yaml

Disables texture preloading in Time Crisis 3 to massively improve performance.
Performance is very bad with it enabled, that is bad.

GameDB: Disable texture preloading for Time Crisis 3

---

pcsx2/x86/iR5900Misc.cpp

Typo which caused incorrect sa to be saved in the kernel, which crashed UEFA Champions League 2006-2007 on starting a game.
Closes #7729
Safe to yolo merge, issue is obvious. But I did check it no longer crashes.

x86/iR5900: Fix incorrect blend in mfsa

---

pcsx2/PCSX2Base.h
pcsx2/x86/microVU_Compile.inl

Aligns the VU JIT buffer to 32byte for AVX2 and 16byte for SSE4, regardless of which version of PCSX2 you use.
When using an SSE4 build (which the MultiISA technically will be) it could have aligned to 16bytes (128bits) not 32bytes(256bits) which is required for AVX2, causing crashes when using VMOVAPS (aligned move) since AVX2 instructions can still be used if available.
Already tested, just need to wait for the CI

mVU: Align x86ptr based on AVX2 caps

---

pcsx2/DEV9/AdapterUtils.cpp

Fix out_of_range exception when parsing a gateway address ending in a number > 128 (i.e 192.168.1.254) on Linux
Don't crash when encountering unusual gateway addresses
Test with typical gateway addresses (i.e. 192.168.1.1)
Test with unusual gateway addresses

DEV9: Fix out_of_range exception with automatic gateway

---

pcsx2/x86/microVU_Execute.inl
pcsx2/x86/microVU_Misc.inl

eax wasn't being backed up, and in most cases it contains the address we're loading from/storing to.
Fixes #7740.
Test Arc the Lad.

microVU: Fix VU1->VU0 register access in MTVU mode

---

pcsx2/GS/Renderers/SW/GSDrawScanline.h
pcsx2/GS/Renderers/SW/GSRasterizer.h
pcsx2/GS/config.h
pcsx2/PCSX2Base.h

Also remove unused options from config.h
Unnecessary includes, recompiling unnecessary files when changing config
Make sure build passes.

Misc: Remove GS/config.h include from PCSX2Base.h

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtUtils.cpp

It tried to return the main window's handle for screensaver inhibit, which isn't visible/mapped in nogui mode.
Fixes #7721.
Test nogui parameter (preferably on linux).

Qt: Fix Host::GetTopLevelWindowInfo() in nogui mode

---

bin/resources/GameIndex.yaml

Hashcache disabled + FMVsoftwaregamefix + Roundsprite for Iris 2 Roundsprite was forgotten to be added for the Japanese entries for iris 3 (eternal mana 2)
Kinda fixes https://github.com/PCSX2/pcsx2/issues/7746
Less tinkering
Test iris 2 or iris 3 variants.

GameDB: Iris 2 + Iris 3

---

bin/resources/GameIndex.yaml

Sets texture preloading to partial for Tekken 4 to prevent it from exploding most violently.
Performance being bad is bad we should make it good.

GameDB: Set preloading to Partial for Tekken 4

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp

- One annoying issue is when you watch the emulator when unfocused especially on light themes such as the blue theme where the button is very light and the text as well.
- Before:
- After (If focused when you clicked it will look the same):
- Re-ordered the themes according to their position in the GUI.
- Also added a purple variant for Scarlet Red and a Blue variant for Ruby.
- Violet Angel:
- Sapphire:
Less annoying shit + more variety.
Test themes. (Hot-swapping is still kinda buggy as it needs PCSX2 to be restarted).

Qt: Fix out of focus colors + 2 new dark themes

---

common/GL/Program.cpp

common-ogl: Fix Program linked with warnings log spam on gl.
Mostly observed on amd driver.
Log spamming when it shouldn't.
Make sure the console error is gone on amd gpus on windows.

common-ogl: Fix Program linked with warnings log spam on gl.

---

cmake/BuildParameters.cmake
cmake/SearchForStuff.cmake

Fixes the build system potentially getting confused with a partial ffmpeg installation.
Also gets rid of the stupid debug logic from 2016 which didn't make sense even back then.
Should fix #7765, but I'm not installing Fedora to find out.

CMake: Search specifically for the ffmpeg components we need

---

pcsx2-qt/SettingWidgetBinder.h
pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/AudioSettingsWidget.h

Makes the sliders behave the same as the other non-checkbox/combo per-game settings, i.e. change value to set, right click -> reset to use global setting. However, due to space constraint, default isn't prefixed, instead it sets the font of the corresponding label to bold.
Closes #7600.
Test per-game audio settings (volume, and one of the latency/TS options for example). No need to test all, but volume and one other, since the code is duplicated for volume (so it doesn't lag when dragging).

Qt: Fix per-game settings with sliders

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtUtils.cpp
pcsx2/Frontend/DInputSource.cpp

Using dinput would cause PCSX2 to crash on startup. See individual commits for more explanation.
Crashes are bad.
Test dinput.

DInputSource: Fix crash and operation in nogui mode

---

bin/resources/GameIndex.yaml

Makes a bunch of VU gamefixes more specific to the correct VU unit, also add missing fixes for guitar hero games (and corrected some). Only really round modified for the most part, clamping is less problematic to calculation errors.
Also filled in comments for all VU/EE rounding and clamping settings in the DB.
Nicer to make things specific to the unit that needs them, less chance of problems.
I guess if you wanna test the games that were modified to make sure they're okay, otherwise, check the CI.
Were missing but now added:
Guitar Hero - Van Halen
Guitar Hero - Smash Hits/Greatest hits
Guitar Hero - Aerosmith on Tour
Simple 2000 Series Vol. 48 - The Taxi - Untenshu ha Kimi da
Can't test:
Sly 3 (bombs/ladders) - GiladN on Discord is testing for me.
Freaky Flyers (bad effects) - not sure …

GameDB: Comment all EE/VU fixes, add some missing ones

---

pcsx2-qt/Debugger/BreakpointDialog.cpp
pcsx2-qt/Debugger/CpuWidget.cpp
pcsx2-qt/Debugger/DisassemblyWidget.cpp
pcsx2-qt/Debugger/DisassemblyWidget.h
pcsx2-qt/Debugger/MemoryViewWidget.cpp
pcsx2-qt/Debugger/RegisterWidget.cpp

- Page Up/Down hotkey for the disassembly view
- Stops certain actions from being performed if the VM is dead (fixes crashes)
- Add the missing functionality of toggling breakpoints on or off through the breakpoint dialog and list
- Add a 'NOP Instruction(s)' context menu action for the disassembly view
Fixes / Features
Test the above.

Debugger: Cleanup and fixes

---

bin/resources/GameIndex.yaml

Removes disable Instant VU1 from SoTC as it should be user choice to enable or disable it if needed.
It was dumb to even add this and I will now remove it because it is dumb and shouldn't have been even added.

GameDB: Remove disable Instant VU1 from SoTC

---

pcsx2/USB/usb-mic/audiodev-cubeb.cpp
pcsx2/USB/usb-mic/audiodev-cubeb.h
pcsx2/USB/usb-mic/audiodev-noop.h
pcsx2/USB/usb-mic/audiodev.h
pcsx2/USB/usb-mic/usb-mic-singstar.cpp

Turns out I broke this with the Qt refactor.
Probably a bit difficult to test if you don't have a stereo mic, but I've double checked the logic and it seems sound (hah).
Using the real singstar mic currently doesn't support two players.
Test singstar games with usb mic.

USB: Support stereo input for Singstar Mic

---

bin/resources/GameIndex.yaml

Adds HPO Special Mipmapping Full and Trilinear PS2 to FIFA 06 to 10 and fixes the name and adds HPO Special to Conan.
I never want to play a football game again.

GameDB: Various fixes for FIFA games and Conan

---

pcsx2/USB/usb-hid/usb-hid.cpp

It was reading/writing past the end of the array, striding by `sizeof(u8) * 16` instead of `sizeof(u8)` (but still saving the same total number of bytes).
Fixes crash when using save states with USB keyboard.
Already tested, issue is fairly clear.

USB: Fix incorrect serialization of HIDKbdDevice.

---

bin/resources/GameIndex.yaml
pcsx2/SPU2/spu2sys.cpp

Allows writing of loops start if voice processing has already written it.
Games do sucky things they shouldn't, waveform writing in the first 4T's has priority over register writes, but if this has already passed then the register write can take effect. Regression from #4186 
Retest stuff on #2371 (already tested Mafia, Megaman X7, Unreal Tournament) and White Van Racer if you're insane enough to own that game.
Fixes White Van Racer
Fixes #5991 (Pro Biker 2)

SPU2: Allow loop rewrite of LOOPSTART if block header already passed

---

CMakePresets.json

This adds a number of cmake presets to the project to make compiling easier. These can be used when compiling on the command line, and Visual Studio Code has built in support for them.
Just to note, the existing ways of building still work. This is just an alternative.
Compiling with the clang-devel preset, for example, would be a matter of typing:
```
mkdir build
cd build
cmake --preset clang-devel ..
make
```
Alternatively, if you don't like command lines:
In Visual Studio Code, open the pcsx2 folder. It'll automatically have you choose a preset, create the build folder for you, run the cmake command, and if you hit play at the bottom, it'll compile and open pcsx2.
You can also add your own presets beyond the ones I've added by adding a CMakeUserPresets.json file.
Presets I've added: …

build: Add cmake presets to pcsx2.

---

common/AlignedMalloc.h
common/SafeArray.h

Removes the define pxUSE_SECURE_MALLOC, and any code that checks for it.
If you try and enable that code, it doesn't compile, as the function being called doesn't exist. Less dead code is better.
Compile!

common: Remove pxUSE_SECURE_MALLOC.

---

bin/resources/GameIndex.yaml
pcsx2/CMakeLists.txt
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/GSCrc.cpp
pcsx2/GS/GSCrc.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/GSUtil.cpp
pcsx2/GS/GSUtil.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSRendererHWMultiISA.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/MTGS.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp
pcsx2/pcsx2core.vcxproj
pcsx2/pcsx2core.vcxproj.filters

The game database is a better place for them.
Also gets rid of CRC hacks from the base GSState class - the software renderer doesn't need to worry about them, let alone use them.
Also adds a CRC hack for Barnyard to fix the mipmap rendering by punting it to the CPU.
Also fixes the cut-off screen in Battlefield 2 - Modern Combat. But you need full blending for the terrain to render correctly, and draw calls go brr haha.
Making CRC hacks apply to demos etc, easier maintenance in the future (we don't know all game CRCs).
Fixes mipyard (barnyard).
Fixes #1565.
Closes #5062.
Test games which use CRC hacks (e.g. burnout 3).
Test Barnyard.
Test Battlefield 2 Modern Combat.

GS: Move most CRC hacks to the game database

---

pcsx2-qt/MainWindow.cpp

I've given some love to dark themes, but doesn't mean light themes doesn't deserve it either. Making it better in contrast to make it more legible along with making it a bit more appealing.
- PCSX2
- Before:
- After:
- Untouched Lagoon
- Before:
- Aft
er:
- Baby Pastel
- Before:
- After:
Don't want bad/worse themes and not be used at all
Test PCSX2 (Blue), Baby Pastel (Pink) and Untouched Lagoon (Green)

Qt: Fix light themes

---

bin/resources/GameIndex.yaml

Adds Tex in RT and CPU CLUT to BF2 MC to fix lights shining through objects like the moon shining through buildings.
Light be gone

GameDB: More BF2 MC Fixes

---

common/Vulkan/Context.cpp
common/Vulkan/Context.h
common/Vulkan/SwapChain.cpp
common/Vulkan/SwapChain.h
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/Frontend/VulkanHostDisplay.cpp
pcsx2/PerformanceMetrics.cpp
pcsx2/PerformanceMetrics.h

Avoid using the same semaphore for multiple images.
Grab the next swap chain image immediately after presenting, before going to sleep. Should reduce the next frame's present time.
Expose threaded presentation in the UI, apparently on some systems it improves things?
Making Vulkan frame times less erratic.
Test new options, make sure stuff like window resizes/fullscreen toggles still work.

GS/Vulkan: Potential improvements to frame timing

---

bin/resources/GameIndex.yaml

Adds gamedb entry of InstantVU1 being disabled for above game.
Last boss hangs going in to his elevator kind of thing without this due to a timing problem, this seems to correct/avoid it.
Watch the CI, change has already been tested

GameDB: Add Disable Instant VU to Batman - Rise of Sin Tzu

---

bin/resources/GameIndex.yaml

- So I have found an actual Spanish copy of Terminator 3 - Rise of the Machines. When I did my previous research, I mostly focused on information legally locatable on the Internet (mostly pictures taken by news websites and second hand markets such as eBay). Turns out the region labelling is wrong (it's a Spanish-only disc), but the name is still correct? (the cover/manual are for Spanish and Portugal, while the game does not have a Spanish/Portuguese selector and the main menu reads the localized "La rebelión de las máquinas" name). The Italian release has a separate disc elsewhere.
- Adding Buzz!: ¿Qué sabes de tu país? (Buzz! Brain of... from Spain/Portugal).
Polishing the GameDB to the nth degree.
Find those games and see that the names are now adequate.

GameDB: Fix Terminator 3 Spain region, add Buzz Brain of Spain

---

pcsx2/x86/microVU_IR.h

Fixes out of bounds check when clamping Q register on the VU's
Out of bounds undefined behaviour is bad, mkay.
Watch CI

VU: Fix out of bounds check for Q clamp

---

pcsx2/x86/microVU_IR.h

`x86regs[n].reg` is signed now.
Regression from #7769.
Difficult to test since release builds don't have assertions, but FFX no longer trips the assert in a debug build.

x86/microVU: Don't assert clearing macro mode temps

---

pcsx2/GS/GSRegs.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes white screen inbetween logos in FFX.
It uses the following blend:
```
ALPHA
A:1
B:2
C:2
D:2
FIX:0
=> (Cd - 0) * Af + 0
```
Which was one of the cases we optimized in #7539 - iirc Burnout 3 used it. But it was confusing the software renderer (causing it to use a block fill instead of a proper render, which tosed out Cd), I should have noted the comment above IsOpaque() that says that only Cs/As/0 is used.
So, handle the Cd case separately, and only for hardware.
In theory we could replace it with an fbmsk, but that would assume that the RGB mask was all zeros to begin with, otherwise there _would_ be a side-effect.
Fixing regressions.
Test booting FFX in software, make sure there's no white flicker between logos.

GS: Separate Cd output from Cs blend cases

---

bin/resources/GameIndex.yaml

Corrects Blood Omen 2s name to properly say "The Legacy of Kain".
Name correct more gooder.

GameDB: Correct Blood Omen 2 name

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/AudioSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/SPU2/Mixer.cpp

Removes the options menu for interpolation as all but gaussian will be removed.
Having a selection box for just one option is a bit silly I'll see if I can remove the actual code for it later on in another PR as that part frightens me more than this.
Make sure the CI doesn't explode and that audio still works.

SPU2: Purge interpolation options

---

CMakeLists.txt
cmake/BuildParameters.cmake
pcsx2-qt/Debugger/DisassemblyWidget.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/QtHost.cpp
pcsx2-qt/SettingWidgetBinder.h
pcsx2-qt/Settings/ControllerSettingsDialog.cpp
pcsx2-qt/Settings/InputBindingDialog.cpp
pcsx2-qt/Settings/InputBindingWidget.cpp

-Wno-overloaded-virtual & -Wno-deprecated-declarations were there to mute out warnings coming from wx and gtk 2 code, so I removed them.
This lot to a bunch of deprecated Qt warnings that had been muted showing up. Resolved those warnings.
Added -Wno-maybe-uninitialized, as the GS vector code in gcc spams a bunch of warnings (about member m in GSVector8i, IIRC), and I wasn't sure how to resolve them otherwise.
Added cmake policy code for CMP0069 that stenzek suggested earlier.
(There are still some warnings, but a good deal less, and one already has another pr open.)
It's generally better to fix warnings, when possible. Deprecated api calls will eventually be removed, so it's best to take care of them. (With wxwidgets, it was using ancient gtk code in the library itself, so there was no …

Build/Qt/GS: Unmute some warnings, & resolve Qt/misc warnings.

---

pcsx2-qt/Settings/AudioSettingsWidget.cpp
pcsx2-qt/Settings/AudioSettingsWidget.ui
pcsx2-qt/Settings/EmulationSettingsWidget.cpp
pcsx2/Config.h

Lowering 100 ms audio latency to 60 ms.
Makes 100 mixing latency with 20 output latency (120) into a new total default of 80 ms which is 50% lower but still is enough headroom as 40 ms even for less capable machines is too high. Unless you have a real potato which it will still skip at 200+ but at that time you will have changed to async mode to make it more bearable, switched games or other settings.
Lowering the mixing latency even more would be detrimental.
Adding tooltip for Affinity Control
Changing tooltip for Cycle Skip from None to Disabled as that is a valid option.
1.6 already had problems at 100 ms and 1.7 nightly/dev builds can handle much lower values without skipping.
Test games, preferable heavier games perhaps with weaker computers/laptops as well.

Qt: Lower audio ms + Tooltip (affinity+Cycle skip)

---

pcsx2/VMManager.cpp

3 is a nice compromise if you have 4 core or more but for some games higher numbers like 8 or even higher would work, however for a lot of games it would perhaps even reduce the performance compared to 3 software rendering threads or in more likelihood have diminishing returns.
MTVU was already auto-detected to be enabled if you have 4+ cores (minus the automatic fixes for specific games that dislike MTVU) which makes it better for the user experience not giving a single care and having a better experience than even 1.6 where you needed to enable it by hand or by preset 3. Now this will go hand in hand with MTVU and not leave free performance on the table where possible. Keep in mind if you have 2/4 CPUs like 2 cores with multithreading this won't be activated but might or not help if you …

VMManager: Increase software thread count on multicore (4+) CPUs

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

Draws its mipmaps at runtime in a very similar way, except with 24-bit textures as well as 16/32-bit.
Closes #6953.
Closes #5743.
Test Jurassic Park and Nicktoons. I don't have the games, only the GS dumps, so someone who owns them will have to check.

GS/HW: Adjust Barnyard fix for Jurassic Park and Nicktoons Unite

---

common/Vulkan/SwapChain.cpp
common/Vulkan/SwapChain.h

Some drivers apparently don't iterate images in the order you expect.
Closes #7852.
Make sure Vulkan works. I've tested radv on Linux.

Vulkan: Use pool of semaphores instead of per-image

---

common/emitter/cpudetect.cpp
pcsx2-qt/Debugger/BreakpointDialog.cpp
pcsx2-qt/Debugger/Models/BreakpointModel.cpp
pcsx2-qt/Debugger/Models/BreakpointModel.h
pcsx2-qt/Debugger/Models/ThreadModel.cpp
pcsx2-qt/Settings/AudioSettingsWidget.cpp

Reducing warning spam. One of these is actually a legit error too (the EE threads one, the object it's referencing is destroyed at the end of the statement).
Make sure build passes.

Misc: Latest round of warning cleanups

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSMTLSharedHeader.h
pcsx2/GS/Renderers/Metal/convert.metal

Implements CLUT update shaders for the Metal renderer
Make GPU CLUT updating work on Metal
~~Completely untested, may or may not work, please test~~ Got two reports of it working so I'm calling that good

GS:MTL: Implement clut update shaders

---

cmake/BuildParameters.cmake

Removed some code turning on -Wno-deprecated-register -Wno-c++14-extensions for clang.
Compiling without those flags in clang doesn't have any warnings, so the issues that they were turned off for are no longer there.
Compile with clang.

cmake: Turn back on some warnings that no longer need to be turned off.

---

bin/resources/GameIndex.yaml

Add HPO Normal to Sega Superstars Tennis
Bloom was misaligned when upscaling
watch CI

GameDB: Add Half-Pixel Offset for Sega Superstars Tennis

---

pcsx2-qt/Debugger/BreakpointDialog.cpp
pcsx2-qt/Debugger/DisassemblyWidget.cpp
pcsx2/DebugTools/DebugInterface.cpp

This PR adds three new references for the debugger condition expressions
`target` -> The evaluated target of the load or the store, 0 if the opcode is not a memory access
`load` -> The evaluated target of a load, is 0 if the opcode is not loading
`store` -> The evaluated target of a store, is 0 if the opcode is not storing
----
`v1 = 0x12000000`
<table>
<tr>
<td>
<b>Breakpoint Instruction:</b>
<td>
<b>ld v0,0x1000(v1)</b>
<td>
<b>sd v0,0x1000(v1)</b>
<td>
<b>nop</b>
<tr>
<td>
<code>target</code>
<td>
<code>0x12001000</code>
<td>
<code>0x12001000</code>
<td>
<code>0</code>
<tr>
<td>
<code>load</code>
<td>
<code>0x12001000</code>
<td>
<code>0</code>
<td>
<code>0</code>
<tr>
<td>
<code>store</code>
<td>
<code>0</code>
<td>
<code>0x12001000</code>
<td>
<code>0</code>
</table>
Some other stuff …

Debugger Expressions: Add 'target', 'load', and 'store' references

---

pcsx2/Frontend/FullscreenUI.cpp

What the title says. PCSX2 might crash, or cause a GPU reset while deleting state otherwise.
Crashing bad.
Test deleting state in fullscreen UI, make sure no validation errors occur (already done myself).
Fairly safe change, it just moved the block further up in the function.

FullscreenUI: Fix descriptor use-after-free when deleting state

---

pcsx2/SPU2/SndOut.cpp

SPU2: Cleanup SndOut.cpp
const, casts, constexpr, initializations.
Remove dynamic tuning commented out code. No longer works as it relied on wx.
SPU2: Update WriteSamples function commented out code to work properly when enabled.
Code cleanup.
Compiles, spu2 works.

SPU2: Cleanup SndOut

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp

The post-processing effect, which from what I can tell, we'll never be able to emulate in hardware (it overlaps FRAME and Z) needs a variable skip count for when autoflush is on versus off. The on case was wrong before, it had an extra draw, which loaded a 1024x1024 texture into the hash cache, wasting CPU time hashing, and spiking the memory usage.
Also gets rid of preload frame, it doesn't seem to be needed for the sun to work? But the testers can confirm.
Slight performance improvement.
Test Burnout games, make sure nothing's broken that wasn't broken before.

GS/HW: Adjust Burnout CRC hack to stop hash cache spiking

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Detail in commits.
Allocating a 32k texture is silly.
Jordan knows what to do.

GS/HW: Break slightly less when booting Mercenaries at high upscaling

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

GS-hw: Cleanup GSRendererHW.
Constants, initializations, casts, broken commented out logs and more. Remove unused/duplicate function EmulateAtst.
Code cleanup.
Tested on several dumps, but test more just to make sure nothing is broken, hw renderers.

GS-hw: Cleanup GSRendererHW.

---

bin/resources/GameIndex.yaml

Note: All the FPS that is gonna be mentioned below is meant to be the in-game/in-level FPS, not the menus nor the cutscenes,
The PAL version of Syphon Filter: The Omega Strain runs at 25 FPS on PS2, but on PCSX2 1.6, 1.7, ..etc (all versions) it runs mostly at 50 FPS and it's abnormally fast which is changing the whole game speed, and on PCSX2 you can reproduce the issue by rebooting the emulator, each time you reboot you might get the game at 25 FPS or at 50 FPS (game of luck) but mostly 50 and sometimes 25, also the NTSC-U and NTSC-K versions of the game run at 30 FPS so the PAL can't be this much faster so the correct speed by A) conclusion and B) testing on a real PS2 should be 25 FPS, this is a patch to fix the issue and make it run always at 25 FPS.
I posted a github issue about …

GameDB: Syphon Filter: The Omega Strain PAL speed fix patch

---

bin/resources/GameIndex.yaml

Added switch to software renderer on fmvs to 3 regions of Onimusha - warlords
It can be extremely dangerous for people who suffer from epilepy, and this is only added temporarily until a better fix is made. it should close #7787 as not planned for now.
Make sure refraction is ok with it and that it builds correctly

GameDB: Add SoftwareRendererFMVHack to Onimusha: Warlords

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/HostSettings.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/GSCapture.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/Pcsx2Config.cpp

- Add Recording tab in Graphic settings
- Move video codec, container and bitrate settings into it from Advanced tab
- Add video folder setting
- Add extra arguments setting
Now you can record a video in CRF mode while using libx264
download necessary files from #7613 and test video path setting and extra arguments
I don't know much what arguments are supported though

GS: Add video folder and support additional arguments for video dumping

---

pcsx2/SPU2/DplIIdecoder.cpp
pcsx2/SPU2/Mixer.cpp
pcsx2/SPU2/Mixer.h
pcsx2/SPU2/SndOut.cpp
pcsx2/SPU2/SndOut.h

It's clamped to 16-bit in the output anyway.
Volume application is moved to the audio thread, so the stretcher has higher precision if the user chooses a low volume.
Also vectorizes the int->float conversion (since it happens on the EE thread, it's beneficial for performance).
Clip range is increased, because I have no idea what he meant in that comment.
Holding true to the mop and bucket in my avatar, cleaning up air's mess.
It also simplifies the coming-soon audio dumping.
Test audio output, particularly reverb sensitive games, make sure nothing broke.

SPU2: Use 16-bit samples for output (and associated cleanup)

---

pcsx2/DEV9/AdapterUtils.cpp
pcsx2/DEV9/AdapterUtils.h
pcsx2/DEV9/pcap_io.cpp
pcsx2/DEV9/sockets.cpp

Adjust formatting of AdapterUtils.
Use unique_ptr to manage lifetime of ifaddrs array.
typedef the buffer unique_ptr to make it simpler to use.
More consistent formatting.
Makes AdapterUtils a little simpler to use.
Test networking on Linux.

DEV9: AdapterUtils use unique_ptr to manage lifetime of ifaddrs array + formatting

---

bin/resources/GameIndex.yaml

Adds Full mipmapping to parappa the rapper 2 to fix missing floor textures,
and Trilinear filtering to fix fog in certain levels Closes #7922
It's how the game should look like normally.
Make sure it builds correctly. and that nothing more needs to be added.

GameDB: Add Mipmapping and Trilinear to Parappa the Rapper 2

---

bin/resources/GameIndex.yaml

This beta's region is PAL and it has the same abnormal speed issue as the PAL version of the final release of Syphon Filter: The Omega Strain, same issue was discussed here #7806  so this is a patch to fix it
This Syphon Filter PAL Beta runs at an incorrect speed just like the final PAL version of the game
-Run game without patch, it runs on 50 FPS on most session, but sometimes when you reboot it runs at 25 FPS
-On PS2 it runs at 25 FPS
-The Final release version of this beta has the same issue
-The NTSC version on the game is 30 FPS so the PAL must be 25 FPS not 50 FPS
-Apply the patch and the game will run at 25 FPS (in-game only not the menus which is correct)

GameDB: Syphon Filter: The Omega Strain Beta Speed Fix

---

bin/resources/GameIndex.yaml

Corrects sun rendering in CMR3 in Hardware mode and with upscaling, presumably by allowing the sun's occlusion query to work correctly.
SW:
HW, Vulkan, 4x upscaling, current master:
HW, Vulkan, 4x upscaling, with this PR:
Hax is fix.
Check Colin McRae Rally 3.

GameDB: Correct Colin McRae Rally 3 sun rendering

---

bin/resources/GameIndex.yaml

Adds autoflush to fix texture corruptions.
Textures doing the rainbow is bad.

GameDB: Add AutoFlush to Battle For Volcano Island

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/pcsx2core.vcxproj.filters

Don't do the fast mem clear in hardware if scanmsk is enabled.
Also fixed up some VS filters for files not being in respective locations while I was there.
It broke Rimoko Koron's Sony Entertainment screen, and it's also incorrect behaviour.
Seems to also fix the same bad behaviour in Alpine Racer 3.
Apparently fixes Ichigeki Sacchuu! Hoihoi-san also.
Test Rimoko Koron in hardware.
Fixes #7923

GS: Don't do fast clear if SCANMSK is enabled.

---

bin/resources/GameIndex.yaml

Autoflush fixes the missing sun luminosity.
Sun should look more like a ball of fire and not a thin yellow circle.

GameDB: Add Autoflush to Dynasty Warriors 5 Xtreme

---

bin/resources/GameIndex.yaml

This PR contains fixes for misaligned and incorrect bloom effects when upscaling is used for SpongeBob The Movie.
When upscaling is used, the bloom looks misaligned and duplicated, it looks disorienting.
Screenshot on 4x Upscale:
In Native Res:
Make sure the bloom in-game are pleasant to see!
and make sure CI Bois is happy ;)
I have also tested it myself:

GameDB: Fixes for SpongeBob - The Movie

---

bin/resources/GameIndex.yaml

Disables Instant VU to dramatically decrease the load the game puts on the EE and VU for seemingly no reason.
This game is probably cursed and is doing something cursed that frankly I am too smooth to understand but this alleviates it somewhat so I call that a win.
Fixes #6911 

GameDB: Disable Instant VU in Kim Possible WTS

---

bin/resources/GameIndex.yaml

Removed an unnecessary HW fix for Armored Core Last Raven.
It just prevents the warning OSD when Preload Frame Data is disabled.
1. Open "Game Property"
2. Enable "Manual Hardware Fixes"
3. Disable "Preload Frame Data"
4. Start a new game
5. Start the AC Test to see if the black screen appears
I only tested SLPS-25462 (NTSC-J), so it's needed to test following games as well:
- SLPS-25730 (NTSC-J)
- SLPS-73247 (NTSC-J)
- SLUS-21338 (NTSC-U)
- SLES-53820 (PAL-E)

GameDB: Remove Preload Frame Data for AC Last Raven

---

pcsx2/GS/GSDrawingContext.h

Casts bitfields which were assigned with a u64 value to 32bits in GS draw dumping. Remove Clang pragma for format warnings.
These problems were ignored without actually checking if it was a problem, but it seems to be when doing fprintf on clang, bitfields get implicitly converted to 32bit, but not so with MSVC. So instead of ignoring it, we now cast it to 32bit, as all we need is 32bit anyways, then everybody is happy.
Dump some draws, make sure the values of MIPMAP1/2, CLAMP and TEX0 all make sense.

GS/Debug: Fix bitfield reading in fprintf for cross compatibility.

---

common/GL/Program.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS-gl/vk: Cleanup some logs.
Instead of ifdefing the longs use Devcon, does the same thing. Hide point expansion logs behind dev/debug build.
common-ogl: Fix Shader compiled with warnings log spam on gl.
Observed on intel igpu.
GS-hw: Fix texture shuffle assert which broke debug builds.
Log fixes and cleanup, debug build fix.
Logs work as intended, debug build compiles.

GS: Misc changes

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Noticed this copy/paste fail while reworking stuff for ROV.
Setting up the wrong descriptors.
Make sure build passes, difficult to test because you'd need to find a case where it actually runs out.

GS/Vulkan: Don't apply TFX state on utility draw

---

pcsx2-qt/QtHost.cpp
pcsx2/CDVD/CDVD.cpp

Queues a VM shutdown when called via CdPowerOff which is inside a currently running block.
Shutting down/Resetting the VM in the middle of executing a block will cause everything to explode (was crashing) as the state gets partially overwritten at the end of the block, so the reset is invalid.  Shutting down also doesn't work as it'll attempt to update sound output etc which will no longer exist.  so it's better to queue it and let it deal with it at a convenient point.
Run the following ELF, make sure it just closes the emulation and goes back to the game list.
[cdvdPowerOff.zip](https://github.com/PCSX2/pcsx2/files/10475155/cdvdPowerOff.zip)

VM: Queue shutdown message when called from inside emulation.

---

pcsx2-gsrunner/Main.cpp

This was missing, which meant `GSshutdown()` wasn't called, which meant the screenshot threads weren't joined before exiting `main()`.
Hopefully sorting out the random-missing-frames when doing regression runs.
Nothing for testers here.

GSRunner: Release globals on shutdown

---

pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Breaks down VRAM usage into the various pools, making it more obvious when we have spikes.
Legend:
```
S: Sources (including copies of targets).
T: Targets (where we render to, this is generally the main user of VRAM).
H: Hash cache (complete textures).
P: Pool (textures which can be immediately reused without allocation).
```
Nice to know when PCSX2 VRAM spikes (e.g. #7952).
Test new stats, make sure they don't underflow past 0 (I think I caught all the allocation sites..).

GS: Show VRAM usage in statistics

---

bin/resources/GameIndex.yaml

Adds some missing PAL demos to the DB.
Missing entry's are bad.

GameDB: Add missing PAL demos

---

pcsx2/Frontend/OpenGLHostDisplay.cpp

Fixes OSD getting messed up when the GS output is turned off.
Undefined screen contents isn't ideal.
Easiest one to test is TC:NYC after skipping the intro FMVs. Tested this myself.

OpenGLHostDisplay: Set colour mask before drawing OSD

---

pcsx2/Frontend/DInputSource.cpp
pcsx2/Frontend/DInputSource.h

Replaces a manual `FreeLibrary` in `DInputSource` with WIL.
RAII is good.
Make sure that DirectInput source initializes and shuts down correctly and without crashes, and the source itself is still functional.

DInputSource: Use wil on m_dinput_module

---

pcsx2-qt/QtHost.cpp
pcsx2/VMManager.cpp
pcsx2/VMManager.h
pcsx2/x86/ix86-32/iR5900-32.cpp

Stops us resetting during the event test, which can leave things in a pretty messed up state.
Things get pretty messed up.
Easiest one to test is TC: NYC - skip the intro FMV, wait for the logo to be displayed, reset the VM. Skip the FMV again, PCSX2 should no longer crash.

VMManager: Defer reset when running

---

pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp
pcsx2-qt/pcsx2-qt.vcxproj

Qt tries to dynamic_cast as part of an assertion, which aborts at runtime. When we next rebuild Qt, we'll disable RTTI in Qt, so this will be a non-issue. But until then, this change makes debug clang builds usable.
Clang debug builds currently abort at runtime.
None needed, CI doesn't generate debug builds.

Build: Enable RTTI for Clang debug builds

---

pcsx2/SingleRegisterTypes.h
pcsx2/vtlb.cpp

This was only necessary on 32-bit because the sign bit was abused for representing handlers. Since we're 64-bit only, we use bit 63, which won't clash with the guest's 32-bit virtual address.
Cleaner code. VTLB's already difficult enough to understand :-).
Test a few games, make sure they still run. Anything which doesn't TLB miss won't be affected, and I have tested with a couple of ELFs which do, and they still report the correct address.

vtlb: Remove upper/lower 32-bit unmapped split

---

bin/resources/GameIndex.yaml

This PR contains fixes for misaligned and incorrect bloom effects when upscaling is used for The Incredibles: Rise of the Underminer. Also adds fixes to the Spanish version of SpongeBob - The Movie, basically an expansion of #7936 
Just like The Incredibles and the SpongeBob Movie game, when upscaling is used in Rise of the Underminer, the bloom looks misaligned and duplicated, it looks disorienting.
Make sure the bloom looks correctly in-game.
GS dumps:
[after.zip](https://github.com/PCSX2/pcsx2/files/10506572/after.zip)
[before.zip](https://github.com/PCSX2/pcsx2/files/10506573/before.zip)

GameDB: Fixes for Incredibles - ROTU

---

pcsx2/CDVD/GzippedFileReader.cpp
pcsx2/CDVD/InputIsoFile.cpp
pcsx2/Frontend/GameList.cpp

Possible regression from #7965, although I couldn't reproduce PCSX2 crashing. Regardless, spamming an error popup during game list scan is a bad thing.
Unneeded popups if you happened to scan bad files.
Test game list scanning, opening valid+invalid files, make sure nothing crashes.

CDVD: Don't report host error on iso detect fail 

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp

Currently, the Help -> Check For Updates menu item will force an update check (if the user previously skipped the update), but the settings dialog will not. This PR makes both behave the same.
Inconsistent behaviour for the same task is bad UX.
Can't test on a PR build, but I have tested the changes myself locally.

Qt: Make behavior between both update checks consistent

---

pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_In.cpp
pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.cpp
pcsx2/DEV9/sockets.cpp

Bind source port of UDP connections with nearby source & destination ports.
In the sockets backend, UDP connections are by default treated as using ephemeral source ports.
Heuristics are used to determine when a UDP connection should be bind to the source port,
This proved too strict for some games using different (but nearby) ports for source/destination.
Test online games that use UDP packets for network communication, such as Twisted Metal:Black Online.

DEV9: Sockets, Treat UDP connections with nearby src/dst ports as fixed 

---

pcsx2/Frontend/ImGuiOverlays.cpp

Resolves inputs not appearing on OSD by changing pressure threshold for buttons to >0.00 from >= 0.50
Allows pressure to be seen on buttons that have it
~~Changes default button deadzone to 0.25 from 0.00~~
May or may not resolve #7881, ~~the deadzone can always be configured if users are unhappy, but having no deadzone causes problems when an analog stick is mapped to a digital button.~~
Map an analog stick to the dpad and see if the inputs and OSD match
Try using a pressure sensitive button and see if the inputs and OSD match

OSD: Fix invisible inputs

---

crowdin.yml
pcsx2-qt/Translations/pcsx2-qt_en.ts

We've selected / got approved by Crowdin to use for our translations.  Some things I'd like to iron out as part of the review process, as I'm not familiar with Qt's translation flow, and their official documentation leaves a lot to be desired.
- I generated this file via `lupdate`, specifically the following command:
- Is this correct?  It seems to be accurate, despite everything being labelled as "unfinished".  Which I think doesn't matter since it's the base language anyway?
```
lupdate.exe -recursive '.' -ts ./Translations/PCSX2Emulator_en.ts -source-language en
```
- How are the subsequent `*.ts` files for each language applied to the frontend?  I assume this is something that can be ironed out later, but one thing that immediately stands out is how should the files be named,
- …

translations: Commit initial Qt .ts translation file to integrate with Crowdin

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2/SaveState.cpp
pcsx2/VMManager.cpp
pcsx2/VMManager.h
tests/ctest/core/StubHost.cpp

This PR fixes two distinct issues related to #7945:
1. Deleting states from the dropdown did not refresh the list of save states, so it was possible to attempt to load an inexistant save state. Now any "cache" has been removed and dropdowns are just being repopulated as the menu is about to show, because it's a lightweight operation anyway and it closes virtually any edge cases. Also comes with an added bonus of pre-emptively protecting against cases where the save state was removed from Explorer.
2. Adds a distinct error message when the save state load fails specifically because the file doesn't exist, instead of giving a generic "corrupted or invalid gzip archive" message.
UI bugs ew.
* Make sure that #7945 is fixed.
* Make sure that save states populate dropdowns correctly still. …

Remove explicit save state cache invalidation and add a distinct error when a save state file doesn't exist

---

pcsx2-qt/MainWindow.cpp

Regression from a PR wiped the right click context menu for games on the game list. Tried to be too clever and missed the fact one callsite doesn't need the menus wiped.
Regressions bad.
1. Ensure that right clicking on the game in the game list works as expected.

Host: Fix a context menu regression from #7960

---

pcsx2/DEV9/AdapterUtils.cpp
pcsx2/DEV9/AdapterUtils.h
pcsx2/DEV9/pcap_io.cpp
pcsx2/DEV9/sockets.cpp

Moves code for getting the adapter MAC address into AdapterUtils.
Unifies the definitions for `GetAdapter*()` methods.
Better handle situations where we fail to get the MAC address.
Reduced code duplication.
Makes AdapterUtils a little simpler to use.
Test pcap on Windows & Linux

DEV9: Move adapter MAC address code into AdapterUtils

---

pcsx2-qt/Settings/AchievementSettingsWidget.cpp
pcsx2/Frontend/Achievements.cpp
pcsx2/Frontend/FullscreenUI.cpp

GS thread might not initialize fullscreen UI before data finishes parsing.
race conditions aren't fun
yolo because who cares?

Achievements: Fix race in notifications

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/AutoUpdaterDialog.cpp
pcsx2-qt/DisplayWidget.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Host.h
pcsx2/VMManager.cpp
pcsx2/x86/ix86-32/iR5900-32.cpp

This was a bit wonky in batch mode before. Now all possible exit paths close the application at the same point.
Also immediately stops the IOP running code when the VM enters the stopping state.
Improving #7982 and #7940.
Check PCSX2 shuts down correctly in batch/nogui modes.
Check game shutdown from menu and big picture UI.
Check ELF in #7940 works as expected in both normal and nogui mode.

Qt: Better handle VM-requesting-shutdown case

---

pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Display output uses fixed translations for 16 and 24 bit color, instead of the values in the TEXA register
Fixes #7987
Less broken
Test #7987

GS: Display output ignores TEXA

---

bin/resources/GameIndex.yaml

Adds full mipmapping and trilinear (PS2) to harry potter and the chamber of secrets to fix blurry textures also adds a missing DB entry.
Blurry flickering textures bad.
https://github.com/PCSX2/pcsx2/pull/7988#issuecomment-1407667701

GameDB: Add full Mipmapping to Harry Potter COS

---

bin/resources/GameIndex.yaml

Disables preloading entirely on Tekken Tag Tournament and Tekken 4 and adds missing fix comments and missing db entry's for both games.
Games being slow is bad.

GameDB: Various Tekken fixes

---

pcsx2/IPU/IPU.cpp

Reset alpha thresholds on IPU reset. While i don't have ability to test this on real hardware now, this seems to be correct undocumented behavior.
Fixes https://github.com/PCSX2/pcsx2/issues/6057
Game set 0x100 translucency threshold, and soon after that reset IPU. Manual mention only that "data being decoded inside ipu is abandoned" on IPU reset, but it seems this mean also alpha th.
```
[   17.2204] write32: IPU_CMD=0x91000000
[   17.2214] SETTH (Set threshold value)command 1000000.
[   17.2258] read32: IPU_CTRL=0x00000000
[   17.2270] write32: IPU_CTRL=0x00800000
[   17.2287] write32: IPU_CTRL=0x40000000
```
Watch Berwick Saga intro. Test other games, specially Hype Time Quest, and Perfect Ace 2, also FMVs in other games.

IPU: Reset threshold on IPU reset.

---

common/emitter/avx.cpp

emitter: Ignore Wmissing-braces warnings on clang.
Ignore warnings.
Warnings are gone from clang builds.

emitter: Ignore Wmissing-braces warnings on clang.

---

pcsx2/Counters.cpp
pcsx2/GS.cpp

Resets the GS Privilage Registers (ones which handle the display outputs) on GS Reset via the CSR register.
This is console accurate emulation, the real hardware also resets these, we confirmed this with a test.
run some games and make sure the displays come on, even try via the bios in software mode, where it used to leave a bit of logo at the bottom.
Fixes #3485 (Bios logo being left at the bottom)
Also fixed junk screens between loading games in the Capcom Classics Collection discs.

GS: Clear Privilage registers on GS Reset via CSR

---

pcsx2-qt/Settings/DEV9SettingsWidget.cpp
pcsx2-qt/Settings/DEV9SettingsWidget.h

Fix handling of per-game HDD path,
Fix HDD overwrite check condition being flipped.
In per game, populate the HDD file browser with the global HDD path if no per game file is set.
Fix the HDD Enable toggle not behaving correctly in per-game settings.
Rewrite the code for handling HDD size, making its UI in per game settings more constant with other settings panels.
The HDD size UI per-game settings didn't behave like other per game sliders or spinboxes, as it was written before https://github.com/PCSX2/pcsx2/pull/6780 & https://github.com/PCSX2/pcsx2/pull/7764
Use `SettingAccessor` for spinboxes as `BindWidgetToIntSetting` doesn't cover this use case
`BindSliderToIntSetting` doesn't cover this use case, so handle the context menu ourself.
Other fixes where made along the way.
Test HDD …

DEV9: QT Per-game settings fixes

---

pcsx2-qt/MainWindow.cpp

Adds a missing cleanup call in `MainWindow::onGameListRefreshComplete()`, so now the status text in the bottom bar vanishes after game scanning is complete.
Improves UI parity with DuckStation.
Notice that "Scanning directory X..." is not lingering after starting PCSX2 anymore.

Qt: Clear the status text after gamelist scanning

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Don't do Texture in RT on old frames or ones which were never drawn by the GS (we can only tell this by age, currently).
Also update a target if the source partially overlaps the end of the target, and update any dirty parts of the texture.
Also add Mipmapping and Trilinear to Jak X to fix some ground textures, also fix gs fixes for one version of Nicktoons Unite!
This was causing misdetection in Dragon Quest 8, causing FMV's to fail along with some texture corruption.
Test games which have `textureInsideRT` in the game DB, Ratchet & Clank, Jak, etc. and DQ8 ofc.
Fixes #7994 hopefully

GS-TC: Improvements to Tex in RT

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Sets the PCRTC (output circuit) to always preload the frame from the GS memory if no texture matching has been created.
Late Edition: Modifies Preload Frame to match related EE Uploads.
Many games will just draw the loading screen firstly direct from the EE and by default we create blank new textures, but this will never get updated, since the game may only write once, or it will do some sort of alpha blend (with what is now a blank texture). This resolves these situations.
Late addition: I've modified preload frame to be slightly less gross also, so it should only trigger if there's a related EE upload that frame, otherwise it won't preload, which should bring more reliable behaviour.
Late late addition and the entrance of scope creep: I also made it so the first frame after a GS reset …

GS-HW: Improve preload frame. Fix missing loading screens/logos, reduce corruption.

---

pcsx2/GS/GSClut.cpp

Adds handling for CLUT write checks on wrapping transfers.
This was failing the check before, because the end block was lower than the start block due to the wrapping.
Check Star Wars Battlefront 2, not sure it will affect much else.
Fixes #8021

GS-CLUT: Handle invalidation on wrapping writes

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSState.cpp

Adds the preloading check to local moves, which may get done before the hw renderer picks them up.
Missed them in my previous PR, which was relied upon by Siren 2 when using preload frame.
Test Siren 2, not sure what else benefits.
Siren 2:
Before:
After:

GS-HW: Queue preloads from Local->Local moves on CPU also

---

pcsx2/GS/GSState.cpp

Fixes OOB array access in Xenosaga I's cutscenes. m_index.tail is zero, therefore the loop afterwards will access `index[-1]`, and crash if whatever happened to be before the buffer was larger than the vertex buffer array.
This snippet was pretty slow before, and since it's executed for every primitive, I went ahead and vectorized it.
Looks like a ~2% performance boost in the xenosaga cutscene dump
UB is bad.
~~Tested myself, but if you want, run xenosaga through its first cutscene. But the crash isn't reliable to produce on master.~~
Test games which relied on CLUT auto flush.

GS: Don't do CLUT auto flush test on invalid PRIM

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

Adjusts the clear behaviour when the draw actually happens to not suck so much.  The loading screen is still broken, but this fixes all the menus etc.
Also Extends the clears to handle one which is alpha blended , which gets used for shadows in games such as Brave, Narc, State of Emergency 2.
It sucked so much, didn't handle a whole load of cases.
Test games that do double half clear, like Burnout, Superman, Haunting Ground, maybe? idk, not sure what other ones do FBW=1
Do note this is basically hacks and heuristics to get around how the game reacts with the hardware texture cache, which does not handle this properly and fundamentally can't because of how the hardware renderer works.  Hopefully it's safe enough however.
Fixes #3180 best we can until a drastic change is made to the HW …

GS-HW: Improve FBW=1 clear for Singstar, NARC, Brave, State of Emergency 2 games

---

pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/Settings/GameSummaryWidget.ui

Playable rating was missing which is the most common rating for PCSX2. There are some other issues like the images look bad for star rating and some other stuff. Also resize the compatibility table width a bit.
Per-game properties
- Before:
- After:
Makes PCSX2 more consistent and correct.
Just scanning gamelist should be enough or you can check the per-game properties as well.

Qt: Fix compatibility string

---

bin/resources/GameIndex.yaml

GameDB: Add basic mipmap to Narc and Tom & Jerry War of the Whiskers.
Fixes textures.
Fixes textures.
Test the dumps from #3180

GameDB: Add basic mipmap to Narc and Tom & Jerry War of the Whiskers.

---

pcsx2-qt/MainWindow.cpp
pcsx2/VMManager.cpp

Fixes a crash on shutdown on Macs, the Metal renderer tries to clear the layer on a window which has been destroyed already.
Also fixes crash when shutting down while paused in the interpreter.
Crash bad.
Make sure confirm shutdown is enabled, disable recompiler, start game (or load state), exit pcsx2 by closing the window, confirm exit. should no crashie

Qt: Defer application quit on window close

---

pcsx2/PAD/Host/KeyStatus.cpp

Whoops.
Having all button pressure go to 1 when you release the pressure modifier is not ideal.
Enable input OSD, press and release pressure modifier. No buttons should be pressed. Confirm modifier still works by pressing with any face button.

PAD: Fix pressure getting set to 1 after modifier

---

pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp

Adds a `-debugger` command line option for the Boot and Debug functionality.
It's nice to have :)
Start games with the `-debugger` option, the debugger should open and execution should pause on the entry point.

Add command line boot and debug option

---

pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

Switches DX11 to a larger streaming buffer, adds missing texture copy counter for colclip.
Less code? Potentially a tiny bit more performance on bad drivers.
Test all renderers, make sure they're not obviously broken.

GS/HW: Simplify m_vertex/m_index

---

bin/resources/GameIndex.yaml

Update K-1 Grand Prix games to use Instant DMA instead of disabling Instant VU1 and MTVU.
This seems to be more reliable in correcting the issue, and for some reason the old way is no longer working properly.
As a bonus it'll run slightly faster too thanks to MTVU.
Check the games modified don't flicker.

GameDB: Update K-1 Grand Prix fixes to use Instant DMA instead.

---

bin/resources/GameIndex.yaml

This PR aim to fix ghosting effects on the Toy Story 3 and WALL-E game. it is an upscaling issue and the more you increase the multiplier, the more apparent the issue were, GS Dump are also provided. This also applies the fixes to other region of the game as well as adjusting the name for the NTSC-U region to match other region name for consistency.
WALL-E suffers from ghosting effects In-Game, here is comparison:
Before:
After:
GS Dump for WALL-E:
[Wall-E_SLUS-21736_20230204162204.zip](https://github.com/PCSX2/pcsx2/files/10608306/Wall-E_SLUS-21736_20230204162204.zip)
Toy Story 3 also seems to suffer from the same problem although to a lesser extent, another comparison:
Before:
After:
GS Dump for Toy Story 3:
[Toy Story 3_SLUS-21931_20230204162024.zip](https://github.com/PCSX2/pcsx2/files …

GameDB: Fixes for "Toy Story 3" & "WALL-E"

---

bin/resources/GameIndex.yaml

Adds Instant DMA hack to Scandal to fix graphical problems.
Potentially some cache shenanigans going on meaning DMA's get corrupted, this gets around it.
Run Scandal, make sure everything is displayed as it should be.
Fixes #8053

GameDB: Add Game Fix for Scandal

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/USB/usb-msd/usb-msd.cpp

USB: Fix Variable is assigned a value that is never used warning.
GS-tc: Cleanup hw texturecache. Initializations, constants, casts.
Initializations, constants, casts.
Cleanup code, warnings.
Hw renderers work.

Misc: Cleanup some warnings and gs hw tc.

---

bin/resources/GameIndex.yaml

Disables InstantVU1 to fix missing letters in text such as the letter E also adds more fixes and missing fixes for Forever Kingdom / Evergrace 2.
Missing l tt rs ar bad,

GameDB: Add Disable InstantVU to MGS 3 Subsistence

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Stops merge sprite activating in native.
Native doesn't need upscaling hacks.
Test a game with merge sprite in the gamedb.
Fixes #8063

GS-HW: Don't enable merge sprite in native resolution

---

pcsx2/USB/usb-lightgun/guncon2.cpp

Fix wrong code of GunCon2.
- 240 is used for the default screen height elsewhere in the file.
- BID_SHOOT_OFFSCREEN is already handled at line 295.
Test shoot offscreen button.

USB/LightGun/GunCon2: Fix wrong code of GunCon2

---

pcsx2-gsrunner/Main.cpp
pcsx2-gsrunner/test_run_dumps.py
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GSDumpReplayer.cpp
pcsx2/GSDumpReplayer.h

Reduced console spam to stop the console lagging out the system, plus made it so only the last loop actually saved any pictures.  Also added the ability to use hardware hacks by using the `-renderhacks` parameter followed by the following
af = AutoFlush
cpufb = CPU Framebuffer Conversion
dds = Disable Depth Support
dpi = Disable Partial Invalidation
dsf = Disable Safe Features
tinrt = Texture in Render Target
You can string them together like `afcpufbddsdpidsftinrt` and it will split them out.
Console spam was annoying, normal config doesn't load so it's nice to be able to set these manually for testing.
Already tested and working fine.

GSDumpRunner: Small tweaks for speed + ability to do manual hardware fixes

---

bin/resources/GameIndex.yaml

Stops the hash cache from being silly and exploding.
Stupid game using 600MB of VRAM is stupid.

GameDB: Add Paltex to Gacharoku

---

pcsx2-qt/MainWindow.cpp

Currently, it'll open whereever the separate window was last positioned, or some default OS-specified location, which is a bit confusing in multiple monitor setups.
So, prefer the monitor where the main PCSX2 window is.
Sorry wayland users, your protocol or compositors are fundamentally broken and every compositor I've tried blatantly ignores window positioning requests.
Having PCSX2's fullscreen window open on a different display isn't ideal.
Closes #8055.
Test fullscreen with PCSX2 on different monitors.

Qt: Open fullscreen window on same display as main

---

bin/resources/GameIndex.yaml

Added missing `"` (quatation mark) for `memcardFilters:`.
- Armored Core Last Raven is only the game missing `"`.
It could solve something but I'm not sure.
- My saves of Armored Core Nexus are already importable before this change...
Make sure if some saves can be imported to Armored Core Last Raven.

GameDB: Add missing quatation marks in memcardFilters

---

pcsx2/CDVD/Darwin/DriveUtility.cpp
pcsx2/CDVD/Darwin/IOCtlSrc.cpp
pcsx2/CDVD/Linux/DriveUtility.cpp
pcsx2/CMakeLists.txt

Add physical disc support for macOS, moved FreeBSD null code to macOS code and removed conditional compilation from Linux code.
For macOS physical disc support.
Test if PCSX2 still builds on FreeBSD.
Test if CDVD module still works on FreeBSD.
Test if physical CDs and DVDs could be played on macOS.

CDVD: macOS physical disc support

---

pcsx2-qt/SettingWidgetBinder.h
pcsx2-qt/Settings/ControllerBindingWidgets.cpp
pcsx2-qt/Settings/ControllerBindingWidgets.h
pcsx2-qt/Settings/ControllerSettingWidgetBinder.h
pcsx2-qt/Settings/InputBindingDialog.cpp
pcsx2-qt/Settings/InputBindingDialog.h
pcsx2-qt/Settings/InputBindingDialog.ui
pcsx2/Frontend/InputManager.cpp
pcsx2/PAD/Host/KeyStatus.cpp
pcsx2/PAD/Host/KeyStatus.h
pcsx2/PAD/Host/PAD.cpp
pcsx2/PAD/Host/PAD.h

Thought of a way to make this which doesn't look disgusting UI-wise. To set per-bind sensitivity/deadzone, shift-click the binding (same as making multiple bindings).
Also adds multiplier parsing to controller settings, so e.g. sensitivity will be shown as 130% instead of 1.3 (better UX).
Something which has been asked for on numerous occasions, but I couldn't think of a way to present it in the UI which wasn't gross. And the multiplier thing has been on my todo list for a while.
Closes #6629.
Closes #4055.
Closes #8029.
Test per-bind sensitivity/deadzone.
Test trigger sensitivity/deadzone.
Test stick sensitivity/deadzone,  make sure I didn't break it.

Qt: Add trigger and per-bind deadzone/sensitivity settings

---

bin/resources/GameIndex.yaml

Added following lines to all the 12 titles of Armored Core Nexus.
``` yaml
roundModes:
eeRoundMode: 0 #Fixes Z-Fighting.
```
This change solves texture-flickering on Armored Core Nexus.
Go a mission that has texture-flickering.
- In most missions, looking down causes flicker.
- For disc 1, the cutscene of "Eliminate Crest AC" is the most clearly example.
I only tested `SLPS-25338` and `SLPS-25339` (NTSC-J), so it's needed to test following games as well:
```
SCAJ-20076 SCAJ-20077 | NTSC-Unk
SLES-82036 SLES-82037 |  PAL-M5
SLKA-25201 SLKA-25202 | NTSC-K
SLPS-73202 SLPS-73203 | NTSC-J (PS2 the best)
SLUS-20976 SLUS-21079 | NTSC-U
```

GameDB: Fix texture-flickering of Armored Core Nexus

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp

Causes off-by-one rasterization differences with lines.
Fixes xenosaga shadows gs dump.
It was clearly wrong before.

GS/DX11: Disable multisampling in rasterizer state

---

common/Vulkan/Builders.cpp
common/Vulkan/Builders.h
common/Vulkan/Context.cpp
common/Vulkan/Context.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Xenosaga III uses lines to clear out the edges of its shadow map, as seen here:
With standard rasterization rules (rectangle for strictLines=true, i.e. nvidia, or parallelograms if strictLines=false, i.e. AMD/Intel), this meant the bottom-right pixel didn't get filled in, as seen above.
If we switch to Bresenham rules, it does get filled in as expected.
Before:
After:
What a run rollercoaster this was to debug.
Test xenosaga_shadow GS dump on each GPU vendor. Extension support looks pretty decent.

GS/Vulkan: Use Bresenham line rasterization when supported

---

pcsx2/MemoryCardFolder.cpp

Prevents crashing in YAML code by trying to delete a node entry which doesn't exist.
This was causing Ecco the Dolphin to crash during saving. This is really a symptom of a bigger problem with folder memcards but it seems to recover well enough to at least save, from what I can tell.  It beats CTDing anyway.
Load Ecco the Dolphin with a folder memory card (don't forget to make a player), kill yourself and let the continue timer run out, it should save and continue, instead of crashing.

Mcd-Folder: Prevent crash trying to delete non-existent node.

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSVertexSW.h

DirectX and OpenGL no longer have different draw splitting.
Also swaps out the size_t fields in GSState for u32s, packs a bit more in the cache line, and ever-so-slightly smaller code size (likely no observable perf difference).
Consistency.
Test a couple of auto flush games. I've done a GS runner pass and it's all good.

GS: Handle index swap case for auto flush

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Silly game does a post effect using triangles and invalid/fixed tex0.
I can make this more efficient in the future, but for now this just fixes the regression.
Regression from #8015.
Test TS2. I've done a runner pass and nothing else seems affected.

GS/HW: Fix fixed/invalid TEX0 case in TimeSplitters 2

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Mainly in DX11 when the staging buffer was used.
Crash bad.
You'd need a game with an odd framebuffer size and to use DX11. Or can just yolo since it's an obvious change.

GS/HW: Fix crash with AVX2 due to unaligned pitch

---

pcsx2/GS/Renderers/OpenGL/GLLoader.cpp
pcsx2/GS/Renderers/OpenGL/GLLoader.h
pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp

.. to disable the use of PBOs when reading back. Apparently they might be slower on some older drivers according to #8074?
On my A750 with the Windows driver, I get 52fps in the Gradius GS dump with PBOs, and 35fps without. Mesa is about the same for both.
Older systems I guess
Test Gradius dump with `DisableGLDownloadPBO` option under `EmuCore/GS` set to `true` and `false`, observe performance. You'll need to manually make it, it's a hidden option.

GL/OpenGL: Add a hidden [EmuCore/GS] DisableGLDownloadPBO option

---

bin/resources/GameIndex.yaml

GameDB: Add full mipmap and trilinear ps2 to Hard Hitter games.
Improves ground texture rendering.
Improves #5250
Test the dump in the linked issue.

GameDB: Add full mipmap and trilinear ps2 to Hard Hitter games.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Fixes a problem I created where there's no texture (m_src) but it tries to read it and crashes SIlent Hill Origins, when it's been optimised out.
Crashing is bad, not crashing is much better.
Start a new game in Silent Hill - Origins

GS: Fix TME processing when Alpha->IsBlack & !TEX0->TCC

---

README.md

Change 'wxwidgets' to 'wxWidgets' and specify that Visual C++ is needed on Windows instead of just stating that it's needed to run PCSX2.
wxWidgets (with a capital second 'w') is the proper stylization. Appending "on Windows" to the line about Visual C++ ensures that a Mac user or a less tech-savvy Linux user naively following the documentation to the letter doesn't go out looking for a software package that doesn't exist on their platform.

Readme: Two minor changes to the README

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Tightens CLUT draw detection slightly.
Klonoa 2 was detecting the top left corner being drawn (possibly post/shuffle effect?) causing glitching, which became apparent in #8101 The rest of the games on my CLUT list seem to be fine still.
Already checked my list from #7267, Ace Combat 5 sun occlusion is busted again, but not because of this PR.

GS-HW: Tighten CLUT detection slightly.

---

pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp

Regression from yesterday.
Crash bad.
Can be difficult to trigger the crash, but if you look at the code, the transfer uses the 64 byte pitch, but the allocation previously didn't.

GS/OGL: Fix possible crash downloading odd texture sizes

---

common/GL/Context.cpp

Changed "Created a Open ES/OpenGL context" to "Created an Open ES/OpenGL context".
Minor grammar mistake.
Say it out loud and see which one sounds better.

Context.cpp: fix minor typo

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Xenosaga I does a move from BP 1C00 to E00, then from E00 to 2A00 a few frames later for its cutscene transitions. 2A00 then gets used as a texture and blended on top of the later frames. Because there's no target at 2A00, the move falls back to the CPU, and E00 contains junk which gets moved and eventually preloaded instead.
Gradius V uses moves for a screen move/wobble-like effect, by moving chunks of the framebuffer out, then using those as a texture. It's not broken at the moment, but it does readback (slow), and break upscaling.
Fixes #6625.
Improves #8074.
Fixes #5299.
Test Xenosaga and Gradius.
Test Bleach Blade Battlers 2nd (don't disable depth).

GS/HW: Carefully allow move to create new targets

---

bin/resources/GameIndex.yaml

Ports patch to fix broken collisions to PAL Disney's Cars
SPS is bad and gross.
Make sure the SPS is fixed and the game functions correctly.

GameDB: Port COP2 patch for Disneys Cars

---

pcsx2/GS/GSCrc.cpp
pcsx2/GS/GSCrc.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Seems with the HLE clear changes we don't need this any more, yay!
It does do a local memory -> depth buffer copy which wasn't the case before (due to the hack), **but** only in the main menu, where you're not going to be GPU bottlenecked in the first place.
These hardcoded per-game messes in the TC trigger me so much.
Test FFX-2 in menu and ingame, make sure nothing's broken.

GS/HW: Purge FFX-2 depth clear CRC hack

---

common/D3D12/Context.cpp
common/D3D12/Context.h
common/Vulkan/Context.cpp
common/Vulkan/Context.h
pcsx2-gsrunner/Main.cpp
pcsx2-qt/QtHost.cpp
pcsx2/Frontend/D3D11HostDisplay.cpp
pcsx2/Frontend/D3D11HostDisplay.h
pcsx2/Frontend/D3D12HostDisplay.cpp
pcsx2/Frontend/D3D12HostDisplay.h
pcsx2/Frontend/ImGuiManager.cpp
pcsx2/Frontend/ImGuiManager.h
pcsx2/Frontend/MetalHostDisplay.h
pcsx2/Frontend/MetalHostDisplay.mm
pcsx2/Frontend/OpenGLHostDisplay.cpp
pcsx2/Frontend/OpenGLHostDisplay.h
pcsx2/Frontend/VulkanHostDisplay.cpp
pcsx2/Frontend/VulkanHostDisplay.h
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSRenderer.h
pcsx2/HostDisplay.h
tests/ctest/core/StubHost.cpp

Currently, if `vkQueueSubmit()` or `vkWaitForFences()` fails, e.g. due to an invalid GPU command or driver bug, PCSX2 just panics/crashes. This isn't ideal.
Since we have most of the needed data stored in local memory, we can attempt to recover by tossing away all data on the GPU, and starting fresh. You'll probably get broken rendering for a frame or longer, but it's better than crashing, and might give you enough time to get to a save point. I wouldn't recommend making a save state after a GPU crash though :-).
For the case where a single object keeps crashing the GPU, it's limited to one reset per 15 seconds. That way we don't keep endlessly resetting the GPU and potentially hanging the user's PC.
Making PCSX2 more reliable.
I don't know of any way to crash the renderers currently, but …

GS: Attempt to recreate device if GPU crashes

---

bin/resources/GameIndex.yaml

Changes HPO to HPO Special to fix rainbow garbage on the top and left side of the screen when moving.
Rainbow garbage bad.

GameDB: Update HPO on Spider Man 2

---

bin/resources/GameIndex.yaml
pcsx2/GS/GS.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Rewrite the PCRTC code to make more sense and not look quite so gross.
Was gross, had flaws, needed fixing.
I guess check offsets on the screen n stuff, and games which make use of the positioning such as DmC and WipEout Fusion.

GS: Rework of PCRTC code

---

bin/resources/GameIndex.yaml

GameDB: Replace DMABusyHack with InstantDMAHack for MGS2 Sons of Liberty.
DMA timing problem.
Fixes broken half-bottom artifacts.
GameDB: Add missing Need for Speed - Carbon entry.
Fixes #8109
ci passes, game is fixed.

GameDB: Replace DMABusyHack with InstantDMAHack for MGS2 Sons of Liberty and add missing db entry for NFS Carbon

---

pcsx2/Frontend/InputManager.cpp
pcsx2/GS/GSLocalMemory.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSVertexTrace.cpp
pcsx2/GS/Renderers/Common/GSVertexTrace.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Cleanup of GSState, making sure everything is initialized.
Also get rid of RemovePartial(), it's never called.
Everything should be reset when we, well, reset, or load state.
PCSX2 should be deterministic :P
Make sure load state works. Check games sensitive to target preloading.

GS: Make resets more deterministic

---

pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Null/GSDeviceNull.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

Uses linear sampling for final display output when using screen offsets.
In normal mode, Point looks clearer and better as we output the size the framebuffer renders, but in screen offsets mode, it will stretch/resize the picture, causing it to look gross due to the nearest neighbour sampling, so this will make it look a bit blurry in some cases (like DMC) when using Screen Offsets, but you can't have it both ways without us making it larger first, then sampling it down, but that's extra work for the GPU, but that's a debate for another day.
Test Ratchet & Clank in native with and without screen offsets, make sure it doesn't look gross like master.

GS: Use linear interpolation for Screen Offsets

---

pcsx2/GS/GSState.h

limits the height of the framebuffer read to the size of the display, to stop the Texture Cache freaking out.
This was a regression from the PCRTC rewrite which broken Silent Hill 2 videos. I forgot that game sent double height rubbish.
Test Silent Hill 2 (already done)

GS: Limit the height of framebuffer reads

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/Common/GSDirtyRect.cpp
pcsx2/GS/Renderers/Common/GSDirtyRect.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

~~NOTE: I still need to give this a GS runner pass, haven't hit any cases that do offset updates yet to verify that this part still works.~~
The tex-in-rt invalidation was using the incoming (usually an EE write) PSM/BW, but dirtying a rectangle in the target's coordinate space. This lead to a bunch of large dirty rects with a BW of 1 in VP2, which caused corruption during the battle fade transition.
Fewer texture uploads makes Intel GPUs happy.
Fixes swirl battle transition in Valkyrie Profile 2.
Fixes top-left screen rendering in Lego Racers 2.
Fixes track in GH3 (crowds are still broken).
Need to confirm if it `fixes` #4349.
Fixes #4816.
Test games which use RT updates.

GS/TextureCache: Allow tex-in-rt for 16/24/32-bit targets

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

Xenosaga does its moves for the fade transition between scenes, but since it's all handled in hw now, when there's a loading screen longer than 400 frames/6.6 seconds, it removes the target, which means junk from local memory gets loaded.
This PR changes the TC aging so that it only increments when there were actually draws/transfers in the frame. In other words, during Xenosaga's black loading screens, it won't age the targets, and the fade transition should be correct.
Fixes #6625.
Fixes flicker in loading screen fade in WWE SmackDown Here Comes the Pain.
Partially fixes menu background in King's Field.
Test Xenosaga loading screen transitions, not just cutscene transitions.

GS/HW: Don't age texture cache on idle frames

---

pcsx2/GS/GSState.h

Fixes undefined behaviour thing where `display` is -1, which isn't a valid array index.
I was coding at 6am.
Already tested, obvious fix.

GS: Fix undefined behaviour bug in PCRTC

---

pcsx2/Counters.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Same as #5922, except rebased, and with the issue which caused garbage post-processing in Black hopefully fixed.
Quoting refraction:
> Previously we were basically presenting the previous frame at the beginning of the next vsync start as a result of how things were working previously, we had to, however this will move it to VSync end, so the framebuffer pointers will have changed to the "just rendered" frame, which in theory should potentially reduce input lag by 1 frame.
> I can't remember what 2D fighting game used to have a problem with it this way around, but it's worth testing any you have.
Aside from that, test games for input lag (probably better on Qt) and make sure you don't get any black frame flashing that wasn't there previously.
Check Black (both PAL and NTSC).

Counters: Present at VSync End (round 2)

---

pcsx2/CDVD/Darwin/IOCtlSrc.cpp

CDVD: Fix FreeBSD compile.
No physical disc support on FreeBSD, DKIOCDVDSETSPEED DKIOCCDSETSPEED are apple only.
Regression from #7603
FreeBSD compiles, ci passes.

CDVD: Fix FreeBSD compile.

---

bin/resources/GameIndex.yaml

Adds Tex in RT to fix underwater rendering being totally broken.
Having broken water is a very _vexing_ issue
Helps #6288 

GameDB: Vexx underwater rendering fixes

---

bin/resources/GameIndex.yaml

No longer needed as the hash cache no longer does an explosion.
Enjoy the 142 less texture uploads and a free 5 fps on the side.

GameDB: Remove fix from Soulcalibur 3

---

bin/resources/GameIndex.yaml

Change Normal Vertex halfpixel with roundsprite.
- Before:
- After:
Less brokey with upscaley
Test SLPM-66675

GameDB: Fix Japanese KH2 - Final Mix

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Forces preloads to work regardless of the GUI option, but only if an EE upload matches perfectly (or m_force_preload is enabled), the GUI option now forces preloads on everything.
Before it was only preloading during the force period or if the option was enabled, but some games require this to work correctly, such as Astro with its jet packs.
Test games, make sure nothing is busted.
Fixes #6565
Astro
Master:
PR:
Other minor changes:
Juiced (lights on back of car)
Master:
PR:
Kunoichi (not a fix as shadows are still missing, but makes it look less annoying):
Master:
PR:
Sakura Taisen/Wars (idk which one) (as above, not a fix as shadows are still missing, but makes it look less annoying):
Master:
PR:

GS: Preload whenever it matches an upload. GUI option forces preloads.

---

pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Tries to optimise access to a target during local memory invalidation to reduce the number of readbacks in some games. This significantly increases performance in some cases.
We were pretty much always downloading a texture even when it wasn't drawn to since the local memory was last invalidated, but also some games were downloading to the EE in tiny chunks and it's more performant to just download the whole thing, so now we check for more than one read between draws.
Test games that normally have a high RB number.
SOCOM 2:
Master (~37fps):
PR (~180fps):
Gundam Battle Assault 3:
Master (~44fps):
PR (~200fps): (it was going so quick I couldn't even get the same screenshot lol)
Red Faction II:
Master (~350fps):
PR (~820fps):
Armored Core 3:
Master (~47fps):
PR (~117fps):

GS-HW: Optimise readback performance for some cases

---

bin/resources/GameIndex.yaml

Fixes random graphical corruption that can happen by adding EE Timing hack.
Spikey bois are spooky.

GameDB: Fix V-Rally 3 graphical corruption

---

pcsx2/IopBios.cpp
pcsx2/IopBios.h
pcsx2/VMManager.cpp

Host root doesn't get cleared if you boot an ELF, then an ISO, it will use the ELF's host root.
While it's not really escaping the path confinement, it's also not the expected behaviour - booting an iso should not have access to hostfs.
Probably a bit difficult to test since afaik no retail games will poke hostfs, if you have ulaunchelf on an ISO I guess you could.
Make sure elfs still have access to hostfs (should be unaffected).

VMManager: Clear host root on booting ISO

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

NFSU2 does consecutive channel shuffles with blending, reducing the alpha channel over time.
Fortunately, it seems to change the FBMSK along the way, so this check alone is sufficient.
We were only looking at the PSM/page/sprite before, which meant we skipped everything after the first shuffle...
Before:
After:
Fixes #7549
Fixes #2279
Test NFSU2.

GS/HW: Split up consecutive channel shuffles

---

bin/resources/GameIndex.yaml

Se De-interlace to Adaptive TFF. I thought this was fixed but needs to be checked later.
- Automatic de-interlacing check 18 seconds to 30 seconds:
https://user-images.githubusercontent.com/24227051/219121522-9dd6cb5c-db03-4fc4-927d-92f60b854c74.mp4
- Vs now:
https://user-images.githubusercontent.com/24227051/219121888-1e34865d-607c-4beb-bf9d-c9f3ff9f89d9.mp4
Less shaking.
Test Bakugan.

GameDB: Bakugan Battle Brawlers

---

pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp

Make sure anti-blur works for the framebuffers and screen offsets also.
Did some const'ing because I don't wanna get nagged by LightningTerror :P
It was omitted from the rewrite and showed up in games like Tenshu 4.
Test things, make sure nothing looks broken.

GS-PCRTC: Fix up some PCRTC anti-blur behaviour + code cleanup

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fixes a couple of bugs I found during moving the target lookup before source.
Fixes #7310.
Test VP2 I guess.

GS/HW: Fix repeating edges in shader sampled mode/incorrect target heights

---

bin/resources/GameIndex.yaml

Fixes the awful flickering and missing textures that happens all over the game.
Awful game needs silly hacks to function correctly because the devs snorted epoxy.

GameDB: Add VU Sync hack to Salt Lake 2002

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

GT4 sets region clamp to 0..127, 0..255 on a 64x128 texture. Shader sampling is redundant here, and no trilinear means it looks shit.
Fixes some mipmapping issues in GT4.
Test GT4?

GS/HW: Allow hardware sampling when clamp_max is larger

---

bin/resources/GameIndex.yaml

GameDB: Add full mipmap with ps2 trilinear to Matrix, The - Path of Neo.
Improves ground textures to match sw renderer.
GameDB: Add missing db entry for Silent Scope 3.
Korean version.
Better rendering, missing entries.

GameDB: Add full mipmap + trilinear to matrix, add Silent Scope 3 db entry.

---

pcsx2/Counters.cpp

Rearrange pad/core updates in vsync to avoid some weird pad input lag/missed inputs issue.
Apparently this gets around some weird input lag issue.
Was introduced in #8101 as an issue, did some tests on discord with the user reporting it (along with a trap test to make sure they weren't lying) and checks out, this apparently fixes it, so there we go..
Kinda already been tested.

Pad/Counters: Rearrange Pad/Core updates on VSync

---

bin/resources/GameIndex.yaml

Add bug fix to prevent divide-by-zero behaviors when SubDither3 is active during the final battle or other battles with onscreen effects related to SubDither3
```
sceVu0ApplyMatrix(&vtw,(Vector4 *)&slm,&vt);
// vtw.w will be zero... Oops!
sceVu0ScaleVector(1.0 / vtw.w,&vtw,&vtw);
```
Thanks to Tellow and Cheesey for their inputs into this fix
Division by zero is bad. It hangs.
It's been tested to prevent the hang already.

GameDB: Add pnach fix to Fatal Frame 1 / Project Zero

---

pcsx2-qt/MainWindow.cpp

Window geometry wasn't being saved if there was no VM running.
Diff might look odd, but closeEvent() gets called twice, once when you close it while the VM is running, and again when the application is quitting, so we save then.
Closes #8168.
Make sure window geometry saves on shutdown.

Qt: Fix window geometry not saving on exit

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Flushes the targets from the hardware texture cache back to memory when swapping renderer, reopening the GS.
This was a problem in games where things were only ever rendered on the GPU, then you changed config or changed to the software renderer, it would lose that information, resulting in graphical errors.
Make sure Futurama lets you load ingame with Hardware mode, switch to software and back again without any texture corruptions.
Fixes #6918 probably

GS: Flush targets back to GS memory when swapping renderers

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Some callers were using blocks, others were using pages before.
Enables target expansion in Stuntman, which slightly improves rendering without CPU sprite. The full "fix" needs page handling in P8 conversion.
Consistency mainly.
GS runner says it's okay.

GS/HW: Use block instead of page pointer for height lookup

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Preserve the width of textures used as the frame output.
The texture cache was changing the size of the textures for some draw, and then the frame was after a different size, causing the picture to desync and get messy.
Test Nicktoons Unite, maybe a spatter of random games. Already done a GS Dump run on 1000+ dumps.
Fixes the intro FMV's in Nicktoons Unite.
Master;
PR:

GS-HW: Preserve width of frame textures

---

bin/resources/GameIndex.yaml

Fixes for Transformers Revenge of the Fallen misaligned bloom and soft shadows and Legend of Kay broken shadow rectangles and misaligned bloom.
Master:
PR:
Master:
PR:
Big black rectangles missing from your grass shouldn't be a key selling feature of a video game.

GameDB: Various fixes

---

bin/resources/GameIndex.yaml

Ports a patch over to the PAL version to fix the pause menu hud and other parts.
Broken hud and other bits of the game are kinda stinky.

GameDB: Port patch to PAL Transformers ROTF

---

bin/resources/GameIndex.yaml

Something changed and now this just causes rainbow vomit in game and in menus instead of fixing the issue it was originally put in for.
Release me from this mortal coil.

GameDB: Remove CPU CLUT from Transformers The Game

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Kinda defeats the point of the optimization when it does.
Runner's done the heavy lifting. Should be fine I hope.

GS/HW: Don't allow region textures to make sources larger

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fix up local memory invalidation (readbacks) to work correctly for Fatal Frame, Armored Core 3 and Shadows Hearts2.
Limit the resizing of the framebuffer to 2x the resolution when the draw is a memory clear.
This is partly a regression fix PR but also improving upon previous changes.
The first problem, it was just wrong and buggy, part of the problem for fatal frame was that it does vertical stripes and reads horizontally, instead of from the top down, but there was also some issues when the block pointer it requested was below the current texture start (this was part of the problem with Armored Core 3)
The other part of the fix is to stop massive targets being created when it does a huge memclear, this was resizing targets so some of them were taking up 90% of the GS memory! causing …

GS-HW: Fix Download readbacks and limit FB resizing

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

The current invalidation code sucks, but at least this stops things which are blatently wrong from happening.
TC:NYC will have some slight glitches after this PR, I'll fix that in a follow-up.
Fixes rainbow vomit in COD2, haunting ground mirror, glitched textures in rally fustion, maybe others..
Fixes #5431.

GS/HW: Don't try to dirty targets which don't overlap

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GSLocalMemory.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSRenderer.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp

Unfortunately it's too risky to enable by default all the time. So, we'll make it a hw fix, and hopefully one day can make it default on.
Also makes save states readback the TC as well.
Also fixes Burnout 3's sky getting corrupted when the option is on.
Fixing Burnout's sky, probably other random corruption.
Test Burnout and save states and/or renderer switches.
Test a few games which need readbacks to make sure they still work.

GS/HW: Make readback-on-close a HW fix

---

pcsx2/MemoryCardFolder.cpp

Stops the OSD spam when saving a game to a memcard folder
Every write triggered an OSD message, and there could be hundreds, this stops it happening more than once every 5 seconds.
Save your game with a folder memcard inserted, maybe with the console window open so you can see the green messages.

MCD: Stop Memcard Folders spamming the console/OSD when saving a game

---

pcsx2/GS/GSUtil.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Correct the check for CPU CLUT draw checks if there has been writes from the EE, make sure all of the texture is invalid before skipping the local memory invalidation.
Also fix up readback behaviour for Local->Host transfers
The invalidation thing was wrong, so this is more correct, fixes games where we use CPU CLUT to fix post processing.
Readbacks just needed some more work, but also some games  like Ratchet Gladiator would upload a texture, then immediately download it, but if there was still an old target hanging around the download would pick that, so I now detect that.  I also handled the wrap around 2048 correctly.
Check Brave, Futurama, Dave Mirra's Freestyle BMX 2 with SW switches. For the CLUT thing check LEGO Star Wars. For readbacks, check Ratchet Gladiator, Fatal Frame, GT4 …

GS-HW: Drop to CPU CLUT w/e invalidate only if dirty covers whole tex

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

GS-hw: Use rgb color for second output instead of alpha.
We want different alpha value for each channel.
GS-ogl: Check each channel individually if it overflows and do corrections.
We want to check and adjust alpha value based on each channel instead of taking the minimum overflow.
It is more accurate this way, it should've been done earlier but I didn't have a test case.
Better accuracy using mix of hw/sw blending, allows us better accuracy at lower levels of blending, also useful for dx11 since it doesn't fully support sw blending.
Follow up from #6784
Test the games and dumps mentioned/listed in #6784
Fixes Cat in the Hat's fire effect using lower level of blending.
Need to test metal as well.
Test a bunch of games/dumps, especially dx as it will be more likely to show up there.

GS-hw: Adjust alpha compensation for blend mix1

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Apparently this was never updated to RGBA16.
Debug layer errors, possible corruption/GPU crash?
Test a game which uses colclip blend (e.g. Sly).

GS/DX12: Fix incorrect pipeline RT format

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/Renderers/Common/GSTexture.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/OpenGL/GLState.cpp
pcsx2/GS/Renderers/OpenGL/GLState.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/OpenGL/GSTextureOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp

Eventually hopefully we can make this the default, but it breaks too much at the moment.
Fixes missing/corrupted textures in True Crime: New York City.
Gets rid of an unnecessary readback in True Crime: New York City.
Stops some offscreen targets from expanding in size.
Test TC:NYC.

GS: Partial target invalidation option, Z eliding

---

bin/resources/GameIndex.yaml

Adds mipmapping full and trilinear PS2 to 007 Everything Or Nothing to fix up texture detail and removes mipmapping from Fifa games to prevent players from going bald or having rainbow vomit shirts.
Male pattern baldness is not good.

GameDB: 007 EON Fixes

---

bin/resources/GameIndex.yaml

Adds Texture in RT to Growlanser 5 and 6 to fix a layering issue and to Poinies Poin to fix text corruption after an FMV.
Fixes #8245 
Fixes #6797 
Issues are bad for you.

GameDB: Gorwlanser 5&6 and Poinies Poin Fixes

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Normally we would use 1024 here to match the clear above, but The Godfather does a 1023x1023 draw instead (very close to 1024x1024, but apparently the GS rounds down..). So, catch that case, we don't want to create that target, because the clear isn't black, it'll hang around and never get invalidated.
That 1024x1024 target gets read back with CPU CLUT enabled, blowing away the entirety of local memory, including texture data.
Test Godfather (booting from fresh, not a state). Open menu, should be fine.

GS/HW: Use 1023 for skip-target-creation threshold

---

bin/resources/GameIndex.yaml

- Timesplitters 2 (normal vertex screwing up bottom)
- Before:
- After:
- Timesplitters Future Perfect (remove depth lines)
- Before:
- After:
- Dragon Ball Z - Infinite World (dash)
Less tinkering

GameDB: Timesplitters Series + minor maintenance

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Sets the scale for the temp depth stencil for when upscaling is active.
This was a regression from #8242 which affected The Sims Bustin' Out when upscaled
Test the sims

GS-HW: Set scale on temporary depth stencil

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSUtil.cpp
pcsx2/GS/GSUtil.h
pcsx2/GS/Renderers/Common/GSDirtyRect.cpp
pcsx2/GS/Renderers/Common/GSDirtyRect.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Improves the local memory invalidation skipping, and target selection for invalidation, but also fixes some bugs with preloading memory in to target.
Also support per channel dirtying of target textures.
This wasn't quite right, there were edge cases and it was a bit fast and loose in some scenarios, this tries to be heuristically more accurate.
Some games also update just alpha channels on a 32bit colour, and previously we'd wipe out the RGB also and load it from local memory, this would of course load in garbage, so now it will attempt to only reload the necessary channels.
Overlap check also needed a fix as if the start and end pixel are within the same page, it's entirely possible due to the PS2 memory swizzling that the start block is higher than the end block, which will cause the …

GS-HW: Improve Local->Host and preload accuracy. Per channel dirtying targets.

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Setup routine assumed DS was never null.
Crash bad.
yolo

GS/DX12: Fix potential crash in PrimID DATE setup

---

pcsx2-qt/AutoUpdaterDialog.cpp

Both can be annoying if the update check takes a long time, and it takes focus away from the game or big picture UI.
Manual update checks will still display regardless of whether a game is running.
Closes #8196.
Bit difficult to test this, because the updater isn't enabled on PR builds. But I've done my best to simulate the scenarios, and the logic is simple enough to follow.

Qt: Don't display updater if running a game or fullscreen

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fixes the texture cache falling apart in 007: Everything or Nothing.
Stops PCSX2 crashing.
Closes #8260.
Test EoN.

GS/HW: Don't try to draw with invalid TEX0 configuration

---

bin/resources/GameIndex.yaml

Adds paltex to Dance Summit 2001 to massive increase FPS and reduce hash cache usage dramatically.
Master:
PR:
More brrr and less hash cache gooder betterer.

GameDB: Dance Summit 2001 Fixes

---

pcsx2-qt/MainWindow.cpp

Fixes lockup/crash when starting a file early.
Closes #8266.
@RedDevilus knows what to do.

Qt: Cancel game list refresh before GetSaveStateFileName()

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Could cause an out of bounds texture upload.
Closes #8280.
Test TC:NYC (again..).

GS/HW: Fix incorrect size of region mipmap levels

---

pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSRenderer.cpp

`src_out_rect` was never initialized, so equality only happened in debug builds, and it also wasn't testing the source rectangle (from the texture).
Gets rid of a redundant framebuffer blit at the end of a frame in games where the two merge inputs are identical, saving a bit of GPU time.
Doing a runner pass to be safe..

GS: Fix output equal check in Merge()

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp

Fixes depth inaccuracy in WWE SmackDown! Here Comes the Pain.
Mentioned in #3636.
Sadly depth is still kinda broken on Intel. Only happens with zclamp on, i.e. writing depth in the shader. Might be a driver bug.
Test DX12, but it's fairly obvious this was missing, and incorrect MaxDepth was being set in the shader as a result.

GS/DX12: Add missing clip_control support flag

---

bin/resources/GameIndex.yaml

Improvements made for Armored Core 2 Another Age, Armored Core 3 Silent Line, and Armored Core Last Raven
Made various changes in GameDB to a select few Armored Core games.
Removed Round Sprite from AC3SL and ACLR.
Added Half-Pixel Offset changes to AC2AA and ACLR.
Added Target Partial Invalidation to NTSC-U and PAL-E AC3SL.
Round Sprite breaks the in-game HUD elements for AC3SL and ACLR, while giving negligible to no improvements. Interestingly, Round Sprite does help AC3, which might be the reason it was added onto 3SL as well.
HPO fixes misaligned shadows and AC reflection textures in ACLR and AC2AA respectively, and fixes the double-image ghosting/blur in ACLR. 
Note that this does add 2px of garbage pixels in the top and left side of ACLR's garage, but the image clarity boost is …

GameDB: Various Armored Core Improvements

---

pcsx2/GS/GSLocalMemory.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Track target sources in all pages instead of just the first page it falls within.
Not really sure on the justification behind this, but I need source invalidation out of the origin page for fixing Destroy All Humans.
Enabling future TC functionality.
Test regular games.. runner says it's okay.

GS/HW: Track target sources in all pages

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

I think I stuffed this up when I added GPU CLUT, it got hidden instead.
Silly users following "youtube settings" then whinging that stuff is broken
yolo

Qt: Skipdraw shouldn't be visible in global settings

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

Games set TW/TH to 1024, and use UVs for smaller textures inside that.
Such textures usually contain junk in local memory, so try to make them smaller based on UVs.
Gets rid of the readbacks by relaxing the hw move checks a bit, I need to test this more thoroughly.
dey slow
Compare snowblind game performance, add whatever's missing in gamedb

GS/HW: Add a new option to try to make Snowblind games faster

---

bin/resources/GameIndex.yaml

Removes the texture preloading restriction as the game no longer violently blows up during gameplay with the hash cache enabled.
Adds XGKick gamefix for Zombie Hunters.
Brrrr,

GameDB: Remove unneeded Midnight Club 3 fixes

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Probably not going to be fatal since the texture wasn't sampled in the case I saw this, but a validation error nonetheless.
Validation layer errors are bad.
Runner says it's okay.

GS/Vulkan: Fix RT being left bound as texture

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

If the alpha channel of a C32 texture gets overwritten, instead of erasing the whole texture, make it a 24bit texture so it no longer uses alpha.
This was previously erasing it and destroying the RGB data along with it, which in Shadow Hearts later got reused, but instead of getting this data since it was gone, it got garbage from memory.  This is a heuristic so it *might* break something, but hopefully it's safe.
Test Shadow Hearts as per the issue below, test general games. GS Dump runner seemed to not affect anything.
Fixes #6959 Shadow Hearts Covenant broken fusion effect
Fixes #909 Primal black screen in HW mode.
Mobile Suit Gundam - One Year War also shows some improvement, but is still unfortunately unplayable in hardware.
Master:
PR:

GS-TC: On invalidate of the alpha of 32bit, drop back to 24bit

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp

And enable it for Justice League.
Can double the frame rate, at least in the GS dumps.
Test Justice League, make sure snowblind perf didn't regress.

GS/HW: Fix off by one in estimate texture region

---

common/Vulkan/Context.cpp
pcsx2-qt/MainWindow.cpp

Apparently some systems were returning `VK_INCOMPLETE` here... which meant that the GPU count changed inbetween the two calls?
Vulkan not working on some systems.
Test affected systems.

Context/Vulkan: Handle VK_INCOMPLETE return from vkEnumeratePhysicalDevices()

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/MainWindow.ui

This PR changes the behaviour of the toolbar's `Settings` button:
* When the game is not running, open Global Settings (same as it is now).
* When the game is running, open a small context menu that allows the user to open Global Settings or Game Properties.
It also removes `File -> Settings` for consistency with DuckStation, besides a whole Settings menu is right next to it.
More intuitive access to Game Properties, also signaling clearly what is what - currently it may be unclear whether clicking `Settings` changes global or per-game settings.
Make sure UI works as described.

Make Game Properties accessible from the toolbar

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/GSLocalMemory.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/GameDatabase.cpp
pcsx2/Pcsx2Config.cpp

This mode can construct a source from one or more targets currently on the GPU, taking into consideration differing page pitches.
Fixes shadows in Destroy All Humans. Can also be used for Guitar Hero, although that has a bunch of other clear/invalidation issues in play too.
Before:
After:
My rambling about DAH:
> so they render the shadow map, and to deal with world-space that fall outside the range, since the PS2 has no "clamp to border colour" option, they need a black rectangle around the shadow map
most games will just draw a 1px line in such cases
> but no, this bugger offsets the base pointer by -32 (effectively moving the texture towards the right, with the right most page moving down one row), then redraws it with slightly offset texture coordinates
> why they couldn't just offset …

GS/HW: Add "Merge Targets" texture-in-RT mode

---

bin/resources/GameIndex.yaml

Fixes for misaligned bloom and sun occlusion and intensity in Destroy All Humans 1 and 2.
Misaligned bloom is gross and the sun going through objects is silly.

GameDB: Destroy All Humans 1&2 Fixes

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

And slience a warning in TC.
PR merge order funsies..
Make sure skipdraw is gorn

Qt: Fix skipdraw not being hidden globally again

---

pcsx2-qt/QtHost.cpp
pcsx2/Frontend/InputManager.cpp
pcsx2/Frontend/InputManager.h

Stops binds getting stuck and having to manually press/release them, if you give focus to another window, release the key, and then go back to PCSX2.
It was annoying.
Test switching to another window with keybinds pressed and unpressed, make sure PCSX2 doesn't go into an infinite loop (see the comments as to my reasoning).

Qt: Clear all keyboard bind states when focus is lost

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Value written from HDR setup must be visible for any DATE reads.
Fixes flickering in DBZ BT2.
Test DBZ BT2 I guess. GS dump is on Discord.

GS/Vulkan: Don't skip barrier with colclip+readwrite date

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

The legit palette draws all seem to use FBW 1.
There's a couple of draws which use the alpha channel of the FB which are currently falsely triggering.
Closes #8320.
Check Jak games which were flickering before, make sure Jak 3 isn't borked, sensitive bugger.

GS/HW: Require FBW=1 for Jak OI fix

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fixes a possible validation error in Ultraman Fighting Evolution - Rebirth.
Things which might crash/lock up a GPU are bad in Vulkan.
Runner says it's okay.

GS/HW: Avoid copying an empty rectangle

---

bin/resources/GameIndex.yaml
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp

`PCRTCOffsets`:
Enables "Screen Offsets"
`PCRTCOverscan`
Enables "Show Overscan"
`minimumBlendingLevel`:
Forces the blend level to `max(userBlendLevel, minimumBlendLevel)`.
Use **with care**. Only games which are completely broken at lower levels and are lightweight requirements wise should be considered.
`maximumBlendingLevel`:
Forces the blend level to `min(userBlendLevel, maximumBlendLevel)`.
In other words, clamps to the specified level. Can be used for games which are unnecessarily slow at basic (e.g. memester hunter).
`recommendedBlendingLevel`:
Displays a notification when starting the game advising the user that a higher blending level is recommended, but warns of the requirements increases. Use for minor or heavy-hitting games that require higher blending.
Improving UX.
Test new …

GameDB: Add PCRTC and blending HW fixes

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

And use PCRTCDisplays instead.
I said I'd do it weeks ago.
Test feedback games, e.g. memeosaga.

GS: Get rid of GetOutputSize()

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2/GSDumpReplayer.cpp
pcsx2/GSDumpReplayer.h

And stops the crash when spam clicking shutdown.
Making testing easier, maybe.
Start GS dump, drag new GS dump over, it should switch.
Spam shutdown and try to crash.

Qt: Support changing running GS dump by drag/dropping

---

pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

And use it for preloading.
Saves a few draw calls.
Test a few preload needing games in each renderer.

GS/HW: Implement multi stretch for DX11/DX12/OpenGL

---

bin/resources/GameIndex.yaml

Adds a variety of fixes and recommendation's for users to ignore.
Better performance or quality, what's not to love.
Some screenshots so Red doesn't starve from lack of content for the Q1 2023 report.
Star Ocean 3 Master:
PR;
Monster Hunter Master:
PR:
Driver Master:
PR:
Underground 2 Master:
PR:
Shadow The Edgehog Master:
PR:
Tribes Aerial Assault Master:
PR:
Make sure I didn't make the CI whinge that I misspelt something obvious.

GameDB: Various recommendations and fixes

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Allows the texture TBW to expand, if it's an output framebuffer.
Changes from 1.7.4114 for Nicktoons Unite! broke Champions of Norrath which attempts to double the width from 512 to 1024
Test Champions of Norrath and Nicktoons Unite! (I've actually already done this)
Fixes #8287
Master:
PR:

GS-TC: Allow TBW expansion

---

pcsx2/GSDumpReplayer.cpp

Fixes title and HW fixes not applying when dragging a new GS dump onto a running PCSX2.
It's confusing without HW fixes.
Test dragging a GS dump over PCSX2 while one is already open, it should change serial/title.

GSDumpReplayer: Update serial on dump load

---

pcsx2/GSDumpReplayer.cpp
pcsx2/GSDumpReplayer.h
pcsx2/R5900.cpp
pcsx2/System.cpp

And get rid of memory reset, it's never used.
Resetting while a GS dump was running would sometimes crash.
Test resetting while playing a GS dump.

GSDumpReplayer: Fix resetting

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

Not sure how I wrote this, must've been half asleep.
Clearly wrong.
Can probably just yolo it, unless you can find a multi stretch which uses different colour enables. They both match vk now.

GS/HW: Fix incorrect condition in DX11/OGL

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

Originally we would multiply Cs by 1.9921875 to compensate for the wrong Ad value that is being used in hw blend, however an issue arises when any rgb value is higher than 128, then the multiplication would've been wrong resulting in wrong colors.
This aims to address that, if any rgb value is higher than 128 then take the highest value and adjust the compensation accordingly. which will give us more accurate colors.
Some effects might appear darker now on some games but it is more accurate now, they looked better purely by chance.
This is the best we can do with hw blend here, other alternative is to use sw blend which will be High in these cases on gl/vk or rov on dx.
Follow up from #5411
Accuracy, should've been done in #5411
Making hw blend suck less
Example:
Bakugan Battle Brawlers: …

GS-hw: Improve how we handle hw blend clr3 case

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/ShaderCacheVersion.h

GS-hw: Fix invert rounding for accumulation blend on gl.
Also make the checks consistent for all renderers.
Bugfix, regression from #8250
Tested, should be fine, change is obvious, can test the dump below.
[destroyallhumans_zfight.gs.zip](https://github.com/PCSX2/pcsx2/files/10902262/destroyallhumans_zfight.gs.zip)

GS-hw: Fix invert rounding for accumulation blend on OpenGL.

---

pcsx2/R5900.cpp

Fixes a regression which caused PCSX2 to crash if you loaded a dump with widescreen patches enabled.
Regression from #8341 
Crashes are bad mkay.
Make sure dump loading works correctly with widescreen patches enabled and the CI is a happy boy.

GSDumpReplayer: Fix widescreen patch crashing on GS dump load

---

bin/resources/GameIndex.yaml

Adds missing JP fixes for Ponkotsu Roman Daikatsugeki Bumpy Trot also makes Fallout Brotherhood Of Steel go BRRRR.
Fixes #8346 
Brotherhood Of Steel Master:
PR:
Bards Tale Master:
PR:
Missing fixes bad.

GameDB: Add missing Ponkotsu Roman Fixes

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Qt: Disable framebuffer fetch option on d3d.
Option shouldn't be toggleable on d3d.
On d3d option shouldn't be toggleable.

Qt: Disable framebuffer fetch option on d3d.

---

pcsx2-qt/MainWindow.ui

Restores the preferences menu option from the system menu that disappeared in #8297
Required for expected behavior on macOS (both from a "users expect it to be there" perspective, and a "removing it breaks the standard settings keyboard shortcut" perspective)
- Make sure you can ⌘, your way to settings

Qt: Restore main menu settings button

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

Avoids trying to start render passes with no target (and no dimensions, which are otherwise pulled from the target if not available)
Fixes #8238
Less crashy
Make sure nothing broke
#8238 was fixed by 40ee0e2aa7d38f29c329fdb3d3e3b8d576f63227, so this case really shouldn't be hit, but it's nice to be safe

GS:MTL: Don't start render passes with no targets

---

pcsx2/GS/Renderers/Metal/GSTextureMTL.h
pcsx2/GS/Renderers/Metal/GSTextureMTL.mm

Not aligning to 32 bytes can cause exceptions due to unaligned stores in ReadTexture().
Fixes #8303 (hopefully).
Test AVX2 with GT4 dump.

GS/Metal: Align texture upload pitch to 32 bytes

---

pcsx2/GameDatabase.cpp

It was reading from the GS thread copy instead of the CPU thread config.
> it's reading from the gs thread
> so, when you changed it to e.g. high, recommended = high, it still read the old value (e.g. medium), and displayed the warning
Test a game with recommended blending (e.g. Burnout 3).

GameDatabase: Fix recommended blending message

---

bin/resources/GameIndex.yaml

I Added autoflush to Dirge of Cerberus: Final Fantasy VII in the Gameindex.yaml
The game needs autoflush in order for the lighting to be accurate.
This fix needs testing because I've only tested it using a gs dump.

GameDB: Add autoflush to Dirge of Cerberus: Final Fantasy VII

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/Metal/tfx.metal
pcsx2/ShaderCacheVersion.h

GS-hw: Support Ad masked alpha on blend mix 1 and 2 clr cases.
GS-hw: Cleanup hw blend clr cases.
Cleanup redundant Blend C sets, they are already set properly beforehand.
Cleanup multiple barrier sets for Ad cases, set one at the end instead.
Cleanup conditions, reduce and cleanup the code.
Cleanup, possible regression fix for blend mix 2.
Dump runner doesn't show any changes (maybe Blockus_depth2, Burnout Revenge - impact screen as they showed up in the compare but didn't spot any diff) for blend mix 1 and 2 cases, maybe there's a game out there that uses it?

GS-hw: Blend fixes and cleanup.

---

bin/resources/GameIndex.yaml

It fixes this chain gate thingy on the left side. I really am oblivious as to what I should be calling it.
[Tony Hawk's Underground 2.zip](https://github.com/PCSX2/pcsx2/files/10949394/Tony.Hawk.s.Underground.2.zip)
Nothing. These 2 fixes are always safe to add.

GameDB: Add Mipmap and Trilinear to Tony Hawk's Underground 2

---

pcsx2/Frontend/ImGuiOverlays.cpp

Adds Estimate Texture Region and GPU CLUT to the status bar as well as amends the names of CPU CLUT and GPU CLUT.
More information more gooder.

ImGuiOverlays: Add missing fixes to status bar

---

bin/resources/GameIndex.yaml

Adds a missing gs fix to tony hawk's underground 2 and fix mrlink's typos
I forgot to add it.......
Nothing.

GameDB: Add blending level 3 to Tony Hawk's Underground 2

---

bin/resources/GameIndex.yaml

There's another version and I was oblivious to that.

GameDB: Add missing Tony Hawk's Underground 2 fixes.

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

Sets `a_masked` as a bool instead of an int, to match the shader
Not make every pipeline compile attempt fail
Test Metal renderer

GS:MTL: Fix wrong function constant type

---

common/D3D11/ShaderCompiler.cpp
common/GL/Program.cpp
common/Vulkan/ShaderCompiler.cpp

renames bad shader files so it's more obvious on linux where they came from.
seeing "bad_shader" files in your home directory isn't clear what it's from.
No real need, just a filename change.

GS: Rename bad_shader files to pcsx2_bad_shader for linux clarity

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui

Moves paltex and crc hacks into the hardware fixes section, and then removes the manual hardware fixes override from global settings completely.
Anyone who had global settings for hardware fixes will have those settings cleared/reset, so to not conflict when creating per-game configuration.
Option is still available globally in devbuilds.
Too many moronic youtubers and their stupid settings guides making people break other games.
Make sure manual hw fixes still works per-game, and that it's gone from global settings.
I've verified the clear logic works as expected.

Qt: Hide manual hardware fixes from global settings

---

pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp

Removes the last parts of WrapGSMem left.
It's not an option anymore and we haven't needed it, behaviour is permanently on.
Give it a cursory check, especially on games which used to need WrapGSMem (if you know them), as behaviour may have changed here, not 100% sure on the effect.

GS-Config: Remove remnants of the WrapMem setting.

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp

Fixes Integer Scaling when using Bilinear (Sharp)
Bilinear (Sharp) scales the image beyond the window size prior to checking if it can be integer scaled, so we need to compensate for the fact the image will be shrunk back down again.
Run games with integer scaling using various upscaling, compare to Bilinear (Smooth)
Fixes #8246

GS: Fix integer scaling when using Bilinear (Sharp)

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Fixes the masking of the Target Partial Invalidation setting when modifying the Texture in RT dropdown value.
The event was using the INI setting, which hadn't been set by this point, so the value was always behind what had just been selected, so this will use the current UI value instead of the INI value. The two aren't mutually exclusive, so it should be enabled when Tex in RT is disabled, and visa versa.
Go in to the graphics settings, enable manual hw fixes (so per game, or use a dev build) and mess with the Tex in RT dropdown.

UI: Fix masking of Target Partial Invalidation with Tex in RT

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Detects when games do texture shuffles with double width instead of double height (how dare you)
Usually when shuffling a 32bit texture as 16bit, you would double the height as the page size is double for 16bit, however some gamedevs thought they were clever and would double it horizontally instead, this messed up our height correction/detection when a shuffle happened.
Kind of a regression from #8336 however it was never really handled properly, but hacked in until said PR.
Test Midnight Club 3, maybe a spatter of other games doing texture shuffles, just to make sure things are okay. I did a GS Dump run on my 1100 dumps, and everything else seemed to be okay.
Midnight Club 3:
Master:
PR:

GS: Detect double width texture shuffles

---

pcsx2/VU0.cpp
pcsx2/x86/microVU_Macro.inl

Masks the value of R when reading it from VU0 on to the EE through CFC2
the 0x3f800000 (1.0) we add when writing to R is implied on the register, so when reading, the top bits should be zero, this was causing bad AI behaviour in Onimusha Dawn of Dreams.
Test Onimusha Dawn of Dreams, make sure the AI is less braindead.  I guess maybe try other bad AI games, on the offchance it helps. Stuntman is unaffected.

COP2: Mask R register on CFC2 reads

---

bin/resources/GameIndex.yaml

I have added Mipmap and Trilinear for Spyro: Enter the Dragonfly
The mountain's textures were looking very sharp without it.
[Spyro - Enter the Dragonfly_SLES-51043_20230315134521.gs.zip](https://github.com/PCSX2/pcsx2/files/10978796/Spyro.-.Enter.the.Dragonfly_SLES-51043_20230315134521.gs.zip)
Check the GS dump I have added, just to confirm that the game truly needs it.

GameDB: Add Mipmap and Trilinear to Spyro: Enter the Dragonfly

---

bin/resources/GameIndex.yaml

Fixes broken effects when using lower than high blending.
Master:
PR:
Broken effects bad.

GameDB: SMT DS Fixes

---

.github/workflows/macos_build.yml
.github/workflows/scripts/releases/rename-release-assets.py

macOS 10.14 fixed a bug where Archive Utility couldn't decompress .tar.xz files, and we now use a minimum version of 10.14 so we might as well use them
Save a few mb on the download
Make sure you can still unzip builds
@xTVaser there's nothing on the website side of things that would dislike this change, right?

CI:macOS: Use xz for distribution

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

GS-hw: Clean up Wunused-variable warnings in hw renderer.
Less warnings.
CI compiles.

GS-hw: Clean up Wunused-variable warnings in hw renderer.

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Drops back to the CPU for drawing the glass smashed effect
Also fix rects for SW draws.
The game draws this from a 4bit texture on boot, before the title screen, problem is this gets ejected from the texture cache due to old age and never ends up in GS memory, so we may as well draw it on the CPU so it goes in to GS memory.
As for SW draw dumps, the rects took the width, height of the rect, but this didn't really do much good if the draw was offset.
Run any of the Burnout games 3 onward, check the glass looks smashed when you crash.

HW-CRC: Draw glass smash on CPU in Burnout 3+

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Corrects the width/height of the source and copy when the source is found in a render target (previous draw).
This was errantly taking a restricted region, but in DBZ BT3 it's offset, but when it's a render target, it's not really set up to handle the offset, so we just make sure we take everything we need.
Check DBZ BT3 2 player mode (already checked a GS Dump).
Master:
PR:

GS-HW: Correct region size when source is in render target

---

pcsx2/GameDatabase.cpp
pcsx2/MemoryCardFolder.cpp

The return type switched between 0.4 and 0.5, so this will be compatible with both
Fixes #8427
Better compatibility with multiple ryml versions
Try building with ryml 0.5

Core: Use auto for ryml noderefs

---

pcsx2/x86/BaseblockEx.h
pcsx2/x86/ix86-32/iR5900-32.cpp

Stops storing sizes in 16-bit integers
Fixes assertion failures on Crash Team Racing
Fixes #8418 (though please compile your actual builds in release, we don't want issues being made about the terrible performance of debug builds)
Less brokenness
We weren't even saving any space with this in 64-bit because of the field ordering
Test Crash Team Racing
Test other games

iR5900: Don't limit block sizes to 16 bits

---

pcsx2-qt/Debugger/CpuWidget.cpp

Converts the value we're searching for to ulonglong instead of long
Fixes crash caused by searching for a value larger than the type
Should fix #8420. Long was also not big enough to search for 64 bit values, so longlong should be used instead.
Search for values greater than 7FFFFFFF in the debugger. It should allow you to now.
An error box should now prevent you from searching for a value higher than the type you're searching for. On master, doing this causes PCSX2 to stop responding and begin rapidly consuming memory until it presumably crashes.

Debugger: use ulonglong for memory search + fix crash

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

On local mem invalidation, make sure we mask the target with the drawn area for that target before we try to download from it.
This was causing a misdetection in Shadow Hearts - From The New World, as the game starts trying to double buffer, then decides to use offsets instead, and we don't handle "draw inside RT" style draws currently, so it kinda gets in to a mess. While this isn't the perfect solution here, it's still correct to check the area drawn is what we need from the current target.
Test Shadow Hearts - From The New World, I  guess a spattering of other games which do readbacks (Though I'm not expecting any change anywhere else, this was still happening, just later, in the wrong place)

GS-TC: mask target rect with drawn area before download.

---

bin/resources/shaders/dx11/interlace.fx
bin/resources/shaders/opengl/interlace.glsl
bin/resources/shaders/vulkan/interlace.glsl
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/Metal/GSMTLShaderCommon.h
pcsx2/GS/Renderers/Metal/interlace.metal
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

It's silly to draw to the whole double-sized render target, but discard half the pixels.
Also centralizes the constant setup, get rid of the duplication.
Lastly, forces LOD 0 sampling in these shaders, since you can't use normal sampling because the derivates are undefined in
non-uniform control flow.
Small performance boost at high upscaling.
Make sure MAD works as expected in all renderers.

GS: Reduce MAD buffering draw size 

---

pcsx2/VMManager.cpp

A misplaced parenthesis caused `s_active_widescreen_patches` to evaluate only ever to `0` or `1`. No interlace patches had it right, widescreen ones did not.
Make UI not lie.
1. Put any widescreen cheat in `cheats_ws`.
2. Load the game.
3. Observe that "X widescreen cheats loaded" does not lie about the amount of loaded patch lines like it used to.

VMManager: Fix "X widescreen patches loaded" text when loading from files

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSRendererSW.h

Removes ExpandTarget function where it would expand targets on EE write.
this was original added for the Castlevania Curse of Darkness videos, however this has now been resolved through better means, and this keeps causing us headaches, especially if it's doing huge clears through the EE memory.
Test Castlevania Curse of Darkness FMV's, apparently might affect Mercenaries to an extent also.

GS: Remove ExpandTarget on EE Write

---

bin/resources/GameIndex.yaml

Adds partial target invalidation to every From Soft game because they used way too much glue.
Fixes (partially) #8450 
From Soft needs to lay off the glue.

GameDB: From Soft game fixes

---

pcsx2/GS/GSLocalMemory.h
pcsx2/GS/GSLocalMemoryMultiISA.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h

Compensates for misaligned transfers which generally happen with 24bit transfers when the transfer is split.
In Keroro Gunso and We Love Katamari it downloads the 24 bit framebuffer in 2 parts, but it ends the first transfer 1 channel in to the 3 channel pixel, meaning it's offset strangely when it does the second part of the transfer.  So to compensate for this we do the whole pixel it ends on, then do an offset on the second part of the transfer, this stops the colours being incorrect as a bar across the bottom.
Test Keroro Gunso - Mero Mero Battle Royale pause screen and We Love Katamari Damacy transition in to the collection.
Keroro Gunso:  (There is another issue I need to solve with HW mode where the download fails first time, need to investigate)
Master:
PR:
We Love Katamari: …

GS: Compensate for misaligned partial 24bit local->host transfers

---

.github/workflows/scripts/linux/build-dependencies-qt.sh
cmake/BuildParameters.cmake
cmake/FindLibbacktrace.cmake
cmake/SearchForStuff.cmake
common/CMakeLists.txt
common/CrashHandler.cpp
common/Linux/LnxHostSys.cpp

Uses libbacktrace to get a backtrace when we crash on Linux.
Also updates Qt to 6.4.3 and SDL2 to 2.26.4, since I'm modifying the dependencies script, and it'll take a while to build/cache.
Helps support and bug reports, since users don't want to (or don't know how to) use gdb.
Can't do demangling, because the gcc function allocates memory, and we don't want to be doing that if we crashed because we had a screwed up heap.
Kinda difficult, unless you know how to make pcsx2 crash, in which case we should fix it :P
But the Linux guys can make sure that the AppImage still works with updated Qt/SDL.

CrashHandler: Print backtrace on Linux

---

cmake/BuildParameters.cmake

-g tends to blow the AppImage sizes up a bit too much, and we don't need the stack frame/variable information for user backtraces.
AppImage went from ~40MB to ~100MB...
See how much the AppImage gets reduced.

CMake: Swap -g for -g1 in Linux Release builds

---

pcsx2-qt/AutoUpdaterDialog.cpp
pcsx2-qt/AutoUpdaterDialog.h
pcsx2-qt/QtHost.cpp

Does what the title says.
Stops users complaining about having multiple AppImages lying around.
Can't really test this in PR form, but I've ran all the components independently and it behaves as expected.

Qt: Remove backup AppImage on next launch

---

pcsx2-qt/Settings/InterfaceSettingsWidget.cpp

Change "Recommended Value" to default value for following preferences:
- Create Save State Backups
- Double-click Toggles Fullscreen
- Hide Mouse Cursor
Just for more consistency.
- This was discussed in #8464 
I'm not sure.

UI: Correct Recommended Values for a few items

---

pcsx2/GS/Renderers/DX11/GSDevice11.cpp

Regression from #8336.
P8 conversions turning into black breaks games.
Closes #8415.
Already tested, issue is fairly obvious (storing integer data in a float4).

GS/DX11: Fix incorrect UBO for P8 conversion

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Checks that the LocalMem invalidation is inside that render target, otherwise look for more render targets.
Metal Gear Solid 2 Substance was getting false positives during the cutscene, causing it to download garbage.
Test readbacky stuff.

GS-TC: Only stop checking for RT's if whole read is inside that RT.

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

On Local Mem invalidations, if the start/end address of the read matches the entire RT, then it's pretty certain that's the same one.
Metal Gear Solid 2 still didn't work properly, mainly because I was an idiot, we won't speak of this again.
Test MGS2 Substance cutscenes (already checked it, and made sure I didn't accidentally leave old override settings on this time.)

GS-TC: Give option to match target on exact memory addresses

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

This does a few things:
If a render target is used as a source it will check if what it reads is going to be bigger and resizes it to match.
The drawing rect for hardware mode draws is rounded up as to make sure it draws all required pixels.
In order of things:
- Games such as Armored Core will use a render target which is much smaller than what it requires, causing the render target to repeat across the who draw, this was also an issue with the water in Wave Race (though that has a different issue, but the reflections are better now).
- The drawn rect was not big enough for calculating the draws, meaning the drawn area we were recording was incorrect, meaning Dogs Life didn't download all the data it needed, leaving a line of beads in Jake's head.
Test above mentioned games, make sure …

GS-HW: Resize RT used as larger source

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.h
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp

Jak uses colloquially known as "mip tricks" for its water, giving it a different appearance the more it's minified based on how large the texture appears on screen.
We can't texture-inside-RT for mip chains at the moment, so punting it to the CPU is realistically the only option to handle this for now.
Unfortunately the CRC hack still has to stay there for Jak X.. sprite render ends up with a box in the top-left corner.
Before:
After:
Need to test a bit more of all three Jak games to make sure this isn't triggering incorrectly. If it does, please post a GS dump so I can investigate.

GS/HW: Swap OI_JakGames CRC hack for CPU sprite render

---

bin/resources/GameIndex.yaml

The streets were looking inaccurate in https://github.com/PCSX2/pcsx2/pull/7969 's gs dump.
~ This is the same pr as #8491

GameDB: Add Mipmap and Trilinear to The Incredibles

---

bin/resources/GameIndex.yaml

Adds ee nearest rounding mode to gamedb to fix the rainbow specular highlighting that can appear on the car models.
Before:
After:
Weird colour changes and iridescent sheens are not right.
Tested locally and it hasn't had any detrimental effect on the games physics after running though a couple of rallies and has fixed the colour issues on all out of the box unlocked cars.

GameDB: Fix WRC 4 car discolouration

---

pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/GS/Renderers/Common/GSRenderer.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Provide HPO Normal offsets when there is no Render Target.
HPO offsets are usually provided by the Render Target, so if a draw is doing the depth only and no offsets are provided, this is basically undefined behaviour, causing bad draws, this was evident in Kingdom Hearts: Chain of Memories and I believe Rogue Galaxy as reported here: https://forums.pcsx2.net/Thread-Bug-Report-Rogue-Galaxy-NTSC-U
Test Kingdom Hearts and Rogue Galaxy while upscaling.
Kingdom Hearts (the rendering of Sora is the only part of interest here):
Master:
PR:

GS: Provide HPO Normal offsets when there is no RT.

---

.github/workflows/release_pipeline.yml

Removes the AVX2 and SSE4 builds in favour of the unified Qt build.
Making support vastly smoother when you only have 1 build to tell someone to go download instead of playing whack a mole with 3 different builds that do the same thing.
Make sure CI is happy? Might need someone who actually knows how this works to also have a look.

CI: Remove separate Windows builds

---

.github/workflows/release_pipeline.yml

Switches the Qt builds over to using Clang by default which should be a bit faster overall.
Gotta go fast.

CI: Switch Windows Qt builds to Clang

---

bin/resources/GameIndex.yaml

A continuation of #8492 
Like The Incredibles + ROTU, The SpongeBob Movie Game also needs trilinear filtering and mipmapping for textures to be rendered accurately to console or in software mode. I also replaced textureInsideRT with partialTargetInvalidation instead as it was breaking more things rather than fixing things.

GameDB: Add Mipmap/Trilinear to SpongeBob Movie & Incredibles

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Check what channel is being read during split shuffle detection.
50 Cent Bulletproof was misdetecting this effect as it does 2 shuffles, one for the green channel, the one for the red, but it was being detected as the same shuffle, making the screen very green! So now we change that the first UV's for each shuffle match up.
Test 50 Cent (I've checked GS dumps).
50Cent:
Master:
PR:
Fixes #8503

GS-HW: Check what channel is being read during a possible split shuffle

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fixes up Translate by page behaviour and clean up required variables.
Also only abort local mem invalidate on exact match.
When I originally did this, I assumed buffer width was in pages, it isn't, which gave incorrect results.  It flukely got away with it, but it wasn't right so now it's fixed up.
Gran Turismo 3 seems to be getting multiple overlapping targets on boot, causing it to invalidate the memory with incorrect data. Now it will only complete the invalidation early if the target matches exactly.
Test games, especially those which require Tex in RT. No known fixes/breakages however. Also GT3
Fixes the split time car sprites in Gran Turismo 3.

GS-TC: Fix up page translation logic, clean up variables

---

bin/resources/shaders/common/fxaa.fx
pcsx2/ShaderCacheVersion.h

Fixes fxaa regression on opengl.
Bad shader/broken display using fxaa.
Regression from #8209
FXAA works on opengl.

GS: Fix fxaa bad shader regression on opengl.

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/x86/iFPU.cpp
pcsx2/x86/iFPUd.cpp

Fixes Tales of Destiny crashing on clang builds (clang was using r8, which was allocated by a caller, msvc was not).
Also cleans up some new warnings it was spewing.
Has been a bug since my dynarec optimizations, but nobody noticed.
Test Tales of Destiny on clang build.

x86/iFPU: Inline FPU_MUL_HACK to dynarec

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/InterfaceSettingsWidget.cpp

- Adjusted Highlight color of buttons to improve its contrast and readability for both Pizza and Cobalt Theme.
- Simplified the theme name a little bit.
- Tweaks the variable names for consistency with other themes (Copy paste fail moment).
Before:
After:
Before: 
After:
Readability++
Contrast++ 
Make sure the button and highlights are still readable elsewhere!
Feedback are appreciated!

Qt: Theme Polishes for Pizza and Cobalt

---

bin/resources/GameIndex.yaml

Fixes blurriness in Sitting Ducks.
Sitting Ducks does not look as sharp as it should without this fix applied.
Over the Hedge has an unnecessary line drawn in the Woods main area.
Sitting Ducks Before (Master):
Sitting Ducks After (Pull Request):
Over the Hedge Before (Master):
Over the Hedge After (Pull Request):
No suggested testing steps.

GameDB: Fix blurriness in Sitting Ducks and Fog Line in Over the Hedge

---

bin/resources/GameIndex.yaml

Fixes for missing Tekken 5 demo that caused camera issues.
Fixes #8527
Game missing fixes bad.

GameDB: Fix missing Tekken 5 demo

---

pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp
pcsx2-qt/Settings/ControllerGlobalSettingsWidget.ui
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/SDLInputSource.cpp
pcsx2/Frontend/SDLInputSource.h

Expose SDL raw input as configuration option.
#8518 has had a side effect of disabling the previous sdl raw input default. This brings the behaviour back as a togglable option for those that enjoyed it randomly turing off xinput pads while in sdl mode. May also have compatbility advantages for less common pads with it as user option.
Tested locally with switch pro, wired 360, xbox elite 2 and f430 wheel plus steam deck with no issues.

SDLInputSource: SDL raw input as config option.

---

pcsx2-qt/MainWindow.cpp

Unchecking the pause button was unpausing the VM, before it shut down, which re-hid the main window.
Fixes #8466.
Test confirm VM shutdown while fullscreen (done myself).

Qt: Fix main window closing on fullscreen shutdown

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

UpdateConfig() was being called regardless of whether sw renderer was enabled, which meant it started the worker thread, and it never got joined when PCSX2 closed.
Fixes crash on shutdown if sw renderer is selected, but texture replacements were previously enabled in hw.
Already tested, can review changes manually, but it's pretty straightforward.

GS: Fix crash on shutdown when using software renderer

---

common/D3D12/Context.cpp
common/D3D12/Context.h
pcsx2/Frontend/D3D11HostDisplay.cpp
pcsx2/Frontend/D3D11HostDisplay.h
pcsx2/Frontend/D3D12HostDisplay.cpp
pcsx2/Frontend/D3D12HostDisplay.h
pcsx2/GS/GS.cpp
pcsx2/GS/GSUtil.cpp
pcsx2/GS/Renderers/DX11/D3D.cpp
pcsx2/GS/Renderers/DX11/D3D.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp

Also makes Vulkan the device for Intel Arc GPUs.
Software will now use the preferred API for the system, in other words, Vulkan for NV/AMD, or DX11 for Arc. Works around NVIDIA driver issues and our interlacing shaders...
Less code, I'm going to ditch HostDisplay completely, since it's kinda redundant now, but one thing at a time.
Test D3D renderers and default renderer.

GS: Unify D3D device creation paths

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GameDatabase.cpp
pcsx2/GameDatabase.h
pcsx2/Pcsx2Config.cpp

Required for Crash Bandicoot: The Wrath of Cortex.
It constructs a new P8 texture in local memory based on the depth buffer, by reinterpreting it as C8, then draws a bunch of tiny sprites to C32, then reinterprets _this_ as P8. Any single pixel being off breaks the effect, which is why it didn't work with upscaling before.
So, this PR adds a new upscaling hack to force these palette texture draws to native resolution instead. WoC looks fairly good, the edges are still a bit rubbish, but they are at native in the software renderer too. The effect just.. isn't fantastic.
Before:
After:
It also helps Driv3r's glitched out text (similar method to draw), punting that to the CPU would be ideal, but that introduces other issues.
Closes #2380.
Closes #6006.
Test Crash WoC.

GS/HW: Add NativePaletteDraw upscaling fix

---

pcsx2/USB/usb-pad/usb-pad-ff.cpp
pcsx2/USB/usb-pad/usb-pad-sdl-ff.cpp

Removes some incorrect logspam from the set force methods. The second call to each set ends up always hitting the else condition and spits out whatever the last internal SDL error message is sitting in it's buffer.
Also gates off the FF packet dump behind DEBUG ifdef because thats way too verbose for normal use.
Logspam bad. Logspam with irrelevent errors, even worse.
Should be safe. CI pass and look for cleaner logs with force feedback devices are in use.

USB: Remove force feedback logspam

---

pcsx2/x86/iFPU.cpp
pcsx2/x86/iFPUd.cpp

Fixes the FPU_MUL_HACK for Tales of Destiny
When it was converted from the old style the wrong value was set for the result, causing the towns in Tales of Destiny to softlock.
Already had somebody test Tales.

EE: Correct FPU_MUL_HACK result value

---

pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

Was trying to bind a depth stencil target as a render target...
Framebuffer was not complete, sad driver
This showed up in Tekken 5, but it was clearly wrong

GS/OGL: Fix incorrect binding in multi stretch rect

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

The effect still isn't correctly emulated, it's meant to fade between the previous frame and current.. but that's not working correctly, because the RT is C24 not C32, and the channel shuffle effect isn't correctly emulated, and I don't feel like going down that rabbit hole today.
But it gets it back to where it was.
Regression from #8209.
Test GT4 fade transition (start a race).

GS/HW: Fix blue screen in GT4 transitions

---

pcsx2/GS.cpp

Don't reset the vsync rate etc on CSR reset.
This information is controled by GSSetCRT and is handled separately from the usual privilaged registers in PCSX2, so for now it's best we don't change what it was already set to on CSR reset, if the game wants to change it, it will call GSSetCRT.
Nothing much to test, just a small thing I noticed.

GS: Don't reset CRT mode on reset

---

pcsx2/Counters.cpp
pcsx2/GS.cpp

Uses our progressive check to see if the game is interlaced instead of the GSSetCRT check.
Some things can swap between progressive and interlaced without calling GSSetCRT, this makes sure we catch that.
Just make sure the capped framerate of games is okay.

GS/Counters: Use progressive check, not GSSetCRT for interlace mode

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp

Updates CRC hack to actually render the special effects and add GameDB entry for some half screen effects.
The old CRC hack just killed the special effect, which is rendered by offsetting in to the render target, which we don't support. So punting it to the SW renderer is a better choice.
Test Sacred Blaze and make sure fancy light effects (and the memcard/options screens in the main menu) all work ok.
Master:
PR:
Software (for reference):

GS: Update fixes for Sacred Blaze

---

bin/resources/GameIndex.yaml

Replace Texture inside RT with Partial Target Invalidation
It was breaking lights.
Check CI
Fixes #8562

GameDB: Replace Tex in RT with Partial Target Invalidation, Dark Cloud 2

---

pcsx2/x86/ix86-32/iR5900-32.cpp

Clears the Reset request for the EE JIT after the reset has been started, when a memory overflow happens.
Oversight/missed thing from #8511
Test Metal Gear Solid 2, make sure it doesn't get in a reset loop (already checked).

EE: Clear reset required status on JIT overflow reset

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

FF12 apparently does a whacky point draw for FMVs (not that uncommon) but then copies it with textured lines?
And the cheeky CRC hack screws with the texture cache's fields unsafely.
Regression from #8209 and #8336.
Test FF12 PAL (done with a block dump).

GS/HW: Fix Final Fantasy XII CRC hack

---

pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp

Fixes scanmask usage situations which break with antiblur enabled.
Final Fantasy X-2 was using scanmask for shadows, and anti-blur was breaking them.
Test FFX-2, Metal Gear Solid 2 (water/radar) & 3 (windows), Alpine Racer 3, or any other Scanmask games you might know.
Fixes #8227

GS: Fix some Scanmask situations in PCRTC

---

pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/USB/usb-pad/usb-pad-sdl-ff.cpp
pcsx2/vtlb.cpp

Was probably trying to do it on a shuffle or another target source
People are silly
Yolo because the option is silly
The warning fixes are just whitespace/braces so will be safe

GS/HW: Don't try to use forced trilinear on shuffles

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Direct textures were using the indexed/palette read routine, leading to hash collisions when there shouldn't have been one.
Test a texture pack to make sure it didn't break. It shouldn't, since palette textures which are the most common would be unaffected.

GS/HW: Fix incorrect hashing of non-palette textures

---

bin/resources/GameIndex.yaml

Updating gameDB entries of Siren and Fatal Frame.
Fixes black lines in Fatal Frame and sky rendering in Siren.
Before: 
After:
[FF1+Siren-GS_Dumps.zip](https://github.com/PCSX2/pcsx2/files/11159059/FF1%2BSiren-GS_Dumps.zip)

Updated gameDB entries for Fatal Frame and Siren GameDB

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

Improves the use of source in target when the target wraps (issue with King's Field pause screen)
Improves Double Half Clear to also work per channel, so if some channels are masked, it retains the old data (Lord of the Rings + Ninja Assault)
Adds reading back targets to the GS memory when a GS CSR reset is performed (for the Jak games when changing to Progressive mode)
Also add Auto Flush to Power Drome US, apparently it wasn't there.
Wrapping wasn't being handled right, so the results of tests were incorrect, causing it to pull data from local memory, which is garbage.
Double half clear was too stringent and needed to be loosened off in some cases, but was also very rigid in how it worked, now it can be a bit less so.
Flushing the targets on CSR reset flushes the targets to GS memory …

GS-TC: Improve handing of wrapping targets & double half clear

---

pcsx2-qt/QtHost.cpp
pcsx2/Counters.cpp
pcsx2/Counters.h
pcsx2/GS.cpp
pcsx2/SaveState.cpp
pcsx2/VMManager.cpp

Retools how UpdateVSync works to be less prone to errornous updates.
Kind of a regression/highlighted problem from #8552 brought up by the progressive mode in Fatal Frame 3, where it was constantly toggling the interlace bit in progressive mode (this does nothing), but it was causing the ticks/counters to reset, starting the current frame over, making them longer, which in turn made the framerate too low.
I figured I'd retool things a bit so it wasn't doing any work it didn't have to while I was at it.
Test Fatal Frame 3 progressive mode, check it's 59.94. Maybe check a spatter of other games, especially if the framerate wasn't quite sitting where it should be.

Counters: Retool UpdateVSyncRate

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

DBZ Budokai 3 downloads the depth buffer from 0xe00, then does a bunch of draws with 0xe00 as a depth buffer. Then it reuploads the old 512x448 C32 target back to 0xe00, then uses it as FRAME.
Because our last use was as depth, we update the old target as Z24, scrambling the blocks.
This PR changes the order so that the update happens on the new target (and associated format) instead of the old. The old is going to get tossed away anyway, so no need to keep the dirty list around. Furthermore, if the whole target is dirty, we can skip the copying-of-the-old-target-back-in step.
Closes #8579.
Dump runner says it's okay.

GS/HW: Update target in new format when reinterpreting 

---

pcsx2/GS/Renderers/Common/GSDevice.cpp

Fixes a typo where m_current was used instead of the incoming texture.
It was wrong and causing things to crash if you booted a game, changed to software mode, then hit reset.
Just make sure nothing crashes running normally, or pressing F9 after loading then pressing reset.

GS: Fix typo in ResizeTexture which was causing a crash

---

pcsx2/GS/Renderers/Common/GSFastList.natvis
pcsx2/GS/Renderers/HW/GSTextureCache.natvis
pcsx2/pcsx2core.vcxproj
pcsx2/pcsx2core.vcxproj.filters

While investigating #8580, I wanted to look at the list of targets present when paused in the debugger, but FastList isn't really capable of doing that. So I wrote some natvis type files for both FastList, as well as targets, to make debugging stuff in the TC a little less pain-inducing.
None needed, it only affects running under the debugger.

GS: Add VS natvis files for FastList and TC Targets

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Gradius does a bunch of moves and then samples from them as described in #8107. This broke some time recently with the page translation stuff, it was looking for a target at 34A0, finding 3440, which was a dirtied target which shouldn't be considered. But instead of continuing to search for the next target (34A0 was at the end of the list), it was exiting early.
Closes #8580.
Test Gradius.

GS/HW: Don't break out of target search loop on dirty target

---

pcsx2/GS/GSLocalMemoryMultiISA.cpp
pcsx2/GS/GSState.cpp

Avoid modifying the memory address and length when the request is only 1 QW as it likely is going in to a CPU register, also avoid downloading more than requested.
This was causing stack corruption which could have manifested in crashes.  This PR is a temp measure until my lazy ass properly redoes the download function to copy this in to a temp buffer instead of reading it off in chunks like this, which would give accurate results.
Probably won't see it but I guess make sure FFX-2 doesn't crash coming out of the fight with Yuna at the beginning (white screen transition).

GS: Avoid modifying single QW downloads as they go to a register

---

bin/resources/shaders/opengl/tfx_vgs.glsl
common/GL/Program.cpp
common/GL/Program.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h

Bug inherited from the DuckStation code I pulled in ages ago.
Plus gets rid of the GL-specific selector, we don't need it and can just use the base class.
Leaks are bad.
Make sure the OpenGL renderer still works.

GS/OGL: Don't leak shader objects when compiling

---

pcsx2/GS/GSLocalMemory.h
pcsx2/GS/GSLocalMemoryMultiISA.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h

Retools GS downloads (Local -> Host) to buffer the entire read before downloading.
As a bonus, unsync'd reads might also be slightly more reliable if they were split in to two or more reads, not sure how frequent this is.
Split transfers are kinda gross and messing with offsets to the memory/length is just dangerous and we ended up with stack and heap corruption in some cases, so it's better if we just buffer the lot so we can read it off in 8 bit increments and get the exact data it's expecting.
Test any games with readbacks, make sure they're okay, especially FFX-2 and Keroro Gunsou - Mero Mero Battle Royale (though  I've already tested this and a sprinkle of other games)

GS: Retool downloads to buffer full read

---

bin/resources/GameIndex.yaml

Adds mipmapping and trilinear to Hasbro Family Game Night
Textures are broken without it, similarly to Ratchet & Clank/Jak
Check CI is happy
Fixes #8589

GameDB: Add mipmapping to Hasbro Family Game Night

---

pcsx2/GS/Renderers/Common/GSDevice.cpp

Apparently getting the font data clears the texture pointer.
Closes #8591.
Closes #8594.

GS: Fix crash when resizing window

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
tests/ctest/core/StubHost.cpp

Renderer switches had a very brief moment where there was no window on screen -> Qt thought "no windows left, better shut down", which deadlocked waiting for the CPU thread to shut down -> waiting for GS thread -> GS thread waiting for main window to create new render window.
This PR creates the new window at the same time as destroying the old one. Why do we need to do this? Renderer switches to/from DirectX, particularly when flip mode gets engaged.
Closes #8592.
Test linked issue.

Qt: Recreate new window immediately when switching APIs

---

pcsx2/GS/GS.cpp

Resets the performance counters on reset.
"stop ref getting triggered by phat numbers of TCs"

GS: Reset performance counters on renderer switch

---

bin/resources/GameIndex.yaml

Adds Autoflush and HPO Special to Ultimate Spider-Man
Fixes shadow positioning, much like Spider-Man 2, matches closer software mode (minus the resolution). HPO Normal does look better aligned, but it causes top left glitches.
Watch CI
Master:
PR:

GameDB: Add Autoflush and HPO Special to Ultimate Spider-Man

---

pcsx2/x86/iR5900Analysis.cpp

When checking the EE program for recompilation, checks if it's setting something on the VU's to zero, which is likely being used a lock/loop sync
This optimisation was too loose for Ratchet & Clank games, so there was some SPS still, this should clear it up.  This doesn't seem to cause any FPS loss, which was of course a worry.
Test Ratchet & Clank games for SPS on default settings (I don't care if overclocking/underclocking the EE causes problems, that's to be expected)
Up Your Arsenal: (Look at his feet, ear, tail)
Master:
PR:

EE/COP2: Check for likely zero clears in COP2 synced ops

---

bin/resources/GameIndex.yaml

Adds Instant DMA to Jak 3 
Due to timing problems, there ends up being holes in the face geometry without it.  Turning off instant VU was another possible fix but that has performance implications where this is free/potentially faster.
Test Jak 3, make sure nothing is broke.
Master:
PR:

GameDB: Add InstantDMA to Jak 3 for holes in face geometry

---

pcsx2/GS/GSLocalMemory.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Don't want to do divides per-target.
All the tiny optimizations eventually add up.
Test a couple of games sensitive to translated targets.

GS/HW: Tiny optimization in source lookup

---

bin/resources/GameIndex.yaml

Updates the Ultimate Spider-Man gamefix to only affect VU1
Affecting both VU's was causing fire effects to be missing, but the texture fix was only required on VU1.
Watch CI:
Fixes #8569
Master:
PR:

GameDB: Update the VU clamp mode on Ultimate Spider-Man

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Skips the broken post effect completely, rather than doing a bunch of pointless copies and draws to screen-sized targets which don't get used.
> source is 8c0, the main color buffer
> but yeah, it's just interleaved
> so the first row will write to 1a40 for color, 1a60 for depth, the next will write to 1a80 for color, 1aa0 for depth, and so on
> so that ends up as black
> then it takes this interleaved s**t and writes it to 1dc0 with FBW 5
> which is... 28 pages after 1a40
> so directly after these interleaved draws
> problem obviously is, we're not interleaving 1a40+1a60
> although.. I don't know if it's actually reading it
> need to dump the draws..
>     min t (x,y,z,w): 1.000000, 1.000000, 16.000000, 16.000000
>     max t (x,y,z,w): 65.000000, 449.000000, 1040.000000, 7184.000000
> so …

GS/HW: Adjust Burnout CRC to fully skip broken post effect

---

pcsx2/x86/iR5900Analysis.cpp

Increases the sync when a clear is likely happening on COP2
Ratchet broke more in other ways, I guess we need even more sync. There is a small performance impact here, between 2-5%, but I dont' see any other way around it, at least it's not as bad as it used to be still lol.
Test Ratchet & Clank games.

EE/COP2: Increase likely clear sync

---

bin/resources/shaders/dx11/tfx.fx
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Metal/tfx.metal

Fixes broken half screen in Miami Vice and 10 Pin - Champions Alley.
Closes #8313.
Closes #1824.

GS/HW: Allow translating targets for depth sources

---

bin/resources/GameIndex.yaml

Fixes cut off text in PAL versions of Zone of the Enders 2.
Fixes #4091 
Cut off text is ba

GameDB: PAL ZoE 2 Text fix

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

This happened in GOW2 when switching to progressive mode. Copying a depth to colour format is illegal in Vulkan.
UB which can make drivers very cranky.
Test GOW2 progressive switch.

GS/HW: Always convert float depth to integer on readback

---

pcsx2/SPU2/spu2freeze.cpp
pcsx2/SaveState.h

Storing pointers in the save state is kinda terrifying. There was a hack here before to null out the write pointer, but not the read pointer.
Let's do it properly and save the offsets from IOP memory instead.
Sadly need to bump save state, don't want to have a mess of different version handling here.
Got a random crash when saving and loading after restarting the emu in Burnout 3 due to this.
Test saving and loading state after restarting emu (to get fresh/changed base pointers). Burnout 3 in the middle of a race is a good candidate since that crashed for me.

SPU2: Store DMA pointers as offsets in save state

---

pcsx2/SPU2/spu2freeze.cpp

Corrects the pointer to the cores used for correcting the DMA pointers when restoring savestates.
Pointing at the savestate data instead of the actual core is bad, caused crashes.
try saving states and loading them on a couple of games.
Fixes #8641

SPU2: Fix savestate loading setting incorrect variable

---

.github/workflows/scripts/linux/appimage-qt.sh

Apparently needed for Qt 6.5, and it was missing.
Also gets rid of the unit tests from bloating the binary.
Fixes launching on a out-of-the-box Ubuntu 20.04 install.
@Mrlinkwii test pls.

AppImage: Include libxcb-cursor

---

pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp

Hide the option introduced in #8526 when not applicable.
Has no effect on non win32 SDL builds to makes sense to hide it.
Controller config shouldn't go boom and everyone but windows users should not see it.

Qt: Hide SDL Raw option on non win32 builds

---

bin/resources/GameIndex.yaml

Added Kirie hang fix to Fatal Frame Korea and Asia.
Add PNACH fix to Fatal Frame 1 preventing Kirie final boss hang that occurs on real hardware.
Mo regions, mo able to beat game without glitch
Already been tested

GameIndex: Add Fatal Frame 1 Boss Hang Fix to more regions.

---

bin/resources/GameIndex.yaml
pcsx2/SPU2/ADSR.cpp
pcsx2/SPU2/Dma.cpp

Adjusts the maximum value the ADSR can adjust by and the inclusiveness of the IRQ addressing.
ADSR can adjust by 0x4000 per tick, not 0x3fff as we had it clamped to before, this was incorrect, causing Spyro Enter the Dragonfly to hang.
IRQ addressing was including the end address when testing if an IRQ should fire, however the end address isn't read, so it doesn't make much sense that it would trigger it, plus it was causing Fatal Frame/Project Zero 2 speech not to work correctly. Limited testing has shown it wouldn't trigger.
Test Spyro - Enter the Dragonfly and Fatal Frame/Project Zero 2, plus a bunch of other games which are sensitive to SPU2 stuff in the past https://github.com/PCSX2/pcsx2/issues?q=is%3Aissue+sort%3Aupdated-desc+spu2+is%3Aclosed+label%3ASPU2
Thanks to Goatman13 and …

SPU2: Small tweaks to ADSR and IRQ address triggers

---

pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

Prevents older GPUs with newer extensions (most common on Linux) from failing to run due to us making GLSL 430 shaders
Fixes #8661
Compatibility with old GPUs
@vetework please

GS:OGL: Support vs expand on older GL with SSBO extension

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Not sources. They already have AEM resolved.
Closes #8640.
Before:
After:
Weirdly... also seems to fix the post-processing in Shrek 2...
Test dump/texture in linked issue (already done).
Unfortunately this seemed to have almost every bloody dump in the collection show up as a diff. But I went through them and the only one with any noticeable difference was Shrek 2 above.

GS/HW: Only force shader sampling for non-32bit targets

---

pcsx2/GS/GSDrawingContext.h
pcsx2/GS/GSState.cpp

~~My **guess** is that the drawing environment registers get left alone, and only the privileged registers are reset.~~
See the notes in the diff/source.
```
// Basically, GOW does a 32x448 draw after resetting the GS, thinking the PSM for the framebuffer is going to be set to C24,
// therefore the alpha bits get left alone. Because of the reset, in PCSX2, it ends up as C32, and the TC gets confused,
// leading to a later texture load using this render target instead of local memory. It's a problem because the game uploads
// texture data on startup to the beginning of VRAM, and never overwrites it.
//
// In the software renderer, if we let the draw happen, it gets scissored to 1x1 (because the scissor is inclusive of the
// upper bounds). This doesn't seem to destroy the chest texture, …
```

GS/HW: Skip draws on reset until scissor is set

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

This was causing validation errors, and could possibly make a GPU/driver crash.
@refractionpcsx2 I didn't think enough to say whether we _should_ be trying to preserve some of the depth bits here, but if so, we'd need a separate shader.
This is an invalid draw.
Test GT4 (this is where I saw it).

GS/HW: Don't attempt to colour copy into depth target

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/GSVector4i.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/Common/GSVertexTrace.cpp
pcsx2/GS/Renderers/Common/GSVertexTrace.h
pcsx2/GS/Renderers/Common/GSVertexTraceFMM.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
pcsx2/GS/Renderers/SW/GSDrawScanline.h
pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.cpp
pcsx2/GS/Renderers/SW/GSRasterizer.cpp
pcsx2/GS/Renderers/SW/GSRasterizer.h
pcsx2/GS/Renderers/SW/GSRendererSW.cpp
pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Most draws don't come close to 65535 vertices.
Save some bandwidth.
Make sure all renderers work. Dump run says it's okay.

GS: Use 16-bit indices instead of 32-bit

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Happened with odd-sized textures in Shrek 2.
Out of bounds crashing the driver/GPU are bad.
Test Shrek 2.

GS/HW: Ensure region texture mipmaps don't go out of bounds

---

bin/resources/shaders/opengl/tfx_vgs.glsl
bin/resources/shaders/vulkan/tfx.glsl
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp

Only exists in GLSL.
Just in case the compiler doesn't make this transformation.
Try VK/GL.

GS/HW: Use bitfield extract for VS expand (GL/VK)

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Apparently some stages use a sky height of 128 instead of 256?
Closes #8665.
Test Burnout 3 and Black.

GS/HW: Adjust Black/Burnout sky CRC hack

---

pcsx2/Vif1_Dma.cpp
pcsx2/Vif_Codes.cpp

Fixes VIF1 stall behaviour when InstantDMA is enabled.
It was getting in to infinite loops when used with Metal Gear Solid 3
Test MGS3 and other games with InstantDMA enabled (check the gamedb if you're unsure)

Vif: Fix up Instant DMA behaviour

---

bin/resources/GameIndex.yaml

- Made names of Armored Core games uniform.
- Add CPU Sprite Render Size to bunch of Armored Core games for fixing #2397
- Makes easy to look for Armored Core games in GameIndex.yaml
- Fixes #2397
- Only for Last Raven, this change causes z-fighting on some shadow rendering.
I'm not sure.

GameDB: Fix Armored Core water and game names

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp

Changed Recommended Value to Checked for Show Indicators.
Just for consistency. It is checked by default, but Recommended Value is left Unchecked.
I'm not sure

Qt: Correct Recommended Value for Show Indicators

---

pcsx2/x86/microVU_IR.h

Make sure to back up the VI register being used before copying a new value in to it.
If writeReg wasn't currently cached, but the loadReg was cached, it's likely that they weren't the same reg, however there was no path where the current value of writeReg was being backed up for immediately following branches. This caused SPS in World Rally Championship.
Test games generally, but also if you know games which have problems with VU JIT but not int (or the old SuperVU), it may affect them.
World Rally Championship:
Master:
PR:

VU-JIT: Backup non cached VI before writing to it when load != write

---

bin/resources/GameIndex.yaml

Add patch for Michigan: Report from Hell.
Fixes falling through the floor in library.
Fixes https://github.com/PCSX2/pcsx2/issues/6821 .
Test game affected by patch.
Note: JPN region don't need that patch, game wait properly at interlock before reading vf30.

GameDB: Add patch for Michigan: Report from Hell.

---

pcsx2/x86/microVU_IR.h

Avoids a situation where we can find the loadReg when allocating a GPR then the writeReg stealing it.
The above was happening then it was overwriting the value when it needed to backup the VI register. This broke Gauntlet and Star Wars Episode 3
Test above mentioned games and WRC 4 (I've already done this but you're welcome to try that + others)

VU-JIT: Avoid writeReg stealing loadReg GPR

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Significantly reduces render passes in Sly 2 (~2,000 to 700 in the intro).
Vroom vroom.
Test performance changes in a few games, including Sly 2.

GS/HW: Avoid render pass restarts to turn off RT

---

pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp
pcsx2/Frontend/FullscreenUI.cpp

Forgot about the bigscreen mode for #8653. Adding now.
Parity between Qt and FullscreenUI.
No FullscreenUI SDL Raw option on mac and linux builds.

FullscreenUI: Only show SDL Raw on win32 builds.

---

pcsx2/DebugTools/DebugInterface.cpp
pcsx2/DebugTools/DebugInterface.h
pcsx2/DebugTools/MIPSAnalyst.cpp
pcsx2/R5900OpcodeTables.cpp
pcsx2/R5900OpcodeTables.h

Implements the proper opcode flags for BC0**ₓᵧ** instructions
Implements the condition evaluation required for these instructions (COP0COND)
Fixes #8697
Test BC0**ₓᵧ** instructions in the debugger
Also do a pass through on other instructions. The instruction flag mask for branches was changed from 3 bits to 4.
I don't see any instances of this 4th bit being used elsewhere, but it's best to be safe.

Debugger: Implement BC0XY branches & their condition evaluation

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Expands RT's which overlap the source based on the rect size not the dirty size
This wasn't correctly expanding the source when a target is used but is smaller than the requested size. This was evident in Final Fantasy X-2 if you went in to the menu and config, then back out.
Test games, FFX-2 (press triangle then config, then back out), and just random stuff, make sure VRAM doesn't explode etc.
Fixes #8643

GS-TC: Use the expected rect to expand the target when Tex is RT.

---

pcsx2/CMakeLists.txt

Don't claim a build succeeded if it actually failed
Avoid accidentally publishing broken stuff
See if the build fails while our qt 6.5.0 is still broken
Edit: Build failed successfully, yay!  Now to get qt 6.5.0 fixed...

CMake: Properly fail on windeployqt failure

---

common/Vulkan/Context.cpp
common/Vulkan/Context.h
common/Vulkan/SwapChain.cpp
pcsx2-gsrunner/Main.cpp
pcsx2-qt/MainWindow.cpp
pcsx2-qt/MainWindow.h
pcsx2-qt/QtHost.cpp
pcsx2-qt/QtHost.h
pcsx2/GS/GS.cpp
pcsx2/GS/GS.h
pcsx2/GS/Renderers/Common/GSDevice.cpp
pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX11/D3D.cpp
pcsx2/GS/Renderers/DX11/D3D.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.h
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
tests/ctest/core/StubHost.cpp

Hopefully for the last time?
To switch out of fullscreen when displaying a popup, or not to?
For Windows, with driver's direct scanout, what renders behind tends to be hit and miss.
We can't draw anything over exclusive fullscreen, so get out of it in that case.
Wayland's a pain as usual, we need to recreate the window, which means there'll be a brief period when there's no window, and Qt might shut us down. So avoid it there.
On MacOS, it forces a workspace switch, which is kinda jarring.
Refactors GS startup to present a blank frame as soon as possible. That way the grey screen instead of the game list getting left over isn't displayed for as long.
Closes #8709.
Closes #8704.
Hammer the heck out of fullscreen in DX11 and 12, GL or Vulkan.

GS: Refactor exclusive fullscreen yet again

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Docs/gamedb-schema.json
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GameDatabase.cpp
pcsx2/Pcsx2Config.cpp

God of War (2) explicitly flushes the GS's texture cache when drawing the trails of red things, whatever they are. This causes up to 500 texture copies, which gets pretty slow, especially on GPUs like M1.
So, let's add a new level to autoflush - only apply it to sprites. This cuts the copies (and draws) down to approximately 10-ish, without needing to disable auto flush. It's potentially beneficial to other games too, but I haven't looked at any aside from GTA:SA and GOW.
Vroom vroom
Test a few autoflush games, make sure I didn't break it. Test GOW/2 to make sure it looks correct.

GS/HW: Allow auto flush to be applied only to sprites

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fixes the comparator for std::sort when purging the hash cache
It wasn't passing back correct values before (should be true/false). Black FMV's were crashing on linux because it couldn't handle it, windows just YOLO'd it.
Test Black works on linux, check other games don't explode hash cache.

GS-HW: Fix std::sort comparator for purging hash cache

---

pcsx2/GS/Renderers/Common/GSDevice.h
pcsx2/GS/Renderers/DX12/GSDevice12.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
pcsx2/ShaderCacheVersion.h

Programs/pipelines were duplicating due to padding bits, most noticeable in OpenGL.
Regression from #8613.
@JordanTheToaster knows what to do.

GS/HW: Fix pipeline/shader duplication

---

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

I don't trust drivers to insert a barrier here. At least one of them gets it wrong.
Also moves the masking of depth/colour to the common renderer for consistency.
Less potential for breakage.
Check a couple of games render correctly with OpenGL and Vulkan. Runner seems okay.

GS/OGL: Don't reuse targets when they're the texture

---

.github/labeler.yml

They changed when we moved to QT

ci: Update labeler debugger directories

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Tokyo Xtreme Racer Zero does C32 moves from previously-rendered-as Z32 targets, but with one of them being C32 because it cleared it..
DBZ BT3 PAL offsets its shuffle position by 8 without pushing the texture coordinates out, which failed the current size check. The upper Y bound of the coordinates are also -0.5 what they should be.
Closes #8694.
Closes #8691.
Check affected games. Runner says everything else seems to be okay.

GS/HW: Texture cache regression fixes

---

bin/resources/GameIndex.yaml

Fixes for broken textures on player model.
Master:
PR:
CI happy.

GameDB: FFXII texture fixes

---

common/Perf.cpp
common/Perf.h
pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp
pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp
pcsx2/VirtualMemory.cpp
pcsx2/VirtualMemory.h
pcsx2/x86/iR3000A.cpp
pcsx2/x86/ix86-32/iR5900-32.cpp
pcsx2/x86/ix86-32/recVTLB.cpp
pcsx2/x86/microVU.cpp
pcsx2/x86/microVU_Compile.inl
pcsx2/x86/microVU_Execute.inl
pcsx2/x86/newVif_Dynarec.cpp
pcsx2/x86/newVif_UnpackSSE.cpp

Jitdump lets us annotate blocks, extending sampling to individual instructions.
To use:
```
$ perf record -p $(pidof pcsx2-qt) -k mono # optionally -F max or a different sampling frequency
.. CTRL+C to stop
$ perf inject --jit -i perf.data -o perf.data.inject # this will create tons of .so files, one for each block
$ perf report -i perf.data.inject -Mintel # because AT&T syntax is awful
```
To remove said .so files, you'll find it'll probably exceed the command line limit of your shell. So use find instead:
```
find . -name '*.so' -delete
```
Improving profiling PCSX2.
Make sure Windows/Linux builds still boot games. The code is ifdef'ed out, so it shouldn't have any effect.

Perf: Support instruction-level profiling with jitdump on Linux

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

My Intel A750 GPU apparently doesn't support `VK_KHR_fragment_shader_barycentric`, and since we removed geometry shaders completely, resulted in primid not being enabled.
Which lead GT4 to issue thousands of barriers, for DATE.
Based on what I read from Tellow's notes, it seems the combination of older GPUs and drivers is broken on Macs? So I left the barycentric extension intact, but only for MacOS.
Fixes GT4 struggling even at 1x on Arc.
I've tested it fixes the issue. Don't think anyone else has an Arc GPU :-)

GS/Vulkan: Make primid not require barycentric extension

---

pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

GT4 clears the entirety of GS memory shortly after startup with a 1024x1024 draw, but it's split over several sprites, so the current detection doesn't pick it up.
Same with its framebuffer clears. So let's detect it and handle accordingly.
Also makes the blur effect in Midnight Club 3 not so overly exaggerated. Obviously it's still semi-broken, because it's page offset evilness, but if you compared it to software, it was much more obvious than it should have been.. because it was loading garbage from local memory which should've been cleared.
Stops the target size and VRAM usage blowing out.
Check GT4 VRAM usage.  @JordanTheToaster knows how to reproduce it.
Test Splinter Cell Double Agent. It showed up in the runner, but only on frame 1, so might just be a false positive.

GS/HW: Detect clears spanning multiple sprites

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Fix a crash in MGS2
@stenzek I'm not sure if letting it through like this is the correct thing to do.  The call stack is
https://github.com/PCSX2/pcsx2/blob/aa9a0dca4bc81f0addcc9b544c53eb55e7ae2a47/pcsx2/GS/Renderers/HW/GSTextureCache.cpp#L1076
https://github.com/PCSX2/pcsx2/blob/aa9a0dca4bc81f0addcc9b544c53eb55e7ae2a47/pcsx2/GS/Renderers/HW/GSTextureCache.cpp#L553-L554
Can you confirm/deny if this is the right way to handle it?
Edit: I was being dumb, I can just pass the clut info in from the depth lookup function too
Less crash yay
Test [this GSdump](https://tellowkrinkle.com/dl/MGS2Crash.gs.xz) (warning: 92MB compressed, 2GB uncompressed)

GS: Fix crash when looking up color textures with depth lookups

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

Fixes a crash when quitting right after starting (much easier to hit if you use the interpreter)
Not crashing is good
Normal testing

GS:MTL: Always end all encoders on FlushEncoders

---

pcsx2/SaveState.h
pcsx2/VU.h
pcsx2/VU0microInterp.cpp
pcsx2/VUmicroMem.cpp
pcsx2/x86/microVU.h
pcsx2/x86/microVU_Compile.inl
pcsx2/x86/microVU_Execute.inl
pcsx2/x86/microVU_IR.h
pcsx2/x86/microVU_Misc.inl

The VF cycle count doesn't go above 4, across 32 registers that saves 64 bytes.
Also gets rid of blockhasmbit, since save states are getting invalidated anyway, it was never used.
I assume that the cycles for the VF registers can't go above 15 (really, 4), since only the FMAC instructions write to them. AFAICT, this should be fine, the only longer instructions are in the EFU, and those write to P/Q, not to the VFs.
vroom vroom
Test some VU heavy games, make sure nothing broke.

x86/microVU: Pack VF cycles into bitfields 

---

pcsx2/x86/microVU.h

Doesn't actually affect anything, only for debugging.

x86/microVU: Fix typo in VI CRC

---

.github/workflows/scripts/linux/appimage-qt.sh
cmake/BuildParameters.cmake
common/CMakeLists.txt
common/Linux/LnxMisc.cpp

Changed the screen saver inhibiting method from calling an external program "xdg-screensaver" to using DBus. 
DBus is used in most desktop environments to handle the screen saver, among other things, regardless of display server type(X11 or Wayland).
Make sure the screensaver is suspended after starting the emulation without any input.
An easy way of testing without waiting it is running `dbus-monitor --session | grep -e Session -e Screen -e login` in a separate terminal and seeing the output, the output could be slightly different for each desktop so I couldn't put a specific enough string in the grep command.
well for gnome `dbus-monitor --session | grep -e member=InhibitorAdded -e member=InhibitorRemoved` is specific and will get you the screen saver inhibitor status without any …

Linux: implement DBus screensaver inhibitor

---

bin/resources/shaders/opengl/cas.glsl
bin/resources/shaders/opengl/convert.glsl
bin/resources/shaders/opengl/merge.glsl
bin/resources/shaders/opengl/present.glsl
bin/resources/shaders/opengl/shadeboost.glsl
bin/resources/shaders/opengl/tfx_fs.glsl
bin/resources/shaders/opengl/tfx_vgs.glsl
pcsx2/pcsx2core.vcxproj
pcsx2/pcsx2core.vcxproj.filters

Less aggressive version of #8648
Our GLSL shaders have a lot of nested ifdefs which are incredibly confusing with the default clang-format formatting
Test OpenGL things

GS:OGL:Shaders: Formatting

---

pcsx2-qt/Debugger/Models/BreakpointModel.cpp
pcsx2/Interpreter.cpp
pcsx2/x86/iR3000A.cpp
pcsx2/x86/ix86-32/iR5900-32.cpp

Fixes memory checks for both the IOP and EE recompiler when n > 1 and one or more **only** log.
This would cause an issue where the first memory check would log, then the second would trigger because the opcode target address and size would be clobbered. 
Fixes a warning when breakpoints or memory checks are added. The insert logic was incorrect and didn't account for multi-thread latency. (This had no known side effect besides the runtime warning)
Fixes EE interpreter breakpoints and memory checks. I assume the exception changes that have happened lately were the cause of this. In essence; there was an uncaught exception being thrown.
This would cause a SIGTERM and crash.
I ask that @stenzek verify that calling `Cpu->ExitExecution();` in that context is the correct approach.
Test memory …

Debugger: Fix a few breakpoint and memorycheck issues

---

pcsx2/x86/newVif.h
pcsx2/x86/newVif_Dynarec.cpp
pcsx2/x86/newVif_UnpackSSE.cpp
pcsx2/x86/newVif_UnpackSSE.h

Gets rid of some pointless function abstraction, hangover from having SSE2. Also use mVU functions for copying if some target vectors are protected.
Cleaner more optimal code, very marginally faster in games protecting vectors during VIF unpacks, GT4 comparison below shows a marginal improvement when MTVU is off.
Test a few games, make sure nothing is broke, should be fine, tested a few myself.
GT4 example, ran each one twice to make sure the results were mostly consistent

VIF-JIT: Clean up pointless code, optimise protected vector copies

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp

Ignore draws using DATE when detecting clears.
DATE should never be a component of clears, and was causing misdetection of double half clears in Xenosaga 2.
Test Xenosaga 2 (maybe 3 also?) make sure it doesn't cause seizures anymore.

GS-HW: Avoid clear misdetection with DATE enabled

---

common/Vulkan/Context.cpp
common/Vulkan/Context.h
common/Vulkan/SwapChain.cpp
common/Vulkan/SwapChain.h
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/Pcsx2Config.cpp

I don't really care about the HDR implications of this, but it is slightly annoying not being able to see the volume overlay, or the dropped frames when toggling fast forward with vsync on with driver-controlled exclusive fullscreen.
This gives you the option to specifically allow/disallow exclusive fullscreen on supporting drivers. It is only a **hint** to the driver, nothing is guaranteed. If you want full control over exclusive fullscreen, your only option is to use DirectX.
Aforementioned annoyances, and it's relatively small code-wise, unlike adding full application exclusive control, which imo is pretty pointless when you can't switch mode.
Test new option. A good way is with the vsync example above, which should flicker, even with MPO supporting systems, since it recreates the swap …

GS/Vulkan: Add exclusive fullscreen control option

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Xenosaga 3 has tex-in-RT, offsetting a source from a larger target, but the invalidation kills the target but not the source otherwise. Which means if it got used, we'd go boom.
Also fixes m_from_target_TEX0 being tested when it might not be valid.
Memclear was wiping out local memory, which just got the FMV written into it, by the letterbox draw.
I broke them.
Test Xenosaga 3, all FMVs should show on new game.
The source asset only trips in devbuilds, but I've checked myself that it no longer does.

GS/HW: Fix regressions in Xenosaga III

---

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

GS:MTL: Extend render pass restart avoidance code to depth-only passes
Previously only worked when the depth texture was removed, but not when the color texture was removed.
Ported from VK/D3D12.
Fixes #8781
Test #8781

GS:MTL: Extend render pass restart avoidance code to depth-only passes

---

pcsx2/x86/newVif_Dynarec.cpp
pcsx2/x86/newVif_UnpackSSE.cpp
pcsx2/x86/newVif_UnpackSSE.h

Improved detection of when rows/cols/write protect are used instead of input data, reducing codegen of the VIF JIT
potentially more brr in some places, but not much.
Test games, if it says "Skipping stuff!" in the console, it's hit the new code. Tested Kingdom Hearts 2, Tales of Legendia and Gran Turismo 4 already (the latter two hit it)

VIF: Improve IR setup for skipped unpack inputs/writes

---

common/Linux/LnxMisc.cpp
pcsx2/x86/newVif_Dynarec.cpp

also minor misc cleanup
Now on a certain assertion error, it will return with:
"Vpu/Vif - Invalid Unpack! [11]" or `[3]` or `[7]`
instead of:
"Vpu/Vif - Invalid Unpack! [%d]"
Correct behavior is better.
You can test those packages (once they build) :
[Windows test build](https://github.com/CharlesThobe/pcsx2/actions/runs/4877302358)
[Linux test build](https://github.com/CharlesThobe/pcsx2/actions/runs/4877302355)
[MacOS test build](https://github.com/CharlesThobe/pcsx2/actions/runs/4877302357)
1- Start the VM.
2- The error should appear just like the format above.

VIF: Fix assertion error not returning int value.

---

bin/resources/GameIndex.yaml

Mitigates bloom misalignment when upscaling Secret Agent Clank, and applies its NTSC-U 4-star compatibility rating to the PAL versions.
Aligned bloom is better than misaligned bloom, easily noticeable around the player and the top-right lights in the below screenshots. The PAL-M12 version runs fine for me across the whole game, and the NTSC-U version already had a 4-star rating, so I unified the PAL ratings in the process.
|Before, 4x resolution|After, 4x resolution|
|-|-|
|![image](https://user-images.githubusercontent.com/14360666/236320857-18aadf6e-66b1-4e57-bb82-6f1b2ebf845c.png)|![image](https://user-images.githubusercontent.com/14360666/236320893-66a0b645-a964-4a01-8399-1913725ad18e.png)|
Make sure that Secret Agent CI is happy.

GameDB: Secret Agent Clank compat and bloom fix

---

bin/resources/GameIndex.yaml

Fixes for broken window and shadow rendering headlight brightness and overbightness in hardware mode.
Master:
PR:
Fixes #7673 
Brightness is bad for your eyes.

GameDB: Juiced 1 Fixes

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Only updates dirty areas of texture  if the BP's match, otherwise ignore it.
This was causing false positives, updating incorrect targets, which then corrupted targets. This was a regression from #8745 
idk, test Dragon Quest 8, Spongebob Squarepants - The Movie, and Dark Cloud I guess!
Dark Cloud:
Master:
PR:
Spongebob:
Master:
PR:
Dragon Quest 8:
Master:
PR:

GS: Only update dirty on local invalidate if bp matches

---

common/Perf.cpp
pcsx2/GS/Renderers/Common/GSFunctionMap.h

The missing const_cast caused an error.
Things wouldn't compile for me on Linux without it.
Test VTune JIT profiling

Profiling: Fix missing cast and remove redundant SW-JIT profiling code

---

bin/resources/GameIndex.yaml

Fixes text in state of emergency 2
It got broked somewhere.
watch cI
Before:
After:

GameDB: Add text fix for State of Emergency 2

---

pcsx2/GS/GS.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm

GS: Replace EmuConfig.GS with GSConfig.
EmuConfig isn't safe to run on the gs thread.
Better to use GSConfig.
Changed configs still work.

GS: Replace EmuConfig.GS with GSConfig.

---

bin/resources/GameIndex.yaml

Remove patches that are no longer required.
Why IOP patches were there: https://www.patreon.com/posts/sins-of-ps2-2001-42262496
Why EE patch is still there: https://www.patreon.com/posts/sins-of-ps2-dead-33513267
Fixed in https://github.com/PCSX2/pcsx2/pull/3778
Test games affected by PR.

GameDB: Remove DOA2 iop patches.

---

bin/resources/GameIndex.yaml
pcsx2/GS/GS.natvis
pcsx2/GS/GSCrc.cpp
pcsx2/GS/GSCrc.h
pcsx2/GS/GSState.cpp
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Some games, such as Tomb Raider: Underworld, and Destroy All Humans shift the texture pointer back behind the framebuffer, but then offset their texture coordinates to compensate. Why they do this, I have no idea... but it's usually only a page wide/high of an offset.
Thankfully, they also seem to set region clamp with the offset as well, so we can use that to find the target that they're expecting to read from. Example from Tomb Raider: TBP0 0xee0 with a TBW of 8, MINU/V of 64,32, which means 9 pages down, or 0x1000, which lines up with the main framebuffer.
~~Marked as a draft because the channel shuffle change breaks the GT4 hack. I need to think of another way to do it, probably as an OI hack instead.~~
Closes #8270.
Before:
After:
Before:
After:
Test Tomb Raider games. I noticed an …

GS/HW: Fix post processing in Tomb Raider games

---

pcsx2/Sif.h
pcsx2/Sif0.cpp

Fixes the SIF junk behaviour to accurately match what the PS2 console does.
To Save repeating myself here's the comment I made in the code.
If there is not enough data produced from the IOP, it will always use the previous full quad word to
fill in the missing data.
One thing to note, when the IOP transfers the EE tag, it transfers a whole QW of data, which will include
the EE Tag and the next IOP tag, since the EE reads 1QW of data for DMA tags.
So the data used will be as follows:
Less than 1QW = Junk data is made up of the EE tag + address (64 bits) and the following IOP tag (64 bits).
More than 1QW = Junk data is made up of the last complete QW of data that was transferred in this packet.
Data is always offset in to the junk by the amount the IOP actually transferred, so if it sent 2 …

SIF: Correct junk data behaviour. Fixes True Crime Streets of LA

---

bin/resources/GameIndex.yaml
pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/Frontend/FullscreenUI.cpp
pcsx2/Frontend/ImGuiOverlays.cpp
pcsx2/GS/GS.cpp
pcsx2/GS/GSState.cpp
pcsx2/GS/GSUtil.cpp
pcsx2/GS/GSUtil.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h
pcsx2/Pcsx2Config.cpp
pcsx2/VMManager.cpp

Replace it with a boolean "Disable Render Fixes" option.
Most of them didn't do anything, and the aggressive CRC hacks are not needed anymore.
GSC_AceCombat4 - couldn't get this to trigger.
GSC_FFXGames - dunno what this did, but FFX has been fine for some time.
GSC_Okami - breaks a bunch of the game's effects, downsample is intentional.
GSC_RedDeadRevolver - working as intended, patch on forums.
GSC_ShinOnimusha - breaks effects, only saves 5-10% GPU at 8x.
GSC_XenosagaE3 - breaks cutscenes, minimal perf difference.
Freeing up a row so the settings dialog isn't so large.
Helping reduce the perception that PCSX2 is "full of hacks".
Make sure option breaks games which need render fixes.

GS: Remove CRC hack levels

---

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
pcsx2-qt/Settings/GraphicsSettingsWidget.ui
pcsx2/Config.h
pcsx2/GS/Renderers/DX11/GSDevice11.cpp
pcsx2/GS/Renderers/DX11/GSDevice11.h
pcsx2/GS/Renderers/DX12/GSDevice12.cpp
pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/VKContext.h
pcsx2/Pcsx2Config.cpp

And automatically disable it on Fermi (buggy driver).
Better than rendering garbage.
Make sure renderers still work.

GS: Add option to disable vertex shader expand

---

pcsx2/USB/usb-lightgun/guncon2.cpp

Apparently reduces input lag, I guess the game has its own timer based on how long it takes the GunCon to report no position detected.
Credit to @pcnimdock for debugging.
Closes #7803.
Make sure GunCon2 still works (I've checked TC2/3).

USB/GunCon2: Adjust calibration timer

---

bin/resources/GameIndex.yaml

Game does 640x1232 draws to clear out most (but not all) of GS memory, then 224 high draws to 1216 high targets, presumably moving GS memory around. TME is enabled, I don't want to try to HLE this mess.
Enabling SW FMV render isn't needed for the FMV, it's just a convenient way to remove these targets from the TC, as the clearing/copying mess happens before the FMVs play.
Closes #8772.
Test affected game (done with the supplied blockdump).

GameDB: Add SW FMV render to Poinie's Poin

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Ace Combat 04 reads RG, writes to RGBA by setting a MINU of 1015.
Fixes #1547.
Fixes #1739.
Fixes #1861.
Fixes #6626.
(clouds need CPU CLUT off, breaks them for some reason..)
Test AC games.

GS/HW: Handle texture shuffles using region repeat (Ace Combat Series)

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Check if this write/draw covers the entire target, and erase it early if so.
No point keeping targets which are fully dirtied around.
Making the target list a bit smaller.
Check games sensitive to invalidation which also use tex-in-rt.
I haven't done a runner pass yet.

GS/HW: Remove targets when invalidate area covers valid area

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSState.h
pcsx2/GS/Renderers/SW/GSRendererSW.cpp

Fix the large PCRTC offsets used by NASCAR games. Also force deinterlacing mode to Adaptive TTF, due to misdetection of games own deinterlacing.
Epilepsy is bad.
Already tested, just make sure CI passes

GS-HW: Fix annoying NASCAR offsets in PCRTC using HW mode

---

pcsx2-qt/GameList/GameListWidget.cpp
pcsx2-qt/MainWindow.cpp
pcsx2/Frontend/FullscreenUI.cpp

Adds ability to scan and open .mdf (Media Descriptor Format, aka Alcohol 120%) files
PCSX2 can open .mdf files, always has been able to, but Qt didn't look for these extentions so any games in this format were missing from the list.
if you have an .mdf image, see if it appears in your game list (have already tested this)

UI: Add ability to list .mdf files

---

pcsx2-qt/Settings/AdvancedSettingsWidget.cpp
pcsx2-qt/Settings/AdvancedSettingsWidget.ui
pcsx2/CommonHost.cpp
pcsx2/CommonHost.h
pcsx2/Config.h
pcsx2/Elfheader.cpp
pcsx2/Elfheader.h
pcsx2/PINE.cpp
pcsx2/PINE.h
pcsx2/Pcsx2Config.cpp

Since the death of wx, PCSX2 has been without PINE. I've now done my best to make it work again.
I've replaced the old threading with std::thread, and done some changes to prevent heap corruption.
There are also some minor changes made like moving the allocation of the static buffers to the constructor instead of leaving that to the worker thread.
And of course the GUI:
There is one minor thing I couldn't figure out a good way of doing though. PINE is supposed to start on emulator startup, but the only ways I found to achieve this had one of two issues:
1. The config hadn't loaded yet
2. It reloaded PINE on every config change, causing lots of servers spawning when editing the slot one digit at a time
PINE good.
Test the GUI and test PINE I suppose. I've tested PINE on windows, but not on …

PINE: Update to the age of Qt

---

pcsx2/CDVD/CDVD.cpp
pcsx2/VMManager.cpp
pcsx2/VMManager.h

Reloads disc information when a disc swap occurs
Some people were asking for it so they could see what disc they were on (and discord rich presence ofc).
Also if you do a savestate after swapping disc, it wouldn't let you reload it unless you restart the game.
Funny side effect on Monster Rancher 4 when using Saucer Discs is that it will show the name for the game you insert if there are any, but it shouldn't load any new patches, but it will load gamefixes which might cause it to crash, but it's the best I could do.  However if a game requires a patch, you won't be able to load it with codebreaker, I'm sorry but I can't risk loading patches, it could completely break games like Monster Rancher.
Test games with disc swaps and make sure the name etc changes and savestates are related to …

CDVD: Reload game data when swapping discs to reflect new name.

---

pcsx2/pcsx2.vcxproj

Quick fix so we don't blow up CI build sizes until I finish cleaning up the msbuild props...

MSBuild: Fix lib/pdb output directory

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Unfortunately because we're HLE'ing split RGB shuffles into one, and the draws themselves vary a lot, we can't predetermine a skip number, and because the game changes the CBP, we that's going to break us in the middle off the shuffle... So, just track it ourselves.
Regression from #8780.
Test GT4.

GS/HW: Fix GT4 render hack

---

pcsx2/SPU2/ADSR.cpp
pcsx2/SPU2/Mixer.cpp
pcsx2/SPU2/RegTable.cpp
pcsx2/SPU2/defs.h
pcsx2/SPU2/regs.h
pcsx2/SPU2/spu2.cpp
pcsx2/SPU2/spu2.h
pcsx2/SPU2/spu2freeze.cpp
pcsx2/SPU2/spu2sys.cpp
pcsx2/VMManager.cpp

Try to compute as much of it as possible at compile time.
Less indirection when reading registers/memory.
Make sure sound still works.

SPU2: Get rid of dynamic allocations

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Deletes fully dirtied old targets
Keeping around old targets is just asking for trouble, and it was causing trouble.
Just test a bunch of Texture Cache sensitive games.
Fixes corrupted lights in Syphon Filter Omega Strain

GS-TC: Delete fully dirtied old targets

---

pcsx2/x86/microVU_Branch.inl
pcsx2/x86/microVU_Compile.inl

Instead of emitting a copy of the pipeline state at the end of the block's code, we can simply reference back to the block itself.
This will reduce icache pressure ever-so-slightly, since the pipeline state is 96 bytes.
I don't expect this to make a measurable difference on its own, but all the tiny things do add up.
Ongoing performance work.
Check some games sensitive to M-bit, this previously wasn't using the fast copy routine. I _think_ I've done this correctly, but don't know which games hit this path.

x86/microVU: Reference StateEnd instead of inlining state

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Forces local mem invalidation to invalidate the whole RT when doing a local->local copy to itself on the CPU.
Also allow moves within the same RT/depth stencil to happen.
The game is doing local->local copies, usually from 192->512 to 0->384 on the X (moving the image left), line by line, This was causing things to get out of whack and the RT was ending up with the wrong data, causing glitches on the screen in Vampire Darkstalkers.
The HW copies of the same render target/depth stencil wasn't allowed before as it's a validation error, but it's fine with a temporary texture in the middle.  This saves a readback on Vampire Darkstalkers (about 30fps faster).
Test Vampire Darkstalkers and make sure it works fine.
Fixes #3481 
Master:  (Look in the top left)
PR:

GS-HW: Invalidate local mem for whole texture on local->local copy. Allow HW recursive moves.

---

bin/resources/GameIndex.yaml

Adds missing COP2 patches for COD Finest Hour regions
Also added mipmapping to reduce shimmering.
Patches seem to be the same for all regions, which is handy.  I'm pretty confident this is actually a bug in the original game design which they never caught, but to maintain accuracy this patch correct the timing.
Watch the CI

GameDB: Add missing COP2 patches for Call of Duty Finest Hour

---

bin/resources/GameIndex.yaml
pcsx2/GS/GSLocalMemory.cpp
pcsx2/GS/GSLocalMemory.h
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Attempts to avoid clearing targets which don't already exist
Before this would create errant targets, sometimes located in the middle of buffers (Armored Core 2), which would later cause misdetection when it actually required those addresses.  This was also causing some blowout of target sizes when it wasn't needed.
Test a whole bunch of games, and especially FMV's
Fixes #8645 Psychonauts weird top screen corruption
Fixes #6604 Front Mission 4 shadows
Fixes #8860 Armored Core 2 FMV flickering
Improves accuracy of Time Crisis 3 menu
Improves accuracy on Cricket 2002 camera view
Psychonauts:
Master:
PR:
Front Mission 4:
Master:
PR:
Cricket 2002:
Master:
PR:
Time Crisis 3: (Comapre the honeycomb effect at the bottom centre of the screen, more accurately matches software mode)
Master:
PR:

GS-HW: Avoid clears with new targets

---

pcsx2-gsrunner/Main.cpp
pcsx2-qt/QtHost.cpp
pcsx2/LogSink.cpp
pcsx2/LogSink.h

Wasn't getting flushed/closed on shutdown.
No logs makes figuring out which dumps do funky stuff kinda difficult.
Make sure file logging still works in Qt.

GSRunner: Fix log file writing

---

bin/resources/GameIndex.yaml

Fixes for Full mipmapping causing texture problems with Harrys face and lighting being wonky at lower than full blending.
Master:
PR:

GameDB: HP COS Fixes

---

bin/resources/GameIndex.yaml

GameDB: Add full mipmap with ps2 trilinear to 2002 FIFA World Cup.
Improves ground textures to match sw renderer.
Improves #5505, ground textures.
CI passes.

GameDB: Add full mipmap with ps2 trilinear to 2002 FIFA World Cup.

---

pcsx2/Achievements.cpp

Due to some reason I can't explain, our ISO filesystem code will read any ELF version suffix as ;1.
This was worked around for our main CDVD code here: https://github.com/pcsx2/pcsx2/commit/d36bb196126408068fbb1feb7f22cc5e0d7f6b1f,
but was not passed onto the Achievements ELF hashing code.
All this does is copy that workaround to the Achievements hashing routine.
Fixes #8889
The Achievements hashing code was looking for the 'correct' ELF file `SLUS_212.35;2` taken from `SYSTEM.CNF;1`.
This would cause it to fail.
Test games that have known ELF version suffixes that are **not** `;1`
[MLB 2K6](http://redump.org/disc/20905/) is one example.

Achievements: Implement the ELF suffix hack from CDVD when hashing

---

common/StringUtil.h
pcsx2/Patch.cpp
tests/ctest/common/string_util_tests.cpp

Enforces that the addresses/values in patches must be a hex literal, without the 0x prefix. Current patches don't have the prefix, so changing to decimal-except-if-prefixed behaviour (which is the "standard") would break existing patches, so this seems like the path of least resistance. Better than crashing games because patches try to write to NULL...
This also uncovered a bug in my StringUtil method, which is nice. So I added a unit test so it won't fail again :)
Closes #8893.
Make sure widescreen patches still work.

Patch: Discard patches with non-hex addresses/values

---

pcsx2/Patch.cpp

Fixes the parsing of `double` values in patches, also expand the log to give an example of how a hex string should be presented.
Double thing got broken by accident.
Log message was a bit ambiguous only saying "a hex number is expected" when 0x1234ABCD is provided, so I've expanded to to explain without any prefixes and gave an example to give the user clarity on their error.
Already tested, watch CI

Patches: Fix parsing of double words. Expand error log.

---

bin/resources/GameIndex.yaml

Added patches for the European and Japanese versions of Galerians: Ash to fix missing textures when using hardware rendering. 
A note on the authors I listed: US and European patches have been on the wiki for some time, but the GameDB only included the US patch, so I added the European patch from the wiki. The author of the US patch in the GameDB is "kozarovv", so I assume that that person also authored the European patch. However, the wiki edit that added the two patches was by user "Red Tv", so I'm not sure if they should be listed as well/instead. For the Japanese patch, I found the addresses myself by referencing the US patch, so I've given kozarovv credit on that one as well.
A significant amount of text in the game is unreadable without these patches.
Based on other GameDB PRs, it …

GameDB: Fix missing textures in Galerians: Ash

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h

Battlefield 2 clears the framebuffer by drawing rows of pages at a time. Try to collapse these into a single draw.
It still has other complete dickish stuff that needs more hacks, but this one's general and applicable to everything at least.
Mem clears were a bit slow, we can vectorize them for a ~6x speedup in C16 fills.
Vroom vroom.
Test The Suffering, shadow was doing weird stuff in the dump run, but manually running it seems fine..

GS/HW: Detect row/page-based split clears (and vectorize them)

---

pcsx2-qt/QtHost.cpp
pcsx2/MTVU.cpp
pcsx2/VMManager.h

Forces use of 2MB stacks for threads that may run µVU recompilers (macOS defaults to 512kb)
Fixes crashes in Garfield: Saving Arlene on macOS
Less crashy more runny
Test Garfield: Saving Arlene on macOS
Test other things

Core: Use 2MB stacks for µVU

---

common/CMakeLists.txt
common/Darwin/DarwinMisc.cpp
common/Darwin/DarwinMisc.h
pcsx2/VMManager.cpp

Add CPU count detection for macOS
Fixes #8585
So M1 users don't keep coming to us with performance issues because they have MTVU off
Note: cpuinfo prefers relying on cpuid over sysctl, which makes it misdetect M1s in Rosetta as 8 symmetric cores, so we're skipping cpuinfo on macOS.
Reset to default settings and see if MTVU is enabled

VMManager: MacOS CPU count detection

---

bin/resources/GameIndex.yaml

Fixes light alignment at native resolution to match software.
Fixes #8907 
Misalignment gross.

GameDB: Urban Chaos Light alignment fix

---

pcsx2/GS/GSGL.h
pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

Debug is too slow to actually run games.
The performance hit from the extra virtual calls is fairly minimal. Obviously we don't want it in Release, but Devel turns off inlining and other things which make a non-trivial difference, so what's another thing.
Saves me constantly applying this patch locally.
Make sure Release build performance is unaffected. Carbon's a good test.

GS: Enable API debug logging in Devel builds

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp

Tekken Tag Tournament, Star Ocean and probably other games put their font texture in the alpha channel of the framebuffer, then use P8H/P4HL/P4HH to pluck it out.
The problem is, they also set the texture size to 1024x1024, and don't use any region clamping. Hashing 1024x1024 **hurts**, since it has to expand the indices out, then hash a ton of data.
So, instead, use the partial preloading heuristics in this case. Partial invalidation works, but because the font part of the texture doesn't get invalidated, there's no texture uploads, no hashing, everyone wins.
Before:
After:
In devel:
- Star Ocean GS dump went from 364fps to over 2,200fps.
- TTT went from 139fps to 210fps.
Better solution than #8910.
Check affected games. I'm doing a dump run to see what else pops up..

GS/HW: Don't preload large framebuffer alpha textures

---

.github/ISSUE_TEMPLATE/app_bug_report.yaml
.github/ISSUE_TEMPLATE/emu_bug_report.yaml

Corrects spelling of appropriate
Adds text area for logs/dumps for the application template
Clarifies that dumps should be in a zip file
Improves templates
Read the text
Github can preview issues templates (as a beta feature), so you may be able to preview the template on my branch
[App template](https://github.com/PCSX2/pcsx2/blob/90ce710372c11bb5f0f4f288c9d0922ae32497a5/.github/ISSUE_TEMPLATE/app_bug_report.yaml)
[Emu template](https://github.com/PCSX2/pcsx2/blob/90ce710372c11bb5f0f4f288c9d0922ae32497a5/.github/ISSUE_TEMPLATE/emu_bug_report.yaml)

Github: Update issue template regardiing crash dumps

---

pcsx2/GS/GSState.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fix some resizing bugs when tex is RT and it needs to resize the target, and don't resize when shuffles are involved.
Also fix an annoyance with texture min/max calculation.
The resizing was resizing down if it was reading strips of an RT but growing in the other direction, but also we weren't resizing if the BP's matched. Also if it was a shuffle/recursive draw there's no need to resize the texture (this breaks 50 Cent)
The scenario in Texture Min/Max was that it was doing a bilinear draw, so we add -0.5/0.5 to the coordinates to make sure we get whole pixels, however if the min X and Y was 0 they ended up as -1 (because we do floor(-0.5) on them, basically), causing the border check to think it was wrapping when this isn't the case.
Just test an array of games, including the intro for …

GS-TC: Fix bugs with target resize and borders in texture min max

---

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h

And just set the render area to the full target every time.
Except colclip draws.
Some games render with changing viewports, and it throws the heuristics off. e.g. Transformers was doing over 2,000 render passes. Now down to 13.
It was mainly an optimization for when our target sizes were complete rubbish and always larger than needed. Since they're not anymore, the CPU overhead isn't worthwhile, and the "average" cases don't seem to take a performance hit.
Make sure performance in games which do many render passes is unaffected.

GS/Vulkan: Remove render area heuristics

---

pcsx2/IopMem.cpp
pcsx2/IopMem.h
pcsx2/Patch.cpp
pcsx2/Patch.h
pcsx2/vtlb.cpp
pcsx2/vtlb.h

Allows patching an arbitrary range of bytes, as opposed to a maximum of 8 via doubleword.
Example:
```
patch=1,EE,206211E8,bytes,0000010014000600
```
would write `00 00 01 00 14 00 06 00` to `0x206211E8`.
Makes logging a bit less confusing. Instead of printing out all patches when they're parsed (loaded), they're only printed when they're actually active.
Makes code patching a bit cleaner.
@CookiePLMonster do you have any other test cases? (preferably patching more than 8 bytes)

Patch: Add "bytes" type and improve logging

---

pcsx2/GS/Renderers/Metal/tfx.metal

Apparently the Catalina Intel UHD 630 backend compiler ICE's on use of the bool3 constructor over a float3... (Weirdly this happens on the Metal22 metallib compiled for 10.15 but not on the one compiled for 10.13... we do still want PrimID support if possible so I'd rather not remove it if I don't have to)
Fixes #8379
Less broken
Test the gsdump mentioned in #8379 on Catalina

GS:MTL: Fix ICE on macOS 10.15

---

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
pcsx2/GS/Renderers/HW/GSRendererHW.h
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h
pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp

GS/Vulkan: Colclip drawback shouldn't use DONT_CARE load:
- Regression from #8921.
GS/HW: Fix PrimitiveCoversWithoutGaps returning true with gaps
- Previously it only checked that all sprites matched in size, not that there wasn't actually any gaps between them.
- Needed for better clears to not break.
GS/HW: Black blending should preserve RGB, not A
- Self-explanatory. Stops mem clears writing back black instead of black plus some non-zero alpha (needed for memosaga)
GS/HW: Rename IsBlendedOrOpaque() to IsDiscardingDstColor()
- And remove the dst color output case, this is clearly wrong when we're using this to try to identify clears.
GS-HW: Only preload targets when data is needed
- Changes LookupTarget to only reload data if there are gaps in the draw, blending with Dst Colour or …

GS: Various fixes

---

pcsx2-qt/QtHost.cpp

Add the missing `-bigpicture` CLI parameter to the CLI help text.
Align output of the CLI `-help` command to the available parameters documented on the wiki to ensure that the parameters on the wiki are still valid: https://wiki.pcsx2.net/Command-line_support#General_Options_QT
Parameter should be listed when running `pcsx2-qt -help`.

Qt: Add missing bigpicture parameter to help text

---

pcsx2/CDVD/IsoFS/IsoFS.cpp

Whenever a version suffix that is **not** `;1` is come across, create an entry of the file _with_ `;1` as well.
For example
```
My.ISO/
├─ SLUS_1234;1
├─ DATA/
│  ├─ SOME_MUSIC;2
│  ├─ PICTURE_OF_CAT;4
│  ├─ PASSWORDS.TXT;1
```
Will be available as:
```
My.ISO/
├─ SLUS_1234;1
├─ DATA/
│  ├─ SOME_MUSIC;2
│  ├─ SOME_MUSIC;1
│  ├─ PICTURE_OF_CAT;4
│  ├─ PICTURE_OF_CAT;1
│  ├─ PASSWORDS.TXT;1
```
This is a happy medium so we can continue to behave like CDVDMAN (all files in `cdrom0:` are suffixed with `;1`) while allowing for the possibility of newer CDVDMAN modules, or homebrew modules to utilize this suffix format.
This also allows for the rare chance to support something that loads an ELF with a non-`;1` suffix with a supported CDVDMAN module.
This has an issue with a rare edge case where …

IsoFS: Create 'hard-links' for non-conforming version suffixes

---

pcsx2/Patch.cpp

Patches: Don't reload GameDB when crc is 0.
Bios uses crc 0, spams useless log that bios serial is not in the gamedb.
Bugfix.
CI builds, db isn't reloaded on bios.

Patches: Don't reload GameDB when crc is 0.

---

pcsx2-qt/QtHost.cpp
pcsx2/Patch.cpp
pcsx2/Patch.h
pcsx2/VMManager.cpp

In some cases (e.g. global cheat enable, global WS patches enable), the OSD message indicating how many patches were active was not getting shown.
Regression from my patch PR.
Test every combination of global/per-game/specific patch enabling and make sure the message displays, or doesn't display when appropriate.
Make sure message doesn't say "no patches loaded" when you reboot.

VMManager: Fix patches OSD not getting shown in some cases

---

pcsx2/USB/usb-pad/usb-pad-sdl-ff.cpp
pcsx2/USB/usb-pad/usb-pad-sdl-ff.h
pcsx2/USB/usb-pad/usb-pad.cpp

Makes some changes to fix some bugs and give SDL a better hint to what kind of directional feedback to give, lengthen time for FFB to run.
Before we were clamping to U16 on S16 registers, but also the feedback type was seemingly for controller pads rather than wheels.
I have also changed the initialisation to use a memset as described in the SDL documentation (also thanks to Stenzek for diagnosing this),  since doing `thing = {};` is fine on structs, etc, on Unions this will only initialise the first variable if it isn't the largest in the union, which is true in this case, this leaves the rest of the union completely uninitialized, which was then passing garbage to the SDL effect functions.
Check wheel supporting games like GT4, NFS (not sure which one), Enthusia etc.
Should improve GT4 …

USB: Improve FFB for steering wheels

---

pcsx2/Achievements.cpp
pcsx2/Patch.cpp

This PR fixes two minor issues with Achievements and Patches:
1. Patches and Cheats are now always listed in the UI, regardless of the Hardcore Mode state. This fixes an UI inconsistency where those lists would appear empty after booting the game in Hardcore and then leaving.
2. Achievements retain the Hardcore Mode state after toggling Test Mode or Rich Presence. This fixes a small exploit where switching those options on/off and then resetting would load user-supplied Patches (but not Cheats) on the next boot while in HC.
Exploits are bad.
1. Run the game in Hardcore Mode with at least one patch (for that game) in the `patches` directory.
2. Toggle Test Mode on and off, then Reset.
3. Observe that the patch does **not** load.

Minor fixes for Achievements and Patches

---

pcsx2/DEV9/smap.cpp

Swaps locks around on DEV9 reset to avoid potential deadlock.
Deadlocking is bad, y'all
Make sure PCSX2 doesn't hang starting a game with HDD support, or online support.

DEV9: swap unlocks to avoid potential deadlock

---

bin/resources/shaders/dx11/present.fx
bin/resources/shaders/opengl/present.glsl
bin/resources/shaders/vulkan/present.glsl
pcsx2/GS/Renderers/Vulkan/VKSwapChain.cpp

Stops the validation layer complaining.
Other commit also fixes another validation layer error - it wasn't a real issue, since the padding never gets read, but nonetheless it's better to be correct.
Validation layer reports are there for a good reason.
Make sure exclusive fullscreen control still works (i.e. allowed -> volume overlay is not visible).

GS/Vulkan: Add missing chain to exclusive fullscreen control

---

bin/resources/GameIndex.yaml

Added gsHWFixes for the Asian versions.
PAL and NTSC-U version had these fixes already but NTSC-J didn't.
N/A

GameDB: Added fixes for Crash Bandicoot 5

---

pcsx2/Docs/PCSX2_FAQ.md

It used to link to the website wiki which had outdated instructions for windows. Now all the links go to the GitHub wiki and I also included MacOS. This should make building on your target OS easier to find.

docs: update build guide URLs

---

pcsx2/GS/GSState.cpp

Skips using the Autoflush optmisation when TEXFLUSH is pending.
This with the combination of not flushing on tex flush, a previous optimisation from #8723 and skipping checks on odd numbers of verticals (which was an optimisation made a while back), this meant that flushes which needed to be done didn't happen, and as a result the shadows in Jak & Daxter (although only on software for some reason) broke.  This fixes it.
Check Jak & Daxter games in software mode, make sure the shadows are fine.
@stenzek can you check this doesn't make things explode from TEXFLUSH again? Thanks :D
Jak 3:
Master:
PR:

GS: Skip autoflush optimisation when pending texflush

---

.github/workflows/linux_build_flatpak.yml
.github/workflows/linux_build_matrix.yml
.github/workflows/linux_build_qt.yml
.github/workflows/release_pipeline.yml
.github/workflows/scripts/common/name-artifacts.sh
.github/workflows/scripts/linux/flatpak/modules/10-libpcap.json
.github/workflows/scripts/linux/flatpak/modules/11-libaio.json
.github/workflows/scripts/linux/flatpak/modules/12-soundtouch.json
.github/workflows/scripts/linux/flatpak/modules/20-sdl2.json
.github/workflows/scripts/linux/flatpak/modules/21-libbacktrace.json
.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json
.github/workflows/scripts/linux/generate-cmake-qt.sh
.github/workflows/scripts/linux/generate-metainfo.sh
.github/workflows/scripts/linux/install-packages-flatpak.sh
.github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in
.github/workflows/scripts/releases/rename-release-assets.py
cmake/BuildParameters.cmake
pcsx2/CMakeLists.txt
pcsx2/GS/GSCapture.cpp

This PR adds a Flatpak build to our CI, using (almost) the same configuration as the AppImage.
Thanks to @charlesthobe for the assistance with putting the manifest together.
The current flatpak package was created without any discussion with us, and has several issues:
- Out of sync with releases.
- Built with gcc instead of clang (up to 15% slower in some games).
- Until recently, disabled inlining => significant speed loss.
- Not maintained by us, so we cannot debug or fix any problems with it.
- No notification of updates.
- Probably doesn't have working ffmpeg (at least not for all formats).
So, instead, I'm proposing we provide this package ourselves. I've been able to work around most of my grievances with the format (mainly by not having to confirm to flathub builder limitations …

CI/Linux: Add Flatpak build files

---

pcsx2-qt/Debugger/MemoryViewWidget.cpp
pcsx2-qt/Debugger/MemoryViewWidget.h

Added support for pasting strings of ASCII text or hex data from the clipboard into the debugger's memory view. The "Paste" option is added to the right-click context menu.
When hacking or reverse engineering a game, it can be helpful to modify large blocks of the PS2's memory with a hard-coded sequence of values. The easiest way to do this is to paste the sequence of values into memory via memory view. Unfortunately, PCSX2's debugger doesn't seem to support this currently.
My testing was mostly copying data from an external hex editor (HxD on Windows) into the memory view after booting a game.
What I tested:
- Copying standard ASCII text into the text view of the debugger.
- Copying standard ASCII text into the hex view of the debugger.
- This did nothing as expected. Inputs to the hex …

Debugger/MemoryView: Support pasting hex/text from clipboard

---

pcsx2/GS/GSCapture.cpp

I'm a doofus and didn't realize there was another level of API required on top of libavcodec to use the hardware encoders.
Having the hardware encoders in the list, but being non-functional isn't very useful.
Test hardware encoders. Make sure software encoding still works.
I've tried with NVEnc on Linux, seems fine.

GS/Capture: Support hardware video encoding

---

pcsx2/GS/GSUtil.cpp
pcsx2/GS/GSUtil.h
pcsx2/GS/Renderers/Common/GSDirtyRect.h
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Fixes depth leaking into the image.
Game's an ass. See the comment in the source.
Note to myself: my clear PR currently doesn't negate the need for this fix... need to dig further into why.
Closes #8976.
Test Haunting Ground. The 3 dumps I have seem okay.

GS/HW: Make Haunting Ground render fix invalidate depth as well

---

bin/resources/GameIndex.yaml

Patch still decrements until satisfactory level
Use higher quality level as a baseline.
Makes thumbnails nicer if the output size can handle it, still shrinks if too big.
Save the game a few times, see what happens.
Side note: Our discovery is the JPEG scuff on the sides of the thumbnails is NOT JPEG scuff. It is GS memory. If you upscale, the GS memory will bleed in to the frame. Don't upscale, no JPEG scuff.

GameDB: Xenosaga Ep 1 - Attempt to use quality level 100 as a base

---

pcsx2/GS/GSState.h
pcsx2/GS/Renderers/Common/GSRenderer.cpp
pcsx2/VMManager.cpp

Fixes up the offsets for overscan modes and correctly stays in 4:3 when overscanning, closer matching the PS2
Numbers were quite a bit off, causing a weird vertical offset.  and I don't know where I hit my head to think I needed to change aspect. Closer matches PS2 output now.
None really, just PRing for the CI then merge, already gone through it on Discord with Nicknine.
Before:
After:
PS2 output through capture (with exagerated gamma/greenness so you can see the borders):

GS: Fix up overscan offsets. Stop using 3:2 for overscan.

---

bin/resources/GameIndex.yaml
pcsx2/GS/Renderers/HW/GSHwHack.cpp
pcsx2/GS/Renderers/HW/GSHwHack.h

MGS3 copies 256x224 in Z24 from 0x2000 to 0x2080 (with a BW of 8, so half the screen), and then uses this as a Z buffer. So, we effectively have two buffers within one, overlapping, at the 256 pixel point, colour on left, depth on right. Our texture cache can't handle that, and it thinks it's one big target, so when it does look up Z at 0x2080, it misses and loads from local memory instead, which of course, is junk. This is for the depth of field effect (MGS3-DOF.gs).
We could fix this up at the time the Z data actually gets used, but that doubles the amount of copies we need to do, since OI fixes can't access the dirty area. So, instead, we'll just fudge the FBP when it copies 0x2000 to 0x2080, which normally happens with a 256 pixel offset, so we have to subtract that from the sprite …

GS/HW: Add render fix for MGS3 DoF effect

---

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
pcsx2/GS/Renderers/HW/GSTextureCache.h

Used by Metal Gear Solid 2, and Zone of the Enders 2.
Instead of just moving the full target sensibly, they break it up into a series of 1-page-wide moves, presumably to avoid page breaks? Why they couldn't just do offset columns instead of offsetting the base pointer is beyond me.
But anyway, since it's page aligned, we can just convert it to rectangles in the target, and copy them ourselves.
Unfortunately these games were the only two that I saw using this, at least in the dump collection anyway.
Getting rid of the readbacks, plus the effect was broken in hardware (it would only dirty the top 1/3 of the screen).
Test MGS2/ZoE2.

GS/HW: Implement FBW-based moves

---

pcsx2-qt/MainWindow.cpp
pcsx2-qt/Settings/ControllerSettingsDialog.cpp
pcsx2-qt/Settings/ControllerSettingsDialog.ui
pcsx2/Config.h
pcsx2/GSDumpReplayer.cpp
pcsx2/ImGui/FullscreenUI.cpp
pcsx2/PAD/Host/PAD.cpp
pcsx2/Pcsx2Config.cpp
pcsx2/USB/USB.cpp
pcsx2/USB/USB.h
pcsx2/VMManager.cpp
pcsx2/VMManager.h

**VMManager: Fix dump playback adding to play time**
Self-explanatory.
**VMManager: Fix title updates when switching GS dumps**
Self-explanatory.
**VMManager: Fix fast forward boot with GS dumps**
Regression from boot PR - the option would cause GS dumps to play at unthrottled speed.
**Qt: Fix crash booting with mouse mapping**
Regression from boot PR - fix crash on startup if pointer is bound to controller.
**VMManager: Only reload core settings on ELF load** 
We don't need to reload e.g. input sources, bindings, etc, after booting the game.
**USB: Copy configuration when creating input profile** 
This was previously missing, you had to manually bring across USB settings.
Also clears the USB settings when you reset to defaults.
**Qt: Fix size of input profile dropdown**
It was too small …

Misc: Regression fixes from boot PR

---

pcsx2/VMManager.cpp

Fixes the order of operations when setting up memcards and disc serials
Disc serial was being loaded before memcards were initialised, so folder memcards didn't learn about the serial, causing savegames to not work/be missing
check folder memcards

Host/Mcd: Fix boot order so memcard type is set before loading memcards

---

pcsx2/Hotkeys.cpp
pcsx2/VMManager.cpp

And cleanup boot init a little.
Also makes GS dumps not open memory cards (useful for two instances).
Regression.
Make sure ws patches change the aspect ratio (checked myself).

VMManager: Fix WS patch not applying auto aspect ratio

---

pcsx2/GS/Renderers/HW/GSHwHack.cpp

Checks DS (depth stencil) exists before trying to clear it.
Trying to clear null is bad.
Fixes #9015

GS/CRC: Fix Ar Tonelico 2 CRC hack to check DS exists
