pcsx2-qt/Translations/pcsx2-qt_en.ts, pcsx2/GameDatabase.cpp, pcsx2/Patch.cpp
Fixes CTD on Manual Hardware Fixes enabled
Fixes CTD on Manual Hardware Fixes enabled
Enable Manual Hardware Fixes, make sure game not commit die
=> Translations: Fix missing context marker on Manual Hardware Fixes string

pcsx2/Elfheader.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Elfheader: Fix Wsign-compare warnings.
GS-hw: Fix Wunused-variable warning.
Fixes compiler warnings.
CI passes and warnings are gone.
=> Misc: Fix compiler warnings.

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Adds checks to make sure the targets/depth stencils exist on the FFX and Sonic Unleashed CRC hacks.
Also in the Burnout CRC exclude indexed texture mapped draws from being skipped.
The target/depth checks weren't being done before and if they didn't exist, it would just crash, but luckily they never used to, but now we're more efficient in making targets, it's more susceptible to them not existing.
With Burnout the new CRC hack to massively increase the speed was also skipping the creation of the Undercarriage graphic, so I've changed it to not include indexed draws.
Already tested sonic, but it can't be worse.
=> GS/HW: Fix up FFX, Sonic Unleashed and Burnout CRC hacks

updater/Windows/WindowsUpdater.cpp
This PR makes the error message (that appears when you tries to run the Updater directly) to be more clearer and more user friendly.
This changes "Qt frontend" to "main PCSX2 application"
Not everyone knows what "Qt" and "frontend" means.
Make sure the text shows up correctly.
=> Updater: Clarify the error message when the program being runs directly

pcsx2/GS/GSDrawingContext.cpp, pcsx2/GS/GSDrawingContext.h, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/GSVector4i.h
More accurate, stops it passing through vertices which are off-screen and coordinates overflowed.
Differences versus current have been manually verified to be correct.
Correctness.
Speed boost.
Progress in stopping zero-area primitives causing invalidation issues.
Check performance in GS/vertex-heavy games, make sure it hasn't regressed (it should be slightly faster if anything).
Make sure upscaling doesn't have holes in geometry.
=> GS: Use 32-bit vertex positions for culling

pcsx2-qt/Settings/AudioSettingsWidget.cpp
Self-explanatory.
Closes #9034.
Right click volume slider.
=> Qt: Fix crash when right clicking volume slider

bin/resources/GameIndex.yaml
Correct gamefixes to fix CLUT problems in HW mode
Old fix didn't work.
Fixes #9039
=> GameDB: Fix CLUT colors for Kazuku Keikaku (SLPM-65889)

.github/workflows/linux_build_matrix.yml, .github/workflows/macos_build_matrix.yml, .github/workflows/windows_build_matrix.yml
Currently, if you push a branch to the PCSX2 repo, then make a pull request, it builds it twice - once for the branch push, and another for the pull request. This just holds up the CI and is duplicating effort.
Similar thing for releases - merging runs the release pipeline, as well as the (wasted) branch push.
I changed the matrix workflows to only run when it's a pull request, because we obviously want that, or if it's a repo other than main PCSX2. I brought the up months ago, and I think it was Tellow (sorry if I'm misremembering) who said they wanted the ability to continue to run the CI on their fork without any extra effort, so this change shouldn't prevent that from happening.
If there's a cleaner way to do it, then I'll change things, because having to duplicate it on each job is …
=> CI: Prevent double builds on pushes to pcsx2 repo

bin/resources/GameIndex.yaml, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Removes some old age hack code and improves the age handling of full dirty targets. Plus remembers recent EE writes done just before VSync.
The setting age to 0 on EE write was never really right, but it was a means to an end when it was done, now it's no longer required.  This then allows us to tighten the age check for removing fully dirtied targets.
Also made it remember recent writes from the EE if the most recent one was on the same draw number as VSync occurs on, this can happen with videos.
Test random things, see if anything explodes.
=> GS/HW: Improve target age handling and remember recent EE Writes

bin/resources/GameIndex.yaml
Fixes transparency in Japanese game Snow
Transparency bad
Watch CI
Fixes #9043
=> GameDB: Add minimum blending level for Snow (SLPS 25342 & 25332)

pcsx2/DEV9/ATA/ATA.h, pcsx2/DEV9/ATA/ATA_Transfer.cpp
Deduplicates the code asserting that the sparse/allocated apis and FileSystem apis are in sync.
This moves back the assert talked about here https://github.com/PCSX2/pcsx2/pull/8992#discussion_r1232734269 as its intention was to protect this debug only code from being unable to restore the file pointer.
The error handling mentioned https://github.com/PCSX2/pcsx2/pull/8992#discussion_r1234689894 is retained as it protects non-debug code.
Addresses https://github.com/PCSX2/pcsx2/pull/8992#discussion_r1232748845
Less duplicated code, hopefully code is clearer in intent
DEV9 works as expected, CI passes.
=> DEV9: Deduplicate sparse file assert code

pcsx2/GameDatabase.cpp, pcsx2/GameDatabase.h, pcsx2/Pcsx2Config.cpp, pcsx2/VMManager.cpp
Stops upscaling hacks loading from the gamedb in native resolution
These should not apply in native res.
Test games with upscaling fixes in the gamedb, make sure they don't enable.
=> GameDB/Config: Don't apply GS upscaling fixes in native resolution

pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Updates more of the destination target information when a move is done in hardware mode
Before we weren't updating the drawn area, which is technically all of it here as it is all dirty compared to local mem, but also we were using the source valid bits but this certainly isn't true as there could be data from local mem which is stored on the texture being copied, but also there could be dirty data under the new target if the valid bits don't cover the entire pixel colour.
Uhh smoke test, I guess, not much uses this. Armored Core, Bust a Move (both tested), stuff like that.
Fixes #9042
Cross Channel - To All People (slightly different frame, which is why one is darker)
Master:
PR:
=> GS/HW: Update drawn area and full valid bits on hardware move

pcsx2-qt/CMakeLists.txt, pcsx2-qt/QtHost.cpp, pcsx2-qt/Settings/BIOSSettingsWidget.cpp, pcsx2-qt/Settings/BIOSSettingsWidget.h, pcsx2-qt/Settings/InterfaceSettingsWidget.cpp, pcsx2-qt/Settings/InterfaceSettingsWidget.h, pcsx2-qt/SetupWizardDialog.cpp, pcsx2-qt/SetupWizardDialog.h, pcsx2-qt/SetupWizardDialog.ui, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters
Adds a setup wizard to Qt, like wx used to have.
You can force the wizard to run by adding `-setupwizard` to the CLI. 
Note: I'm aware the icon is low-res and looks like ass on hidpi, we need a better one.
Making it easier for users to set up PCSX2.
Test setup wizard on a clean copy of PCSX2. Make sure all functionality works as expected (can check by visually inspecting the ini).
Make sure cancelling setup makes it run again next time.
Make sure existing inis don't trigger setup wizard.
=> Qt: Add Setup Wizard

pcsx2-qt/Settings/AchievementSettingsWidget.ui
As was discussed in https://github.com/PCSX2/pcsx2/issues/9046#issuecomment-1605271962, this PR removes the color style attribute override from hyperlink on Rcheevos so it follows the currently applied style/theme.
NOTE: I noticed that the hyperlink color itself doesn't change fully on theme/style changes, meaning you have to fully restart PCSX2 for the change to take effect, a small issue but worth keeping in mind
NOTE #2: Another thing i noticed is that the translation file also contains color attributes override as well, @stenzek do we need to do something about it, or leave it as is?
Readability 100
and Consistency, dude. 
Check if the links are readable on each themes.
=> Qt: Removes hyperlink color override from Rcheevos

pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Patch.cpp, pcsx2/Patch.h
Self-explanatory. Was in the Qt side but not big picture.
Feature parity.
Check patch/cheats menu in big picture UI.
=> FullscreenUI: Add patches/cheats to game settings

pcsx2/IPU/IPU_Fifo.cpp, pcsx2/IPU/IPU_Fifo.h, pcsx2/IPU/IPUdma.cpp
Rewrite the IPU FIFOs to transfer with memcpy all at once instead of single QWC loops. Also small change to IPU_TO DMA so it doesn't loop if the FIFO is full.
Just nicer code, slightly quicker.
Test videos, make sure everything works as it did.
Test video was the ONI PAL intro, 3 passes for each:
Test video was the FFX-2 NTSC intro, 3 passes for each:
=> IPU: Redo FIFO transfers, plus small IPU_TO DMA tweak

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/SW/GSRendererSW.cpp, pcsx2/GS/Renderers/SW/GSRendererSW.h
Double buffers the EE transfer list for saving only the last 5 draws of transfers.
previously it was going through in draw order which could be thousands (Liberty City Stories suffered greatly with 9000+ transfers), now we go in reverse saving the most recent transfers in to a new buffer, then just erase the rest and swap buffer, this proved to be much quicker.
Test Liberty City Stories, maybe some random other stuff as smoke test, dump run on 1300+ showed no changes visually.
=> GS: Double buffer the EE transfer queue

pcsx2-qt/Settings/AchievementLoginDialog.ui
Makes the Achievements login box slightly bigger to avoid weird jumping around on windows due to the size being smaller than the text allowed.
It was kinda janky on windows, this also leaves an extra line in case translations are slightly longer
Look at the achievements login box, move it around, make sure it doesn't jiggle violently.
=> UI: Expand Achievement login box height slightly

common/CocoaTools.h, common/CocoaTools.mm, pcsx2-qt/AutoUpdaterDialog.cpp
When launching the new PCSX2 after an update, the Mac updater now uses a shell script to wait until the old PCSX2 has closed before launching the new one
With the old flow, since new PCSX2 was launched while the old one was still open, it would get a separate dock icon, which meant that if the user had PCSX2 pinned in the dock, the new one wouldn't use the pinned dock icon
Tested locally (PR builds don't have the updater enabled)
=> Updater:Mac: Delay launch of new application until the old one exits

pcsx2/IPU/IPU.cpp, pcsx2/IPU/IPU.h, pcsx2/IPU/IPU_Fifo.cpp, pcsx2/IPU/IPU_MultiISA.cpp, pcsx2/IPU/IPUdma.cpp
Try to slow down IDEC and BDEC based on how much data they have transferred, and use a base amount of delay of 64 to begin processing.
These numbers aren't exact, they're just something so it doesn't go insanely fast, there are situations where a DMA will start to drain an IDEC and it will go so fast, the data hasn't been written by the time the IPU gets to it, so this will simulate the encoding time, at least a little.  In the future it would be nice to run some tests on a PS2 get some good numbers, but doing IPU Stuff is difficult.
Test videos, make sure nothing is broken, also check Lord of the Rings - Return of the King (PAL)
Fixes #7073 Lord of the Rings - Return of the King
=> IPU: Slow down BDEC and IDEC so they don't outstrip DMA data writes

bin/resources/GameIndex.yaml
Add high blending for a couple of VN's
transparent is bad
No need
Fixes #9080
Fixes #9061 however it still has an unsolvable upscaling issue, but as per the templates, we don't take reports for upscaling issues (unless the GameDB can fix it)
=> GameDB: Add blending for Clannad and Clover Heart's VNs

pcsx2-qt/Translations/pcsx2-qt_en.ts, pcsx2/CDVD/CDVD.cpp, pcsx2/MemoryCardFile.cpp, pcsx2/MemoryCardFile.h, pcsx2/MemoryCardFolder.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/Sio.cpp, pcsx2/Sio.h, pcsx2/VMManager.cpp
Hugely improves swapping of memcards and reinserting (especially when loading a savestate).
Initially I just wanted to fix a bug I introduced with it not loading game specific memcards due to a chicken/egg problem with loading memory cards, I've kinda rewritten some of how that's done and centralised some of the code.
The second problem was one which has plagued PCSX2 since the beginning, reinserting memory cards on "swap".  Previously we just ejected it and told the PS2 we were disconnected for 60 reads, and this *kinda* worked, but it was very unreliable, plus it was very annoying for people loading states as you had to keep retrying until it eventually worked.
The solution turned out to be simple. When the PS2 boots, the terminator for the memcard is set to 0x55, mcman picks this value …
=> SIO/MCD: hugely improved memcard swapping + reinsertion + Fix per game cards

pcsx2-qt/Settings/AudioSettingsWidget.cpp, pcsx2-qt/Settings/AudioSettingsWidget.h, pcsx2-qt/Translations/pcsx2-qt_en.ts, pcsx2/SPU2/SndOut.cpp, pcsx2/SPU2/SndOut.h, pcsx2/SPU2/SndOut_Cubeb.cpp, pcsx2/SPU2/SndOut_XAudio2.cpp
Replacement for #9078.
These strings were not translatable.
Make sure sound still works.
=> Qt: Move audio backend names to core and allow translation

pcsx2/GS/GSLocalMemory.cpp, pcsx2/GS/GSLocalMemory.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Onimusha 3 moves texture data to a previous render target location (e00), then copies it back with a 1-line offset, to "scroll" the texture upwards. Of course this is done with P8.
Surface offsets got the dirty rect wrong, and it ended up reading back garbage. So instead, when it's page aligned (the first one is in this case), figure out the rectangle for each page in the **target's** PSM/coordinate space, and dirty that instead. Better than surface offsets, which gets it wrong (of course..).
In addition, we can do the same for avoiding some readbacks - if all the pages we're invalidating are within the dirty area, we can skip reading back, since local memory is valid. I do have a slight concern with this - since it uses the union of the dirty area instead of iterating through them, but …
=> GS/HW: When page aligned, dirty page rects instead of SO

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Translations/pcsx2-qt_en.ts
Removed below outdated info from description of Preload Frame Data. (See #7805 )
> Fixes black screen issues in games like Armored Core: Last Raven.
For correction of the description
I'm not sure.
=> UI: Remove outdated info from descritption

pcsx2/Interpreter.cpp, pcsx2/R3000AInterpreter.cpp, pcsx2/R5900.h, pcsx2/Sio.cpp
What the title says. Also cleans up a warning in the EE int, and gets rid of the spam when using multiple memory cards and loading state.
Cleanup/less spam.
Make sure int still boots a game.
=> R5900: Fully get rid of exceptions

.github/workflows/cron_publish_flatpak.yml, .github/workflows/linux_build_flatpak.yml, .github/workflows/linux_build_matrix.yml, .github/workflows/release_pipeline.yml, .github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json, .github/workflows/scripts/linux/generate-metainfo.sh, .github/workflows/scripts/linux/install-packages-flatpak.sh, .github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in
As discussed in https://github.com/flathub/flathub/issues/4248.
For now, it's just on the manual trigger, because we don't have push access to the main repo yet, it would just keep building/pushing every day.
Next step.
CI passes.
=> CI/Linux: Publish Flathub builds daily [disabled for now]

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h, pcsx2/ShaderCacheVersion.h
Needed since the upscale multiplier is no longer part of the shader/pipeline.
Closes #9112.
Test dump linked in PR, scrollwheel upscaling.
=> GS/Vulkan: Make line width dynamic

pcsx2/GS/Renderers/Common/GSDevice.cpp
GS-hw: Change some blend operations in hw blend table.
Change the operations for Cs in table to CONST_ZERO as we want it to be 0.
Accuracy.
No test case has been confirmed to trigger it but the behavior is correct now.
=> GS-hw: Change some blend operations in hw blend table.

bin/resources/GameIndex.yaml
- Remove unnecessary CPU Sprite Render Size from bunch of Armored Core games besides Last Raven.
- Update comments of CPU Sprite Render Size for Armored Core Last Raven.
- Add HPO Normal for fixing misaligned blur in Armored Core Nexus, Nine Breaker, and Formula Front.
- The water rendering issue doesn't occur without CPU Sprite Render Size since v1.7.4665, so this is no longer needed for the Armored Core games.
- But hardware renderers have another issue (glowing effects disapper) on Last Raven without CPU Sprite Render Size,  so I changed comment of those line as:
```yaml
cpuSpriteRenderBW: 2 # Fixes glow effects, but breaks shadows of certain objects.
```
- As a side note, that glow issue has persisted for a while. It occurs even on v1.6.0
Already tested on v1.7.4666
- Found a fact, …
=> GameDB: Various fixes for Armored Core games

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Our clear detection sucks at the moment, in particular for double half/striped-double/FBW clears.
This PR attempts to detect them more accurately, to avoid creating false targets in the TC, and save VRAM bandwidth by using target clears instead of useless draws. At 8x, with 3 draws per frame, that's around 4GB/s of bandwidth saved.
Correctness
Vroom vroom
~~Unfortunately it doesn't seem to directly fix anything that I've seen.~~ But it does make things easier down the line, and the TC less ball-achey.
Fixes #8872.
Fixes #9096.
Test a range of games, make sure nothing broke. Dump runner has a bunch of diffs, but I've fixed everything I could visibly see issues with.
=> GS/HW: Improve detection of clears

pcsx2/GS/GSLocalMemory.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Avoids divide by zero errors
Dividing by zero is bad. Call of Duty 3 was hitting this with a buffer width of 0
Untested but pretty confident this is better than crashing.
=> GS/HW: avoid divide by zero's in draw rect calculations

pcsx2/GS/GS.cpp, pcsx2/GS/Renderers/Common/GSRenderer.cpp
FFX's FMVs writes to the render target (annoyingly with a Y offset to push it to the second buffer, but alas).
The draw where it alpha tests+copies what I'm guessing is the subtitle text over the top gets buffered, and flushed at VSync time. Problem is the EE transfer list got cleared in GSRendererHW::VSync(), before the flush happened, so it doesn't know it needs to preload.
So reverse the order of operations.
Fixes FMV flicker in FFX.
Check FFX FMV.
=> GS: Move VSync flush to caller

pcsx2/GS/Renderers/Common/GSDevice.cpp
Was using a DONT_CARE load op, but discarding every other line -> leaving uninitialized data in the RT.
Only affects the first frame. But annoying for GS dumps.
Correctness.
CI passes.
=> GS: Fix uninitialized data in deinterlacing

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Used by Ape Escape 2, Everybody's Tennis/Golf, Okage, and Valkyrie Profile 2.
Unfortunately the player shadows are still missing in tennis/golf - it does a P4HH -> P4 move to create a texture which later gets drawn to the FB which gets channel shuffled... I swear I can smell something... like... epoxy... now I have a feeling of writing an overengineered shadow renderer...
Sadly none of the other currently-broken channel shuffles seem to work with this heuristic.
Closes #9161.
Closes #5342.
Check affected games.
=> GS/HW: Use minimum UV as a channel shuffle heuristic 

common/FileSystem.cpp, common/Path.h, pcsx2-qt/CMakeLists.txt, pcsx2-qt/Settings/MemoryCardCreateDialog.cpp, pcsx2-qt/Settings/MemoryCardCreateDialog.h, pcsx2-qt/Settings/MemoryCardCreateDialog.ui, pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp, pcsx2-qt/Translations/pcsx2-qt_en.ts, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters, pcsx2/ImGui/FullscreenUI.cpp, tests/ctest/common/path_tests.cpp
If you created a memcard with a colon in it, it'd put the card data in an alternate data stream instead...
Closes #9145.
Try creating a card with a normal, then malformed name.
=> Qt: Don't allow creation of memory cards with invalid names

bin/resources/GameIndex.yaml
Added CPU Sprite Render to Armored Core Formula Front.
- HPO Normal was added to fix blur effects, but it breaks shadow rendering in this game.
- CPU Sprite Render can fix it.
Tested ACFF
=> GameDB: Fix broken shadow in Armored Core Formula Front

pcsx2-gsrunner/Main.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2/GS/GS.cpp, pcsx2/GS/GS.h, pcsx2/GS/GSCapture.cpp, pcsx2/GS/GSCapture.h, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/GS/Renderers/Common/GSRenderer.h, tests/ctest/core/StubHost.cpp
Automatically restart capture on renderer or hardware reset.
Syncs video capture checkbox to "real" state.
Closes #9176.
Closes #8904.
Check loading state when capturing video+audio.
Check resetting while doing the same.
=> GS: Improve capture robustness

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
Further improvements to clear detection. Fixes a few games, breaks a couple of others:
- sf3ex: Effect is broken anyway, but now flickers on alternate frames because of false double buffer detection.
- Growlanser: Heritage of War: Game uploads a Z buffer, moves to swizzle it, but in C32 instead of Z32 so it doesn't get uploaded, because the target got purged. Needs EE transfer handling to be improved.
Not sure if we should hold off on merging until I solve the above.. the first two weren't working correctly anyway. And were sorta working only by chance...
Fixes #8672.
Fixes #9167.
Fixes #9163.
Fixes #9170.
Check affected games.
=> GS/HW: Be more strict with double half clear detection

pcsx2/USB/usb-pad/usb-turntable.cpp, pcsx2/USB/usb-pad/usb-turntable.h
Update some of the labels used for DJ Hero Turntable Emulation
Swap the multiplier from integer to float
Fix turntables being scaled by 255 instead of 128
A few people contacted me on one of the DJ Hero Discord servers and pointed out that the labels I had used were somewhat confusing and in a few places they were actually wrong. 
I have gone for clockwise and counterclockwise, as the turntables can be in any orientation, and due to that it is possible for up and down to be a bit confusing in different orientations.
Someone also tested with a Wii Turntable with a Raphnet adapter, and it turns out those need to be given a fractional multiplier, as the turntable range from those is too large and the game doesn't handle it correctly.
Since the positive and negative values are bound …
=> USB: Fix DJ Hero Turntable Labels

bin/resources/GameIndex.yaml
Quick fix for an incorrect name for NFS U2
Incorrect name bad
CI good
=> GameDB: NFS U2 Name fix

bin/resources/GameIndex.yaml
I tried to make sure the names I was interested in remain uniform across different editions and correspond to Redump database. 
Some names are misleading or just incorrect, which makes it confusing to distinguish one edition from another or messes up the position of the game in the library because of some missing dash.
Non-applicable
=> GameDB: Fixing multiple names

pcsx2/Input/SDLInputSource.cpp
Apparently on cmake, SDL isn't compiled with stdio support...
Regression from #9181.
Make sure controller db loads.
=> Input/SDL: Don't pass stdio handle to SDL

pcsx2/USB/shared/ringbuffer.cpp, pcsx2/USB/usb-mic/audiodev-cubeb.cpp, pcsx2/USB/usb-mic/audiodev-cubeb.h
- RingBuffer would store a size of zero if you wrote the entire the entire buffer in one call.
- ResetBuffers() should be called before starting the stream, otherwise you risk a race where the callback happens before the buffer is allocated.
- Fix incorrect latency being passed into Cubeb.
Side note: that ring buffer class is pretty awful. But I don't care enough to rewrite it.
Closes #8974.
Test usb-mic.
=> USB/usb-mic: Fix buffer handling

bin/resources/GameIndex.yaml, pcsx2/Config.h, pcsx2/Docs/gamedb-schema.json, pcsx2/GameDatabase.cpp, pcsx2/GameDatabase.h, pcsx2/Pcsx2Config.cpp
Refraction's going to hate me.
And clean up the speedhack enum in general, making it scoped.
It's better UX for those games which have no other option than having users complain, and telling them to bump it themselves, then having the warning show up on startup.
Make sure MVU Flag/Instant VU/MTVU disables still work via gamedb.
=> GameDB: Add eeCycleRate option

pcsx2/DebugTools/MIPSAnalyst.cpp
Fixes #9197 
Properly handle 32bit reg sign extension in mipsanalyst.
Should fix stepping through branches on compare with zero instructions.
Test stepping through branches on IOP debugger.
=> mipsanalyst: sign extend 32 bit regs

bin/resources/GameIndex.yaml, pcsx2/Config.h, pcsx2/Docs/gamedb-schema.json, pcsx2/GS/GS.cpp, pcsx2/GS/GS.h, pcsx2/GS/GSRegs.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSHwHack.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GameDatabase.cpp, pcsx2/GameDatabase.h, pcsx2/Pcsx2Config.cpp
And use it to fix Growlanser. (I'll also use this for Ico later on to avoid readbacks)
Regression from #9171.
I only have one GS dump for the series, so I have no idea if this completely fixes the issue. I tried to make the hack fairly generic, so hopefully it'll work cross-region.
@Risae could you check some of these games, and if it's still broken, upload a GS dump please?
=> GS/HW: Add render fix for complex moves

pcsx2/Counters.cpp, pcsx2/IopCounters.cpp, pcsx2/R3000A.cpp, pcsx2/R3000A.h, pcsx2/R5900.cpp, pcsx2/R5900.h, pcsx2/Vif1_Dma.cpp
Optimise when internal interrupts run, reducing exits from the EE, improving performance.
Also improved the EE/IOP sync to split more efficiently.
More brrr
Test games, feel free to compare to master :) Make sure nothing broke in the process.
Examples of performance improvements.  FMV's around 10-30% faster, ingame anywhere from 1-7% faster (in testing)
FMV's
Ingame benchmarks
=> Counters + DMA: Optimize when internal interrupts run

bin/resources/GameIndex.yaml
Recommend **Blending Accuracy** set to **High** for **Need for Speed: Underground 1**
Road/Sidewalk reflections look better
CI passes, game looks better!
=> GameDB: NFS UG1 Blending

.github/workflows/linux_build_flatpak.yml, .github/workflows/linux_build_matrix.yml, .github/workflows/linux_build_qt.yml, .github/workflows/macos_build.yml, .github/workflows/macos_build_matrix.yml, .github/workflows/release_pipeline.yml, .github/workflows/scripts/common/name-artifacts.sh, .github/workflows/scripts/releases/rename-release-assets.py, .github/workflows/windows_build_matrix.yml, .github/workflows/windows_build_qt.yml
And adjust release filenames.
Consistency, and there's no need to put Qt in the filenames, Qt is our only option now.
Also hopefully will stop Linux builds from missing the cache every time.. there was a double space in the key, and GH seems to have changed something recently that strips them.
~~I'm also going to run the release pipeline on my fork to make sure that side works.~~ Seems fine
=> CI: Remove redundant GUI variables

pcsx2/Vif1_Dma.cpp
Adds missing internal DMA stall flag
This would have caused the DMA to infinite loop in instant DMA mode and the new DMA changes, causing a regression in games that use it, like Parappa the Rapper 2
Already tested
Fixes #9212
=> VIF: Add missing internal DMA stall flag

.github/workflows/linux_build_qt.yml, .github/workflows/scripts/linux/AppRun-qt, .github/workflows/scripts/linux/appimage-qt.sh, .github/workflows/scripts/linux/install-packages-qt.sh
Moves the Linux builder to Ubuntu 22.04 so we can use C++20.
Switches from manual AppImage creation to using linuxdeploy, but we have to do some post steps because the Qt plugin there doesn't support Wayland... of frickin course. Gotta love the Linux desktop experience.
~~Adds libstdc++ into the appimage so hopefully it'll still run on Ubuntu 20.04. With any luck the libc is the same.....~~
Moves the Linux builder to Ubuntu 22.04 so we can use C++20.
Make sure AppImage works on a few distros in both brokeland and xorg.
=> Linux/CI: Switch to Ubuntu 22.04 and linuxdeploy

pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
Fixes Wunused-but-set-variable warning.
Cleanup warnings.
CI passes.
=> GS-ogl: Fixes Wunused-but-set-variable warning.

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
Parappa draws a fullscreen quad with the texture pointing at the framebuffer, but uses a region repeat of 1008, 0, to drop the bottom 4 bits of the UV's Y, producing a mosaic effect.
We weren't testing for this before, so it was using barriers to read the FB without overlap, which meant the UVs weren't mutated.
Fixes #9216.
Check parappa dump.
No other games except parappa hit this in the dump collection, should be safe.
=> GS/HW: Avoid tex-is-fb when incompatible clamp is used

pcsx2/ImGui/ImGuiOverlays.cpp
Draws the input recording overlay first and then the performance overlays.
Closes #8330.
Check by playing an input recording while all OSD settings are on.
=> OSD: Input recording overlap fixed

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Improves strip gap detection in weird cases where the game isn't drawing strips
Lord of the Rings - The Third Age draws 2048 sprites with an 8x8 size, going across 32 pixels, then down 8 pixels, repeat until it reaches 512 height, then skips 32 pixels and repeats until it fills the screen.  This is a very over engineered way of doing a double half clear if I ever saw one, but our current master code assumes developers aren't batshit insane, but here we are.
Surprisingly even though I'm now checking 4096 vertices (but only when everything else required matches), it actually runs a tiny bit (2%) quicker than master.
Test Powerdrome, GT4 Online and LOTR The Third Age, or any other double clear games you might know.  GS dumps say all is good.
=> GS/HW: Improve double half clear for strange strip drawing

pcsx2/GS/GS.cpp, pcsx2/GS/GSExtra.h, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/GSVector4i.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h, pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp, pcsx2/GS/Renderers/HW/GSTextureReplacements.h
Calculate and remember the alpha values of RT's when drawing.
Also fix a bug in DATE where it was using the optimised shortcut (incorrectly) even if the Alpha to 1.0 (0x80) was masked.
Added stenzek's changes to also calculate the alpha values for sources.
RT's can be unpacked from indexed textures, where we do know the alpha, then read as C32 normal images, where we don't normally know the alpha. Doing this means we can't usually know the alpha in advance, meaning we miss out on potential blending optimisations and using hardware blending.
Also DATE_one is an optimisation to say if the data being written is above/below the threshold for DATE, then all pixels after the first pass will fail. This was wrong when the alpha at 1.0 (0x80) isn't written, so it now checks for the FBMASK and …
=> GS/HW: Calculate alpha min/max for sources and targets

common/CMakeLists.txt, common/TextureDecompress.cpp, common/TextureDecompress.h, common/common.vcxproj, common/common.vcxproj.filters, pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp
Fixes regression from https://github.com/PCSX2/pcsx2/commit/a371c5b7d069a53e396bbb42482699004269aeb3
=> GS/HW: Decompress replacement textures to get alpha min/max

pcsx2/GS/GSState.cpp
Only clamp texture co-ords to texture bounds in hardware mode.
regressed software mode in #8906, software handles this stuff itself, where hardware mode craps the bed without, so let's keep it for hardware only.
Test Ratchet & Clank - Deadlocked in software mode around lava. Smattering of other games.
=> GS: Only clamp tex co-ords to bounds in hardware.

bin/resources/GameIndex.yaml
add HPO Special to LEGO Batman to fix depth line
line is gross
Watch CI
=> GameDB: Fix depth line in LEGO Batman

bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h, pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp, pcsx2/GS/Renderers/Vulkan/VKContext.cpp, pcsx2/GS/Renderers/Vulkan/VKContext.h, pcsx2/ShaderCacheVersion.h
Makes sense to use the extension, since it's what we're doing.
Enables us to use dynamic rendering everywhere later on (needed for ROV).
Compare performance (no change expected), check games.
=> GS/Vulkan: Use VK_EXT_attachment_feedback_loop_layout when supported

.github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json
This brings the functionality in line with the old Flatpak release. This allows PCSX2 to inhibit the screensaver or screen blanking without needing to touch the mouse/keyboard while the VM is running.
Adds one flag to the to the flatpak packaging json file.
The old Flatpak packaging used this finish-arg to allow the screensaver inhibitor to function. Without this flag the screensaver will come up during a play session because gamepad inputs don't prevent screen blanking.
If you want to manually test this flag without committing the easiest way is to use Flatseal and then add `org.freedesktop.ScreenSaver` to PCSX2 under the Talks subsection in the Session Bus section. Wait for your screen saver or screen blank timeout and observe. You can also observe the inhibition and uninhibition by …
=> Flatpak: Add the talk-name flag for org.freedesktop.Screensaver

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
Reduces the cutoff for preferring PrimID destination alpha over barriers
Also wires up the disable fbfetch checkbox on the Metal renderer
The old number was decided back when we had an OpenGL renderer that used texture atomics for the PrimID algorithm.
New one was tested based on performance of [NBAStreetVol2-SLUS-20651-DATE.zip](https://github.com/PCSX2/pcsx2/files/12035718/NBAStreetVol2-SLUS-20651-DATE.zip), which seems to have a lot of medium-size batches of destination alpha draws.
<details>
<summary>Test results</summary>
Note: Render pass count is approximately equal to 2x the number of PrimID passes
On the Metal renderer:
| Cutoff | # Barriers | # Render Passes | FPS (Intel UHD 630 @ 2x) | FPS (AMD Radeon Pro 5600M @ 4x) |
|---:|---:|---:|---:|---:|
| 0 | 17 | 861 | 74 | 87 |
| 30 …
=> GS: Reduce cutoff for PrimID destination alpha

pcsx2-qt/Settings/InputBindingWidget.cpp
Adds tooltips to controller bindings to say what controls you need to add/clear bindings.
Users weren't really aware of adding additional bindings, for example, so this could inform at least some users.
Mess about with the controller UI
=> UI: Add controller binding tooltips for additional controls

pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Sets the valid size of the target to the size of the draw, not the cached size.
It is possible a target can get reused as a different size, but before it was invalidly making the valid size the previous height.  This was happening with Shadow Hearts, where the second half of what was a 448 high buffer was now being used to upload new textures, triggering PCSX2 to invalidate that second half of the depth buffer constantly, which made the render passes reset every draw.  This now correctly only marks the valid size to what is actually being drawn.
Also copy the valid size on dst_match in case this needs to be expanded/invalidated.
Test Shadow Hearts and a smattering of a few games.
=> GS/HW: Use draw for valid height, preload cached size

bin/resources/shaders/dx11/cas.hlsl, bin/resources/shaders/opengl/cas.glsl, bin/resources/shaders/opengl/convert.glsl, bin/resources/shaders/vulkan/cas.glsl, bin/resources/shaders/vulkan/convert.glsl, pcsx2/GS/Renderers/Metal/convert.metal, pcsx2/ShaderCacheVersion.h
GS: Fixes shader initialization warnings.
Fixes these shader initialization warnings on GL.
Delete shader cache, run opengl, make sure the warnings are gone, also make sure other renderers still work.
=> GS: Fixes shader initialization warnings.

pcsx2-qt/MainWindow.cpp
- Raises settings if you attempt to open it while it's already open
- Delays raising settings after a language change because Qt is weird on macOS
- No more missing settings windows
Test the above on macOS
=> Qt:Mac: Make sure settings windows are raised when requested

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiFullscreen.cpp, pcsx2/ImGui/ImGuiFullscreen.h
Fixes big picture light mode colors so you don't get black text on black backgrounds
Also switches the switch color to look less disabled in light mode
Usable light mode
Look at the About PCSX2 window in big picture
Look at settings toggles
Look at the pause menu
=> FSUI: Fix light mode colors

pcsx2-qt/MainWindow.ui
Removes the `&`s from toolbar icon strings, which are used in menubars to mark [mnemonic characters](https://en.wikipedia.org/wiki/Mnemonics_(keyboard))
They're not useful, and may make translators think they need to add extra characters in parentheses for the mnemonic to be placed on
None until translations are updated against the new strings
=> Qt:Translation: Remove mnemonics from toolbar strings

bin/resources/GameIndex.yaml
Fixes for spikey SPS on characters with VU1 clamp extra plus sign.
The boys shouldn't be spikey.
=> GameDB: Naruto Ultimate Ninja 5 Fixes

common/Linux/LnxMisc.cpp
1- Don't call `dbus_connection_unref()` on the public connection.
2- Keep the value of the inhibitor cookie until it's used.
3- Disallow reuse of the inhibition as long as there's an inhibitor alive.
1- Calling "`dbus_connection_unref(connection)` " would have resulted in undefined behavior according to DBus documentation.
2- If uninhibiting fails, then the inhibitor is still alive and the cookie is valid, so we shouldn't inhibit again.
Make sure starting the VM with "Inhibit Screensaver" ticked inhibits the screensaver, I already did so.
=> Common: Linux: fix potentially unsafe screensaver inhibitor

.github/workflows/cron_update_base_translation.yml, .github/workflows/scripts/common/update_base_translation.sh, pcsx2-qt/Translations/update_en_translation.sh
This way the file can be updated, without running into conflicts from different PRs changing different source locations.
Making crowdin not display out of date strings.
CI passes - already tested on my fork: https://github.com/stenzek/pcsx2/pull/1
=> CI: Add daily base translation update

bin/resources/GameIndex.yaml
Fixes lego drome racers having a black screen in hardware mode.
Before:
After:
Fixes #9270 
Blackscreen in hardware mode bad.
=> GameDB: Lego Drome Racers blackscreen fix

common/FileSystem.cpp, common/FileSystem.h
This PR changes `ManagedCFilePtr` to use a functor structure instead of a lambda for a deleter.
Slimmer `std::unique_ptr`'s, as seen here - notice `static_asserts`:
https://godbolt.org/z/8rTWoe3qd
No idea? This has no chance of breaking if it compiles.
=> FileSystem: Make FILE* unique pointers use a functor deleter

.github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in
Now [the flathub page](https://flathub.org/apps/net.pcsx2.PCSX2) should show links for donations, FAQ and translations.
More accessibility to those options.
Only applicable after merging; make sure said links appear in [the flathub page](https://flathub.org/apps/net.pcsx2.PCSX2)
=> Flatpak: Add project links to the flathub store page

bin/resources/GameIndex.yaml, pcsx2/GS/GSCrc.cpp, pcsx2/GS/GSCrc.h, pcsx2/GS/GSLocalMemory.cpp, pcsx2/GS/GSLocalMemory.h, pcsx2/GS/GSVector.h, pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX12/D3D12Builders.cpp, pcsx2/GS/Renderers/DX12/D3D12Builders.h, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/VKBuilders.cpp, pcsx2/GS/Renderers/Vulkan/VKBuilders.h
Currently, PCSX2 removes any Z targets when you write to the RT at an address, or vice versa. Hence the gross CRC hack for Getaway. Let's get rid of that, which also fixes a bunch of other issues.
- Fixes lens flare and DoF in True Crime: NYC.
- Fixes reflections in Eragon.
- Fixes floor in Area 51.
- Fixes flickering in Transformers.
- Improves fog effect in Forgotten Realms - Demon Stone.
Fixes lens flare noted in #8242.
Gets rid of 1/4 of the remaining GSCrc entries.
Fixes #3986.
Make sure DBZ BT2/3 didn't take a non-trivial speed hit.
(needs high blending for fog wall)
=> GS/HW: Support alpha in RT concurrently with Z

crowdin.yml
Just to make it more difficult to make the mistake i just made (forgot to put a prefix in the squash merged commit)
I also realized that i need to remove the `ci skip` from the title of the PR (which becomes the master merge commit), or the release workflows won't run
=> crowdin: update automatic PR title so squash merge has the right format

bin/resources/GameIndex.yaml, pcsx2/GS/GSCrc.cpp, pcsx2/GS/GSCrc.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSHwHack.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Current Ico CRC hack is disgusting. New way intercepts it at the move level instead, which is slightly less disgusting, but more importantly, doesn't have an unnecessary readback (bad for perf).
Vroom vroom.
Closer to getting rid of GSCrc
Make sure Ico isn't broken ingame.
=> GS/HW: Replace Ico CRC hack with move handler

pcsx2-qt/MainWindow.cpp, pcsx2-qt/Settings/GameCheatSettingsWidget.cpp, pcsx2-qt/Settings/GameCheatSettingsWidget.h, pcsx2-qt/Settings/GamePatchSettingsWidget.cpp, pcsx2-qt/Settings/GamePatchSettingsWidget.h, pcsx2-qt/Settings/SettingsDialog.cpp, pcsx2-qt/Settings/SettingsDialog.h
Because CDVD sucks and you can't open two images concurrently, we can't populate the summary page.
But we can still populate the window title, and game fixes/cheats.
Closes #9283.
Check game properties on scanned and unscanned files.
=> Qt: Fix game properties for unscanned files

pcsx2/VMManager.cpp
MTGS was already opened, so it didn't get the new CRC.
Closes #9293.
Start big picture then a game, make sure texture replacements load.
=> VMManager: Notify MTGS in UpdateDiscDetails()

.github/workflows/macos_build.yml, .github/workflows/scripts/macos/build-dependencies.sh, cmake/BuildParameters.cmake, pcsx2/GS/GSCapture.cpp, pcsx2/Pcsx2Config.cpp
- Adds a minimal (~3MB) copy of ffmpeg to Mac builds (includes a few small lossless codecs and the interface to macOS's system encoding libraries)
- Fixes a bug where s16 codecs would get their audio mangled
- Fixes a bug where setting a pixel format with `pixel_format=fmt` in the extra arguments would break things
Capture support on macOS
Try recording things on macOS
=> GS:Mac: Add ffmpeg

pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp
BC1 is 8 bytes per block, not 16.
Whoops.
CI passes, Already tested.
=> GS/HW: Fix alpha min/max crashing on BC1 textures

.github/workflows/scripts/linux/appimage-qt.sh
Linuxdeploy is a pain in the arse. See the comment in the source....
Being able to debug user issues.
Make sure AppImage still works.
=> CI/Linux: Fix AppImage getting symbols stripped

bin/resources/GameIndex.yaml
a fixed version of #9300
Run the French & German versions of this game. Check that weird SPS caused by COP2 timing issues are fixed.
=> GameDB: Adding Cop 2 patches for French & German versions of Kessen II

pcsx2/CDVD/CDVD.cpp
Fixed a small typo I found in cdvdUncheckedLoadDiscElf.
Fixes a typo.
=> CDVD: Fix DevCon typo for cdvdUncheckedLoadDiscElf

bin/resources/GameIndex.yaml
Added Blending Accuracy 3 for Spyro: Enter the Dragonfly
Added Blending Accuracy 3 to fix Gems not shining properly.
Just playing the game will show the visual improvement/correction on gems.
=> GameDB: Add Blending Accuracy to Spyro: Enter the Dragonfly

pcsx2/USB/usb-pad/usb-turntable.cpp, pcsx2/USB/usb-pad/usb-turntable.h
I missed this during review.
Prevents save states being created with the device connected.
CI passes.
=> USB-Turntable: Implement Freeze()

.github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/macos/build-dependencies.sh
qtimageformats provides image plugins for tiff, webp, and others.
Users tend to use these formats for covers. Windows was shipping the plugins, Linux/Mac were not.
Make sure Mac/Linux builds still work.
You could try a webp cover too I guess.
=> CI: Add qtimageformats for Linux/Mac

bin/resources/GameIndex.yaml
Changed halfPixelOffset from 1 to 2 for Spyro: A Hero's Tail
This fixes some effects (like blackscreens when loading stuff in the background) still being missaligned with halfPixelOffset=1 and others are also better aligned.
Example, it's a bit hard to notice, but you can see one line of pixels not being black at the top:
Starting up the game and seeing the black screen right before the main menu loads, and also you can see the glow effect on the black gem in the background of the main menu.
=> GameDB: Change halfPixelOffset to Spyro: A Hero's Tail

pcsx2-gsrunner/Main.cpp
=> GSRunner: Fix Unicode command line on Win32

bin/resources/GameIndex.yaml
"Need for Speed - Underground" NTSC-J has SLPM-65471.
https://wiki.pcsx2.net/Need_for_Speed:_Underground
http://redump.org/disc/33880/
"Firefighter F.D. 18" NTSC-J has SLPM-65470:
https://wiki.pcsx2.net/Firefighter_F.D._18
http://redump.org/disc/38733/
=> GameDB: correct an entry

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Actually fixes the invalidate check when the target wraps.
And a regression from #9297.
See above.
Smoke test, dump run looks fine.
=> GS/HW: Use GetUnwrappedEndBlockAddress() where appropriate

pcsx2/CDVD/IsoReader.cpp, pcsx2/CDVD/IsoReader.h, pcsx2/VMManager.cpp
If the main ELF on the disc is not a valid serial, display the ELF name instead.
Shortens "Unknown Game" to "[?]".
Better window titles.
Check known and unknown games (e.g. homebrew ELF, PSX game).
=> VMManager: Display title as serial or ELF

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Fixes a bug in double half clears and improves target buffer overlap detection for games which decide to keep swapping double buffering techniques (Grandia Xtreme, NCAA Football games, plus I think a Madden one is the same)
The double half thing was a misdetection, as it was a 32bit frame buffer with 16bit z, which would have failed the different type check, but it was expecting the framebuffer mask to be set to something other than 0, which it wasn't, as this wasn't a double half clear, it was just the Z butted up against the frame.
The double buffer changes, the modification to the existing overlap check was due mainly to the TextureMinMax function screwing the end block, but I think this code is better to make sure the new target completely covers the old one (hopefully no bugs)
The …
=> GS/HW: Fix Double Half Clear bug + better detect double buffer changes

bin/resources/GameIndex.yaml
Fixes a COP2 clip flag arrangement
it was incorrect, and may have been causing black screens in some situations (both renderers), so best to eliminate it.
Watch CI, patch already tested to make sure it doesn't explode
=> GameDB: Add patch for Shadow Hearts NTSC-U bad clip arrangement

pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
This was a thing for some game which stored texture data in the upper 8 bits of the framebuffer.
I hope our invalidation is better now, and we don't need the hack anymore. It's really annoying when debugging GS dumps.
(the target's alpha should not be valid, so it should always load from local memory in these cases).
Easier debugging, fewer uploads when saving state, more deterministic from loading state versus continuing.
Start a couple of games, smoke test.
=> GS/HW: Get rid of 2 frame forced preload

pcsx2/SIO/Pad/PadDualshock2.cpp
Reverts back to older behavior for pad command 0x46. Puts back some 1's where I thought we could put 0's.
Will need to do a deeper dive at a later time to understand what these bytes are truly doing, but games seem happier this way.
Fixes pad detection in NBA 2K7, possibly others.
Boot a game, see if the pad is responsive at all. Thorough tests not required, if there is a problem the game will either report no controllers are connected, or be completely unresponsive to inputs.
=> Pad: Revert back to old Constant 1 behavior

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
Enables one-barrier software blending for fullscreen quads.
We can also use tex-is-fb safely in these scenarios too.
We could also consider doing a "Quads to Sprites" conversion routine... not sure if it's worth it.
Fixes Persona 4 menu background, Hard Hitter Tennis shadows at Basic blending.
Lots and lots of diffs, but mostly tiny un-visually-distinguishable changes due to sw blending now being used.
But check Persona 4 I guess.
=> GS/HW: Assume primitive does not overlap if it is a single quad

pcsx2-gsrunner/Main.cpp, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Shamelessly stolen from the source because I can't be bothered to re-type it.
Burnout has a... creative way of achieving its bloom effect, to avoid horizontal page breaks.
First they double strip clear a single page column to (191, 191, 191), then blend the main framebuffer into this column, with (Cs - Cd) * 2. So anything lower than 191 clamps to zero, and anything larger boosts up a bit. Then that column gets downsampled to half size, makes sense right?
The fun bit is when they move to the next page, instead of being sensible and using another double strip clear, they write Z to the next page as part of the blended draw, setting it to 191 (in Z24 terms). Then the buffers are swapped for the next column, 0x1a40 and 0x1a60 in US.
We _could_ handle that, except for the fact that instead of …
=> GS/HW: HLE the Burnout games bloom effect

pcsx2-gsrunner/Main.cpp, pcsx2-qt/CMakeLists.txt, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/Settings/ControllerBindingWidgets.cpp, pcsx2-qt/Settings/USBBindingWidget_GunCon2.ui, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters, pcsx2/ImGui/ImGuiManager.cpp, pcsx2/ImGui/ImGuiManager.h, pcsx2/Input/InputManager.cpp, pcsx2/Input/InputManager.h, pcsx2/LayeredSettingsInterface.cpp, pcsx2/USB/USB.cpp, pcsx2/USB/USB.h, pcsx2/USB/usb-lightgun/guncon2.cpp, tests/ctest/core/StubHost.cpp
Smaller version of #8437.
In addition to the default pointer-based configuration, this PR allows you to bind a controller to aiming instead, which apparently some lightguns use.
Also adds custom cursors/crosshairs, which will hide the system cursor when active.
Closes #7891.
Closes #9256.
To test this with a controller, simply bind all four relative directions to e.g. an analog stick, and pick a crosshair image, so you can see where you're aiming.
Make sure mouse based aiming still works (clear all four relative axes by right clicking the bindings).
=> USB-GunCon2: Support binding to controller

bin/resources/GameIndex.yaml, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2/Config.h, pcsx2/Docs/gamedb-schema.json, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GameDatabase.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/Pcsx2Config.cpp
Some games don't like it when preloaded framebuffers get interpolated when upscaled.
So extend the previous force-bilinear hack to have a force-nearest option.
Fixes #9172.
@JordanTheToaster
=> GS/HW: Extend bilinear dirty upscale fix to force nearest

pcsx2/SIO/Pad/PadDualshock2.cpp
Changes Button Query command to respond depending on the current mode, rather than always reporting a full DS2 button layout.
Fixes CoD 3 not understanding which buttons the controller has available, perhaps others.
Test if games still accept input. Basic tests will do, e.g. pressing X on menu buttons or flipping through menus with the d-pad and analog sticks.
=> Pad: Change button query response depending on current mode

bin/resources/GameIndex.yaml
Adds said option to Racing Sim 3
Game was crashing on load going ingame due to bad data being downloaded, since invalidation didn't work correctly.
Watch CI
=> GameDB: Add Partial Target Invalidation to Racing Simulation 3

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Modify burnout OI hack to break the online mode less.
It was more brokerer
Test burnout online mode (and normal burnout games)
Fixes #9635
=> GS/HW: Modify Burnout IO CRC hack to not affect online mode screen

pcsx2-gsrunner/Main.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/Settings/AchievementLoginDialog.cpp, pcsx2-qt/Settings/AchievementLoginDialog.h, pcsx2-qt/Settings/AchievementLoginDialog.ui, pcsx2-qt/Settings/AchievementSettingsWidget.cpp, pcsx2/Achievements.cpp, pcsx2/Achievements.h, pcsx2/ImGui/FullscreenUI.cpp, tests/ctest/core/StubHost.cpp
Handles RetroAchievements tokens being reset gracefully by prompting the user to re-login.
Also extends the token lifetime by sending a login request each for each PCSX2 instance which uses achievements.
(I plan to move this over to rc_client eventually, but for now it's a band-aid fix for tokens getting reset.)
Better UX.
Test invalidating token (done myself).
=> Achievements: Log-in explicitly on startup to refresh the token

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Adjusts the downscale rect when doing the Burnout bloom HLE.
The rect was producing slightly incorrect results when compared to software mode, this makes native HW and SW look identical.
Test burnout games.
=> GS/HW: Tweak Burnout bloom CRC coords

bin/resources/GameIndex.yaml
- Before HW Parappa 2:
- After HW Parappa 2:
- SW Parappa 2:
Before HW Socom US Navy Seals Combined Assault:
After HW Socom US Navy Seals Combined Assault:
Before HW Socom US Navy Seals Combined Assault:
After HW Socom US Navy Seals Combined Assault:
Before HW Socom 3 Navy Seals:
After HW Socom 3 Navy Seals:
Before HW SSX 3 (recommended blending so only OSD notification):
After HW SSX 3 (recommended blending so only OSD notification):
Before HW SSX On Tour (recommended blending so only OSD notification):
After HW SSX On Tour (recommended blending so only OSD notification):
Before HW SSX Tricky (recommended blending so only OSD notification):
After HW SSX Tricky (recommended blending so only OSD notification):
Before HW Blood Will Tell (Dororo) Basic Blend:
After HW Blood Will Tell …
=> GameDB: Beeg fixing about everything

pcsx2/SIO/Pad/PadNotConnected.cpp
Switches disconnected pad from simulating 0xff on the data line to 0x00.
Fixes uLaunchELF spinning waiting for second pad to come online.
Boot any game or ELF known to probe second controller, with no second controller plugged. Game should finish boot and accept input from first pad.
=> Pad: Set data low when no pad present

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Fudges the CRC hack numbers a little bit to compensate better for upscaling.
Upscaling this effect sucks, and there's no *real* solution, but this gets it mostly lined up with all upscales, so it's less annoying.
Test Burnout 3+ games.
Master:
PR:
=> GS/HW: Adjust Burnout bloom CRC to work better with upscaling

bin/resources/GameIndex.yaml, pcsx2/Achievements.cpp, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GameDatabase.cpp, pcsx2/SIO/Pad/PadDualshock2.cpp
removes some old frame width hacks for blue tongue games, added to part of the CRC.
These hacks were breaking other games, namely Keroro Gunsou - Mero Mero Battle Royale.  Nicktoons Unite! amongst the others changes the width from 640 to 512, then uses the target temporarily as a Z buffer of a different size, then goes back to using it as a framebuffer, but this draw never really worked properly and was already being partially thrown on to the SW renderer.
Test some random games, make sure everything is okay, along with any Blue Tongue games (Jurassic Park, Nictoons Unite/Spongebob Volcano Island, Barnyard), and also Keroro Gunsou.
Fixes #9004 width problem with Keroro Gunsou - Mero Mero Battle Royale
=> GS/HW: Update Blue Tongue CRC and remove frame width hacks

pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
Fixes depth state in multistretchrect function for OpenGL
It was killing the depth test, which was used in SMT Lucifer's Call
Test above game (already done)
All changes courtesy of Stenzek
Look at the shadow
Master:
PR:
=> GS/OGL: Fix depth state in MultiStretchRects

pcsx2/GS/GSCrc.cpp, pcsx2/GS/GSCrc.h, pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSHwHack.cpp
Removes old CRC hack for Shin Megami Tensei - Nocturne
Doesn't seem to fix anything anymore, so no point in it being there.
Try Nocturne, make sure nothing is broke.
1 CRC hack left to get rid of..
=> GS: Kill SMT Nocturne CRC hack

pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SaveState.h
Fix vibration motors backwards and too low power delivery to small motor. Also fix inconsequential but (technically) incorrect return values for vibration mapping command. Fixes #9622 
Vibration motors were only partially working, but mostly broken.
Play games known to have vibration. Make sure your hands shake.
=> Pad: Fix vibration motors backwards and too low power delivery to small motor

pcsx2/GS/GSRegs.h, pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHWMultiISA.cpp, pcsx2/GS/Renderers/SW/GSRendererSW.cpp
Fixes the alpha test control result when AFAIL is RGB_ONLY and the framebuffer is not 32bit.
RGB_ONLY is only active when the framebuffer format is 32bits, in any other mode the control method will be FB_ONLY meaning 16bit will write to the alpha channel.
Test random stuff (or games listed below) make sure nothing is funny. Results test against PS2.
Fixes shadows in DNA - Dark Native Apostle
Fixes Fog/Lighting in Shrek 2
Fixes distant lighting in True Crime - Streets of LA
DNA:
Master:
PR:
Shrek 2:
Master:
PR:
True Crime - Streets of LA:
Master:
PR:
=> GS: Correct alpha test for RGB Only and non-32bit colours

pcsx2-qt/Translations.cpp
Adds missing Latvija option to the menu of selectable languages.
Missing languages are baaad.
Cerams, ka dators nesprāgst
=> Translations: Add Latvija to the menu

bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Metal/tfx.metal, pcsx2/ShaderCacheVersion.h
Fixes banding in Xenosaga, Tales of the Abyss, Beyond Good and Evil.
Closes #7272.
(before followed by after)
I've looked through 1,289 changed GS dumps and couldn't see anything which looked worse. The dumps above are a much closer match to sw now. So.. smoke test?
=> GS/HW: Don't drop fractional colour before modulating

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Some stuff still depends on it if it's done early (e.g. texture min/max).
Fixes bloom in Burnout 3 in DX11.
Test Burnout in DX11.
=> GS/HW: Update vertex trace in ReplaceVerticesWithSprite()

common/TextureDecompress.cpp, pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/Models/BreakpointModel.cpp, pcsx2/CDVD/IsoHasher.h
Fixes #9230
Decided to add some stuff as well
Fixes `-Wunused-variable` warnings
Fixes `-Wdeprecated-enum-enum-conversion` warning
Fixes `-Wsign-compare` warning
Fixes `-Wignored-qualifiers` warning
Debugger function was broken and caused a deadlock (not good)
Warnings are not desirable and should be addressed 
Does the `run-to-cursor` context menu action work?
Does the memory search function still work?
=> Debugger: Fix 'run-to-cursor' context action ft. warning fixes

bin/resources/shaders/common/fxaa.fx, bin/resources/shaders/dx11/convert.fx, bin/resources/shaders/dx11/interlace.fx, bin/resources/shaders/dx11/merge.fx, bin/resources/shaders/dx11/present.fx, bin/resources/shaders/dx11/shadeboost.fx, pcsx2/GS/Renderers/DX11/D3D.cpp, pcsx2/GS/Renderers/DX11/D3D11ShaderCache.cpp, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX11/GSDevice11.h, pcsx2/GS/Renderers/DX11/GSTextureFX11.cpp, pcsx2/GS/Renderers/DX12/D3D12ShaderCache.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.h, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
Feature level 11.0 GPUs were first released in 2009, almost 14 years ago now. Older GPUs have not had drivers released in a long time, and are known to be buggy.
None of us have hardware this old, so it's impossible for us to support it. And even then, there's no guarantee that we'll be able to work around whatever issue it is.
PCSX2 is not going to run well on this sort of hardware. But if for some reason you are silly enough to want to do this, you can always use the WARP device, probably in combination with the software renderer. But I doubt it'll run fast enough anyway.
Less dead code which we can't test/maintain.
Make sure FXAA in all renderers still works (I removed some unused bits there).
=> GS/DX11: Require feature level 11.0 

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Forgot to update the memory usage here..
Stops target memory usage stat underflowing in Ratchet.
CI passes - already checked it fixes it.
=> GS/HW: Fix target memory usage underflowing

pcsx2/SIO/Sio2.cpp
Remove erroneous auto eject decrement that was causing the system to not detect the card as removed.
Fixes issues with memory card swaps and savestate loads possibly causing inconsistent memory card states.
BACKUP YOUR MEMORY CARDS FIRST.
Boot BIOS or a game. Swap memory cards between slots, insert cards, eject cards. Game should recognize the card is being ejected and/or moved.
Create a savestate with one card inserted, switch your config to another card. Load the state, card should immediately eject, and insert a moment after.
=> Memcard: Remove erroneous auto eject decrement

bin/resources/GameIndex.yaml
Add missing entries and reorder some out of order entries.  List was provided by the Redump team (thank you guys for your hard work putting the list together).
python scripts to append these was done with the help of ChatGPT, some of the region/languages may be incorrect, but they can be amended if need be.
Missing stuff is bad.
Watch the CI
=> GameDB: Sort and append missing entried from Redump

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Fixes detection of reverse texture shuffles
Some games (for some reason or another) start the shuffle in the bottom right then work towards the upper left, probably to try and avoid overwriting data accidentally and making use of the texture cache (ps2 one)
Try games, mainly Smugglers Run and Midnight Club 2
Fixes #1958 Smugglers Run Shadows
Fixes #3102 Midnight Club 2 headlights
Midnight Club 2:
Master:
PR:
Smuggler's Run:
Master:
PR:
=> GS/HW: Improve detection of reverse texture shuffles

pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
If we're reinterpreting a Z24 target as C32, we can clear the alpha, don't need to convert it. If we're discarding RGB, we can skip the whole thing.
Allow fast clears even when the target is expanding to match the other RT/DS size. The contents of the other parts are undefined from the TC's perspective anyway.
Tiny tiny speed boost.
Smoke test, runner says it's good.
=> GS/HW: Minor optimizations

pcsx2-qt/MainWindow.cpp
It broke if you went jpg -> png -> jpg.
Closes #9672.
Change covers from jpg -> png -> jpg.
=> Qt: Fix changing cover file formats

pcsx2-qt/SetupWizardDialog.cpp, pcsx2/SaveState.cpp
This PR attempts to make the incompatible savestate message translatable, and adding clarification about the existing memory card.
More translation, the better
Make sure CI passes and the text looks right.
=> Qt: Make incompatible savestate message translatable

pcsx2/GS/Renderers/Common/GSTexture.h
Not needed anymore since it's unorm8.
Smaller struct size.
CI passes.
=> GS: Drop alignment from ClearValue

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
I added a condition for tex_is_rt but didn't use it...
Stops Ratchet turning into a flickery mess with DX11/GL renderers.
Closes #9684.
CI passes, but doing a dump run just to be safe.
=> GS/HW: Fix bilinear-over-self targets getting discarded

bin/resources/GameIndex.yaml
Fixes for the pretty awful brightness on pretty PS1 looking textures.
Fixes #9687 
Before:
Afer:
They look even worse without high blending despite that seemingly being impossible with how awful they look anyway.
=> GameDB: Go Go Golf Fixes

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Stop invalidating the buffers of a target just because we're displaying it.
This never made sense.
Only dump affected was Grand Prix Challenge, which is slightly improved, but still broken.
So usual smoke test.
=> GS/HW: Don't invalidate alpha on display target lookup

bin/resources/GameIndex.yaml
"SLKA-25323" is "FIFA 06", not "SSX on Tour".
"SSX on Tour" is misprinted as "SLKA-25323" on the game DVD cover,
so most Internet websites display "SSX on Tour" as "SLKA-25323", but this is clearly an error.
The DVD itself is clearly marked "SLKA-25325".
https://forums.pcsx2.net/Thread-Bug-Report-Serial-ID-SLKA-25323-its-name-is-incorrect
=> GameDB: entry correction

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Throwing away alternating lines is bad.
Closes #9689.
CI passes - dump run says it's fine.
=> GS/HW: Don't discard target when SCANMSK is set

bin/resources/GameIndex.yaml
Texture Inside RT was fixed in https://github.com/PCSX2/pcsx2/pull/9187
I'm an idiot sandwhich with rebase.
Test growlanser 5 and 6.
=> GameDB: Remove accidental addition Growlanser 5+6

common/FileSystem.cpp
Most of the credit here goes to @RedPanda4552 for debugging the folder memory card corruption.
stdio/std::FILE tends to defer flushing the write to the underlying OS file (FD). This is great, but becomes a problem when the file is being extended. See the following test code:
```cpp
std::FILE* fp = FileSystem::OpenCFile("D:\\foo.txt", "wb");
for (int i = 0; i < 512; i++)
{
char c = 0xff;
std::fwrite(&c, 1, 1, fp);
}
// std::fflush(fp);
s64 size = FileSystem::FSize64(fp);
std::fclose(fp);
```
When using filelength(), FSize64 returns 0, because the 512 byte write has been buffered, and not flushed to the file. Internally, filelength() does the same seek/tell/seek dance that we're doing manually, as seen here:
Adding the fflush above does fix the problem. But really, we may as well not …
=> FileSystem: Partial revert of c82f800

bin/resources/GameIndex.yaml
Based on:
https://github.com/PCSX2/pcsx2/pull/9671#issuecomment-1657337888
I do see a lot of the missing entries actually come from the PCSX2 wiki, and the csv was mostly duplicates but I checked and cleaned it up while looking at other things to potentially fix.
GGeneration is faulty naming though, G Genereration needs a space.
There are also 2 reasons why we don't fully follow redump: For starters Windows uses specific characters in their code and following that would make it impossible to make covers for them and some other things The other thing is when The blablabla  turns into blablabla, The for filtering purposes.
In future we should probably have a display language for specific languages, ex. Korean entries show Japanese, English or others
Easier for compiling as much information …
=> GameDB: Missing Korean entries + maintenance

pcsx2/SIO/Memcard/MemoryCardFolder.cpp
Apparently I didn't initialize the file path field. Which meant that files in the subdirectory weren't closed when the folder was deleted, which meant the path rename failed on Windows.
Regression from ea051c6. Nobody noticed in over a year :D
Test deleting a save in the BIOS with a folder memory card and filtering disabled. It should silently fail on master (with a log message about `MoveFileEx()` failing), but succeed on the PR.
=> MemoryCardFolder: Initialize hostFilePath

.github/workflows/release_cut_new.yml, .github/workflows/scripts/releases/announce-release/index.js, .github/workflows/scripts/releases/announce-release/package-lock.json, .github/workflows/scripts/releases/announce-release/package.json
Fixes previous attempt.  Overlooked the fact that it was able to grab the release info via the event payload (kicked off by a `released` event).  That's no longer the case, so the release has to be grabbed manually from the API.
I actually tested it this time - https://github.com/xTVaser/pcsx2-rr/actions/runs/5746987049/job/15577646112#step:10:19
=> ci: properly fetch release info to make announcement

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
First started and conceived by Stenzek, I continued his work while he slept :D  This PR will correctly use the alpha values for 16 bit and 24bit textures to improve the alpha min/max trace to help us optimise draws better, also rechecks if we require an alpha test.
Cool little idea to make the numbers better.
Test games, make sure nothing is broken.
Barnyard:
Draw Calls: -462 [2285=>1823] in one scene
Primal Image:
Draw Calls: -6712 [14796=>8084]
Barriers: -3483 [6967=>3484]
Syphon Filter (Omega Strain, I think):
Draw Calls: -290 [946=>656]
Go Go Golf
Master:
PR:
SOCOM 2:
Master:
PR:
=> GS/HW: Re-optimize alpha test after updating direct alpha range

pcsx2/Input/InputManager.cpp
Add a not to the multitap enabled check.
Fixes #9724 
Fixes incorrect logic where InputManager checks for multitaps.
Boot a multitap supported game, make sure mappings on slots B-D now work.
=> InputManager: Fix incorrect compare for multitap enabled

pcsx2/GS/Renderers/Metal/GSTextureMTL.mm
Klona 2, and maybe other games download a cleared buffer. FlushClears() will start a render pass (encoder) in this case, which means there's two encoders after the copy encoder is created, which is a no-no.
Fixes Klona 2 crashing on new game, maybe others?
Check affected games.
=> GS/Metal: Don't end up with two encoders on readback

pcsx2/SIO/Memcard/MemoryCardFile.cpp
Only show relative memcard formats in memcard screen.
It allowed you to load any file as a memcard, this could be bad if somebody thinks their game iso is a memcard (trust me, this isn't out of the realms of possibility)
put random crap files in your memcard folder, make sure you can only see your ps1/ps2/rawbin files.
=> UI: Only allow relative memcard files in memcard interface

pcsx2-qt/Settings/GameListSettingsWidget.cpp, pcsx2-qt/Settings/GameListSettingsWidget.h, pcsx2-qt/Settings/GameListSettingsWidget.ui, pcsx2-qt/SetupWizardDialog.ui, pcsx2/GameList.cpp
This PR adds an option to add entire directories to Excluded Paths, and not only the individual files.
Resolves #7126.
It's a reasonable request and might be useful if you scan recursively but want to exclude specific subdirectories.
1. Add a recursive search directory.
2. Add an excluded directory that is one of the subdirectories of the above directory.
3. Rescan.
4. Verify that the games from the excluded directory do **NOT** show on the game list.
=> GameList: Add an option to exclude entire directories

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
Recreate the rendering rect for a split draw done 1 page at a time.
The split shuffle couldn't handle 1 FBW wide splits before, and you ended up with a massive rect like 64x4096, which is obviously wrong.
Try random games as a smoke test, and test Need for Speed Hot Pursuit 2 as well.  Dump runner didn't show any other differences :(
Fixes #2942 NFS HP2 "Busted" screens.
Master:
PR:
=> GS/HW: Handle split shuffles with a width of 1

pcsx2-qt/SettingWidgetBinder.h, pcsx2-qt/Settings/AchievementSettingsWidget.cpp, pcsx2-qt/Settings/AchievementSettingsWidget.h, pcsx2-qt/Settings/AchievementSettingsWidget.ui, pcsx2/Achievements.cpp, pcsx2/Config.h, pcsx2/Pcsx2Config.cpp
This change adds a configurable duration for the Retro Achievements notifications. This PR also includes a minor update to the the BindSliderToIntSetting method to allow clamping of values when binding a slider to a setting in case of manual updates.
Fixes issue #9692 
Long durations on notifications can be intrusive to gameplay. This allows players to modify notification durations to their preference.
1. Enable Achievements,  Test Mode, and Notifications
2. Sign into RetroAchievements
3. Load a game with achievements
This PR affects all achievement notifications so the configured duration can be observed during the initial game info notification, when mastering a game, when unlocking an achievement, and when activating/submitting a leaderboard.
Game used for testing was Kuon …
=> RetroAchievements/Qt: Add configurable achievement notification duration

bin/resources/GameIndex.yaml, pcsx2/IPU/IPU.cpp, pcsx2/IPU/IPU_Fifo.cpp, pcsx2/IPU/IPU_MultiISA.cpp, pcsx2/IPU/IPUdma.cpp
Improves internal flow of data in the IPU and properly delays IPU before decoding.
I noticed Harley Davidson videos were running really laggy and freezing up, so it was obviously getting confused, so I tidied up the flow between the DMA's and IPU a little.
Also improved the Myst 3 patch to just wait until IPU is no longer busy instead of using some arbitrary number.
Test videos in games, make sure nothing is broken more than it was.
=> IPU: Improve DMA/IPU call locations to reduce looping

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
Happens in Crash: WoC. Z writes only happens on the second pass, and the condition I removed only checks the first pass.
I'm not sure on rationale behind this check, nulling out the depth buffer to avoid render pass restarts sounds like it'll cause the opposite, because it's likely that subsequent draws are going to use said depth buffer if it was supplied. The base class (GSRendererHW::Draw) takes care of disabling it in most cases.
Fixes #9734.
Test Crash WoC Level 4. I've only checked the AS build, since I still haven't bothered to figure out how to cross-compile. Will grab the CI build once it's up.
=> GS/Metal: Fix crash when Z write is on second pass

.github/workflows/macos_build.yml, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h, pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp, pcsx2/GS/Renderers/Vulkan/GSTextureVK.h, pcsx2/GS/Renderers/Vulkan/VKBuilders.cpp, pcsx2/GS/Renderers/Vulkan/VKBuilders.h, pcsx2/GS/Renderers/Vulkan/VKEntryPoints.inl, pcsx2/GS/Renderers/Vulkan/VKShaderCache.cpp, pcsx2/GS/Renderers/Vulkan/VKStreamBuffer.cpp, pcsx2/GS/Renderers/Vulkan/VKStreamBuffer.h, pcsx2/GS/Renderers/Vulkan/VKSwapChain.cpp, pcsx2/ShaderCacheVersion.h
Can result in up to a 6% perf improvement for GS+draw-bound games (which there aren't that many of). But every bit counts.
Also mandate a bunch of extensions which are supported by any PC hardware made in the last 10 years or so.
Note that I've disabled Vulkan in CI macOS builds now (not that anyone should have been using it), but left the scaffolding in place should MoltenVK decide to support these extensions in the future.
Vroom vroom
Usual smoke testing.
Make sure CAS still works.
=> GS/Vulkan: Use push descriptors instead of per-frame allocations

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
RenderDoc doesn't support it.
So, until it does, has to be optional. At least for this one, it won't result in incorrect rendering, just a changed index order, unlike e.g. line rasterization.
Making renderdoc work again.
Smoke test
=> GS/Vulkan: Make VK_EXT_provoking_vertex optional again

common/Misc.cpp, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
Fixes a bug where assertion failure messages weren't included in crash reports thanks to LTO optimizing out the crash report info
Better crash reports
~~Purposefully crash PCSX2~~ Hopefully there aren't any known ways to do this, or we should be fixing those
=> Mac: Better crash reports on assertion failures

common/SettingsInterface.h, pcsx2-qt/Settings/GameSummaryWidget.cpp, pcsx2-qt/Settings/GameSummaryWidget.h, pcsx2-qt/Settings/GameSummaryWidget.ui, pcsx2-qt/Settings/SettingsDialog.cpp, pcsx2-qt/Settings/SettingsDialog.h, pcsx2/GameList.cpp, pcsx2/GameList.h, pcsx2/VMManager.cpp
This PR adds an ability to override game names and regions on the list, which can be useful when using romhacks. With this change, two previously "identical" entries can be given unique names and/or regions. These attributes are being saved into a new `custom_properties.ini` file, where each **section** name is a full path to a file.
A new "Restore" buttons have been added to the Game Summary which restore the original property. Deleting the custom Title restores the default one.
To-do and/or agree on:
* ~~Should this be only possible for titles or also serials and regions?~~ It is titles and regions now.
* ~~Is an Edit button a good UX? Maybe those fields should just become editable as-is?~~ It is Restore instead now.
* Should the Game List sort again after quitting the summary? Right …
=> GameList: Support adding custom titles and/or regions to files

pcsx2/ImGui/ImGuiManager.cpp, pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/USB/usb-lightgun/guncon2.cpp
Also fixes it showing the cursor in the top-left instead of the middle, before the first position update comes in.
It wasn't usable without a windowed switch before.
Test relative mode in GunCon2 with start windowed and fullscreen.
=> USB/GunCon2: Fix cursor when starting fullscreen

pcsx2/DebugTools/DisR5900asm.cpp
Fixes an OOB access when disassembling an invalid opcode (71756972h)
The PMFHL/PMTHL opcode disassembly uses a special table to show the value of the `fmt` portion of the instruction.
We grab `fmt` with the same macro for `sa`, which happens to be too big for our PMFHL/PMTHL LUT.
All I've done is extend the LUT so I can mask it down to 0x7.
OOB memory accesses are unpredictable and ended up causing crashes.
In the memory view, put `0x71756972` and view that segment of memory with the disassembly viewer. The disassembly viewer should show `pmfhl.?? ...`
=> Dis5900: Mask and extend the pmfhl & pmthl LUT

pcsx2/GS/GSState.cpp
Fixes autoflush behaviour when drawing with colour format but texture is Z format at same address.
When using Z + C the coordinates for either are swapped when checking against the other, we didn't do this before, causing false flushes. This reduces drawcalls and mistakes when splitting draws which may be shuffles.
Also when formats don't match, try to do it by page if we can first, this catches some situations where it doesn't overlap, saving some flushes.
Also account for texture clamping to correct the texture coordinates.
Also added a tiny shortcut thanks for our existing temp draw buffer.
Test Driv3r, Xenosaga Episode 3 and a smattering of other games. Any listed below are good too.
Fixes Autoflush behaviour in Driv3r
Axel Impact
Barnyard
Beyond Good and Evil (in some scenarios that …
=> GS: Fix autoflush behaviour when using Z + C formats + improve performance

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Changes the Double Half Clear code to use the first part format as the "master" format, so for example if the bit depth is 24, and the second half is 32bit, this works fine, but not the other way around as the base needs 32bits.
~~Also added a GSC pass for the depth clear to fix up an issue the hardware renderer can't handle in Tiger Woods 2002~~
Spiderman - Web of Shadows was clearing the Z with this double half clear but using different bit depths for some reason, when the Z is only 24 bit in this game anyway.
~~the Tiger Woods 2002 situation is an annoying one I'm calling a "flipped clear", as the game only uses the Z on the menu for drawing Tiger Woods, which is 256x512, but then when it clears it, it does 512x256, which our hardware renderer doesn't understand correctly and only …
=> GS/HW: Allow double clear when base is lowest bitsize denominator

bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Metal/tfx.metal, pcsx2/ShaderCacheVersion.h
GS/HW: Cleanup texture shuffle shader and conditions.
Cleaner code.
Make sure texture shuffle games still work and nothing is broken, also make sure no bad shader files on all hw renderers.
Vulkan dump run on 456 dumps unchaged.
Smoke tested GL/DX on a few texture shuffle dumps.
=> GS/HW: Cleanup texture shuffle shaders.

bin/resources/GameIndex.yaml
Fixes  #9764 
also adds  recommendedBlendingLevel full for Ghost Recon - Advanced Warfighter
basic :
full :
SW:
Watch CI / check said game
=> GameDB: Fixes for Ghost Recon - Advanced Warfighter & Battlefield 2

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/Gif.cpp
Stops it halfing the height on a shuffle by accident.
Fixes problem where it could try and read a null RT
Adjusted how GIF Intermittent packets split.
Was too horny with the halving, so in some cases the actual size got halved, not just the doubled shuffle size.
Regression from #9745
null RT was possible if there was no RT but it was still reading a texture, possibly in an Alpha tested Z write situation.
Adjusted GIF intermittent packet timing to be a bit kinder to games without sacrificing speed.
Test Onimusha 3, Wallace & Gromit Project Zoo, Puzzle Quest, Motocross Mania 3. Make sure nothing is broken.
Fixes #6733 Puzzle Quest flickering graphics
Fixes Motocross Mania 3 flickering textures
Fixes Onimusha 3 bad height on shuffle, plus some invisible bad height changes in Haunting Ground …
=> GS/HW: Regression fixes and GIF Fix for Puzzle Quest/Motocross Mania 3

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Restrict double buffer detection to wider buffers.
It was getting false positives in The Suffering and breaking the shadow processing.
Test The Suffering.
=> GS/HW: Restrict double buffer detection to widths greater than 256

pcsx2-qt/QtKeyCodes.cpp
On macOS, Qt applies the Keypad modifier regardless of whether the arrow keys, or numpad was pressed.
The only way to differentiate between the keypad and the arrow keys is by the text.
Fixes #8690.
Test key mapping in MacOS.
=> Qt: Fix arrow key handling on macOS

pcsx2/USB/usb-pad/usb-turntable.cpp
I've noted that I must have accidentally set the multiplier to 0 by default instead of 1, which means that the turntable velocity would have just been zeroed out by default
By default one would expect the turntable to work
Set up a turntable, note that it is defaulted to 1.
=> USB-Turntable: Default multiplier to 1

bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/ShaderCacheVersion.h
GS/HW: Adjust how we handle RT alpha in blending.
When both rt min and max are equal then we know what Ad value is, if so use Af bit instead and set AFIX value from rt alpha value that we know.
On OpenGL when BLEND C == 1 but reading the rt is disabled, set the value to 0 instead of reading an undefined value.
Allows to use hw, blend mix/accumulation blend in more occasions.
Fixes KH2, Burnout Takedown  blending effect regressions.
Fixes #9753
Aside from the mentioned regressions dump runner shows no diffs.
Raw Danger -70 barriers +69 texture copies
Eternal Poison -1 barriers 
NFSU2 -2 barrier +1 texture copy, another dump -1 barrier
=> GS/HW: Adjust how we handle RT alpha in blending.

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Correctly remove offset from coordinates when checking if they are shuffle coordinates.
Forgot to do this before
No notable changes, it was wrong, YOLO once it builds
=> GS/HW: Correctly remove offset when detecting shuffle coords

.gitignore
Don't include txt files that are generated when PCSX2 crashes as part of git changes.
Cleanliness, stop Git from being annoying
N/A
=> gitignore: Don't include TXT files generated by crash dumps

pcsx2/SIO/Pad/Pad.cpp, pcsx2/SIO/Pad/PadBase.h, pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SIO/Pad/PadGuitar.h, pcsx2/SIO/Pad/PadNotConnected.cpp, pcsx2/SIO/Pad/PadNotConnected.h, pcsx2/SIO/Pad/PadTypes.h, pcsx2/SaveState.h
Switches triggers to use the normal button deadzone value. They were left behind after the old separate trigger deadzone UI option was removed. 
Fixes #9744, button deadzones will work again for triggers.
Boot the pad tester elf, test that the triggers now respect deadzone.
=> [SAVEVERSION+] Remove old trigger deadzone references, replace with button deadzone

pcsx2/GS/Renderers/DX11/GSDevice11.cpp
Saw this when checking #9787. Stops the discard happening later, and blowing away the cleared value.
Doesn't fix the actual issue (it needs autoflush+copies for DX, slowwww), but stops us reading undefined data, which is never good.
Smoke test. Didn't bother with a dump run, because DX is unreliable there on NV.
=> GS/DX11: Commit clear before clearing stencil

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Disallow the use/conversion of 16bit targets to PSMT8
The swizzle for these is not something the hardware renderer supports and the likelihood is the data it wants is actually coming from memory. In the case of Armored Core it was uploading the indexed texture in to the start of the Z buffer, a part which wasn't being used, and this was confusing the hardware renderer.
Test Armored Core Nexux shop parts screen + smoke test, confirmed GS Dump works.
Fixes #9799
Armored Core Nexus:
Master:
PR:
=> GS/TC: Don't allow tex is rt for PSMT8 on 16bit targets

bin/resources/GameIndex.yaml
Adds VU0 clamping to solve dialogue background problems
They were broken
Watch CI, game already tested
Master:
PR:
=> GameDB: Add VU0 clamping to Naruto Ultimate Ninja 5 (Accel 2)

bin/resources/GameIndex.yaml
Fixes clip flag ordering for Initial D - Special Stage
It was in an order which doesn't work on PCSX2, this corrects it.
Watch CI
=> GameDB: Add COP2 patch for Initial D - Special Stage (SLPM-65268)

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
If this is the first draw to the target as a feedback loop, make sure we re-generate the texture descriptor.
Otherwise, we might have a previous descriptor left over, that has the RT in a different state.
Happens in Dragon Quest 8.
Smoke test, dump runner says it's okay.
=> GS/Vulkan: Avoid incorrect-layout RT descriptor

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
GS/HW: Cleanup draw when pixels fail on alpha test/date.
Also make CleanupDraw use it's own function.
Currently we cleanup draw when pixels fail on alpha test in some cases, let's do the same for remaining case as well as destination alpha testing.
Dump run didn't show any changes.
=> GS/HW: Cleanup draw when pixels fail on alpha test/date.

pcsx2/SIO/Pad/PadDualshock2.cpp
Fixes #9796. Changes small vibration motor to only turn on if LSB is set in the value it was given.
Hardware tested. Motor only engages if turned on using a value with LSB set, aka any odd number. Fixes idiotic games like Resident Evil 4, which send 0x02 to the small motor during cutscenes.
* Let Resident Evil 4 boot and idle at the main menu, cutscene will start playing, verify controller does not rumble.
* Try other games known to use the small motor, make sure the motor still turns on when expected.
=> Pad: Only consider LSB for small motor vibration

pcsx2-qt/Debugger/MemoryViewWidget.cpp, pcsx2-qt/Debugger/RegisterWidget.cpp, pcsx2-qt/Debugger/RegisterWidget.h
Initialize primitive class members that would otherwise be of unknown values 
Also implement the "Copy Address" context menu for the memory view
It's my best idea to fix the indeterminate behaviour causing #9813
Try the FPR and VU0 register "show as hex" context menu options.
=> Debugger: Properly initialize primitive class members

bin/resources/GameIndex.yaml
Set VU1 clamping to Extra + Preserve Sign to avoid rare SPS.
Fixes #9817
Test said games. I played for ~20 minutes and everything seems to work ok.
=> GameDB: Change VU1 clamping mode for Naruto 2

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Fixes missing null check on Growlanser CRC hack.
wasn't checking if tsrc was null, then tried to use it.
Start a new game of Growlanser V, make sure it goes ingame.
Fixes #9827
=> GS/HW: Fix CRC hack for Growlanser V not checking for null

bin/resources/GameIndex.yaml
Removed EE Round Mode from Armored Core 3 and Armored Core Silent Line.
Current master forces Nearest rounding to fix Z-fighting, but it causes below problems:
- In Armored Core 3, intro cutscene of "Disable Pulse Generator" mission gets glitched.
- In Armored Core Silent Line, vertical lasers get vanished in "Secure Fortress NK-432" mission.
Chop/Zero rounding doesn't cause them, but it gets Z-fighting come back, so #2398 might be reopened.
Test mentioned mission levels.
=> GameDB: Remove EE Round Mode from Armored Core 3 games

bin/resources/GameIndex.yaml
Adds EE Timing fix to Gunfighter II to help fix texture flickering.
GIF FIFO is no longer enough.
Wait for CI To say it's okay, and wait for Sten to fix builds so libzip doesn't explode anymore.
=> GameDB: Add EE timing fix to Gunfighter II

bin/resources/GameIndex.yaml, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.h, pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2/Config.h, pcsx2/GS/GSRegs.h, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/Common/GSDirtyRect.cpp, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSHwHack.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSRendererHWMultiISA.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h, pcsx2/GameDatabase.cpp, pcsx2/GameDatabase.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/Pcsx2Config.cpp
Overhauls a bunch of the GPU invalidation to try and make it suck less.
It wasn't brilliant and broke down in many places.
Test anything you like, reports of broken games are welcome (and GS dumps) but this is WIP for now.
Fixes Indiana Jones as originally noted here #8971.
Fixes https://github.com/PCSX2/pcsx2/issues/9143 MGS3 garbage.
Fixes #8883 Radiata Stories fireplace shadows.
Fixes regression on Dark Cloud 2 faces.
Fixes Kung Fu Panda FMV's.
~~Fixes DNA - Dark Native Apostle shadows (now match SW)~~ This was still broken, but fixed in another PR which merged.
~~Fixes subtle bug in True Crime NYC~~ Fixed by another PR which merged.
Improves Z invalidation (required for FFX once #9302 merges).
Fixes #9791 by deleting old targets which are no longer valid.
Fixes problem with the …
=> GS/HW: Rewrite invalidation function

bin/resources/GameIndex.yaml
Adds the HW fix for Blood Money to the US version.
I didn't think the US version was affected, so I didn't add it, apparently it is.
Watch CI
=> GameDB: Add Hitman Blood Money HW fix to the US versions

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Makes sure the alpha used is the vertex alpha on shuffles when TCC (Use Texture Alpha) is set to false (aka Vertex Alpha)
TEXA is basically ignored if the texture alpha of 16/24 bit is used but the alpha is ignored, this was happening for normal draws, but for shuffles it was always using TEXA.  This forces the values to be direct replacements, so the alpha goes unmodified. 
Annoyingly the only thing affected was the Official US Playstation Demo Disc 57 main menu, nothing else I have dumps for uses it, so, smoke test I guess..
Fixes #4090 Official US Playstation Magazine Demo Disc 057 main menu.
Master:
PR:
=> GS/HW: Don't use TEXA on 16/24 bit when TCC is set to Vertex alpha

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Avoids expanding dirty rects to the entire page when the block size is relatively small.
In FFX it draws 512x416, and it does some invalidation in the pixels between 416 and 448, we were expanding this to the whole page which covers 384->448, causing big black areas in the texture. This change isn't necessarily correct, but it's a lot closer, the only better solution is when the writes are this small, do per block offsetting, but that could get slow and gross.
Test scene transitions in the FFX intro, make sure the bottom corner doesn't have a big black box (already tested).  Smoke test.
Fixes FFX transitions.
=> GS/TC: Don't expand block offsets to page size when small

pcsx2/GS/GSClut.cpp, pcsx2/GS/GSLocalMemory.cpp, pcsx2/GS/GSLocalMemory.h, pcsx2/GS/GSLocalMemoryMultiISA.cpp, pcsx2/GS/GSState.cpp, pcsx2/GS/GSTables.cpp, pcsx2/GS/GSTables.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/SW/GSDrawScanline.cpp
They aren't just an offset of the base value like the color formats, but instead an xor of the associated color format
For example, PSMZ32 bp=16, what address is the block at (4, 0)?  The equivalent for CT32 would be (16+16 = 32).  Our old algorithm would do (16+(16^0x18) = 24).  But the actual value is (16+16)^0x18 = 56.
Note: This removes an optimization we had, as it's not compatible with the real GS algorithm.  RIP.  Hopefully it doesn't hurt performance too much, but if it does, I don't think there's much we can do about it.
Fixes #4309
Fixes #804
More accurate
- Test [FFX-DepthXor.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/12135947/FFX-DepthXor.gs.xz.zip)
- Test other dumps in case I broke something in the refactor
- Test performance and (maybe) be sad
=> GS: Fix sub-page addressing of Z formats

pcsx2/SIO/Pad/PadBase.cpp, pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SaveState.h, pcsx2/StateWrapper.h
[SAVEVERSION+] unfortunately, because I haven't moved everything over to StateWrapper yet.
Closes #9857.
Closes #9716.
Save state with button held, release, make sure it's released when you load.
=> Pad: Don't save button/analog state

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSHwHack.h
Removes Final Fantasy X CRC hack used for transitions.
Removed Texture in RT for FFX also, was needed for the Anima summon.
Actual problem with CRC hack was fixed with #9302
Texture in RT was used for its partial invalidation functionality, which is a permanently on thing now, so the hack is no longer required.
Test battle transitions make sure the corners look okay (they should) and Anima summons. Tested with GS Dumps so far only.
=> GS/HW: Remove Final Fantasy X CRC hack

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Ignores the rect size of uploads when checking if a target needs to be tossed when changing the width.
This seemed a bit unreliable as it can use the wrong width/rect to upload to, the likelyhood is, if the width has changed and it's not a shuffle, we probably want to toss it, as long as information has been uploaded.
Similar problem with Call of Duty World at War, it was resizing a target after dirtying it, and the rect was being translated, putting the dirty area in the wrong place, since our hw renderer doesn't really understand rescaling on width change.
Try Battle Assault 3 featuring Gundam Seed and a smattering of games to make sure it doesn't break anything. Dump runner only showed this and Baldur's Gate DA 2 as diffs but BG DA2 was an invisible change type one (this game generally …
=> GS/HW: Don't rely on transfer rect size if target width changes

pcsx2/SIO/Pad/Pad.cpp, pcsx2/SIO/Pad/PadBase.h, pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SIO/Pad/PadGuitar.h, pcsx2/SIO/Pad/PadNotConnected.cpp, pcsx2/SIO/Pad/PadNotConnected.h, pcsx2/SaveState.h
Buttons were stored twice, binary values were still getting saved.
Also stops scale/deadzone/etc getting saved to state.
Already tested, CI builds.
=> Pad: Don't serialize buttons or config

pcsx2/GS/GS.cpp
Toggles whatever's enabled on and off.
Closes #9683.
Test new hotkey.
=> Hotkeys: Add "Toggle On-Screen Display"

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
I probably broke this when I removed `preserve_rt_color` check from `preserve_depth` in refraction's invalidation PR.
Throwing away data is bad.
Dump run says it's okay, smoke test.
=> GS/HW: Fix depth getting discarded with DATE on

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Always calculate valid area and end block on new targets
Regression from #9745, was using the valid area to calculate target overlap and copying, but if the valid was empty due to it preloading from transfers, it was exploding, notably in WWE Smackdown Here Comes the Pain
Smoke test + WWE Smackdown Here Comes the Pain (already checked). Dump run said nothing else changed.
=> GS/HW: Always calculate valid area + end block on new targets (WWE Smackdown HCTP Crash)

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fixes `requires rgb/alpha` detection and modifies behaviour to semi resemble the old behaviour.
We don't really deal with the alpha channels properly if it's expecting some level of preloaded stuff, we kinda fall over.  The old code used to just check if RGB was valid for normal formats, but that cause problems with games storing fonts in the alpha channel, but now the detection is improved to do similar, unless only the alpha is required, then the alpha is checked.
Test random games and Hitman 2 + Tony Hawk Pro Skater 4
Fixes Tony Hawk Pro Skater 2 black screen
Fixes Hitman 2 black screen
=> GS/HW: Fix up and restore some old valid channel behaviour

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Clear old targets of different formats when the correct type is not found.
Game was clearing the Z buffer with C32, then using it at half height as Z16S, but the target was staying huge and now being classed as a Z texture, and it was storing textures inside this, causing masses of uploads (it's still bad, but 500 vs 1800, more like it used to be) So this removes old targets of different formats on clears.
Test a new game on Shadow Hearts, make sure the uploads isn't going above 600
Shadow Hearts_SLUS-20347_20230715001123
Draw Calls: -956 [3577=>2621]
Render Passes: -1904 [1912=>8]
Copies: +1 [1=>2]
Uploads: -956 [1343=>387]
=> GS/HW: Kill old opposite type targets on clears

bin/resources/GameIndex.yaml
Adds VU0 clamping Extra + Sign to Sky Odyssey to fix the line thickness of runways.
It was incorrect before.
Watch CI
Fixes #9878
Master:
PR:
=> GameDB: Add VU0 clamping Extra + Sign to Sky Odyssey

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Only allows a depth source to be selected if the rect it wants fits inside the target.
Conflict - Vietnam draws a single dot with 0x2300 as the depth location, then uploads its FMV frames to 0x2300, but doesn't get stopped by the dirty because it draws another single dot between frames, so it ends up picking this single dot as the source/frame over the actual frame.
Test Conflict - Vietnam
Fixes #9884
=> GS/TC: Only look up alternate depth sources if inside the target

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Avoids targets with no size being made in the texture cache
Sometimes the PCRTC circuits get enabled with rubbish sizes, this confuses the texture cache, and it was ending up with targets covering the entire GS memory.
Also sets the end block to match the start block on new targets, rather than the end of memory, just in case it does somehow not update it, it won't span the entire memory.
Test the FMVS on Taiko no Tatsujin - Tatacon de Dodon ga Don
Fixes #9883
=> GS/TC: Avoid no size targets being made

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Allows checking for primitive gaps to allow reverse draws starting from the bottom.
Also remove Tex in RT for Dragon Quest VIII
Without gaps didn't allow vertical mode to look in reverse (I didn't do the horizontal equivalent, maybe we should..), which is something DQ8 does, this was causing it to fail to notice it being a new render target and kept the old one, which made a further texture lookup kill the target as it overlapped errantly.
Tex in RT is also being removed from DQ8 as it seems to do more harm than good these days and the game seems fine without it.
Test Dragon Quest VIII (a few areas with and without water/fire, transitions/fmvs etc) and some random other games, make sure everything is fine.
Primitive check change:
Master:
PR:
Tex in RT change:
Master (simulated):
PR:
=> GS/HW: Allow reverse primitive gap checking

.github/workflows/scripts/windows/build-dependencies.bat
Backpatch the fix from Qt for monitor identification post 6.5.2
They made a change to monitor detection, released 6.5.2 (which we updated to) realised the monitor detection was broken and reverted it. This pulls in the revert.
If your PCSX2 was opening on the wrong monitor, try this.
=> Build: patch in Qt monitor fix from post 6.5.2

pcsx2/windows/PCSX2.manifest
removes references to Vista and Windows 7
PCSX2 no longer supports Vista and Windows 7 & Windows 8/8.1
make sure PCSX2 still works on Windows
=> Build: remove references to Vista and Windows 7 & Windows 8/8.1

bin/resources/GameIndex.yaml
Fixes black and white colors in hardware renderers.
No cpuCLUTRender set:
Software:
cpuCLUTRender: 2
Added cpuCLUTRender: 2 to GameIndex.yaml to fix the grayscale colors while playing the game using hardware renderers. 
The game looks fine in software mode, but doesn't in any hardware renderer. This game is part of a series of Model 2 arcade ports Sega did that leave these grayscale textures unless cpuCLUTRender: 2 is used (like Sega Rally 95). 
Launch the game and start a normal match. The mech selection screen will be the first thing you see with issues.
=> GameDB: Set cpuCLUTRender to 2 for Sega Ages 2500 Vol.31 Virtual On (SLPM-62767)

common/CMakeLists.txt, common/SmallString.cpp, common/SmallString.h, common/common.vcxproj, common/common.vcxproj.filters, pcsx2/GameList.cpp, pcsx2/ImGui/FullscreenUI.cpp, tools/generate_fullscreen_ui_translation_strings.py
Chonker of a PR to make the big picture UI localizable. I added a "small string" class to avoid heap allocations on returning translated strings, because doing hundreds of allocations on every frame is nasty as heck. In the future, we could potentially do compile-time hashing here, but I don't think it's worth it, at least at the moment.
I've probably missed a few strings, but they're easy enough to tag later.
For CJK, I'll probably switch over to Noto instead of the system font, the latter looks kinda terrible, and I don't feel like dealing with fontconfig (*shudder*) on Linux.
Last remaining part of PCSX2 to be localized before next version.
Make sure functionality in the Big Picture UI still works (e.g. settings, achievements, game grid, file selection).
=> FullscreenUI: Make localizable

bin/resources/GameIndex.yaml
Replace the EE timing fix with EE cycle rate 300% which seems to work better for this game.
Does better than the existing hacks, for the one weirdo who actually gets pleasure out of playing this shovelware.
Watch CI
=> GameDB: Replace EE timing with cycle rate on Robin Hood 2 - The Siege

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Resets the age of the source RT when doing a hardware move.
Age is supposed to be reset when the target is being used, so it was likely just an oversight.
Check Waga Ryuu o Miyo - Pride of the Dragon Peace
Fixes #6950
=> GS/TC: Update source age on HW move

common/FileSystem.cpp, common/Linux/LnxHostSys.cpp, pcsx2/Linux/LnxFlatFileReader.cpp
We don't have 32-bit builds anymore, so no need to explicitly use 64-bit file function variants.
Closes #8398.
Make sure dual layer DVD dumps still load on Linux.
=> Misc: Drop stat compatibility calls

common/SettingsWrapper.cpp, common/SettingsWrapper.h, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/Settings/EmulationSettingsWidget.cpp, pcsx2-qt/Settings/SettingsDialog.cpp, pcsx2-qt/Settings/SettingsDialog.h, pcsx2-qt/Settings/SettingsDialog.ui, pcsx2/Config.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Pcsx2Config.cpp
Adds copy global settings and reset per-game settings buttons.
Fixes crash when changing language with big picture open.
Adds an option to stop big picture when it's running (and no game is).
Closes #9881.
Closes #9110.
Test listed stuff above.
=> Qt: Misc stuff

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Prevents incorrect-state descriptor.
Validation errors bad.
Smoke test Vulkan.
=> GS/Vulkan: Clear primid texture binding before prepass

.github/workflows/scripts/macos/build-dependencies.sh, pcsx2/Input/SDLInputSource.cpp
Previously discussed on Discord the other week. When MFI is enabled in SDL, plugging a controller in seems to pick a fight between MFI and SDL's HIDAPI, and you get multiple connection events for the same joystick instance.
Based on Tellow's suggestion, I tried disabling MFI, and it stops the duplication. Presumably this will mean that some controllers that are not supported by HIDAPI will no longer work? There's also still an IOKit backend, however...
I also worked around it on our side, so it won't duplicate, but that's not a great solution, because you end up with the player ID (`SDL-#`) changing, which breaks your binds. Disabling MFI ensures it always reconnects as #0.
Fixes duplicate controllers showing up on MacOS.
Test replugging controllers on MacOS.
=> CI: Disable MFI joystick for SDL on MacOS

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Remove horizontal offset from start invalidation page.
This is handled later, so we shouldn't do this too early. It was breaking SOCOM 3 loading screens due to the invalidation being offset correctly on the target, but the width was different, so it was getting in a mess.
Not really much to test, did a dump run, was fine.
SOCOM 3:
Master:
PR:
=> GS/TC: Ignore horizontal offset in invalidation start position

bin/resources/GameIndex.yaml
Fixes for slow performance and shadows being less broken now.
Before:
After:
Game performance bad made more gooder.
=> GameDB: DT games various fixes

pcsx2/Counters.cpp
Resetting the vsync counter state to render every time `UpdateVSyncRate()` is called can end up missing GS IRQs and the CSR flip.
This was ultimately the cause of #9929, but #9933 also fixes it because it avoids calling `UpdateVSyncRate()` in the config change scenario.
Ultimately we need both to be correct, but I split them into two separate PRs, because of the (slim) chance of regressions.
Not skipping IRQs.
Smoke test a few games, preferably both PAL and NTSC. Need to boot them from the start, not load state.
=> Counters: Don't skip vblanks on video mode change

bin/resources/GameIndex.yaml
Fixes missing textures in the game. For example, in the cutscene before the final boss.
=> GameDB: Add VU Clamping to Twisted Metal - Head-On

bin/resources/GameIndex.yaml
Added Upscaling fixes to King's Field IV
Removes white lines on sky and lava when upscaling.
[King's Field IV - The Ancient City_SLUS-20318_20230909214438.gs.zip](https://github.com/PCSX2/pcsx2/files/12566595/King.s.Field.IV.-.The.Ancient.City_SLUS-20318_20230909214438.gs.zip)
closes #3811
=> GameDB: Upscaling fixes for King's Field IV

pcsx2/Config.h, pcsx2/Counters.cpp, pcsx2/Counters.h, pcsx2/GS.cpp, pcsx2/GS.h, pcsx2/GSDumpReplayer.cpp, pcsx2/Hotkeys.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/PerformanceMetrics.cpp, pcsx2/PerformanceMetrics.h, pcsx2/SPU2/SndOut.cpp, pcsx2/SPU2/SndOut.h, pcsx2/SPU2/SndOut_Cubeb.cpp, pcsx2/SPU2/spu2.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
No more messing with counter state on setting changes. It was really bad before, thanks to wx rubbish.
Closes #9929.
Test NTSC and PAL games, make sure frame rates are correct.
Make sure vsync and sync to host refresh works as expected.
Check frame pacing, make sure it's the same as before.
=> VMManager: Rewrite frame limiting

pcsx2-qt/GameList/GameListModel.cpp, pcsx2-qt/GameList/GameListModel.h, pcsx2-qt/GameList/GameListWidget.cpp, pcsx2-qt/GameList/GameListWidget.h, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/MainWindow.ui, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/SettingWidgetBinder.h, pcsx2-qt/Settings/BIOSSettingsWidget.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/InputBindingDialog.cpp, pcsx2-qt/Settings/InputBindingWidget.cpp, pcsx2-qt/Settings/InputBindingWidget.h, pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp, pcsx2-qt/Themes.cpp, pcsx2/Patch.cpp, pcsx2/Patch.h, pcsx2/VMManager.cpp, pcsx2/VMManager.h
See commit lists, UI stuff is so boring these days that I can't be arsed re-writing it.
Closes https://github.com/PCSX2/pcsx2/issues/6159.
Closes https://github.com/PCSX2/pcsx2/issues/8044.
Closes https://github.com/PCSX2/pcsx2/issues/9869.
Closes https://github.com/PCSX2/pcsx2/issues/9914.
Closes https://github.com/PCSX2/pcsx2/issues/7215.
Closes https://github.com/PCSX2/pcsx2/issues/4634.
Closes https://github.com/PCSX2/pcsx2/issues/9139.
Closes https://github.com/PCSX2/pcsx2/issues/7681.
Test linked issues.
=> Qt: Bug fixes

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/VUops.cpp
Restores the scissor after a hardware draw is finished.
We can mess with the scissor during a draw, and if this doesn't get updated by writing to SCISSOR or XYOFFSET then it will retain the fiddled scissor, even if it's not correct for the next draw, this corrects that.  It was very prevalent in the Crash Tag Team Racing menu where it would stop updating the lower 2/3 of the image after a period of time.
Test Crash Tag Team Racing (idling in the menu and seeing if it screws up is probably good enough), and smoke test some other games
=> GS/HW: Restore scissor after draw

pcsx2/x86/ix86-32/iR5900.cpp
Skips handling exceptions when FlushCache and iFlushCache syscalls
The cache isn't supported in the recompiler anyways. It might increase performance by a little bit
Benchmark EE heavy games
=> iR5900 Recompiler: Skip exception handler for (i)FlushCache syscalls

pcsx2-qt/DisplayWidget.cpp, pcsx2-qt/DisplayWidget.h, pcsx2-qt/MainWindow.cpp
Fixes returning from fullscreen putting the main window in fullscreen mode on MacOS.
I limited it to MacOS, because I can't be arsed testing to see if Lameland hates it, which it might.
Fix janky fullscreen behavior.
Test entering and returning from fullscreen in MacOS. Make sure it no longer stays fullscreen.
Make sure I didn't break fullscreen on Windows/Linux.
=> Qt: Fix returning from fullscreen on MacOS

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Don't allow PCRTC frames to pull from depth
Depth should never be something used as an output frame, and this was causing problems with Neo Contra where instead of pulling from GS memory, it was copying from an old depth buffer.
Try Neo Contra, and I guess some random stuff.
Fixes Neo Contra FMV's
Master:
PR:
=> GS/HW: Don't allow PCRTC frames pull RGB from depth

bin/resources/GameIndex.yaml
GameDB: Various gs hw fixes.
Kazoku Keikaku - Kokoro no Kizuna:
Replace gpuTargetCLUT with cpuCLUTRender, fixes black letters.
Ricky Ponting International Cricket 2007:
Change mipamp basic to mipmap full with ps2 trilinear. Add cpuSpriteRenderBW 4, fixes garbage menus.
Add the hw fixes to all serials.
Add recommended blend level to full, to fix dark stage.
Cat in the Hat, The:
Add full mipmap with ps2 trilinear, improves textures to match sw renderer.
Fixes https://github.com/PCSX2/pcsx2/issues/9804, relevant https://github.com/PCSX2/pcsx2/issues/9039
Fixes https://github.com/PCSX2/pcsx2/issues/7174
Fixes https://github.com/PCSX2/pcsx2/issues/5507 remaining issues
CI passes
=> GameDB: Various gs hw fixes.

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHWMultiISA.cpp, pcsx2/GS/Renderers/SW/GSRendererSW.cpp
GS: Remove fm_mask parameter from TryAlphaTest.
Not used, we get the value locally instead.
Cleaner code.
CI passes, alpha test works.
=> GS: Remove fm_mask parameter from TryAlphaTest.

pcsx2/Dmac.h, pcsx2/GS.cpp, pcsx2/Gif_Unit.cpp, pcsx2/Gif_Unit.h, pcsx2/IPU/IPU.cpp, pcsx2/IPU/IPU.h, pcsx2/IPU/IPU_Fifo.cpp, pcsx2/IPU/IPU_MultiISA.cpp, pcsx2/IPU/IPUdma.cpp, pcsx2/IPU/IPUdma.h, pcsx2/MTVU.cpp, pcsx2/SaveState.h, pcsx2/Vif0_Dma.cpp, pcsx2/Vif1_Dma.cpp, pcsx2/Vif1_MFIFO.cpp, pcsx2/Vif_Codes.cpp
Correct the DMA Stall for VIF MFIFO, correctly delay GIF FINISH interrupts
Improve IPU Core/DMA call flow
The DMA Stall was pointing to normal VIF so this would have hung in some situations, especially when using Instant DMA.
GIF FINISH was being set immediately, so any games which were watching for the interrupts could have started processing it too early.
For IPU the timing of the DMA's is just gross and it was getting messy, so I've attempted to clean this up somewhat and make it make more sense to how the rest of the emulator works.
Nothing specific (Except Batman Begins FMVs), just test stuff, if you know what games use MFIFO and FINISH then you're certainly going to be able to target things well :P I can't think of a list of games off-hand though. Also test random FMV's, make sure …
=> VIF: Correct DMA stall for VIF1 MFIFO - Improve IPU Core/DMA call flow

pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Improves clear detection when using multiple quads
before it only checked one triangle, but also it didn't properly set the mode to sprites, even though it was replacing triangles with sprites.
Test Dropship and Grand Prix Challenge, and test random games (bonus if you know they double half clear)
Dropship:
Master:
PR:
Grand Prix Challenge (still wrong, but not ever other line wrong, solid as it should be)
Master:
PR:
=> GS/HW: Improve clear detection with multiple Tris

pcsx2/Gif_Unit.h, pcsx2/MTVU.cpp
Don't check current patch when checking busy paths.
It's possible the current path may show as busy to be cleared later, but Finish won't recheck, so let's just ignore the current path.
Check SMT Nocturne
Fixes SMT Nocturne loading
=> GIF: Don't check current path for FINISH

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fixing up some tex in rt bugs
Fix split shuffles when the first draw overdraws too much.
bugs are buggy, but also needed to ignore the swizzle when checking tex in rt.
Split shuffle detection failed if the game decided to draw too many pages, which happened with Jurassic - The Hunted where they decided to draw an extra row of pages (I guess they forgot to change it from the PAL version), but the next draw matched the half way point of the render target.
No dumps showed any diffs, I guess smoke test, or any games you know need tex in rt
Test Jurassic - The Hunted.
Jurassic - The Hunted:
Master:
PR:
=> GS/HW: Tex in RT fixes handling shuffles

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Properly size RT in Sonic Unleashed CRC
It wasn't scaling so it broke when upscaling.
Watch CI, already tested.
Master:
PR:
=> GS/HW: Properly scale RT in Sonic Unleashed CRC

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Ignore alpha requirement for 24bit textures
If we aren't using the alpha, we have no need to require it.
Fixes Lord of the Rings Third Age, nothing else showed up in the GS dump run of 1800ish dumps. Smoke test I guess.
Master:
PR:
=> GS/HW: Don't require alpha when requesting 24bit

pcsx2/GS/GSClut.cpp, pcsx2/GS/GSClut.h, pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Redo some of the double half clear checks to try to catch the cases better.
There was a lot of problems with misdetections, especially if no targets existed, making some bad targets being created. Naturally I ended up going down a spiral of regressions, so it went a bit further than I was hoping.
Also makes sure we don't flush on CLUT reload if the current draw isn't using a texture, unless the current draw is the new CLUT.
MGS thermal vision has many less draws now, but now has an upload due to a Double Half Clear misdetect, since the code is hit early due to a CLUT upload before the new context is set up.  The solution to this is going to be to delay CLUT reloads until it tries to draw more, but that's out of scope of this PR. Currently mitigated with `GS/HW: Assume not a DHC if clut …
=> GS/HW: Redo some double half clear checks + Reduce CLUT flushes

.github/workflows/macos_build.yml, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
MoltenVK does not support VK_EXT_line_rasterization. We want it for other platforms, but on Mac, lines aren't going to be correct in Metal either.
Apparently Intel's Metal driver is dogs**t slow, and MoltenVK's defer-recording-until-submit-time can end up faster, because we submit on a worker thread.
On Apple Silicon, it's the opposite. Metal is faster than MoltenVK (not unexpected), but as soon as blending gets involved, performance utterly tanks (in Vulkan) because of the barriers on my M2 Pro. Don't have any Intel machines to check.
Test MoltenVK on MacOS.
=> GS/Vulkan: Make line rasterization optional on MacOS

pcsx2-qt/Debugger/DebuggerWindow.ui, pcsx2-qt/GameList/EmptyGameListWidget.ui, pcsx2-qt/GameList/GameListWidget.ui, pcsx2-qt/Settings/AchievementSettingsWidget.ui, pcsx2-qt/Settings/AdvancedSettingsWidget.ui, pcsx2-qt/Settings/AudioSettingsWidget.ui, pcsx2-qt/Settings/BIOSSettingsWidget.ui, pcsx2-qt/Settings/ControllerBindingWidget.ui, pcsx2-qt/Settings/ControllerBindingWidget_DualShock2.ui, pcsx2-qt/Settings/ControllerBindingWidget_Guitar.ui, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.ui, pcsx2-qt/Settings/ControllerMacroEditWidget.ui, pcsx2-qt/Settings/DEV9SettingsWidget.cpp, pcsx2-qt/Settings/DEV9SettingsWidget.ui, pcsx2-qt/Settings/DebugSettingsWidget.ui, pcsx2-qt/Settings/EmulationSettingsWidget.ui, pcsx2-qt/Settings/FolderSettingsWidget.ui, pcsx2-qt/Settings/GameFixSettingsWidget.ui, pcsx2-qt/Settings/GameListSettingsWidget.ui, pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2-qt/Settings/InterfaceSettingsWidget.ui, pcsx2-qt/Settings/MemoryCardSettingsWidget.ui, pcsx2-qt/Settings/USBBindingWidget_DrivingForce.ui, pcsx2-qt/Settings/USBBindingWidget_GTForce.ui, pcsx2-qt/Settings/USBBindingWidget_GunCon2.ui, pcsx2-qt/Settings/USBDeviceWidget.ui, pcsx2-qt/Translations/pcsx2-qt_en.ts
This PR removes some stray translation strings that doesn't show up at all in the interfaces like so:
Squeaky Clean ✨
CI Passes, tested locally.
=> Qt: Removes stray strings from translations

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Resizes the rect based on the half way point as a base rather than going from the end of the previous rect.
some games stopped at the previous pixel, in the case of Spider-Man 2 it did 127x63, so adding on as we did before went to 127x126 instead of 127x127, meaning there was a line left over which didn't get cleared, and this was evident in the shadow
Test Spider-Man 2, nothing else in the dump run seemed to be affected.
Fixes Spider-Man 2 (look at the pavement below Spider-Man)
Master:
PR:
=> GS/HW: Resize rect from half point on double half clear

pcsx2-qt/Settings/DEV9SettingsWidget.cpp, pcsx2-qt/Settings/DEV9SettingsWidget.h, pcsx2/Config.h, pcsx2/DEV9/ATA/ATA_Info.cpp, pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/DEV9/ATA/ATA_Transfer.cpp, pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp, pcsx2/DEV9/ATA/Commands/ATA_CmdPIOData.cpp, pcsx2/DEV9/DEV9.cpp, pcsx2/Pcsx2Config.cpp
Remove HddSizeSectors setting and instead use the file size to calculate the number of sectors
Additionally, a crash fix to handle invalid LBA accesses.
Previously it was possible to set size of the Hdd to a different value to the actual size.
Under such conditions we would report the set size, but report an error when trying to access beyond the end of the file.
This behaviour is unexpected and is pretty dumb.
Additionally, Some games (HDD Utility) would still attempt the read/write regardless of the reported failure, resulting in a emulator crash.
This change also makes it easier for a user to use their own dump, as we should no longer need to contend with GiB vs GB issues.
Unlike in Wx, the Qt build is only able to create a Hdd image in the settings UI, so we can remove the config …
=> DEV9: Don't Report Size setting for Hdd size, Instead use file size

pcsx2/SPU2/Mixer.cpp, pcsx2/SPU2/defs.h, pcsx2/SPU2/spu2sys.cpp
Some games leave paused voices hanging with volume turned on which results in dc offset. Filter it out.
Fixes #5337 
Test that audio still sounds fine.
=> SPU: DC filter output

pcsx2/VMManager.cpp
Fixing a problem where the strings called in the message "{0} cannot be performed while hardcore mode is active. Do you want to disable hardcore mode? {0} will be cancelled if you select No." were not translatable.
Assist translation efforts.
Make sure I did not mess things up.
=> [UI] Add achievement-related translatable strings

pcsx2/Achievements.cpp
Changed one line regarding the number of achievements unlocked and points earned in one popup.
Better consistency with the other references to the number of achievements unlocked and points earned in the rest of the achievements UI.
CI passes.
=> Achievements: Different choice of words in achievement popup

pcsx2/ImGui/FullscreenUI.cpp
Removing two strings that were remnants of DuckStation for Android. Suggested by Stenzek.
Less clutter for translators.
Make sure I did not break anything.
=> [UI] Minor tweaks on Big Picture

pcsx2/SPU2/Mixer.cpp, pcsx2/SPU2/defs.h, pcsx2/SPU2/spu2sys.cpp
The filter seems to introduce some small amount of gain
Should stop the samples overflowing.
That naruto game should be fine again.
=> SPU: Change order of dc filter and final clamp

pcsx2/GS/GSClut.cpp, pcsx2/GS/GSClut.h, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Attempt to reduce needless flushes of the GS context
Also fixing up some test draw changes code which was looking at the wrong context, not that it mattered apparently.
If the current vertex being written was only being queued but nothing was being drawn, there was no need to flush the context as it could revert back to the previous state by the next vert write.
Also no need to flush on CLUT change if the current texture being drawn is not indexed.
Test random games, biggest difference seen is in FF7 Dirge of Cerberus. Also check Tomb Raider Legends as it had some render size changes (actually looks clearer in places now).
Dirge of Cerberus stat changes:
1665->963 draw calls
287->335 fps
A bunch of other games had small reductions in draw calls but nothing significant, unfortunately.
=> GS: Reduce unnecessary flushes

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Make sure RGB is required on source lookup if using a 24/16bit source texture and using As for alpha blending with AEM enabled.
Before there was a scenario where it could only use the source for alpha blending, but that source had been cleared to black, and it used AEM to override the alpha values in TEXA, but because we weren't checking this, it was saying it didn't require RGB or Alpha and just getting any old junk, which broken the rendering in Dark Cloud (only thing I've found affected so far)
Test Dark Cloud, nothing else affected by a dump run.
Dark Cloud
Master:
PR:
=> GS/HW: Require 24/16bit RGB color if using AEM

pcsx2-qt/Translations/pcsx2-qt_en.ts, pcsx2/GameList.cpp
This PR fixes a single untranslatable that were found on the Cover Downloader.
Untranslatable string bad.
CI Passes.
=> Qt: Fix untranslatable string on cover downloader

pcsx2/Achievements.cpp, pcsx2/GameDatabase.cpp, pcsx2/Hotkeys.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/SIO/Pad/Pad.cpp, pcsx2/SIO/Pad/PadDualshock2.cpp
- Added numbers to all strings with more than one {} so translators who might not know that they can move those variables can, in fact, move them around the string.
- Tagged a number of untranslatable strings in Big Picture. Keep in mind that these are the strings that actually exist within the FullscreenUI.cpp file, as there's a number of those strings that do not seem to be taken from there (I do not know from where, though, so I'm leaving those out of scope). The FSUI_XSTR names have been added by guesswork, so more expert eyes are required.
- Ran the generate_fullscreen_ui_translations script, which removes that "Quick Save Slot" string that was inherited from DuckStation for Android.
Improving strings for translators with no knowledge of the intricacies of programming, adding missing …
=> UI: Changes for translators

pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SIO/Pad/PadGuitar.h
Adds additional details about vibration motor config and the specific button mapping requested by the game.
Might help with more rapid diagnosis of controller problems, specifically with games that do non-standard things with controller config.
Boot games, verify that controller config logs show up and show new info.
=> Pad: More detailed config logs

common/Pcsx2Defs.h, pcsx2/AsyncFileReader.h, pcsx2/CDVD/BlockdumpFileReader.cpp, pcsx2/CDVD/CDVDcommon.cpp, pcsx2/CDVD/CDVDcommon.h, pcsx2/CDVD/CDVDdiscReader.cpp, pcsx2/CDVD/CDVDdiscReader.h, pcsx2/CDVD/CDVDdiscThread.cpp, pcsx2/CDVD/CDVDisoReader.cpp, pcsx2/CDVD/ChdFileReader.cpp, pcsx2/CDVD/ChdFileReader.h, pcsx2/CDVD/CsoFileReader.cpp, pcsx2/CDVD/CsoFileReader.h, pcsx2/CDVD/Darwin/IOCtlSrc.cpp, pcsx2/CDVD/GzippedFileReader.cpp, pcsx2/CDVD/GzippedFileReader.h, pcsx2/CDVD/InputIsoFile.cpp, pcsx2/CDVD/IsoFileFormats.h, pcsx2/CDVD/IsoHasher.cpp, pcsx2/CDVD/Linux/IOCtlSrc.cpp, pcsx2/CDVD/ThreadedFileReader.cpp, pcsx2/CDVD/ThreadedFileReader.h, pcsx2/CDVD/Windows/IOCtlSrc.cpp, pcsx2/Darwin/DarwinFlatFileReader.cpp, pcsx2/GameList.cpp, pcsx2/Linux/LnxFlatFileReader.cpp, pcsx2/MultipartFileReader.cpp, pcsx2/VMManager.cpp, pcsx2/windows/FlatFileReaderWindows.cpp
Currently, we give a pretty crappy error if a user tries to open an invalid/corrupted file. Just "failed to open CDVD". This PR propagates errors from the file backends up to the host, so the user can get _some_ clue about what's going on.
Also cleans up a bunch of crusty old code in CDVD (still pretty yuck), `void funcname(void)`, get rid of `CALLBACK`, etc.
Check compressed and non-compressed ISOs on Windows and Linux.
Check starting direct from DVD on Windows and Linux (if possible).
=> CDVD: Report open errors to host

pcsx2-qt/Settings/EmulationSettingsWidget.cpp
Make a string available for translation.
Percentages take a non-breaking space between the value and "%" in French.
Settings->Emulation->Normal speed description
=> Qt: Make "100%" string available for translation

bin/resources/GameIndex.yaml
Changes the HPO of Xenosaga Episode III games to Special (Texture).
They looks better than HPO Normal.
CI Passes and nothing else is broke in the game.
=> GameDB: Xenosaga Eps III Fixes

bin/resources/shaders/dx11/convert.fx, bin/resources/shaders/opengl/convert.glsl, bin/resources/shaders/vulkan/convert.glsl, pcsx2/ShaderCacheVersion.h
Converts the non-metal shaders (metal already does this) for depth 16 -> rgb5a1 to use integer full range conversion
Most of the work done by Stenzek (I mostly just helped with the debugging and poked the code in lol)
The old way had off by 1 problems and was not really possible to get correct without coming across rounding issues.
Test Shadow Tower Abyss make sure the shadows render correctly and the screen isn't too dark.
Fixes #3281
Master:
PR:
=> GS/HW: Convert depth16->rgba16 shader to integer

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Correctly update dirty depth with the correct format, when local memory invalidates buffers.
this was always doing 32bit and making the depth buffer incorrect, which broke a bunch of games.
Test random stuff but also test Glass Rose, Kamen Rider, Warship Gunner 2, and Sakura Taisen
Fixes #9981 Karmen Riders missing characters in HW
Fixes #7553 Warship Gunner 2 shadows and geometry (the hull problem had been previously fixed but shadows were missing)
Fixes #1919 Sakura Taisen shadows (the ground was fixed previously)
Fixes Glass Rose missing ghosts in hardware
Glass Rose:
Master:
PR:
Kamen Rider:
Master:
PR:
Warship Gunner 2:
Master:
PR:
Sakura Taisen:
Master:
PR:
=> GS/HW: Update dirty depth in matching format

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSHwHack.h
remove Sakura Taisen CRC hack.
Actually breaks the menu and kills the shadows.
Watch CI, already tested
=> GS/HW: Remove CRC hack for Sakura Taisen

pcsx2-gsrunner/Main.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/Settings/ControllerBindingWidgets.cpp, pcsx2-qt/Translations/pcsx2-qt_en.ts, pcsx2-qt/Translations/update_en_translation.bat, pcsx2/CDVD/CDVDisoReader.cpp, pcsx2/CDVD/CsoFileReader.cpp, pcsx2/CDVD/GzippedFileReader.h, pcsx2/GameList.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/FullscreenUI.h, tests/ctest/core/StubHost.cpp
Nails a bunch of recent warnings introduced when using clang-cl.
Fixes SettingInfo formats not being translated (e.g. deadzone percentage).
Ditches the ImGui cover downloader, because it was pretty janky, and just lets Qt handle it instead.
See above.
Already tested. CI passes.
=> Misc: Warnings cleanup

3rdparty/simpleini/include/SimpleIni.h, pcsx2/DEV9/pcap_io.cpp, pcsx2/DebugTools/DebugInterface.cpp, pcsx2/DebugTools/DisR3000A.cpp, pcsx2/DebugTools/DisR5900asm.cpp, pcsx2/DebugTools/DisVU0Micro.cpp, pcsx2/DebugTools/DisVU1Micro.cpp, pcsx2/DebugTools/DisVUops.h, pcsx2/DebugTools/DisassemblyManager.cpp, pcsx2/DebugTools/ExpressionParser.cpp, pcsx2/DebugTools/MIPSAnalyst.cpp, pcsx2/DebugTools/SymbolMap.cpp, pcsx2/GS/GSCapture.cpp, pcsx2/GS/Renderers/SW/GSScanlineEnvironment.h, pcsx2/IopBios.cpp, pcsx2/R5900OpcodeImpl.cpp
This causes hundreds of warnings spewed when building on MacOS.
It's really annoying.
Make sure debugger still works and displays values. Most of them were in there.
=> Misc: Clean up snprintf() usage

pcsx2-qt/Settings/BIOSSettingsWidget.ui, pcsx2-qt/SetupWizardDialog.ui
=> UI: Rename the "Open in Explorer" button to "Open BIOS Folder"

README.md
Switch to the `app.` prefix because `www.` refers to 404 now.
--
--
=> Readme: Fix Codacy Badge link

pcsx2-qt/AutoUpdaterDialog.cpp, pcsx2-qt/Themes.cpp, pcsx2-qt/Translations/pcsx2-qt_en.ts, updater/Windows/WindowsUpdater.cpp
This PR adds Download Size indicator to the auto updater just like the one on Duckstation.
Good for someone who has limited data caps.
Make sure its shown properly and nothing else broke
=> Qt/Updater: Add download size estimation to the Updater

pcsx2-qt/Debugger/MemoryViewWidget.cpp, pcsx2-qt/Debugger/MemoryViewWidget.h
This fixes the issue of 'G' executing the go-to box instead of putting it into the text view
Runs the tables keypress handler before the widget
If you were to click on the text area and press 'G', you'd end up opening the goto address box instead of inserting a 'G' into that address
CTRL+G is still an override and will work whether you're clicked into the text or hex area.
- Open the debugger
- Click into the text area
- Press 'G'
- A 'G' should be inserted
- Press 'g'
- A 'g' should be inserted
- Press CTRL + 'G'
- The go to address box should pop up
- Click into the hex area
- Press 'g', 'G' or CTRL + 'G'
- The go to address box should pop up
=> Debugger: Run the tables keybind handler before the widgets

bin/resources/GameIndex.yaml
Re adds partial texture preloading to Battlefield Modern Combat 2 as it still seems to make the hash cache explode CPU Sprite to Dark Cloud 2 to fix lines in geometry and disabling MVU Flag Hack for tales of rebirth to fix graphical corruptions.
Good CI pass check for db to make happy boy.
=> GameDB: Misc fixes

pcsx2/CDVD/CDVD.cpp, pcsx2/CDVD/CDVD.h, pcsx2/CDVD/CDVD_internal.h, pcsx2/SaveState.h
Improve the latency of RPM changes when going for CAV to CLV
Going in to CLV the game will expect the speed to stabilise before reading, CAV is more YOLO so doesn't *really* matter so much. Before we just made it simulate a whole spinup in both situations, which caused problems in games like Nickelodeons Avatar, where it swaps constantly between CAV and CLV during cutscenes.
- Corrects CLV read speeds for CD and DVD's.
- Fixed rotational latency which was the wrong way around for CLV, also averaged it (half) for actual rotational latency.
More work can be done to improve seek times (maybe port the seek calculations from Duckstation?), but not really interested in doing so right now :P
Try cutscenes on Nickelodeon Avatar - The Legend of Aang, Digital Devil Saga ~~and maybe transitions in …
=> CDVD: Better simulate RPM changes going in to CLV + read speed

common/General.h, pcsx2/CDVD/CDVD.cpp, pcsx2/CDVD/CDVD.h, pcsx2/CDVD/CDVD_internal.h, pcsx2/CDVD/IsoFileFormats.h, pcsx2/CDVD/Ps1CD.cpp, pcsx2/GS/GSState.cpp
Improve naming of CDVD variables
Clean up C style casting where possible and remove some technical undefined behaviour.
Get rid of some dumb things
Cleanup is good
Test some random games, make sure everything works as before, including loading BIOS region info when fast booting.
=> Build: Fix up various warnings, increase variable readability

pcsx2/CDVD/CDVD.cpp, pcsx2/IopHw.h, pcsx2/R3000A.cpp
Fixes CD/DVD seek times when seeking to a close sector
Add an IOP function for looking up remaining time on an interrupt
Fix up the flow of reads vs buffering sectors
Seeks were happening way too soon if they were to local positions, there should have been rotational latency in finding the sector, but we were treating it as if it was a contiguous read, meaning the delay was extremely low, much lower than games were expecting.
The flow of reads vs buffered sectors was a little broken, meaning that it was having the DMA reads out of step with the CDVD reads, making it try too early, then wait, meaning it could overstep the read point, plus it was spamming the function way too much.
Test random games, but most importantly, Shadow Hearts Covenant.
Fixes #7139
Edit: It fixes it, success!
=> CDVD: Fix seek times, improve read flow

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Screenshots are before, then after.
**GS/HW: Toss targets when BW changes instead of incorrectly converting**
Fixes #5589.
**GS/HW: Fix off-by-one in region clamp**
Fixes text in ZIPANG, decals in Enthusia Professional Racing, edge of screen in Dynasty Warriors, and others.
**GS/HW: Allow bilinear from colour backed Z formats**
Fixes the haze effect in GTA: San Andreas from being extra blurry.
Improves shadows in Everybody's Golf and Tennis.
See above.
Runner says it's good, but double check a couple of the games above.
=> GS/HW: Multiple fixes

pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.ui, pcsx2/Input/DInputSource.cpp, pcsx2/Input/DInputSource.h
Adds another checkbox allowing users to ignore the inversion flag on a control, as reported by the controller. Any binds created while this box is ticked will have the inversion flag forced off.
Third party controllers and adapters, most notably all the PS2 to USB adapters, seem to love flagging the positive component, but not the negative component of their analog stick axes as inverted. As a result the stick always appears to be pressed, even though it is resting at neutral position. 
Testing will require a DInput capable controller which has the above issue. Try to manually map both analog sticks. If your controller is one with the issue, you will observe a ~ at the end of the positive components of the analog sticks.
Then enable Ignore Inversion, and remap the sticks. You should no …
=> DInput: Add option to ignore inversion flag

pcsx2-qt/AutoUpdaterDialog.cpp
Retrieve the download size of our 'best' asset for the user and show that (extends #10068)
It'll fix #10087 once this and the "behind-the-scenes" change is deployed
=> Updater: Fetch best asset size for download size notification

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/DisassemblyWidget.h, pcsx2-qt/Debugger/Models/BreakpointModel.cpp, pcsx2-qt/QtUtils.cpp, pcsx2-qt/QtUtils.h, pcsx2/DebugTools/Breakpoints.cpp, pcsx2/DebugTools/Breakpoints.h
Implement sorting for the thread list
Implement export CSVs for breakpoints, thread lists, and call stacks
Implement importing CSVs for breakpoints
Fixes an issue with the context menu pop up location
Implements stubbing (noping) functions
Implements restoring instructions that have been noped or re-assembled
Implements restoring functions that have been stubbed
Implements the ability to view long function names in the disassembly view by clicking on function entry points
Demangle function names in the disassembly view
Most of these were by request or were just minor issues.
Importing breakpoints via CSVs was added so you can restore / share your breakpoint setups. For example:
```
TYPE,OFFSET,SIZE / LABEL,INSTRUCTION,CONDITION,HITS,ENABLED
8,33634c,,nop,v0 != 1,0,1
8,336354,,nop,a2 == …
```
=> Debugger: A bunch of stuff

pcsx2-qt/Debugger/DebuggerWindow.cpp, pcsx2-qt/Debugger/DebuggerWindow.ui, pcsx2-qt/MainWindow.cpp
The title + A toolbar checkbox to toggle always on top off and on
Sometimes you don't want the debugger on top of everything all the time
Click on the main window while the debugger is on top of it. The debugger should go behind the main window.
Try the above after clicking the always on top button.
=> Debugger: Fix an issue where the debugger is always on top of the main window

bin/resources/GameIndex.yaml
Fixes for vertical and horizontal lines in game. Fixes #10086 
Before:
After:
Lines bad.
Make sure CI Is happy boi.
=> GameDB: Taito memory fixes

pcsx2/IopMem.cpp, pcsx2/VUmicroMem.cpp
Was pointing into rec space instead of the data space.
Memory corruption is bad.
CI passes.
=> IopMem: Fix incorrect memory pointer

.github/workflows/macos_build.yml, .github/workflows/scripts/macos/build-dependencies.sh
remove libjpeg from mac  build script
make sue it still builds and mac works
=> CI: remove libjpeg from mac  build script

bin/resources/GameIndex.yaml
Forces high blending for Gun as it's required for the game to render correctly anyway.
Before:
After:
The game needs it so force it.
=> GameDB: Force minimum blend for Gun

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Xenosaga and VP2 break otherwise.
Xenosaga draws a line around the RT, which is offset by 1 row/column, which the off-by-one clamp was previously masking.
VP2 is just a can of worms I don't have the energy to deal with at the moment.
Closes #10110.
Check Xenosaga/VP2.
=> GS/HW: Restore off-by-one clamp when upscaling

.github/workflows/lint_gamedb.yml, bin/resources/GameIndex.yaml, pcsx2-qt/GameList/GameListModel.cpp, pcsx2-qt/GameList/GameListModel.h, pcsx2-qt/GameList/GameListWidget.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/Settings/GameListSettingsWidget.cpp, pcsx2-qt/Settings/GameListSettingsWidget.h, pcsx2-qt/Settings/GameListSettingsWidget.ui, pcsx2-qt/Settings/GameSummaryWidget.cpp, pcsx2-qt/Settings/GameSummaryWidget.ui, pcsx2-qt/Translations.cpp, pcsx2/Docs/gamedb-schema.json, pcsx2/GameDatabase.cpp, pcsx2/GameDatabase.h, pcsx2/GameList.cpp, pcsx2/GameList.h, pcsx2/ImGui/FullscreenUI.cpp
Switches the main display of GameDB entries to the game's native language in Qt (bigpicture coming later)
(Note: I only added native language entries to Japanese games, we still need someone to do it for the Korean games.)
...plus a few modifications to the gamedb validation scripts so you actually see line numbers when validation fails
Should I include an option to force English titles?  If so, where should I put it?
It would be pretty goofy to have the entire UI translated into Japanese, but still use English titles
- Make sure your Japanese games show in Japanese in the game list
- Make sure the Japanese games sort properly (should be gojuuon order by pronunciation of the kanji)
=> Use native language GameDB entries

bin/resources/GameIndex.yaml
Change mipmap basic to full with trilinear and add it to a region that didn't have it.
Consistent to use full mipmap with trilinear, a region was missing the hw fixes.
CI passes.
=> GameDB: Adjust hwfixes for Tom & Jerry's War of the Wiskers.

bin/resources/GameIndex.yaml
We previously used the `XXX, The` convention to get things to sort correctly, which ended up getting displayed, but now we have separate sort names and can use them
Less user-visible ", The" names
Refresh your game list, look at it, and see that games starting with "The" now use their proper name but still sort in the correct place
=> GameDB: Use sort names for titles beginning with "The"

bin/resources/GameIndex.yaml, pcsx2/Achievements.cpp, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/PINE.cpp, pcsx2/Recording/InputRecording.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
- Adjusts all final fantasy games to have matching names
- Fixes use of non-English names in pause menu overlay (imgui font support is terrible, so using non-English names results in ???s)
No one likes it when their game is ???????
- Refresh and look at your Final Fantasy game collection
- View games from pause menu
=> GameDB: JP name fixes

pcsx2-qt/AutoUpdaterDialog.cpp, pcsx2-qt/AutoUpdaterDialog.ui
Move the download size text from the changelogs list into the top bar like so:
NOTE: The actual functionality is still WIP and will come later.
Better visibility and aesthetic.
Make sure i didn't break other stuff.
=> Qt/Updater: Move download size indicator for better placement

pcsx2-gsrunner/test_check_dumps.py, pcsx2/GS/Renderers/Common/GSDirtyRect.cpp, pcsx2/GS/Renderers/Common/GSDirtyRect.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Don't align the area we write to the target to the block size. If the format matches, the writes don't need to be block aligned. We still read the whole thing in, because that's the granularity that ReadTexture operates at, but discard those pixels when updating the framebuffer. Onimusha 2 does this dance where it uploads the left 4 pixels to the middle of the image, then moves it to the left, and because we process the move in hardware, local memory never gets updated, and thus is stale.
Closes #7563.
Closes #8509.
Runner shows no other regressions.
=> GS/HW: Don't align dirty rectangles to block sizes when updating

pcsx2/GS/GSState.cpp
Kind of scrapings in the sand from #10030 to fix a couple of flush problems which was causing some slight performance issues.
Bugs are bad.
Already tested, no point, wait for CI
=> GS: Fix some flush check behaviour, small optimisation

pcsx2/SPU2/Mixer.cpp, pcsx2/SPU2/defs.h, pcsx2/SaveState.h
Fix applying master volume.
Burnout 3 had samples overflowing 16bits.
Burnout 3 shouldn't be crackling anymore.
=> SPU2: Fix applying master volume

pcsx2/CMakeLists.txt, pcsx2/GS/GSVector4i.h, pcsx2/GS/GSVector8i.h, pcsx2/SPU2/Mixer.cpp, pcsx2/SPU2/Mixer.h, pcsx2/SPU2/Reverb.cpp, pcsx2/SPU2/ReverbResample.cpp, pcsx2/SPU2/defs.h, pcsx2/SPU2/spu2sys.cpp, pcsx2/SaveState.h, pcsx2/pcsx2.vcxproj
Use SIMD for resampling.
Vroom vroom.
Check that things sound the same.
Ok so this is probably a marginal improvement TBH. But I was bored enough to muck around with it. I'll use this opportunity to see what you guys think about using GSVector in the SPU :^)
=> SPU2: Optimize reverb resampling

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
When alpha min is higher or equal to 128 we will always blend so no need to enable the pabe flag, enable only when alpha min is lower than 128.
Brrr, less draw calls, less texture barriers.
super_robot_wars_alpha ['Draw Calls: -15 [458=>443]', 'Barriers: -21 [191=>170]']
=> GS/HW: Enable PABE only when Alpha min is lower than 128.

pcsx2/USB/usb-hid/usb-hid.cpp
fixes usb mouse wheel inputs for e.g. Half-Life
fixes #10152
see #10152
=> USB: Fix inverted mouse wheel

pcsx2/Input/DInputSource.cpp
Apparently there's a device out there which overflows DIJOYSTATE2.
It doesn't appear to have have any buttons, so we can hopefully skip it.
SDL skips devices which don't have *both* axes and buttons.
Less crashy.
Make sure DInput still works.
=> DInputSource: Ignore devices with no buttons

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Adds empty check for EE uploads on source lookup.
It could be empty at this point, causing the `back()` check to error out. This was happening in Persona 3 (at least I think it was here)
Smoke test mostly, GS Dump run was okay. probably a good idea to check persona 3, apparently was crashing during a boss fight.
=> GS/TC: Check transfer list is empty before accessing on source lookup

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Invalidate alpha on channels with no alpha channel on upload to alpha channel.
Invalidation code was only invalidating when the upload shares bits with the target, which is correct, however there are scenarios (mainly texture shuffles) where the alpha channel can be marked as valid, even though it's not part of the target, so if the data being uploaded covers the alpha channel, we need to change the `m_alpha_valid_high/low` to false, despite no valid area changes.
In the case of Juiced, it has a Z24 buffer, which means no alpha channel, so the game stores car textures in the alpha channel, but due to a shuffle effect on the Z24 buffer, it gets marked that the alpha has been rendered, and a later texture lookup (for the car texture) thinks this is now a valid texture to use, but it isn't, …
=> GS/TC: Invalidate alpha on overlapping targets with no alpha

pcsx2/Input/DInputSource.cpp
Fixes a crash when the device reports more buttons than what `DIJOYSTATE2` can handle. Also partially reverts #10155 because it was rolled out as a tentative crash fix that didn't help - it's unlikely but not impossible IMO that valid axis-only devices exist, so it makes no sense not to allow them.
Should fix a crash with specific DirectInput devices.
Make sure that DirectInput Source gamepads didn't regress.
=> DInputSource: Limit the amount of reported buttons and POV hats to what the data format supports

.github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/linux/install-packages-qt.sh
Qt needs DBus support for global menu. We're already including DBus in the AppImage for screen saver inhibiting, so may as well build Qt with it too.
Note: Doesn't work in Wayland, because Wayland is broken by design rubbish. 
Closes #10173.
Check if global menu works in AppImage.
=> CI/AppImage: Enable DBus for dependencies

.github/workflows/linux_build_qt.yml, .github/workflows/scripts/linux/appimage-qt.sh, .github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json, .github/workflows/scripts/linux/install-packages-flatpak.sh, .github/workflows/scripts/linux/install-packages-qt.sh, cmake/SearchForStuff.cmake
Disables Wayland, it's super broken/buggy in basically every scenario. KDE isn't _too_ buggy, GNOME is a complete disaster.
- Stupid obsession with CSD in Gnome => inconsistency
- Inability to position windows => window position saving doesn't work
- NVIDIA just crashes in swap chain creation under Wayland
- Broken global menus
- and many others
Until they sort their s**t out, which is unlikely, since there's been very little progress over the last decade, just keep it disabled. For the Flatpaks, users can re-enable it with flatseal if they really want the crappy experience.
Bumps the Flatpak to the KDE/Qt 6.6 runtime, now that it's available.
Bumps the compiler to Clang/LLVM 17, as that's all that's available in 6.6
Removes the host:ro filesystem permission from the PCSX2 flatpak. It's …
=> CI/Linux: Disable Wayland and spring cleaning

pcsx2-qt/Settings/AchievementSettingsWidget.cpp, pcsx2/Achievements.cpp, pcsx2/ImGui/FullscreenUI.cpp
As in the (lengthy) PR title. PCSX2 already disables Hardcore Mode if the game has no RetroAchievements entry, but it kept it enabled if the entry was there but was empty.
Consistency. Hardcore Mode is not needed if there is nothing to earn in the game.
1. Ensure that Hardcore Mode still works in games with achievements.
2. Ensure that Hardcore Mode turns off if the game has a RetroAchievements entry, but no achievements or leaderboards.
3. Try to check if no stupid exploits are created by this.
=> Achievements: Disable Hardcore Mode if the game has a RetroAchievements entry, but no achievements or leaderboards

pcsx2-qt/Tools/InputRecording/NewInputRecordingDlg.cpp
It was effectively creating a file open dialog, instead of a save dialog, and confusing GNOME.
GNOME is broken in so many ways, but this one was on us.
See above.
Test saving input rec.
=> Qt: Fix QFileDialog usage in NewInputRecordingDlg

bin/resources/GameIndex.yaml
Fixes for skin colour and banding by recommending high blending.
Basic:
High:
Banding is gross and bad.
=> GameDB: MGS 3 Fixes

pcsx2/DebugTools/DebugInterface.cpp, pcsx2/DebugTools/MipsStackWalk.cpp
Fixes up EE assumptions in the stack walker as well as a wrong test for valid iop addresses.
They've never worked previously.
Check that backtraces make sense on both ee and iop.
=> Debugger: Fix IOP stack tracing

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/DebuggerWindow.cpp, pcsx2-qt/Debugger/DebuggerWindow.h, pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/Models/BreakpointModel.cpp, pcsx2-qt/Debugger/Models/BreakpointModel.h, pcsx2-qt/Debugger/Models/StackModel.h, pcsx2-qt/Debugger/Models/ThreadModel.h, pcsx2-qt/QtUtils.cpp, pcsx2/DebugTools/Breakpoints.cpp, pcsx2/DebugTools/Breakpoints.h, pcsx2/DebugTools/DisassemblyManager.cpp, pcsx2/DebugTools/DisassemblyManager.h, pcsx2/Interpreter.cpp, pcsx2/R3000AInterpreter.cpp, pcsx2/x86/iR3000A.cpp, pcsx2/x86/ix86-32/iR5900.cpp
- Fix up the CSV exporting system to support decimal (oops)
- Add spacebar as a breakpoint hotkey
- Change the colour of a breakpoint when it's set and enabled vs set and not enabled
- I tried to fix up the breakpoint, stack and thread list columns. It looks a little goofy when empty but it's pretty okay when it's filled with data. (I either do this or re-implement columns myself **ʷʰᶦᶜʰ ᴵ ʷᶦˡˡ ʰᵃᵛᵉ ᵗᵒ ᵈᵒ ᶠᵒʳ ᵗʰᵉ ʳᵉᵍᶦˢᵗᵉʳ ʷᶦᵈᵍᵉᵗ**)
- Whenever a breakpoint is hit it'll take you to the breaking CPU tab and change the colour of the tab text
- Fall back to an unmangled symbol when a symbol cannot be demangled in the disassembly view (oops x2)
- Until the disassembly widget is updated, I've turned off pseudo instructions. It sometimes doesn't make any sense and can be confusing
Who doesn't …
=> Debugger: Some more debugger updates

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
GS/HW: Minor optimization on color dest blend.
Add early return, no need to run the rest of the code.
Minor optimization.
Already tested, no diffs.
=> GS/HW: Minor optimization on color dest blend.

pcsx2/GS/GSRegs.h, pcsx2/GS/Renderers/Common/GSRenderer.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Disable using texture when not required
Sometimes texture mapping can be enabled when it isn't required, meaning a lookup is done but not required. This avoids it where possible.
Test games, including ones listed. None of these games have been performance tested, only dump run for changes.
Reduction in stats, perf change questionable if it happens:
Ace combat 04: -1 Upload
Fire Pro Wrestling: -1 Upload
Futurama: -1 Upload
Maximo vs. Army of Zin: -1 Upload
Mobile Suit Gundam - Zeonic Front: -1 Upload
Need for Speed - Underground: -1 Render Pass and -1 Copy
Spider-Man 2: -1 Upload (-2 Uploads in another scene)
Also potential performance implications to test for on (no reduction in stats but all disable texturing):
Captain Tsubasa
Conspiracy - Weapons of Mass Distruction
Destroy All Humans …
=> GS/HW: Disable texture when not required

.github/workflows/linux_build_qt.yml
GitHub runners have added the toolchain test repo, which pulled in GCC 13, which means that our AppImages no longer run on Ubuntu 22.04/Debian 12.
Until they fix that, try to remove the traces of GCC 13 from the runner image before building, which means it should link with the older libstdc++, and hopefully still work fine.
This is documented upstream at https://github.com/actions/runner-images/issues/8659
Fixing AppImages on older-than-2023 distros.
Check AppImage on Ubuntu 22.04/Debian 12.
=> CI/AppImage: Work around GH runner issue #8659

.github/workflows/linux_build_flatpak.yml, .github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json, .github/workflows/scripts/linux/install-packages-flatpak.sh
Flathub is going to enable server-side release validation, therefore we should validate on our end before pushing.
Closes #10133.
Make sure Flatpak still works.
=> CI/Flatpak: Validate build before pushing

bin/resources/GameIndex.yaml
Add speedhack and hwfixes to McDonald's Original Happy Disc.
PaRappa the Rapper 2:
Instant Vu 0, MTVU0, fixes noodles.
Pipo Saru 2001:
Recommended blend level high, fixes metal surfaces not being rendered correctly. Full mipmap, plus trilinear ps2, fixes ground textures to match sw renderer.
Fixes https://github.com/PCSX2/pcsx2/issues/9850
CI passes.
=> GameDB: Add speedhack and hwfixes to McDonald's Original Happy Disc.

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Fix Tex in RT Merge Targets crashing.
Check if src->m_from_target is actually null so it doesn't cause any access violations when reading.
Fixes Dirge of Cerberus crashing with Merge Targets enabled.
Crashes are bad.
Dump from https://github.com/PCSX2/pcsx2/issues/10031 no longer crashes with merge targets, other usual testing.
=> GS/HW: Fix Tex in RT Merge Targets crashing.

.github/workflows/scripts/linux/appimage-qt.sh, .github/workflows/scripts/linux/apprun-hooks/default-to-x11.sh
Slightly better version of #10179 which enables users to set an environment variable to force the use of Wayland if they want a rubbish, broken experience.
The way I had to do this was utterly disgusting, but LinuxDeploy doesn't let you add your own apprun-hooks, so we have to inject them in after the fact. Hopefully it won't break with some future LinuxDeploy update........
This'll probably have to stay around for years at least, because of the fundamental design flaws in the WL protocol, and if anything gets fixed, GNOME doesn't adopt it, so it's pointless. Guess we could check `XDG_SESSION_TYPE`, but as it stands, WL on KWin is broken too.
tldr, set `I_WANT_A_BROKEN_WAYLAND_UI=YES ./PCSX2.AppImage` (or any other value) if you want pain and suffering, and don't complain.
Giving users …
=> CI/AppImage: Add I_WANT_A_BROKEN_WAYLAND_UI environment variable

pcsx2-qt/QtHost.cpp, pcsx2/Counters.cpp, pcsx2/GS/GS.cpp, pcsx2/GS/GS.h, pcsx2/GS/Renderers/Common/GSRenderer.h, pcsx2/MTGS.cpp, pcsx2/MTGS.h
Disables the skipping of interlacing when Deinterlacing is on Auto if the SW FMV fix is enabled.
A bunch of games have their interlacing built in to the FMV's, and they are expecting the native number of lines, so when you upscale the deinterlacing doesn't work because we're trying to deinterlace more lines.  Further to this we try to cheat when the interlacing is done in FIELD mode, which means the full frame is there and it reads every other line, we output a progressive signal, again this will break with said FMV's above, so this forces the normal MAD Adaptive deinterlacing (if a manual deinterlacing mode isn't set) to take place on these FMV's when the SW switch is engaged, this should drastically reduce combing in FMV's.
No-Interlacing patches will stop this working, just an FYI as …
=> GS: Disable interlace skipping on FMVs on SW FMV switch

pcsx2/Counters.cpp
Fixes the H-Blanks per frame according to testing.
Also fix a bug in checking if it's NTSC
The numbers were slightly out, I retested them and they match pretty closely now.
Smoke test some games, maybe try some games with incorrect field orders, might be better now..
cycles values are bus cycles/256
----------------------------------------------------------------
Progressive NTSC
PCSX2
bus cycles during vblank 842 vrender 8785 vblank 842
blanks during vblank 23 vrender 240 vblank 23
PS2
bus cycles during vblank 842 vrender 8785 vblank 841
blanks during vblank 23 vrender 240 vblank 23
----------------------------------------------------------------
Progressive PAL
PCSX2
bus cycles during vblank 959 vrender 10617 vblank 958
blanks during vblank 26 vrender 288 vblank 26
PS2
bus cycles during …
=> PCRTC/Counters: Fix H-Blanks per frame

bin/resources/GameIndex.yaml
Patch to sync audio and video in Valkyrie Profile 2 FMV's
I'm not sure on the source of this but, I suspect the game thinks somewhere that it's in NTSC mode instead of PAL (I think a few games do this), but I'm unsure where this would be.  This patch will suffice for the moment, until somebody completely dissects this game.
Test Valkyrie Profile 2 PAL FMV's
=> GameDB: Patch to fix Valkyrie Profile 2 PAL FMV timing

bin/resources/GameIndex.yaml
Fixes for chromatic fringing on edges.
Before:
After:
Chromatic fringing is gross.
=> GameDB: Scarface TWIY Fixes

pcsx2-qt/QtHost.cpp, pcsx2/Hotkeys.cpp, pcsx2/VMManager.h
This PR adds the current active savestate slot indicator just like the one on 1.6.0
1.6.0:
Nightly:
Nice QoL feature so you don't have to constantly switch savestate slots just to see which one you are on at the moment.
Plus 1.6 used to have it so.... feature parity? ;)
Make sure stuff doesn't break.
=> Qt: Show currently active savestate slot on status bar

pcsx2/Interpreter.cpp, pcsx2/R5900.h, pcsx2/VU0.cpp, pcsx2/VU0microInterp.cpp, pcsx2/x86/microVU.h, pcsx2/x86/microVU_Compile.inl, pcsx2/x86/microVU_Execute.inl
Scale VU0 cycles with EE cycle rate
Also fix cycle underflow issue
Fix VU0 sync with EE interpreter
Implement EE overclocking on interpreter
When the EE is over/underclocked, VU0 goes out of sync, which can cause problems, most prominently in Ratchet & Clank games, this tries to alleviate that somewhat by trying to keep the two more in sync, this does NOT mean it will be perfectly reliable, but may mean R&C will handle up to 180% without exploding. 300% will boot but the graphics will be broken (unless either VU0 or the EE is set to interpreter).
EE Interpreter changes were to stop Ratchet & Clank crashing but also allow you to over/underclock.
Test Ratchet & Clank games (maybe Jak as well?, other games if you care) with the EE overclocked, see if it works better.
I'm not really concerned …
=> VU: scale VU0 cycle rate with EE + Fix EE Interpreter sync + Implement EE overclocking on Interpreter

pcsx2-qt/AutoUpdaterDialog.cpp
Prints stderr from tar command if it fails
User came to us with the updater failing due to being unable to unpack the update, maybe seeing the stderr from tar will help
Untested, but it hopefully won't be worse than the current error message
(If anyone can think of a way to make tar fail while creating the staging directory succeeds, please test that)
=> Updater:Mac: Show tar stderr if it fails

bin/resources/shaders/vulkan/tfx.glsl, pcsx2/ShaderCacheVersion.h
GS/HW: Make sure feedback loop is enabled for SW_AD_TO_HW  blend.
Fixes Colin McRae Rally 2005 on Vulkan.
Possible others as well on basic blend with barriers or Medium blend with barriers disabled.
Accuracy, bad shader files are bad.
Test Colin McRae Rally 2005.
=> GS/VK: Make sure feedback loop is enabled for SW_AD_TO_HW  blend.

pcsx2/IopBios.cpp
Moved the Register/ReleaseLibraryEntries HLE so it'll be run in release builds
A lot of people debug with release builds and having a "broken" function window the debugger on these builds isn't that practical 
See if the function list works on release builds
=> IOP HLE: Generate module list on release builds

pcsx2/COP2.cpp, pcsx2/FPU.cpp, pcsx2/VUops.cpp, pcsx2/x86/microVU_Macro.inl
Improve the interpreter FPU emulation
Just some things weren't right, like flag handling and bad float conversions.
test random games in the interpreter.
Fixes Gran Turismo 4 in the interpreter
=> EE/Int: Improve FPU emulation

pcsx2/Counters.cpp, pcsx2/IopCounters.cpp, pcsx2/IopDma.cpp, pcsx2/SPU2/spu2.cpp, pcsx2/SPU2/spu2.h
Refactor, tidy up and correct some behaviour on EE and IOP counters.
Also makes the ticks for SPU2 correct, not *12 which was kind of a hack.
Code was a little gross in places and not always right.
Test game sensitive to sound issues (Titeuf Mega Compet needed the *12, but is apparently okay with these changes)
=> Counters: Improve counter updates and fix a couple of errors

pcsx2/IPU/IPU.cpp, pcsx2/IPU/IPU.h, pcsx2/IPU/IPU_Fifo.cpp, pcsx2/IPU/IPU_MultiISA.cpp, pcsx2/IPU/IPUdma.cpp
Stops transferring data on tag edges, also centralise IPU_PROCESS interrupts
Transfers will stop on tag edges if there's no data request, until another request for data is made, I believe this was causing data to outstrip the reads, causing bad data to get uploaded.
test videos, especially sensitive games
Fixes #10232 WWE Smackdown Shut Your Mouth
=> IPU: Pause IPU_TO on tag edge. Stop repeat Interrupts

pcsx2-qt/GameList/GameListModel.cpp, pcsx2/GameList.cpp, pcsx2/GameList.h
Ignore game list display settings, they're for display
Prevents cover paths from changing based on the status of the use English titles setting
Set a custom cover for some Japanese games, enable English titles, and make sure the covers are visible
=> Qt: Always use non-English title for cover paths

.github/ISSUE_TEMPLATE/app_bug_report.yaml, .github/ISSUE_TEMPLATE/emu_bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
Added an anti-piracy warning to issue templates.
Prevent invalid issues.
I've tested that the issue templates function correctly in my fork. There might not be any further testing required.
=> Issue template change: add anti-piracy warning

pcsx2/Counters.cpp
Pass the newly updated start cycle for gated counters
It was passing the previously updated one which was old, which could cause too many cycles to be counted during gates.
Not sure tbh.. any games which use gates (I don't have a list) most notably the DDR games use them, I think.
=> Counters: Pass correct start cycle for gated counters

pcsx2/COP0.cpp, pcsx2/x86/iCOP0.cpp
Update CPU cycles and then the performance counters to correctly increment them
cpu cycles weren't being updated, neither was the counter being updated before the KSU mode (Kernel/Supervisor/User) was modified. Also the last check cycle wasn't being updated if the event wasn't counted, meaning it would count bad amounts of cycles.
Test random stuff. GTA 3, Next Generation Tennis 2003 and Spongebob Battle for Bikini Bottom all use performance counters, I did give them a quick go and they seemed fine. Not sure what else is affected by them.
No known fixes.
=> COP0: Correctly update performance counter cycles

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Don't convert old depth buffers to render targets if they are not being preserved
Harry potter was misdetecting old targets from a previous frames during a striped memory clear which only matched by address, not size, causing the new target to have a very wrong buffer width (TBW), which then later went very wrong during a readback as it missed half the data. It was a string of nonsense :P
Smoke test mostly. very minor single pixel differences shown in Spider-Man 2 and Motocross Mania probably due to different target sizing/resizing, nothing else showed up in a dump run.
Fixes Harry Potter and the Prisoner of Azkaban
Master:
PR:
=> GS/HW: Don't convert old depth if being overwritten

.github/workflows/linux_build_flatpak.yml
We're currently failing validation with a `finish-args-unnecessary-xdg-config-access` error.
This is **not** caused by anything we're doing, it's an issue with the upstream Qt SDK: https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/3bac997f76646f1abda38d376e217a5635167144/org.kde.Sdk.json.in#L84
So, for now, just disable it. I don't have time at the moment to chase bugs upstream, if it's still broken next week, I'll do so then.
=> CI/Flatpak: Disable build/repo linting

pcsx2/IopBios.cpp, pcsx2/IopBios.h, pcsx2/VMManager.cpp
Sets the ``hostRoot`` path to the directory of the boot iso.
Gives access to the host filesystem when running an iso. This isn't useful for anything but niche cases (homebrew, modding) but it is a small addition that won't negatively impact existing features.
Run the elf and the iso with ``Host Filesystem`` enabled and they should both print out the contents of the ``content.txt`` file inside.
[hostfs-tester.zip](https://github.com/PCSX2/pcsx2/files/13315226/hostfs-tester.zip)
Implements #10259
=> IOP HLE: Add support for host fs when booting an iso

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Re-adds previously removed horizontal offset if it isn't processed during invalidation.
This was being lost, causing some games to invalidate the wrong page.
Test Gran Turismo 4 messing around in the menus, maybe SMT Lucifer's Call?, SOCOM 3 loading screens.
Master:
PR:
=> GS/TC: Re-add horizontal offset if not processed during invalidation

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp
Updates the cheats settings window to reload the active cheats when clicking Reload.
Previously, the list reload function was being called. Instead, the function that reloads the list _and_ the enabled cheats is called.
Fixes #10282. 
The Cheats Settings menu was failing to reload cheats when pressing the button. This meant if you enabled a cheat, made changes, and clicked reload, there would be no updates in behavior.
Now cheats can be reloaded as expected.
- Load a cheat file for a game.
- Once enabled, update that cheat and save.
- Click the reload button.
Ensure that the behavior of the cheat now responds as expected when clicking reload.
<details> <summary>Note: The way I tested this was the following:</summary>
<ul>
<li>Created this cheat: <code>[Cheat/Test1] …
=> Qt: Fix Failing to reload cheats on button press

pcsx2/R3000A.cpp
Fix r3000 COP0 Status value on reset.
Previously used value was wrong. BEV bit wasn't correct one, and CU0 and TS bits are not enabled by default.
None, Status register is overwritten almost right after boot. I tested PS2 game/PS1 game/Bios with standard and deckard model bios file just in case.
=> R3000: Fix COP0 Status value on reset

pcsx2/SIO/Memcard/MemoryCardFolder.cpp, pcsx2/SIO/Memcard/MemoryCardFolder.h
1. Use **timegm** / **_mkgmtime** (on Windows) instead of **mktime**, to make sure that timestamps will be treated as if they were in UTC, thus not adding or subtracting any time while saving. 
2. Change **MemoryCardFileEntryDateTime::FromTime** accordingly, since we no longer need to offset times read from **_pcsx2_index** manually.
This way timestamps inside mcFolders will match those in mcFiles and thus will be interpreted correctly by the PS2 Bios.
Always used memory card files and decided to try out memory card folders for a change.
I then noticed the timestamps (inside the **_pcsx2_index** files) on all the saves I converted from mcFile -> mcFolder were off by 8 hours. Do note that my timezone is UTC+1 and mcFiles store time in JST/UTC+9, so the offset being 8 hours gave me a hint …
=> MemoryCardFolder: Fix incorrect save timestamps

pcsx2/DebugTools/Breakpoints.cpp, pcsx2/DebugTools/Breakpoints.h, pcsx2/R5900.cpp
The debugger sets a pc and a tick count to be checked whenever you resume after a breakpoint is hit. If these match during a breakpoint check, the current pc and tick count then the breakpoint is skipped.
This is so you can resume after a breakpoint is executed. Without this you'd continuously break on the same instruction when resuming.
The issue is that resets are queued and wont happen immediately. If you were to break on a breakpoint, queue a reset, then resume, in some instances the breakpoint wouldn't be hit (it'll be skipped) next time it's executed.
I've just removed the skip and tick flags upon cpu reset.
Breakpoints were not functioning as expected
Go to the entry point of a game/homebrew. Set a breakpoint there and reset. When you hit that breakpoint, reset, then resume. The …
=> Debugger: Clear breakpoint skips when resetting

README.md
* Add section for Contributing / Building in the README with a link to the Contributing.md / GitHub Wiki
The new category is placed at the bottom, since it is only relevant to developers.
* Adjust the Technical Notes header from ### to ## to match the rest of the README
* As a new contributor, I did not think to check the GitHub Wiki for build instructions. Instead I referenced the PCSX2 Wiki (first result when searching), which was completely outdated and did not mention the pcsx2-windows-dependencies repo. 
* Rather than have build instructions in the README, simply linking to the GitHub Wiki will allow for one source of truth, preventing constant updates to the README if/when build procedures change.
* I did not see the contributing.md (since it was in the .github folder rather than …
=> Readme: Clarify latest build/contribution info

pcsx2-qt/DisplayWidget.cpp, pcsx2-qt/DisplayWidget.h, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2/SIO/Memcard/MemoryCardFolder.cpp
Apparently something changed in Qt 6.6, and the windowed transition when invoking the confirm popup didn't complete in time, and/or something to do with parenting changed, which causes a squished popup dialog.
This was racey anyway, `g_emu_thread->isFullscreen()` gets set before on the CPU thread before it calls back to the UI thread, so the wait loop wasn't actually doing much. Poll it from both locations instead - can't use just the UI thread, because the setFullscreen() call itself is asynchronous.
Changes the close behaviour of the display window, if you press ALT+F4 while full screen, PCSX2 will now exit instead of returning to the game list.
Also fixes the main window getting displayed, but not being interactable while the popup is open.
Includes a small dose of Wayland-frustrated …
=> Qt: Improve fullscreen behaviour

pcsx2-qt/MainWindow.cpp
When displaying the confirm popup when fullscreen.
I didn't implement this correctly in #10295.
CI passes, already tested.
=> Qt: Use main window geometry for temporary window

cmake/SearchForStuff.cmake, common/HTTPDownloader.cpp, common/HTTPDownloader.h, common/HTTPDownloaderCurl.cpp, common/HTTPDownloaderCurl.h, common/HTTPDownloaderWinHTTP.cpp, common/HTTPDownloaderWinHTTP.h, common/ProgressCallback.h, common/vsprops/QtCompile.props, pcsx2-qt/AutoUpdaterDialog.cpp, pcsx2-qt/AutoUpdaterDialog.h, pcsx2-qt/CMakeLists.txt, pcsx2-qt/QtProgressCallback.cpp, pcsx2-qt/QtProgressCallback.h, pcsx2/Achievements.cpp, pcsx2/GameList.cpp, pcsx2/Host.cpp, pcsx2/Host.h
Qt 6.6 changed some QtNetwork behaviour, which makes it block the UI thread for a second or so doing something with TLS certificates (I forget the exact function name).
I've been wanting to ditch QtNetwork for some time, just procrastinated it, but now I have a reason to actually do it. Since it's blocking DuckStation updating to Qt 6.6 too.
Use our internal HTTPDownloader (WinHttp/Curl) instead.
Getting rid of the delay on startup that's been there since Qt 6.6.
Fewer dependencies, yay?
Can't really test it, since the updater doesn't exist on PR builds.
I've tested it on Windows as best I can, will do Linux/Mac as well soon.
=> Qt: Use HTTPDownloader instead of QtNetwork for updates

pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/DisassemblyWidget.h
Add the ability to copy a function name when you right click the first instruction of a function (the line where the function name displays).
(Only adds this right click option to the starting instruction of the function that has the text name, not to all instructions of the function.)
**Demonstration:**
Names can be quite long and complicated, thus it can be quite helpful to be able to just copy the name. 
Just a convenience feature.
- Load any ISO or ELF
- Open the debugger
- Open the Functions tab
- Double click a function to jump to it's position
- Right click the first instruction to verify the context menu for "Copy Function Name" exists.
- Verify the copied name is valid and validate that the context menu option is not available for other instructions of the function.
=> Debugger: Allow copying function names

pcsx2/Achievements.cpp
Forgot to change this in the HTTPDownloader changes.
Redundant copies.
CI passes.
=> Achievements: Avoid string copy on server call

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Can't believe I'm fixing a religious game.
Anyway, Takes the larger bit depth of the two when doing a double half clear, to avoid the alpha not being overwritten when it should be.
Also restricted when the hw renderer can create a new target to cut down FMV errors.
Veggie Tales - LarryBoy and the Bad Apple was doing a double half clear to wipe two textures, with the upper half being a C32 texture, but because the Z Buffer was the base, it was using that, which was set to Z24 format, meaning the alpha was left untouched. The next draw relied on this being cleared, but ended up drawing garbage to the screen from a messy alpha channel.
Bad targets were also being created on idle frames between FMV's in games like Clock Tower 3
Smoke test some random games you know do double half clears I …
=> GS/HW: In double half clears, take larger bit depth

bin/resources/GameIndex.yaml
Add preload frame fix for Rule of Rose to fix FMVs
The game draws the FMV frames in a really weird way, by doing a strip of the black border at the top, then drawing the rest of the frame.  This works around it for now, since fixing it properly (preloading on expand) is a can of worms, which I'm not willing to get in to any time soon.
Test Rule of Rose FMVs (already done)
Fixes #9925
=> GameDB: Fix FMVs on Rule of Rose + PAL Region

pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/GS/Renderers/Common/GSRenderer.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Allow more draws to remain queued at vsync if there were recent uploads.
This was kind of a regression from #10296 as we rely on the transfers now to create new PCRTC frames if there are no matching draws, and this makes matching more difficult with FMV's.
Test Final Fantasy X International, and some random FMV's.
Also fixes Neopets FMV's
=> GS/HW: Allow more draws to remain if recent draws done near vsync

pcsx2/GS/GSClut.cpp
Constants, switch cases.
Code cleanup.
CI passes.
=> GS: Some cleanup to GSClut.

bin/resources/GameIndex.yaml, pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h
Pre-rounds and truncates STQ float values for textures on sprites.
Extracted as safe code to use from #6553 so we can at least get the manhunt fixes in for the lighting.
We did some tests on hardware, and we found the truncating of float values gets pretty crazy depending on the difference between values. What is done in this PR seems to work pretty well for a bunch of games, however hardware mode won't feel all the fixes, I believe due to the difference in how GPU's handle texture coordinates.
Test any games including the ones listed below, make sure nothing looks busted in software and hardware.
All the following results are on Software mode
Ben 10:
Master:
PR:
Armored Core 2:
Master:
PR:
Beyond Good & Evil:
Master:
PR:
G-Force:  (kind of subjective but certainly not bad, matches some …
=> GS: Pre-round/truncate STQ values based on hardware tests

pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/GS/Renderers/Common/GSRenderer.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
replicate half pixel offset for destination texture coordinates when using Blit FMV override in the hardware renderer. Also disable bilinear if the game isn't doing it.
when doing direct copies this doesn't work as expected and causes really awkward jittering and interlacing problems with some FMVs which use it, namely This is Football 2003 (maybe the other This is Football games too). I don't remember what other FMV's use this, but I will update here if I find out.
Test FMV's which experienced jittering in hardware mode, this *might* have improved it.
Also fixes Devil May Cry regression from #10296
Fixes #10304
=> GS/HW: Mirror half pixel offset when using FMV Blit override

bin/resources/GameIndex.yaml
Fixes screen shake in game caused by HPO Normal in Underground 2 and broken sprites and crowds in NBA Live 05 and 09.
Less break more good.
=> GameDB: NFS Underground 2 and NBA 05/09 fixes

bin/resources/GameIndex.yaml
Fixes large HC size causing high GS%.
More fps more vroom.
=> GameDB: Ace Combat 4 fixes

pcsx2/System.cpp
Cuts out unnecessary info and uses CPUInfo to print processor name core count and thread count.
Less junk info more good.
Make sure CPU information works correctly on the console.
=> Console: Update CPU detection

pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2/Achievements.cpp, pcsx2/Achievements.h, pcsx2/Hotkeys.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
Currently, PCSX2 if you're fullscreen and load a state while HC mode is on, because it blocks until the VM is un-fullscreened, but the VM can't un-fullscreen because it's waiting for the UI thread to confirm the mode switch.
Instead, use the big picture UI to manage it all. Works with a gamepad, and doesn't break fullscreen.
Also fixes the pause buffering "exploit" by putting a cooldown on pause hotkeys.
Fixes deadlocks.
Try loading states while fullscreen and HC is on.
Make sure PCSX2 "works" as normal, since I changed the main CPU thread loop.
=> Achievements: Use big picture to confirm HC mode disable

bin/resources/GameIndex.yaml
GameDB: Various gshw fixes.
Add full mipmap plus ps2 trilinear to Snoopy vs. The Red Baron. Improves ground textures to match sw renderer.
Add full recommended blending level to Blokus Club with Bumpy Trot. Fixes water reflections.
Add full mipmap plus ps2 trilinear and medium recommended blending level to Gallop Racer 2003: A New Breed. Blending improves lighting, maximum blending is needed for full accuracy. Mipmap + trilinear, improves ground textures to match sw renderer.
Add full mipmap plus ps2 trilinear
Accuracy, improves https://github.com/PCSX2/pcsx2/issues/5240, https://github.com/PCSX2/pcsx2/issues/4879 https://github.com/PCSX2/pcsx2/issues/6375
Ci passes, test dumps from https://github.com/PCSX2/pcsx2/issues/5240, https://github.com/PCSX2/pcsx2/issues/4879 …
=> GameDB: Various gshw fixes.

pcsx2/ImGui/FullscreenUI.cpp
This PR fixes the pause menu game info with longer Rich Presence string. The code attempt to account for multiple-line RP, but didn't do so properly. Two changes are made:
1. Cover size is now consistent regardless of whether RP is present or not - a bigger one looks somewhat nicer.
2. Sizing logic is fixed.
It looked kinda goofy. Before:
After:
For comparison, the current sizing without Rich Presence:
Try any game with RetroAchievements and Rich Presence, and verify that the string displays properly.
=> FullscreenUI: Properly account for multiline Rich Presence in Title Info

pcsx2-qt/MainWindow.cpp
add the ability to load  .backup save states in UI
load some .backup files  make sure they work
=> QT: add the ability to load  .backup save states in UI

pcsx2/Achievements.cpp
Fixes broken percentage display if unofficial achievements are enabled.
Sets with only unofficial achievements displayed wrong if unofficial test mode was enabled.
Before:
After:
1. Launch any game with an unofficial set.
2. Enable "Unofficial Test Mode".
3. Inspect the percentage unlock and text in the Achievements screen.
=> Achievements: Fix the percentage counter when only unofficial achievements exist

pcsx2/ImGui/FullscreenUI.cpp
Fixes issues I noticed when backporting https://github.com/PCSX2/pcsx2/pull/10330 into DuckStation as https://github.com/stenzek/duckstation/pull/3058:
1. One of the layout shifts remained unscaled.
2. If the path is empty, the subtitle was placed too high and overlapped the title.
Pretty
Run any game with Rich Presence enabled and verify that the title info in bottom right of the pause menu looks OK.
=> FullscreenUI: Fixup mistakes missed in #10330

pcsx2-qt/SetupWizardDialog.ui
fixes links in first page of Setup Wizard 
make sure links  work on in first page of Setup Wizard
=>  Qt: Fix links in first page of Setup Wizard

pcsx2/SIO/Memcard/MemoryCardProtocol.cpp, pcsx2/SIO/Multitap/MultitapProtocol.cpp, pcsx2/SIO/Multitap/MultitapProtocol.h, pcsx2/SIO/Pad/Pad.cpp, pcsx2/SIO/Pad/Pad.h, pcsx2/SIO/Pad/PadBase.cpp, pcsx2/SIO/Pad/PadBase.h, pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SIO/Pad/PadGuitar.h, pcsx2/SIO/Pad/PadNotConnected.cpp, pcsx2/SIO/Pad/PadNotConnected.h, pcsx2/SIO/Sio2.cpp, pcsx2/SIO/Sio2.h, pcsx2/SIO/SioTypes.h, pcsx2/SaveState.cpp, pcsx2/SaveState.h
An assortment of changes which I've attempted to fragment into separate commits as best I could. Brings PCSX2 much much closer to what PS2 hardware does for the RECV1 register and the data values peripherals send.
Main focus was extending RECV1 - the old method was that we had a known good value for when a device was found, and a known good value for when no device was found. These were assumed to always work, and because of how most games poll devices, they kind of just did. Hardware tests however showed there were some more specific nuances, and implementing these makes games such as Gauntlet: Dark Legacy much happier when dealing with multitaps.
Old code also assumed that when the game changes the target slot for a multitap, it intends to do so for both pads and memcards at the same …
=> SIO2/Pad/Multitap/Memcard: Assorted accuracy improvements for response data

.gitmodules
For some reason we used a branch xz from around 6 years ago? Honestly not sure why.
6 Year old submodule's are a bit out of date.
Make sure CI passes and that loading xz gs dumps save states and anything else that uses xz still works.
=> 3rdparty: Use upstream xz submodule

pcsx2/ImGui/FullscreenUI.cpp
Fixes issues with macro settings both setting incorrect keys in the config file, and not writing to disk until emulator exit.
Broken things are inconvenient.
Set macro settings via big picture, open normal settings, make sure they match.
=> Big Picture: Fix macro settings not applying correctly

bin/resources/GameIndex.yaml
Fixes for the hash cache being silly and spiking to stupid levels killing performance.
Game is stupid and absolutely destroys the GS thread with silly spikes in the HC during lightning strikes.
=> GameDB: PJ King Kong fixes

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h
Closes #10370
Allows user to right click a memory search result in order to go to that memory address location in the disassembly view.
Allows quicker access to viewing search result addresses in the disassembly view without requiring the user to change tabs, or change their position in the Memory View.
- Launch a game and open the debugger.
- Perform a memory search.
- Right click search results and verify the context menu opens giving the ability to "Go to in Disassembly".
- Verify it takes the user to a new position in the Disassembly View, likely the closest assembly instruction to that given address.
=> Qt: Adds right click menu option 'Go To Disassembly' to Memory Search results

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h
Adds the ability to remove individual search results from the Memory Search results list. Right clicking a result will give the "Remove Result" option in the context menu.
Especially with large lists of results, it's helpful to be able to filter out addresses that we know we're not interested in. Primarily a convenience feature.
- Open a game and the debugger.
- Perform a memory search.
- Right click any result, click 'Remove Result'.
- Verify it's no longer in the list, and does not reappear upon a filter search (ensures it's not just gone from the UI, but our internal results set).
Safe guards are in place to make sure the value being replaced is the one you selected.
=> Qt: (Debugger) Add ability to remove result from Memory Search results

pcsx2-qt/Settings/AchievementLoginDialog.cpp, pcsx2-qt/Settings/AchievementSettingsWidget.cpp, pcsx2/Achievements.cpp
Ports of https://github.com/stenzek/duckstation/commit/07fac1fb19553a43d6b25ea0104097cad5b43046 and https://github.com/stenzek/duckstation/commit/dc6bb357d427178ce5b2f1e4c4aaeec26616ced0.
Prevents users assuming that hardcore mode is on by default.
Potentially fixes #10355.
Test logging in with achievements+hardcore disabled, look for prompts.
=> Qt: Prompt user to enable HC mode on achievement login

pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2/Config.h, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GameDatabase.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/Pcsx2Config.cpp
Adds another HPO mode that simply aligns coordinates to native resolution, when converting them to clip-space.
Some games like it, others hate it.
Upscaling fixes?
Make sure I didn't break the other HPO modes.
=> GS/HW: Add 'Align To Native' HPO mode

common/SmallString.h
Port of https://github.com/stenzek/duckstation/commit/a9ee2a34d849135e207da8f1eedd42a646f20bc5
Copying SmallString objects could result in crashes.
CI passes.
=> SmallString: Add missing copy construct/assign operators

pcsx2-gsrunner/test_run_dumps.py, pcsx2/DEV9/PacketReader/IP/UDP/DNS/DNS_Classes.cpp, pcsx2/DEV9/PacketReader/IP/UDP/DNS/DNS_Classes.h, pcsx2/GS/GSRingHeap.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/x86/ix86-32/iR5900.cpp
Misc: Codacy and compiler warnings cleanup.
Cleaner code, less warnings.
CI passes.
=> Misc: Codacy and compiler warnings cleanup.

common/FileSystem.cpp, common/Path.h, pcsx2/Pcsx2Config.cpp, tests/ctest/common/path_tests.cpp
Port of https://github.com/stenzek/duckstation/commit/524625269fe5f365a10dbfc2e18c325b6c4fab61 and https://github.com/stenzek/duckstation/commit/407049cd91b65c8a917533b87c7264dba3e2adc5.
Fixes PCSX2 generating incorrect relative paths when the data directory is involved in a symlink'ed path. e.g. from FreeBSD, `/home` is symlinked to `/usr/home`, therefore `..` in `/home/foo` actually resolves to `/usr`, not `/`. Silly Unix...
Ensure Linux/Mac builds still find your user data.
Note to self: Test flatpak as well before merging.
=> Qt: Resolve any symbolic links in AppRoot/DataRoot

pcsx2-qt/Settings/AdvancedSettingsWidget.cpp, pcsx2-qt/Settings/AdvancedSettingsWidget.ui, pcsx2-qt/Settings/DEV9SettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/ImGui/FullscreenUI.cpp
- Adding translation support for all the substrings related to the single/multiframe GS Dump message.
- Correcting the None option in the Deinterlacing settings according to what was talked about in Crowdin, unified that string with the Big Picture mode.
- Minor English text fixes reported in Crowdin.
Second attempt at doing this PR after the former, https://github.com/PCSX2/pcsx2/pull/10253 , was mangled by bad squashing and rebasing.
Moar translatable strings for non-English speakers, cleaner explanation for the None option.
Make sure I did not break anything, build looks good on my end.
=> UI: Minor additions for translations and English text changes (2nd attempt)

pcsx2/Recording/InputRecordingFile.cpp, pcsx2/Recording/InputRecordingFile.h
Input-rec: Set git tagged emu version instead of static version.
The static version was set as 1.7.0, not knowing which nightly version the recordings were made on.
Consistency, fixes https://github.com/PCSX2/pcsx2/issues/10366
Test input recording, make sure pcsx2 version info in recordings is properly set, see https://github.com/PCSX2/pcsx2/issues/10366
=> Input-rec: Set git tagged emu version instead of static version.

bin/resources/GameIndex.yaml, pcsx2/Docs/gamedb-schema.json
This PR fixes ghosting and bloom issues on WALL-E
SW:
HW: 
HW + HPO Native and Round Sprite Full:
less ghost better-er.
Make sure i didn't break anything else.
=> GameDB: Fixes for WALL-E

pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2/CDVD/CDVD.cpp, pcsx2/Counters.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/SIO/Memcard/MemoryCardProtocol.cpp, pcsx2/SIO/Sio.cpp, pcsx2/SIO/Sio.h, pcsx2/VMManager.cpp
Adds a counter, set to 300 frames when a write operation is sent to a memory card. Every frame, the counter is decremented. On shutdown, the counter is cleared.
Also moved memory card auto eject countdown function out to Counters.cpp. It will run at the same frequency, it's just now it's not stuck in CDVD anymore, it's in Counters.cpp which makes more sense.
New MemcardBusy::IsBusy() function can be used by the frontend and/or emu thread to detect if memcard activity has happened within the last 300 frames. That can then be used to determine whether to continue with or abort shutdowns, restarts, disc swaps, savestates, etc.
~~I attempted to make the frontend changes but quickly realized I did not understand how anything worked. I am going to either need assistance or pass that off to …
=> Memcard: Add tracking for when memory cards are busy writing

bin/resources/GameIndex.yaml
Bloom effects aren't aligned correctly when increasing internal resolution, enabling Round Sprite and Wild Arms Hack fixes it.
Misaligned effects are bad mmkay
Software (native res)
Hardware (upscaled)
Hardware (upscaled w/fixes)
[GS Dump](https://drive.google.com/file/d/1ObomDS9PyC_puUJjmt4NFmts8H4OWpfX/view?usp=sharing)
=> GameDB: RPM Tuning bloom misalignment fix

bin/resources/GameIndex.yaml
This PR sets HPO to Special setting to fix bloom misalignment seen on player's blood vision. Comparison below:
**Native**
**Upscaled (master)**
**Upscaled (w/fix)**
less tinkering ofc
[GS Dump](https://drive.google.com/file/d/12KPfoViX4THhG6-A2-KLb4NFT_geHxiK/view?usp=sharing)
=> GameDB: Darkwatch Upscaling Fix

.github/workflows/linux_build_qt.yml
Version number changed, breaking our workaround for https://github.com/actions/runner-images/issues/8659.
Fix AppImage building.
Make sure AppImage runs on plain Ubuntu 22.04 install.
=> CI/AppImage: Bump libc6 downgrade version

bin/resources/GameIndex.yaml
GameDB: Remove Merge sprite from God Hand.
It breaks the lighting in the game making it dark, changing the Shadeboost is not a good solution and just masks the issue.
Accuracy.
CI passes.
=> GameDB: Remove Merge sprite from God Hand.

pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Correctly handle the height of copies from old render targets when preloading.
It was copying too much if the target not only overlapped the old one, but was also much bigger, causing crashes (mainly on DX12)
Test hitman contracts, and any other game which crashed on DX12
=> GS/TC: Copy only up to old RT size on preload overlap

bin/resources/shaders/dx11/cas.hlsl, pcsx2/ShaderCacheVersion.h
GS/D3D: Fix X3206 CAS shader warning.
Warning X3206: implicit truncation of vector type warning fix.
Less shader warnings.
Test CAS on DX11/12.
Edit: Tested and CAS works.
=> GS/D3D: Fix X3206 CAS shader warning.

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/DisassemblyWidget.h, pcsx2-qt/Debugger/MemoryViewWidget.h, pcsx2-qt/Debugger/RegisterWidget.h
Fixes #10392 
The inactive CPU widget was being set to focus every time the VM state changed to pause.
Try to reproduce the issue in #10392 
I also fixed a signed-compare warning. Try removing memory search results and verify that it works.
=> Debugger: Don't modify disassembly focus on CPU state change

bin/resources/GameIndex.yaml
adds vu1 clamping to Gun Survivor 3 - Dino Crisis/Dino Stalker
fixes flashing when shooting, solution was captured from the wiki
Watch CI, game already tested.
=> GameDB: Add VU1 clamping to Dino Stalker/Gun Survivor 3 - Dino Crisis

pcsx2/GS/Renderers/DX12/GSDevice12.cpp
No effect, since the runtime overrode it anyway.
Gets rid of a warning with debug device enabled.
Build passes.
=> GS/DX12: Fix a warning during PrimID DATE pipeline creation

pcsx2-qt/MainWindow.cpp, pcsx2-qt/Settings/SettingsWindow.cpp
Fixes #10422.
Test linked issue.
=> Qt: Fix incorrect translation context preventing settings switch

bin/resources/GameIndex.yaml
This PR fixes the menu text artifacts by enabling Round Sprite Half.
Master:
PR:
Artifacting bad
Make sure i didn't miss other things.
=> GameDB: Fixes for Boku no Natsuyasumi 2

pcsx2-qt/MainWindow.cpp, pcsx2-qt/Settings/SettingsWindow.cpp, pcsx2-qt/Settings/SettingsWindow.h
Since per-game settings windows aren't parented, they don't close with the main window. Explicitly close them.
Closing the main window should close PCSX2 completely.
Close main window with a per-game settings/game properties window open. Game properties windows should auto-close.
=> Qt: Fix game properties dialogs keeping app open

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Shouldn't happen under normal circumstances, because VRAM is overcommitted/swapped.
But in the case of a broken driver or weird setup where OOM does occur, log an error and eventually skip the draw instead of crashing.
Crashes are worse than graphical glitches.
Already tested by simulating allocation failure.
=> GS/HW: Don't crash on texture allocation failure

pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp, pcsx2-qt/Settings/MemoryCardSettingsWidget.ui, pcsx2/Config.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/SIO/Sio.cpp, pcsx2/VMManager.cpp
Removes memory card auto eject as an option entirely. No more UI checkbox. No more ini setting. Gone.
Another way to try and stop people from killing their memory cards with savestates. If you load a savestate, your memory cards WILL be ejected. It is the ONLY safe option.
Boot games, make sure auto eject still behaves like it should when loading savestates. Specifically, the memcard contents from when the state was captured need to be different to activate auto eject.
Test Guitar Hero 2 in particular. There were some older code comments calling out this game as hanging when auto eject was enabled; I suspect this might have been silently fixed with time.
Would be a good idea to test other Guitar Hero games for safety - I tested Guitar Hero 3 (NTSC-U) and it was fine both in the main menu …
=> Memcard: Remove option to disable auto eject

pcsx2/Counters.cpp, pcsx2/Hw.cpp, pcsx2/IopMem.cpp, pcsx2/Memory.cpp, pcsx2/Memory.h, pcsx2/SaveState.cpp, pcsx2/SaveState.h, pcsx2/VMManager.cpp
Fix up some reset behaviour to make it more determinate.
Default to interlaced video signal.
Indeterminate behaviour is bad.
Test booting games. Fifa 2004 is a good one as it will fail to boot if the interlace mode is wrong, possibly Petit Copter 2 too
=> Core: Improve determinism on reset + default interlaced

pcsx2/SIO/Sio.cpp
Wait 60 (maybe 59?) vsyncs between eject events for memcards.
It was waiting 1 frame before, however that same frame was the one it got the UI event, so it was basically immediate, so the PS2 never saw the card change, frying your card.
Already tested
=> MCD: Correctly wait 60 frames for eject timeout

pcsx2/SIO/Memcard/MemoryCardProtocol.cpp, pcsx2/SIO/Sio.cpp, pcsx2/SIO/Sio2.cpp, pcsx2/SIO/SioTypes.h
Adjustments from disassembly and some manual tests to make games properly detect the terminator has reset and flagged a card as ejected.
Fixes issues where terminator was still not being picked up as an indicator that a card was ejected; in such cases the time ejected was not enough on its own to warn the game, and cards were still vulnerable.
Test basic load/save functionality. Eject and insert cards, then try again. Load a savestate, then try again.
=> Memcard: Fix terminator not properly flagging ejections

pcsx2/DEV9/ATA/ATA_Info.cpp
PS2 support 28-bit addressing not the the 24-bit addressing. 24-bit addressing is limited by 8Gb storage, while 28-bit is limited by 128Gb
Change hdd max size from 8Gb to 128Gb
Currently, games with official HDD support very fast reach the limit of 8Gb and cannot be installed pass that mark.
Run any app that shows hdd size or free space (launchelf for example). Now it will shows correct size/free space.
=> DEV9: fix incorrect max hdd size

pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Fixes the 16bit depth conversion on shuffles
Also fix the size of the shuffle draw in the CRC hack for NFS Undercover.  Handling the shuffle properly is likely possible, but would need a lot of retooling of the split shuffle handling, and I suspect it will break things.
When the texture was actually 16bit depth on a shuffle, it was telling the shader that the format was actually 32bit, so the conversion was incorrect, breaking the shuffle. Used as a DOF effect.
The CRC was getting trolled by the shuffle code which was halving the width of the draw.
Test NFS Undercover, nothing else really affected.
Master:
PR:
=> GS/HW: Fix 16bit depth conversion in shuffles + fix NFSU CRC

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Mercenaries - Playground of Destruction double half clears from 0x2000 -> 0x2DFF, with the ZBUF at 0x2700. Apparently there's some prior target at this BP, because the half_point check was failing.
~~So, restrict said check to only targets created in the current frame. Doesn't seem to be any casualties on the current GS dump collection.~~
Turns out this was actually a channel shuffle from the previous frame that was getting missed, because it never wrote to Z on this target with the draw... so that is the proper fix.
Also fixes a Vulkan spec violation, but it was probably harmless.
Fixes half-screen garbage in Mercenaries - Playground of Destruction after certain triggers.
Test Mercenaries.
=> GS/HW: Always mark fetched/created depth targets as used

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fixes up source alpha tracking behaviour when using partial preloading
It was doing the wrong comparison, so the alpha never got set.
Test The Getaway, make sure the intro video shows
The Getaway
Master:
PR:
=> GS/HW: Fix source partial preload alpha tracking behaviour

pcsx2/Achievements.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
This PR changes the way Discord Rich Presence shows time elapsed. Now instead of updating on every single RPC change, the time only gets reset on:
* Starting the emulator
* Starting/stopping the game
It is more meaningful to show how long the user has been in a specific game than to show how long the current Rich Presence string has been active for.
1. Run any game with RetroAchievements Rich Presence, with Discord Rich Presence enabled.
2. Perform any actions in-game that change the presence string.
3. Confirm that the "Time elapsed" display on Discord does **not** reset when the presence string changes.
Closes #10390
=> DiscordRPC: Show session time in Discord Rich Presence

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/CpuWidget.ui
Implements #10266
Adds the ability to do debugger memory searches for values that are not equal to, greater than (or equal), or less than (or equal) to the search value.
Does not tackle `[Not] Changed`, `[De/In]creased`, or `[De/In]creased By` in this PR as it increases the scope of the issue and the changes required. Adding this as the initial step + refactoring to make it easier to add more in the future.
___
Currently it is not possible to search for a value that is not _exactly_ known. Adding the ability to do > or < searches allows finding a bulk of values and narrow down results. Not Equals also helps filter out/narrow down results lists for values we know we don't need or don't want.
___
I highly recommend validating > and < (and >=, <=) with float and double, and any int type. …
=> Debugger: Add memory search types: GreaterThan(OrEqual), LesserThan(OrEqual), and Not Equal

pcsx2-gsrunner/Main.cpp, pcsx2/GS/GSPerfMon.cpp, pcsx2/GS/GSPerfMon.h, pcsx2/GS/Renderers/Common/GSRenderer.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Fixes games which reverse their texture shuffle coordinates, causing bad detections in our code.  Mostly fixes fog effects.
This was getting false shuffles, causing the wrong thing to be shuffled out.
Also fixed the performance metrics for games which have idle frames, they were erroneously getting divided by two
Test the games listed below, smoke test others, though dump run says everything else is unchanged.
Fixes #7292 
Colin McRae Rally 2005 (Though still broken, only less):
Master:
PR:
Grand Prix Challenge:
Master:
PR:
Test Drive Unlimited:
Master:
PR:
Transformers:
Master:
PR:
Master:
PR:
=> GS/HW: Fix texture shuffles with reversed co-ords

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Change dirtys to only update on draw if they intersect the draw.
Also fix some FindSource in targets with regions and offsets.
The only clear dirty on intersect change was for MotoGP4 where it uploads a C16 image to the top left of the Z buffer, then uses that Z buffer again on the next draw, then the draw following that is using the image.  This was getting in to a mess and being translated as a Z24 format, which corrupted the image.
The region stuff was a bug I encountered trying to fix up the other behaviour, when looking for a target we were using the incoming rect, which was post-regioning with the clamp, so we needed to re-add the offsets when looking up the target, this was a problem with Rugby 08 and possibly the FIFA games, however mipmapping still doesn't work it seems when …
=> GS/HW: Only update dirty if intersects + fix tex is rt regions

pcsx2/Input/SDLInputSource.cpp, pcsx2/Input/SDLInputSource.h
For users with controllers that don't have a corresponding GameControllerDB entry, you had to create one, then replace the supplied `game_controller_db.txt` in resources.
This didn't work on Linux, because the AppImage/Flatpak is immutable. On MacOS, it requires re-signing the bundle.
So, load it from the data directory if the file exists there.
Easier for users to support their broken-ass off-brand controllers.
Make sure controllers still work.
=> SDLInputSource: Optionally load game_controller_db.txt from data dir

pcsx2/x86/iFPU.cpp
The `andps+minss+maxss+orps` sequence was from the SSE2 days when you couldn't do integer min/max. Since SSE4 is our baseline, save a temporary register, and an extra two dependent instructions by using `pminsd+pminud` instead. Same as the VUs.
Micro-optimizations.
Smoke test a couple of games. I've verified the instruction sequence produces the same output for all inputs, so it should be fine.
=> x86/FPU: Use SSE4 pminsd+pminud for sign clamping

pcsx2/GS/Renderers/HW/GSHwHack.cpp
Need to track the FBMSK as well. The transition at the start of the race does both an RGB and A shuffle, but obviously changes FBMSK mid-way, so we can restart then.
For the A shuffle, the Prologue version shuffles into FBP0 from a different TBP0, so we can't use that as an indicator. Luckily, all the alpha destination shuffles seem to write to FBP0, so we can get away with just hardcoding it.
Fixes transitions in Prologue version, and the coloured strip when starting normal races.
Closes #8370.
Before:
After:
Test GT4, GT4 Prologue.
Check both NTSC and PAL for the former, make sure the fix for the pink strip in #10144 didn't break (@JordanTheToaster).
=> GS/HW: Further improve GT4 render fix

pcsx2/Gif_Unit.cpp, pcsx2/Gif_Unit.h
#10448 uncovered an assertion in GIF that assumed it would be evaluated - said assertion was actually the processing of the packet. Assertions should never have side effects.
Fixes Tony Hawk games locking up on boot. Regression from #10448.
=> GIF: Get rid of assertion with side effects

common/CMakeLists.txt, common/vsprops/QtCompile.props, pcsx2-qt/CMakeLists.txt, pcsx2/CMakeLists.txt
`PrecompiledHeader.cpp` only exists for generating the PCH with MSBuild, not needed for CMake.
Ever-so-slight reduction in build times.
CI passes.
=> CMake: Don't compile PrecompiledHeader.cpp

.github/workflows/scripts/macos/build-dependencies.sh
This seems silly, but since we don't have a direct reference to QtSvg, it doesn't deployed directly from the main binary (only indirectly from iconengines), and the libqsvg.dylib imageformat plugin does not get deployed.
Patch macdeploy to remove the Svg check, ensuring the dylib is always deployed.
Fixes controller images not being displayed in Mac builds.
Check for controller images in Mac build.
=> Qt: Patch macdeployqt to always deploy Qt SVG imageformat plugin

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Fixes some behaviour for alpha shuffles, also fix handling of dst matches when target is used as a source or the entire content is invalidated.
__Channel shuffle change__: Alpha just wasnt' handled, there was a note there saying "let's choose blue" like a flip of a coin.
__DST Matches change__: There were cases where games were using a target as a different format, or adding an alpha channel to a 24bit value, but things were getting out of sync.  Terminator 3 was using this with old data in the RGB (where the depth was), Final Fantasy X-2 used part of the Z buffer as a 16bit target, but this later got completely cleared and we weren't removing the target due to the valid size being different, now we invalidate dst matches based on the area drawn to them.
Check The Terminator 3 and the …
=> GS/HW: Fix some channel shuffle and target match behaviour

bin/resources/GameIndex.yaml
Adjustments per refractionpcxs2's comment: https://github.com/PCSX2/pcsx2/pull/10475#issuecomment-1869172085
Using "dot hack - " instead of ".hack//" for titles 
There's apparently a bug with QT regarding // and some filenames, just wanted to make them all match up since JP used .hack// as the title instead of the EN dot hack -
=> GameDB - Fix dothack titles

bin/resources/GameIndex.yaml
Recommend full blending to fix grey text.
Basic blending.
Full blending.
Accuracy, for those who don't mind any performance changes.
[Silent Hill - Origins_SLUS-21731_20231225220536.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/13768231/Silent.Hill.-.Origins_SLUS-21731_20231225220536.gs.zst.zip)
(Remove zip extension)
=> GameDB: Recommended blending for Silent Hill: Origins.

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Don't use threaded presentation when spinning is enabled. ScanForCommandBufferCompletion() calls vkGetFenceStatus(), which reads a fence that has been passed off to the thread.
Spec violations.
=> GS/Vulkan: Disable threaded presentation when spin is enabled

.gitignore, pcsx2-qt/Debugger/Models/BreakpointModel.cpp, pcsx2-qt/Settings/AdvancedSettingsWidget.cpp, pcsx2-qt/Settings/AudioSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2/SIO/Pad/PadDualshock2.cpp
This PR attempts to fill missing description in certain sections of the settings.
See commit list for more information.
Fixes #6937 
Preview:
Missing Description Bad.
Make sure i don't break other stuff.
=> Qt: Some description works and other misc UI improvements

pcsx2/VMManager.cpp
Don't need to look at clusters, total CPU count is the only needed metric.
Simplification, fixing MTVU defaults in VM configurations with whacky topologies.
CI passes.
=> VMManager: Simplify CPU heuristics for MTVU default

pcsx2-qt/Settings/SettingsWindow.cpp
When you select game properties, you expect the properties window to get brought to the front/activated.
Launch game, open game properties, select main PCSX2 window to obscure the game properties window.
Select game properties again. Existing window should be activated.
=> Qt: Fix game properties dialog not activating

pcsx2/GameList.cpp
Apparently this is the reason we don't allow colons in GameDB titles.
Making it so GameDB titles can match the actual game.
Make sure your existing covers show up.
=> GameList: Sanitize all cover paths

bin/resources/GameIndex.yaml, pcsx2/x86/iFPU.cpp
Finally had the chance to look into this. The "Full Throttle" text getting stuck on screen seems to be due to the following block of instructions (NTSC-U, Version 1.01):
```
003A9820 sw   zero, 0x  14(a0)
003A9824 neg.s        f03, f00
003A9828 mul.s        f03, f03, f12
003A982C lwc1 f01, 0x   0(a0)
003A9830 mtc1 zero, f00
003A9834 lui  at, 0x3F80
003A9838 mtc1 at, f02
003A983C add.s        f01, f01, f03
003A9840 max.s        f00, f01, f00
003A9844 min.s        f00, f00, f02
003A9848 jr   ->ra
003A984C swc1      f00, 0x   0(a0)
```
Forcing full EE FPU clamping for this block fixes the text. But that's a janky solution, because it would mean finding the offsets for every release/revision. Instead, I noticed that we're using floating-point min/max, which means that negative NaNs get punted …
=> x86/FPU: Always preserve sign in neg.s (Fix GT4 text)

pcsx2-qt/QtHost.cpp, pcsx2/R5900.cpp
Recreated https://github.com/PCSX2/pcsx2/pull/2576 for QT
Useful feature for homebrew, but some retail games will also benefit from it. More details in PR mentioned earlier + below added an example of Splinter Cell command.
This can be tested in [Tom Clancy's Splinter Cell](http://redump.org/disc/3812/) cause this game support arguments (credits to @rickgaiser). If you mount an iso in virtual drive `/dev/rdisk2` then you can choose the following command to directly start the game and skip the main menu (MacOs command, Windows commands can be different):
```sh
./PCSX2.app/Contents/MacOS/PCSX2 -disc /dev/rdisk2 -elf /Volumes/SPLINTER_CELL/LOADER.PS2 -gameargs "cdrom0:\\LOADER.PS2;1 0_0_2 -wantload -ll -diskimage -restart -l=1 -v=13117"
```
It will boot directly into this screen:
fixes …
=> QT: Return ability to pass launch arguments with CLI option -gameargs

pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/DEV9/ATA/Commands/ATA_SCE.cpp
This commit introduces the capability to read the content of a *.hddid file located in the same directory as the HDD image (same name, different extension). The retrieved content is then used to fill the SCE_IDENTIFY_DRIVE response.
Some PS2 apps requires that SCE_IDENTIFY_DRIVE not only return true, but also needs proper content of its response. The response is unique for each HDD. 
It improves previous https://github.com/PCSX2/pcsx2/pull/9263 Next step to the PlayOnline Viewer games and BB Navigator games support.
PlayOnline Viewer games:
- Final Fantasy XI: Online NTSC-U http://redump.org/disc/15026/
- Final Fantasy XI: Online NTSC-J http://redump.org/disc/79596/
- Tetra Master NTSC-U http://redump.org/disc/5794/
- Tetra Master NTSC-J http://redump.org/disc/27151/
- Janhourou …
=> DEV9: Add support for external HDD ID

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Removes old targets if the width changes and is drawing outside the height of a page, if it's not a clear and the target is dirty.
In this scenario, the likelyhood is the target is changing to something new, which was the case with Medal of Honor, causing the texture to be the wrong shape, which can mess up the rendering. The only other solution would be for us to rearrange targets on width change, but we don't do this currently.
Test some random games and Medal of Honor - European Assault
Medal of Honor - European Assault:
Master:
PR:
=> GS/TC: Remove old targets when changing width and outside a page

pcsx2/GS/Renderers/DX11/D3D.cpp, pcsx2/GS/Renderers/DX11/D3D.h, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
There's no point showing GPUs in the list that don't support the required Vulkan version, or extensions, since they won't be usable.
More critically, it throws off the automatic renderer check, and tries to create a Vulkan device that fails, instead of falling back to D3D. Thanks AMD for not supporting a 2016/2017 extension on your GPUs released in 2019, then dropping support for them entirely.
Less user complaints that they can't start PCSX2, because they're using 3 year old drivers.
Make sure Vulkan still works on NV/AMD.
=> GS/Vulkan: Ignore GPUs that don't meet the required extensions

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Fix source rect for target lookups. Also fix some invalidation issues
I kinda messed up in #10424 and forgot that the region is included in the incoming rect, so I pushed up the end of the rect twice as far as it should have been, which broke some stuff.
Invalidation had a problem when translating the start page for negative positions, or when the format was changed from 8bit to 32bit, these are now resolved (or at least much better.)
Test Ace Combat Zero, Pirates - Legend of the Black Kat, and I guess some random stuff.
Fixes #10489 
also fixes issues with Pirates - Legend of Black Kat
Fixed issue with Dark Cloud 2
Ace Combat Zero:
Master:
PR:
Dark Cloud 2:
Master:
PR:
Pirates - Legend of Black Kat:
Master:
PR:
=> GS/HW: Only check requested rect for source lookup +2 invalidation issues

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Improves matching of dst_matched targets and stops expansion when the the draw is expecting DATE (Alpha >=1) is set, since we expand to black, so this will never be true.
I was stopping some stupid expansion that The Getaway Black Monday does, and kinda went down a bit of a path trying to keep duplicated targets matched up on either color/z side.
Test random games, would be nice to check The Getaway Black Monday for random glitching (Silent was going to check this).
Games to test which showed up in the dump with either shrunk targets or less copies:
Ace Combat 04
Shin Megami Tensei - Persona 3
No known fixes, however.
=> GS/HW: Fix some target resize/clear handling

bin/resources/GameIndex.yaml
Add NTSC-C game's official chinese name in GameDB, also a transliteration (Hanyu Pinyin) for sorting.
This addition is to make it easier to search the game using the official Chinese name.
Copy from [Here](https://club.tgfcer.com/thread-7165750-1-1.html).
=> GameDB: Add NTSC-C game's official Simplified Chinese name

pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_In.cpp, pcsx2/DEV9/Sessions/UDP_Session/UDP_FixedPort.cpp, pcsx2/DEV9/Sessions/UDP_Session/UDP_Session.cpp
probably just new fallout for only me since 47a65ce01ec48ad6f38468c201547bacec98d969 but i didn't bisect
replace u_long with unsigned long and include `<sys/select.h>` for `fd_set`/`FD_ISSET` etc in the posix path. 
fixes downstream builds against musl libc on linux (which is strict about header namespaces and doesn't have nonstandard typenames like `u_long` aliased to `unsigned long`).  
(nobody cares about this but me, but this should be a completely harmless change anyway)
make sure nothing broke in dev9, but this should yield identical build output to before
=> DEV9: fix some missing includes and nonportable u_long type use

pcsx2/GS/Renderers/Metal/GSDeviceMTL.h, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/GS/Renderers/Metal/GSTextureMTL.mm
Adds labels to textures based on their usage and a counter
If a texture doesn't have a label, Xcode's GPU debugger gives it the amazing label of `sprintf(label, "Texture %p", this)`, which is very non-memorable and makes keeping track of which textures are going where much more painful than it needs to be.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</Summary>
</details>
=> GS:MTL: Give labels to textures

pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Round 3 with this damn game. Hopefully got it this time. In the split-channel/alpha render fix, I wasn't actually writing alpha with the colour information, so the transition was black instead of from the previous frame.
Also fixes incorrect target texture invalidation, because GT4 writes to the target as C24, it was tossing the alpha channel, which could cause graphical corruption (DONT_CARE load action). Unfortunately it adds an upload/draw in Dirge, Arse Combat and a couple of others, but at least we don't have indeterminate alpha channels hanging around that are flagged as valid...
Test GT4 transitions.
=> GS/HW: Properly fix GT4 fade transitions (again)

pcsx2-qt/Settings/GamePatchDetailsWidget.ui, pcsx2-qt/Settings/GamePatchSettingsWidget.ui
Disables vertical scrolling in favour of word wrap on the patch names and description boxes.
Master:
PR:
Better readability.
Make sure that the Patches tab looks OK.
=> GamePatchSettingsWidget: Enable word wrap for long patch names/descriptions

pcsx2/IopBios.cpp
Regression from https://github.com/pcsx2/pcsx2/commit/bbc0bcae1e39bea6f49f89a08a4bb67b5edb4eac (#6551)
FindFiles returns false when the directory is empty or the path is NULL, **not** when there is an error like the old GHC implementation. This made it so you couldn't `dopen` an empty directory.
=> IOP HLE: Fix broken dopen implementation

bin/resources/GameIndex.yaml
Recommends 'Full' blending setting
Solves lighting flickering issues.
Please check that 4 is the 'Full' setting, if not, then inform me.
**Blending Accuracy:** Basic
**Blending Accuracy:** Full
=> GameDB: 007 - Agent Under Fire

pcsx2/GS/GS.cpp, pcsx2/GS/GSState.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/MTGS.cpp
Regression from #10523, and a preexisting issue (switching from sw -> hw).
me make a boo boo
Set renderer to software, make sure F9 actually switches to hardware. Check inverse of this.
Make sure catwoman dump is the same in SW, and HW switched to SW.
=> GS: Fix autoflush init after renderer switch

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp, pcsx2-qt/Settings/GameCheatSettingsWidget.h, pcsx2-qt/Settings/GamePatchSettingsWidget.cpp, pcsx2-qt/Settings/GamePatchSettingsWidget.h, pcsx2-qt/Settings/SettingsWindow.cpp
The `Clear Settings` button will now disable all cheats and patches from the configuration. This will allow quickly resetting to having no game altering pnach patches/cheats.
Implements #10255
One may expect all their configuration for a game including patch/cheat selections to disable when pressing the `Clear Settings` button. This allows them to reset to a full default as cheats/patches can make a significant impact on the game.
Verify all patches/cheats are removed from the gamesettings config.
=> Qt: Clear Settings button disables Cheats/Patches

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.ui
Adds support for doing `Not Equals` filter searches for Arrays/String searches.
Previously only `Equals` was supported for array/string searches.
Also condenses the memory search `Start`/`End` inputs into one line to make space for future UI elements, and adds a `Comparison` label to label the search comparison type dropdown.
**Note**: Does not support `Not Equals` initial searches, as this would create huge amounts of unnecessary and useless reads/results.
___
___
___
Not Equals array and filter searches allow for easy filtering of results/narrowing down strings/data you don't want after seeing the values/results.
The UI changes were made at request, with the `Comparison` label being added so that the dropdown is labeled just as `Type` is.
The `Start` and `End` were changed to one line …
=> Debugger: Add Not Equals Array/String filter searches + minor memory search UI change

README.md
This PR updates the frontpage readme to be more concise. Much of the old information has been moved over to the new documentation site and no longer needs to be duplicated.
Cleanliness, remove duplicate data
Preview of changes:
=> Readme: Update and Remove Redundant Info

pcsx2/DebugTools/Debug.h, pcsx2/LogSink.cpp, pcsx2/R5900OpcodeImpl.cpp, pcsx2/SourceLog.cpp
Remove the syscon logging and merge the syscall logging with the generic EE debug logging
It's effectively the same thing. The EE logs cover DECI2 and SIO writes. The syscon logs cover the printf syscall on the EE.
I've tested and it works.
=> Core: Set syscon log colour to the EE's log colour

.gitignore, pcsx2-qt/Settings/GameCheatSettingsWidget.cpp, pcsx2-qt/Settings/GameCheatSettingsWidget.ui, pcsx2-qt/Settings/GamePatchSettingsWidget.cpp, pcsx2-qt/Settings/GamePatchSettingsWidget.ui, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Patch.cpp, pcsx2/Patch.h
Makes the default functionality to search for Cheats/Patches for all CRCs for a particular game a toggle-able setting.
This functionality was changed in #9246, changing it from only showing the current CRC to showing all available CRCs. This keeps the new functionality as default while allowing the ability to override it.
**Note:** Also adds `/bin/patches` to `.gitignore` so patches in the development folder aren't considered a commit-able change. (Just as the cheats folder is currently handled)
___
This helps for decluttering cheat lists and showing only Cheats/Patches meant for a particular CRC.
As one who owns multiple regions in order to write patches for different versions (and thus has many copies of a patch that are incompatible with each other) it is difficult to deal with. Being …
=> Qt: Make Patch/Cheat Settings 'Show All CRCs' a toggle-able setting

pcsx2/GS/GSUtil.cpp
Corrects the auto renderer selection on linux if OpenGL and Vulkan are both enabled.
If OpenGL was enabled, it was always overriding the renderer with OpenGL, even if Vulkan was fine.
Boot a game on linux (or steamdeck) with the renderer set to auto, make sure it boots using Vulkan if actually supported. You can check this in the emulog for `Allowing Vulkan as default renderer.`
=> Linux: Stop OpenGL overriding Vulkan if both VK and OpenGL are enabled

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Catwoman draws to the target at 2E60 via 2D00, one page back horizontally, and one vertically.
The Destroy All Humans fix also works here, but it only applied to the texture, not the RT. So do a very conservative form of RT-in-RT to handle Catwoman.
Also adds round sprite full to fix post-processing alignment when upscaled.
Closes #10542.
Before:
After:
Test Catwoman.
=> GS/HW: Handle offset RTs when offset texture is detected 

pcsx2-qt/CMakeLists.txt, pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/CpuWidget.ui, pcsx2-qt/Debugger/MemoryViewWidget.cpp, pcsx2-qt/Debugger/MemoryViewWidget.h, pcsx2-qt/Debugger/Models/SavedAddressesModel.cpp, pcsx2-qt/Debugger/Models/SavedAddressesModel.h, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters
Adds the ability to save memory addresses to a newly added `Saved Addresses` tab widget in the debugger.
Works as a way to bookmark memory addresses and allow jumping back to saved addresses.
Adds the ability to add memory addresses as a Saved Addresses from the Memory Search results list context menu and `Memory View` context menu. Also allows exporting and importing the Saved Addresses in CSV format so that users can save/restore their addresses.
- Updates double clicking Memory Search results to change the current tab to the `Memory View`. Previously it would change the address but stay on the same widget (thus not showing the address to the user).
- Replaces uses of the number `256` as a literal in place of `Qt::UserRole` to make it more clear what it's purpose is/where the number …
=> Debugger: Add Saved Addresses tab widget for bookmarking memory addresses

cmake/BuildParameters.cmake, pcsx2-qt/Settings/MemoryCardConvertDialog.cpp, pcsx2/DEV9/Sessions/ICMP_Session/ICMP_Session.cpp, pcsx2/Dmac.cpp, pcsx2/GS/Renderers/Common/GSFunctionMap.h, pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.cpp, pcsx2/GS/Renderers/SW/GSRendererSW.cpp, pcsx2/IPU/IPU_Fifo.cpp, pcsx2/ps2/BiosTools.cpp
Enabled some previously disabled warnings. Fixed the existing code that caused those warnings to fire.
Only applicable to clang/gcc builds.
Forces people to write warning-free code :smiling_imp: :nail_care: 
Check CI and see if the format stuff is proper.
=> Misc: Enable some disabled warnings

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp, pcsx2-qt/Settings/GameCheatSettingsWidget.h, pcsx2/Patch.cpp
What a mess...
Also fixes the discrepancy between the number of patches shown in the UI, and the OSD.
But you really should move over to labelled patches. Editing/uncommenting pnaches by hand is terrible.
Fixes #10561.
Test linked issue, and make sure that local patches still override zip patches.
=> Patch: Fix ungrouped patches from >1 file not merging

.gitignore, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2-qt/SetupWizardDialog.cpp, pcsx2-qt/Translations.cpp, pcsx2/Achievements.cpp, pcsx2/Config.h, pcsx2/ImGui/ImGuiManager.cpp, pcsx2/Input/SDLInputSource.cpp, pcsx2/Pcsx2Config.cpp
This PR adds automatic downloading of CJK fonts for use with the OSD/Big Picture, which currently don't exist on Linux, and are platform-specific on Windows/Mac.
It also adds the ability for selected resources to be overridden by the user, including fonts and sounds. If you hate the achievement sound effects, for example. Doing so requires you to use **non-portable** mode, and place the files in `Documents/PCSX2/resources`.
Closes #10524.
- Test CJK languages in OSD/Big Picture.
- Switch from both the setup wizard, as well as interface settings.
=> Qt: Add runtime downloading of CJK OSD fonts

bin/resources/GameIndex.yaml
Adds HPO Special to help with blur caused by upscaling.
Blur bad.
=> GameDB: DMC 1 Fixes

pcsx2-qt/Settings/ControllerBindingWidget_Popn.ui, pcsx2-qt/Translations/pcsx2-qt_en.ts
This PR removes the translation hint from Pop'n Music bindings as it is unnecessary and the string SHOULD be localizeable.
Making Translation Better
Make sure i don't miss other stuff
=> Qt: Minor Translation Fixes

bin/resources/GameIndex.yaml, pcsx2-qt/Settings/AdvancedSettingsWidget.cpp, pcsx2-qt/Settings/AdvancedSettingsWidget.ui, pcsx2-qt/Settings/GameFixSettingsWidget.cpp, pcsx2-qt/Settings/GameFixSettingsWidget.ui, pcsx2/Config.h, pcsx2/Docs/gamedb-schema.json, pcsx2/GameDatabase.cpp, pcsx2/GameDatabase.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/x86/iFPU.cpp, pcsx2/x86/iFPUd.cpp
I can't escape the curse of GT4 :cry:.
Turns out the Japanese release of GT4 crashes with nearest rounding on division, because of this abomination (see https://github.com/PCSX2/pcsx2/issues/10550#issuecomment-1878506216):
Another, potentially cleaner solution is to use chop for division as well as rounding, which apparently prevent the error from accumulating in this routine, and causing the validation to fail.
I'm a bit iffy about changing the default behaviour to follow the normal rounding mode this close to a release, so while that's something we could consider in the future, a stop-gap measure is to make the force-to-nearest-rounding opt-in. And at the same time, get rid of the negative division gamefix, since it can be represented using this new value instead.
According to #3816, it …
=> Config: Replace FpuNegDivHack with eeDivRoundMode

bin/docs/ThirdPartyLicenses.html, pcsx2-qt/AboutDialog.cpp, pcsx2-qt/AboutDialog.h
Something I added to DuckStation a while back and have been meaning to bring across. 
Some licenses require you to include their appropriate notices in software that uses their code, so we should do so to be compliant.
Help - > About PCSX2 -> Make sure License/Third-Party Licenses links work.
=> Qt: Add third-party license statements

pcsx2/PINE.cpp, pcsx2/PINE.h
PR #10448 introduced two regressions to PINE:
- Inverted the OOB checks, causing it to return that a packet is unsafe when within bounds
- Used the incorrect type for socket binding, leading to the socket never binding on Windows.
This fixes both regressions
PINE was broken
Well a bit late but compile and run the sample client from here: https://projects.govanify.com/govanify/pine
This fixes #10582
=> PINE: fix regressions introduced in #10448

bin/resources/GameIndex.yaml
- Removed CPU Sprite Renderer from Armored Core Last Raven. It fixes broken shadows.
- Minor change: Replace katakana with hiragana for `name-sort` of three Armored Core [Machine Side Box] games.
Broken shadow is now big problem for players. But this change makes glow effects on the wall of red internecine levels vanished again.
Already tested by Jordan.
=> GameDB: Fix broken shadows in Armored Core Last Raven

bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/Metal/tfx.metal, pcsx2/ShaderCacheVersion.h
Allow blending on normal shuffles (special shuffle types excluded)
Previously we checked if the RGB channels were being written to enable blending, however this isn't actually true with shuffles, since half of the write represents a whole channel, not just the alpha channel (of 16bit).
Test random games, make sure the colours are okay. Test Bully in native resolution.
Fixes Bully Depth of Field offset in native resolution (lessened problem when upscaling)
Before:
After:
=> GS/HW: Allow blending on normal shuffles for Bully Depth of Field

pcsx2-qt/QtHost.cpp
Stops the status bar showing HW when switched to SW, or displaying "Auto".
Regression from #10523.
CI passes.
=> Qt: Fix incorrect renderer shown in status bar

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Fixes failed double-half clear detection due to a 211-frame old target hanging around in Wakeboarding Unleashed featuring Shaun Murray.
Before:
After:
CI passes, dump run is clean.
=> GS/HW: Don't rely on old targets for double-half clear

pcsx2/GS/GSState.cpp
Checks the address of GS transfers when checking if a flush is required.
Armored Core was trying to copy the Colour framebuffer at 0x0 to 0x1180, the home of the Z buffer, with a draw pending which used that Z buffer, however it didn't trigger this because it wasn't overwriting the pending draw, the problem being when a Z target is picked, it'll kill any colour targets to avoid duplication, so the copy was being made, then it was being killed, so data was instead pulled from GS memory, not a good time.
Also fixes the text on the screen in Dr. Seuss' The Cat in the Hat, didn't look in to the reason why, probably a similar reason since software was okay.
Test Cat in the Hat and Armored Core 2 and 3 (pause screens included)
Armored Core 2 pause screen:
Master:
PR:
Dr. Seuss' The Cat in the …
=> GS: Flush draw when address matches FRAME/Z

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Detect striped moves in hardware moves
If a game decides to transfer one line at a time with a single page width/height,, right now it'll do the first line then do the rest in native resolution, this should fix that.
Also added merge sprite to Sakura Teisen to remove the blur from the picture.
Test Sakura Teisen - Atsuki Chishioni, make sure upscaling works okay (GS dump tested only)
Fixes #10056
Master:
PR:
=> GS/HW: Detected striped moves in HW

.github/workflows/cron_publish_flatpak.yml, .github/workflows/linux_build_flatpak.yml, .github/workflows/linux_build_qt.yml, .github/workflows/macos_build.yml, .github/workflows/release_cut_new.yml, .github/workflows/windows_build_qt.yml, cmake/Pcsx2Utils.cmake
- I missed updating the flatpak cron workflow so this has a quick fix for that
- Found a problem in the cmake tagging code (likely also exists in the msbuild code but that isn't used for releases).  If a commit had multiple tags it would not handle it well.  Now it grabs the latest tag, but it's worth being aware of this as there is a race condition here (don't kick off a bunch of releases for the same commit at the same time).
- Added a way to manually kick off a release with a custom tag, this will be needed for doing non-regular, non-prelease builds.
I tested it over on my fork:
- one from the automatic push to master https://github.com/xTVaser/pcsx2-rr/releases/tag/v2.0.2
- one from manually kicking off a prerelease https://github.com/xTVaser/pcsx2-rr/releases/tag/v2.0.3
- one from …
=> CI: fix flatpak cron and add a way to manually kick off a release

bin/resources/GameIndex.yaml, pcsx2-gsrunner/Main.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Upgrades a target to 32bit from 24bit if the src is rt requests it and needs the alpha
Armored Core - Last Raven was rendering a texture for the VFX in 24bit but uploading the alpha channel, so when it used it as a source and was doing the draw based on an alpha test, it was failing to draw them completely. This upgrades the texture to C32 and adds in the alpha channel.
Edit: As usual I blew the scope up a little, and fixed some bugs with updating dst_matched targets as it was skipping every other dirty rect if there was still dirty alpha, this fixes Kenran Butousai but also some underlying issues with Driv3r, but also re-sorted how valid channels are selected, etc.
Test random games, but also Armored Core - Last Raven, Ty the Tasmanian Tiger, Kenran Butousai, and the Ratchet games showed …
=> GS/HW: Upgrade target to C32 if alpha requested on src is rt

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Skips drawing empty rect draws.
This doesn't actually draw anything, but just makes weird targets with bad information (the Dark Cloud example had a start BP of 0x1A40 and end of 0x1A3F because of how it's calculated).
Test random games, a bunch of stuff showed up in a GS dump (probably due to lack of resizing), try Dark Cloud.
Dark Cloud
Master:
PR:
=> GS/HW: Don't bother trying to draw empty draws

pcsx2/GS/Renderers/Metal/GSDeviceMTL.h, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/GS/Renderers/Metal/convert.metal
Properly handles hdr rendering to cleared textures
HDR rendering starts by rendering to an hdr texture, then copying that to the original texture, which means that any clears don't get noticed by the BeginRenderPass code.  We could just `FlushClears` the main rt before hdr, but we might as well save a texture copy by just clearing the HDR target instead.
Test [this Ico gsdump](https://github.com/PCSX2/pcsx2/files/13747729/Ico-ShadowTrails.gs.xz.zip)
=> GS:MTL: Properly handle hdr rendering to cleared textures

pcsx2/MTGS.cpp
Linux appears? to inherit the value of MXCSR from the creating thread, and that breaks parts of the software renderer.
This broke when switching from clang-16 to clang-17, it's smelling like something to do with denormals (since the EE thread sets FTZ/DAZ), but I can't be bothered to check for code differences to say for certain.
Fixes some games being broken in Software on Linux.
Check SH3 and whatever the other broken game was on AppImage.
=> MTGS: Explicitly set FP control register on startup

pcsx2-qt/Settings/GameCheatSettingsWidget.cpp, pcsx2-qt/Settings/GamePatchSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
Add an on hover description to explain the purpose of the 'All CRCs' button in the Cheat and Patch Settings window.
Also adds a minor text change to adjust 'Kbps' to 'kbps' by request in graphics settings.
Reduces potential confusion about the exact purpose/effect it has.
- Just validating that the text appears on hover.
- Validating `Settings->Graphics->Recording` shows the lowercase "kbps" text for Audio Bitrate.
No other impact area.
___
**Cheat & Patch Settings windows:**
**Audio Bitrate text change:**
=> Settings: Adds on hover description to 'All CRCs' on hover for cheat/patch settings

pcsx2/VMManager.cpp
Async mix should be purged 😠 .
Closes #10609.
=> VMManager: Force TimeStretch in Achievements HC Mode

cmake/Pcsx2Utils.cmake
Apparently setting a variable with `PARENT_SCOPE` doesn't apply it in the current scope. Thanks CMake.
This didn't show up on the Linux CI, because apparently they have a later version of CMake installed somewhere else in PATH.
Closes #10608.
CI passes.
=> CMake: Set LINUX in current and parent scope

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Mismatched sizes are a spec violation for hardware devices.
Was triggering in SOTC booting.
Regression from #10478.
=> GS/HW: Fix drawing with mismatched target sizes

common/Console.cpp, common/Console.h, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h
Make System Console and Verbose contingent on Advanced Settings being enabled.
Make Debug Console contingent on actually running under a debugger.
Less cramped.
Make sure menu items are hidden without advanced, shown with.
Restart PCSX2 inbetween and make sure it behaves itself.
=> Qt: Tidy up Tools menu

pcsx2-qt/DisplayWidget.cpp, pcsx2-qt/QtHost.cpp, pcsx2/ImGui/ImGuiManager.cpp, pcsx2/ImGui/ImGuiManager.h, pcsx2/MTGS.cpp
Currently, you can't toggle fullscreen by double clicking the left mouse button when PCSX2 is paused via the hotkey, this PR fixes that.
Quality of Life improvements
Try toggling fullscreen while paused, make sure it works properly.
=> FSUI: Allow toggling fullscreen when VM is paused

pcsx2-qt/QtHost.cpp, pcsx2/Cache.cpp, pcsx2/Dmac.h, pcsx2/GS/GSCapture.cpp, pcsx2/GS/GSDrawingContext.cpp, pcsx2/GS/GSDrawingContext.h, pcsx2/GS/GSDrawingEnvironment.h, pcsx2/GS/GSRegs.h, pcsx2/GS/GSState.cpp, pcsx2/GS/GSVector4.h, pcsx2/GS/GSVector4i.h, pcsx2/GS/GSVector8.h, pcsx2/GS/GSVector8i.h, pcsx2/GS/Renderers/Common/GSVertex.h, pcsx2/GS/Renderers/DX11/GSTexture11.cpp, pcsx2/GS/Renderers/DX11/GSTexture11.h, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/IPU/IPU.h, pcsx2/IPU/IPU_MultiISA.cpp, pcsx2/SPU2/SndOut.h, pcsx2/Vif.h, pcsx2/x86/ix86-32/iR5900.cpp
Most involve making types POD.
For the vector classes, in debug builds, we get an inlined 8-byte-at-a-time move, instead of a call. In release, it gets inlined to a vector move as you would expect.
Some of these were legitimate errors, like in GSCapture and reading uninitialized variables in the IPU.
Tidy tidy
Make sure HW and SW renderer performance is unchanged.
Usual smoke tests.
Dump runner says it's okay.
=> Misc: More warning cleanup

.github/workflows/linux_build_qt.yml, .github/workflows/scripts/linux/build-dependencies-qt.sh
Implemented for Mac in #10506, adding to Linux.
Letting users specify where dependencies end up.
AppImage still runs.
=> CI: Allow user to override deps build path

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Don't mark the alpha as valid when upgrading 24bit alpha to 32bit
turns out this was a bad idea, Ratchet 3 wasn't very happy.
Test Ratchet & Clank 3
Fixes #10626
Master:
PR:
=> GS/HW: Don't mark 24bit alpha as valid on upgrade

pcsx2-qt/AutoUpdaterDialog.cpp, pcsx2-qt/AutoUpdaterDialog.h, pcsx2-qt/QtHost.cpp, updater/Windows/WindowsUpdater.cpp
Some users want to install PCSX2 to Program Files. Currently, they can't update.
This PR runs the updater as Administrator if it detects that it can't write to the PCSX2 directory.
Note that if you actually want to run PCSX2 out of Program Files, you'll also need to remove `portable.ini`. I'll PR removing that later..
Needed for stable, one step closer to purging portable-by-default.
PR builds don't have the updater, but I've tested as best I can locally.
=> Qt: Invoke Updater as Administrator for Program Files installs

cmake/BuildParameters.cmake
#10574 changed things so that `DISABLE_BUILD_DATE` does nothing, but it didn't remove the option declaration at the beginning of the file.
Don't declare variables that do nothing.
=> Build: Remove unused option `DISABLE_BUILD_DATE`

bin/portable.ini
It just changes the default, you can still re-enable portable mode by creating `portable.ini` in the PCSX2 directory. All existing portable installations will remain in portable mode, unless you remove `portable.ini` and move your data over.
For all the time I've been around at least, PCSX2 has defaulted to portable mode for nightly builds. But only for Windows, Mac/Linux are not portable in the first place. I'm not really sure why.
For the stable release, we definitely want to default to non-portable. But in my opinion, we should just make non-portable the default anyway.
- Easier to test different builds, since they all share the same ini/bios/cards/etc.
- Consistency across platforms.
- Users can install to Program Files if they really want to (after #10633 is merged).
- The "expected" …
=> CI: Default to non-portable builds

pcsx2/GameList.cpp
Checks if exclusion paths are not empty string before excluding games from the list. Yep, that's it.
Works around a bug of unknown origin which causes empty string to be added to the exclusions list, which would in turn clear the games list completely.
Close PCSX2 if it is open. Manually add the following to your PCSX2.ini file in the GameList section towards the bottom:
`ExcludedPaths = `
Verify your games list still populates when you open PCSX2.
=> Game List: Ignore exclusion paths if they are empty string

bin/resources/GameIndex.yaml
Fixes the notoriously inaccurate water in Just Cause. Setting blending to 'High' fixes the translucency part, and then PS2 trilinear + PS2 mipmap fixes the texture on top of the water.
This dramatically improves the graphical fidelity of Just Cause, as the water is easily seen from many parts of the map and comprises a large portion of the game world.
Play Just Cause for a bit and see if anything is weird. It shouldn't be, as this simply increases accuracy.
=> GameDB: Fix water in Just Cause

pcsx2/DEV9/ATA/ATA.h, pcsx2/DEV9/ATA/ATA_Info.cpp, pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp, pcsx2/DEV9/ATA/Commands/ATA_CmdNoData.cpp
Fixes MDMA mode
Removes SDMA
MDMA transfer mode was found to be not working using https://github.com/ps2homebrew/PS2HDDTester/releases
SDMA is not supported by the original PS2 HDD, (determined by inspecting [HDD_IDentify.bin.zip](https://github.com/PCSX2/pcsx2/files/13799140/HDD_IDentify.bin.zip) posted in https://github.com/PCSX2/pcsx2/pull/10514
Run the MDMA tests found in https://github.com/ps2homebrew/PS2HDDTester/releases
=> DEV9: Fix MDMA

pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/SIO/Pad/PadBase.h, pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SIO/Pad/PadGuitar.h, pcsx2/SIO/Pad/PadNotConnected.cpp, pcsx2/SIO/Pad/PadNotConnected.h, pcsx2/SIO/Pad/PadPopn.cpp, pcsx2/SIO/Pad/PadPopn.h
Currently, the input OSD shows the raw values of the analog sticks, which can be near-zero, since they don't rest at exactly the center. This is a bit annoying.
Instead, use the effective value, which considers any deadzone set by the user. Also switches over to integer values, since this is arguably more readable than fractional. Also matches padtest.
User request
Test input OSD with pad and keyboard.
=> ImGuiOverlays: Display inputs as integer, ignoring deadzone

common/FileSystem.cpp, pcsx2/GameList.cpp
If PCSX2 hits a symbolic link in recursive directory scanning that points to a directory above it in the path, it ends up following this symbolic link, until it eventually hits the arbitrary path limit. This can cause the system to run out of memory, which is not desirable.
So, let's use the `RealPath()` functions I added a while back to resolve each recursive directory to its "real" location, and only scan each of those once.
Test game list scanning on Windows and Linux.
=> FileSystem: Handle infinite symlink loops in FindFiles()

pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/SIO/Pad/PadBase.h, pcsx2/SIO/Pad/PadDualshock2.cpp, pcsx2/SIO/Pad/PadDualshock2.h, pcsx2/SIO/Pad/PadGuitar.cpp, pcsx2/SIO/Pad/PadGuitar.h, pcsx2/SIO/Pad/PadNotConnected.cpp, pcsx2/SIO/Pad/PadNotConnected.h, pcsx2/SIO/Pad/PadPopn.cpp, pcsx2/SIO/Pad/PadPopn.h
What the title says. I forgot that 0 doesn't show...
Analogs show as -1..1, buttons from 0-255. Still kinda matches padtest.
Regression from #10653.
Check input display.
=> ImGuiOverlays: Fix analog input display

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
Silly Crash and Burn points the texture to the framebuffer, but either has RGB masked, or blend set to As, with the vertices being all-zero. So the draw does nothing, except write Z.
Some of them also have ATEST enabled, and will always fail, so skip those draws.
Guessing they just left registers as zero...
Reduces almost 500 copies per frame to zero.
~~Breaks Guitar Hero and a couple of other dumps, need to fix those.~~
```
crashnburn ['Draw Calls: -395 [2264=>1869]', 'Render Passes: -1119 [1139=>20]', 'Barriers: +365 [0=>365]', 'Copies: -374 [383=>9]']
Crash_N_Burn_SLUS-21013_20240114180751 ['Draw Calls: -495 [2635=>2140]', 'Render Passes: -1404 [1424=>20]', 'Barriers: +456 [0=>456]', 'Copies: -468 [477=>9]']
```
Affects a bunch of others too. Some notable mentions:
``` …
```
=> GS/HW: Further improve no_rt heuristics

pcsx2/SIO/Pad/Pad.cpp
Force multitapped slots to Not Connected if their multitap is missing.
Prevents fully defined pad types (DS2, Guitar, etc) from being instanced when they would not be used. Also prevents these pads from appearing in the OSD despite the multitap they belong to being missing.
Enable one or both mutltitaps. Switch some number of pads that belong to that multitap to anything besides Not Connected. Disable the multitap. Verify non-multitapped controllers continue to function. Verify controllers which belonged to the disabled multitap no longer appear on the OSD.
=> Pad: Force multitapped slots to Not Connected if their multitap is missing

bin/resources/GameIndex.yaml
Adds HPO Native to S.L.A.I. Steel Lancer Arena International
Fixes double image in-game, and properly aligns object glows in menus.
Adds ~1px-2px of garbage on left side. Most visible during loading transitions and while paused. Easily fixed with cropping.
GSDumps: https://litter.catbox.moe/kjf86m.7z
=> GameDB: Add HPO Native to S.L.A.I.

pcsx2-gsrunner/Main.cpp, pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2/GameList.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/FullscreenUI.h, tests/ctest/core/StubHost.cpp
Apparently the create memory card dialog in big picture doesn't work in anything other than English.... so just purge it. It sucked anyway.
Instead, make it open the Qt dialog, that way users can still create cards from Big Picture.
Stable prep.
Test creating memory card from BP, in both windowed and fullscreen. It should temporarily leave fullscreen.
=> FullscreenUI: Link create memory card to Qt dialog

pcsx2-qt/Tools/InputRecording/InputRecordingViewer.cpp
This non-printable character (U+FE0F, VARIATION SELECTOR 16) has been added for seemingly no reason to multiple strings and have polluted Translation Memory on Crowdin for some languages ( :eyes: ). Let's get rid of it.
=> Qt: Remove non-printable character from some strings

pcsx2-qt/Settings/SettingsWindow.cpp, pcsx2-qt/Settings/SettingsWindow.h, pcsx2/ImGui/ImGuiManager.cpp, pcsx2/USB/usb-lightgun/guncon2.cpp
Backport of https://github.com/stenzek/duckstation/commit/89709094003301674cd3ff900aa68f00f8ca6f49.
Some locales have long setting descriptions, which do not fit in the current sized textbox.
Kinda difficult to test if you don't have any long descriptions, but I've hacked one in and it works as expected.
=> Qt: Make Shift+Wheel scroll settings info panel

pcsx2/SPU2/ADSR.cpp
Fixes #10685 
Nocash docs says volume sweep phase does nothing in exponential decrease mode.
=> SPU: VolumeSlide: disregard phase when exp + decr

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Noticed COD was uploading its depth buffer that it just cleared, which was all zeros.
Previous heuristic made sure it was the previous draw that cleared it, to skip the upload. But when you draw other stuff inbetween the clear and the first draw that uses the target (like cod does with its skybox), that doesn't work.
So, make the hw_clear a flag instead, so that later partial writes don't get lost to full-target writes.
Fewer target uploads. Vroom vroom
Smoke test, check some affected games like NFSU, God Hand, God of War.
=> GS/HW: Better avoid target uploads on HW clear

pcsx2/GS/GSState.cpp
Fixes flush reasons on read/write overlap.
It was wrong for moves and downloads
Nothing to test, purely for GS draw dumping.
=> GS: Correct flush reasons

bin/resources/GameIndex.yaml
Adds Zathura, Bionicle, Scarface, Spider-Man 2, BfBB, and Hot Wheels: World Race to the games which have PS2 trilinear+Full mipmap in the GameDB.
Battle for Bikini Bottom: [SpongeBob SquarePants - Battle for Bikini Bottom_SLUS-20680_20240120160308.zip](https://github.com/PCSX2/pcsx2/files/13999373/SpongeBob.SquarePants.-.Battle.for.Bikini.Bottom_SLUS-20680_20240120160308.zip)
Bionicle: [Bionicle_SLUS-20818_20240120143230.zip](https://github.com/PCSX2/pcsx2/files/13999165/Bionicle_SLUS-20818_20240120143230.zip)
Hot Wheels: World Race: [Hot Wheels - World Race_SLUS-20737_20240120023832.zip](https://github.com/PCSX2/pcsx2/files/13999168/Hot.Wheels.-.World.Race_SLUS-20737_20240120023832.zip)
Scarface: [Scarface - The World is Yours_SLUS-21111_20240120144534.zip](https://github.com/PCSX2/pcsx2/ …
=> GameDB: A few trilinear+mipmap games

pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm
Metal was assuming a full StretchRect() always covered all channels.
Depth -> RGB copies don't, which resulted in a DONT_CARE load action, and the alpha channel becoming undefined. At least on Apple Silicon, anyway.
Fixes GT4 fade transition, maybe other things that use overlapping Z and RT.
Before:
After:
Test GT4 on Mac, preferably Apple Silicon. Desktop GPUs might just behave "correctly" anyway.
=> GS/Metal: Don't discard alpha on RGB depth copy

pcsx2-qt/Settings/SettingsWindow.h, pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
We were misdetecting Jak II's framebuffer clear at 3300[C32] and 2600[Z24] as a double-half clear. This caused a 32-bit GS memory clear of both buffers, wiping out the font texture that starts at 2400.
Test starting a new game in Jak II.
=> GS/HW: Fix double-half clears misfiring on CT32+Z24 when clearing depth

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSHwHack.cpp
Fix up Tekken 5 CRC behaviour to not break everything.
It was breaking everything. I added HPO Native as well to align the post effect and replaced the skips which avoided the post/blur with a single draw so the picture doesn't get messed up, however this does misalign shadows in other scenes, but it's a lesser evil.
Make sure not everything is broken in Tekken 5.
Fixes #10131
=> GS/HW: Fix up Tekken 5 CRC hack to not remove post + break other scenes

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Stops targets copying from overlapping targets after a hw clear.
ICO was preloading its target from an old target after a mem clear, ending up with bad data. We should probably invalidation partial matched targets on clears too, but this seems to cause a bunch of extra uploads, and doesn't fix anything, so not bothering for now.
Check ICO (Dump already checked)
ICO:
Master:
PR:
=> GS/HW: Don't preload target from overlapping targets after hw clear

pcsx2-qt/Settings/MemoryCardCreateDialog.cpp, pcsx2-qt/Settings/MemoryCardCreateDialog.ui, pcsx2/Config.h, pcsx2/Pcsx2Config.cpp, pcsx2/SIO/Memcard/MemoryCardFile.cpp, pcsx2/SIO/Memcard/MemoryCardFile.h
Inherited from wx....
If you unchecked the NTFS compression checkbox, it wouldn't explicitly set it to false, so if the memcards directory was compressed, the file would automatically be compressed too.
Test memcard creation and selection (boot and make sure saves still load).
=> MemoryCardFile: Fix NTFS compression always applying

pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp, pcsx2-qt/Settings/MemoryCardSettingsWidget.h, pcsx2-qt/Settings/MemoryCardSettingsWidget.ui
This PR removes some unneeded and unused options on the memory card settings page.
Removed option:
- Duplicate (It is not implemented and no plan to do so, it is trivial to do by the user anyway)
- ~~NTFS Compression (It's already enforced by default and there's no reason to disable it.)~~
Master:
PR:
Squeaky Clean ✨
Make sure i didn't break anything on Windows.
=> Qt: Clean up memory card settings section.

pcsx2-qt/SetupWizardDialog.ui
Missing the flag to enable links to be clicked
Forgot it
CI passes
=> Qt: Fix unclickable links in Setup Wizard

.gitignore, pcsx2-qt/CMakeLists.txt, pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/DebuggerSettingsManager.cpp, pcsx2-qt/Debugger/DebuggerSettingsManager.h, pcsx2-qt/Debugger/Models/BreakpointModel.cpp, pcsx2-qt/Debugger/Models/BreakpointModel.h, pcsx2-qt/Debugger/Models/SavedAddressesModel.cpp, pcsx2-qt/Debugger/Models/SavedAddressesModel.h, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters, pcsx2/Config.h, pcsx2/Pcsx2Config.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h
Adds `/inis/debuggersettings/` settings folder to contain settings specifically for the debugger. Adds functionality to manually save (to debugger settings) Breakpoints/Saved addresses and automatically load them upon launching the debugger.
Creates a settings file for each game in `/inis/debuggersettings` when user saves a Breakpoint or Saved Address via the context menu. (Note: Autosaving was not implemented due to many potential edge cases risking info loss.) Saves these debugger settings in JSON format and parses them on debugger load so that they can be loaded for the user.
Allows persisting breakpoints and saved addresses between PCSX2 runs so one does not have to export and re-import them.
Also gives flexibility to add more configuration in the future, including non-game specific …
=> Debugger: Adds loading breakpoints/saved addresses from settings [DebuggerSettings]

pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp, pcsx2-qt/Settings/MemoryCardSettingsWidget.ui, pcsx2/ImGui/FullscreenUI.cpp
Change mentions of "port" when referring to Memory Cards to "slot". Also renamed one GUI element to match this change.
"Slot" is the official term, we should use it instead of "port".
Check Memory Card settings in Qt and ImGui.
=> GUI: Memory Card "slot" instead of "port"

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h
Adds the ability to copy the address directly of a memory search result through the right click context menu.
Makes it quick & easy instead of having to go to the memory address in memory view and then copy.
- Perform any memory search with results and verify the copied address matches the selection and is in hexadecimal.
=> Debugger: Allow copying address of memory search results

pcsx2/PINE.cpp
Ensure thread safety when loading/saving state
Save states would get easily corrupted using PINE because we didn't ensure thread safety, fix that.
unbreak PINE
Use https://projects.govanify.com/govanify/pine and try to save/loadstate and make sure pcsx2 doesn't crash
=> PINE: fix save state regression introduced during the switch to Qt

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Spiderman: Web of Shadows clears its depth buffer with 32-bit FRAME and 24-bit Z. So the upper 8 bits of half the depth buffer are not cleared, yay. We can't turn this into a 32-bit clear, because then it'll zero out those bits, which other games need (e.g. Jak 2). We can't do a 24-bit clear, because something might rely on half those bits actually getting zeroed. So, instead, we toss the depth buffer, and let the mem clear path write out FRAME and Z separately, with their associated masks. Limit it to black to avoid false positives.
Also fixes FBW getting blown out to 20 for a horizontal double-half clear in Wakeboarding Unleashed.
Test spodermen and wakeboarding unleashed.
=> GS/HW: Handle more double-half clear edge cases

cmake/Pcsx2Utils.cmake, common/CocoaTools.h, common/CocoaTools.mm, pcsx2-qt/CMakeLists.txt, pcsx2-qt/MainWindow.cpp, pcsx2-qt/QtUtils.cpp, pcsx2-qt/QtUtils.h
Replaces "Open Containing Directory" button with "Show in Folder/Finder" button, which actually selects the file in the file explorer it opens.
For the name, "Show in Finder" is very standard on macOS, and for Windows I took "Show in Folder" from the option for the equivalent action in web browsers' download managers, but I've seen other applications use "Show in Explorer" (e.g. JetBrains IDEs), or even "Show in Windows Explorer", and am open to changing it.
Note: I don't know how to do this on Linux, so Linux remains "Open Containing Directory".  If anyone knows, they're welcome to add the appropriate code to `QtUtils::ShowInFileExplorer`.
More useful
Right click on a game and select the new option
(I don't remember if I tested it on Windows, so it definitely needs testing there)
=> Qt: Make "Open Containing Directory" action select the file

pcsx2-qt/Settings/DEV9SettingsWidget.cpp, pcsx2-qt/Settings/DEV9SettingsWidget.h, pcsx2-qt/Settings/DEV9SettingsWidget.ui, pcsx2/DEV9/ATA/ATA.h, pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/DEV9/ATA/Commands/ATA_CmdDMA.cpp, pcsx2/DEV9/ATA/Commands/ATA_Command.cpp
Adds LBA48 support for HDD larger than 128GB
A checkbox is added to allow choosing larger sizes (upto 2tb)
Larger sizes are supported, but need to be created manually
Managed to get this working, thanks to the fixes added in https://github.com/PCSX2/pcsx2/pull/10514
Support HDD sizes >128GB with supporting homebrew software.
Test HDD images larger than 128GB with homebrew apps that support LBA48
Note that the UI checkbox doesn't actually toggle LBA48 support, that is instead enabled based on the HDD file size
=> DEV9: LBA48 Support

pcsx2/DEV9/ATA/ATA_Info.cpp
A few changes that bring our Identify report closer to what original PS2 Hardware reports (as per the dump in https://github.com/PCSX2/pcsx2/pull/10514)
Also remove casts, I had thought these where needed to avoid a narrowing conversion warning, but looking at the build logs we don't get those warnings.
Better match PS2 hardware
Test PS2 HDD games and apps
=> DEV9: ATA Identify Fixes

pcsx2-qt/CMakeLists.txt, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.h, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.ui, pcsx2-qt/Settings/ControllerMappingSettingsDialog.ui, pcsx2-qt/Settings/ControllerSettingsWindow.cpp, pcsx2-qt/Settings/ControllerSettingsWindow.h, pcsx2-qt/Settings/ControllerSettingsWindow.ui, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters, pcsx2/Input/DInputSource.cpp, pcsx2/Input/DInputSource.h, pcsx2/Input/InputSource.cpp, pcsx2/Input/InputSource.h, pcsx2/Input/SDLInputSource.cpp, pcsx2/Input/SDLInputSource.h
Instead of being specific to DInput.
See #10585.
Test mapping with the setting enabled.
=> Qt: Make "Ignore Inversion" a global mapping setting

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Kills the source that was found if it's connected to a target, but the read is outside of that target, if we are using merged targets, of course.
Also adds Texture in RT (Merge Targets) to Shadow Hearts
Because the game in question (Shadow Hearts) uses double buffering, then reads those double buffers both at 0x00000 but using an offset, the original source doesn't get invalidated, since the target hasn't been invalidated.  This PR will invalidate it so targets can be merged together in to a single source if this happens.
Test Shadow Hearts, make sure transitions for fights no longer flicker, opening the menu doesn't cover the screen in garbage, and special effects for Fusion moves work correctly.
Fixes #6742
Fusion Effect:
Master:
PR:
Battle Transition:
Master:
PR:
Menu:
Master:
PR:
=> GS/HW: Kill old source using target if rect is outside target surface

pcsx2-gsrunner/Main.cpp, pcsx2-qt/QtHost.cpp, pcsx2/Counters.cpp, pcsx2/VMManager.cpp, pcsx2/VMManager.h, tests/ctest/core/StubHost.cpp
Currently, we do emulated vblank start -> poll pads -> throttle -> push frame. This means that pads get polled potentially up to 16ms before the game receives them.
This PR moves the polling to after throttling, and the GS frame push (because that could stall), reducing the amount of delay between polling, and the guest polling the controller (in the vsync handler).
What we _really_ need to do, is move the frame push to before the throttle as well. But that'll introduce pacing issues with VRR setups. So, we need timed present. But the extension for that is held back by **gosh darn wayland**, amongst other issues. This is why we can't have nice things. DirectX has had it since Vista..............
Reducing input lag.
Check input lag.
=> Counters: Move input poll to after throttle

pcsx2/USB/USB.cpp, pcsx2/USB/shared/ringbuffer.cpp, pcsx2/USB/shared/ringbuffer.h, pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp, pcsx2/USB/usb-mic/audiodev-cubeb.cpp, pcsx2/USB/usb-mic/audiodev-cubeb.h, pcsx2/USB/usb-mic/audiodev-noop.h, pcsx2/USB/usb-mic/audiodev.h, pcsx2/USB/usb-mic/usb-headset.cpp, pcsx2/USB/usb-mic/usb-mic-singstar.cpp
Rewrite the RingBuffer class, because like the rest of the USB code, it was awful, and corrupted heap memory if PCSX2 lagged.
Fixes incorrect config key, preventing audio input/output with USB Headset emulation.
Fixes device configuration getting reset when saving state, preventing USB Headset from working after loading state.
Closes #8316.
Closes #7606.
Test Singstar, make sure it didn't break (it seemed fine).
Test USB-Headset games. I checked Sly 2.
=> USB: Audio fixes

bin/resources/GameIndex.yaml
GameDB: Add mipmap full with ps2 trilinear to SWAT Global Strike Team.
Improves building textures to match sw renderer.
Accuracy.
CI passes.
=> GameDB: Add mipmap full with ps2 trilinear to SWAT Global Strike Team.

pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
Utter garbage no-regard-for-buffer-sizes USB code strikes again.
Thanks to Prafull for testing, since I couldn't get the virtual camera to work.
Closes #4241.
Test EyeToy. Needs to be checked again, since I tidied up the code a little, and added the fix to ov511p as well.
=> USB: Fix buffer copies in EyeToy

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.ui, pcsx2/ImGui/FullscreenUI.cpp
We've discouraged setting the WS/NI patch options per-game for some time now. So, formally deprecate them, and give the user the opportunity to remove them from the configuration when they next open Game Properties.
Not having two places to enable the same thing in Game Properties.
Use an old version, or manually enable WS/NI patches in game properties.
Open game properties on PR build, make sure it gives you the option to remove them.
Inspect ini file, make sure the keys are removed.
Make sure opening game properties again does not display prompt.
=> Qt: Deprecate per-game WS/NI toggles in favor of Patches

pcsx2/GS/GS.cpp, pcsx2/GS/GSCapture.cpp, pcsx2/ImGui/ImGuiOverlays.cpp, pcsx2/VMManager.cpp
Further improvement to #10619 as suggested in https://github.com/PCSX2/pcsx2/pull/10619#issuecomment-1908659085.
Also fixes recording persisting through VM shutdown.
QoL improvement.
Test capture overlay.
Make sure recording stops when VM is shutdown in Big Picture, and without.
=> GS/Capture: Show video timestamp instead of wall time

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
Backport of https://github.com/stenzek/duckstation/commit/bcf7f55b93d6c61a66c1aabec5b8568d10a5b26c
Waiting on a fence that hasn't been submitted yet = spec violation.
Smoke test Vulkan renderer, preferably something with readbacks.
=> GS/Vulkan: Fix potential race between submit and main thread

pcsx2-qt/Debugger/RegisterWidget.cpp, pcsx2-qt/Debugger/RegisterWidget.h
Double clicking a register segment will open the segment edit dialogue that normally has to be accessed by the right click menu.
Ease of use/efficiency. Makes editing register values little more intuitive.
Just verifying the correct value appears when double clicking and pressing okay edits the value expected, as well as no weird behaviors when CPU is off or double clicking on other areas, etc.
=> Debugger: Adds editing register values via double click

bin/resources/GameIndex.yaml, bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/Metal/tfx.metal, pcsx2/ShaderCacheVersion.h
Allows palettes to be used in P8H lookups on depth textures.
Deswizzles draws which are manually deswizzling depth to be used on a colour target.
Also added mipmapping to Arc the Lad to help with the depth of field effect.
We don't swizzle the depth like the GS does, this would be slow if we did, but gamedevs who tried to be clever and deswizzle it themselves kinda screwed us there, so this replaces the draw with a single sprite.
If the Z is different on each sprite there is no handling for this, but it will throw a log message.
Test Crash N Burn, Arc the Lad - End of Darkness/Generation and Vampire Panic.  Maybe just random spattering of games. Mercenaries 1 & 2 also showed very small differences but nothing scary, maybe check them.
Fixes #7528 Arc the Lad - Twilight of the Spirits
Fixes …
=> GS/HW: Allow palette lookups from depth and deswizzle manual deswizzles

pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/DEV9/DEV9.cpp
Correctly reports no device connected when HDD is not enabled
The PS2 always reports HDD functionality if you have an expansion bay addon. The device status/control register however reports all bits set (except the reset bit) if the game/program tries to poll it, which will result in it being reported as missing.
Test Final Fantasy X International with Ethernet enabled but HDD disabled
Fixes #10754
=> DEV9: Fix HDD Response when no HDD is connected

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Acquire isn't valid for stores...
Typo.
CI passes. No effect on x86.
=> GS/Vulkan: Fix incorrect memory order arg

.github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/linux/flatpak/modules/20-sdl2.json, .github/workflows/scripts/macos/build-dependencies.sh, .github/workflows/scripts/windows/build-dependencies.bat, cmake/SearchForStuff.cmake, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.ui, pcsx2-qt/Settings/ControllerSettingsWindow.ui, pcsx2/Input/SDLInputSource.cpp, pcsx2/Input/SDLInputSource.h
Also exposes the new MFI/IOKit backend hints introduced in 2.30. Should let users prevent duplicate devices from showing up, without the downside to breaking MFI-only devices.
Bumpity bump.
Test controllers on all platforms.
=> deps: Bump to SDL2 2.30.0

pcsx2/GS/GS.cpp, pcsx2/VMManager.cpp
Regression from #10741.
Messing with CPU thread state on the GS thread is a bad idea (TM), even if the main thread is blocking waiting for the GS thread to close.
Also, it wouldn't work if you were using Big Picture mode.
Test shutting down with input recording active in both "normal" and BP mode.
=> GS: Move input recording shutdown to VMManager

common/FileSystem.cpp
Per TellowKrinkle "Looks like we accidentally truncate our characters to 8 bits before doing the detection
So any unicode character whose lower 8 bits are not allowed in paths will get replaced "
Fixes #10783 
Broken names bad.
=> FS: Fix cover text truncation

pcsx2-qt/MainWindow.cpp
This PR makes the Memory Card Busy dialog box defaults its button to No instead of Yes.
Also makes the box critical instead of just a question.
NOTE:
This is possibly a Qt bug, according to documentations `QMessageBox::critical` should defaults to No already, but apparently it wasn't the case?
Preview:
We don't want users to accidentally destroy their card when they pressed enter blindly.
Check the functionality.
=> Qt: Default to No for exit Memcard abort msgbox

pcsx2-qt/Debugger/MemoryViewWidget.cpp
Checks the status of a QString conversion of the keypress being entered into the hex nibble of the memory viewer widget before they're entered to ensure they're valid.
Before, pressing a key other than 0–9 or a–f in the hex viewer would result in a failed QString conversion resulting in a 0. This fixes #10745 by @Berylskid. Credit to @Daniel-McCarthy for pointing out that the function call was failing because the QString conversion was failing and for noting that the status of this conversion was stored in pressHandled, which I hadn't realized.
Go to the debugger while in a game, go to the hex viewer at the bottom, and try entering usual values into the hex viewer. Then try to add an unusual one (not 0–9 a–f) and see what happens.
=> Debugger: Check for successful QString conversion in MemoryViewerWidget.cpp before writing

bin/resources/GameIndex.yaml, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Avoids speedhacking tex is fb when the draw isn't directly recursive
Speedhacks are a great idea, until they aren't.
Test X2: Wolverine / X-Men 2 - Wolverine's Revenge for light penetration
Master:
PR:
=> GS/HW: Only allow tex is fb on alpha if draw is recursive

pcsx2/SIO/Memcard/MemoryCardFolder.cpp
Fix incorrect order of directory entry and file name when looking for _pcsx2_meta_directory files. The target filename "_pcsx2_meta_directory" was being placed before the directory that was supposed to be checked for said file, resulting in no match found, hence the corrected directory entry stored inside was not copied into the folder memcard.
Fixes #6708, possibly other games which dislike folder memcards.
Fixes games which depend on meta files to correct weird filename problems or file attribute problems.
Boot games which have problems with folder memcards. Start your folder memcard with no data. Create a save file, then fully close PCSX2. Boot the game again, and the game should still be able to see your save data.
=> Memcard: Fix incorrect order of directory/filename path components for _pcsx2_meta_directory files

bin/resources/GameIndex.yaml
* Fixed typo/wrong name/name-sort/name-en.
* Replaced full-width tilde (U+FF5E) with wave dash (U+301C).
* Removed VW067-J1 since it is a mere number for catalog purpose but not game ID.
* According to SCE's internal title database (mentioned in PS3 compatibility list):
* Preffixed some suffixed "low-cost edition" suffix.
* Replaced "PS2 the Best" with "PlayStation 2 the Best".
More accurate name/name-sort/name-en.
=> GameDB: NTSC-J Overhaul

pcsx2/Achievements.cpp
Fixes off by one error in memory lookups in Retro Achievements
if the read was on the end of scratchpad memory, say 0x20003fff and was 1 byte big or 0x20003ffc and was 4 bytes, it would fail the end of memory check which points to 0x20004000
Not sure anything uses this, make sure retro achievements still work, i guess.
=> RAchievements: Fix off by one error in scratchpad reads

pcsx2/GS/Renderers/Common/GSRenderer.cpp
Fixes crop scaling when in software mode, but also if your internal resolution was lower than the window size and you used Bilinear (Sharp) filtering
Software mode: It was using HW upscale values, regardless of the current renderer, it now forces x1 for calculating software mode src size.
Bilinear (Sharp): When this option is active, the "current" framebuffer size gets increased to be larger than the window. Unfortunately the crop amount is done on *this* framebuffer, so it was resulting in bad amounts of cropping. It now adjusts the crop amount based on the real framebuffer size vs the "current" framebuffer size.
Test crop values in software and hardware at different resolutions, including Bilinear (Sharp) mode, try different window sizes, make sure the cropping doesn't completely take a …
=> GS: Fix crop scaling for software and bilinear (sharp)

pcsx2-gsrunner/Main.cpp, pcsx2-qt/Settings/InterfaceSettingsWidget.cpp, pcsx2-qt/Settings/InterfaceSettingsWidget.ui, pcsx2/Config.h, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Pcsx2Config.cpp, pcsx2/VMManager.cpp
Removes the toggle option to disable per-game settings
Nobody actually used this, and users were just disabling this then wondering why their settings didn't work, along with confusing people trying to support them. So negatives hugely outweigh the positives of having the option there.
Make sure per-game settings still work
=> UI: Remove option to disable per-game settings

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
llvmpipe apparently supports raster order attachment access now, and if you force-disable fbfetch, it wasn't creating the render passes with the self-dependency declared.
Spec violations.
Smoke test barriers.
=> GS/Vulkan: Use fbfetch flag for subpass dependency

.github/ISSUE_TEMPLATE/app_bug_report.yaml, .github/ISSUE_TEMPLATE/emu_bug_report.yaml
Removes 10.14 and 10.15, and adds 14
10.14 and 10.15 are no longer supported
14 now exists
None
=> GitHub: Update macOS versions on issue templates

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
Changes the tooltip for the SW renderer thread count setting
Old tooltip is old
Make sure the text appears properly
=> UI: Update SW Renderer Threads Tooltip

3rdparty/libchdr/CMakeLists.txt, 3rdparty/libchdr/include/dr_libs/dr_flac.h, 3rdparty/libchdr/include/libchdr/cdrom.h, 3rdparty/libchdr/include/libchdr/chd.h, 3rdparty/libchdr/libchdr.vcxproj, 3rdparty/libchdr/src/libchdr_cdrom.c, 3rdparty/libchdr/src/libchdr_chd.c, 3rdparty/libchdr/src/libchdr_huffman.c
Backport of https://github.com/stenzek/duckstation/commit/0e6a9f637bc1975a75edcfd0ccf32f59bbafd733
Closes #10823.
Test zstd chds. You can use `chdman create{cd,dvd} -i ... -o ... -c cdzs` to do so.
I've tested it myself, but only in a Linux aarch64 VM, so no idea if Windows or x86 works. But I don't see why it shouldn't.
=> 3rdparty/libchdr: Rebase to upstream 2a1119c

pcsx2/GS/GS.cpp, pcsx2/ImGui/ImGuiManager.cpp, pcsx2/ImGui/ImGuiManager.h
Fixes OSD spinbox closing on click, and popups closing on window resize.
UpdateScale() was pushing a dummy frame, which would make the popup window inactive -> nav gets reset -> popup gets closed.
Make sure big picture mode isn't broken.
Try resizing window with an option popup open.
Try changing the OSD scale via BP mode.
=> ImGuiManager: Defer scale updates

bin/resources/GameIndex.yaml
Makes whole image visible.
Top part of the image was cut off.
None.
Before:
After:
=> GameDB: Fix Overscan on Crash Twinsanity (PAL)

bin/resources/GameIndex.yaml
Fixes shadow rendering in Jak The Lost Frontiers.
Fixes #10828 
Current HW:
Current SW:
PR HW:
Shadow work more good.
=> GameDB: Jak TLF Fixes

pcsx2/ps2/BiosTools.cpp
Change the development tool bios detection to be accurate and also detect namco system 246 & system 256 bios files
I think that detecting a namco rom is important, because due to lots of nonstandard changes (eg: making `rom0:MCMAN` use the same RPC layout than retail `rom0:XMCMAN`) it wont work with any software that uses these files at any given moment. So spotting it right away is useful 
get a devkit bios and a COH-H bios and try if they get detected appropiately
=> Correctly identify development tool and Namco system 246/256 bios

pcsx2-qt/CMakeLists.txt, pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/CpuWidget.ui, pcsx2-qt/Debugger/MemorySearchWidget.cpp, pcsx2-qt/Debugger/MemorySearchWidget.h, pcsx2-qt/Debugger/MemorySearchWidget.ui, pcsx2-qt/pcsx2-qt.vcxproj, pcsx2-qt/pcsx2-qt.vcxproj.filters
Moves Memory Search UI into it's own custom widget and migrates the search related functions from `CpuWidget.h/cpp/ui` to their own `MemorySearchWidget`.
The scope of Memory search related functionality is increasing and the `CpuWidget` is already fairly bloated being a general parent of a lot of different and unrelated functionality. This helps make `CpuWidget` easier to read/understand/maintain and allows the new `MemorySearchWidget` to expand in functionality and improve focus.
This impacts all search related functionality, and integration between other components, such as double clicking an address and seeing it in Memory View, or visiting a search result in disassembly view, or taking a search result into saved addresses model.
<details><summary><sup>
Note:<br>
Also makes the …
=> Debugger: Migrates Memory Search tab to it's own widget

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Preload whole target when upload matches, instead of just recent dirty area.
This was a fix for Medal of Honor European Assault which basically creates a new target at 0x3100 at 64x64, but it was getting confused with an existing target, so after the changes of 1.7.5328, the target was getting killed, and it was preloading from memory (as it should) but only half of it, instead of the whole thing from the mem clear, because we don't add a transfer when it attempts to continue with the clear.
Test Medal of Honor European Assault (Though this will be nullified by master anyway) to check for black spots.  Also check MLB 09 - The Show and Sven-Goran Erikssons World Manager 2002. Maybe smoke test some other games.
Medal of Honor European Assault (nullified by another solution on master): …
=> GS/HW: Preload whole target on match

pcsx2-qt/Debugger/DisassemblyWidget.cpp
The debugger was crashing on open if no game was running due to failing to read from the CPU while the cpu was not alive.
The opcode was read before checking if it should be shown, so I have moved it to only read if the showOpcode boolean is true, and set it to not show opcodes if the cpu is not alive.
Less crash more good.
Open the debugger without opening a game, should open fine now.
=> Debugger: Fixes crash on debugger open when cpu not alive

3rdparty/xbyak/xbyak/xbyak.h, 3rdparty/xbyak/xbyak/xbyak_mnemonic.h, 3rdparty/xbyak/xbyak/xbyak_util.h
Updates xbyak to 7.05.1 to fix a crash on SSE4a CPUs not failing gracefully.
Crashing is bad.
Make sure the things all work and the CI is a happy boy.
=> 3rdparty: Update xbyak to 7.05.1

.github/workflows/linux_build_flatpak.yml
Regression from #10838. Tags aren't fetched for PR builds, so this wasn't caught.
=> CI/Flatpak: Fix dubious ownership error

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Calculates the alpha values of the dirty areas being updated from GS memory, for keeping the RT information up to date.
We didn't do this before, and just assumed full range alpha on invalidation, but this isn't true and removes some optimisation situations. This will help potentially with #10853 
Smoke test, mostly. GS Dump run was fine, some very minor changes, probably due to doing things in shader rather than hardware.
Driv3r (look at the gradient on the left wall):
Master:
PR:
Evergrace 2:
Barriers: -133 [272=>139] (but this is only for one frame)
Forever Kingdom:
Barriers: -309 [320=>11]
Keroro Gunsou:
Draw Calls: -2 [178=>176]
Render Passes: -7 [83=>76]
Barriers: -10 [96=>86]
=> GS/HW: Calculate alpha on updated areas on RT invalidation

pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2/DebugTools/MIPSAnalyst.cpp, pcsx2/DebugTools/MIPSAnalyst.h, pcsx2/DebugTools/SymbolMap.cpp, pcsx2/DebugTools/SymbolMap.h
Fixes #2836
Also adds "NR" to the disassembly dialog when a function is suspected to noreturn.
I'm thinking in the future it would be nice to detect a function epilogue after noreturn functions. If there is no epilogue, it still is technically part of the function despite it being 'technically' impossible to reach. 
When searching through functions, there were no heuristics for noreturn function. This would cause the function to sometimes merge into the next.
Look at some non-returning functions and see if they are separated from the next function.
---
Here is an example of these changes
Before, this would be one long function.
=> DebugTools: Add noreturn heuristic

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h
Implements #10840
The debugger now refreshes/updates it's widgets once a second so that the user does not need to interact with the debugger to know when data/state changes.
Note: I am also considering eventually allowing the user to configure this interval, however have not implemented it here. It is fixed to a one second interval agreed upon in #10840.
Allows the user to watch data/state changes without intervention/interaction.
Validating everything that should be updating gets updated while the cpu is alive.
=> Debugger: Add automatic refreshing on 1 second interval

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
While investigating a Persona 3 dump, I noticed that we were fully clearing the buffer when initializing the stencil for first-write-wins (ONE). This was about 20us of GPU time at 8x upscaling on my GPU, as seen below:
Instead, since we only care about a tiny region of the framebuffer, we can use an attachment clear (which I'm guessing will get lowered to a draw that sets stencil in the driver), and only write the region that we actually need to load. This reduces the cost of the draw by approximately 85%.
Overall, this increases performance by approximately 66% in the Persona 3 dump at 16x upscaling.
Lots of render pass reductions. The main ones:
```
AFL Premiership 2007_SCES-54639 ['Render Passes: -809 [829=>20]']
Dragon_Ball_Z_Budokai_Tenkaichi_3_SLES-54945-splitscreen ['Render Passes: …
```
=> GS/Vulkan: Use attachment clear for ONE stencil

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/CpuWidget.ui, pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/MemorySearchWidget.cpp, pcsx2-qt/Debugger/MemorySearchWidget.h, pcsx2-qt/Debugger/MemorySearchWidget.ui
- For Int/Float types, adds the following search comparisons: `Increased, Increased By, Decreased, Decreased By, Changed, Changed By, Not Changed`.
- For String/Array types, adds the following search comparisons (when **_filtering_**): `Not Equals, Changed, Not Changed` 
- Shows `Searching...` when a memory search is in progress, and `<number> results found` on search completion.
- Now only displays the comparison types that are valid for the given selected search state. If a comparison type is not supported for a type it will not appear, and if a comparison type requires search results to filter, it will not appear until a search has been performed.
- Switching search types disables filter search until a new search is performed. (Can't search for ints, then filter by float or string. If …
=> Debugger: Memory search increased/decreased/changed + results count

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Improve RT alpha calculation
Allows the RT alpha to be more accurate to what it actually contains. Will help with future improvements like #10853
Smoke test mostly, nothing of note changed.
=> GS/HW: Improvements to rt alpha accuracy

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Sets alpha required correctly for 8H, 4HH, 4HL formats.
before it was checking if the source format used the alpha, which isn't important in formats which originate from the targets alpha channel.
Already tested, no visible changes (but there is on the RTA PR)
=> GS/HW: Require alpha for 8H, 4HH, 4HL on source lookup

pcsx2-qt/SetupWizardDialog.ui
Fixed broken setup guide links in the setup wizard.
broken links bad boooo
Open setup wizard and test links.
=> UI: Fix broken setup guide links

common/Linux/LnxMisc.cpp, pcsx2/VMManager.cpp
- Implements power profile logging on Windows
- Implements logging GPUs on Windows and Linux*
- Implements distro logging on Linux (Instead of just 'Linux')
*There are some limitations on driver version logging on Linux. It should always work for the dGPU (which is really what matters most).
Improves the ability to provide support when you can see if the user has set a poor power profile, or if their drivers are outdated.
Run PCSX2 and look at the console.
Linux example
Windows example (Sorry, two screenshots, and the driver version is now aligned like Linux)
=> VMManager: Log power profile and GPUs on startup

pcsx2/VMManager.cpp
=> vmmanager:revert gpu logging

pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/ControllerLEDSettingsDialog.ui, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Input/SDLInputSource.cpp, pcsx2/Input/SDLInputSource.h, pcsx2/SIO/Pad/Pad.cpp
This change adds a toggle to enable/disable the Player LED on DualSense controllers.
Not to be confused with the primary LED. The Player LED is a non-customizable bright white array of white LEDs that indicate the player number. Image of before and after.
The UI change is added to the LEDSettingsDialog
* RAW mode does not have Player LEDs on.
* Turning on Enhanced Mode turns on the Player LED in addition to the primary LED.
* There is no option to disable the Player LEDs currently. You can only customize the primary LED.
* A user may want to completely disable all LEDs on their controller. Currently you can disable the Primary LED but not the Player LED. This is distracting/bright when playing in low lighting conditions.
* You can already tell which player is which due to the customized …
=> Qt/PAD: Enable/Disable Player LED for DualSense Controllers in Enhanced mode

pcsx2/GS/Renderers/Vulkan/VKSwapChain.cpp
We don't actually need +1 semaphores, or, more than one really. But, the validation layer gets cranky if we don't fence wait before the next image acquire. So, add an additional semaphore to ensure that we're never acquiring before fence waiting.
Stop validation layer complaining about something that's not actually an issue.
Smoke test Vulkan renderer.
=> VulkanDevice: Add additional semaphore on swap chain

pcsx2-qt/LogWindow.cpp, pcsx2-qt/LogWindow.h
What the title says. Originally I wanted it to stay active if PCSX2 was closing, and disable itself if the user pressed the X button. However, it is not possible to differentiate between the window being closed as a result of the task ending, or an actual user action. 
So, disable the button instead, if the user wants to disable the log window, they can do so via the Tools menu.
I also made the height adjustable/saveable, and independent to the main window at the same time.
Fixing log window disabling itself.
Make sure log window doesn't disable itself.
=> Qt: Fix log window disabling itself on close

.github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/linux/flatpak/modules/20-sdl2.json, .github/workflows/scripts/macos/build-dependencies.sh, .github/workflows/scripts/windows/build-dependencies.bat, cmake/SearchForStuff.cmake
See title.
Qt 6.7 has been delayed it seems.
Check all platforms.
=> CI: Update to SDL2 2.30.1 and Qt 6.6.2

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h
Flatout 2 (redundantly) clears a buffer through both FRAME and Z, which was causing the TC to get confused when I added overlapping buffer support.
Interestingly, they do so with two 32-wide sprites; if they had omitted the second half of it, we'd have a powerdrome-style clear where the right half gets written through Z, and it would be faster. But what they did is no faster.
Amusingly, there's a few other games that do this as well (DMC3, Ratchet, Tom & Jerry), except they do it on 640x448-style buffers :rofl:.
Fixes #10865.
Before:
After:
Test Flatout.
=> GS/HW: Handle redundant FRAME+Z buffer clears

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Using vkCmdClearAttachments() within a render pass on NVIDIA seems to cause dependency issues between draws that are testing depth which precede it. The result is flickering where Z tests should be failing.
Breaking/restarting the render pass isn't enough to work around the bug, it needs an explicit pipeline barrier. As far as I can tell, this is a driver bug, because attachment clears should occur in rasterization order, quoting the spec:
>  Unlike other clear commands, vkCmdClearAttachments is not a transfer command. It performs its operations in rasterization order. For color attachments, the operations are executed as color attachment writes, by the VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT stage. For depth/stencil attachments, the operations are executed as depth writes and …
=> GS/Vulkan: Work around NVIDIA attachment clear bug

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Since we're hashing at the block level, a different TBW that causes a different-looking texture should cause different blocks to get hashed, and thus, a different hash.
Fixes async texture replacement loading.
Check async texture loading.
=> GS/HW: Don't include TBW in hash cache key

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Don't try to convert outside of targets to indexed, since there is no data to convert.
Seems silly just thinking about it, doesn't it.
Test Ace combat 04, make sure terrain doesn't disappear.
Fixes #10789 
Ace Combat 04:
Master:
PR:
=> GS/HW: Don't allow conversion to indexed is read is outside the target

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
GS/HW: Calculate blend/rt alpha min/max based on alpha test.
GS/HW: Adjust blend_alpha_min/max based on DATE.
Accuracy, will improve hw blending with Ad operations, requires less sw blend (less barriers, copies, draw calls).
Will also help https://github.com/PCSX2/pcsx2/pull/10853 requiring less copies.
Persona 3 shows a slight difference matching it more to sw renderer, I expect dx11/12 to show more differences, other than that shows slight barrier reductions in other games.
=> GS/HW: Improve RT/Blend min max detection based on DATE and ATE.

pcsx2-qt/Debugger/MemorySearchWidget.cpp, pcsx2-qt/Debugger/MemorySearchWidget.h
Reduces memory useage during memory searching process.
- Minimizes passing by copy, uses references to avoid causing copies
- Deletes FutureWatcher ptr when no longer needed to avoid leaking memory (thanks Fobes)
- Updates the search results vector in-place so that no extra copies are needed.
- Makes use of std::move to transfer resources instead of keeping two copies.
- No longer keeps a copy of prior search results on main thread in addition to the active search. The stored results are transferred to the search worker and then transferred back.
- Updates the storage of prior results to use a vector instead of QMap, making indexing for results loading much quicker and less intensive.
More improvements to be made, but making a first that should make a decent impact.
Also fixes an issue …
=> Debugger: Reduces RAM useage for searches (Act 1)

bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Metal/tfx.metal, pcsx2/ShaderCacheVersion.h
Since we can't do `Cd*(Alpha + 1) - Cs*Alpha` in hw blend what we can do is adjust the Cs value that will be subtracted, this way we can get a better result in hw blend. Result is still wrong but less wrong than before.
Accuracy.
This is mostly for dx11/12. Vulkan, GL will only hit this path if barriers are disabled.
Makes dx hw blend suck less.
Test DX blending, list of games in the text file.
Result will still be wrong but less wrong.
[List.txt](https://github.com/PCSX2/pcsx2/files/14547608/List.txt)
=> GS/HW: Adjust blend mix for impossible blend.

pcsx2-qt/Settings/GraphicsSettingsWidget.cpp
Qt: Disable Texture barriers option on Metal.
Not implemented.
Override texture barriers option should only be available on vk/gl.
=> Qt: Disable Texture barriers option on Metal.

pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Improve detection of texture shuffle width/height and tidy up some of the variable naming
There were some cases of misdetection thanks to magic numbers, but also the variable naming made following the code confusing, so I corrected it.
Check Superman - Shadow of Apokolips. Also check The Getaway, Dog's Life (smell-o-vision) and Smugglers Run shadows are all okay/no change.
Fixes #10908
Superman:
Master:
PR:
=> GS/HW: Improve shuffle width/height detection

pcsx2-qt/MainWindow.cpp, pcsx2/Achievements.cpp
Added the "pts" unit in some RA-related strings. "Your score" strings and the like were not changed since I believe they are about the in-game score and not the RA score. Feel free to correct me.
It helps clarify what the number is about.
1. Log in to RA, read the status bar.
2. Trigger the login notification (no idea how you're supposed to do that).
=> UI: Add the "points" unit in some RA-related strings

pcsx2/GS/GSState.h, pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX11/GSDevice11.h, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h, pcsx2/GS/Renderers/Metal/GSDeviceMTL.h, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.h, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h
Fix up and optimise some stuff with the new RTA correction stuff.
There were cases that could cause a decorrect where we could adjust the new data in-line, plus some other small optimisations.
Follow up from https://github.com/PCSX2/pcsx2/pull/10853
Smoke test mostly, dump run seems fine. No fixes/breaks.
=> GS/HW: Optimize RTA correction to reduce copies

pcsx2-qt/LogWindow.cpp, pcsx2-qt/LogWindow.h
Backport from Duckstation.
Fixes #10939 
It's silly.
Make sure you can't close the log window from the task bar.
=> Qt: Fix closing log window via taskbar

bin/resources/GameIndex.yaml
Add full mipmap with ps2 trilinear to Global Storm:
- Fixes ground textures.
Add missing autoflush fixes to other regions of Terminator 3 The Redemption:
- Fixes environment lights visible through player model.
Fixes https://github.com/PCSX2/pcsx2/issues/10947
Helps https://forums.pcsx2.net/Thread-Bug-Report-Conflict-Global-Storm-SLES-52573
Test the dumps provided on the issues.
It seems that preload frame helps Global Storm with some white borders but that needs to be verified while playing the game.
=> GameDB: Add some gshw fixes.

pcsx2-qt/SetupWizardDialog.ui
Since the links for the docs has been changed, update the link on the setup wizard.
Also makes the text looks a bit more nicer.
Preview:
Usability and Eye Candy 100
See if the text shows up properly and the link opens correctly
=> Qt: Update docs link on setup wizard

pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.h
Regression from #10949.
Silly me for thinking `QGuiApplication::quit()` couldn't get cancelled by the log window being closed first...
=> Qt: Fix main window stuck open after update

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Stops it correcting RTA's that can't be corrected.
Mistake from 1.7.5625 (#10941) causing it to try to correct targets which can't be corrected.
Already checked.
Fixes poor performance in NFS Most Wanted (and probably other games with high Alphas)
=> GS/HW: Make sure RTA doesn't correct when it can't

pcsx2-qt/MainWindow.cpp, pcsx2-qt/MainWindow.ui
Did this for duckstation a while back, forgot to backport.
Before:
After:
Check mac main window.
=> Qt: Enable unifiedTitleAndToolBarOnMac for main window

.github/workflows/macos_build.yml, .github/workflows/scripts/macos/build-dependencies.sh, pcsx2/CMakeLists.txt, tests/ctest/core/CMakeLists.txt
GitHub recently enabled M1 runners for public projects. They bring a considerable speed boost to CI runtimes, DuckStation went from 15mins+ down to 3mins after switching.
Can't use MoltenVK from brew anymore, because that's going to be arm64. So, build it ourselves as part of the deps package. It doesn't take long on M1 :-).
Only caveat is now we're building on ARM, so we have to be careful and make sure we actually create an x86 build. Luckily I'd already done most of this so I could run the x86 build script on my Macbook.
Vroom vroom.
Test Mac builds ~~, once I actually get it working. I have a feeling it's going to explode at first~~ .
=> CI: Swap to MacOS 14 runner

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Compare dirty rects within valid rect bounds when checking for merging.
Some games send dirty rects which are larger than the valid area of the texture, however they can vary in size, meaning our check to see if it should be joined to the existing dirty rect will fail.  This does mean the dirty rect will become bigger, but it won't go beyond the size of the texture, which is fine. But this means our "fully dirty rect" check will work and properly invalidate old targets.
Test Metal Gear Solid 3 call transition.
Fixes #10951
Master:
PR:
=> GS/HW: Compare dirty rects by valid bounds

pcsx2/GS/GSState.cpp
Checks both edges of the current triangle during quad check
When using DX and VK they can have different settings for "provoking vertex", meaning the first and last point can be swapped, this was causing the quad check to fail as the first vert wasn't connected to the previous triangle. In Transformers on DX, this meant that it ended up using an image from a previous draw as depth.
Smoke test mostly.
Splinter Cell - Chaos Theory:
Master:
PR:
Transformers:
Master:
PR:
=> GS/HW: Check both edges of current triangle for quads

pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/GS/Renderers/Metal/GSTextureMTL.mm, pcsx2/GS/Renderers/Metal/convert.metal, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Fixes an issue where textures would be the wrong size when upscaling
Also treat rta flag like a bit instead of an offset, as that's how we use it
Less broken
Test [rc2scale.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/14751708/rc2scale.gs.xz.zip)
=> Fix RTA when upscaling on Metal

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Detect when the width of a shuffle isn't a multiple of the original texture size and handle resized shuffles.
Superman Shadow of Apokolips does a shuffle where it decides to do 1024x529 instead of 640x448 which is the original screen size, so this isn't double in either direction which shuffles normally are (because this is done in 16bit on a 32bit target)
Smoke test and Superman,.
Fixes https://github.com/PCSX2/pcsx2/issues/10908
Master:
PR:
=> GS/HW: Detect shuffles reshaping the target

pcsx2/GS/GSClut.cpp, pcsx2/GS/GSClut.h, pcsx2/GS/GSState.cpp
CLUT wasn't force reloaded, so if the game didn't write to TEX0 before its first draw after loading a state, you got either the CLUT before the state was loaded, or random/uninitialized garbage.
Do the same for reset as well, except zero it out in that case.
We probably should save the CLUT to the GS state, rather than force reloading it for 100% determinism... but I might leave that to refraction, since he knows that code much better than myself.
Stopping GS dump runs from being inconsistent on certain dumps.
Test saving and loading state.
=> GS: Improve state load determinism

pcsx2/GS/Renderers/Metal/tfx.metal
GS/Metal: Fix Wunused-const-variable warning.
Less warnings.
CI compiles.
=> GS/Metal: Fix Wunused-const-variable warning.

pcsx2/GS/GS.cpp, pcsx2/GS/GS.h, pcsx2/GS/GSUtil.cpp, pcsx2/GS/GSUtil.h, pcsx2/MTGS.cpp, pcsx2/VMManager.cpp
The PSM mappings can be determined at compile time, instead of runtime.
This renders init/shutdown redundant.
Less code, fewer plugin memories.
Smoke test.
=> GS: Purge GSinit() and GSshutdown()

.gitignore, pcsx2/Pcsx2Config.cpp, updater/Updater.cpp
allows the use of portable.txt as well as portable.ini 
on some OS's  it may be difficult to create ini files  automatically , thus makes its  more easier for the users on this OS to create the portable file 
create a portable.txt /.ini and make sure portable mode works 
updater needs checked
=> Config: Allow the use of portable.txt

bin/resources/shaders/opengl/convert.glsl, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/opengl/tfx_vgs.glsl, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/Metal/GSDeviceMTL.mm, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Remove checks for unused features.
Clip control is supported even by VMware (despite not being core until 4.5), and without it, depth accuracy was garbage anyway.
Fewer runtime checks.
Smoke test all renderers.
=> GS: Cleanup unused features

pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp
Ensure blending is disabled when colormask is zero.
Intel's (older) DX11 drivers apparently crash the GPU when SRC1_COLOR is used in blend, when the shader doesn't output it, even though it's not being written.
It was also missing entirely for OpenGL.
Fixing Intel GPU hang.
Smoke test.
Fixes DX11 crashing on intel on Persona 3 FES.
Fixes OpenGL crashing on intel on Persona 3 FEs.
Fixes OpenGL shader macros crashing on intel.
=> GSDevice: Improve IsEffective() test

pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp
ALT+ENTER wasn't getting correctly disabled, which caused DXGI to freak out.
Spec violation.
Test ALT+ENTER on DX11/DX12.
=> GS/DX: Fix ALT+ENTER causing mode switch

bin/resources/shaders/common/fxaa.fx, pcsx2/GS/Renderers/DX11/D3D.cpp, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX11/GSDevice11.h
Since I removed optional clip-control, apparently some GPUs from the mesozoic era can no longer run PCSX2.
DX11 feature level 10 is going to be better than GL on these GPUs, if anything even runs at all, because at least the depth is correct. GL provides no benefit, since texture barrier isn't supported, so no SW blend.
But add a warning, because we can't fix any bugs that happen on these setups.
Digging for fossils?
Make sure DX11 still works.
=> GS/DX11: Re-enable FL10 support with a warning

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Round up lookup rects to the ceiling block, but without the TextureMinMax adjustment.  Also clean up the Tex in RT check and general formatting in the texture cache file.
Also fix up some shuffle behaviour to fix some issues when the texture can't be the framebuffer (like no barriers)
This is one thing that's been a bit of a bane for us, the cleaning up was just something I wanted to do.
Shuffles had problems with copying the framebuffer correctly and setting the coordinates/copy area, this fixes that up.
Test many games, especially ones which use Tex in RT, make sure they're no worse.
Fixes Godfather (for reals)
Also fixes Godfather and 007 Russia With Love on Direct3D and probably Metal too.
Corrects the minimap on Steambot and PachiPara 13
Godfather:
Master:
PR:
PachiPara 13:
Master: …
=> GS/HW: Round lookup rect to block boundary and improve overlap check. Fix up shuffle behaviour (Mostly Direct3D)

pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.h, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
I got blamed for breaking Brave, but turns out my clear fix just masked the real issue :cry:
Fixes shadows in Brave, how many times I don't know now.
(spike in the bottom left of the shadow)
Smoke test.
Check Brave if you have it.
=> GS/Vulkan: Fix incorrect clear colour for fast colclip

pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Avoid deleting depth targets on shuffles
Bee Movie does a weird size to a shuffle (essentially 640x448 over a 512x512) and it was deleting the depth target when it was attached to the source, but we shouldn't really be deleting targets on shuffles, the was causing null exceptions later on, which crashed PCSX2, not to mention broke the graphics.
Smoke test mostly and Bee Movie. Dump run was fine.
Fixes #11004
Bee Movie:
Master:
PR:
=> GS/HW: Avoid deleting depth targets on shuffles

pcsx2-qt/MainWindow.cpp, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h
Yay race conditions
Fixes #10995
Test closing with BP mode active
=> Qt: Fix crash on shutdown with BP mode open

pcsx2-qt/MainWindow.cpp, pcsx2-qt/QtHost.cpp, pcsx2-qt/QtHost.h, pcsx2/GS/Renderers/Common/GSRenderer.cpp
Fixes renderer information getting stuck blank when switching renderers, or loading GS dumps.
Also replaces the "previous" resolution being displayed with "No Image" if PCRTC displays are off.
Closes #11006.
@JordanTheToaster knows what to do.
=> Qt: Fix vanishing status bar renderer info

pcsx2/GS/GSState.cpp, pcsx2/GS/GSState.h, pcsx2/GS/Renderers/HW/GSHwHack.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Stops alpha from unused CLUT colours from leaking into the alpha range, saves a good number of draw calls on many games, and some RTA conversions.
Some small render fixes in Urban Chaos (lighting), Tomb Raider (lighting), NBA (bandanna), Sims Bustin Out/Urbz (shadows).
Some notable mentions:
```
EA_Sports_Rugby_2004_SLES-51732_20220817213743 ['Draw Calls: -1228 [5360=>4132]']
Grand Theft Auto - San Andreas_SLUS-20946_20231011210201 ['Draw Calls: -569 [2222=>1653]']
Manhunt_SLUS-20827ugh ['Draw Calls: -224 [884=>660]']
Mark of Kri, The_SCUS-97140_20221211064922 ['Draw Calls: -184 [601=>417]', 'Barriers: -3 [5=>2]']
Metal Gear Solid 3 - Snake Eater_SLES-82024_20231022135932 ['Draw Calls: -284 [1015=>731]', 'Barriers: -4 [32=>28]']
Metal Gear Solid 3 - Subsistence …
```
=> GS/HW: Compute source alpha min/max based on texture instead of CLUT

bin/resources/shaders/dx11/convert.fx, bin/resources/shaders/opengl/convert.glsl, bin/resources/shaders/vulkan/convert.glsl, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.h, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/Metal/convert.metal
Fix up some RTA behaviour and reduce the number of copies
Also correct the valid size when preloading from GS memory (and using uploaded data)
There were places where it was doing RTA correction where it didn't need to, especially for 24 bit targets where the alpha doesn't exist, but also some times when the alpha was actually zero before the draw and non-zero after, but because we were updating it, it was doing it the copy way.
Test games, especially Shadow Hearts - Covenant
Fixes #10999
Fixes #10979
Shadow Hearts:
Master:
PR;
=> GS/HW: Fix up RTA correction behaviour and preloading valid areas

pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp
Fixes the priority inversion issue of precaching textures blocking textures required, delaying high res textures until after all precached textures have been loaded.
Not that anyone should be using precache anyway, but for those who do (maybe super potato HDDs with lots of RAM, seems unlikely), it'll work as expected.
Also fixes the issue of dumping blocking loading, if you're loading+dumping at the same time.
See above.
Check texture loading with async and precache.
=> GS/HW: Prioritize loading required replacement textures over precache

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Avoids reading indexed data from a target if the area completely overlaps (meaning there was an upload)
There were false positives and breaks in some games due to it reading this out of targets. Plus these changes saved a few uploads.
Test a smattering of games including those listed below.
Fixes WW1 - Red Baron
Master:
PR:
Other changes shown in the GS dump run
catwoman_ghost
Draw Calls: +7 [381=>388]
Render Passes: +2 [124=>126]
Uploads: +3 [40=>43]
cod2
Draw Calls: -12 [93=>81]
Render Passes: -21 [54=>33]
Copies: -8 [9=>1]
Uploads: -7 [40=>33]
Crime_Life_-_Gang_Wars__PAL-M5__SLES-52122
Draw Calls: -3 [398=>395]
Render Passes: -4 [78=>74]
Copies: -2 [20=>18]
Uploads: -3 [29=>26]
Fight Night - Round 3_SLUS-21383_20220618124952
Draw Calls: -2 [839=>837]
Render Passes: -3 [27=>24]
Copies: …
=> GS/TC: Read indexed texture from GS memory if complete dirty overlap

common/CMakeLists.txt, common/CrashHandler.cpp, common/FileSystem.cpp, common/FileSystem.h, common/Windows/WinMisc.cpp, pcsx2/CDVD/GzippedFileReader.cpp, pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/windows/FlatFileReaderWindows.cpp, updater/Updater.cpp, updater/UpdaterExtractor.h, updater/Windows/WindowsUpdater.cpp
Another DuckStation backport. Win32 API won't accept paths longer than 260 characters, unless you use the literal prefix, which requires a bit of preprocessing, especially with UNC paths.
Prepend the prefix on all our path functions, which thankfully mostly go through the FileSystem class.
Make PCSX2 work in whacky setups, rather than silently failing.
Make sure file functionality works. e.g. folder memcards, screenshots, game scanning.
=> FileSystem: Handle paths longer than MAX_PATH on Windows

common/Error.cpp, common/Error.h, common/FileSystem.cpp, common/FileSystem.h, common/MemorySettingsInterface.cpp, common/MemorySettingsInterface.h, common/SettingsInterface.h, pcsx2-gsrunner/Main.cpp, pcsx2-qt/QtHost.cpp, pcsx2/Config.h, pcsx2/INISettingsInterface.cpp, pcsx2/INISettingsInterface.h, pcsx2/LayeredSettingsInterface.cpp, pcsx2/LayeredSettingsInterface.h, pcsx2/Pcsx2Config.cpp
Stops users from losing data when they somehow don't have a writable documents directory...
Make sure setup process works.
Make sure existing setups still load.
=> Qt: Ensure settings are writable before running setup wizard

.github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/linux/flatpak/modules/20-sdl2.json, .github/workflows/scripts/macos/build-dependencies.sh, .github/workflows/scripts/windows/build-dependencies.bat, cmake/SearchForStuff.cmake
Hot off the press.
Old Qt versions aren't supported.
Make sure basic functionality still works.
Make sure gamepads still work.
=> Deps: Update to Qt 6.7.0 and SDL 2.30.2

pcsx2-qt/QtHost.cpp
Null pointer dereference.
Crash bad.
Obvious issue. CI passes.
=> Qt: Fix crash on shutdown settings save

3rdparty/imgui/CMakeLists.txt, 3rdparty/imgui/imgui.vcxproj, 3rdparty/imgui/imgui.vcxproj.filters, 3rdparty/imgui/include/imconfig.h, 3rdparty/imgui/include/imgui.h, 3rdparty/imgui/include/imgui_freetype.h, 3rdparty/imgui/include/imgui_internal.h, 3rdparty/imgui/include/imgui_stdlib.h, 3rdparty/imgui/include/imstb_textedit.h, 3rdparty/imgui/src/imgui.cpp, 3rdparty/imgui/src/imgui_demo.cpp, 3rdparty/imgui/src/imgui_draw.cpp, 3rdparty/imgui/src/imgui_freetype.cpp, 3rdparty/imgui/src/imgui_stdlib.cpp, 3rdparty/imgui/src/imgui_tables.cpp, 3rdparty/imgui/src/imgui_widgets.cpp, 3rdparty/imgui/src/imstb_truetype.h, bin/docs/ThirdPartyLicenses.html, cmake/SearchForStuff.cmake, common/vsprops/LinkPCSX2Deps.props, pcsx2-qt/QtHost.cpp, pcsx2/Achievements.cpp, pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiFullscreen.cpp, pcsx2/ImGui/ImGuiManager.cpp
Updates imgui dependency to v1.90.4, and re-applies local modifications.
Enables the FreeType rasterizer, now that we have that as a dependency, for improved font rendering, particularly at small sizes.
Before:
After:
See above.
Make sure big picture mode still functions as expected.
Make sure OSD still works.
=> 3rdparty/imgui: Update to v1.90.4

bin/resources/shaders/dx11/tfx.fx, pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/DX11/GSDevice11.cpp, pcsx2/GS/Renderers/DX12/GSDevice12.cpp, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/OpenGL/GSDeviceOGL.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
Allows us to blend Cd with alpha range of 0-2 instead of 0-1. Not all Cd cases are covered, but it's a good start.
Second best scenario, something between sw rendering and previous hw rendering, there may be a slight performance impact, but nothing like reading the framebuffer.
Also allows us to do Ad cases where we can double the blend to get the
proper blend result since Ad range is 0-1 instead of 0-2.
Make hw blending suck even less, will help Direct3D.
Test various of games that previously were broken on Direct3D or needed higher blending on Direct3D.
This won't affect Vk/GL unless we turn off barriers, so the same games can be smoke test on them just to know nothing broke.
There's 2 dumps I need to check and make sure they aren't actually broken so don't merge, image comparisons of …
=> GS/HW: Add support for blend second pass for hw blending.

bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/Metal/tfx.metal, pcsx2/ShaderCacheVersion.h
Enables colour rearranging on shuffle on SW blend or TFX (not decal)
The colour can be modulated by the vertex colour, which means that the incoming colour will be wrong, this was happening on Ratchet & Clank Up Your Arsenal.
Test Ratchet & Clank UYA, and a smattering of other games.
Ratchet:
Master:
PR:
=> GS/HW: Rearrange color on shuffle if SW Blend or TFX

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
Cleanup EmulateBlending a bit more.
Cleaner code, the pabe condition is useless as it was only hit during minimum blend, otherwise blend mix supports alpha > 128.
=> GS/HW: Cleanup EmulateBlending a bit more.

common/Console.h, pcsx2/PrecompiledHeader.h
Works around GCC issues that were breaking builds
We don't officially support GCC but it would be nice if the builds didn't fail completely
Build a debug build with GCC
=> Fix GCC builds

bin/resources/GameIndex.yaml
Harry potter Half blood
Full blending, problems with current HPO Works, instantDMA or patches to avoid crash in FMV, also align sprite to avoid new issue.
- Log when it freezes:
- HW Master:
- HW PR with new fixes:
- Software renderer:
Soukou Kihei Votoms
- HW Master:
- HW PR with new fixes:
- Software renderer:
Align Sprite, Align to native, Autoflush
Harry PotterPrisoner of Azkaban
Full slow blending for better lighting
- HW Master:
- HW PR with new fixes:
Titeuf
Autoflush sprites only for sun through building (sun occlusion)
- HW Master:
- HW PR with new fixes:
Rygar, Align to native for better aligned and better shadows
- HW Master:
- HW PR with new fixes:
- Software Renderer:
Ruff trigger:
- HW PR with new fixes:
- HW PR with new fixes:
- Software Renderer:
Automatic shit is what …
=> GameDB:Bigger blob of various fixes

pcsx2-qt/Debugger/CpuWidget.cpp, pcsx2-qt/Debugger/CpuWidget.h, pcsx2-qt/Debugger/DebuggerWindow.cpp, pcsx2-qt/Debugger/DebuggerWindow.h, pcsx2-qt/Debugger/DisassemblyWidget.cpp, pcsx2-qt/Debugger/Models/BreakpointModel.cpp, pcsx2-qt/MainWindow.cpp, pcsx2/DebugTools/Breakpoints.cpp, pcsx2/DebugTools/Breakpoints.h, pcsx2/DebugTools/DebugInterface.cpp, pcsx2/VMManager.cpp
This PR fixes numerous issues related to the debugger:
1. Fixes an use-after-free where breakpoints were updated after DebuggerWindow shut down already.
2. Adds a Hardcore Mode disable prompt when starting Boot and Debug with HC enabled.
3. Marks addresses `< 0xBFC00000` as invalid, fixing asserts in Debug and possible crashes in Release (by @F0bes).
4. Fixes numerous data races in the code, such as:
* Unbinding a debug interface update CB while it's in use, causing a possible use-after-free.
* Binding breakpoints via the disassembly widget that would read a stale local variable, and bind the breakpoint to a bogus address.
Stability good.
1. Test Boot and Debug with Hardcore Mode **disabled**.
2. Test Boot and Debug with Hardcore Mode **enabled**.
3. Test binding and unbinding breakpoints …
=> Debugger: Stability improvements

pcsx2/ImGui/ImGuiFullscreen.cpp
*For those of you fine folks who doesn't like to be in the dark, here's a present...*
This PR tweaks the color scheme of BPM's Light Mode to be less bright, with less saturated blue accent color, and no more eye-burning.
Hopefully less retinas being burned.
See if it looks good.
=> BPM: Light Mode color scheme update

.github/workflows/scripts/common/shaderc-changes.patch, .github/workflows/scripts/linux/build-dependencies-qt.sh, .github/workflows/scripts/linux/flatpak/modules/20-sdl2.json, .github/workflows/scripts/linux/flatpak/modules/22-shaderc.json, .github/workflows/scripts/linux/flatpak/net.pcsx2.PCSX2.json, .github/workflows/scripts/macos/build-dependencies.sh, .github/workflows/scripts/windows/build-dependencies.bat, common/Image.cpp, pcsx2-qt/QtKeyCodes.cpp, pcsx2-qt/SettingWidgetBinder.h, pcsx2-qt/Settings/AchievementSettingsWidget.cpp, pcsx2-qt/Settings/AudioSettingsWidget.cpp, pcsx2-qt/Settings/BIOSSettingsWidget.cpp, pcsx2-qt/Settings/ControllerGlobalSettingsWidget.cpp, pcsx2-qt/Settings/DEV9SettingsWidget.cpp, pcsx2-qt/Settings/DEV9SettingsWidget.h, pcsx2-qt/Settings/DebugSettingsWidget.cpp, pcsx2-qt/Settings/EmulationSettingsWidget.cpp, pcsx2-qt/Settings/GameCheatSettingsWidget.cpp, pcsx2-qt/Settings/GameListSettingsWidget.cpp, pcsx2-qt/Settings/GamePatchSettingsWidget.cpp, pcsx2-qt/Settings/GraphicsSettingsWidget.cpp, pcsx2-qt/Settings/InterfaceSettingsWidget.cpp, pcsx2-qt/Settings/MemoryCardSettingsWidget.cpp, pcsx2-qt/SetupWizardDialog.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h, pcsx2/GS/Renderers/Vulkan/VKShaderCache.cpp
- Gates the generation of non-semantic debug info behind the extension being present. Fixes the validation error.
- Swaps Flatpak to using CMake for building SDL2, like the AppImage.
- Uses Release build type for Flatpak's shaderc.
- Bump Flatpak to Qt 6.7.
- Fix deprecation warnings from Qt 6.7.
- Changed QCheckBox `stateChanged()` signals to `checkStateChanged()` - the latter is strongly typed.
- Fixes libpng/libjpeg on Windows in Debug builds.
Chores.
Make sure checkboxes in UI still works.
Make sure Vulkan renderer still works.
Test saving PNG and JPEG screenshots.
=> Chores: VK validation fixes, Qt 6.7 deprecation fixes, Flatpak build consistency

pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp
glslang generates debug info instructions before phi nodes at the beginning of blocks when non-semantic debug info is enabled, triggering errors by spirv-val. Gate it by an environment variable if you want source debugging until this is fixed.
Apparently meme distro's validation layers crash with it...
CI passes.
=> GS/Vulkan: Add env var for non-semantic debug info

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Devil May Cry is pretty whacky. It copies the framebuffer at FBP 0x0 to 0x1400 (at the full size...), then draws the subtitle on the copied framebuffer. But it only copies the bottom chunk of it, not the whole thing (512x32 in this example). And it doesn't copy it with a draw, it copies it with a move.
Then it uses the PCRTC to blend the two framebuffers together. Currently, this falls apart, because the heuristic to create a new target via move relies on the destination offset being zero. Which is isn't here, because it's only copying the bottom part of the FB.
So, leverage the hash cache to allow previously-known targets to be created for moves, which means it all happens in hardware (no readback), and preserves upscaling. We also have to inject the clears into the hash cache as well, …
=> GS/HW: Allow creation of known targets via move with offset

pcsx2-qt/Settings/DEV9SettingsWidget.cpp, pcsx2-qt/Settings/DEV9SettingsWidget.ui, pcsx2-qt/Settings/InterfaceSettingsWidget.ui
Moves some widgets around to free up approximately 30 pixels of height in the settings window, so it can fit on displays for users unfortunate enough to still be using a 768p display.
=>
=>
Less user cry cry.
Make sure settings dialog looks okay.
=> Qt: Shrink settings window by ~30 pixels

pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Try to avoid deleting targets which haven't been overlapped or dirtied.
Some games will preload some information then not touch it until after the game loads, but we eject things that haven't been used for 300ish frames, so sometimes this data can be ejected.
Same can happen for games if you spend too long in a pause screen/menu, causing the game to corrupt when you go back. An example of this may be using the shop in the Ratchet games, or changing the background in King's Field 4, then back again after waiting.
Try games you think suffer from above, it might help.
Fixes #7332
=> GS/HW: Try to keep old targets around without overlap or dirty areas

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
GS/HW: Ensure tex shuffles, masking are render target draws.
Fixes Castlevania Curse of Darkness crashing.
Check the dump if it still crashes on dx.
https://cdn.discordapp.com/attachments/923492653788692480/1229064937050214411/Castlevania_-_Curse_of_Darkness_SLUS-21168_20240414104422.gs.zst?ex=662e52eb&is=661bddeb&hm=f5572bbdaa1d68da4a12061542428427e5d44899be3b6f06f604388283f034c1&
Smoke test, no diffs showed up.
Edit: tested and crash is fixed.
=> GS/HW: Ensure tex shuffles, masking are render target draws.

pcsx2/VMManager.cpp
`VMManager` will log an ELF's entry point to the console prefixed with `0x`, but the actual value is not formatted in hexadecimal.
The value was clearly intended to be formatted in hexadecimal but the `:08X` format specifier was left out by mistake.
=> VMManager: Log entry point in hexadecimal

pcsx2/ImGui/FullscreenUI.cpp, pcsx2/Pcsx2Config.cpp
Config/FullscreenUI: Properly disable GPU Palette Conversion.
When manual hardware fixes are disabled.
Fixes https://github.com/PCSX2/pcsx2/issues/11029
Test https://github.com/PCSX2/pcsx2/issues/11029
=> Config/FullscreenUI: Properly disable GPU Palette Conversion.

pcsx2/GS/GS.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.h
Since we have the RT alpha range, we can potentially reduce the range of the CLUT that's used to determine the source alpha min/max.
Unfortunately, in the few games I looked at, they were all 0/255 anyway, so it doesn't really help much.
But it did for True Crime: NYC, which enables RTA, and knocks off up to 700 barriers depending on the scene.
Small wins add up.
Smoke test, runner says we good.
=> GS/HW: Cross-reference RT alpha with CLUT for P8H/P4HL/P4HH

pcsx2/DEV9/ATA/ATA_Info.cpp, pcsx2/DEV9/ATA/ATA_State.cpp, pcsx2/DEV9/ATA/HddCreate.cpp, pcsx2/DEV9/DEV9.cpp
Fix inconsistent log formats
Remove a pointless log that always printed `0`
Only log the HDD file path if HDD is enabled
Consistency in logs
Logging the HDD path when HDD is off is unneeded.
Look at logs with and without HDD enabled
=> DEV9: Adjustments to HDD logs

pcsx2/ImGui/FullscreenUI.cpp, pcsx2/ImGui/ImGuiOverlays.cpp
what the title says
boom 
try double clicking in the display area while the save state selector (function keys) is open
=> ImGuiOverlays: Fix possible crash in save state selector

pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/GS/Renderers/HW/GSTextureCache.cpp
Fixes an RTA bug with depth textures , but also fixes some other bugs (which some how didn't affect things) along the way
Previous depth dstmatch code was incorrect, causing bugs.
Fixes Area 51, nothing else showed in dump run
Area 51:
Master:
PR:
=> GS/HW: Fix some small errors updating depth in RT targets

pcsx2-qt/Debugger/DebuggerWindow.ui
Disables the context menu for the toolbar in the debugger window.
Fixes #10473
See if you can hide the toolbar.
=> Debugger: Disable the debugger toolbar ctx menu

pcsx2/DEV9/Sessions/TCP_Session/TCP_Session.h, pcsx2/DEV9/Sessions/TCP_Session/TCP_Session_Out.cpp
Better track PS2's sequence number when closing connection
Previous code didn't properly validate PS2's sequence number when handling connection closing packets
Test networking games using sockets
=> DEV9: Refine tracking of PS2's TCP sequence numbers during connection closing

pcsx2/GS/GSPng.cpp
=> GS: Fix crash and file leak during dump

bin/resources/shaders/dx11/tfx.fx, bin/resources/shaders/opengl/tfx_fs.glsl, bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Common/GSDevice.cpp, pcsx2/GS/Renderers/Common/GSDevice.h, pcsx2/GS/Renderers/HW/GSRendererHW.cpp, pcsx2/ShaderCacheVersion.h
GS/HW: Extend blend second pass to more blend formulas.
`Cs + Cd*Ad, Cs - Cd*Ad, Cd*(1 - Ad), Cs*(1 + Ad), Cs*(1 - Ad).`
More accuracy on basic blend on dx.
Test scarface, mgs3, tokyo extreme racer.
Eye Candy:
Scarface, master vs pr dx basic blend:
=> GS/HW: Extend blend second pass to more blend formulas.

bin/resources/shaders/vulkan/tfx.glsl, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp, pcsx2/GS/Renderers/Vulkan/GSDeviceVK.h, pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp, pcsx2/ShaderCacheVersion.h
Apparently this causes GPU crashes on RDNA3, and didn't provide any tangible benefit for NVIDIA.
I'll replace this at some point with dynamic rendering local reads, either before or after the GPUDevice transition.
Might fix the crashes on RDNA3.
Compare performance in barrier-heavy games on NVIDIA, make sure it is unaffected.
See if it fixes the GPU crashes on RDNA3.
=> GS/Vulkan: Drop feedback loop extension

pcsx2/GS/Renderers/HW/GSRendererHW.cpp
In some games (e.g. True Crime: NYC), we're uploading the contents of memory to targets even though they're being cleared.
So... don't do that.
Decent upload saving.
Smoke test, runner says it's okay. Maybe check TC: NYC.
=> GS/HW: Clear dirty list on target clear

pcsx2/GS/GSLzma.cpp, pcsx2/GS/GSLzma.h
Moves the file handle to a base GSDump class and makes it managed, to make it impossible to miss closing it again.
Playing back LZMA dumps leaked the file handle.
1. Launch PCSX2.
2. Play back any LZMA GSDump and shut it down without shutting down PCSX2.
3. Observe that it is now possible to delete the dump from disk without shutting down PCSX2, long as the dump is not running of course. Without this PR, PCSX2 must be entirely closed to allow to close the file.
=> GSLzma: Fix a file handle leak in GSDumpLzma
